# Generated by Django 6.0.3 on 2026-09-11 17:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0009_workspace_role_identity'),
        ('party', '0002_enable_workspace_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_name', models.CharField(max_length=255)),
                ('source_type', models.CharField(max_length=8)),
                ('source_system', models.CharField(max_length=120)),
                ('source_sha256', models.CharField(max_length=64)),
                ('source_bytes', models.PositiveIntegerField()),
                ('contract_version', models.CharField(default='party-master/1', max_length=32)),
                ('headers', models.JSONField(default=list)),
                ('mapping', models.JSONField(default=dict)),
                ('summary', models.JSONField(default=dict)),
                ('approval_digest', models.CharField(blank=True, max_length=64)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('state', models.CharField(choices=[('NEEDS_MAPPING', 'Needs mapping'), ('READY', 'Ready'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='NEEDS_MAPPING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('committed_at', models.DateTimeField(null=True)),
                ('committed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartyIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_identity', to='party.party')),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row', models.PositiveIntegerField()),
                ('raw', models.JSONField(default=dict)),
                ('canonical', models.JSONField(default=dict)),
                ('issues', models.JSONField(default=list)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('disposition', models.CharField(default='UNVALIDATED', max_length=16)),
                ('committed_at', models.DateTimeField(null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rows', to='data_portability.importbatch')),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company')),
                ('identity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_rows', to='data_portability.partyidentity')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('workspace', 'batch', 'source_row'), name='port_batch_row_uniq')],
            },
        ),
        migrations.CreateModel(
            name='SourceIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_system', models.CharField(max_length=120)),
                ('external_id', models.CharField(max_length=255)),
                ('accepted_digest', models.CharField(max_length=64)),
                ('local_digest', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='data_portability.partyidentity')),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('workspace', 'source_system', 'external_id'), name='port_source_identity_uniq')],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceNamespace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('workspace',), name='port_namespace_workspace_uniq')],
            },
        ),
    ]
