# Generated by Django 6.0.3 on 2026-09-12 01:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_portability', '0002_workspace_guards'),
        ('orgs', '0009_workspace_role_identity'),
        ('party', '0002_enable_workspace_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('profile', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_identity', to='party.partyaddress')),
                ('contact', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_identity', to='party.partycontactmethod')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='children', to='data_portability.partyidentity')),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='importrow',
            name='child_identity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_rows', to='data_portability.childidentity'),
        ),
        migrations.CreateModel(
            name='ChildSourceIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=32)),
                ('source_system', models.CharField(max_length=120)),
                ('external_id', models.CharField(max_length=255)),
                ('accepted_digest', models.CharField(max_length=64)),
                ('local_digest', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='data_portability.childidentity')),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('workspace', 'profile', 'source_system', 'external_id'), name='port_child_source_uniq')],
            },
        ),
    ]
