# Generated by Django 6.0.3 on 2026-09-12 01:54

import django.db.models.deletion
from django.db import migrations, models


SQL = """
CREATE OR REPLACE FUNCTION portability_child_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN RAISE EXCEPTION 'Child provenance cannot be deleted'; END IF;
    IF TG_OP = 'UPDATE' AND NEW.workspace_id <> OLD.workspace_id
    THEN RAISE EXCEPTION 'Child ownership is immutable'; END IF;
    IF TG_TABLE_NAME = 'data_portability_childidentity' THEN
        IF TG_OP = 'UPDATE' AND (
            (NEW.public_id,NEW.parent_id,NEW.profile,NEW.created_at) IS DISTINCT FROM
            (OLD.public_id,OLD.parent_id,OLD.profile,OLD.created_at)
            OR (NEW.contact_id IS NOT NULL AND NEW.contact_id IS DISTINCT FROM OLD.contact_id)
            OR (NEW.address_id IS NOT NULL AND NEW.address_id IS DISTINCT FROM OLD.address_id)
            OR (NEW.identifier_id IS NOT NULL AND NEW.identifier_id IS DISTINCT FROM OLD.identifier_id))
        THEN RAISE EXCEPTION 'Child identity cannot be rebound'; END IF;
        IF NOT EXISTS (SELECT 1 FROM data_portability_partyidentity p
            WHERE p.id=NEW.parent_id AND p.workspace_id=NEW.workspace_id)
        THEN RAISE EXCEPTION 'Child parent must share Workspace'; END IF;
        IF NEW.profile NOT IN ('party-contact/1','party-address/1','party-identifier/1')
            OR (NEW.profile='party-contact/1' AND NEW.address_id IS NOT NULL)
            OR (NEW.profile='party-address/1' AND NEW.contact_id IS NOT NULL)
            OR (NEW.profile <> 'party-identifier/1' AND NEW.identifier_id IS NOT NULL)
            OR (NEW.profile='party-identifier/1' AND (NEW.contact_id IS NOT NULL OR NEW.address_id IS NOT NULL))
            OR (TG_OP='INSERT' AND NEW.contact_id IS NULL AND NEW.address_id IS NULL AND NEW.identifier_id IS NULL)
        THEN RAISE EXCEPTION 'Child profile and target must match'; END IF;
        IF NEW.contact_id IS NOT NULL AND NOT EXISTS (
            SELECT 1 FROM party_partycontactmethod c JOIN data_portability_partyidentity p ON p.party_id=c.party_id
            WHERE c.id=NEW.contact_id AND c.workspace_id=NEW.workspace_id AND p.id=NEW.parent_id)
        THEN RAISE EXCEPTION 'Contact must share Party and Workspace'; END IF;
        IF NEW.address_id IS NOT NULL AND NOT EXISTS (
            SELECT 1 FROM party_partyaddress c JOIN data_portability_partyidentity p ON p.party_id=c.party_id
            WHERE c.id=NEW.address_id AND c.workspace_id=NEW.workspace_id AND p.id=NEW.parent_id)
        THEN RAISE EXCEPTION 'Address must share Party and Workspace'; END IF;
        IF NEW.identifier_id IS NOT NULL AND NOT EXISTS (
            SELECT 1 FROM party_partyidentifier c JOIN data_portability_partyidentity p ON p.party_id=c.party_id
            WHERE c.id=NEW.identifier_id AND c.workspace_id=NEW.workspace_id AND p.id=NEW.parent_id)
        THEN RAISE EXCEPTION 'Identifier must share Party and Workspace'; END IF;
    ELSIF TG_TABLE_NAME = 'data_portability_childsourceidentity' THEN
        IF TG_OP <> 'INSERT' THEN RAISE EXCEPTION 'Child source evidence is immutable'; END IF;
        IF NOT EXISTS (SELECT 1 FROM data_portability_childidentity c
            WHERE c.id=NEW.identity_id AND c.workspace_id=NEW.workspace_id AND c.profile=NEW.profile)
        THEN RAISE EXCEPTION 'Child source must share Workspace and profile'; END IF;
    END IF;
    RETURN NEW;
END $$;
CREATE OR REPLACE FUNCTION portability_child_tombstone_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF OLD.contact_id IS NOT NULL AND NEW.contact_id IS NULL AND EXISTS (
        SELECT 1 FROM party_partycontactmethod WHERE id=OLD.contact_id)
    THEN RAISE EXCEPTION 'A live contact identity cannot be detached'; END IF;
    IF OLD.address_id IS NOT NULL AND NEW.address_id IS NULL AND EXISTS (
        SELECT 1 FROM party_partyaddress WHERE id=OLD.address_id)
    THEN RAISE EXCEPTION 'A live address identity cannot be detached'; END IF;
    IF OLD.identifier_id IS NOT NULL AND NEW.identifier_id IS NULL AND EXISTS (
        SELECT 1 FROM party_partyidentifier WHERE id=OLD.identifier_id)
    THEN RAISE EXCEPTION 'A live identifier identity cannot be detached'; END IF;
    RETURN NULL;
END $$;
CREATE OR REPLACE FUNCTION portability_child_result_guard() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE batch_profile text;
BEGIN
    SELECT contract_version INTO batch_profile FROM data_portability_importbatch WHERE id=NEW.batch_id;
    IF NEW.child_identity_id IS NOT NULL AND (NEW.committed_at IS NULL OR NOT EXISTS (
        SELECT 1 FROM data_portability_childidentity c WHERE c.id=NEW.child_identity_id
        AND c.workspace_id=NEW.workspace_id AND c.parent_id=NEW.identity_id AND c.profile=batch_profile))
    THEN RAISE EXCEPTION 'Child result must match parent, profile and Workspace'; END IF;
    IF NEW.committed_at IS NOT NULL AND batch_profile IN ('party-contact/1','party-address/1','party-identifier/1') AND NEW.child_identity_id IS NULL
    THEN RAISE EXCEPTION 'Child completion requires a child result'; END IF;
    IF batch_profile='party-master/1' AND NEW.child_identity_id IS NOT NULL
    THEN RAISE EXCEPTION 'Master result cannot reference child'; END IF;
    RETURN NEW;
END $$;
"""

REVERSE = """
DO $$ BEGIN IF EXISTS (SELECT 1 FROM data_portability_childidentity WHERE profile='party-identifier/1') THEN RAISE EXCEPTION 'Cannot remove identifier portability with retained identities'; END IF; END $$;
CREATE OR REPLACE FUNCTION portability_child_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN RAISE EXCEPTION 'Child provenance cannot be deleted'; END IF;
    IF TG_OP = 'UPDATE' AND NEW.workspace_id <> OLD.workspace_id
    THEN RAISE EXCEPTION 'Child ownership is immutable'; END IF;
    IF TG_TABLE_NAME = 'data_portability_childidentity' THEN
        IF TG_OP = 'UPDATE' AND (
            (NEW.public_id,NEW.parent_id,NEW.profile,NEW.created_at) IS DISTINCT FROM
            (OLD.public_id,OLD.parent_id,OLD.profile,OLD.created_at)
            OR (NEW.contact_id IS NOT NULL AND NEW.contact_id IS DISTINCT FROM OLD.contact_id)
            OR (NEW.address_id IS NOT NULL AND NEW.address_id IS DISTINCT FROM OLD.address_id))
        THEN RAISE EXCEPTION 'Child identity cannot be rebound'; END IF;
        IF NOT EXISTS (SELECT 1 FROM data_portability_partyidentity p
            WHERE p.id=NEW.parent_id AND p.workspace_id=NEW.workspace_id)
        THEN RAISE EXCEPTION 'Child parent must share Workspace'; END IF;
        IF NEW.profile NOT IN ('party-contact/1','party-address/1')
            OR (NEW.profile='party-contact/1' AND NEW.address_id IS NOT NULL)
            OR (NEW.profile='party-address/1' AND NEW.contact_id IS NOT NULL)
            OR (TG_OP='INSERT' AND NEW.contact_id IS NULL AND NEW.address_id IS NULL)
        THEN RAISE EXCEPTION 'Child profile and target must match'; END IF;
        IF NEW.contact_id IS NOT NULL AND NOT EXISTS (
            SELECT 1 FROM party_partycontactmethod c JOIN data_portability_partyidentity p ON p.party_id=c.party_id
            WHERE c.id=NEW.contact_id AND c.workspace_id=NEW.workspace_id AND p.id=NEW.parent_id)
        THEN RAISE EXCEPTION 'Contact must share Party and Workspace'; END IF;
        IF NEW.address_id IS NOT NULL AND NOT EXISTS (
            SELECT 1 FROM party_partyaddress c JOIN data_portability_partyidentity p ON p.party_id=c.party_id
            WHERE c.id=NEW.address_id AND c.workspace_id=NEW.workspace_id AND p.id=NEW.parent_id)
        THEN RAISE EXCEPTION 'Address must share Party and Workspace'; END IF;
    ELSIF TG_TABLE_NAME = 'data_portability_childsourceidentity' THEN
        IF TG_OP <> 'INSERT' THEN RAISE EXCEPTION 'Child source evidence is immutable'; END IF;
        IF NOT EXISTS (SELECT 1 FROM data_portability_childidentity c
            WHERE c.id=NEW.identity_id AND c.workspace_id=NEW.workspace_id AND c.profile=NEW.profile)
        THEN RAISE EXCEPTION 'Child source must share Workspace and profile'; END IF;
    END IF;
    RETURN NEW;
END $$;
CREATE OR REPLACE FUNCTION portability_child_tombstone_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF OLD.contact_id IS NOT NULL AND NEW.contact_id IS NULL AND EXISTS (
        SELECT 1 FROM party_partycontactmethod WHERE id=OLD.contact_id)
    THEN RAISE EXCEPTION 'A live contact identity cannot be detached'; END IF;
    IF OLD.address_id IS NOT NULL AND NEW.address_id IS NULL AND EXISTS (
        SELECT 1 FROM party_partyaddress WHERE id=OLD.address_id)
    THEN RAISE EXCEPTION 'A live address identity cannot be detached'; END IF;
    RETURN NULL;
END $$;
CREATE OR REPLACE FUNCTION portability_child_result_guard() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE batch_profile text;
BEGIN
    SELECT contract_version INTO batch_profile FROM data_portability_importbatch WHERE id=NEW.batch_id;
    IF NEW.child_identity_id IS NOT NULL AND (NEW.committed_at IS NULL OR NOT EXISTS (
        SELECT 1 FROM data_portability_childidentity c WHERE c.id=NEW.child_identity_id
        AND c.workspace_id=NEW.workspace_id AND c.parent_id=NEW.identity_id AND c.profile=batch_profile))
    THEN RAISE EXCEPTION 'Child result must match parent, profile and Workspace'; END IF;
    IF NEW.committed_at IS NOT NULL AND batch_profile IN ('party-contact/1','party-address/1') AND NEW.child_identity_id IS NULL
    THEN RAISE EXCEPTION 'Child completion requires a child result'; END IF;
    IF batch_profile='party-master/1' AND NEW.child_identity_id IS NOT NULL
    THEN RAISE EXCEPTION 'Master result cannot reference child'; END IF;
    RETURN NEW;
END $$;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('data_portability', '0004_child_guards'),
        ('party', '0002_enable_workspace_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='childidentity',
            name='identifier',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_identity', to='party.partyidentifier'),
        ),
        migrations.RunSQL(SQL, REVERSE),
    ]
