# Generated by Django 6.0.3 on 2026-09-12 02:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from apps.tenancy.rls import EnableWorkspaceRLS


SQL = """
CREATE FUNCTION portability_preset_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP <> 'INSERT' THEN RAISE EXCEPTION 'Mapping preset versions are immutable'; END IF;
    IF NEW.profile NOT IN ('party-master/1','party-contact/1','party-address/1','party-identifier/1','party-role/1','party-relationship/1')
       OR jsonb_typeof(NEW.mapping) <> 'object' OR jsonb_typeof(NEW.headers) <> 'array'
       OR octet_length(NEW.mapping::text) > 262144
    THEN RAISE EXCEPTION 'Invalid preset profile or configuration'; END IF;
    IF EXISTS (SELECT 1 FROM data_portability_mappingpresetversion p WHERE p.workspace_id=NEW.workspace_id
        AND p.name=NEW.name AND (p.profile<>NEW.profile OR p.source_system<>NEW.source_system))
    THEN RAISE EXCEPTION 'Preset families cannot change profile or source system'; END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER portability_preset_immutable BEFORE INSERT OR UPDATE OR DELETE
ON data_portability_mappingpresetversion FOR EACH ROW EXECUTE FUNCTION portability_preset_guard();
CREATE FUNCTION portability_batch_preset_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.mapping_preset_id IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM data_portability_mappingpresetversion p
        WHERE p.id=NEW.mapping_preset_id AND p.workspace_id=NEW.workspace_id
        AND NEW.source_type='csv' AND p.profile=NEW.contract_version
        AND p.source_system=NEW.source_system AND p.mapping=NEW.mapping
        AND p.headers @> NEW.headers AND p.headers <@ NEW.headers)
    THEN RAISE EXCEPTION 'Batch preset must match Workspace, source, headers, profile and mapping'; END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER portability_batch_preset_match BEFORE INSERT OR UPDATE
ON data_portability_importbatch FOR EACH ROW EXECUTE FUNCTION portability_batch_preset_guard();
"""

REVERSE = """
DO $$ BEGIN IF EXISTS (SELECT 1 FROM data_portability_mappingpresetversion)
THEN RAISE EXCEPTION 'Cannot remove retained mapping preset versions'; END IF; END $$;
DROP TRIGGER portability_batch_preset_match ON data_portability_importbatch;
DROP FUNCTION portability_batch_preset_guard();
DROP TRIGGER portability_preset_immutable ON data_portability_mappingpresetversion;
DROP FUNCTION portability_preset_guard();
"""


class Migration(migrations.Migration):

    dependencies = [
        ('data_portability', '0007_childidentity_related_parent_and_more'),
        ('orgs', '0009_workspace_role_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingPresetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('version', models.PositiveIntegerField()),
                ('profile', models.CharField(max_length=32)),
                ('source_system', models.CharField(max_length=120)),
                ('headers', models.JSONField(default=list)),
                ('mapping', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company')),
            ],
        ),
        migrations.AddField(
            model_name='importbatch',
            name='mapping_preset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='data_portability.mappingpresetversion'),
        ),
        migrations.AddConstraint(
            model_name='mappingpresetversion',
            constraint=models.UniqueConstraint(fields=('workspace', 'name', 'version'), name='port_preset_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='mappingpresetversion',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='port_preset_positive_version'),
        ),
        EnableWorkspaceRLS("MappingPresetVersion"),
        migrations.RunSQL(SQL, REVERSE),
    ]
