# Generated by Django 6.0.3 on 2026-09-12 05:08

import django.db.models.deletion
import uuid
import re
import django.utils.timezone
from apps.tenancy.rls import EnableWorkspaceRLS
from django.conf import settings
from django.db import migrations, models



FIELDS = ("master", "contact", "address", "identifier", "role", "relationship")

SQL = """
CREATE FUNCTION portability_bundle_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP <> 'INSERT' THEN RAISE EXCEPTION 'Bundle source and membership are immutable'; END IF;
    IF NEW.source_sha256 !~ '^[0-9a-f]{64}$' THEN RAISE EXCEPTION 'Invalid bundle checksum'; END IF;
    IF EXISTS (
        SELECT 1 FROM (VALUES
            (NEW.master_id,'party-master/1'), (NEW.contact_id,'party-contact/1'),
            (NEW.address_id,'party-address/1'), (NEW.identifier_id,'party-identifier/1'),
            (NEW.role_id,'party-role/1'), (NEW.relationship_id,'party-relationship/1')
        ) AS member(batch_id, profile)
        WHERE member.batch_id IS NOT NULL AND NOT EXISTS (
            SELECT 1 FROM data_portability_importbatch b WHERE b.id=member.batch_id
            AND b.workspace_id=NEW.workspace_id AND b.contract_version=member.profile
            AND b.source_type='jsonl' AND b.source_system='rokkad:' || NEW.source_namespace::text)
    ) THEN RAISE EXCEPTION 'Bundle batches must match Workspace, profile and source namespace'; END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER portability_bundle_immutable BEFORE INSERT OR UPDATE OR DELETE
ON data_portability_importbundle FOR EACH ROW EXECUTE FUNCTION portability_bundle_guard();
"""
REVERSE = """
DO $$ BEGIN IF EXISTS (SELECT 1 FROM data_portability_importbundle)
THEN RAISE EXCEPTION 'Cannot remove retained bundle history'; END IF; END $$;
DROP TRIGGER portability_bundle_immutable ON data_portability_importbundle;
DROP FUNCTION portability_bundle_guard();
"""


def backfill(apps, schema_editor):
    """Recover only complete, verifiable group evidence from staging audit entries."""
    Bundle = apps.get_model("data_portability", "ImportBundle")
    Batch = apps.get_model("data_portability", "ImportBatch")
    Audit = apps.get_model("orgs", "AuditLog")
    alias = schema_editor.connection.alias
    recovered = skipped = 0
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT current_setting('app.workspace_id', true)")
        previous = cursor.fetchone()[0] or ""
        try:
            logs = Audit.objects.using(alias).filter(action="DATA_IMPORT",
                description="Validated and staged Party bundle for separate profile review; no Party data committed.").order_by("pk")
            for log in logs.iterator():
                data = log.data
                if not isinstance(data, dict) or not log.company_id or not log.user_id:
                    skipped += 1; continue
                try:
                    namespace = str(uuid.UUID(data["source_namespace"]))
                    checksum = data["sha256"]
                    members = data["batches"]
                    if not isinstance(checksum, str) or not re.fullmatch("[0-9a-f]{64}", checksum):
                        raise ValueError()
                    if not isinstance(members, dict) or set(members) != {f"party-{field}/1" for field in FIELDS}:
                        raise ValueError()
                    cursor.execute("SELECT set_config('app.workspace_id', %s, true)", [str(log.company_id)])
                    links = {}
                    for field in FIELDS:
                        key = members[f"party-{field}/1"]
                        if key is None:
                            links[field + "_id"] = None
                            continue
                        batch = Batch.objects.using(alias).get(public_id=uuid.UUID(key), workspace_id=log.company_id,
                            contract_version=f"party-{field}/1", source_type="jsonl", source_system="rokkad:" + namespace)
                        links[field + "_id"] = batch.pk
                    existing = Bundle.objects.using(alias).filter(workspace_id=log.company_id, **links)
                    if any(links.values()) and existing.exists():
                        continue
                    if existing.filter(source_sha256=checksum, created_at=log.timestamp).exists():
                        continue
                    if any(value is not None and Bundle.objects.using(alias).filter(
                        workspace_id=log.company_id, **{field: value}).exists() for field, value in links.items()):
                        skipped += 1; continue
                    Bundle.objects.using(alias).create(workspace_id=log.company_id, source_namespace=namespace,
                        source_sha256=checksum, created_by_id=log.user_id, created_at=log.timestamp, **links)
                    recovered += 1
                except (KeyError, ValueError, TypeError, AttributeError, Batch.DoesNotExist):
                    skipped += 1
        finally:
            cursor.execute("SELECT set_config('app.workspace_id', %s, true)", [previous])
    if recovered or skipped:
        print(f"Bundle history: recovered={recovered}, skipped_unverifiable={skipped}")


class Migration(migrations.Migration):

    dependencies = [
        ('data_portability', '0009_xlsx_preset_guard'),
        ('orgs', '0009_workspace_role_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_namespace', models.UUIDField()),
                ('source_sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='address_bundle', to='data_portability.importbatch')),
                ('contact', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contact_bundle', to='data_portability.importbatch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('identifier', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='identifier_bundle', to='data_portability.importbatch')),
                ('master', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_bundle', to='data_portability.importbatch')),
                ('relationship', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relationship_bundle', to='data_portability.importbatch')),
                ('role', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='role_bundle', to='data_portability.importbatch')),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        EnableWorkspaceRLS("ImportBundle"),
        migrations.RunSQL(SQL, REVERSE),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
