# Generated by Django 6.0.3 on 2026-09-12 06:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_portability', '0010_importbundle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanHistoryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_sha256', models.CharField(max_length=64)),
                ('document', models.JSONField()),
                ('mapping', models.JSONField(default=dict)),
                ('preview', models.JSONField(default=dict)),
                ('state', models.CharField(choices=[('STAGED', 'STAGED'), ('READY', 'READY'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED')], default='STAGED', max_length=12)),
                ('approval_digest', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        # Fail closed between this table's creation and the scoped policy in 0012.
        # With no policy, forced RLS denies all restricted-role DML.
        migrations.RunSQL(
            "ALTER TABLE data_portability_loanhistorybatch ENABLE ROW LEVEL SECURITY; "
            "ALTER TABLE data_portability_loanhistorybatch FORCE ROW LEVEL SECURITY;",
            "ALTER TABLE data_portability_loanhistorybatch NO FORCE ROW LEVEL SECURITY; "
            "ALTER TABLE data_portability_loanhistorybatch DISABLE ROW LEVEL SECURITY;",
        ),
    ]
