# Generated by Django 6.0.3 on 2026-09-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_portability', '0012_loanhistorybatch_result_loanhistorybatch_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanhistorybatch',
            name='profile',
            field=models.CharField(choices=[('loan-history/1', 'Complete history'), ('legacy-opening/1', 'Legacy opening')], default='loan-history/1', max_length=32),
        ),
        migrations.RunSQL("""
CREATE FUNCTION portability_loan_profile_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF NEW.profile NOT IN ('loan-history/1','legacy-opening/1')
 OR (TG_OP='UPDATE' AND NEW.profile IS DISTINCT FROM OLD.profile)
 THEN RAISE EXCEPTION 'Loan import profile is immutable and must be supported'; END IF;
 IF NEW.result_id IS NOT NULL AND NOT EXISTS (
   SELECT 1 FROM loans_historicalloanimport r WHERE r.id=NEW.result_id AND
   ((NEW.profile='legacy-opening/1' AND r.document=NEW.document->'opening') OR
    (NEW.profile='loan-history/1' AND r.document=NEW.document)))
 THEN RAISE EXCEPTION 'Loan import result must match its exact profile document'; END IF;
 RETURN NEW;
END; $$;
CREATE TRIGGER portability_loan_profile_guard BEFORE INSERT OR UPDATE ON data_portability_loanhistorybatch
FOR EACH ROW EXECUTE FUNCTION portability_loan_profile_guard();
""", "DROP TRIGGER portability_loan_profile_guard ON data_portability_loanhistorybatch; DROP FUNCTION portability_loan_profile_guard();"),
    ]
