# Generated by Django 6.0.3 on 2026-09-12 23:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from apps.tenancy.rls import EnableWorkspaceRLS


class Migration(migrations.Migration):

    dependencies = [
        ('data_portability', '0013_loan_batch_profile'),
        ('loans', '0013_historicalloanevidence'),
        ('orgs', '0009_workspace_role_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanArchiveBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_sha256', models.CharField(max_length=64)),
                ('document', models.JSONField()),
                ('state', models.CharField(choices=[('STAGED', 'STAGED'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED')], default='STAGED', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='loans.historicalloanevidence')),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        EnableWorkspaceRLS("LoanArchiveBatch"),
        migrations.RunSQL("""
CREATE FUNCTION portability_archive_batch_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF TG_OP='DELETE' THEN RAISE EXCEPTION 'Archive staging history is retained'; END IF;
 IF NEW.source_sha256 !~ '^[0-9a-f]{64}$' THEN RAISE EXCEPTION 'Invalid archive fingerprint'; END IF;
 IF TG_OP='INSERT' THEN
  IF NEW.state<>'STAGED' OR NEW.result_id IS NOT NULL
  OR NEW.document->>'profile' IS DISTINCT FROM 'loan-closed-evidence/1'
  THEN RAISE EXCEPTION 'New archive batches must contain staged evidence'; END IF;
 ELSE
  IF OLD.state<>'STAGED' OR NEW.state NOT IN ('COMPLETED','CANCELLED')
  OR NEW.workspace_id IS DISTINCT FROM OLD.workspace_id
  OR NEW.public_id IS DISTINCT FROM OLD.public_id
  OR NEW.created_by_id IS DISTINCT FROM OLD.created_by_id
  OR NEW.created_at IS DISTINCT FROM OLD.created_at
  OR NEW.source_sha256 IS DISTINCT FROM OLD.source_sha256
  THEN RAISE EXCEPTION 'Invalid archive staging transition'; END IF;
  IF NEW.state='CANCELLED' THEN
   IF NEW.document<>'{}'::jsonb OR NEW.result_id IS NOT NULL
   THEN RAISE EXCEPTION 'Cancelled archive batches must clear staged evidence'; END IF;
  ELSE
   IF NEW.document IS DISTINCT FROM OLD.document OR NEW.result_id IS NULL OR NOT EXISTS (
    SELECT 1 FROM loans_historicalloanevidence e WHERE e.id=NEW.result_id
    AND e.workspace_id=NEW.workspace_id AND e.source_sha256=NEW.source_sha256 AND e.document=NEW.document)
   THEN RAISE EXCEPTION 'Archive result must match its Workspace and source evidence'; END IF;
  END IF;
 END IF;
 RETURN NEW;
END; $$;
CREATE TRIGGER portability_archive_batch_guard BEFORE INSERT OR UPDATE OR DELETE ON data_portability_loanarchivebatch
FOR EACH ROW EXECUTE FUNCTION portability_archive_batch_guard();
""", "DROP TRIGGER portability_archive_batch_guard ON data_portability_loanarchivebatch; DROP FUNCTION portability_archive_batch_guard();"),
    ]
