# Generated by Django 6.0.3 on 2026-09-21 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from apps.tenancy.rls import EnableWorkspaceRLS


class Migration(migrations.Migration):

    dependencies = [
        ('data_portability', '0014_loanarchivebatch'),
        ('orgs', '0009_workspace_role_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyMediaReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_system', models.CharField(max_length=120)),
                ('source_id', models.CharField(max_length=120)),
                ('evidence_sha256', models.CharField(max_length=64)),
                ('source_evidence', models.JSONField()),
                ('target', models.JSONField()),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('workspace', 'source_system', 'source_id'), name='port_legacy_media_source_uniq')],
            },
        ),
        EnableWorkspaceRLS("LegacyMediaReceipt"),
        migrations.RunSQL("""
CREATE FUNCTION portability_legacy_media_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF TG_OP <> 'INSERT' THEN RAISE EXCEPTION 'Legacy media receipts are immutable'; END IF;
 IF NEW.evidence_sha256 !~ '^[0-9a-f]{64}$'
 OR NEW.source_evidence->>'status' IS DISTINCT FROM 'EXACT_SOURCE_FILE_PRESERVED'
 OR NEW.target->>'kind' NOT IN ('party', 'collateral', 'archive')
 THEN RAISE EXCEPTION 'Invalid legacy media receipt'; END IF;
 RETURN NEW;
END; $$;
CREATE TRIGGER portability_legacy_media_guard BEFORE INSERT OR UPDATE OR DELETE ON data_portability_legacymediareceipt
FOR EACH ROW EXECUTE FUNCTION portability_legacy_media_guard();
""", "DROP TRIGGER portability_legacy_media_guard ON data_portability_legacymediareceipt; DROP FUNCTION portability_legacy_media_guard();"),
    ]
