# Generated by Django 6.1.1 on 2026-09-30 13:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from apps.tenancy.rls import EnableWorkspaceRLS


class Migration(migrations.Migration):

    dependencies = [
        ('data_portability', '0015_legacy_media'),
        ('orgs', '0010_storage_inventory'),
        ('loans', '0009_historicalloanimport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidedOpeningBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_key', models.CharField(max_length=48)),
                ('source_name', models.CharField(max_length=255)),
                ('source_sha256', models.CharField(max_length=64)),
                ('document', models.JSONField()),
                ('mapping', models.JSONField(default=dict)),
                ('preview', models.JSONField(default=dict)),
                ('approval_digest', models.CharField(blank=True, max_length=64)),
                ('state', models.CharField(choices=[('STAGED', 'STAGED'), ('READY', 'READY'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED')], default='STAGED', max_length=12)),
                ('results', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('committed_at', models.DateTimeField(null=True)),
                ('committed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('state', 'CANCELLED'), _negated=True), fields=('workspace', 'source_key', 'source_sha256'), name='port_guided_source_active_uniq')],
            },
        ),
        EnableWorkspaceRLS('GuidedOpeningBatch'),
        migrations.RunSQL("""
CREATE FUNCTION portability_guided_opening_guard() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE item jsonb;
BEGIN
 IF TG_OP='DELETE' THEN RAISE EXCEPTION 'Guided import history cannot be deleted'; END IF;
 IF NEW.source_sha256 !~ '^[0-9a-f]{64}$' OR NEW.source_key !~ '^[a-z0-9][a-z0-9-]{0,47}$'
 OR NEW.state NOT IN ('STAGED','READY','COMPLETED','CANCELLED')
 THEN RAISE EXCEPTION 'Invalid guided import identity or state'; END IF;
 IF TG_OP='INSERT' THEN
  IF NEW.state<>'STAGED' OR NEW.results<>'[]'::jsonb OR NEW.mapping<>'{}'::jsonb
  OR NEW.preview<>'{}'::jsonb OR NEW.approval_digest<>'' OR NEW.committed_by_id IS NOT NULL
  OR NEW.committed_at IS NOT NULL OR NEW.document->>'profile' IS DISTINCT FROM 'outstanding-register/1'
  OR jsonb_typeof(NEW.document->'rows') IS DISTINCT FROM 'array'
  OR NOT jsonb_array_length(NEW.document->'rows') BETWEEN 1 AND 200
  THEN RAISE EXCEPTION 'New guided imports require bounded staged source evidence'; END IF;
 ELSE
  IF OLD.state IN ('COMPLETED','CANCELLED') OR
   (NEW.workspace_id,NEW.public_id,NEW.source_key,NEW.source_name,NEW.source_sha256,NEW.created_by_id,NEW.created_at)
   IS DISTINCT FROM
   (OLD.workspace_id,OLD.public_id,OLD.source_key,OLD.source_name,OLD.source_sha256,OLD.created_by_id,OLD.created_at)
  THEN RAISE EXCEPTION 'Guided source identity and completed evidence are immutable'; END IF;
  IF NEW.state='CANCELLED' THEN
   IF NEW.document<>'{}'::jsonb OR NEW.mapping<>'{}'::jsonb OR NEW.preview<>'{}'::jsonb OR NEW.approval_digest<>''
   THEN RAISE EXCEPTION 'Cancelled staging must clear private source and review'; END IF;
  ELSIF NEW.document IS DISTINCT FROM OLD.document THEN
   RAISE EXCEPTION 'Guided source rows are immutable';
  END IF;
  IF NEW.state='READY' AND (NEW.approval_digest !~ '^[0-9a-f]{64}$'
    OR NEW.preview->'issues' IS DISTINCT FROM '[]'::jsonb)
  THEN RAISE EXCEPTION 'Ready guided imports require a successful reviewed preview'; END IF;
  IF NEW.state='COMPLETED' THEN
   IF OLD.state<>'READY' OR NEW.mapping IS DISTINCT FROM OLD.mapping OR NEW.preview IS DISTINCT FROM OLD.preview
   OR NEW.approval_digest IS DISTINCT FROM OLD.approval_digest OR NEW.committed_by_id IS NULL OR NEW.committed_at IS NULL
   OR jsonb_typeof(NEW.results)<>'array' OR NOT jsonb_array_length(NEW.results) BETWEEN 1 AND 20
   OR jsonb_array_length(NEW.results) IS DISTINCT FROM (NEW.preview->>'loans')::int
   THEN RAISE EXCEPTION 'Completion requires the exact reviewed batch and all results'; END IF;
   FOR item IN SELECT * FROM jsonb_array_elements(NEW.results) LOOP
    IF NOT EXISTS (SELECT 1 FROM loans_historicalloanimport r WHERE r.workspace_id=NEW.workspace_id
      AND r.id=(item->>'origin_id')::bigint AND r.loan_id=(item->>'loan_id')::bigint
      AND r.source_sha256=item->>'source_sha256' AND r.document->>'profile'='loan-opening-commit/1')
    THEN RAISE EXCEPTION 'Guided results must match immutable openings in this Workspace'; END IF;
   END LOOP;
   IF (SELECT count(DISTINCT x->>'origin_id') FROM jsonb_array_elements(NEW.results) x) <> jsonb_array_length(NEW.results)
   THEN RAISE EXCEPTION 'Each guided result must be distinct'; END IF;
  END IF;
 END IF;
 IF NEW.state<>'COMPLETED' AND (NEW.results<>'[]'::jsonb OR NEW.committed_by_id IS NOT NULL OR NEW.committed_at IS NOT NULL)
 THEN RAISE EXCEPTION 'Only completed guided imports may have results'; END IF;
 RETURN NEW;
END; $$;
CREATE TRIGGER portability_guided_opening_guard BEFORE INSERT OR UPDATE OR DELETE ON data_portability_guidedopeningbatch
FOR EACH ROW EXECUTE FUNCTION portability_guided_opening_guard();
""", "DROP TRIGGER portability_guided_opening_guard ON data_portability_guidedopeningbatch; DROP FUNCTION portability_guided_opening_guard();"),
    ]
