# Generated by Django 5.2.6 on 2025-11-15 09:42

import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("approval", "0002_initial"),
        ("contact", "0001_initial"),
        ("product", "0002_initial"),
        ("terms", "0002_auto_20230723_1647"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceReceiptView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=50)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "amount_allocated",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
            options={
                "db_table": "sales_receipt_view",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "voucher_date",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "voucher_no",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                ("due_date", models.DateField(blank=True, db_index=True, null=True)),
                ("is_ratecut", models.BooleanField(default=False)),
                ("is_gst", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Paid", "Paid"),
                            ("PartiallyPaid", "PartiallyPaid"),
                            ("Unpaid", "Unpaid"),
                        ],
                        db_index=True,
                        default="Unpaid",
                        max_length=15,
                    ),
                ),
                (
                    "gold_rate",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "silver_rate",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "approval",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="approval.approval",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sold",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="contact.customer",
                        verbose_name="Customer",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sale_term",
                        to="terms.paymentterm",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
                "get_latest_by": "id",
            },
        ),
        migrations.CreateModel(
            name="Balance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "amount",
                    djmoney.models.fields.MoneyField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balances",
                        to="sales.invoice",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_return",
                    models.BooleanField(default=False, verbose_name="Return"),
                ),
                ("quantity", models.IntegerField()),
                ("weight", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "less_stone",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=10,
                        verbose_name="less wt",
                    ),
                ),
                ("touch", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "wastage",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "net_wt",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "making_charge",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "hallmark_charge",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "metal_balance_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="USD",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "metal_balance",
                    djmoney.models.fields.MoneyField(
                        decimal_places=3,
                        default=Decimal("0"),
                        default_currency="USD",
                        max_digits=14,
                    ),
                ),
                (
                    "cash_balance_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "cash_balance",
                    djmoney.models.fields.MoneyField(
                        decimal_places=3, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "approval_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sold_items",
                        to="approval.approvalline",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_items",
                        to="sales.invoice",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sold_items",
                        to="product.stock",
                    ),
                ),
            ],
            options={
                "ordering": ("-pk",),
            },
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "voucher_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("voucher_no", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "weight",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "touch",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                ("convert", models.BooleanField(default=False)),
                ("rate", models.IntegerField(default=0)),
                (
                    "total_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "total",
                    djmoney.models.fields.MoneyField(decimal_places=3, max_digits=10),
                ),
                (
                    "amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "amount",
                    djmoney.models.fields.MoneyField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "description",
                    models.TextField(default="describe here", max_length=50),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Allotted", "Allotted"),
                            ("Partially Allotted", "PartiallyAllotted"),
                            ("Unallotted", "Unallotted"),
                        ],
                        default="Unallotted",
                        max_length=18,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="contact.customer",
                        verbose_name="Customer",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="ReceiptAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "allocated_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "allocated",
                    djmoney.models.fields.MoneyField(
                        decimal_places=4, default=Decimal("0"), max_digits=19
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sales.invoice"
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sales.receipt"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="receipt",
            name="invoices",
            field=models.ManyToManyField(
                through="sales.ReceiptAllocation", to="sales.invoice"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["status", "-created"], name="sales_invoi_status_875c9a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["customer", "-created"], name="sales_invoi_custome_f568b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["due_date", "status"], name="sales_invoi_due_dat_b89d0e_idx"
            ),
        ),
    ]
