# Generated by Django 5.0.1 on 2024-04-06 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_remove_stocklot_stock_remove_stocklot_variant_and_more"),
        ("sales", "0002_auto_20240406_1131"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sold_items",
                to="product.stock",
            ),
        ),
        migrations.AlterModelTable(
            name="salebalance",
            table="sales_balance",
        ),
    ]
