# Generated by Django 6.0.3 on 2026-03-23 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_pr5_invoiceitem_union_subject'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoiceitem',
            name='sales_invoiceitem_exactly_one_subject',
        ),
    ]
