# Generated by Django 5.1.2 on 2024-12-04 11:23

import apps.tenant_apps.dea.models.moneyvalue
import django.contrib.postgres.fields
import django.utils.timezone
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("sales", "0004_remove_invoiceitem_huid_invoice_balance_cash_and_more"),
        ("sales", "0005_remove_invoiceitem_rate"),
        ("sales", "0006_invoice_balance"),
        ("sales", "0007_invoice_voucher_date_receipt_voucher_date_and_more"),
        ("sales", "0008_receipt_convert"),
        ("sales", "0009_receipt_amount_receipt_amount_currency"),
        ("sales", "0010_alter_receipt_voucher_date"),
        ("sales", "0011_invoice_voucher_no_receipt_voucher_no"),
        ("sales", "0012_alter_invoice_voucher_no_alter_receipt_voucher_no"),
        ("sales", "0013_alter_invoice_balance_cash_currency_and_more"),
    ]

    dependencies = [
        ("sales", "0003_alter_invoiceitem_product_alter_salebalance_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoiceitem",
            name="huid",
        ),
        migrations.AddField(
            model_name="invoice",
            name="balance_cash",
            field=djmoney.models.fields.MoneyField(
                blank=True, decimal_places=3, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="balance_gold",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=3,
                default_currency="USD",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="balance_silver",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=3,
                default_currency="EUR",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="gold_rate",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="invoice",
            name="silver_rate",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.RemoveField(
            model_name="invoiceitem",
            name="rate",
        ),
        migrations.AddField(
            model_name="invoice",
            name="balance",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=apps.tenant_apps.dea.models.moneyvalue.MoneyValueField(
                    blank=True, null=True
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="voucher_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name="receipt",
            name="convert",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="receipt",
            name="amount",
            field=djmoney.models.fields.MoneyField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="voucher_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="invoice",
            name="voucher_no",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="receipt",
            name="voucher_no",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="balance_cash_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("AUD", "Australian Dollar"),
                    ("INR", "Indian Rupee"),
                    ("USD", "US Dollar"),
                ],
                default="INR",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="balance_gold_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("AUD", "Australian Dollar"),
                    ("INR", "Indian Rupee"),
                    ("USD", "US Dollar"),
                ],
                default="USD",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="balance_silver_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("AUD", "Australian Dollar"),
                    ("INR", "Indian Rupee"),
                    ("USD", "US Dollar"),
                ],
                default="EUR",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="cash_balance_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("AUD", "Australian Dollar"),
                    ("INR", "Indian Rupee"),
                    ("USD", "US Dollar"),
                ],
                default="INR",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="metal_balance_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("AUD", "Australian Dollar"),
                    ("INR", "Indian Rupee"),
                    ("USD", "US Dollar"),
                ],
                default="USD",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("AUD", "Australian Dollar"),
                    ("INR", "Indian Rupee"),
                    ("USD", "US Dollar"),
                ],
                default="INR",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="total_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("AUD", "Australian Dollar"),
                    ("INR", "Indian Rupee"),
                    ("USD", "US Dollar"),
                ],
                default="INR",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="receiptallocation",
            name="allocated_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("AUD", "Australian Dollar"),
                    ("INR", "Indian Rupee"),
                    ("USD", "US Dollar"),
                ],
                default="INR",
                editable=False,
                max_length=3,
            ),
        ),
    ]
