# Generated by Django 5.0.1 on 2024-04-08 07:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0004_remove_invoiceitem_huid_invoice_balance_cash_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoiceitem",
            name="rate",
        ),
    ]
