# Generated by Django 5.0.1 on 2024-04-11 17:41

import django.contrib.postgres.fields
from django.db import migrations

import apps.tenant_apps.dea.models.moneyvalue


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0005_remove_invoiceitem_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="balance",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=apps.tenant_apps.dea.models.moneyvalue.MoneyValueField(
                    blank=True, null=True
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
