# Generated by Django 5.0.1 on 2024-04-14 12:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0006_invoice_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="voucher_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="receipt",
            name="voucher_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
