# Generated by Django 5.0.1 on 2024-04-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0007_invoice_voucher_date_receipt_voucher_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="convert",
            field=models.BooleanField(default=False),
        ),
    ]
