# Generated by Django 5.0.1 on 2024-04-16 09:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0009_receipt_amount_receipt_amount_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="voucher_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
