# Generated by Django 5.0.1 on 2024-04-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0010_alter_receipt_voucher_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="voucher_no",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="receipt",
            name="voucher_no",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
