# Generated by Django 5.0.1 on 2024-04-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0011_invoice_voucher_no_receipt_voucher_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="voucher_no",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="voucher_no",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
