# Generated by Django 5.0.1 on 2024-06-13 06:19

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0012_alter_invoice_voucher_no_alter_receipt_voucher_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="balance_cash_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("AUD", "Australian Dollar"),
                    ("INR", "Indian Rupee"),
                    ("USD", "US Dollar"),
                ],
                default="INR",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="balance_gold_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("AUD", "Australian Dollar"),
                    ("INR", "Indian Rupee"),
                    ("USD", "US Dollar"),
                ],
                default="USD",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="balance_silver_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("AUD", "Australian Dollar"),
                    ("INR", "Indian Rupee"),
                    ("USD", "US Dollar"),
                ],
                default="EUR",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="cash_balance_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("AUD", "Australian Dollar"),
                    ("INR", "Indian Rupee"),
                    ("USD", "US Dollar"),
                ],
                default="INR",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="metal_balance_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("AUD", "Australian Dollar"),
                    ("INR", "Indian Rupee"),
                    ("USD", "US Dollar"),
                ],
                default="USD",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("AUD", "Australian Dollar"),
                    ("INR", "Indian Rupee"),
                    ("USD", "US Dollar"),
                ],
                default="INR",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="total_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("AUD", "Australian Dollar"),
                    ("INR", "Indian Rupee"),
                    ("USD", "US Dollar"),
                ],
                default="INR",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="receiptallocation",
            name="allocated_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("AUD", "Australian Dollar"),
                    ("INR", "Indian Rupee"),
                    ("USD", "US Dollar"),
                ],
                default="INR",
                editable=False,
                max_length=3,
            ),
        ),
    ]
