# Generated by Django 5.2.6 on 2025-11-15 09:42

import apps.tenant_apps.contact.models
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(blank=True, max_length=255, verbose_name="Name"),
                ),
                (
                    "firstname",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="First Name"
                    ),
                ),
                (
                    "lastname",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Last Name"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "M"), ("F", "F"), ("N", "N")],
                        default="M",
                        max_length=1,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "religion",
                    models.CharField(
                        choices=[
                            ("Hindu", "Hindu"),
                            ("Muslim", "Muslim"),
                            ("Christian", "Christian"),
                            ("Atheist", "Atheist"),
                        ],
                        default="Hindu",
                        max_length=10,
                    ),
                ),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("R", "Retail"),
                            ("W", "Wholesale"),
                            ("S", "Supplier"),
                        ],
                        default="R",
                        max_length=30,
                        verbose_name="Customer Type",
                    ),
                ),
                (
                    "relatedas",
                    models.CharField(
                        choices=[
                            ("s", "S/o"),
                            ("d", "D/o"),
                            ("f", "F/o"),
                            ("c", "C/o"),
                            ("p", "P/o"),
                            ("h", "H/o"),
                            ("w", "W/o"),
                            ("o", "O/o"),
                        ],
                        default="s",
                        max_length=5,
                        verbose_name="Related As",
                    ),
                ),
                (
                    "relatedto",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Related To"
                    ),
                ),
                (
                    "dob",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of Birth"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        blank=True, default=True, verbose_name="Active"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="customers_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "ordering": ("-created", "name", "relatedto"),
                "unique_together": {("name", "relatedas", "relatedto")},
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "contact_type",
                    models.CharField(
                        choices=[("H", "Home"), ("O", "Office"), ("M", "Mobile")],
                        default="M",
                        max_length=1,
                        verbose_name="Contact Type",
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128,
                        region=None,
                        unique=True,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=True, verbose_name="Default"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Verified"),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contactno",
                        to="contact.customer",
                        verbose_name="Customer",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area", models.CharField(max_length=30, verbose_name="Area")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("doorno", models.CharField(max_length=30, verbose_name="Door No")),
                (
                    "zipcode",
                    models.CharField(
                        default="632001", max_length=6, verbose_name="Zip Code"
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("street", models.TextField(max_length=100, verbose_name="Street")),
                (
                    "city",
                    models.CharField(
                        default="Vellore", max_length=30, verbose_name="City"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=True, verbose_name="Default"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Verified"),
                ),
                (
                    "state",
                    models.CharField(
                        default="Tamil Nadu", max_length=30, verbose_name="State"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="India", max_length=30, verbose_name="Country"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address",
                        to="contact.customer",
                        verbose_name="Customer",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="CustomerPic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=apps.tenant_apps.contact.models.customer_pic_upload_to
                    ),
                ),
                ("is_default", models.BooleanField(default=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pics",
                        to="contact.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Proof",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Verified"),
                ),
                (
                    "proof_type",
                    models.CharField(
                        choices=[
                            ("AA", "AadharNo"),
                            ("DL", "Driving License"),
                            ("PN", "PanCard No"),
                        ],
                        default="AA",
                        max_length=2,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("proof_no", models.CharField(max_length=30)),
                ("doc", models.FileField(upload_to="upload/files/proofs")),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proofs",
                        to="contact.customer",
                        verbose_name="Customer",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="CustomerRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("s", "S/o"),
                            ("d", "D/o"),
                            ("f", "F/o"),
                            ("c", "C/o"),
                            ("p", "P/o"),
                            ("h", "H/o"),
                            ("w", "W/o"),
                            ("o", "O/o"),
                        ],
                        default="s",
                        max_length=2,
                        verbose_name="Relationship",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships",
                        to="contact.customer",
                        verbose_name="Customer",
                    ),
                ),
                (
                    "related_customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relatedby",
                        to="contact.customer",
                        verbose_name="Related Customer",
                    ),
                ),
            ],
            options={
                "unique_together": {("customer", "related_customer", "relationship")},
            },
        ),
    ]
