# Generated by Django 5.0.1 on 2024-02-26 08:35

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="Customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="address",
                to="contact.customer",
                verbose_name="Customer",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="area",
            field=models.CharField(
                default="ChinaAllapuram", max_length=30, verbose_name="Area"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(
                default="Vellore", max_length=30, verbose_name="City"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="doorno",
            field=models.CharField(max_length=30, verbose_name="Door No"),
        ),
        migrations.AlterField(
            model_name="address",
            name="street",
            field=models.TextField(max_length=100, verbose_name="Street"),
        ),
        migrations.AlterField(
            model_name="address",
            name="zipcode",
            field=models.CharField(
                default="632001", max_length=6, verbose_name="Zip Code"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="contact_type",
            field=models.CharField(
                choices=[("H", "Home"), ("O", "Office"), ("M", "Mobile")],
                default="M",
                max_length=1,
                verbose_name="Contact Type",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contactno",
                to="contact.customer",
                verbose_name="Customer",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, unique=True, verbose_name="Phone Number"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="Address",
            field=models.TextField(blank=True, max_length=100, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="active",
            field=models.BooleanField(blank=True, default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="area",
            field=models.CharField(blank=True, max_length=50, verbose_name="Area"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="customer_type",
            field=models.CharField(
                choices=[("R", "Retail"), ("W", "Wholesale"), ("S", "Supplier")],
                default="R",
                max_length=30,
                verbose_name="Customer Type",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="firstname",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="First Name"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="gender",
            field=models.CharField(
                choices=[("M", "M"), ("F", "F"), ("N", "N")],
                default="M",
                max_length=1,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="lastname",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Last Name"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(blank=True, max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="pic",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="customer_pics/",
                verbose_name="Picture",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="relatedas",
            field=models.CharField(
                choices=[
                    ("s", "S/o"),
                    ("d", "D/o"),
                    ("f", "F/o"),
                    ("c", "C/o"),
                    ("p", "P/o"),
                    ("h", "H/o"),
                    ("w", "W/o"),
                    ("o", "O/o"),
                ],
                default="s",
                max_length=5,
                verbose_name="Related As",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="relatedto",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Related To"
            ),
        ),
        migrations.AlterField(
            model_name="customerrelationship",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relationships",
                to="contact.customer",
                verbose_name="Customer",
            ),
        ),
        migrations.AlterField(
            model_name="customerrelationship",
            name="related_customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relatedby",
                to="contact.customer",
                verbose_name="Related Customer",
            ),
        ),
        migrations.AlterField(
            model_name="customerrelationship",
            name="relationship",
            field=models.CharField(
                choices=[
                    ("s", "S/o"),
                    ("d", "D/o"),
                    ("f", "F/o"),
                    ("c", "C/o"),
                    ("p", "P/o"),
                    ("h", "H/o"),
                    ("w", "W/o"),
                    ("o", "O/o"),
                ],
                default="s",
                max_length=2,
                verbose_name="Relationship",
            ),
        ),
        migrations.AlterField(
            model_name="proof",
            name="Customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proofs",
                to="contact.customer",
                verbose_name="Customer",
            ),
        ),
    ]
