# Generated by Django 5.2.6 on 2026-02-24 12:43

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0002_contact_model_refactoring"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "ordering": ("-created", "firstname", "lastname"),
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
            },
        ),
        migrations.RenameIndex(
            model_name="address",
            new_name="contact_add_custome_f6f0e8_idx",
            old_name="contact_add_cus_def_idx",
        ),
        migrations.RenameIndex(
            model_name="address",
            new_name="contact_add_city_37de97_idx",
            old_name="contact_add_city_st_idx",
        ),
        migrations.RenameIndex(
            model_name="contact",
            new_name="contact_con_custome_509e13_idx",
            old_name="contact_con_cus_def_idx",
        ),
        migrations.RenameIndex(
            model_name="customer",
            new_name="contact_cus_firstna_8ccff6_idx",
            old_name="contact_cus_name_idx",
        ),
        migrations.RenameIndex(
            model_name="customer",
            new_name="contact_cus_created_083ea7_idx",
            old_name="contact_cus_created_idx",
        ),
        migrations.RenameIndex(
            model_name="customer",
            new_name="contact_cus_custome_eeb46c_idx",
            old_name="contact_cus_type_idx",
        ),
        migrations.RenameIndex(
            model_name="customer",
            new_name="contact_cus_active_c997c3_idx",
            old_name="contact_cus_active_idx",
        ),
        migrations.RenameIndex(
            model_name="customerrelationship",
            new_name="contact_cus_custome_0f30e5_idx",
            old_name="contact_rel_cus_rel_idx",
        ),
        migrations.RenameIndex(
            model_name="customerrelationship",
            new_name="contact_cus_related_eeecd4_idx",
            old_name="contact_rel_related_idx",
        ),
        migrations.RenameIndex(
            model_name="proof",
            new_name="contact_pro_custome_5f6324_idx",
            old_name="contact_pro_cus_typ_idx",
        ),
        migrations.AlterUniqueTogether(
            name="customer",
            unique_together={("firstname", "lastname", "relatedas", "relatedto")},
        ),
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(max_length=50, verbose_name="City"),
        ),
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.CharField(
                choices=[
                    ("IN", "India"),
                    ("US", "United States"),
                    ("UK", "United Kingdom"),
                ],
                default="IN",
                max_length=2,
                verbose_name="Country",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                help_text="Enter phone with country code, e.g., +91 9876543210",
                max_length=128,
                region=None,
                verbose_name="Phone Number",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("N", "Non-binary")],
                default="M",
                max_length=1,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="religion",
            field=models.CharField(
                choices=[
                    ("Hindu", "Hindu"),
                    ("Muslim", "Muslim"),
                    ("Christian", "Christian"),
                    ("Atheist", "Atheist"),
                ],
                default="Hindu",
                max_length=10,
                verbose_name="Religion",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated"),
        ),
        migrations.AlterField(
            model_name="customerrelationship",
            name="relationship",
            field=models.CharField(
                choices=[
                    ("s", "S/o"),
                    ("d", "D/o"),
                    ("f", "F/o"),
                    ("c", "C/o"),
                    ("p", "P/o"),
                    ("h", "H/o"),
                    ("w", "W/o"),
                    ("o", "O/o"),
                ],
                default="s",
                max_length=1,
                verbose_name="Relationship",
            ),
        ),
        migrations.AlterField(
            model_name="proof",
            name="proof_number",
            field=models.CharField(max_length=50, verbose_name="Document Number"),
        ),
        migrations.AlterUniqueTogether(
            name="contact",
            unique_together={("customer", "phone_number", "contact_type")},
        ),
        migrations.AlterUniqueTogether(
            name="proof",
            unique_together={("customer", "proof_type")},
        ),
    ]
