# Generated by Django 5.0.1 on 2024-02-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0002_alter_address_customer_alter_address_area_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="Address",
            field=models.TextField(
                blank=True, max_length=100, null=True, verbose_name="Address"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="area",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Area"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="firstname",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="First Name"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="lastname",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Last Name"
            ),
        ),
    ]
