# Generated by Django 5.0.1 on 2024-02-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0003_alter_customer_address_alter_customer_area_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="relatedto",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Related To"
            ),
        ),
    ]
