# Generated by Django 6.0.3 on 2026-05-02 06:38

from django.db import migrations, models


def backfill_phone_number_normalized(apps, schema_editor):
    Contact = apps.get_model('contact', 'Contact')
    for contact in Contact.objects.all().only('id', 'phone_number'):
        normalized = ''.join(ch for ch in str(contact.phone_number or '') if ch.isdigit())
        Contact.objects.filter(id=contact.id).update(phone_number_normalized=normalized)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone_number_normalized',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, help_text='Digits-only phone number for fast search', max_length=32, verbose_name='Phone Number Normalized'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['area'], name='contact_add_area_f8d9df_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['street'], name='contact_add_street_e34826_idx'),
        ),
        migrations.RunPython(backfill_phone_number_normalized, noop_reverse),
    ]
