# Generated by Django 6.0.3 on 2026-06-16 07:57

from django.conf import settings
from django.db import migrations, models


def keep_single_default(apps, schema_editor):
    for model_name in ("Address", "Contact", "CustomerPic"):
        model = apps.get_model("contact", model_name)
        customer_ids = (
            model.objects.filter(is_default=True)
            .values_list("customer_id", flat=True)
            .distinct()
        )
        for customer_id in customer_ids:
            defaults = model.objects.filter(
                customer_id=customer_id,
                is_default=True,
            ).order_by("pk")
            keep = defaults.first()
            if keep:
                defaults.exclude(pk=keep.pk).update(is_default=False)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contact_phone_number_normalized_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='customerrelationship',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='proof',
            unique_together=set(),
        ),
        migrations.RunPython(keep_single_default, noop_reverse),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('customer',), name='contact_one_default_address_per_customer'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('customer', 'phone_number', 'contact_type'), name='contact_customer_phone_type_uniq'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('customer',), name='contact_one_default_contact_per_customer'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('firstname', 'lastname', 'relatedas', 'relatedto'), name='contact_customer_identity_uniq'),
        ),
        migrations.AddConstraint(
            model_name='customerpic',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('customer',), name='contact_one_default_pic_per_customer'),
        ),
        migrations.AddConstraint(
            model_name='customerrelationship',
            constraint=models.UniqueConstraint(fields=('customer', 'related_customer', 'relationship'), name='contact_customer_relationship_uniq'),
        ),
        migrations.AddConstraint(
            model_name='proof',
            constraint=models.UniqueConstraint(fields=('customer', 'proof_type'), name='contact_customer_proof_type_uniq'),
        ),
    ]
