# Generated by Django 6.0.3 on 2026-06-18 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_contact_unique_together_and_more'),
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='party',
            field=models.OneToOneField(blank=True, help_text='Compatibility bridge to the long-term Party model.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legacy_customer', to='party.party', verbose_name='Party'),
        ),
    ]
