# Generated by Django 5.0.1 on 2024-04-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0007_alter_customer_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="Verified"),
        ),
        migrations.AddField(
            model_name="contact",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="Verified"),
        ),
        migrations.AddField(
            model_name="proof",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="Verified"),
        ),
    ]
