# Generated by Django 5.0.1 on 2024-06-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0008_address_is_verified_contact_is_verified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="created",
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name="customer",
            name="updated",
            field=models.DateTimeField(editable=False),
        ),
    ]
