# Generated by Django 5.0.1 on 2024-06-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0009_alter_customer_created_alter_customer_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
