# Generated by Django 5.0.1 on 2024-07-14 05:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0010_alter_customer_created_alter_customer_updated"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="Customer",
            new_name="customer",
        ),
        migrations.RenameField(
            model_name="proof",
            old_name="Customer",
            new_name="customer",
        ),
    ]
