# Generated by Django 5.0.1 on 2024-08-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0011_rename_customer_address_customer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="is_default",
            field=models.BooleanField(default=False, verbose_name="Default"),
        ),
        migrations.AddField(
            model_name="contact",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
