# Generated by Django 5.0.1 on 2024-08-07 13:31

import django.db.models.deletion
from django.db import migrations, models

import apps.tenant_apps.contact.models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0012_address_is_default_contact_is_default"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="Address",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="area",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="pic",
        ),
        migrations.CreateModel(
            name="CustomerPic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=apps.tenant_apps.contact.models.customer_pic_upload_to
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pics",
                        to="contact.customer",
                    ),
                ),
            ],
        ),
    ]
