# Generated by Django 5.0.8 on 2024-08-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0013_remove_customer_address_remove_customer_area_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="area",
            field=models.CharField(max_length=30, verbose_name="Area"),
        ),
    ]
