# Generated by Django 5.0.8 on 2024-08-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0014_alter_address_area"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerpic",
            name="is_default",
            field=models.BooleanField(default=True),
        ),
    ]
