# Generated by Django 5.1.2 on 2024-10-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0015_alter_customerpic_is_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="is_default",
            field=models.BooleanField(default=True, verbose_name="Default"),
        ),
    ]
