# Generated by Django 6.0.3 on 2026-08-09 03:46

import apps.tenant_apps.loans.models.media
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_collateral_public_ids(apps, schema_editor):
    PawnCollateralItem = apps.get_model("loans", "PawnCollateralItem")
    for item in PawnCollateralItem.objects.filter(public_id__isnull=True).iterator():
        item.public_id = uuid.uuid4()
        item.save(update_fields=["public_id"])


def create_media_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        """
        CREATE OR REPLACE FUNCTION loans_reject_collateral_evidence_mutation()
        RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'collateral media and label evidence is immutable';
        END;
        $$ LANGUAGE plpgsql;
        CREATE TRIGGER loans_photo_immutable
        BEFORE UPDATE OR DELETE ON loans_pawncollateralphoto
        FOR EACH ROW EXECUTE FUNCTION loans_reject_collateral_evidence_mutation();
        CREATE TRIGGER loans_label_immutable
        BEFORE UPDATE OR DELETE ON loans_pawncollaterallabelissue
        FOR EACH ROW EXECUTE FUNCTION loans_reject_collateral_evidence_mutation();
        CREATE OR REPLACE FUNCTION loans_reject_collateral_public_id_change()
        RETURNS trigger AS $$
        BEGIN
            IF NEW.public_id IS DISTINCT FROM OLD.public_id THEN
                RAISE EXCEPTION 'collateral public identity is immutable';
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        CREATE TRIGGER loans_item_public_id_immutable
        BEFORE UPDATE ON loans_pawncollateralitem
        FOR EACH ROW EXECUTE FUNCTION loans_reject_collateral_public_id_change();
        """
    )


def drop_media_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        """
        DROP TRIGGER IF EXISTS loans_item_public_id_immutable ON loans_pawncollateralitem;
        DROP FUNCTION IF EXISTS loans_reject_collateral_public_id_change();
        DROP TRIGGER IF EXISTS loans_label_immutable ON loans_pawncollaterallabelissue;
        DROP TRIGGER IF EXISTS loans_photo_immutable ON loans_pawncollateralphoto;
        DROP FUNCTION IF EXISTS loans_reject_collateral_evidence_mutation();
        """
    )

