# Generated by Django 6.0.3 on 2026-08-08 17:43

import apps.tenant_apps.loans.models.regulatory
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_initial_license_revisions(apps, schema_editor):
    LoanLicense = apps.get_model("loans", "LoanLicense")
    LoanLicenseRevision = apps.get_model("loans", "LoanLicenseRevision")
    revisions = []
    for license in LoanLicense.objects.all().iterator():
        revisions.append(
            LoanLicenseRevision(
                license_id=license.pk,
                revision_number=1,
                kind="INITIAL",
                name=license.name,
                license_number=license.license_number,
                issuing_authority=license.issuing_authority,
                issued_on=license.issued_on,
                expires_on=license.expires_on,
                notes=license.notes,
                created_by_id=license.created_by_id,
            )
        )
    LoanLicenseRevision.objects.bulk_create(revisions, batch_size=500)


LICENSE_REVISION_GUARD_SQL = r"""
CREATE OR REPLACE FUNCTION loans_guard_license_revision_immutable()
RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'Loan license revision evidence is immutable';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER loans_license_revision_update_guard
BEFORE UPDATE ON loans_loanlicenserevision
FOR EACH ROW EXECUTE FUNCTION loans_guard_license_revision_immutable();

CREATE TRIGGER loans_license_revision_delete_guard
BEFORE DELETE ON loans_loanlicenserevision
FOR EACH ROW EXECUTE FUNCTION loans_guard_license_revision_immutable();
"""


LICENSE_REVISION_GUARD_REVERSE_SQL = r"""
DROP TRIGGER IF EXISTS loans_license_revision_delete_guard ON loans_loanlicenserevision;
DROP TRIGGER IF EXISTS loans_license_revision_update_guard ON loans_loanlicenserevision;
DROP FUNCTION IF EXISTS loans_guard_license_revision_immutable();
"""

