# Generated by Django 6.0.3 on 2026-08-09 04:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0031_hierarchical_collateral_storage'),
        ('orgs', '0024_alter_auditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PawnPhysicalVerificationExpectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custody_state_snapshot', models.CharField(max_length=32)),
                ('loan_number_snapshot', models.CharField(max_length=96)),
                ('item_description_snapshot', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collateral_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verification_expectations', to='loans.pawncollateralitem')),
                ('expected_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verification_expectations', to='loans.pawnstoragelocation')),
            ],
            options={
                'ordering': ('expected_location_id', 'collateral_item_id'),
            },
        ),
        migrations.CreateModel(
            name='PawnPhysicalVerificationObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(choices=[('FOUND', 'Found'), ('MISSING', 'Missing'), ('MISPLACED', 'Misplaced'), ('UNEXPECTED', 'Unexpected')], max_length=12)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('collateral_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verification_observations', to='loans.pawncollateralitem')),
                ('expectation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observation', to='loans.pawnphysicalverificationexpectation')),
                ('observed_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verification_observations', to='loans.pawnstoragelocation')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pawn_verification_observations_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('recorded_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PawnPhysicalVerificationResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('CONFIRMED_FOUND', 'Confirmed found'), ('LOCATION_CORRECTED', 'Location corrected'), ('LOST_COMPENSATED', 'Lost and compensated'), ('DAMAGED', 'Damaged — release policy deferred')], max_length=24)),
                ('reason', models.CharField(max_length=500)),
                ('current_market_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('agreed_compensation', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('compensation_reference', models.CharField(blank=True, max_length=120)),
                ('resolved_at', models.DateTimeField(auto_now_add=True)),
                ('observation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='resolution', to='loans.pawnphysicalverificationobservation')),
                ('resolved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pawn_verification_resolutions_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('resolved_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PawnPhysicalVerificationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('COMPLETED', 'Completed')], default='OPEN', max_length=12)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pawn_verification_sessions_completed', to=settings.AUTH_USER_MODEL)),
                ('scope_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verification_sessions', to='loans.pawnstoragelocation')),
                ('started_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pawn_verification_sessions_started', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pawn_verification_sessions', to='orgs.company')),
            ],
            options={
                'ordering': ('-started_at', '-id'),
            },
        ),
        migrations.AddField(
            model_name='pawnphysicalverificationobservation',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='loans.pawnphysicalverificationsession'),
        ),
        migrations.AddField(
            model_name='pawnphysicalverificationexpectation',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expectations', to='loans.pawnphysicalverificationsession'),
        ),
        migrations.AddConstraint(
            model_name='pawnphysicalverificationobservation',
            constraint=models.UniqueConstraint(fields=('session', 'collateral_item'), name='loans_verification_observed_item_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pawnphysicalverificationobservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('classification', 'UNEXPECTED'), ('expectation__isnull', True)), models.Q(models.Q(('classification', 'UNEXPECTED'), _negated=True), ('expectation__isnull', False)), _connector='OR'), name='loans_verification_unexpected_shape'),
        ),
        migrations.AddConstraint(
            model_name='pawnphysicalverificationexpectation',
            constraint=models.UniqueConstraint(fields=('session', 'collateral_item'), name='loans_verification_expected_item_uniq'),
        ),
        migrations.RunSQL(
            sql=r"""
CREATE OR REPLACE FUNCTION loans_verification_evidence_immutable() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'Physical-verification evidence is immutable.';
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION loans_verification_session_guard() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'Physical-verification sessions cannot be deleted.';
    END IF;
    IF OLD.status <> 'OPEN' OR NEW.status <> 'COMPLETED'
       OR OLD.workspace_id <> NEW.workspace_id
       OR OLD.scope_location_id <> NEW.scope_location_id
       OR OLD.public_id <> NEW.public_id
       OR OLD.started_by_id IS DISTINCT FROM NEW.started_by_id
       OR OLD.started_at <> NEW.started_at
       OR NEW.completed_at IS NULL THEN
        RAISE EXCEPTION 'Invalid physical-verification session mutation.';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION loans_verification_expectation_guard() RETURNS trigger AS $$
DECLARE session_workspace bigint; session_status varchar; item_workspace bigint; location_workspace bigint;
BEGIN
    SELECT workspace_id, status INTO session_workspace, session_status
      FROM loans_pawnphysicalverificationsession WHERE id = NEW.session_id;
    SELECT loan.workspace_id INTO item_workspace
      FROM loans_pawncollateralitem item JOIN loans_pawnloan loan ON loan.id = item.loan_id
     WHERE item.id = NEW.collateral_item_id;
    SELECT workspace_id INTO location_workspace
      FROM loans_pawnstoragelocation WHERE id = NEW.expected_location_id;
    IF session_status <> 'OPEN' OR session_workspace <> item_workspace
       OR session_workspace <> location_workspace THEN
        RAISE EXCEPTION 'Invalid physical-verification expectation boundary.';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION loans_verification_observation_guard() RETURNS trigger AS $$
DECLARE session_workspace bigint; session_status varchar; item_workspace bigint;
        expected_session bigint; expected_item bigint; location_workspace bigint;
BEGIN
    SELECT workspace_id, status INTO session_workspace, session_status
      FROM loans_pawnphysicalverificationsession WHERE id = NEW.session_id;
    SELECT loan.workspace_id INTO item_workspace
      FROM loans_pawncollateralitem item JOIN loans_pawnloan loan ON loan.id = item.loan_id
     WHERE item.id = NEW.collateral_item_id;
    IF NEW.expectation_id IS NOT NULL THEN
        SELECT session_id, collateral_item_id INTO expected_session, expected_item
          FROM loans_pawnphysicalverificationexpectation WHERE id = NEW.expectation_id;
    END IF;
    IF NEW.observed_location_id IS NOT NULL THEN
        SELECT workspace_id INTO location_workspace
          FROM loans_pawnstoragelocation WHERE id = NEW.observed_location_id;
    END IF;
    IF session_status <> 'OPEN' OR session_workspace <> item_workspace
       OR (NEW.expectation_id IS NOT NULL AND (expected_session <> NEW.session_id OR expected_item <> NEW.collateral_item_id))
       OR (NEW.observed_location_id IS NOT NULL AND location_workspace <> session_workspace) THEN
        RAISE EXCEPTION 'Invalid physical-verification observation boundary.';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION loans_verification_resolution_guard() RETURNS trigger AS $$
DECLARE session_status varchar;
BEGIN
    SELECT session.status INTO session_status
      FROM loans_pawnphysicalverificationobservation observation
      JOIN loans_pawnphysicalverificationsession session ON session.id = observation.session_id
     WHERE observation.id = NEW.observation_id;
    IF session_status <> 'COMPLETED' OR btrim(NEW.reason) = '' THEN
        RAISE EXCEPTION 'Invalid physical-verification resolution boundary.';
    END IF;
    IF NEW.outcome = 'LOST_COMPENSATED' AND
       (NEW.current_market_value IS NULL OR NEW.current_market_value <= 0
        OR NEW.agreed_compensation IS NULL OR NEW.agreed_compensation <= 0
        OR btrim(NEW.compensation_reference) = '') THEN
        RAISE EXCEPTION 'Lost collateral requires compensation evidence.';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER loans_verification_session_guard_trigger
BEFORE UPDATE OR DELETE ON loans_pawnphysicalverificationsession
FOR EACH ROW EXECUTE FUNCTION loans_verification_session_guard();
CREATE TRIGGER loans_verification_expectation_insert_trigger
BEFORE INSERT ON loans_pawnphysicalverificationexpectation
FOR EACH ROW EXECUTE FUNCTION loans_verification_expectation_guard();
CREATE TRIGGER loans_verification_expectation_immutable_trigger
BEFORE UPDATE OR DELETE ON loans_pawnphysicalverificationexpectation
FOR EACH ROW EXECUTE FUNCTION loans_verification_evidence_immutable();
CREATE TRIGGER loans_verification_observation_insert_trigger
BEFORE INSERT ON loans_pawnphysicalverificationobservation
FOR EACH ROW EXECUTE FUNCTION loans_verification_observation_guard();
CREATE TRIGGER loans_verification_observation_immutable_trigger
BEFORE UPDATE OR DELETE ON loans_pawnphysicalverificationobservation
FOR EACH ROW EXECUTE FUNCTION loans_verification_evidence_immutable();
CREATE TRIGGER loans_verification_resolution_insert_trigger
BEFORE INSERT ON loans_pawnphysicalverificationresolution
FOR EACH ROW EXECUTE FUNCTION loans_verification_resolution_guard();
CREATE TRIGGER loans_verification_resolution_immutable_trigger
BEFORE UPDATE OR DELETE ON loans_pawnphysicalverificationresolution
FOR EACH ROW EXECUTE FUNCTION loans_verification_evidence_immutable();
""",
            reverse_sql=r"""
DROP TRIGGER IF EXISTS loans_verification_resolution_immutable_trigger ON loans_pawnphysicalverificationresolution;
DROP TRIGGER IF EXISTS loans_verification_resolution_insert_trigger ON loans_pawnphysicalverificationresolution;
DROP TRIGGER IF EXISTS loans_verification_observation_immutable_trigger ON loans_pawnphysicalverificationobservation;
DROP TRIGGER IF EXISTS loans_verification_observation_insert_trigger ON loans_pawnphysicalverificationobservation;
DROP TRIGGER IF EXISTS loans_verification_expectation_immutable_trigger ON loans_pawnphysicalverificationexpectation;
DROP TRIGGER IF EXISTS loans_verification_expectation_insert_trigger ON loans_pawnphysicalverificationexpectation;
DROP TRIGGER IF EXISTS loans_verification_session_guard_trigger ON loans_pawnphysicalverificationsession;
DROP FUNCTION IF EXISTS loans_verification_resolution_guard();
DROP FUNCTION IF EXISTS loans_verification_observation_guard();
DROP FUNCTION IF EXISTS loans_verification_expectation_guard();
DROP FUNCTION IF EXISTS loans_verification_session_guard();
DROP FUNCTION IF EXISTS loans_verification_evidence_immutable();
""",
        ),
    ]

