# Generated by Django 6.1.1 on 2026-09-26 11:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0009_workspace_role_identity'),
        ('subscriptions', '0011_access_decision_evidence_guard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_hash', models.CharField(max_length=64, unique=True)),
                ('reason', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=150, unique=True)),
                ('recipient', models.EmailField(blank=True, max_length=254)),
                ('source_fingerprint', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('captured', 'Preview only — not sent'), ('sending', 'Sending'), ('accepted', 'Accepted by email provider'), ('delivered', 'Delivered to recipient mail server'), ('failed', 'Failed'), ('unknown', 'Acceptance uncertain — review required'), ('cancelled', 'Cancelled'), ('bounced', 'Bounced'), ('complaint', 'Spam complaint'), ('suppressed', 'Recipient suppressed')], default='queued', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=64)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invitation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='email_delivery', to='orgs.companyinvitation')),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='email_delivery', to='subscriptions.invoice')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='sending', max_length=16)),
                ('provider_message_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='platform_mail.delivery')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ProviderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('kind', models.CharField(max_length=32)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='platform_mail.attempt')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['status', 'available_at'], name='platform_ma_status_b42a16_idx'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('invitation__isnull', False), ('invoice__isnull', True)), models.Q(('invitation__isnull', True), ('invoice__isnull', False)), _connector='OR'), name='platform_mail_one_source'),
        ),
    ]
