# Generated by Django 6.1.1 on 2026-09-29 12:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_emailaddress_unique_primary_email'),
        ('orgs', '0009_workspace_role_identity'),
        ('platform_mail', '0001_initial'),
        ('subscriptions', '0017_recurring_access_resolution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('verification', 'Email verification'), ('password_reset', 'Password reset')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.RemoveConstraint(
            model_name='delivery',
            name='platform_mail_one_source',
        ),
        migrations.AddField(
            model_name='accountemail',
            name='email_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.emailaddress'),
        ),
        migrations.AddField(
            model_name='accountemail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delivery',
            name='account_email',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery', to='platform_mail.accountemail'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('account_email__isnull', True), ('invitation__isnull', False), ('invoice__isnull', True)), models.Q(('account_email__isnull', True), ('invitation__isnull', True), ('invoice__isnull', False)), models.Q(('account_email__isnull', False), ('invitation__isnull', True), ('invoice__isnull', True)), _connector='OR'), name='platform_mail_one_source'),
        ),
    ]
