# Generated by Django 6.0.3 on 2026-04-09 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0003_alter_customer_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('RENDERED', 'Rendered'), ('PRINTED', 'Printed'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('job_count', models.PositiveIntegerField(default=0)),
                ('selection_snapshot', models.JSONField(blank=True, default=list, help_text='Original source selection (for example loan ids) used to create this batch.')),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notify_v2_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='NotificationEventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('domain', models.CharField(choices=[('LOAN', 'Loan / Girvi'), ('SALES', 'Sales'), ('PURCHASE', 'Purchase'), ('INVENTORY', 'Inventory'), ('ACCOUNTING', 'Accounting'), ('HR', 'Human Resources'), ('GENERAL', 'General')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('payload_schema', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['domain', 'sort_order', 'name'],
                'indexes': [models.Index(fields=['domain', 'is_active'], name='notify_v2_n_domain_c946a6_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('source_app', models.CharField(blank=True, max_length=50)),
                ('source_model', models.CharField(blank=True, max_length=100)),
                ('source_pk', models.CharField(blank=True, max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='notify_v2.notificationbatch')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='notify_v2.notificationeventtype')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='notificationbatch',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='notify_v2.notificationeventtype'),
        ),
        migrations.CreateModel(
            name='NotificationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('LETTER', 'Letter'), ('POST', 'Post'), ('IN_APP', 'In-App')], max_length=20)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RENDERED', 'Rendered'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=150)),
                ('failure_reason', models.TextField(blank=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='notify_v2.notificationbatch')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='notify_v2.notificationevent')),
            ],
            options={
                'ordering': ['scheduled_for', 'created'],
            },
        ),
        migrations.CreateModel(
            name='NotificationAttemptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('status_before', models.CharField(blank=True, max_length=20)),
                ('status_after', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_logs', to='notify_v2.notificationjob')),
            ],
            options={
                'ordering': ['job', 'attempt_number', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('artifact_type', models.CharField(choices=[('PDF', 'PDF'), ('HTML', 'HTML'), ('TEXT', 'Text')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='notify_v2/artifacts/')),
                ('rendered_text', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='notify_v2.notificationjob')),
            ],
            options={
                'ordering': ['job', 'artifact_type', '-created'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('LETTER', 'Letter'), ('POST', 'Post'), ('IN_APP', 'In-App')], max_length=20)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_required', models.BooleanField(default=False)),
                ('batch_enabled', models.BooleanField(default=False, help_text='Allow operators to generate this policy as part of a batch print/post run.')),
                ('cooldown_rule', models.JSONField(blank=True, default=dict)),
                ('schedule_rule', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='notify_v2.notificationeventtype')),
            ],
            options={
                'ordering': ['event_type', 'priority', 'channel'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name_snapshot', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('postal_address_json', models.JSONField(blank=True, default=dict)),
                ('preferred_locale', models.CharField(default='en', max_length=10)),
                ('consent_flags', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notify_v2_recipients', to='contact.customer')),
            ],
            options={
                'ordering': ['name_snapshot', 'id'],
            },
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='notify_v2.notificationrecipient'),
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('LETTER', 'Letter'), ('POST', 'Post'), ('IN_APP', 'In-App')], max_length=20)),
                ('locale', models.CharField(default='en', max_length=10)),
                ('renderer_type', models.CharField(choices=[('PDF', 'PDF'), ('DJANGO', 'Django Template'), ('TEXT', 'Plain Text'), ('HTML', 'HTML')], default='DJANGO', max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('subject_template', models.CharField(blank=True, max_length=200)),
                ('body_template', models.TextField(blank=True)),
                ('layout_key', models.CharField(blank=True, max_length=100)),
                ('sample_payload', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='notify_v2.notificationeventtype')),
            ],
            options={
                'ordering': ['event_type', 'channel', 'locale', '-version'],
            },
        ),
        migrations.AddField(
            model_name='notificationjob',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='notify_v2.notificationtemplate'),
        ),
        migrations.AddIndex(
            model_name='notificationbatch',
            index=models.Index(fields=['status', 'created'], name='notify_v2_n_status_32048e_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationpolicy',
            constraint=models.UniqueConstraint(fields=('event_type', 'channel'), name='notify_v2_unique_policy_per_event_channel'),
        ),
        migrations.AddIndex(
            model_name='notificationrecipient',
            index=models.Index(fields=['email'], name='notify_v2_n_email_7867be_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrecipient',
            index=models.Index(fields=['phone'], name='notify_v2_n_phone_1a75fa_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['event_type', 'created'], name='notify_v2_n_event_t_69caae_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationtemplate',
            constraint=models.UniqueConstraint(fields=('event_type', 'channel', 'locale', 'version'), name='notify_v2_unique_template_version'),
        ),
        migrations.AddIndex(
            model_name='notificationjob',
            index=models.Index(fields=['status', 'scheduled_for'], name='notify_v2_n_status_ecf26e_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationjob',
            constraint=models.UniqueConstraint(fields=('event', 'channel'), name='notify_v2_unique_job_per_event_channel'),
        ),
    ]
