# Generated by Django 6.0.3 on 2026-08-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('artifact_type', models.CharField(choices=[('PDF', 'PDF'), ('HTML', 'HTML'), ('TEXT', 'Text')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='notify_v2/artifacts/')),
                ('rendered_text', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['job', 'artifact_type', '-created'],
            },
        ),
        migrations.CreateModel(
            name='NotificationAttemptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('status_before', models.CharField(blank=True, max_length=20)),
                ('status_after', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['job', 'attempt_number', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('RENDERED', 'Rendered'), ('PRINTED', 'Printed'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('job_count', models.PositiveIntegerField(default=0)),
                ('selection_snapshot', models.JSONField(blank=True, default=list, help_text='Original source selection (for example loan ids) used to create this batch.')),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('source_app', models.CharField(blank=True, max_length=50)),
                ('source_model', models.CharField(blank=True, max_length=100)),
                ('source_pk', models.CharField(blank=True, max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, max_length=255)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='NotificationEventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('domain', models.CharField(choices=[('LOAN', 'Loan / Girvi'), ('SALES', 'Sales'), ('PURCHASE', 'Purchase'), ('INVENTORY', 'Inventory'), ('ACCOUNTING', 'Accounting'), ('HR', 'Human Resources'), ('GENERAL', 'General')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('payload_schema', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['domain', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('LETTER', 'Letter'), ('POST', 'Post'), ('IN_APP', 'In-App')], max_length=20)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RENDERED', 'Rendered'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=150)),
                ('failure_reason', models.TextField(blank=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['scheduled_for', 'created'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('LETTER', 'Letter'), ('POST', 'Post'), ('IN_APP', 'In-App')], max_length=20)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_required', models.BooleanField(default=False)),
                ('batch_enabled', models.BooleanField(default=False, help_text='Allow operators to generate this policy as part of a batch print/post run.')),
                ('cooldown_rule', models.JSONField(blank=True, default=dict)),
                ('schedule_rule', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['event_type', 'priority', 'channel'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name_snapshot', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('postal_address_json', models.JSONField(blank=True, default=dict)),
                ('preferred_locale', models.CharField(default='en', max_length=10)),
                ('consent_flags', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name_snapshot', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('LETTER', 'Letter'), ('POST', 'Post'), ('IN_APP', 'In-App')], max_length=20)),
                ('locale', models.CharField(default='en', max_length=10)),
                ('renderer_type', models.CharField(choices=[('PDF', 'PDF'), ('DJANGO', 'Django Template'), ('TEXT', 'Plain Text'), ('HTML', 'HTML')], default='DJANGO', max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('subject_template', models.CharField(blank=True, max_length=200)),
                ('body_template', models.TextField(blank=True)),
                ('layout_key', models.CharField(blank=True, max_length=100)),
                ('sample_payload', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['event_type', 'channel', 'locale', '-version'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppCloudIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('api_version', models.CharField(default='v20.0', max_length=16)),
                ('phone_number_id', models.CharField(max_length=64)),
                ('access_token_ciphertext', models.TextField()),
                ('webhook_verify_token_ciphertext', models.TextField()),
                ('app_secret_ciphertext', models.TextField()),
                ('is_enabled', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhatsAppCloudWebhookReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=64)),
                ('payload_hash', models.CharField(max_length=64)),
                ('phone_number_id', models.CharField(max_length=64)),
                ('provider_message_id', models.CharField(db_index=True, max_length=150)),
                ('external_status', models.CharField(max_length=32)),
                ('provider_timestamp', models.CharField(blank=True, max_length=32)),
                ('signature_digest', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('processing_status', models.CharField(choices=[('PROCESSED', 'Processed'), ('UNKNOWN_JOB', 'Unknown job')], max_length=16)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('last_received_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-received_at', '-pk'),
            },
        ),
    ]
