# Generated by Django 6.0.3 on 2026-08-16 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notify_v2', '0001_initial'),
        ('orgs', '0001_initial'),
        ('party', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationartifact',
            name='workspace',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='notificationattemptlog',
            name='workspace',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='notificationbatch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notify_v2_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationbatch',
            name='workspace',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='notify_v2.notificationbatch'),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='workspace',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='notificationeventtype',
            name='workspace',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='notify_v2.notificationeventtype'),
        ),
        migrations.AddField(
            model_name='notificationbatch',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='notify_v2.notificationeventtype'),
        ),
        migrations.AddField(
            model_name='notificationjob',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='notify_v2.notificationbatch'),
        ),
        migrations.AddField(
            model_name='notificationjob',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='notify_v2.notificationevent'),
        ),
        migrations.AddField(
            model_name='notificationjob',
            name='workspace',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='notificationattemptlog',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_logs', to='notify_v2.notificationjob'),
        ),
        migrations.AddField(
            model_name='notificationartifact',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='notify_v2.notificationjob'),
        ),
        migrations.AddField(
            model_name='notificationpolicy',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='notify_v2.notificationeventtype'),
        ),
        migrations.AddField(
            model_name='notificationpolicy',
            name='workspace',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='notificationrecipient',
            name='party',
            field=models.ForeignKey(blank=True, help_text='Canonical Party receiving this notification when it represents a business counterparty.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notify_v2_recipients', to='party.party'),
        ),
        migrations.AddField(
            model_name='notificationrecipient',
            name='workspace',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='notify_v2.notificationrecipient'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='notify_v2.notificationeventtype'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='workspace',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='notificationjob',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='notify_v2.notificationtemplate'),
        ),
        migrations.AddField(
            model_name='whatsappcloudintegration',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_cloud_integrations_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='whatsappcloudintegration',
            name='workspace',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='whatsapp_cloud_integration', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='whatsappcloudwebhookreceipt',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='whatsapp_webhook_receipts', to='notify_v2.notificationjob'),
        ),
        migrations.AddField(
            model_name='whatsappcloudwebhookreceipt',
            name='workspace',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddIndex(
            model_name='notificationeventtype',
            index=models.Index(fields=['domain', 'is_active'], name='notify_v2_n_domain_c946a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationeventtype',
            constraint=models.UniqueConstraint(fields=('workspace', 'key'), name='notify_v2_workspace_event_type_key_uniq'),
        ),
        migrations.AddIndex(
            model_name='notificationbatch',
            index=models.Index(fields=['status', 'created'], name='notify_v2_n_status_32048e_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationpolicy',
            constraint=models.UniqueConstraint(fields=('workspace', 'event_type', 'channel'), name='notify_v2_unique_policy_per_event_channel'),
        ),
        migrations.AddIndex(
            model_name='notificationrecipient',
            index=models.Index(fields=['email'], name='notify_v2_n_email_7867be_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrecipient',
            index=models.Index(fields=['phone'], name='notify_v2_n_phone_1a75fa_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrecipient',
            index=models.Index(fields=['party', 'is_active'], name='notify_v2_n_party_i_6df4c0_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['event_type', 'created'], name='notify_v2_n_event_t_69caae_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationtemplate',
            constraint=models.UniqueConstraint(fields=('workspace', 'event_type', 'channel', 'locale', 'version'), name='notify_v2_unique_template_version'),
        ),
        migrations.AddIndex(
            model_name='notificationjob',
            index=models.Index(fields=['status', 'scheduled_for'], name='notify_v2_n_status_ecf26e_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationjob',
            constraint=models.UniqueConstraint(fields=('workspace', 'event', 'channel'), name='notify_v2_unique_job_per_event_channel'),
        ),
        migrations.AddConstraint(
            model_name='notificationjob',
            constraint=models.UniqueConstraint(condition=models.Q(('channel', 'WHATSAPP'), models.Q(('provider_message_id', ''), _negated=True)), fields=('workspace', 'provider_message_id'), name='notify_v2_unique_whatsapp_provider_id'),
        ),
        migrations.AddIndex(
            model_name='whatsappcloudwebhookreceipt',
            index=models.Index(fields=['processing_status', 'received_at'], name='notify_wa_receipt_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='whatsappcloudwebhookreceipt',
            constraint=models.UniqueConstraint(fields=('workspace', 'event_key'), name='notify_v2_workspace_webhook_event_uniq'),
        ),
    ]
