# Generated by Django 6.0.3 on 2026-08-13 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify_v2', '0002_notificationrecipient_party'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppCloudWebhookReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=64, unique=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('tenant_schema', models.CharField(max_length=63)),
                ('phone_number_id', models.CharField(max_length=64)),
                ('provider_message_id', models.CharField(db_index=True, max_length=150)),
                ('external_status', models.CharField(max_length=32)),
                ('provider_timestamp', models.CharField(blank=True, max_length=32)),
                ('signature_digest', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('processing_status', models.CharField(choices=[('PROCESSED', 'Processed'), ('UNKNOWN_JOB', 'Unknown job')], max_length=16)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('last_received_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='whatsapp_webhook_receipts', to='notify_v2.notificationjob')),
            ],
            options={
                'ordering': ('-received_at', '-pk'),
                'indexes': [models.Index(fields=['processing_status', 'received_at'], name='notify_wa_receipt_status_idx')],
            },
        ),
    ]
