# Generated by Django 6.0.3 on 2026-08-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify_v2', '0003_whatsappcloudwebhookreceipt'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='notificationjob',
            constraint=models.UniqueConstraint(condition=models.Q(('channel', 'WHATSAPP'), models.Q(('provider_message_id', ''), _negated=True)), fields=('provider_message_id',), name='notify_v2_unique_whatsapp_provider_id'),
        ),
    ]
