# Generated by Django 6.0.3 on 2026-08-13 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify_v2', '0004_notificationjob_notify_v2_unique_whatsapp_provider_id'),
        ('orgs', '0024_alter_auditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppCloudIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('api_version', models.CharField(default='v20.0', max_length=16)),
                ('phone_number_id', models.CharField(max_length=64)),
                ('access_token_ciphertext', models.TextField()),
                ('webhook_verify_token_ciphertext', models.TextField()),
                ('app_secret_ciphertext', models.TextField()),
                ('is_enabled', models.BooleanField(default=False)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_cloud_integrations_updated', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='whatsapp_cloud_integration', to='orgs.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
