# Generated by Django 6.0.3 on 2026-08-16 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify_v2', '0006_remove_notificationrecipient_customer'),
        ('orgs', '0025_alter_company_schema_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notificationjob',
            name='notify_v2_unique_job_per_event_channel',
        ),
        migrations.RemoveConstraint(
            model_name='notificationjob',
            name='notify_v2_unique_whatsapp_provider_id',
        ),
        migrations.RemoveConstraint(
            model_name='notificationpolicy',
            name='notify_v2_unique_policy_per_event_channel',
        ),
        migrations.RemoveConstraint(
            model_name='notificationtemplate',
            name='notify_v2_unique_template_version',
        ),
        migrations.AddField(
            model_name='notificationartifact',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='notificationattemptlog',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='notificationbatch',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='notificationeventtype',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='notificationjob',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='notificationpolicy',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='notificationrecipient',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='whatsappcloudwebhookreceipt',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AlterField(
            model_name='notificationeventtype',
            name='key',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='whatsappcloudintegration',
            name='workspace',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='whatsapp_cloud_integration', to='orgs.company'),
        ),
        migrations.AlterField(
            model_name='whatsappcloudwebhookreceipt',
            name='event_key',
            field=models.CharField(max_length=64),
        ),
        migrations.AddConstraint(
            model_name='notificationeventtype',
            constraint=models.UniqueConstraint(fields=('workspace', 'key'), name='notify_v2_workspace_event_type_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='notificationjob',
            constraint=models.UniqueConstraint(fields=('workspace', 'event', 'channel'), name='notify_v2_unique_job_per_event_channel'),
        ),
        migrations.AddConstraint(
            model_name='notificationjob',
            constraint=models.UniqueConstraint(condition=models.Q(('channel', 'WHATSAPP'), models.Q(('provider_message_id', ''), _negated=True)), fields=('workspace', 'provider_message_id'), name='notify_v2_unique_whatsapp_provider_id'),
        ),
        migrations.AddConstraint(
            model_name='notificationpolicy',
            constraint=models.UniqueConstraint(fields=('workspace', 'event_type', 'channel'), name='notify_v2_unique_policy_per_event_channel'),
        ),
        migrations.AddConstraint(
            model_name='notificationtemplate',
            constraint=models.UniqueConstraint(fields=('workspace', 'event_type', 'channel', 'locale', 'version'), name='notify_v2_unique_template_version'),
        ),
        migrations.AddConstraint(
            model_name='whatsappcloudwebhookreceipt',
            constraint=models.UniqueConstraint(fields=('workspace', 'event_key'), name='notify_v2_workspace_webhook_event_uniq'),
        ),
    ]
