"""Required posting rule keys for seeded voucher types."""

REQUIRED_SEEDED_VOUCHER_TYPE_RULES = {
    "GIVENLOAN_RECEIPT",
    "GIVENLOAN_PAYMENT",
    "TAKENLOAN_RECEIPT",
    "TAKENLOAN_PAYMENT",
    "GIVENLOAN_RELEASE",
    "GIVENLOAN_AUCTION",
    "GIVENLOAN_SOLD",
    "EXPENSE_EMP_CLAIM",
    "EXPENSE_VENDOR_BILL",
    "EXPENSE_DIRECT_PAYMENT",
    "EXPENSE_REIMBURSEMENT",
    "EXPENSE_OTHER",
}
