"""Core persistence models for the side-by-side Loans domain."""

from .core import (
    LoanChangeLog,
    LoanLicense,
    LoanNumberSequence,
    LoanPolicySnapshot,
    LoanSeries,
    PawnCollateralItem,
    PawnCollateralCustodyEvent,
    PawnLoan,
    PawnLoanAccountingEvent,
    PawnLoanAccountingOutbox,
    PawnLoanApprovalSnapshot,
    PawnLoanDisbursalSnapshot,
    PawnLoanInterestAccrual,
    PawnLoanInterestAccrualLine,
    PawnLoanRepaymentAllocationLine,
    PawnLoanPrincipalClosingLine,
    PawnLoanPrincipalOpeningLine,
    PawnLoanEconomicPolicy,
    PawnLoanFeePolicy,
    PawnMetalInterestRatePolicy,
    PawnLoanNotice,
    PawnLoanAuction,
    PawnLoanAuctionItem,
    PawnLoanAuctionReversal,
    PawnLoanRenewal,
    PawnLoanRenewalReversal,
    PawnLoanRelease,
    PawnLoanReleaseItem,
    PawnLoanReleaseReversal,
    current_tenant_workspace_id,
)
from .documents import (
    LoanDocumentAsset,
    LoanDocumentIssue,
    LoanDocumentLayout,
    LoanDocumentLayoutAssignment,
    LoanDocumentLayoutRevision,
    LoanDocumentPrintProfile,
    LoanDocumentPrintProfileAssignment,
    LoanDocumentPrintProfileRevision,
)
from .funding import (
    FundingLoan,
    FundingLoanCancellation,
    FundingLoanDraftCollateral,
    FundingLoanDraftTerms,
    FundingLoanEvent,
    FundingLoanSequence,
    FundingLoanTermsSnapshot,
    FundingPledge,
    FundingPledgeItem,
    FundingPledgeReversal,
    FundingReturn,
    FundingReturnItem,
    FundingReturnReversal,
)
from .regulatory import LoanLicenseRevision
from .media import PawnCollateralLabelIssue, PawnCollateralPhoto
from .storage import PawnCollateralStorageMovement, PawnStorageLocation
from .verification import (
    PawnPhysicalVerificationExpectation,
    PawnPhysicalVerificationObservation,
    PawnPhysicalVerificationResolution,
    PawnPhysicalVerificationSession,
)
from .operational_notices import LoanOperationalNotice
from .products import LoanProduct, LoanProductVersion
from .obligations import (
    ObligationAllocation,
    RepaymentObligation,
    RepaymentScheduleChange,
    RepaymentScheduleChangeKind,
    RepaymentScheduleVersion,
)

__all__ = [
    "LoanChangeLog",
    "LoanLicense",
    "LoanNumberSequence",
    "LoanPolicySnapshot",
    "LoanSeries",
    "PawnCollateralItem",
    "PawnCollateralCustodyEvent",
    "PawnLoan",
    "PawnLoanAccountingEvent",
    "PawnLoanAccountingOutbox",
    "PawnLoanApprovalSnapshot",
    "PawnLoanDisbursalSnapshot",
    "PawnLoanInterestAccrual",
    "PawnLoanInterestAccrualLine",
    "PawnLoanRepaymentAllocationLine",
    "PawnLoanPrincipalClosingLine",
    "PawnLoanPrincipalOpeningLine",
    "PawnLoanEconomicPolicy",
    "PawnLoanFeePolicy",
    "PawnMetalInterestRatePolicy",
    "PawnLoanNotice",
    "PawnLoanAuction",
    "PawnLoanAuctionItem",
    "PawnLoanAuctionReversal",
    "PawnLoanRenewal",
    "PawnLoanRenewalReversal",
    "PawnLoanRelease",
    "PawnLoanReleaseItem",
    "PawnLoanReleaseReversal",
    "current_tenant_workspace_id",
    "LoanDocumentAsset",
    "LoanDocumentIssue",
    "LoanDocumentLayout",
    "LoanDocumentLayoutAssignment",
    "LoanDocumentLayoutRevision",
    "LoanDocumentPrintProfile",
    "LoanDocumentPrintProfileAssignment",
    "LoanDocumentPrintProfileRevision",
    "FundingLoan",
    "FundingLoanCancellation",
    "FundingLoanDraftCollateral",
    "FundingLoanDraftTerms",
    "FundingLoanEvent",
    "FundingLoanSequence",
    "FundingLoanTermsSnapshot",
    "FundingPledge",
    "FundingPledgeItem",
    "FundingPledgeReversal",
    "FundingReturn",
    "FundingReturnItem",
    "FundingReturnReversal",
    "LoanLicenseRevision",
    "PawnCollateralLabelIssue",
    "PawnCollateralPhoto",
    "PawnCollateralStorageMovement",
    "PawnStorageLocation",
    "PawnPhysicalVerificationExpectation",
    "PawnPhysicalVerificationObservation",
    "PawnPhysicalVerificationResolution",
    "PawnPhysicalVerificationSession",
    "LoanOperationalNotice",
    "LoanProduct",
    "LoanProductVersion",
    "LoanRiskAlert",
    "ObligationAllocation",
    "RepaymentObligation",
    "RepaymentScheduleChange",
    "RepaymentScheduleChangeKind",
    "RepaymentScheduleVersion",
]
from .appraisals import CollateralAppraisal
from .communication import PawnLoanCommunicationConsent, PawnLoanCommunicationPolicy
from .monitoring import LoanMonitoringPolicy
from .risk import LoanRiskAlert, LoanRiskEvent, LoanRiskSnapshot

__all__.append("PawnLoanCommunicationConsent")
__all__.append("PawnLoanCommunicationPolicy")
