# Generated by Django 5.2.6 on 2025-11-15 09:42

import django.db.models.deletion
import djmoney.models.fields
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contact", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account",
                        to="contact.customer",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Ledger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Optional manual ordering among siblings"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Stable symbolic key for posting rules (e.g., 'LOAN_RECEIVABLE', 'CASH').",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "is_operating_revenue",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this is an operating revenue account",
                    ),
                ),
                (
                    "is_direct_expense",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this is a direct expense (COGS) account",
                    ),
                ),
                (
                    "is_operating_expense",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this is an operating expense account",
                    ),
                ),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="dea.ledger",
                    ),
                ),
            ],
            options={
                "ordering": ["tree_id", "lft"],
            },
        ),
        migrations.CreateModel(
            name="AccountType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("AccountType", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=100)),
                (
                    "code_prefix",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Leading segment for ledger codes (e.g., 1=Asset, 2=Liability, 4=Income, 5=Expense)",
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccountType_Ext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="EntityType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Entity Type"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionType_DE",
            fields=[
                (
                    "XactTypeCode",
                    models.CharField(max_length=2, primary_key=True, serialize=False),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Transaction Type"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionType_Ext",
            fields=[
                (
                    "XactTypeCode_ext",
                    models.CharField(max_length=4, primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="VoucherType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="AccountBalance",
            fields=[
                (
                    "account",
                    models.OneToOneField(
                        db_column="account_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="dea.account",
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                ("last_statement_date", models.DateTimeField(null=True)),
                (
                    "last_statement_balance",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                (
                    "credit_sum",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                (
                    "debit_sum",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
            ],
            options={
                "db_table": "account_balances",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LedgerBalance",
            fields=[
                (
                    "ledgerno",
                    models.OneToOneField(
                        db_column="ledgerno_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="dea.ledger",
                    ),
                ),
                ("ledger_name", models.CharField(max_length=255)),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("last_statement_date", models.DateTimeField(null=True)),
                (
                    "opening_balance",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                (
                    "ledger_credit_sum",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                (
                    "ledger_debit_sum",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                (
                    "account_credit_sum",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                (
                    "account_debit_sum",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                (
                    "total_credit_sum",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                (
                    "total_debit_sum",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
            ],
            options={
                "db_table": "ledger_balances_mc",
                "managed": False,
            },
        ),
        migrations.AddField(
            model_name="ledger",
            name="AccountType",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ledgers",
                to="dea.accounttype",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="AccountType_Ext",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dea.accounttype_ext"
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="entity",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dea.entitytype",
            ),
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
                ("desc", models.TextField(blank=True, null=True)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "parent_object_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_entries",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "is_reversal_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dea.journalentry",
                    ),
                ),
                (
                    "parent_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_entries",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "get_latest_by": "id",
            },
        ),
        migrations.CreateModel(
            name="LedgerStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "ClosingBalance_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "ClosingBalance",
                    djmoney.models.fields.MoneyField(decimal_places=3, max_digits=13),
                ),
                (
                    "ledgerno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledgerstatements",
                        to="dea.ledger",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "get_latest_by": "created",
            },
        ),
        migrations.CreateModel(
            name="LedgerTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "amount",
                    djmoney.models.fields.MoneyField(decimal_places=3, max_digits=13),
                ),
                (
                    "amount_base_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "amount_base",
                    djmoney.models.fields.MoneyField(
                        blank=True, decimal_places=3, max_digits=13, null=True
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ltxns",
                        to="dea.journalentry",
                    ),
                ),
                (
                    "ledgerno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_txns",
                        to="dea.ledger",
                    ),
                ),
                (
                    "ledgerno_dr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debit_txns",
                        to="dea.ledger",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.AddField(
            model_name="accounttype_ext",
            name="XactTypeCode",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dea.transactiontype_de"
            ),
        ),
        migrations.CreateModel(
            name="AccountTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "amount",
                    djmoney.models.fields.MoneyField(decimal_places=3, max_digits=13),
                ),
                (
                    "Account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounttransactions",
                        to="dea.account",
                    ),
                ),
                (
                    "ledgerno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aleg",
                        to="dea.ledger",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atxns",
                        to="dea.journalentry",
                    ),
                ),
                (
                    "XactTypeCode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dea.transactiontype_de",
                    ),
                ),
                (
                    "XactTypeCode_ext",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dea.transactiontype_ext",
                    ),
                ),
            ],
            options={
                "ordering": ("created",),
            },
        ),
        migrations.CreateModel(
            name="Voucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voucher_no", models.CharField(max_length=100)),
                ("voucher_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("POSTED", "Posted"),
                            ("CORRECTED", "Corrected"),
                            ("REVERSED", "Reversed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("doc_object_id", models.PositiveIntegerField()),
                ("fingerprint", models.CharField(db_index=True, max_length=128)),
                ("last_posted_at", models.DateTimeField(blank=True, null=True)),
                ("narration", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vouchers_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doc_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vouchers_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voucher_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dea.vouchertype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.AddField(
            model_name="journalentry",
            name="voucher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="journal_entries",
                to="dea.voucher",
            ),
        ),
        migrations.CreateModel(
            name="BusinessDoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("auto_post_to_accounting", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="business_docs_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voucher",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_business_doc",
                        to="dea.voucher",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="AccountStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "ClosingBalance_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "ClosingBalance",
                    djmoney.models.fields.MoneyField(decimal_places=3, max_digits=13),
                ),
                (
                    "TotalCredit_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "TotalCredit",
                    djmoney.models.fields.MoneyField(decimal_places=3, max_digits=13),
                ),
                (
                    "TotalDebit_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "TotalDebit",
                    djmoney.models.fields.MoneyField(decimal_places=3, max_digits=13),
                ),
                (
                    "AccountNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accountstatements",
                        to="dea.account",
                    ),
                ),
            ],
            options={
                "ordering": ("created",),
                "get_latest_by": "created",
                "indexes": [
                    models.Index(
                        fields=["AccountNo"], name="dea_account_Account_28e0d6_idx"
                    )
                ],
                "unique_together": {
                    ("AccountNo", "ClosingBalance_currency", "created")
                },
            },
        ),
        migrations.AddConstraint(
            model_name="ledger",
            constraint=models.UniqueConstraint(
                fields=("name", "parent"), name="unique_ledgername_parent"
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                fields=("contact",), name="unique_contact_account"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ledgerstatement",
            unique_together={("ledgerno", "ClosingBalance_currency", "created")},
        ),
        migrations.AddIndex(
            model_name="ledgertransaction",
            index=models.Index(
                fields=["ledgerno"], name="dea_ledgert_ledgern_b79320_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ledgertransaction",
            index=models.Index(
                fields=["ledgerno_dr"], name="dea_ledgert_ledgern_31d496_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ledgertransaction",
            index=models.Index(
                fields=["created"], name="dea_ledgert_created_19d484_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ledgertransaction",
            index=models.Index(
                fields=["journal_entry", "created"],
                name="dea_ledgert_journal_52c0c0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="accounttransaction",
            index=models.Index(
                fields=["ledgerno"], name="dea_account_ledgern_eea025_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="dea_journal_content_9f6430_idx",
            ),
        ),
    ]
