# Generated by Django 4.2rc1 on 2023-03-31 08:45

import mptt
import mptt.managers
from django.db import migrations


def rebuild_ledger(apps, schema_editor):
    manager = mptt.managers.TreeManager()
    Ledger = apps.get_model("dea", "Ledger")
    manager.model = Ledger
    mptt.register(Ledger, order_insertion_by=["name"])
    manager.contribute_to_class(Ledger, "objects")
    manager.rebuild()


def noop_reverse(apps, schema_editor):
    pass


def insertData(apps, schema_editor):
    """
    Insert initial data for DEA app.
    Note: Ledger codes are manually assigned here for initial setup.
    For new ledgers created after migration, codes will be auto-generated.
    """
    entity = apps.get_model("dea", "EntityType")
    entity.objects.bulk_create([entity(name="Person"), entity(name="Organisation")])

    transactiontype_de = apps.get_model("dea", "TransactionType_DE")
    transactiontype_de.objects.bulk_create(
        [
            transactiontype_de(XactTypeCode="Cr", name="Credit"),
            transactiontype_de(XactTypeCode="Dr", name="Debit"),
        ]
    )

    transactiontype_ext = apps.get_model("dea", "TransactionType_Ext")
    transactiontype_ext.objects.bulk_create(
        [
            transactiontype_ext(XactTypeCode_ext="AC", description="Adjust Credit"),
            transactiontype_ext(XactTypeCode_ext="AD", description="Adjust Debit"),
            transactiontype_ext(XactTypeCode_ext="CPU", description="Cash Purchase"),
            transactiontype_ext(XactTypeCode_ext="CRPU", description="Credit Purchase"),
            transactiontype_ext(XactTypeCode_ext="CRSL", description="Credit Sale"),
            transactiontype_ext(XactTypeCode_ext="CSL", description="Cash Sale"),
            transactiontype_ext(XactTypeCode_ext="IP", description="Interest Paid"),
            transactiontype_ext(XactTypeCode_ext="IR", description="Interest Received"),
            transactiontype_ext(XactTypeCode_ext="LG", description="Loan Given"),
            transactiontype_ext(XactTypeCode_ext="LT", description="Loan Taken"),
            transactiontype_ext(XactTypeCode_ext="LR", description="Loan Released"),
            transactiontype_ext(XactTypeCode_ext="LP", description="Loan Paid"),
            transactiontype_ext(XactTypeCode_ext="PYT", description="Payment"),
            transactiontype_ext(XactTypeCode_ext="RCT", description="Receipt"),
            transactiontype_ext(XactTypeCode_ext="DC", description="Document Charge"),
            transactiontype_ext(
                XactTypeCode_ext="CXC", description="Currency Exchange"
            ),
            transactiontype_ext(
                XactTypeCode_ext="RP", description="Repayment"),
        ]
    )

    # Updated AccountType creation with code_prefix
    acc_type = apps.get_model("dea", "AccountType")
    acc_type.objects.bulk_create(
        [
            acc_type(AccountType="Asset", description="Asset", code_prefix="1"),
            acc_type(
                AccountType="Liability", description="Liabilities", code_prefix="2"
            ),
            acc_type(AccountType="Equity", description="Equity", code_prefix="3"),
            acc_type(AccountType="Income", description="Income", code_prefix="4"),
            acc_type(AccountType="Expense", description="Expense", code_prefix="5"),
        ]
    )

    acc_type_ext = apps.get_model("dea", "AccountType_Ext")
    acc_type_ext.objects.bulk_create(
        [
            acc_type_ext(description="Creditor", XactTypeCode_id="Cr"),
            acc_type_ext(description="Debtor", XactTypeCode_id="Dr"),
        ]
    )

    # Updated ledger creation with new fields
    ledger = apps.get_model("dea", "Ledger")

    # Current Assets (Parent)
    ca = ledger.objects.create(
        AccountType_id=1,
        name="Current Assets",
        code="1000",
        sort_order=10,
        lft=0,
        rght=0,
        level=0,
        tree_id=0,
    )

    # Fixed Assets (Parent)
    ledger.objects.create(
        AccountType_id=1,
        name="Fixed Assets",
        code="1500",
        sort_order=20,
        lft=0,
        rght=0,
        level=0,
        tree_id=0,
    )

    # Cash In Hand (Parent under Current Assets)
    cih = ledger.objects.create(
        AccountType_id=1,
        name="Cash In Hand",
        code="1100",
        sort_order=10,
        parent=ca,
        lft=0,
        rght=0,
        level=0,
        tree_id=0,
    )

    # Cash (Child of Cash In Hand)
    ledger.objects.create(
        AccountType_id=1,
        name="Cash",
        code="1101",
        sort_order=10,
        parent=cih,
        lft=0,
        rght=0,
        level=0,
        tree_id=0,
    )

    # Loans & Advances
    ledger.objects.create(
        AccountType_id=1,
        name="Loans & Advances",
        code="1200",
        sort_order=20,
        parent=ca,
        lft=0,
        rght=0,
        level=0,
        tree_id=0,
    )

    # Sundry Debtors
    ledger.objects.create(
        AccountType_id=1,
        name="Sundry Debtors",
        code="1300",
        sort_order=30,
        parent=ca,
        lft=0,
        rght=0,
        level=0,
        tree_id=0,
    )

    # Inventory (Parent)
    inv = ledger.objects.create(
        AccountType_id=1,
        name="Inventory",
        code="1400",
        sort_order=40,
        parent=ca,
        lft=0,
        rght=0,
        level=0,
        tree_id=0,
    )

    # GST Inventory
    ledger.objects.create(
        AccountType_id=1,
        name="GST INV",
        code="1401",
        sort_order=10,
        parent=inv,
        lft=0,
        rght=0,
        level=0,
        tree_id=0,
    )

    # Non-GST Inventory
    ledger.objects.create(
        AccountType_id=1,
        name="Non-GST INV",
        code="1402",
        sort_order=20,
        parent=inv,
        lft=0,
        rght=0,
        level=0,
        tree_id=0,
    )

    # Interest Receivables
    ledger.objects.create(
        AccountType_id=1,
        name="Interest Receivables",
        code="1250",
        sort_order=25,
        parent=ca,
        lft=0,
        rght=0,
        level=0,
        tree_id=0,
    )

    # LIABILITIES
    cl = ledger.objects.create(
        AccountType_id=2,
        name="Current Liabilities",
        code="2000",
        sort_order=10,
        lft=0,
        rght=0,
        level=0,
        tree_id=0,
    )

    # Loans
    ledger.objects.create(
        AccountType_id=2,
        name="Loans",
        code="2100",
        sort_order=10,
        parent=cl,
        lft=0,
        rght=0,
        level=0,
        tree_id=0,
    )

    # Interest Payable
    ledger.objects.create(
        AccountType_id=2,
        name="Interest Payable",
        code="2200",
        sort_order=20,
        parent=cl,
        lft=0,
        rght=0,
        level=0,
        tree_id=0,
    )

    # Sundry Creditors
    ledger.objects.create(
        AccountType_id=2,
        name="Sundry Creditors",
        code="2300",
        sort_order=30,
        parent=cl,
        lft=0,
        rght=0,
        level=0,
        tree_id=0,
    )

    # Duties & Taxes (Parent)
    dt = ledger.objects.create(
        AccountType_id=2,
        name="Duties & Taxes",
        code="2400",
        sort_order=40,
        parent=cl,
        lft=0,
        rght=0,
        level=0,
        tree_id=0,
    )

    # GST Structure
    cgst = ledger.objects.create(
        AccountType_id=2,
        name="CGST",
        code="2410",
        sort_order=10,
        parent=dt,
        lft=0,
        rght=0,
        level=0,
        tree_id=0,
    )
    sgst = ledger.objects.create(
        AccountType_id=2,
        name="SGST",
        code="2420",
        sort_order=20,
        parent=dt,
        lft=0,
        rght=0,
        level=0,
        tree_id=0,
    )
    igst = ledger.objects.create(
        AccountType_id=2,
        name="IGST",
        code="2430",
        sort_order=30,
        parent=dt,
        lft=0,
        rght=0,
        level=0,
        tree_id=0,
    )

    # Input/Output GST accounts
    ledger.objects.create(
        AccountType_id=2,
        name="Input CGST",
        code="2411",
        sort_order=10,
        parent=cgst,
        lft=0,
        rght=0,
        level=0,
        tree_id=0,
    )
    ledger.objects.create(
        AccountType_id=2,
        name="Output CGST",
        code="2412",
        sort_order=20,
        parent=cgst,
        lft=0,
        rght=0,
        level=0,
        tree_id=0,
    )
    ledger.objects.create(
        AccountType_id=2,
        name="Input SGST",
        code="2421",
        sort_order=10,
        parent=sgst,
        lft=0,
        rght=0,
        level=0,
        tree_id=0,
    )
    ledger.objects.create(
        AccountType_id=2,
        name="Output SGST",
        code="2422",
        sort_order=20,
        parent=sgst,
        lft=0,
        rght=0,
        level=0,
        tree_id=0,
    )
    ledger.objects.create(
        AccountType_id=2,
        name="Input IGST",
        code="2431",
        sort_order=10,
        parent=igst,
        lft=0,
        rght=0,
        level=0,
        tree_id=0,
    )
    ledger.objects.create(
        AccountType_id=2,
        name="Output IGST",
        code="2432",
        sort_order=20,
        parent=igst,
        lft=0,
        rght=0,
        level=0,
        tree_id=0,
    )

    # Tax Liability
    ledger.objects.create(
        AccountType_id=2,
        name="Tax Liability",
        code="2500",
        sort_order=50,
        parent=cl,
        lft=0,
        rght=0,
        level=0,
        tree_id=0,
    )

    # Capital Accounts
    ledger.objects.create(
        AccountType_id=2,
        name="Capital",
        code="2600",
        sort_order=60,
        parent=cl,
        lft=0,
        rght=0,
        level=0,
        tree_id=0,
    )
    ledger.objects.create(
        AccountType_id=2,
        name="Capital A/c",
        code="2610",
        sort_order=10,
        parent=cl,
        lft=0,
        rght=0,
        level=0,
        tree_id=0,
    )

    # INCOME ACCOUNTS
    ledger.objects.create(
        AccountType_id=4,
        name="Interest Received",
        code="4100",
        sort_order=10,
        lft=0,
        rght=0,
        level=0,
        tree_id=0,
    )
    ledger.objects.create(
        AccountType_id=4,
        name="Sales",
        code="4200",
        sort_order=20,
        is_operating_revenue=True,
        lft=0,
        rght=0,
        level=0,
        tree_id=0,
    )

    # EXPENSE ACCOUNTS
    ledger.objects.create(
        AccountType_id=5,
        name="Interest Paid",
        code="5100",
        sort_order=10,
        lft=0,
        rght=0,
        level=0,
        tree_id=0,
    )
    ledger.objects.create(
        AccountType_id=5,
        name="Purchase",
        code="5200",
        sort_order=20,
        is_operating_expense=True,
        lft=0,
        rght=0,
        level=0,
        tree_id=0,
    )

    # COGS Structure
    cogs = ledger.objects.create(
        AccountType_id=5,
        name="COGS",
        code="5300",
        sort_order=30,
        is_direct_expense=True,
        lft=0,
        rght=0,
        level=0,
        tree_id=0,
    )
    ledger.objects.create(
        AccountType_id=5,
        name="GST COGS",
        code="5301",
        sort_order=10,
        is_direct_expense=True,
        parent=cogs,
        lft=0,
        rght=0,
        level=0,
        tree_id=0,
    )
    ledger.objects.create(
        AccountType_id=5,
        name="Non-GST COGS",
        code="5302",
        sort_order=20,
        is_direct_expense=True,
        parent=cogs,
        lft=0,
        rght=0,
        level=0,
        tree_id=0,
    )

    # Trading Account
    ledger.objects.create(
        AccountType_id=4,
        name="Trading",
        code="4300",
        sort_order=30,
        lft=0,
        rght=0,
        level=0,
        tree_id=0,
    )

    # EXPENSE LEDGERS (add missing standard categories)
    expense_parent = ledger.objects.create(
        AccountType_id=5,
        name="Expenses",
        code="5999",
        sort_order=99,
        lft=0,
        rght=0,
        level=0,
        tree_id=0,
    )
    expense_ledgers = [
        ("Travel & Transportation", "5901"),
        ("Food & Meals", "5902"),
        ("Accommodation", "5903"),
        ("Professional Services", "5904"),
        ("Office & Supplies", "5905"),
        ("Utilities & Communications", "5906"),
        ("Maintenance & Repair", "5907"),
        ("Marketing & Advertising", "5908"),
        ("Other Expense", "5998"),
    ]
    for name, code in expense_ledgers:
        ledger.objects.create(
            AccountType_id=5,
            name=name,
            code=code,
            sort_order=10,
            parent=expense_parent,
            is_operating_expense=True,
            lft=0,
            rght=0,
            level=0,
            tree_id=0,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("dea", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(insertData),
        migrations.RunPython(rebuild_ledger, noop_reverse),
    ]