# Generated by Django 4.2rc1 on 2023-03-31 08:45

import mptt
import mptt.managers
from django.db import migrations


def rebuild_ledger(apps, schema_editor):
    manager = mptt.managers.TreeManager()
    Ledger = apps.get_model("dea", "Ledger")
    manager.model = Ledger
    mptt.register(Ledger, order_insertion_by=["name"])
    manager.contribute_to_class(Ledger, "objects")
    manager.rebuild()


def noop_reverse(apps, schema_editor):
    pass


def _next_root_segment(ledger_model, account_type):
    prefix = (account_type.code_prefix or "").strip()
    if not prefix:
        raise ValueError(
            f"Missing code_prefix for AccountType={account_type.AccountType}"
        )

    existing_codes = ledger_model.objects.filter(
        parent__isnull=True,
        AccountType=account_type,
    ).values_list("code", flat=True)

    max_seq = 0
    for code in existing_codes:
        if not code:
            continue
        parts = code.split(".")
        if len(parts) >= 2 and parts[0] == prefix:
            try:
                max_seq = max(max_seq, int(parts[1]))
            except ValueError:
                continue
    return max_seq + 1


def _next_child_segment(ledger_model, parent):
    existing_codes = ledger_model.objects.filter(parent=parent).values_list(
        "code", flat=True
    )

    max_seq = 0
    for code in existing_codes:
        if not code or not parent.code:
            continue
        if not code.startswith(parent.code + "."):
            continue
        try:
            segment = int(code.split(".")[-1])
            max_seq = max(max_seq, segment)
        except ValueError:
            continue
    return max_seq + 1


def _generate_code(ledger_model, account_type, parent=None):
    if parent is None:
        seq = _next_root_segment(ledger_model, account_type)
        return f"{account_type.code_prefix}.{seq:02d}"

    if not parent.code:
        raise ValueError(f"Parent ledger '{parent.name}' has no code")
    seq = _next_child_segment(ledger_model, parent)
    return f"{parent.code}.{seq:02d}"


def _create_ledger(ledger_model, account_type, name, sort_order, parent=None, **extra):
    data = {
        "AccountType": account_type,
        "name": name,
        "sort_order": sort_order,
        "parent": parent,
        "code": _generate_code(ledger_model, account_type, parent=parent),
        # Keep MPTT fields initialized; rebuilt at end of migration.
        "lft": 0,
        "rght": 0,
        "level": 0,
        "tree_id": 0,
    }
    data.update(extra)
    return ledger_model.objects.create(**data)


def insertData(apps, schema_editor):
    """
        Insert initial data for DEA app.

        Ledger codes are generated in migration-time using the same hierarchical format
        as runtime numbering:
            - root: <AccountType.code_prefix>.<NN>
            - child: <parent.code>.<NN>

        This avoids hardcoded legacy numeric codes while keeping deterministic bootstrap
        behavior for fresh schema provisioning.
    """
    entity = apps.get_model("dea", "EntityType")
    entity.objects.bulk_create([entity(name="Person"), entity(name="Organisation")])

    transactiontype_de = apps.get_model("dea", "TransactionType_DE")
    transactiontype_de.objects.bulk_create(
        [
            transactiontype_de(XactTypeCode="Cr", name="Credit"),
            transactiontype_de(XactTypeCode="Dr", name="Debit"),
        ]
    )

    transactiontype_ext = apps.get_model("dea", "TransactionType_Ext")
    transactiontype_ext.objects.bulk_create(
        [
            transactiontype_ext(XactTypeCode_ext="AC", description="Adjust Credit"),
            transactiontype_ext(XactTypeCode_ext="AD", description="Adjust Debit"),
            transactiontype_ext(XactTypeCode_ext="CPU", description="Cash Purchase"),
            transactiontype_ext(XactTypeCode_ext="CRPU", description="Credit Purchase"),
            transactiontype_ext(XactTypeCode_ext="CRSL", description="Credit Sale"),
            transactiontype_ext(XactTypeCode_ext="CSL", description="Cash Sale"),
            transactiontype_ext(XactTypeCode_ext="IP", description="Interest Paid"),
            transactiontype_ext(XactTypeCode_ext="IR", description="Interest Received"),
            transactiontype_ext(XactTypeCode_ext="LG", description="Loan Given"),
            transactiontype_ext(XactTypeCode_ext="LT", description="Loan Taken"),
            transactiontype_ext(XactTypeCode_ext="LR", description="Loan Released"),
            transactiontype_ext(XactTypeCode_ext="LP", description="Loan Paid"),
            transactiontype_ext(XactTypeCode_ext="PYT", description="Payment"),
            transactiontype_ext(XactTypeCode_ext="RCT", description="Receipt"),
            transactiontype_ext(XactTypeCode_ext="DC", description="Document Charge"),
            transactiontype_ext(
                XactTypeCode_ext="CXC", description="Currency Exchange"
            ),
            transactiontype_ext(
                XactTypeCode_ext="RP", description="Repayment"),
        ]
    )

    # Updated AccountType creation with code_prefix
    acc_type = apps.get_model("dea", "AccountType")
    acc_type.objects.get_or_create(
        AccountType="Asset",
        defaults={"description": "Asset", "code_prefix": "1"},
    )
    acc_type.objects.get_or_create(
        AccountType="Liability",
        defaults={"description": "Liabilities", "code_prefix": "2"},
    )
    acc_type.objects.get_or_create(
        AccountType="Equity",
        defaults={"description": "Equity", "code_prefix": "3"},
    )
    acc_type.objects.get_or_create(
        AccountType="Income",
        defaults={"description": "Income", "code_prefix": "4"},
    )
    acc_type.objects.get_or_create(
        AccountType="Expense",
        defaults={"description": "Expense", "code_prefix": "5"},
    )

    asset_type = acc_type.objects.get(AccountType="Asset")
    liability_type = acc_type.objects.get(AccountType="Liability")
    equity_type = acc_type.objects.get(AccountType="Equity")
    income_type = acc_type.objects.get(AccountType="Income")
    expense_type = acc_type.objects.get(AccountType="Expense")

    acc_type_ext = apps.get_model("dea", "AccountType_Ext")
    acc_type_ext.objects.get_or_create(description="Creditor", XactTypeCode_id="Cr")
    acc_type_ext.objects.get_or_create(description="Debtor", XactTypeCode_id="Dr")

    # Updated ledger creation with generated hierarchical codes.
    ledger = apps.get_model("dea", "Ledger")

    # ASSETS
    current_assets = _create_ledger(ledger, asset_type, "Current Assets", 10)
    fixed_assets = _create_ledger(ledger, asset_type, "Fixed Assets", 20)

    cash_in_hand = _create_ledger(
        ledger, asset_type, "Cash In Hand", 10, parent=current_assets
    )
    _create_ledger(ledger, asset_type, "Cash", 10, parent=cash_in_hand)
    _create_ledger(ledger, asset_type, "CASH", 20, parent=cash_in_hand)

    bank_accounts = _create_ledger(
        ledger, asset_type, "Bank Accounts", 15, parent=current_assets
    )
    _create_ledger(ledger, asset_type, "Bank Current Account", 10, parent=bank_accounts)
    _create_ledger(ledger, asset_type, "Bank OD Account", 20, parent=bank_accounts)

    loans_adv = _create_ledger(
        ledger, asset_type, "Loans & Advances", 20, parent=current_assets
    )
    _create_ledger(ledger, asset_type, "LOAN_RECEIVABLE", 10, parent=loans_adv)
    _create_ledger(ledger, asset_type, "LOAN_PRINCIPAL_CTRL", 20, parent=loans_adv)
    _create_ledger(ledger, asset_type, "BORROWER_LOAN_CTRL", 30, parent=loans_adv)

    _create_ledger(ledger, asset_type, "Sundry Debtors", 30, parent=current_assets)
    _create_ledger(ledger, asset_type, "Accounts Receivable", 35, parent=current_assets)

    inventory = _create_ledger(ledger, asset_type, "Inventory", 40, parent=current_assets)
    _create_ledger(ledger, asset_type, "GST INV", 10, parent=inventory)
    _create_ledger(ledger, asset_type, "Non-GST INV", 20, parent=inventory)
    _create_ledger(ledger, asset_type, "INVENTORY", 30, parent=inventory)

    _create_ledger(
        ledger, asset_type, "Interest Receivables", 45, parent=current_assets
    )
    _create_ledger(ledger, asset_type, "GST_INPUT_CREDIT", 50, parent=current_assets)
    _create_ledger(ledger, asset_type, "Prepaid Expenses", 55, parent=current_assets)

    _create_ledger(ledger, asset_type, "Plant & Machinery", 10, parent=fixed_assets)
    _create_ledger(ledger, asset_type, "Furniture & Fixtures", 20, parent=fixed_assets)
    _create_ledger(ledger, asset_type, "Office Equipment", 30, parent=fixed_assets)
    _create_ledger(ledger, asset_type, "Vehicles", 40, parent=fixed_assets)
    _create_ledger(ledger, asset_type, "Computer & Peripherals", 50, parent=fixed_assets)

    # LIABILITIES
    current_liabilities = _create_ledger(ledger, liability_type, "Current Liabilities", 10)
    non_current_liabilities = _create_ledger(
        ledger, liability_type, "Non-Current Liabilities", 20
    )

    loans = _create_ledger(ledger, liability_type, "Loans", 10, parent=current_liabilities)
    _create_ledger(ledger, liability_type, "LOAN_PAYABLE", 10, parent=loans)
    _create_ledger(ledger, liability_type, "BORROWING_PRINCIPAL_CTRL", 20, parent=loans)
    _create_ledger(ledger, liability_type, "LENDER_ACCOUNT_CTRL", 30, parent=loans)

    _create_ledger(
        ledger, liability_type, "Interest Payable", 20, parent=current_liabilities
    )
    _create_ledger(
        ledger, liability_type, "Sundry Creditors", 30, parent=current_liabilities
    )
    _create_ledger(
        ledger, liability_type, "ACCOUNTS_PAYABLE", 35, parent=current_liabilities
    )

    duties_taxes = _create_ledger(
        ledger, liability_type, "Duties & Taxes", 40, parent=current_liabilities
    )
    cgst = _create_ledger(ledger, liability_type, "CGST", 10, parent=duties_taxes)
    sgst = _create_ledger(ledger, liability_type, "SGST", 20, parent=duties_taxes)
    igst = _create_ledger(ledger, liability_type, "IGST", 30, parent=duties_taxes)
    _create_ledger(ledger, liability_type, "Input CGST", 10, parent=cgst)
    _create_ledger(ledger, liability_type, "Output CGST", 20, parent=cgst)
    _create_ledger(ledger, liability_type, "Input SGST", 10, parent=sgst)
    _create_ledger(ledger, liability_type, "Output SGST", 20, parent=sgst)
    _create_ledger(ledger, liability_type, "Input IGST", 10, parent=igst)
    _create_ledger(ledger, liability_type, "Output IGST", 20, parent=igst)
    _create_ledger(ledger, liability_type, "TDS_PAYABLE", 40, parent=duties_taxes)

    _create_ledger(ledger, liability_type, "Tax Liability", 50, parent=current_liabilities)
    _create_ledger(ledger, liability_type, "Salary Payable", 55, parent=current_liabilities)
    _create_ledger(ledger, liability_type, "Rent Payable", 60, parent=current_liabilities)
    _create_ledger(ledger, liability_type, "Accrued Expenses", 65, parent=current_liabilities)
    _create_ledger(ledger, liability_type, "Unearned Revenue", 70, parent=current_liabilities)
    _create_ledger(ledger, liability_type, "Term Loan", 10, parent=non_current_liabilities)
    _create_ledger(
        ledger,
        liability_type,
        "Security Deposits",
        20,
        parent=non_current_liabilities,
        is_current_liability=False,
    )

    # EQUITY
    capital = _create_ledger(ledger, equity_type, "Capital", 10)
    _create_ledger(ledger, equity_type, "Capital A/c", 10, parent=capital)
    _create_ledger(ledger, equity_type, "Drawings", 20, parent=capital)
    _create_ledger(ledger, equity_type, "Retained Earnings", 30, parent=capital)
    _create_ledger(ledger, equity_type, "Opening Balance Equity", 40, parent=capital)

    # INCOME
    _create_ledger(ledger, income_type, "Interest Received", 10)
    _create_ledger(ledger, income_type, "INTEREST_INCOME", 12)
    _create_ledger(
        ledger,
        income_type,
        "Sales",
        20,
        is_operating_revenue=True,
    )
    _create_ledger(
        ledger,
        income_type,
        "Service Income",
        30,
        is_operating_revenue=True,
    )
    _create_ledger(
        ledger,
        income_type,
        "Commission Income",
        40,
        is_operating_revenue=True,
    )
    _create_ledger(ledger, income_type, "Other Income", 50)
    _create_ledger(ledger, income_type, "Trading", 60)

    # EXPENSES
    _create_ledger(ledger, expense_type, "Interest Paid", 10)
    _create_ledger(ledger, expense_type, "INTEREST_EXPENSE", 12)
    _create_ledger(
        ledger,
        expense_type,
        "Purchase",
        20,
        is_operating_expense=True,
    )

    cogs = _create_ledger(
        ledger,
        expense_type,
        "COGS",
        30,
        is_direct_expense=True,
    )
    _create_ledger(
        ledger,
        expense_type,
        "GST COGS",
        10,
        parent=cogs,
        is_direct_expense=True,
    )
    _create_ledger(
        ledger,
        expense_type,
        "Non-GST COGS",
        20,
        parent=cogs,
        is_direct_expense=True,
    )

    expense_parent = _create_ledger(ledger, expense_type, "Expenses", 99)
    expense_ledgers = [
        "Travel & Transportation",
        "Food & Meals",
        "Accommodation",
        "Professional Services",
        "Office & Supplies",
        "Utilities & Communications",
        "Maintenance & Repair",
        "Marketing & Advertising",
        "Bank Charges",
        "Salary & Wages",
        "Rent Expense",
        "Insurance Expense",
        "Depreciation Expense",
        "Bad Debts",
        "Other Expense",
    ]
    for index, ledger_name in enumerate(expense_ledgers, start=1):
        _create_ledger(
            ledger,
            expense_type,
            ledger_name,
            index * 10,
            parent=expense_parent,
            is_operating_expense=True,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("dea", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(insertData),
        migrations.RunPython(rebuild_ledger, noop_reverse),
    ]