# Generated by Django 5.1.7 on 2025-03-29 12:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dea", "0002_initial_fixture"),
    ]

    from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dea", "0002_initial_fixture"),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP VIEW IF EXISTS ledger_balance CASCADE;
            DROP VIEW IF EXISTS account_balance CASCADE;
            DROP VIEW IF EXISTS ledger_balances CASCADE;
            DROP VIEW IF EXISTS account_balances CASCADE;

            ALTER TABLE dea_ledgerstatement
                ADD COLUMN IF NOT EXISTS "ClosingBalance_currency" varchar(3) DEFAULT 'INR' NOT NULL;
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_name = 'dea_ledgerstatement'
                      AND column_name = 'ClosingBalance'
                      AND udt_name = '_money_value'
                ) THEN
                    ALTER TABLE dea_ledgerstatement
                        ALTER COLUMN "ClosingBalance" TYPE numeric(13,3)
                        USING CASE
                            WHEN "ClosingBalance" IS NULL OR coalesce(array_length("ClosingBalance", 1), 0) = 0 THEN 0
                            ELSE regexp_replace(("ClosingBalance")[1]::text, '^\\(([-0-9.]+),.*\\)$', '\\1')::numeric
                        END;
                END IF;
            END $$;

            ALTER TABLE dea_accountstatement
                ADD COLUMN IF NOT EXISTS "ClosingBalance_currency" varchar(3) DEFAULT 'INR' NOT NULL;
            ALTER TABLE dea_accountstatement
                ADD COLUMN IF NOT EXISTS "TotalCredit_currency" varchar(3) DEFAULT 'INR' NOT NULL;
            ALTER TABLE dea_accountstatement
                ADD COLUMN IF NOT EXISTS "TotalDebit_currency" varchar(3) DEFAULT 'INR' NOT NULL;
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_name = 'dea_accountstatement'
                      AND column_name = 'ClosingBalance'
                      AND udt_name = '_money_value'
                ) THEN
                    ALTER TABLE dea_accountstatement
                        ALTER COLUMN "ClosingBalance" TYPE numeric(13,3)
                        USING CASE
                            WHEN "ClosingBalance" IS NULL OR coalesce(array_length("ClosingBalance", 1), 0) = 0 THEN 0
                            ELSE regexp_replace(("ClosingBalance")[1]::text, '^\\(([-0-9.]+),.*\\)$', '\\1')::numeric
                        END,
                        ALTER COLUMN "TotalCredit" TYPE numeric(13,3)
                        USING CASE
                            WHEN "TotalCredit" IS NULL OR coalesce(array_length("TotalCredit", 1), 0) = 0 THEN 0
                            ELSE regexp_replace(("TotalCredit")[1]::text, '^\\(([-0-9.]+),.*\\)$', '\\1')::numeric
                        END,
                        ALTER COLUMN "TotalDebit" TYPE numeric(13,3)
                        USING CASE
                            WHEN "TotalDebit" IS NULL OR coalesce(array_length("TotalDebit", 1), 0) = 0 THEN 0
                            ELSE regexp_replace(("TotalDebit")[1]::text, '^\\(([-0-9.]+),.*\\)$', '\\1')::numeric
                        END;
                END IF;
            END $$;
            """,
            migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            # Forward SQL - Create View
            """
                    CREATE OR REPLACE VIEW ledger_balances AS
                     WITH normalized_transactions AS (
         SELECT dea_ledgertransaction.ledgerno_id,
            dea_ledgertransaction.amount_currency AS currency,
            dea_ledgertransaction.amount AS credit_amount,
            0 AS debit_amount,
            dea_ledgertransaction.created,
            'ledger'::text AS source
           FROM dea_ledgertransaction
          WHERE dea_ledgertransaction.ledgerno_id IS NOT NULL
        UNION ALL
         SELECT dea_ledgertransaction.ledgerno_dr_id AS ledgerno_id,
            dea_ledgertransaction.amount_currency AS currency,
            0 AS credit_amount,
            dea_ledgertransaction.amount AS debit_amount,
            dea_ledgertransaction.created,
            'ledger'::text AS source
           FROM dea_ledgertransaction
          WHERE dea_ledgertransaction.ledgerno_dr_id IS NOT NULL
        UNION ALL
         SELECT dea_accounttransaction.ledgerno_id,
            dea_accounttransaction.amount_currency AS currency,
                CASE
                    WHEN dea_accounttransaction."XactTypeCode_id"::text = 'Cr'::text THEN dea_accounttransaction.amount
                    ELSE 0::numeric
                END AS credit_amount,
                CASE
                    WHEN dea_accounttransaction."XactTypeCode_id"::text = 'Dr'::text THEN dea_accounttransaction.amount
                    ELSE 0::numeric
                END AS debit_amount,
            dea_accounttransaction.created,
            'account'::text AS source
           FROM dea_accounttransaction
          WHERE dea_accounttransaction.ledgerno_id IS NOT NULL
        ), latest_statements AS (
         SELECT DISTINCT ON (dea_ledgerstatement.ledgerno_id, dea_ledgerstatement."ClosingBalance_currency") dea_ledgerstatement.ledgerno_id,
            dea_ledgerstatement."ClosingBalance_currency" AS currency,
            dea_ledgerstatement.created AS statement_date,
            COALESCE(dea_ledgerstatement."ClosingBalance", 0::numeric) AS opening_balance
           FROM dea_ledgerstatement
          ORDER BY dea_ledgerstatement.ledgerno_id, dea_ledgerstatement."ClosingBalance_currency", dea_ledgerstatement.created DESC
        ), transaction_sums AS (
         SELECT l_1.id AS ledgerno_id,
            COALESCE(nt.currency, 'INR'::character varying) AS currency,
            COALESCE(ls.opening_balance, 0::numeric) AS opening_balance,
            ls.statement_date,
            COALESCE(sum(
                CASE
                    WHEN nt.source = 'ledger'::text AND (ls.statement_date IS NULL OR nt.created > ls.statement_date) THEN nt.credit_amount
                    ELSE 0::numeric
                END), 0::numeric) AS ledger_credit_sum,
            COALESCE(sum(
                CASE
                    WHEN nt.source = 'ledger'::text AND (ls.statement_date IS NULL OR nt.created > ls.statement_date) THEN nt.debit_amount
                    ELSE 0::numeric
                END), 0::numeric) AS ledger_debit_sum,
            COALESCE(sum(
                CASE
                    WHEN nt.source = 'account'::text AND (ls.statement_date IS NULL OR nt.created > ls.statement_date) THEN nt.credit_amount
                    ELSE 0::numeric
                END), 0::numeric) AS account_credit_sum,
            COALESCE(sum(
                CASE
                    WHEN nt.source = 'account'::text AND (ls.statement_date IS NULL OR nt.created > ls.statement_date) THEN nt.debit_amount
                    ELSE 0::numeric
                END), 0::numeric) AS account_debit_sum
           FROM dea_ledger l_1
             LEFT JOIN normalized_transactions nt ON l_1.id = nt.ledgerno_id
             LEFT JOIN latest_statements ls ON l_1.id = ls.ledgerno_id AND nt.currency::text = ls.currency::text
          GROUP BY l_1.id, nt.currency, ls.opening_balance, ls.statement_date
        )
 SELECT l.id AS ledgerno_id,
    l.name AS ledger_name,
    l."AccountType_id",
    COALESCE(ts.currency, 'INR'::character varying) AS currency,
    ts.statement_date AS last_statement_date,
    COALESCE(ts.opening_balance, 0::numeric) AS opening_balance,
    COALESCE(ts.ledger_credit_sum, 0::numeric) AS ledger_credit_sum,
    COALESCE(ts.ledger_debit_sum, 0::numeric) AS ledger_debit_sum,
    COALESCE(ts.account_credit_sum, 0::numeric) AS account_credit_sum,
    COALESCE(ts.account_debit_sum, 0::numeric) AS account_debit_sum,
    COALESCE(ts.ledger_credit_sum, 0::numeric) + COALESCE(ts.account_credit_sum, 0::numeric) AS total_credit_sum,
    COALESCE(ts.ledger_debit_sum, 0::numeric) + COALESCE(ts.account_debit_sum, 0::numeric) AS total_debit_sum,
    COALESCE(ts.opening_balance, 0::numeric) + COALESCE(ts.ledger_debit_sum + ts.account_debit_sum, 0::numeric) - COALESCE(ts.ledger_credit_sum + ts.account_credit_sum, 0::numeric) AS current_balance
   FROM dea_ledger l
     LEFT JOIN transaction_sums ts ON l.id = ts.ledgerno_id;
            """,
            # Reverse SQL - Drop View
            "DROP VIEW IF EXISTS ledger_balances;",
        ),
        migrations.RunSQL(
            """
            CREATE OR REPLACE VIEW account_balances AS
WITH latest_statements AS (
    SELECT DISTINCT ON ("AccountNo_id", "ClosingBalance_currency")
        "AccountNo_id",
        created,
        "ClosingBalance",
        "ClosingBalance_currency"
    FROM dea_accountstatement
    ORDER BY "AccountNo_id", "ClosingBalance_currency", created DESC
),
credit_sums AS (
    SELECT 
        at."Account_id",
        at.amount_currency,
        COALESCE(sum(
            CASE
                WHEN (ls.created IS NULL OR at.created > ls.created) 
                AND at."XactTypeCode_id" = 'Cr'
                THEN at.amount
                ELSE 0::numeric
            END), 0::numeric) AS credit_sum
    FROM dea_accounttransaction at
    LEFT JOIN latest_statements ls ON 
        at."Account_id" = ls."AccountNo_id" AND 
        at.amount_currency::text = ls."ClosingBalance_currency"::text
    GROUP BY at."Account_id", at.amount_currency
),
debit_sums AS (
    SELECT 
        at."Account_id",
        at.amount_currency,
        COALESCE(sum(
            CASE
                WHEN (ls.created IS NULL OR at.created > ls.created) 
                AND at."XactTypeCode_id" = 'Dr'
                THEN at.amount
                ELSE 0::numeric
            END), 0::numeric) AS debit_sum
    FROM dea_accounttransaction at
    LEFT JOIN latest_statements ls ON 
        at."Account_id" = ls."AccountNo_id" AND 
        at.amount_currency::text = ls."ClosingBalance_currency"::text
    GROUP BY at."Account_id", at.amount_currency
),
currencies AS (
    -- Get unique currencies per account
    SELECT DISTINCT 
        "Account_id",
        amount_currency
    FROM dea_accounttransaction
)
SELECT 
    a.id as account_id,
    a.party_id,
    a."AccountType_Ext_id",
    COALESCE(ls."ClosingBalance_currency", 
        c.amount_currency,
        'INR'::text) as currency,
    COALESCE(ls.created, NULL::timestamp with time zone) as last_statement_date,
    COALESCE(ls."ClosingBalance", 0::numeric) as last_statement_balance,
    COALESCE(cs.credit_sum, 0::numeric) as credit_sum,
    COALESCE(ds.debit_sum, 0::numeric) as debit_sum,
    CASE 
        WHEN a."AccountType_Ext_id" IN 
            (SELECT id FROM dea_accounttype_ext WHERE "XactTypeCode_id" = 'Dr')
        THEN COALESCE(ls."ClosingBalance", 0::numeric) + 
             COALESCE(ds.debit_sum, 0::numeric) - 
             COALESCE(cs.credit_sum, 0::numeric)
        ELSE COALESCE(ls."ClosingBalance", 0::numeric) + 
             COALESCE(cs.credit_sum, 0::numeric) - 
             COALESCE(ds.debit_sum, 0::numeric)
    END as current_balance
FROM dea_account a
LEFT JOIN currencies c ON a.id = c."Account_id"
LEFT JOIN latest_statements ls ON a.id = ls."AccountNo_id" 
    AND c.amount_currency = ls."ClosingBalance_currency"
LEFT JOIN credit_sums cs ON a.id = cs."Account_id"
    AND c.amount_currency = cs.amount_currency
LEFT JOIN debit_sums ds ON a.id = ds."Account_id" 
    AND c.amount_currency = ds.amount_currency;
            """,
            "DROP VIEW IF EXISTS account_balances;",
        ),
    ]
