# Generated by Django 5.1.2 on 2024-12-04 11:31

import django.db.models.deletion
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("dea", "0004_alter_ledgerbalance_table"),
        ("dea", "0005_alter_entitytype_name_alter_transactiontype_de_name"),
        ("dea", "0006_alter_account_entity"),
        ("dea", "0007_auto_20240413_1413"),
        ("dea", "0008_alter_ledgerbalance_options_alter_ledger_accounttype"),
        ("dea", "0009_alter_accounttransaction_ledgerno"),
        ("dea", "0010_alter_journalentry_content_type_and_more"),
        ("dea", "0011_alter_accounttransaction_amount_and_more"),
        ("dea", "0012_alter_ledgertransaction_amount"),
        ("dea", "0013_journalentry_parent_content_type_and_more"),
        ("dea", "0014_alter_accounttransaction_options"),
    ]

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("dea", "0003_views"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="ledgerbalance",
            table="ledger_balance",
        ),
        migrations.AlterField(
            model_name="entitytype",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Entity Type"
            ),
        ),
        migrations.AlterField(
            model_name="transactiontype_de",
            name="name",
            field=models.CharField(
                max_length=10, unique=True, verbose_name="Transaction Type"
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="entity",
            field=models.ForeignKey(
                default="Person",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dea.entitytype",
            ),
        ),
        migrations.AlterModelOptions(
            name="ledgerbalance",
            options={
                "managed": False,
                "ordering": ["ledgerno__AccountType", "ledgerno__name"],
            },
        ),
        migrations.AlterField(
            model_name="ledger",
            name="AccountType",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ledgers",
                to="dea.accounttype",
            ),
        ),
        migrations.AlterField(
            model_name="accounttransaction",
            name="ledgerno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aleg",
                to="dea.ledger",
            ),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accounttransaction",
            name="amount",
            field=djmoney.models.fields.MoneyField(decimal_places=3, max_digits=13),
        ),
        migrations.AlterField(
            model_name="accounttransaction",
            name="amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("AUD", "Australian Dollar"),
                    ("INR", "Indian Rupee"),
                    ("USD", "US Dollar"),
                ],
                default="INR",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="ledgertransaction",
            name="amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("AUD", "Australian Dollar"),
                    ("INR", "Indian Rupee"),
                    ("USD", "US Dollar"),
                ],
                default="INR",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="ledgertransaction",
            name="amount",
            field=djmoney.models.fields.MoneyField(decimal_places=3, max_digits=13),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="parent_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_entries",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="parent_object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_entries",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterModelOptions(
            name="accounttransaction",
            options={"ordering": ("created",)},
        ),
    ]
