# Generated by Django 5.2.6 on 2026-02-21 10:53

import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("dea", "0003_create_ledger_balance_view"),
        ("orgs", "0019_alter_company_members"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountingPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Jan 2024', 'Q1 2024', 'FY 2023-24'",
                        max_length=100,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="Period starts on this date (inclusive)"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(help_text="Period ends on this date (inclusive)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("CLOSED", "Closed"),
                            ("LOCKED", "Locked"),
                        ],
                        default="OPEN",
                        max_length=10,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("closed_date", models.DateTimeField(blank=True, null=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Period notes or closing remarks"
                    ),
                ),
            ],
            options={
                "verbose_name": "Accounting Period",
                "verbose_name_plural": "Accounting Periods",
                "ordering": ["-end_date"],
                "permissions": [
                    ("can_close_period", "Can close accounting periods"),
                    ("can_lock_period", "Can lock closed periods"),
                    ("can_unlock_period", "Can unlock locked periods"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CurrencyConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_currency",
                    models.CharField(
                        default="INR",
                        help_text="Primary currency for this workspace",
                        max_length=3,
                    ),
                ),
                (
                    "enabled_currencies",
                    models.JSONField(
                        default=list,
                        help_text="List of enabled currency codes ['INR', 'USD', 'EUR']",
                    ),
                ),
                (
                    "auto_update_rates",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically fetch exchange rates from external API",
                    ),
                ),
                (
                    "rate_update_frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MANUAL", "Manual Only"),
                        ],
                        default="MANUAL",
                        max_length=20,
                    ),
                ),
                ("last_rate_update", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Currency Configuration",
                "verbose_name_plural": "Currency Configurations",
            },
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_currency",
                    models.CharField(
                        db_index=True,
                        help_text="ISO 4217 currency code (e.g., USD)",
                        max_length=3,
                    ),
                ),
                (
                    "quote_currency",
                    models.CharField(
                        db_index=True,
                        help_text="ISO 4217 currency code (e.g., INR)",
                        max_length=3,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="1 base_currency = rate × quote_currency",
                        max_digits=18,
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        db_index=True, help_text="Date when this rate becomes effective"
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(
                        blank=True,
                        help_text="Date when this rate expires (null = indefinite)",
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual Entry"),
                            ("CENTRAL_BANK", "Central Bank"),
                            ("API", "External API"),
                            ("MARKET", "Market Rate"),
                        ],
                        default="MANUAL",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False, help_text="Locked rates cannot be modified"
                    ),
                ),
            ],
            options={
                "verbose_name": "Exchange Rate",
                "verbose_name_plural": "Exchange Rates",
                "ordering": ["-effective_date", "base_currency", "quote_currency"],
            },
        ),
        migrations.RemoveField(
            model_name="businessdoc",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="businessdoc",
            name="polymorphic_ctype",
        ),
        migrations.RemoveField(
            model_name="businessdoc",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="businessdoc",
            name="voucher",
        ),
        migrations.AlterModelOptions(
            name="account",
            options={"ordering": ("account_number",)},
        ),
        migrations.AlterModelOptions(
            name="journalentry",
            options={
                "get_latest_by": "id",
                "permissions": [
                    ("can_reverse_entry", "Can reverse journal entries"),
                    ("can_delete_posted_entry", "Can delete posted entries"),
                ],
                "verbose_name": "Journal Entry",
                "verbose_name_plural": "Journal Entries",
            },
        ),
        migrations.AlterModelOptions(
            name="voucher",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="journalentry",
            name="dea_journal_content_9f6430_idx",
        ),
        migrations.RemoveField(
            model_name="journalentry",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="journalentry",
            name="object_id",
        ),
        migrations.RemoveField(
            model_name="journalentry",
            name="parent_content_type",
        ),
        migrations.RemoveField(
            model_name="journalentry",
            name="parent_object_id",
        ),
        migrations.RemoveField(
            model_name="voucher",
            name="polymorphic_ctype",
        ),
        migrations.AddField(
            model_name="account",
            name="account_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Auto-generated unique account number",
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="closed_date",
            field=models.DateField(
                blank=True, help_text="Date when account was closed", null=True
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="account",
            name="credit_days",
            field=models.PositiveIntegerField(
                default=0, help_text="Payment terms in days (0 = cash only)"
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="credit_limit",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                help_text="Maximum credit allowed for this account",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="credit_limit_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("AUD", "Australian Dollar"),
                    ("INR", "Indian Rupee"),
                    ("USD", "US Dollar"),
                ],
                default="INR",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="account",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                    ("SUSPENDED", "Suspended"),
                    ("CLOSED", "Closed"),
                ],
                db_index=True,
                default="ACTIVE",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="accountstatement",
            name="is_opening_statement",
            field=models.BooleanField(
                default=False,
                help_text="True if this is an opening balance statement, False if closing",
            ),
        ),
        migrations.AddField(
            model_name="ledgerstatement",
            name="is_opening_statement",
            field=models.BooleanField(
                default=False,
                help_text="True if this is an opening balance statement, False if closing",
            ),
        ),
        migrations.AddField(
            model_name="voucher",
            name="corrected_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="corrections",
                to="dea.voucher",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="AccountType_Ext",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dea.accounttype_ext",
                verbose_name="Account Type",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="entity",
            field=models.ForeignKey(
                default="Person",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dea.entitytype",
                verbose_name="Entity Type",
            ),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="is_reversal_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reversed_by",
                to="dea.journalentry",
            ),
        ),
        migrations.AlterField(
            model_name="voucher",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("POSTED", "Posted"),
                    ("CORRECTED", "Corrected"),
                    ("REVERSED", "Reversed"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["account_number", "status"],
                name="dea_account_account_48063b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["status", "created_at"], name="dea_account_status_051745_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="voucher",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "POSTED")),
                fields=("doc_content_type", "doc_object_id"),
                name="unique_posted_voucher_per_doc",
            ),
        ),
        migrations.AlterModelTable(
            name="ledgerbalance",
            table="ledger_balances",
        ),
        migrations.AddField(
            model_name="accountingperiod",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="closed_periods",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="accountingperiod",
            name="closing_journal_entry",
            field=models.OneToOneField(
                blank=True,
                help_text="Closing entry that closes income/expense accounts",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="closing_period",
                to="dea.journalentry",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="accountstatement",
            unique_together={("AccountNo", "ClosingBalance_currency", "created")},
        ),
        migrations.AddField(
            model_name="accountstatement",
            name="period",
            field=models.ForeignKey(
                blank=True,
                help_text="Accounting period this statement belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_statements",
                to="dea.accountingperiod",
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="period",
            field=models.ForeignKey(
                blank=True,
                help_text="Accounting period this entry belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="journal_entries",
                to="dea.accountingperiod",
            ),
        ),
        migrations.AddField(
            model_name="ledgerstatement",
            name="period",
            field=models.ForeignKey(
                blank=True,
                help_text="Accounting period this statement belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ledger_statements",
                to="dea.accountingperiod",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="accountstatement",
            unique_together={
                ("AccountNo", "ClosingBalance_currency", "created"),
                ("AccountNo", "period", "is_opening_statement"),
            },
        ),
        migrations.AddIndex(
            model_name="accountstatement",
            index=models.Index(
                fields=["period", "is_opening_statement"],
                name="dea_account_period__2492f4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["period", "posted_at"], name="dea_journal_period__25afc6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["voucher", "posted_at"], name="dea_journal_voucher_f90e84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerstatement",
            index=models.Index(
                fields=["ledgerno", "period"], name="dea_ledgers_ledgern_d38489_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerstatement",
            index=models.Index(
                fields=["period", "is_opening_statement"],
                name="dea_ledgers_period__fc69a7_idx",
            ),
        ),
        migrations.AddField(
            model_name="currencyconfiguration",
            name="workspace",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="currency_config",
                to="orgs.company",
            ),
        ),
        migrations.AddField(
            model_name="exchangerate",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exchange_rates_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="BusinessDoc",
        ),
        migrations.AddConstraint(
            model_name="accountingperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gt", models.F("start_date"))),
                name="period_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountingperiod",
            constraint=models.UniqueConstraint(
                fields=("start_date", "end_date"), name="unique_period_per_workspace"
            ),
        ),
        migrations.AddIndex(
            model_name="exchangerate",
            index=models.Index(
                fields=["base_currency", "quote_currency", "effective_date"],
                name="dea_exchang_base_cu_ff535a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="exchangerate",
            index=models.Index(
                fields=["effective_date", "valid_until"],
                name="dea_exchang_effecti_ed71a1_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="exchangerate",
            constraint=models.CheckConstraint(
                condition=models.Q(("rate__gt", 0)), name="positive_exchange_rate"
            ),
        ),
        migrations.AddConstraint(
            model_name="exchangerate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_until__gte", models.F("effective_date")),
                    ("valid_until__isnull", True),
                    _connector="OR",
                ),
                name="valid_date_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="exchangerate",
            constraint=models.UniqueConstraint(
                fields=("base_currency", "quote_currency", "effective_date"),
                name="unique_rate_per_currency_pair_date",
            ),
        ),
    ]
