# Generated by Django 5.0.1 on 2024-02-29 11:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dea", "0003_views"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="ledgerbalance",
            table="ledger_balance",
        ),
    ]
