# Generated by Django 5.2.6 on 2026-02-26 07:15

import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("dea", "0004_accountingperiod_currencyconfiguration_exchangerate_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentVoucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("auto_post_to_accounting", models.BooleanField(default=True)),
                (
                    "payment_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique payment reference (auto-generated)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When cash actually moved (not contract date)",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("DISBURSAL", "Loan Disbursal/Advance"),
                            ("RECEIPT", "Payment Receipt/Repayment"),
                            ("REFUND", "Refund/Reversal"),
                            ("OTHER", "Other Payment"),
                        ],
                        default="OTHER",
                        help_text="Type of payment: DISBURSAL (outflow/advance), RECEIPT (inflow/repayment)",
                        max_length=20,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("RECEIPT", "Receipt (Cash In)"),
                            ("PAYMENT", "Payment (Cash Out)"),
                        ],
                        help_text="RECEIPT=money coming in, PAYMENT=money going out",
                        max_length=10,
                    ),
                ),
                (
                    "source_object_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="ID of the source document instance",
                        null=True,
                    ),
                ),
                (
                    "total_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "total_amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        help_text="Payment amount in original currency",
                        max_digits=14,
                    ),
                ),
                (
                    "principal_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "principal_amount",
                    djmoney.models.fields.MoneyField(
                        blank=True,
                        decimal_places=2,
                        help_text="Principal portion of payment",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "interest_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "interest_amount",
                    djmoney.models.fields.MoneyField(
                        blank=True,
                        decimal_places=2,
                        help_text="Interest portion of payment",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "fee_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "fee_amount",
                    djmoney.models.fields.MoneyField(
                        blank=True,
                        decimal_places=2,
                        help_text="Fee/charge portion of payment",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=1.0,
                        help_text="Exchange rate to base currency (INR) at payment date",
                        max_digits=10,
                    ),
                ),
                (
                    "amount_in_base_currency_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "amount_in_base_currency",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        help_text="Amount converted to base currency using exchange rate",
                        max_digits=14,
                    ),
                ),
                (
                    "is_multicurrency",
                    models.BooleanField(
                        default=False,
                        help_text="True if payment currency differs from base currency",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("BANK", "Bank Transfer"),
                            ("CHEQUE", "Cheque"),
                            ("UPI", "UPI"),
                            ("CARD", "Card"),
                            ("OTHER", "Other"),
                        ],
                        default="CASH",
                        help_text="How the payment was made",
                        max_length=20,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Bank reference, cheque number, transaction ID, etc",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Additional notes about this payment"
                    ),
                ),
                (
                    "is_final_payment",
                    models.BooleanField(
                        default=False, help_text="Mark if this payment closes the loan"
                    ),
                ),
                (
                    "create_release",
                    models.BooleanField(
                        default=False,
                        help_text="If True and GivenLoan, creates Release record after posting",
                    ),
                ),
                (
                    "posted",
                    models.BooleanField(
                        default=False,
                        help_text="True if this payment has been posted to accounting",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reversal_of",
                    models.ForeignKey(
                        blank=True,
                        help_text="If set, this payment is a reversal of another payment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reversals",
                        to="dea.paymentvoucher",
                    ),
                ),
                (
                    "source_content_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Type of source document (GivenLoan, TakenLoan, SalesInvoice, etc)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paymentvoucher_source",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Voucher",
                "verbose_name_plural": "Payment Vouchers",
                "db_table": "dea_paymentvoucher",
                "ordering": ["-payment_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["source_content_type", "source_object_id"],
                        name="dea_payment_source__f1a1e7_idx",
                    ),
                    models.Index(
                        fields=["payment_id"], name="dea_payment_payment_65b50f_idx"
                    ),
                    models.Index(
                        fields=["payment_date"], name="dea_payment_payment_7cf7e0_idx"
                    ),
                    models.Index(
                        fields=["direction"], name="dea_payment_directi_87c891_idx"
                    ),
                ],
            },
        ),
    ]
