# Generated by Django 5.0.1 on 2024-04-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dea", "0004_alter_ledgerbalance_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entitytype",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Entity Type"
            ),
        ),
        migrations.AlterField(
            model_name="transactiontype_de",
            name="name",
            field=models.CharField(
                max_length=10, unique=True, verbose_name="Transaction Type"
            ),
        ),
    ]
