# Generated by Django 5.0.1 on 2024-04-11 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dea", "0005_alter_entitytype_name_alter_transactiontype_de_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="entity",
            field=models.ForeignKey(
                default="Person",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dea.entitytype",
            ),
        ),
    ]
