# Generated by Django 5.2.6 on 2026-02-27 00:49

import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dea", "0005_paymentvoucher"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseVoucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("auto_post_to_accounting", models.BooleanField(default=True)),
                (
                    "expense_number",
                    models.CharField(
                        db_index=True,
                        help_text="Unique expense reference (auto-generated)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "expense_date",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Date of expense",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("EMP_CLAIM", "Employee Expense Claim"),
                            ("VENDOR_BILL", "Vendor Bill"),
                            ("DIRECT_PAYMENT", "Direct Payment/Cash"),
                            ("REIMBURSEMENT", "Reimbursement Request"),
                            ("OTHER", "Other"),
                        ],
                        default="EMP_CLAIM",
                        help_text="Source of expense",
                        max_length=50,
                    ),
                ),
                (
                    "source_doc_id",
                    models.CharField(
                        blank=True,
                        help_text="Reference to source document ID",
                        max_length=100,
                    ),
                ),
                (
                    "party_name",
                    models.CharField(
                        help_text="Name of employee or vendor", max_length=255
                    ),
                ),
                (
                    "party_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email of party (for employee/vendor)",
                        max_length=254,
                    ),
                ),
                (
                    "gross_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "gross_amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Total before tax (sum of line items)",
                        max_digits=14,
                    ),
                ),
                (
                    "tax_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "tax_amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Total GST (CGST + SGST + IGST)",
                        max_digits=14,
                    ),
                ),
                (
                    "taxable_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "taxable_amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Total of taxable items",
                        max_digits=14,
                    ),
                ),
                (
                    "tds_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "tds_amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="TDS withholding (if applicable)",
                        max_digits=14,
                    ),
                ),
                (
                    "net_payable_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "net_payable",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Amount payable (gross + tax - tds)",
                        max_digits=14,
                    ),
                ),
                ("description", models.TextField(help_text="Description of expenses")),
                (
                    "memo",
                    models.CharField(
                        blank=True, help_text="Short memo or reference", max_length=255
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(
                        default=False, help_text="Whether expense has been paid"
                    ),
                ),
                (
                    "paid_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "paid_amount",
                    djmoney.models.fields.MoneyField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount actually paid (if partially paid)",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "paid_date",
                    models.DateField(
                        blank=True, help_text="When payment was made", null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense Voucher",
                "verbose_name_plural": "Expense Vouchers",
                "ordering": ["-expense_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "line_number",
                    models.PositiveIntegerField(
                        default=1, help_text="Line sequence number"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("TRAVEL", "Travel & Transportation"),
                            ("FOOD", "Food & Meals"),
                            ("ACCOMMODATION", "Accommodation"),
                            ("PROFESSIONAL", "Professional Services"),
                            ("OFFICE", "Office & Supplies"),
                            ("UTILITIES", "Utilities & Communications"),
                            ("MAINTENANCE", "Maintenance & Repair"),
                            ("MARKETING", "Marketing & Advertising"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Expense category",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of this line item"),
                ),
                (
                    "amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2, help_text="Amount before tax", max_digits=14
                    ),
                ),
                (
                    "is_taxable",
                    models.BooleanField(
                        default=True, help_text="Whether this item is subject to GST"
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tax rate as percentage (e.g., 5, 12, 18)",
                        max_digits=5,
                    ),
                ),
                (
                    "tax_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "tax_amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Calculated tax amount",
                        max_digits=14,
                    ),
                ),
                (
                    "tds_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="TDS rate as percentage (e.g., 5, 10)",
                        max_digits=5,
                    ),
                ),
                (
                    "tds_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "tds_amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Calculated TDS amount",
                        max_digits=14,
                    ),
                ),
                (
                    "line_total_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "line_total",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        help_text="Total (amount + tax - tds)",
                        max_digits=14,
                    ),
                ),
                (
                    "expense_voucher",
                    models.ForeignKey(
                        help_text="Parent expense voucher",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="dea.expensevoucher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense Line Item",
                "verbose_name_plural": "Expense Line Items",
                "ordering": ["expense_voucher", "line_number"],
            },
        ),
        migrations.CreateModel(
            name="JournalEntryVoucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("auto_post_to_accounting", models.BooleanField(default=True)),
                (
                    "je_number",
                    models.CharField(
                        db_index=True,
                        help_text="Unique journal entry reference (auto-generated)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "je_date",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Journal entry date (may differ from posting date)",
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("CLOSING", "Closing Entry"),
                            ("ACCRUAL", "Accrual"),
                            ("CORRECTION", "Correction/Reversal"),
                            ("ADJUSTMENT", "Period-End Adjustment"),
                            ("INTERCORP", "Inter-Company"),
                            ("EXCHANGE", "Exchange Rate Adjustment"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        help_text="Type of journal entry",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of the journal entry"
                    ),
                ),
                (
                    "memo",
                    models.CharField(
                        blank=True, help_text="Short memo/reference", max_length=255
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Reference to source document (if applicable)",
                        max_length=100,
                    ),
                ),
                (
                    "total_debit_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "total_debit",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Total of all debit lines",
                        max_digits=14,
                    ),
                ),
                (
                    "total_credit_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "total_credit",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Total of all credit lines",
                        max_digits=14,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When journal entry was reviewed",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who reviewed and approved",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_journal_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal Entry Voucher",
                "verbose_name_plural": "Journal Entry Vouchers",
                "ordering": ["-je_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JournalEntryLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "line_number",
                    models.PositiveIntegerField(
                        default=1, help_text="Line sequence number"
                    ),
                ),
                ("ledger_id", models.IntegerField(help_text="GL account ID (Ledger)")),
                (
                    "ledger_name",
                    models.CharField(
                        help_text="GL account name (for display)", max_length=255
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("DR", "Debit"), ("CR", "Credit")],
                        help_text="Debit or Credit side",
                        max_length=2,
                    ),
                ),
                (
                    "amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        help_text="Amount (always positive, side determines direction)",
                        max_digits=14,
                    ),
                ),
                ("description", models.TextField(help_text="Line description")),
                (
                    "journal_entry",
                    models.ForeignKey(
                        help_text="Parent journal entry",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="dea.journalentryvoucher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal Entry Line Item",
                "verbose_name_plural": "Journal Entry Line Items",
                "ordering": ["journal_entry", "line_number"],
            },
        ),
        migrations.AddIndex(
            model_name="expensevoucher",
            index=models.Index(
                fields=["expense_date", "source_type"],
                name="dea_expense_expense_d661fd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="expensevoucher",
            index=models.Index(
                fields=["-created_at"], name="dea_expense_created_6e8bd3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expensevoucher",
            index=models.Index(
                fields=["is_paid"], name="dea_expense_is_paid_fd486d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="expenselineitem",
            unique_together={("expense_voucher", "line_number")},
        ),
        migrations.AddIndex(
            model_name="journalentryvoucher",
            index=models.Index(
                fields=["je_date", "entry_type"], name="dea_journal_je_date_73759c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentryvoucher",
            index=models.Index(
                fields=["-created_at"], name="dea_journal_created_fb5e42_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="journalentrylineitem",
            unique_together={("journal_entry", "line_number")},
        ),
    ]
