# Generated by Django 5.2.6 on 2026-02-27 01:15

import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dea", "0006_expensevoucher_expenselineitem_journalentryvoucher_and_more"),
        ("party", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseInvoiceVoucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("auto_post_to_accounting", models.BooleanField(default=True)),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True, help_text="Vendor's invoice number", max_length=50
                    ),
                ),
                (
                    "internal_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Our internal reference number (auto-generated: PI-YYYY-MM-0001)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "invoice_date",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Date on vendor's invoice",
                    ),
                ),
                (
                    "received_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when goods/services received",
                        null=True,
                    ),
                ),
                (
                    "purchase_type",
                    models.CharField(
                        choices=[
                            ("GOODS", "Goods (Inventory)"),
                            ("SERVICES", "Services (Expense)"),
                            ("ASSETS", "Fixed Assets"),
                            ("OTHER", "Other"),
                        ],
                        default="GOODS",
                        help_text="Type of purchase",
                        max_length=20,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Reference to PO, GRN, or other document",
                        max_length=100,
                    ),
                ),
                (
                    "subtotal_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "subtotal",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        help_text="Subtotal before taxes",
                        max_digits=14,
                    ),
                ),
                (
                    "discount_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "discount_amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Total discount amount",
                        max_digits=14,
                    ),
                ),
                (
                    "taxable_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "taxable_amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        help_text="Amount subject to tax",
                        max_digits=14,
                    ),
                ),
                (
                    "cgst_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "cgst_amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="CGST amount",
                        max_digits=14,
                    ),
                ),
                (
                    "sgst_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "sgst_amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="SGST amount",
                        max_digits=14,
                    ),
                ),
                (
                    "igst_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "igst_amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="IGST amount",
                        max_digits=14,
                    ),
                ),
                (
                    "tds_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "tds_amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="TDS withheld (if applicable)",
                        max_digits=14,
                    ),
                ),
                (
                    "total_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "total_amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        help_text="Grand total (taxable + taxes)",
                        max_digits=14,
                    ),
                ),
                (
                    "net_payable_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "net_payable",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        help_text="Net payable to vendor (total - tds)",
                        max_digits=14,
                    ),
                ),
                (
                    "paid_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "paid_amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Amount paid to vendor",
                        max_digits=14,
                    ),
                ),
                (
                    "is_fully_paid",
                    models.BooleanField(
                        default=False, help_text="Whether invoice is fully paid"
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        blank=True,
                        help_text="Payment terms from vendor",
                        max_length=100,
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, help_text="Payment due date", null=True
                    ),
                ),
                ("description", models.TextField(help_text="Invoice description")),
                ("notes", models.TextField(blank=True, help_text="Invoice notes")),
                (
                    "memo",
                    models.CharField(
                        blank=True, help_text="Internal memo", max_length=255
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        help_text="Canonical supplier Party.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dea_purchase_invoices",
                        to="party.party",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Invoice Voucher",
                "verbose_name_plural": "Purchase Invoice Vouchers",
                "ordering": ["-invoice_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseInvoiceLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "line_number",
                    models.PositiveIntegerField(
                        default=1, help_text="Line item sequence"
                    ),
                ),
                (
                    "item_code",
                    models.CharField(
                        blank=True, help_text="Product/item code", max_length=50
                    ),
                ),
                ("description", models.TextField(help_text="Item description")),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=1,
                        help_text="Quantity purchased",
                        max_digits=10,
                    ),
                ),
                (
                    "unit_price_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "unit_price",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2, help_text="Price per unit", max_digits=14
                    ),
                ),
                (
                    "line_total_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "line_total",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2, help_text="Line total", max_digits=14
                    ),
                ),
                (
                    "hsn_code",
                    models.CharField(blank=True, help_text="HSN code", max_length=20),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="GST rate", max_digits=5
                    ),
                ),
                (
                    "cgst_rate",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="CGST rate", max_digits=5
                    ),
                ),
                (
                    "sgst_rate",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="SGST rate", max_digits=5
                    ),
                ),
                (
                    "igst_rate",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="IGST rate", max_digits=5
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        help_text="Parent invoice",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="dea.purchaseinvoicevoucher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Invoice Line Item",
                "verbose_name_plural": "Purchase Invoice Line Items",
                "ordering": ["invoice", "line_number"],
            },
        ),
        migrations.CreateModel(
            name="SalesInvoiceVoucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("auto_post_to_accounting", models.BooleanField(default=True)),
                (
                    "invoice_number",
                    models.CharField(
                        db_index=True,
                        help_text="Unique invoice reference (auto-generated: INV-YYYY-MM-0001)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "invoice_date",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Date of invoice",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Reference to sales order or other document",
                        max_length=100,
                    ),
                ),
                (
                    "subtotal_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "subtotal",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        help_text="Subtotal before taxes and discounts",
                        max_digits=14,
                    ),
                ),
                (
                    "discount_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "discount_amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Total discount amount",
                        max_digits=14,
                    ),
                ),
                (
                    "taxable_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "taxable_amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        help_text="Amount subject to tax (subtotal - discount)",
                        max_digits=14,
                    ),
                ),
                (
                    "cgst_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "cgst_amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="CGST (Central GST)",
                        max_digits=14,
                    ),
                ),
                (
                    "sgst_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "sgst_amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="SGST (State GST)",
                        max_digits=14,
                    ),
                ),
                (
                    "igst_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "igst_amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="IGST (Integrated GST) for interstate",
                        max_digits=14,
                    ),
                ),
                (
                    "tcs_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "tcs_amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="TCS (Tax Collected at Source)",
                        max_digits=14,
                    ),
                ),
                (
                    "total_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "total_amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        help_text="Grand total (taxable + taxes + tcs)",
                        max_digits=14,
                    ),
                ),
                (
                    "received_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "received_amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Amount received from customer",
                        max_digits=14,
                    ),
                ),
                (
                    "is_fully_paid",
                    models.BooleanField(
                        default=False, help_text="Whether invoice is fully paid"
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        blank=True,
                        help_text="Payment terms (e.g., Net 30 days)",
                        max_length=100,
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, help_text="Payment due date", null=True
                    ),
                ),
                ("description", models.TextField(help_text="Invoice description")),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Invoice notes/terms"),
                ),
                (
                    "memo",
                    models.CharField(
                        blank=True, help_text="Internal memo", max_length=255
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        help_text="Canonical customer Party.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dea_sales_invoices",
                        to="party.party",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Invoice Voucher",
                "verbose_name_plural": "Sales Invoice Vouchers",
                "ordering": ["-invoice_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalesInvoiceLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "line_number",
                    models.PositiveIntegerField(
                        default=1, help_text="Line item sequence"
                    ),
                ),
                (
                    "item_code",
                    models.CharField(
                        blank=True, help_text="Product/service code", max_length=50
                    ),
                ),
                ("description", models.TextField(help_text="Item description")),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=1,
                        help_text="Quantity sold",
                        max_digits=10,
                    ),
                ),
                (
                    "unit_price_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "unit_price",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2, help_text="Price per unit", max_digits=14
                    ),
                ),
                (
                    "line_total_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "line_total",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        help_text="Line total (quantity * unit_price)",
                        max_digits=14,
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Discount percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "discount_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "discount_amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Discount amount",
                        max_digits=14,
                    ),
                ),
                (
                    "hsn_code",
                    models.CharField(
                        blank=True, help_text="HSN/SAC code for GST", max_length=20
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="GST rate percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "cgst_rate",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="CGST rate", max_digits=5
                    ),
                ),
                (
                    "sgst_rate",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="SGST rate", max_digits=5
                    ),
                ),
                (
                    "igst_rate",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="IGST rate", max_digits=5
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        help_text="Parent invoice",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="dea.salesinvoicevoucher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Invoice Line Item",
                "verbose_name_plural": "Sales Invoice Line Items",
                "ordering": ["invoice", "line_number"],
            },
        ),
        migrations.AddIndex(
            model_name="purchaseinvoicevoucher",
            index=models.Index(
                fields=["invoice_date", "party"], name="dea_purchas_invoice_f0c565_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseinvoicevoucher",
            index=models.Index(
                fields=["purchase_type", "is_fully_paid"],
                name="dea_purchas_purchas_45c895_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseinvoicevoucher",
            index=models.Index(
                fields=["created_at"], name="dea_purchas_created_f1bb30_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="purchaseinvoicelineitem",
            unique_together={("invoice", "line_number")},
        ),
        migrations.AddIndex(
            model_name="salesinvoicevoucher",
            index=models.Index(
                fields=["invoice_date", "party"],
                name="dea_salesin_invoice_3db705_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="salesinvoicevoucher",
            index=models.Index(
                fields=["is_fully_paid"], name="dea_salesin_is_full_5773f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesinvoicevoucher",
            index=models.Index(
                fields=["created_at"], name="dea_salesin_created_43f174_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="salesinvoicelineitem",
            unique_together={("invoice", "line_number")},
        ),
    ]
