# Generated by Django 5.2.6 on 2026-02-27 01:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dea", "0007_purchaseinvoicevoucher_purchaseinvoicelineitem_and_more"),
    ]

    operations = []
