# Generated by Django 5.0.1 on 2024-04-14 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dea", "0007_auto_20240413_1413"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ledgerbalance",
            options={
                "managed": False,
                "ordering": ["ledgerno__AccountType", "ledgerno__name"],
            },
        ),
        migrations.AlterField(
            model_name="ledger",
            name="AccountType",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ledgers",
                to="dea.accounttype",
            ),
        ),
    ]
