# Generated by Django 5.2.6 on 2026-02-27 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0003_alter_customer_options_and_more"),
        ("dea", "0007_purchaseinvoicevoucher_purchaseinvoicelineitem_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseinvoicevoucher",
            name="vendor",
            field=models.ForeignKey(
                help_text="Vendor who supplied",
                limit_choices_to={"customer_type": "S"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_invoices",
                to="contact.customer",
            ),
        ),
    ]
