# Generated by Django 5.0.1 on 2024-06-13 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("dea", "0009_alter_accounttransaction_ledgerno"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalentry",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
