# Generated by Django 6.0.3 on 2026-03-23 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dea', '0010_seed_girvi_release_vouchertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_number', models.PositiveIntegerField(default=1, help_text='Next available sequence number')),
                ('prefix', models.CharField(blank=True, help_text='Custom prefix for this voucher type (e.g., INV, PYT, RCT)', max_length=10)),
                ('period', models.ForeignKey(blank=True, help_text='Period for this sequence (null = not period-specific)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voucher_sequences', to='dea.accountingperiod')),
                ('voucher_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_sequences', to='dea.vouchertype')),
            ],
            options={
                'verbose_name': 'Voucher Number Sequence',
                'verbose_name_plural': 'Voucher Number Sequences',
                'indexes': [models.Index(fields=['voucher_type', 'period'], name='dea_voucher_voucher_f31c05_idx')],
                'unique_together': {('voucher_type', 'period')},
            },
        ),
    ]
