# Generated by Django 5.0.1 on 2024-06-13 06:19

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dea", "0010_alter_journalentry_content_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounttransaction",
            name="amount",
            field=djmoney.models.fields.MoneyField(decimal_places=3, max_digits=13),
        ),
        migrations.AlterField(
            model_name="accounttransaction",
            name="amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("AUD", "Australian Dollar"),
                    ("INR", "Indian Rupee"),
                    ("USD", "US Dollar"),
                ],
                default="INR",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="ledgertransaction",
            name="amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("AUD", "Australian Dollar"),
                    ("INR", "Indian Rupee"),
                    ("USD", "US Dollar"),
                ],
                default="INR",
                editable=False,
                max_length=3,
            ),
        ),
    ]
