# Generated by Django 5.0.8 on 2024-08-31 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("dea", "0012_alter_ledgertransaction_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="parent_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_entries",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="parent_object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_entries",
                to="contenttypes.contenttype",
            ),
        ),
    ]
