# Generated by Django 6.0.3 on 2026-03-26 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dea', '0012_seed_expense_vouchertypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerCodeSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_seq', models.PositiveIntegerField(default=1)),
                ('account_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dea.accounttype')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_code_seq', to='dea.ledger')),
            ],
            options={
                'unique_together': {('parent', 'account_type')},
            },
        ),
    ]
