# Generated by Django 5.0.8 on 2024-10-04 12:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dea", "0013_journalentry_parent_content_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accounttransaction",
            options={"ordering": ("created",)},
        ),
    ]
