# Generated by Django 5.0.8 on 2025-02-16 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0017_alter_contact_is_default"),
        (
            "dea",
            "0004_alter_ledgerbalance_table_squashed_0014_alter_accounttransaction_options",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ledgerbalance",
            options={"managed": False},
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                fields=("contact",), name="unique_contact_account"
            ),
        ),
        migrations.AddConstraint(
            model_name="ledger",
            constraint=models.UniqueConstraint(
                fields=("name", "parent"), name="unique_ledgername_parent"
            ),
        ),
        migrations.AlterModelTable(
            name="ledgerbalance",
            table="resultlb1",
        ),
    ]
