# Generated by Django 6.0.3 on 2026-03-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dea', '0014_seed_expense_ledgers'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='is_current_asset',
            field=models.BooleanField(default=True, help_text='Asset accounts: True = current, False = fixed/non-current'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='is_current_liability',
            field=models.BooleanField(default=True, help_text='Liability accounts: True = current, False = long-term'),
        ),
    ]
