# Generated by Django 5.0.8 on 2025-03-24 12:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dea", "0015_alter_ledgerbalance_options_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="ledgerbalance",
            table="resultlb11",
        ),
    ]
