# Generated by Django 6.0.3 on 2026-05-01 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dea', '0016_remove_currencyconfiguration_workspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-generated unique account number', max_length=20, unique=True),
        ),
    ]
