# Generated by Django 6.0.3 on 2026-05-10 06:01

import django.db.models.deletion
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dea', '0020_repair_ledgertransaction_amount_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField(help_text='1-based sequence within voucher')),
                ('side', models.CharField(choices=[('Dr', 'Debit'), ('Cr', 'Credit')], max_length=2)),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('AUD', 'Australian Dollar'), ('INR', 'Indian Rupee'), ('USD', 'US Dollar')], default='INR', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('amount_base_currency', djmoney.models.fields.CurrencyField(choices=[('AUD', 'Australian Dollar'), ('INR', 'Indian Rupee'), ('USD', 'US Dollar')], default='INR', editable=False, max_length=3, null=True)),
                ('amount_base', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, help_text='Base-currency amount for reporting checks', max_digits=14, null=True)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1, max_digits=12)),
                ('xact_type_ext', models.CharField(default='TXN', max_length=4)),
                ('tax_code', models.CharField(blank=True, max_length=20)),
                ('narration', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, help_text='Optional party/subledger attribution', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voucher_lines', to='dea.account')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_lines', to='dea.ledger')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='dea.voucher')),
            ],
            options={
                'ordering': ['line_no', 'id'],
                'indexes': [models.Index(fields=['voucher', 'side'], name='dea_voucher_voucher_e27d5c_idx'), models.Index(fields=['ledger', 'side'], name='dea_voucher_ledger__2efb56_idx'), models.Index(fields=['account', 'side'], name='dea_voucher_account_9dec35_idx')],
                'constraints': [models.UniqueConstraint(fields=('voucher', 'line_no'), name='uniq_voucher_line_no'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='voucherline_amount_positive')],
            },
        ),
    ]
