# Generated by Django 6.0.3 on 2026-05-10 07:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dea', '0021_voucherline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['POSTED', 'CORRECTED'])), fields=('fingerprint',), name='unique_fingerprint_active'),
        ),
    ]
