# Generated by Django 6.0.3 on 2026-05-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dea', '0022_unique_fingerprint_active'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vouchernumbersequence',
            name='dea_voucher_voucher_f31c05_idx',
        ),
        migrations.AlterUniqueTogether(
            name='vouchernumbersequence',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='vouchernumbersequence',
            name='date_key',
            field=models.CharField(blank=True, default='', help_text='YYYYMMDD key used by date-based sequences (empty for period/global sequences)', max_length=8),
        ),
        migrations.AlterUniqueTogether(
            name='vouchernumbersequence',
            unique_together={('voucher_type', 'period', 'date_key')},
        ),
        migrations.AddIndex(
            model_name='vouchernumbersequence',
            index=models.Index(fields=['voucher_type', 'period', 'date_key'], name='dea_voucher_voucher_6b1efe_idx'),
        ),
    ]
