# Generated by Django 6.0.3 on 2026-05-10 16:50

import django.db.models.deletion
import djmoney.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dea', '0023_voucher_sequence_date_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_post_to_accounting', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('purchase_date', models.DateField()),
                ('cost_currency', djmoney.models.fields.CurrencyField(choices=[('AUD', 'Australian Dollar'), ('INR', 'Indian Rupee'), ('USD', 'US Dollar')], default='INR', editable=False, max_length=3)),
                ('cost', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('salvage_value_currency', djmoney.models.fields.CurrencyField(choices=[('AUD', 'Australian Dollar'), ('INR', 'Indian Rupee'), ('USD', 'US Dollar')], default='INR', editable=False, max_length=3)),
                ('salvage_value', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('useful_life_months', models.PositiveIntegerField()),
                ('method', models.CharField(choices=[('SLM', 'Straight Line Method'), ('WDV', 'Written Down Value')], default='SLM', max_length=3)),
                ('acc_dep_ledger', models.ForeignKey(help_text='Accumulated depreciation ledger', on_delete=django.db.models.deletion.PROTECT, related_name='accumulated_depreciation_assets', to='dea.ledger')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('dep_exp_ledger', models.ForeignKey(help_text='Depreciation expense ledger', on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_expense_assets', to='dea.ledger')),
                ('ledger', models.ForeignKey(help_text='Asset GL ledger', on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets', to='dea.ledger')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['purchase_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DepreciationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('AUD', 'Australian Dollar'), ('INR', 'Indian Rupee'), ('USD', 'US Dollar')], default='INR', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_schedules', to='dea.accountingperiod')),
                ('posted_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_schedules', to='dea.voucher')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_schedules', to='dea.fixedasset')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('asset', 'period'), name='unique_depreciation_schedule_asset_period')],
            },
        ),
    ]
