# Generated by Django 6.0.3 on 2026-05-10 17:28

import django.db.models.deletion
import djmoney.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dea', '0025_depreciation_schedule_business_doc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrepaidExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_post_to_accounting', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_amount_currency', djmoney.models.fields.CurrencyField(choices=[('AUD', 'Australian Dollar'), ('INR', 'Indian Rupee'), ('USD', 'US Dollar')], default='INR', editable=False, max_length=3)),
                ('total_amount', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('expense_ledger', models.ForeignKey(help_text='Expense ledger for amortization', on_delete=django.db.models.deletion.PROTECT, related_name='prepaid_expense_ledgers', to='dea.ledger')),
                ('prepaid_ledger', models.ForeignKey(help_text='Asset ledger for prepaid expense', on_delete=django.db.models.deletion.PROTECT, related_name='prepaid_expenses', to='dea.ledger')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PrepaidScheduleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_post_to_accounting', models.BooleanField(default=True)),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('AUD', 'Australian Dollar'), ('INR', 'Indian Rupee'), ('USD', 'US Dollar')], default='INR', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepaid_schedule_lines', to='dea.accountingperiod')),
                ('posted_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prepaid_schedule_lines', to='dea.voucher')),
                ('prepaid_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_lines', to='dea.prepaidexpense')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('prepaid_expense', 'period'), name='unique_prepaid_schedule_expense_period')],
            },
        ),
    ]
