# Generated by Django 6.0.3 on 2026-05-10 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dea', '0026_prepaid_expense_schedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='dea.ledger')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=14)),
                ('amount_currency', models.CharField(default='INR', max_length=3)),
                ('running_balance', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('running_balance_currency', models.CharField(default='INR', max_length=3)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_lines', to='dea.bankaccount')),
            ],
            options={
                'ordering': ['statement_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('is_manual', models.BooleanField(default=False)),
                ('bank_statement_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_matches', to='dea.bankstatementline')),
                ('ledger_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_matches', to='dea.ledgertransaction')),
                ('matched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_reconciliation_matches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='bankstatementline',
            index=models.Index(fields=['bank_account', 'statement_date'], name='dea_banksta_bank_ac_d1f8c0_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementline',
            index=models.Index(fields=['is_reconciled'], name='dea_banksta_is_reco_da3b43_idx'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationmatch',
            constraint=models.UniqueConstraint(fields=('bank_statement_line', 'ledger_transaction'), name='unique_bank_ledger_reconciliation_match'),
        ),
    ]
