# Generated by Django 6.0.3 on 2026-05-10 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dea', '0027_bank_reconciliation_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('VOUCHER_CREATED', 'Voucher Created'), ('VOUCHER_POSTED', 'Voucher Posted'), ('VOUCHER_REVERSED', 'Voucher Reversed'), ('JOURNAL_ENTRY_CREATED', 'Journal Entry Created'), ('PERIOD_CLOSED', 'Period Closed'), ('PERIOD_LOCKED', 'Period Locked'), ('PERIOD_UNLOCKED', 'Period Unlocked'), ('LEDGER_CREATED', 'Ledger Created'), ('OPENING_BALANCE_SET', 'Opening Balance Set'), ('SETTLEMENT_CREATED', 'Settlement Created'), ('BANK_RECONCILIATION_MATCHED', 'Bank Line Matched'), ('BANK_RECONCILIATION_UNMATCHED', 'Bank Line Unmatched'), ('APPROVAL_REQUESTED', 'Approval Requested'), ('APPROVAL_APPROVED', 'Approval Granted'), ('APPROVAL_REJECTED', 'Approval Rejected')], db_index=True, help_text='Type of accounting event', max_length=40)),
                ('object_id', models.PositiveIntegerField(help_text='ID of the object affected')),
                ('payload_before', models.JSONField(blank=True, help_text='Object state before the action (null for creates)', null=True)),
                ('payload_after', models.JSONField(help_text='Object state after the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which the action was performed', null=True)),
                ('description', models.TextField(blank=True, help_text='Human-readable description of the action')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the event occurred')),
                ('actor', models.ForeignKey(help_text='User who performed the action', on_delete=django.db.models.deletion.PROTECT, related_name='accounting_audit_events', to=settings.AUTH_USER_MODEL)),
                ('object_type', models.ForeignKey(help_text='Type of object affected (e.g., Voucher, JournalEntry)', on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Accounting Audit Event',
                'verbose_name_plural': 'Accounting Audit Events',
                'ordering': ['-occurred_at'],
                'permissions': [('view_accounting_audit_event', 'Can view accounting audit events')],
                'default_permissions': ('view',),
                'indexes': [models.Index(fields=['event_type', 'occurred_at'], name='dea_account_event_t_dd435d_idx'), models.Index(fields=['actor', 'occurred_at'], name='dea_account_actor_i_352f09_idx'), models.Index(fields=['object_type', 'object_id'], name='dea_account_object__952f24_idx'), models.Index(fields=['occurred_at'], name='dea_account_occurre_47f9c6_idx')],
            },
        ),
    ]
