# Generated by Django 6.0.3 on 2026-06-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dea', '0028_accountingauditevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentvoucher',
            name='create_release',
            field=models.BooleanField(default=False, help_text='If True and GivenLoan, this receipt is classified as a release receipt'),
        ),
    ]
