# Generated by Django 6.0.3 on 2026-06-16 10:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dea', '0029_alter_paymentvoucher_create_release'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='voucher',
            name='unique_posted_voucher_per_doc',
        ),
        migrations.AlterField(
            model_name='voucher',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'POSTED')), fields=('doc_content_type', 'doc_object_id', 'voucher_type'), name='unique_posted_voucher_per_doc_type'),
        ),
    ]
