# Generated by Django 6.0.3 on 2026-06-18 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_customer_party'),
        ('dea', '0030_remove_voucher_unique_posted_voucher_per_doc_and_more'),
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyAccountMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_key', models.CharField(db_index=True, max_length=64)),
                ('purpose', models.CharField(choices=[('CUSTOMER_RECEIVABLE', 'Customer Receivable'), ('SUPPLIER_PAYABLE', 'Supplier Payable'), ('BORROWER_LOAN_RECEIVABLE', 'Borrower Loan Receivable'), ('LENDER_LOAN_PAYABLE', 'Lender Loan Payable'), ('CUSTOMER_ADVANCE', 'Customer Advance'), ('SUPPLIER_ADVANCE', 'Supplier Advance')], db_index=True, max_length=64)),
                ('is_default', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('CLOSED', 'Closed')], db_index=True, default='ACTIVE', max_length=16)),
                ('event_type', models.CharField(blank=True, help_text='Optional event-specific mapping discriminator.', max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Party Account Mapping',
                'verbose_name_plural': 'Party Account Mappings',
                'ordering': ('party', 'role_key', 'purpose', 'id'),
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "dea_account" DROP CONSTRAINT IF EXISTS "unique_contact_account"',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='account',
                    name='unique_contact_account',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='contact.customer'),
        ),
        migrations.AddField(
            model_name='partyaccountmapping',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='party_mappings', to='dea.account'),
        ),
        migrations.AddField(
            model_name='partyaccountmapping',
            name='control_ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='party_account_mappings', to='dea.ledger'),
        ),
        migrations.AddField(
            model_name='partyaccountmapping',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dea_account_mappings', to='party.party'),
        ),
        migrations.AddIndex(
            model_name='partyaccountmapping',
            index=models.Index(fields=['party', 'status'], name='dea_partyac_party_i_011499_idx'),
        ),
        migrations.AddIndex(
            model_name='partyaccountmapping',
            index=models.Index(fields=['role_key', 'purpose', 'status'], name='dea_partyac_role_ke_8ce1aa_idx'),
        ),
        migrations.AddIndex(
            model_name='partyaccountmapping',
            index=models.Index(fields=['account', 'status'], name='dea_partyac_account_8e625f_idx'),
        ),
        migrations.AddConstraint(
            model_name='partyaccountmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('party', 'role_key', 'purpose', 'event_type'), name='dea_one_active_party_account_mapping'),
        ),
        migrations.AddConstraint(
            model_name='partyaccountmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True), ('status', 'ACTIVE')), fields=('party', 'role_key', 'purpose'), name='dea_one_default_party_account_mapping'),
        ),
    ]
