# Generated by Django 6.0.3 on 2026-06-19 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_dea_invoice_parties(apps, schema_editor):
    PurchaseInvoiceVoucher = apps.get_model('dea', 'PurchaseInvoiceVoucher')
    SalesInvoiceVoucher = apps.get_model('dea', 'SalesInvoiceVoucher')

    for invoice in PurchaseInvoiceVoucher.objects.filter(
        party__isnull=True,
        vendor__party__isnull=False,
    ).select_related('vendor'):
        invoice.party_id = invoice.vendor.party_id
        invoice.save(update_fields=['party'])

    for invoice in SalesInvoiceVoucher.objects.filter(
        party__isnull=True,
        customer__party__isnull=False,
    ).select_related('customer'):
        invoice.party_id = invoice.customer.party_id
        invoice.save(update_fields=['party'])


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_customer_party'),
        ('dea', '0031_partyaccountmapping_and_more'),
        ('party', '0003_party_relation_label_party_relation_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoicevoucher',
            name='party',
            field=models.ForeignKey(blank=True, help_text='Shadow Party link for the vendor during Customer migration.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dea_purchase_invoices', to='party.party'),
        ),
        migrations.AddField(
            model_name='salesinvoicevoucher',
            name='party',
            field=models.ForeignKey(blank=True, help_text='Shadow Party link for the customer during Customer migration.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dea_sales_invoices', to='party.party'),
        ),
        migrations.RunPython(backfill_dea_invoice_parties, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='purchaseinvoicevoucher',
            index=models.Index(fields=['invoice_date', 'party'], name='dea_purchas_invoice_f0c565_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoicevoucher',
            index=models.Index(fields=['invoice_date', 'party'], name='dea_salesin_invoice_3db705_idx'),
        ),
    ]
