# Generated by Django 6.0.3 on 2026-06-19 11:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dea', '0031_partyaccountmapping_and_more'),
        ('party', '0003_party_relation_label_party_relation_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = []
