# Generated by Django 6.0.3 on 2026-06-24 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dea', '0032_purchaseinvoicevoucher_party_and_more'),
        ('party', '0004_partycodesequence_alter_party_party_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=16)),
                ('name', models.CharField(max_length=64)),
                ('commodity_type', models.CharField(choices=[('METAL', 'Metal'), ('OTHER', 'Other')], default='METAL', max_length=16)),
                ('default_uom', models.CharField(choices=[('GRAM', 'Gram'), ('KG', 'Kilogram'), ('TOLA', 'Tola'), ('OUNCE', 'Ounce')], default='GRAM', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('code',),
                'indexes': [models.Index(fields=['code'], name='idx_dea_commodity_code'), models.Index(fields=['is_active', 'commodity_type'], name='idx_dea_commodity_active_type')],
                'constraints': [models.UniqueConstraint(fields=('code',), name='uniq_dea_commodity_code')],
            },
        ),
        migrations.CreateModel(
            name='CommodityAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('purpose', models.CharField(choices=[('OWNED_STOCK', 'Owned stock'), ('VAULT', 'Vault'), ('KARIGAR_CUSTODY', 'Karigar custody'), ('PARTY_RECEIVABLE', 'Party receivable'), ('PARTY_PAYABLE', 'Party payable'), ('ADJUSTMENT', 'Adjustment'), ('LOSS_GAIN', 'Loss/gain')], max_length=32)),
                ('location_label', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commodity_accounts', to='dea.commodity')),
                ('financial_control_ledger', models.ForeignKey(blank=True, help_text='Optional reconciliation reference only; not a metal balance.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commodity_accounts', to='dea.ledger')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commodity_accounts', to='party.party')),
            ],
            options={
                'ordering': ('commodity__code', 'code'),
                'indexes': [models.Index(fields=['code'], name='idx_dea_comm_account_code'), models.Index(fields=['commodity', 'purpose'], name='idx_dea_comm_account_purpose'), models.Index(fields=['party', 'commodity', 'purpose'], name='idx_dea_comm_account_party'), models.Index(fields=['is_active', 'commodity'], name='idx_dea_comm_account_active')],
                'constraints': [models.UniqueConstraint(fields=('code',), name='uniq_dea_commodity_account_code')],
            },
        ),
    ]
