# Generated by Django 6.0.3 on 2026-06-24 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dea', '0033_commodity_commodityaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_no', models.CharField(db_index=True, max_length=64)),
                ('movement_date', models.DateField(db_index=True)),
                ('source_object_id', models.PositiveIntegerField()),
                ('uom', models.CharField(choices=[('GRAM', 'Gram'), ('KG', 'Kilogram'), ('TOLA', 'Tola'), ('OUNCE', 'Ounce')], default='GRAM', max_length=16)),
                ('gross_weight', models.DecimalField(decimal_places=3, max_digits=14)),
                ('purity', models.DecimalField(decimal_places=6, max_digits=7)),
                ('fine_weight', models.DecimalField(decimal_places=3, max_digits=14)),
                ('movement_type', models.CharField(choices=[('OPENING', 'Opening'), ('PURCHASE_RECEIPT', 'Purchase receipt'), ('SALE_ISSUE', 'Sale issue'), ('RATE_FIXING', 'Rate fixing'), ('KARIGAR_ISSUE', 'Karigar issue'), ('KARIGAR_RECEIPT', 'Karigar receipt'), ('ADJUSTMENT_IN', 'Adjustment in'), ('ADJUSTMENT_OUT', 'Adjustment out'), ('REVERSAL', 'Reversal')], max_length=32)),
                ('fixed_status', models.CharField(choices=[('FIXED', 'Fixed'), ('UNFIXED', 'Unfixed'), ('PARTIALLY_FIXED', 'Partially fixed'), ('NOT_APPLICABLE', 'Not applicable')], default='NOT_APPLICABLE', max_length=16)),
                ('rate', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('rate_currency', models.CharField(blank=True, max_length=3)),
                ('valuation_currency', models.CharField(blank=True, max_length=3)),
                ('valuation_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('idempotency_key', models.CharField(db_index=True, max_length=128)),
                ('narration', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='dea.commodity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dea_commodity_movements', to=settings.AUTH_USER_MODEL)),
                ('from_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_movements', to='dea.commodityaccount')),
                ('is_reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_movements', to='dea.commoditymovement')),
                ('source_content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dea_commodity_movements', to='contenttypes.contenttype')),
                ('to_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_movements', to='dea.commodityaccount')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commodity_movements', to='dea.voucher')),
            ],
            options={
                'ordering': ('movement_date', 'movement_no'),
                'indexes': [models.Index(fields=['source_content_type', 'source_object_id'], name='idx_dea_comm_move_source'), models.Index(fields=['voucher'], name='idx_dea_comm_move_voucher'), models.Index(fields=['commodity', 'movement_date'], name='idx_dea_comm_move_position'), models.Index(fields=['from_account', 'movement_date'], name='idx_dea_comm_move_from'), models.Index(fields=['to_account', 'movement_date'], name='idx_dea_comm_move_to'), models.Index(fields=['is_reversal_of'], name='idx_dea_comm_move_reversal')],
                'constraints': [models.UniqueConstraint(fields=('movement_no',), name='uniq_dea_commodity_movement_no'), models.UniqueConstraint(fields=('idempotency_key',), name='uniq_dea_commodity_movement_idempotency'), models.UniqueConstraint(condition=models.Q(('is_reversal_of__isnull', False)), fields=('is_reversal_of',), name='uniq_dea_commodity_movement_reversal'), models.CheckConstraint(condition=models.Q(('gross_weight__gt', 0)), name='ck_dea_commodity_movement_gross_positive'), models.CheckConstraint(condition=models.Q(('fine_weight__gt', 0)), name='ck_dea_commodity_movement_fine_positive'), models.CheckConstraint(condition=models.Q(('purity__gt', 0), ('purity__lte', 1)), name='ck_dea_commodity_movement_purity_valid'), models.CheckConstraint(condition=models.Q(('from_account__isnull', False), ('to_account__isnull', False), _connector='OR'), name='ck_dea_commodity_movement_one_side'), models.CheckConstraint(condition=models.Q(('from_account__isnull', True), ('to_account__isnull', True), models.Q(('from_account', models.F('to_account')), _negated=True), _connector='OR'), name='ck_dea_commodity_movement_diff_accounts')],
            },
        ),
    ]
