# Generated by Django 6.0.3 on 2026-06-24 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dea', '0034_commoditymovement'),
        ('party', '0004_partycodesequence_alter_party_party_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExposureLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exposure_no', models.CharField(db_index=True, max_length=64)),
                ('source_object_id', models.PositiveIntegerField()),
                ('side', models.CharField(choices=[('PURCHASE', 'Purchase'), ('SALE', 'Sale')], max_length=16)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PARTIALLY_FIXED', 'Partially fixed'), ('FIXED', 'Fixed'), ('REVERSED', 'Reversed'), ('CLOSED', 'Closed')], default='OPEN', max_length=16)),
                ('fixed_status', models.CharField(choices=[('FIXED', 'Fixed'), ('UNFIXED', 'Unfixed'), ('PARTIALLY_FIXED', 'Partially fixed'), ('NOT_APPLICABLE', 'Not applicable')], default='UNFIXED', max_length=16)),
                ('original_fine_weight', models.DecimalField(decimal_places=3, max_digits=14)),
                ('open_fine_weight', models.DecimalField(decimal_places=3, max_digits=14)),
                ('uom', models.CharField(choices=[('GRAM', 'Gram'), ('KG', 'Kilogram'), ('TOLA', 'Tola'), ('OUNCE', 'Ounce')], default='GRAM', max_length=16)),
                ('rate_basis', models.CharField(blank=True, max_length=64)),
                ('valuation_currency', models.CharField(default='INR', max_length=3)),
                ('last_valuation_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('last_valuation_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('idempotency_key', models.CharField(db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exposures', to='dea.commodity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dea_exposure_lines', to=settings.AUTH_USER_MODEL)),
                ('is_reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_exposures', to='dea.exposureline')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commodity_exposures', to='party.party')),
                ('source_content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dea_exposure_lines', to='contenttypes.contenttype')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commodity_exposures', to='dea.voucher')),
            ],
            options={
                'ordering': ('exposure_no',),
            },
        ),
        migrations.CreateModel(
            name='RateFixing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixing_no', models.CharField(db_index=True, max_length=64)),
                ('fixing_date', models.DateField(db_index=True)),
                ('side', models.CharField(choices=[('PURCHASE', 'Purchase'), ('SALE', 'Sale')], max_length=16)),
                ('fine_weight', models.DecimalField(decimal_places=3, max_digits=14)),
                ('uom', models.CharField(choices=[('GRAM', 'Gram'), ('KG', 'Kilogram'), ('TOLA', 'Tola'), ('OUNCE', 'Ounce')], default='GRAM', max_length=16)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=14)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('valuation_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('REVERSED', 'Reversed'), ('CORRECTED', 'Corrected')], default='DRAFT', max_length=16)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=128)),
                ('narration', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rate_fixings', to='dea.commodity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dea_rate_fixings_created', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commodity_rate_fixings', to='party.party')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dea_rate_fixings_updated', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commodity_rate_fixings', to='dea.voucher')),
            ],
            options={
                'ordering': ('fixing_date', 'fixing_no'),
            },
        ),
        migrations.CreateModel(
            name='RateFixingAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine_weight', models.DecimalField(decimal_places=3, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('exposure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rate_fixing_allocations', to='dea.exposureline')),
                ('rate_fixing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='dea.ratefixing')),
            ],
        ),
        migrations.AddIndex(
            model_name='exposureline',
            index=models.Index(fields=['source_content_type', 'source_object_id'], name='idx_dea_exposure_source'),
        ),
        migrations.AddIndex(
            model_name='exposureline',
            index=models.Index(fields=['party', 'status'], name='idx_dea_exposure_party'),
        ),
        migrations.AddIndex(
            model_name='exposureline',
            index=models.Index(fields=['commodity', 'status'], name='idx_dea_exposure_commodity'),
        ),
        migrations.AddIndex(
            model_name='exposureline',
            index=models.Index(fields=['side', 'status'], name='idx_dea_exposure_side'),
        ),
        migrations.AddConstraint(
            model_name='exposureline',
            constraint=models.UniqueConstraint(fields=('exposure_no',), name='uniq_dea_exposure_no'),
        ),
        migrations.AddConstraint(
            model_name='exposureline',
            constraint=models.UniqueConstraint(fields=('idempotency_key',), name='uniq_dea_exposure_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='exposureline',
            constraint=models.CheckConstraint(condition=models.Q(('original_fine_weight__gt', 0)), name='ck_dea_exposure_original_positive'),
        ),
        migrations.AddConstraint(
            model_name='exposureline',
            constraint=models.CheckConstraint(condition=models.Q(('open_fine_weight__gte', 0)), name='ck_dea_exposure_open_non_negative'),
        ),
        migrations.AddIndex(
            model_name='ratefixing',
            index=models.Index(fields=['party', 'status'], name='idx_dea_fixing_party'),
        ),
        migrations.AddIndex(
            model_name='ratefixing',
            index=models.Index(fields=['commodity', 'fixing_date'], name='idx_dea_fixing_commodity_date'),
        ),
        migrations.AddIndex(
            model_name='ratefixing',
            index=models.Index(fields=['voucher'], name='idx_dea_fixing_voucher'),
        ),
        migrations.AddConstraint(
            model_name='ratefixing',
            constraint=models.UniqueConstraint(fields=('fixing_no',), name='uniq_dea_rate_fixing_no'),
        ),
        migrations.AddConstraint(
            model_name='ratefixing',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('idempotency_key',), name='uniq_dea_rate_fixing_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='ratefixing',
            constraint=models.CheckConstraint(condition=models.Q(('fine_weight__gt', 0)), name='ck_dea_rate_fixing_weight_positive'),
        ),
        migrations.AddConstraint(
            model_name='ratefixing',
            constraint=models.CheckConstraint(condition=models.Q(('rate__gt', 0)), name='ck_dea_rate_fixing_rate_positive'),
        ),
        migrations.AddConstraint(
            model_name='ratefixing',
            constraint=models.CheckConstraint(condition=models.Q(('valuation_amount__gt', 0)), name='ck_dea_rate_fixing_value_positive'),
        ),
        migrations.AddIndex(
            model_name='ratefixingallocation',
            index=models.Index(fields=['rate_fixing', 'exposure'], name='idx_dea_fixing_alloc_parent'),
        ),
        migrations.AddConstraint(
            model_name='ratefixingallocation',
            constraint=models.UniqueConstraint(fields=('rate_fixing', 'exposure'), name='uniq_dea_rate_fixing_exposure'),
        ),
        migrations.AddConstraint(
            model_name='ratefixingallocation',
            constraint=models.CheckConstraint(condition=models.Q(('fine_weight__gt', 0)), name='ck_dea_fixing_alloc_weight_positive'),
        ),
        migrations.AddConstraint(
            model_name='ratefixingallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_dea_fixing_alloc_amount_positive'),
        ),
    ]
