# Generated by Django 6.0.3 on 2026-06-24 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dea', '0035_exposureline_ratefixing_ratefixingallocation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessEventDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('FIXED_PURCHASE', 'Fixed purchase')], max_length=32)),
                ('source_reference', models.CharField(max_length=80)),
                ('event_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PREVIEWED', 'Previewed')], db_index=True, default='DRAFT', max_length=16)),
                ('normalized_payload', models.JSONField(default=dict)),
                ('preview_payload', models.JSONField(blank=True, default=dict)),
                ('payload_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dea_business_event_drafts_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dea_business_event_drafts_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-event_date', '-id'),
                'indexes': [models.Index(fields=['event_type', 'status', 'event_date'], name='idx_dea_bus_event_status_date'), models.Index(fields=['payload_hash'], name='idx_dea_bus_event_hash')],
                'constraints': [models.UniqueConstraint(fields=('event_type', 'source_reference'), name='uniq_dea_business_event_draft_ref')],
            },
        ),
    ]
