# Generated by Codex on 2026-06-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dea", "0036_businesseventdraft"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesseventdraft",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("FIXED_PURCHASE", "Fixed purchase"),
                    ("UNFIXED_PURCHASE", "Unfixed purchase"),
                ],
                max_length=32,
            ),
        ),
    ]
