# Generated by Django 6.0.3 on 2026-06-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dea', '0038_alter_businesseventdraft_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesseventdraft',
            name='event_type',
            field=models.CharField(choices=[('FIXED_PURCHASE', 'Fixed purchase'), ('UNFIXED_PURCHASE', 'Unfixed purchase'), ('PURCHASE_RATE_FIXING', 'Purchase rate fixing'), ('FIXED_SALE', 'Fixed sale')], max_length=32),
        ),
    ]
