# Generated by Django 5.2.6 on 2025-11-15 09:42

import django.contrib.postgres.fields.hstore
import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("reorder_level", models.IntegerField(default=1)),
                ("quantity", models.IntegerField(default=0)),
                ("weight", models.DecimalField(decimal_places=3, max_digits=10)),
                ("lot_no", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "serial_no",
                    models.CharField(blank=True, max_length=8, null=True, unique=True),
                ),
                (
                    "huid",
                    models.CharField(blank=True, max_length=7, null=True, unique=True),
                ),
                ("sku", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "purchase_touch",
                    models.DecimalField(decimal_places=3, max_digits=10),
                ),
                (
                    "purchase_rate",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("is_unique", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Empty", "Empty"),
                            ("Available", "Available"),
                            ("Sold", "Sold"),
                            ("Approval", "Approval"),
                            ("Return", "Return"),
                            ("Damaged", "Damaged"),
                            ("Lost", "Lost"),
                            ("Reserved", "Reserved"),
                        ],
                        default="Empty",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="name"
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="AttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("value", models.CharField(default="", max_length=100)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="name"
                    ),
                ),
            ],
            options={
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="name"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "background_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="category-backgrounds"
                    ),
                ),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Movement",
            fields=[
                (
                    "id",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=30)),
                ("direction", models.CharField(default="+", max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("selling_price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="PricingTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("description", models.TextField(blank=True)),
                ("minimum_quantity", models.PositiveIntegerField()),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PricingTierProductPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=3, max_digits=13),
                ),
                ("selling_price", models.DecimalField(decimal_places=3, max_digits=13)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("description", models.TextField()),
                (
                    "attributes",
                    django.contrib.postgres.fields.hstore.HStoreField(
                        blank=True, default=dict, null=True
                    ),
                ),
                ("jattributes", models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="product/")),
                ("alt", models.CharField(blank=True, max_length=128)),
            ],
            options={
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="ProductType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("has_variants", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("product_code", models.CharField(max_length=100, unique=True)),
                (
                    "attributes",
                    django.contrib.postgres.fields.hstore.HStoreField(
                        blank=True, default=dict
                    ),
                ),
                ("jattributes", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="StockStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("Auto", "Auto"), ("Physical", "Physical")],
                        default="Auto",
                        max_length=20,
                    ),
                ),
                ("created", models.DateTimeField(auto_now=True)),
                ("Closing_wt", models.DecimalField(decimal_places=3, max_digits=14)),
                ("Closing_qty", models.IntegerField()),
                (
                    "total_wt_in",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=14),
                ),
                (
                    "total_wt_out",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=14),
                ),
                ("total_qty_in", models.IntegerField(default=0.0)),
                ("total_qty_out", models.IntegerField(default=0.0)),
            ],
            options={
                "ordering": ("created",),
                "get_latest_by": ["created"],
            },
        ),
        migrations.CreateModel(
            name="StockTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("quantity", models.IntegerField(blank=True, default=0)),
                (
                    "weight",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="VariantImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockBalance",
            fields=[
                (
                    "stock",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="product.stock",
                    ),
                ),
                ("closing_wt", models.DecimalField(decimal_places=3, max_digits=14)),
                ("closing_qty", models.IntegerField()),
                ("in_wt", models.DecimalField(decimal_places=3, max_digits=14)),
                ("in_qty", models.IntegerField()),
                ("out_wt", models.DecimalField(decimal_places=3, max_digits=14)),
                ("out_qty", models.IntegerField()),
            ],
            options={
                "db_table": "stock_balance",
                "managed": False,
            },
        ),
    ]
