# Generated by Django 5.2.6 on 2025-11-15 09:42

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contact", "0001_initial"),
        ("dea", "0001_initial"),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attributevalue",
            name="attribute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="values",
                to="product.attribute",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="product.category",
            ),
        ),
        migrations.AddField(
            model_name="price",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prices",
                to="contact.customer",
            ),
        ),
        migrations.AddField(
            model_name="pricingtier",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="product.pricingtier",
            ),
        ),
        migrations.AddField(
            model_name="price",
            name="price_tier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="product.pricingtier"
            ),
        ),
        migrations.AddField(
            model_name="pricingtierproductprice",
            name="pricing_tier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_list",
                to="product.pricingtier",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="product.category",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="product.product",
            ),
        ),
        migrations.AddField(
            model_name="producttype",
            name="product_attributes",
            field=models.ManyToManyField(
                blank=True, related_name="product_types", to="product.attribute"
            ),
        ),
        migrations.AddField(
            model_name="producttype",
            name="variant_attributes",
            field=models.ManyToManyField(
                blank=True, related_name="product_variant_types", to="product.attribute"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="product.producttype",
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stocks",
                to="product.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="product.product",
            ),
        ),
        migrations.AddField(
            model_name="pricingtierproductprice",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="product.productvariant"
            ),
        ),
        migrations.AddField(
            model_name="price",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="product.productvariant"
            ),
        ),
        migrations.AddField(
            model_name="stockstatement",
            name="stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="product.stock"
            ),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="journal_entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stxns",
                to="dea.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="movement_type",
            field=models.ForeignKey(
                default="P",
                on_delete=django.db.models.deletion.CASCADE,
                to="product.movement",
            ),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="product.stock"
            ),
        ),
        migrations.AddField(
            model_name="variantimage",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variant_images",
                to="product.productimage",
            ),
        ),
        migrations.AddField(
            model_name="variantimage",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variant_images",
                to="product.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="images",
            field=models.ManyToManyField(
                through="product.VariantImage", to="product.productimage"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attributevalue",
            unique_together={("name", "attribute")},
        ),
    ]
