# Generated by Django 6.0.3 on 2026-03-20 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='attributes',
        ),
    ]
