# Generated by Django 5.0.1 on 2024-04-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_alter_product_attributes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stocklot",
            name="stock",
        ),
        migrations.RemoveField(
            model_name="stocklot",
            name="variant",
        ),
        migrations.RemoveField(
            model_name="stockstatement",
            name="lot",
        ),
        migrations.RemoveField(
            model_name="stocktransaction",
            name="lot",
        ),
        migrations.RenameField(
            model_name="stock",
            old_name="reorderat",
            new_name="reorder_level",
        ),
        migrations.RenameField(
            model_name="stock",
            old_name="updated_on",
            new_name="updated",
        ),
        migrations.AddField(
            model_name="stock",
            name="huid",
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="is_unique",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stock",
            name="lot_no",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="purchase_rate",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="purchase_touch",
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stock",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="stock",
            name="serial_no",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="sku",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="status",
            field=models.CharField(
                choices=[
                    ("Empty", "Empty"),
                    ("Available", "Available"),
                    ("Sold", "Sold"),
                    ("Approval", "Approval"),
                    ("Return", "Return"),
                    ("Damaged", "Damaged"),
                    ("Lost", "Lost"),
                    ("Reserved", "Reserved"),
                ],
                default="Empty",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="weight",
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="StockLotBalance",
        ),
    ]
