# Generated by Django 5.0.1 on 2024-04-06 07:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("approval", "0005_alter_approvalline_product"),
        ("product", "0005_remove_stocklot_stock_remove_stocklot_variant_and_more"),
        ("sales", "0003_alter_invoiceitem_product_alter_salebalance_table"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StockLot",
        ),
    ]
