# Generated by Django 6.0.3 on 2026-03-20 06:19

import django.db.models.deletion
from django.db import migrations, models


def copy_producttype_attribute_links(apps, schema_editor):
    ProductType = apps.get_model("product", "ProductType")
    AttributeProduct = apps.get_model("product", "AttributeProduct")
    AttributeVariant = apps.get_model("product", "AttributeVariant")

    for product_type in ProductType.objects.prefetch_related(
        "product_attributes", "variant_attributes"
    ):
        for attribute in product_type.product_attributes.all():
            AttributeProduct.objects.get_or_create(
                product_type_id=product_type.id, attribute_id=attribute.id
            )
        for attribute in product_type.variant_attributes.all():
            AttributeVariant.objects.get_or_create(
                product_type_id=product_type.id, attribute_id=attribute.id
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_hstore_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='filterable_in_dashboard',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='filterable_in_storefront',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='input_type',
            field=models.CharField(choices=[('dropdown', 'Dropdown'), ('multiselect', 'Multiselect')], default='dropdown', max_length=50),
        ),
        migrations.AddField(
            model_name='attribute',
            name='value_required',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='attribute',
            name='visible_in_storefront',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='sort_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AssignedProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='product.product')),
                ('values', models.ManyToManyField(to='product.attributevalue')),
            ],
        ),
        migrations.CreateModel(
            name='AssignedVariantAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.ManyToManyField(to='product.attributevalue')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='product.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='AttributeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(blank=True, null=True)),
                ('assigned_products', models.ManyToManyField(blank=True, related_name='attributesrelated', through='product.AssignedProductAttribute', through_fields=('assignment', 'product'), to='product.product')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributeproduct', to='product.attribute')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributeproduct', to='product.producttype')),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
                'unique_together': {('attribute', 'product_type')},
            },
        ),
        migrations.AddField(
            model_name='assignedproductattribute',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productassignments', to='product.attributeproduct'),
        ),
        migrations.CreateModel(
            name='AttributeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(blank=True, null=True)),
                ('assigned_variants', models.ManyToManyField(blank=True, related_name='attributesrelated', through='product.AssignedVariantAttribute', through_fields=('assignment', 'variant'), to='product.productvariant')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributevariant', to='product.attribute')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributevariant', to='product.producttype')),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
                'unique_together': {('attribute', 'product_type')},
            },
        ),
        migrations.AddField(
            model_name='assignedvariantattribute',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantassignments', to='product.attributevariant'),
        ),
        migrations.RunPython(copy_producttype_attribute_links, noop_reverse),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='producttype',
                    name='product_attributes',
                    field=models.ManyToManyField(blank=True, related_name='product_types', through='product.AttributeProduct', through_fields=('product_type', 'attribute'), to='product.attribute'),
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='producttype',
                    name='variant_attributes',
                    field=models.ManyToManyField(blank=True, related_name='product_variant_types', through='product.AttributeVariant', through_fields=('product_type', 'attribute'), to='product.attribute'),
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterUniqueTogether(
            name='assignedproductattribute',
            unique_together={('product', 'assignment')},
        ),
        migrations.AlterUniqueTogether(
            name='assignedvariantattribute',
            unique_together={('variant', 'assignment')},
        ),
    ]
