# Generated by Django 5.0.1 on 2024-04-06 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_delete_stocklot"),
        ("purchase", "0002_auto_20240405_2353"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="purchase_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stocks",
                to="purchase.purchaseitem",
            ),
        ),
    ]
