# Generated by Django 6.0.3 on 2026-03-20 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_attribute_filterable_in_dashboard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='jattributes',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='jattributes',
        ),
    ]
