# Generated by Django 5.0.1 on 2024-04-07 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0007_stock_purchase_item"),
        ("purchase", "0002_auto_20240405_2353"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="purchase_item",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_item",
                to="purchase.purchaseitem",
            ),
        ),
    ]
