# Generated by Django 5.0.1 on 2024-04-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0009_auto_20240407_1339"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="lot_no",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="serial_no",
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
