# Generated by Django 5.0.1 on 2024-04-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0010_alter_stock_lot_no_alter_stock_serial_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="huid",
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
    ]
