# Generated by Django 5.0.1 on 2024-04-09 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0011_alter_stock_huid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="sku",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stocks",
                to="product.productvariant",
            ),
        ),
    ]
