# Generated by Django 5.0.1 on 2024-04-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0013_auto_20240409_1333"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stocktransaction",
            options={},
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="quantity",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
