# Generated by Django 5.0.8 on 2024-09-03 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dea", "0013_journalentry_parent_content_type_and_more"),
        ("product", "0014_alter_stocktransaction_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktransaction",
            name="journal_entry",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stxns",
                to="dea.journalentry",
            ),
        ),
    ]
