# Generated by Django 5.0.8 on 2024-09-03 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dea", "0013_journalentry_parent_content_type_and_more"),
        ("product", "0016_alter_stocktransaction_journal_entry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stocktransaction",
            name="journal_entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stxns",
                to="dea.journalentry",
            ),
        ),
    ]
