# Generated by Django 5.0.8 on 2024-09-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0017_alter_stocktransaction_journal_entry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="product_code",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="sku",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
