from enum import StrEnum


class LoanRepaymentStructure(StrEnum):
    SINGLE_PAYMENT_BULLET = "SINGLE_PAYMENT_BULLET"
    PERIODIC_INTEREST_BULLET = "PERIODIC_INTEREST_BULLET"
    FLEXIBLE_PARTIAL_PAYMENT = "FLEXIBLE_PARTIAL_PAYMENT"
    INSTALLMENT = "INSTALLMENT"
    LEGACY_UNSPECIFIED = "LEGACY_UNSPECIFIED"


class LoanAmortisationMethod(StrEnum):
    NONE = "NONE"
    EMI = "EMI"
    EQUAL_PRINCIPAL = "EQUAL_PRINCIPAL"


class LoanPaymentFrequency(StrEnum):
    AT_MATURITY = "AT_MATURITY"
    MONTHLY = "MONTHLY"
    FLEXIBLE = "FLEXIBLE"


class LoanExtraPaymentRule(StrEnum):
    NOT_APPLICABLE = "NOT_APPLICABLE"
    REDUCE_PRINCIPAL = "REDUCE_PRINCIPAL"
    KEEP_PAYMENT_SHORTEN_TENURE = "KEEP_PAYMENT_SHORTEN_TENURE"


class LoanProductVersionStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    RETIRED = "RETIRED"
