# Generated by Django 6.0.3 on 2026-08-16 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenceauditlog',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preference_audit_logs', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='workspacepreferencemodel',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuration_preferences', to='orgs.company'),
        ),
        migrations.AddIndex(
            model_name='preferenceauditlog',
            index=models.Index(fields=['scope', 'key'], name='configurati_scope_6eb5c8_idx'),
        ),
        migrations.AddIndex(
            model_name='preferenceauditlog',
            index=models.Index(fields=['workspace', 'scope'], name='configurati_workspa_71282d_idx'),
        ),
        migrations.AddIndex(
            model_name='preferenceauditlog',
            index=models.Index(fields=['subject_user', 'scope'], name='configurati_subject_c26281_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workspacepreferencemodel',
            unique_together={('instance', 'section', 'name')},
        ),
    ]
