# Generated by Django 6.0.3 on 2026-09-24 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def retain_or_create_tables(apps, schema_editor):
    connection = schema_editor.connection
    existing = set(connection.introspection.table_names())
    for name in ("LegacyGlobalPreference", "LegacyUserPreference"):
        model = apps.get_model("configuration", name)
        table = model._meta.db_table
        if table not in existing:
            schema_editor.create_model(model)
        else:
            with connection.cursor() as cursor:
                columns = {column.name for column in connection.introspection.get_table_description(cursor, table)}
            required = {field.column for field in model._meta.local_fields}
            if columns != required:
                raise RuntimeError(f"Unexpected legacy preference table structure: {table}")



class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [migrations.SeparateDatabaseAndState(state_operations=[
        migrations.CreateModel(
            name='LegacyGlobalPreference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('section', models.CharField(blank=True, db_index=True, default=None, max_length=150, null=True, verbose_name='Section Name')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Name')),
                ('raw_value', models.TextField(blank=True, null=True, verbose_name='Raw Value')),
            ],
            options={
                'db_table': 'dynamic_preferences_globalpreferencemodel',
                'default_permissions': (),
                'unique_together': {('section', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LegacyUserPreference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('section', models.CharField(blank=True, db_index=True, default=None, max_length=150, null=True, verbose_name='Section Name')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Name')),
                ('raw_value', models.TextField(blank=True, null=True, verbose_name='Raw Value')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dynamic_preferences_users_userpreferencemodel',
                'default_permissions': (),
                'unique_together': {('instance', 'section', 'name')},
            },
        ),
    ]), migrations.RunPython(retain_or_create_tables, migrations.RunPython.noop)]
