# Generated by Django 5.2.6 on 2025-11-15 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("approval", "0001_initial"),
        ("contact", "0001_initial"),
        ("product", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalline",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lineitems",
                to="product.stock",
                verbose_name="Product",
            ),
        ),
        migrations.AddField(
            model_name="return",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_returns",
                to="contact.customer",
            ),
        ),
        migrations.AddField(
            model_name="return",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="returnitem",
            name="line_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="return_items",
                to="approval.approvalline",
            ),
        ),
        migrations.AddField(
            model_name="returnitem",
            name="return_obj",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="approval.return"
            ),
        ),
    ]
