# Generated by Django 5.0.1 on 2024-04-05 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("approval", "0003_initial"),
        ("contact", "0007_alter_customer_created_by"),
        ("product", "0004_alter_product_attributes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="approval",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact",
                to="contact.customer",
                verbose_name="Contact",
            ),
        ),
        migrations.AlterField(
            model_name="approval",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="approval",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="approval",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Complete", "Complete"),
                    ("Billed", "Billed"),
                ],
                default="Pending",
                max_length=10,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="approvalline",
            name="approval",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="approval.approval",
                verbose_name="Approval",
            ),
        ),
        migrations.AlterField(
            model_name="approvalline",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="approvalline",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lineitems",
                to="product.stocklot",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="approvalline",
            name="quantity",
            field=models.IntegerField(default=0, verbose_name="Quantity"),
        ),
        migrations.AlterField(
            model_name="approvalline",
            name="touch",
            field=models.DecimalField(
                decimal_places=3, default=0.0, max_digits=10, verbose_name="Touch"
            ),
        ),
        migrations.AlterField(
            model_name="approvalline",
            name="weight",
            field=models.DecimalField(
                decimal_places=3, default=0.0, max_digits=10, verbose_name="Weight"
            ),
        ),
        migrations.AlterField(
            model_name="return",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="return",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="returnitem",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
