# Generated by Django 5.0.1 on 2024-04-06 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("approval", "0004_alter_approval_contact_alter_approval_created_by_and_more"),
        ("product", "0004_alter_product_attributes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvalline",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lineitems",
                to="product.stock",
                verbose_name="Product",
            ),
        ),
    ]
