# Generated by Django 5.0.1 on 2024-02-20 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("orgs", "0008_company_schema_name_domain_companyownership"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="orgs.company",
            ),
        ),
    ]
