# Generated by Django 5.0.1 on 2024-02-26 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_customuser_workspace"),
        ("orgs", "0010_companypreferencemodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="orgs.company",
                verbose_name="Workspace",
            ),
        ),
    ]
