# Generated by Django 5.0.8 on 2024-08-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_customuser_workspace"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="social_profile_picture",
            field=models.URLField(blank=True, null=True),
        ),
    ]
