# Generated by Django 5.0.8 on 2024-10-07 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_userprofile"),
        ("orgs", "0014_company_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                default="public",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="orgs.company",
                verbose_name="Workspace",
            ),
        ),
    ]
