# Generated by Django 5.0.8 on 2024-10-07 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_customuser_workspace"),
        ("orgs", "0015_company_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="orgs.company",
                verbose_name="Workspace",
            ),
        ),
    ]
