# Generated by Django 5.0.8 on 2024-10-10 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_alter_customuser_workspace"),
        ("orgs", "0015_company_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="social_profile_picture",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="timezone",
            field=models.CharField(
                blank=True, default="Asia/Kolkata", max_length=63, null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="orgs.company",
                verbose_name="Workspace",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
