# Generated by Django 5.1.2 on 2024-10-11 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_userprofile_profile_picture_and_more"),
        ("orgs", "0015_company_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="orgs.company",
                verbose_name="Workspace",
            ),
        ),
    ]
