# Generated by Django 5.1.2 on 2024-11-18 12:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_alter_userprofile_workspace"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="profile_picture",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="social_profile_picture",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="workspace",
        ),
    ]
