# Generated by Django 5.2.6 on 2025-11-15 09:42

import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contact", "0001_initial"),
        ("product", "0001_initial"),
        ("terms", "0002_auto_20230723_1647"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchasePaymentView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchase", models.CharField(max_length=50)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "amount_allocated",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
            options={
                "db_table": "invoice_payment_view",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "voucher_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("voucher_no", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "weight",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "touch",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                ("rate", models.IntegerField(default=0)),
                (
                    "total_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "total",
                    djmoney.models.fields.MoneyField(decimal_places=3, max_digits=10),
                ),
                ("description", models.TextField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Allotted", "Allotted"),
                            ("Partially Allotted", "PartiallyAllotted"),
                            ("Unallotted", "Unallotted"),
                        ],
                        default="Unallotted",
                        max_length=18,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="contact.customer",
                        verbose_name="Supplier",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "voucher_date",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("voucher_no", models.CharField(blank=True, max_length=20, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("is_ratecut", models.BooleanField(default=False)),
                ("is_gst", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Paid", "Paid"),
                            ("PartiallyPaid", "PartiallyPaid"),
                            ("Unpaid", "Unpaid"),
                        ],
                        default="Unpaid",
                        max_length=15,
                    ),
                ),
                (
                    "gold_rate",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "silver_rate",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchases_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="contact.customer",
                        verbose_name="Supplier",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_term",
                        to="terms.paymentterm",
                    ),
                ),
            ],
            options={
                "ordering": ("id", "created"),
            },
        ),
        migrations.CreateModel(
            name="PaymentAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "allocated_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "allocated",
                    djmoney.models.fields.MoneyField(
                        decimal_places=4, default=Decimal("0"), max_digits=19
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="purchase.payment",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="purchase.purchase",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="payment",
            name="invoices",
            field=models.ManyToManyField(
                through="purchase.PaymentAllocation", to="purchase.purchase"
            ),
        ),
        migrations.CreateModel(
            name="PurchaseBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "amount",
                    djmoney.models.fields.MoneyField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balances",
                        to="purchase.purchase",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="PurchaseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "huid",
                    models.CharField(blank=True, max_length=7, null=True, unique=True),
                ),
                ("quantity", models.IntegerField()),
                ("weight", models.DecimalField(decimal_places=3, max_digits=14)),
                ("touch", models.DecimalField(decimal_places=3, max_digits=14)),
                (
                    "net_wt",
                    models.DecimalField(
                        blank=True, decimal_places=3, default=0, max_digits=14
                    ),
                ),
                (
                    "making_charge",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        default=0,
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "hallmark_charge",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        default=0,
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "metal_balance_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="USD",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "metal_balance",
                    djmoney.models.fields.MoneyField(
                        decimal_places=3, default_currency="USD", max_digits=14
                    ),
                ),
                (
                    "cash_balance_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "cash_balance",
                    djmoney.models.fields.MoneyField(decimal_places=3, max_digits=14),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_items",
                        to="purchase.purchase",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="product.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ("-pk",),
            },
        ),
    ]
