# Generated by Django 5.0.1 on 2024-04-05 18:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE OR REPLACE VIEW purchase_balance AS
            SELECT purchase_purchase.id AS voucher_id,
                ROW(COALESCE(sum(pi.cash_balance), 0.0), 'INR'::character varying(3))::money_value AS cash_balance,
                ROW(COALESCE(sum(pi.metal_balance) FILTER (WHERE pi.metal_balance_currency::text = 'USD'::text), 0.0), 'USD'::character varying(3))::money_value AS gold_balance,
                ROW(COALESCE(sum(pi.metal_balance) FILTER (WHERE pi.metal_balance_currency::text = 'EUR'::text), 0.0), 'EUR'::character varying(3))::money_value AS silver_balance,
                ARRAY[
                    ROW(COALESCE(sum(pi.cash_balance), 0.0), 'INR'::character varying(3))::money_value, 
                    ROW(COALESCE(sum(pi.metal_balance) FILTER (WHERE pi.metal_balance_currency::text = 'USD'::text), 0.0), 'USD'::character varying(3))::money_value, 
                    ROW(COALESCE(sum(pi.metal_balance) FILTER (WHERE pi.metal_balance_currency::text = 'EUR'::text), 0.0), 'EUR'::character varying(3))::money_value
                ] AS balances
            FROM purchase_purchase
            JOIN purchase_purchaseitem pi ON pi.invoice_id = purchase_purchase.id
            GROUP BY purchase_purchase.id;
        """,
            reverse_sql="DROP VIEW IF EXISTS purchase_balance;",
        )
    ]
