# Generated by Django 5.0.1 on 2024-04-07 13:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0002_auto_20240405_2353"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseitem",
            name="is_return",
        ),
    ]
