# Generated by Django 5.1.2 on 2024-12-04 11:24

import apps.tenant_apps.dea.models.moneyvalue
import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("purchase", "0003_remove_purchaseitem_is_return"),
        ("purchase", "0004_purchaseitem_huid"),
        ("purchase", "0005_remove_purchaseitem_rate_purchase_balance_cash_and_more"),
        ("purchase", "0006_purchase_balance"),
        ("purchase", "0007_alter_purchase_balance"),
        ("purchase", "0008_alter_purchase_balance"),
        ("purchase", "0009_payment_voucher_date_purchase_voucher_date_and_more"),
        ("purchase", "0010_alter_payment_voucher_date_and_more"),
        ("purchase", "0011_payment_voucher_no_purchase_voucher_no"),
        ("purchase", "0012_alter_payment_voucher_no_alter_purchase_voucher_no"),
        ("purchase", "0013_alter_payment_total_currency_and_more"),
        ("purchase", "0014_alter_payment_created_by_alter_purchase_created_by"),
    ]

    dependencies = [
        ("purchase", "0002_auto_20240405_2353"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseitem",
            name="is_return",
        ),
        migrations.RemoveField(
            model_name="purchaseitem",
            name="rate",
        ),
        migrations.AddField(
            model_name="purchase",
            name="balance_cash",
            field=djmoney.models.fields.MoneyField(
                blank=True, decimal_places=3, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="balance_gold",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=3,
                default_currency="USD",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="balance_silver",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=3,
                default_currency="EUR",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="gold_rate",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="purchase",
            name="silver_rate",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="purchaseitem",
            name="huid",
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="purchase",
            name="balance",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=apps.tenant_apps.dea.models.moneyvalue.MoneyValueField(
                    blank=True, null=True
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="voucher_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="purchase",
            name="voucher_date",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="voucher_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="purchase",
            name="voucher_no",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="total_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("AUD", "Australian Dollar"),
                    ("INR", "Indian Rupee"),
                    ("USD", "US Dollar"),
                ],
                default="INR",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="paymentallocation",
            name="allocated_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("AUD", "Australian Dollar"),
                    ("INR", "Indian Rupee"),
                    ("USD", "US Dollar"),
                ],
                default="INR",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="balance_cash_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("AUD", "Australian Dollar"),
                    ("INR", "Indian Rupee"),
                    ("USD", "US Dollar"),
                ],
                default="INR",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="balance_gold_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("AUD", "Australian Dollar"),
                    ("INR", "Indian Rupee"),
                    ("USD", "US Dollar"),
                ],
                default="USD",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="balance_silver_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("AUD", "Australian Dollar"),
                    ("INR", "Indian Rupee"),
                    ("USD", "US Dollar"),
                ],
                default="EUR",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseitem",
            name="cash_balance_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("AUD", "Australian Dollar"),
                    ("INR", "Indian Rupee"),
                    ("USD", "US Dollar"),
                ],
                default="INR",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseitem",
            name="metal_balance_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("AUD", "Australian Dollar"),
                    ("INR", "Indian Rupee"),
                    ("USD", "US Dollar"),
                ],
                default="USD",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchases_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
