# Generated by Django 5.0.1 on 2024-04-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0003_remove_purchaseitem_is_return"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseitem",
            name="huid",
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
