# Generated by Django 5.0.1 on 2024-04-07 20:04

import django.contrib.postgres.fields
from django.db import migrations

import apps.tenant_apps.dea.models.moneyvalue


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0005_remove_purchaseitem_rate_purchase_balance_cash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="balance",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=apps.tenant_apps.dea.models.moneyvalue.MoneyValueField(
                    blank=True, null=True
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
