# Generated by Django 5.0.1 on 2024-04-08 06:42

import django.contrib.postgres.fields
from django.db import migrations

import apps.tenant_apps.dea.models.moneyvalue


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0006_purchase_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="balance",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=apps.tenant_apps.dea.models.moneyvalue.MoneyValueField(
                    blank=True, null=True
                ),
                size=None,
            ),
        ),
    ]
