# Generated by Django 5.0.1 on 2024-04-14 12:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0008_alter_purchase_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="voucher_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="purchase",
            name="voucher_date",
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="payment",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
