# Generated by Django 5.0.1 on 2024-04-16 09:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0009_payment_voucher_date_purchase_voucher_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="voucher_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="voucher_date",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
    ]
