# Generated by Django 5.0.1 on 2024-04-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0010_alter_payment_voucher_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="voucher_no",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="purchase",
            name="voucher_no",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
