# Generated by Django 5.0.1 on 2024-04-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0011_payment_voucher_no_purchase_voucher_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="voucher_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="voucher_no",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
