# Generated by Django 5.2.6 on 2026-02-27 06:53

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orgs", "0019_alter_company_members"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        help_text="e.g., INV-2025-01-0001",
                        max_length=50,
                        unique=True,
                        verbose_name="Invoice Number",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("issued", "Issued"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="issued",
                        max_length=20,
                    ),
                ),
                (
                    "base_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Plan price",
                        max_digits=10,
                        verbose_name="Base Amount",
                    ),
                ),
                (
                    "overage_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Extra users, additional features",
                        max_digits=10,
                        verbose_name="Overage Amount",
                    ),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "gst_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("18.00"),
                        max_digits=5,
                        verbose_name="GST Rate (%)",
                    ),
                ),
                ("gst_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "razorpay_payment_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Razorpay Payment ID",
                    ),
                ),
                (
                    "razorpay_order_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Razorpay Order ID",
                    ),
                ),
                ("invoice_date", models.DateField(verbose_name="Invoice Date")),
                (
                    "due_date",
                    models.DateField(
                        help_text="7 days from invoice date", verbose_name="Due Date"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Paid On"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "ordering": ["-invoice_date"],
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("starter", "Starter - ₹999/month"),
                            ("professional", "Professional - ₹3,999/month"),
                            ("enterprise", "Enterprise - Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "yearly_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Annual price with 20% discount applied",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly (20% discount)"),
                        ],
                        default="monthly",
                        max_length=10,
                    ),
                ),
                ("max_users", models.IntegerField(default=5)),
                ("max_products", models.IntegerField(default=100)),
                ("max_warehouses", models.IntegerField(default=1)),
                ("max_transactions_per_month", models.IntegerField(default=500)),
                ("max_invoices_per_month", models.IntegerField(default=500)),
                ("has_advanced_reporting", models.BooleanField(default=False)),
                ("has_multi_warehouse", models.BooleanField(default=False)),
                ("has_approvals_workflow", models.BooleanField(default=False)),
                ("has_api_access", models.BooleanField(default=False)),
                ("has_custom_fields", models.BooleanField(default=False)),
                ("trial_days", models.IntegerField(default=14)),
                (
                    "extra_user_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("99.00"), max_digits=6
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "razorpay_payment_id",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Razorpay Payment ID"
                    ),
                ),
                (
                    "razorpay_order_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Razorpay Order ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Amount"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("authorized", "Authorized"),
                            ("captured", "Captured"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("card", "Credit/Debit Card"),
                            ("netbanking", "Net Banking"),
                            ("upi", "UPI"),
                            ("wallet", "Wallet"),
                            ("emandate", "E-Mandate (Auto-pay)"),
                        ],
                        default="card",
                        max_length=50,
                        verbose_name="Payment Method",
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        null=True,
                        verbose_name="Refund Amount",
                    ),
                ),
                (
                    "refund_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Refund Reason"
                    ),
                ),
                ("payment_date", models.DateTimeField(verbose_name="Payment Date")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="subscriptions.invoice",
                        verbose_name="Invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trial", "Trial (14 days free)"),
                            ("active", "Active & Paid"),
                            ("past_due", "Payment Overdue"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="trial",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("end_date", models.DateTimeField()),
                ("trial_end_date", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("auto_renew", models.BooleanField(default=True)),
                (
                    "razorpay_subscription_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("cancellation_reason", models.TextField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.OneToOneField(
                        help_text="The company/workspace being billed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="orgs.company",
                        verbose_name="Company/Workspace",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="subscriptions.plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PriceOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_monthly_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Custom Monthly Price",
                    ),
                ),
                (
                    "custom_annual_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Custom Annual Price",
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage discount applied",
                        max_digits=5,
                        verbose_name="Discount %",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("annual_commitment", "Annual Commitment"),
                            ("volume_discount", "Volume Discount"),
                            ("competitor_match", "Competitor Matching"),
                            ("early_adopter", "Early Adopter"),
                            ("non_profit", "Non-Profit Organization"),
                            ("partner", "Strategic Partner"),
                            ("other", "Other"),
                        ],
                        max_length=255,
                        verbose_name="Discount Reason",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Internal Notes")),
                ("valid_from", models.DateField(verbose_name="Valid From")),
                (
                    "valid_until",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank for indefinite",
                        null=True,
                        verbose_name="Valid Until",
                    ),
                ),
                (
                    "approved_by",
                    models.CharField(
                        help_text="Admin email who approved",
                        max_length=255,
                        verbose_name="Approved By",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_overrides",
                        to="subscriptions.plan",
                        verbose_name="Base Plan",
                    ),
                ),
                (
                    "subscription",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_override",
                        to="subscriptions.subscription",
                        verbose_name="Subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price Override",
                "verbose_name_plural": "Price Overrides",
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="subscriptions.subscription",
                verbose_name="Subscription",
            ),
        ),
        migrations.CreateModel(
            name="UsageMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "users_count",
                    models.IntegerField(default=0, verbose_name="Active Users"),
                ),
                (
                    "transactions_count",
                    models.IntegerField(default=0, verbose_name="Transactions Count"),
                ),
                (
                    "invoices_count",
                    models.IntegerField(default=0, verbose_name="Invoices Count"),
                ),
                (
                    "products_count",
                    models.IntegerField(default=0, verbose_name="Products Count"),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True, help_text="Daily snapshot", verbose_name="Date"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_metrics",
                        to="subscriptions.subscription",
                        verbose_name="Subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usage Metric",
                "verbose_name_plural": "Usage Metrics",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["subscription", "date"],
                        name="subscriptio_subscri_653912_idx",
                    ),
                    models.Index(fields=["-date"], name="subscriptio_date_90cc9e_idx"),
                ],
                "unique_together": {("subscription", "date")},
            },
        ),
    ]
