# Generated by Django 6.0.3 on 2026-08-17 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


CODE_MAP = {
    "advanced_reporting": "reporting.advanced",
    "multi_warehouse": "inventory.multi_warehouse",
    "approvals": "workflow.approvals",
    "api": "api.access",
    "custom_fields": "workspace.custom_fields",
    "max_users": "workspace.max_members",
    "max_products": "inventory.max_products",
    "max_warehouses": "inventory.max_warehouses",
    "max_transactions_per_month": "workspace.max_transactions_per_month",
    "max_invoices_per_month": "workspace.max_invoices_per_month",
}


def canonicalize_entitlement_codes(apps, schema_editor):
    Entitlement = apps.get_model("subscriptions", "SubscriptionEntitlement")
    for old_code, new_code in CODE_MAP.items():
        for row in Entitlement.objects.filter(feature_code=old_code).iterator():
            existing = Entitlement.objects.filter(
                subscription_id=row.subscription_id,
                feature_code=new_code,
            ).first()
            if existing:
                row.delete()
            else:
                row.feature_code = new_code
                row.save(update_fields=["feature_code"])


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='is_active',
        ),
        migrations.AddField(
            model_name='providerwebhookevent',
            name='provider_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionentitlement',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionentitlement',
            name='override_actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_entitlement_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptionentitlement',
            name='override_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subscriptionentitlement',
            name='source',
            field=models.CharField(choices=[('plan', 'Plan projection'), ('override', 'Explicit override')], default='plan', max_length=20),
        ),
        migrations.RunPython(canonicalize_entitlement_codes, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='providerwebhookevent',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_event_id'), name='subscription_provider_event_unique'),
        ),
    ]
