# Generated by Django 6.0.3 on 2026-08-17 07:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_remove_subscription_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscriptionentitlement',
            constraint=models.CheckConstraint(condition=models.Q(('source', 'plan'), models.Q(('source', 'override'), ('override_actor__isnull', False), models.Q(('override_reason', ''), _negated=True)), _connector='OR'), name='subscription_override_requires_provenance'),
        ),
    ]
