# Generated by Django 6.0.3 on 2026-09-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscriptionentitlement_subscription_override_requires_provenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='checkout_key',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='checkout_snapshot',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Razorpay Order ID'),
        ),
    ]
