# Generated by Django 6.0.3 on 2026-09-24 12:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0009_workspace_role_identity'),
        ('subscriptions', '0009_resolution_evidence_guard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceAccessDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('full', 'Temporary normal access'), ('read_only', 'Temporary read-only restriction'), ('default', 'Return to normal subscription policy')], max_length=12)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('entitlement_snapshot', models.JSONField(default=list, editable=False)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='subscriptions.plan')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commercial_access_decisions', to='orgs.company')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
                'indexes': [models.Index(fields=['workspace', '-created_at'], name='subscription_access_latest')],
                'constraints': [models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='subscription_access_reason'), models.CheckConstraint(condition=models.Q(models.Q(('expires_at__isnull', True), ('mode', 'default')), models.Q(('expires_at__gt', models.F('created_at')), ('expires_at__isnull', False), ('mode__in', ['full', 'read_only'])), _connector='OR'), name='subscription_access_expiry')],
            },
        ),
    ]
