# Generated by Django 6.1.1 on 2026-09-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_access_decision_evidence_guard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='tier',
            field=models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='yearly_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual price in INR. Set explicitly for the agreed offer.', max_digits=8, null=True),
        ),
    ]
