# Generated by Django 6.1.1 on 2026-09-27 17:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0009_workspace_role_identity'),
        ('subscriptions', '0012_plan_price_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_key', models.UUIDField(unique=True)),
                ('request_snapshot', models.JSONField(editable=False)),
                ('state', models.CharField(choices=[('creating', 'Creation requested'), ('unknown', 'Provider outcome needs reconciliation'), ('verified', 'Provider agreement verified')], default='creating', max_length=12)),
                ('provider_subscription_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('provider_status', models.CharField(blank=True, max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_agreements', to='orgs.company')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RecurringAgreementEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=40)),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='subscriptions.recurringagreement')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RecurringPlanBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('test', 'Test'), ('live', 'Live')], max_length=4)),
                ('provider_plan_id', models.CharField(max_length=255)),
                ('snapshot', models.JSONField(editable=False)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.plan')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='recurringagreement',
            name='binding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.recurringplanbinding'),
        ),
        migrations.AddConstraint(
            model_name='recurringplanbinding',
            constraint=models.UniqueConstraint(fields=('mode', 'provider_plan_id'), name='recurring_provider_plan_identity'),
        ),
        migrations.AddConstraint(
            model_name='recurringplanbinding',
            constraint=models.CheckConstraint(condition=models.Q(('mode__in', ['test', 'live'])), name='recurring_plan_mode'),
        ),
        migrations.AddConstraint(
            model_name='recurringplanbinding',
            constraint=models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='recurring_plan_reason'),
        ),
        migrations.AddConstraint(
            model_name='recurringagreement',
            constraint=models.UniqueConstraint(condition=models.Q(('closed_at__isnull', True)), fields=('workspace',), name='recurring_one_open_workspace'),
        ),
        migrations.AddConstraint(
            model_name='recurringagreement',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['creating', 'unknown', 'verified'])), name='recurring_creation_state'),
        ),
        migrations.AddConstraint(
            model_name='recurringagreement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('provider_subscription_id__isnull', False), ('state', 'verified'), ('verified_at__isnull', False)), models.Q(('closed_at__isnull', True), ('provider_subscription_id__isnull', True), ('state__in', ['creating', 'unknown']), ('verified_at__isnull', True)), _connector='OR'), name='recurring_verified_identity'),
        ),
    ]
