# Generated by Django 6.1.1 on 2026-09-27 17:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0014_recurring_evidence_guard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringagreementevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RecurringCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_invoice_id', models.CharField(max_length=255, unique=True)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('evidence', models.JSONField(editable=False)),
                ('access_action', models.CharField(choices=[('applied', 'Paid-through advanced'), ('retained', 'Paid-through retained'), ('review', 'Access review required')], max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycles', to='subscriptions.recurringagreement')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_cycle', to='subscriptions.invoice')),
            ],
            options={
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('agreement', 'period_start', 'period_end'), name='recurring_cycle_period_unique'), models.CheckConstraint(condition=models.Q(('period_end__gt', models.F('period_start'))), name='recurring_cycle_period_order'), models.CheckConstraint(condition=models.Q(('access_action__in', ['applied', 'retained', 'review'])), name='recurring_cycle_access_action')],
            },
        ),
    ]
