# Generated by Django 6.1.1 on 2026-09-27 19:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0016_recurring_cycle_evidence_guard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringAccessResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('evidence', models.JSONField(editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('cycle', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='access_resolution', to='subscriptions.recurringcycle')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER recurring_access_resolution_immutable
            BEFORE UPDATE OR DELETE ON subscriptions_recurringaccessresolution FOR EACH ROW
            EXECUTE FUNCTION subscriptions_guard_recurring_fixed();

            CREATE FUNCTION subscriptions_guard_recurring_access_resolution() RETURNS trigger LANGUAGE plpgsql AS $$
            BEGIN
              IF length(trim(NEW.reason)) = 0 OR length(NEW.reason) > 1000 OR NOT EXISTS (
                SELECT 1 FROM subscriptions_recurringcycle c
                JOIN subscriptions_invoice i ON i.id = c.invoice_id
                JOIN subscriptions_subscription s ON s.id = i.subscription_id
                JOIN subscriptions_recurringagreement a ON a.id = c.agreement_id
                WHERE c.id = NEW.cycle_id AND c.access_action = 'review'
                  AND i.checkout_snapshot->>'access_review_reason' = 'future_period'
                  AND s.company_id = a.workspace_id AND s.status = 'active'
                  AND s.end_date = c.period_end AND NEW.evidence->'provider' = c.evidence
                  AND (NEW.evidence->'after'->>'end_date')::timestamptz = c.period_end
              ) THEN RAISE EXCEPTION 'Access resolution must match an applied held cycle'; END IF;
              RETURN NEW;
            END; $$;
            CREATE TRIGGER recurring_access_resolution_link
            BEFORE INSERT ON subscriptions_recurringaccessresolution FOR EACH ROW
            EXECUTE FUNCTION subscriptions_guard_recurring_access_resolution();
            """,
            reverse_sql="""
            DROP TRIGGER recurring_access_resolution_link ON subscriptions_recurringaccessresolution;
            DROP FUNCTION subscriptions_guard_recurring_access_resolution();
            DROP TRIGGER recurring_access_resolution_immutable ON subscriptions_recurringaccessresolution;
            """,
        ),
    ]
