# Generated by Django 6.0.3 on 2026-07-17 13:14

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0024_alter_auditlog_action'),
        ('party', '0005_partyportalaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('license_number', models.CharField(max_length=100)),
                ('issuing_authority', models.CharField(blank=True, max_length=255)),
                ('issued_on', models.DateField()),
                ('expires_on', models.DateField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_licenses_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_licenses_updated', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_licenses', to='orgs.company')),
            ],
            options={
                'ordering': ('workspace_id', 'license_number'),
            },
        ),
        migrations.CreateModel(
            name='LoanSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series', to='loans.loanlicense')),
            ],
            options={
                'ordering': ('license_id', 'code'),
            },
        ),
        migrations.CreateModel(
            name='LoanNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_kind', models.CharField(choices=[('PAWN_LOAN', 'Pawn Loan'), ('PAWN_LOAN_RELEASE', 'Pawn Loan Release')], max_length=32)),
                ('prefix', models.CharField(max_length=24)),
                ('width', models.PositiveSmallIntegerField(default=5)),
                ('next_number', models.PositiveBigIntegerField(default=1)),
                ('maximum_number', models.PositiveBigIntegerField(default=10000)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_number_sequences_updated', to=settings.AUTH_USER_MODEL)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='number_sequences', to='loans.loanseries')),
            ],
            options={
                'ordering': ('series_id', 'document_kind'),
            },
        ),
        migrations.CreateModel(
            name='PawnLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_number', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled'), ('CLOSED', 'Closed')], db_index=True, default='DRAFT', max_length=16)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('monthly_interest_rate', models.DecimalField(decimal_places=6, max_digits=9)),
                ('loan_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('tenure_months', models.PositiveIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pawn_loans', to='party.party')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pawn_loans_created', to=settings.AUTH_USER_MODEL)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pawn_loans', to='loans.loanlicense')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pawn_loans', to='loans.loanseries')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pawn_loans_updated', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pawn_loans', to='orgs.company')),
            ],
            options={
                'ordering': ('loan_date', 'loan_number'),
            },
        ),
        migrations.CreateModel(
            name='PawnCollateralItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('metal', models.CharField(choices=[('GOLD', 'Gold'), ('SILVER', 'Silver'), ('OTHER', 'Other')], max_length=16)),
                ('gross_weight', models.DecimalField(decimal_places=4, max_digits=14)),
                ('net_weight', models.DecimalField(decimal_places=4, max_digits=14)),
                ('purity_percentage', models.DecimalField(decimal_places=4, max_digits=7)),
                ('latest_appraised_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('custody_state', models.CharField(choices=[('IN_VAULT', 'In Vault'), ('WITH_CUSTOMER', 'With Customer'), ('WITH_FUNDING_LENDER', 'With Funding Lender')], db_index=True, default='IN_VAULT', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collateral_items', to='loans.pawnloan')),
            ],
            options={
                'ordering': ('loan_id', 'id'),
            },
        ),
        migrations.CreateModel(
            name='LoanPolicySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_version', models.PositiveSmallIntegerField(default=1)),
                ('interest_method', models.CharField(choices=[('SIMPLE', 'Simple'), ('COMPOUND', 'Compound')], max_length=16)),
                ('partial_month_method', models.CharField(choices=[('FULL_MONTH', 'Full Month'), ('SLAB', 'Slab')], max_length=16)),
                ('partial_month_cutoff_days', models.PositiveSmallIntegerField(default=15)),
                ('partial_month_lower_fraction', models.DecimalField(decimal_places=4, default=Decimal('0.5'), max_digits=5)),
                ('capitalization_interval_periods', models.PositiveSmallIntegerField(default=12)),
                ('accounting_recognition', models.CharField(choices=[('CASH', 'Cash'), ('ACCRUAL', 'Accrual')], max_length=16)),
                ('valuation_method', models.CharField(choices=[('CALCULATED_METAL_VALUE', 'Calculated Metal Value'), ('LATEST_APPRAISAL', 'Latest Appraisal'), ('LOWER_OF_CALCULATED_AND_APPRAISAL', 'Lower Of Calculated And Appraisal')], max_length=48)),
                ('maximum_ltv_ratio', models.DecimalField(decimal_places=4, default=Decimal('0.80'), max_digits=5)),
                ('rounding_method', models.CharField(choices=[('PER_ACCRUAL_PERIOD', 'Per Accrual Period')], max_length=32)),
                ('currency_quantum', models.DecimalField(decimal_places=4, default=Decimal('0.01'), max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='policy_snapshot', to='loans.pawnloan')),
            ],
        ),
        migrations.CreateModel(
            name='LoanChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_kind', models.CharField(choices=[('DRAFT_CREATED', 'Draft Created'), ('DRAFT_UPDATED', 'Draft Updated'), ('APPROVED', 'Approved'), ('RETURNED_TO_DRAFT', 'Returned To Draft'), ('CANCELLED', 'Cancelled'), ('DISBURSED', 'Disbursed'), ('REPAYMENT_RECORDED', 'Repayment Recorded'), ('ACCRUAL_FINALIZED', 'Accrual Finalized'), ('INTEREST_CAPITALIZED', 'Interest Capitalized'), ('RELEASE_COMPLETED', 'Release Completed'), ('CLOSED', 'Closed'), ('REVERSAL_RECORDED', 'Reversal Recorded')], max_length=40)),
                ('from_state', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled'), ('CLOSED', 'Closed')], max_length=16)),
                ('to_state', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled'), ('CLOSED', 'Closed')], max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pawn_loan_changes', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_log', to='loans.pawnloan')),
            ],
            options={
                'ordering': ('loan_id', 'created_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='loanlicense',
            index=models.Index(fields=['workspace', 'is_active', 'expires_on'], name='loans_license_ready_idx'),
        ),
        migrations.AddConstraint(
            model_name='loanlicense',
            constraint=models.UniqueConstraint(fields=('workspace', 'license_number'), name='loans_license_workspace_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='loanlicense',
            constraint=models.CheckConstraint(condition=models.Q(('expires_on__gte', models.F('issued_on'))), name='loans_license_dates_valid'),
        ),
        migrations.AddIndex(
            model_name='loanseries',
            index=models.Index(fields=['license', 'is_active'], name='loans_series_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='loanseries',
            constraint=models.UniqueConstraint(fields=('license', 'code'), name='loans_series_license_code_uniq'),
        ),
        migrations.AddIndex(
            model_name='loannumbersequence',
            index=models.Index(fields=['document_kind', 'is_active'], name='loans_sequence_kind_idx'),
        ),
        migrations.AddConstraint(
            model_name='loannumbersequence',
            constraint=models.UniqueConstraint(fields=('series', 'document_kind'), name='loans_sequence_series_kind_uniq'),
        ),
        migrations.AddConstraint(
            model_name='loannumbersequence',
            constraint=models.CheckConstraint(condition=models.Q(('width__gt', 0)), name='loans_sequence_width_positive'),
        ),
        migrations.AddConstraint(
            model_name='loannumbersequence',
            constraint=models.CheckConstraint(condition=models.Q(('next_number__gt', 0)), name='loans_sequence_next_positive'),
        ),
        migrations.AddConstraint(
            model_name='loannumbersequence',
            constraint=models.CheckConstraint(condition=models.Q(('maximum_number__gt', 0)), name='loans_sequence_max_positive'),
        ),
        migrations.AddIndex(
            model_name='pawnloan',
            index=models.Index(fields=['workspace', 'state', 'loan_date'], name='loans_pawn_state_date_idx'),
        ),
        migrations.AddIndex(
            model_name='pawnloan',
            index=models.Index(fields=['borrower', 'state'], name='loans_pawn_party_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='pawnloan',
            constraint=models.UniqueConstraint(fields=('workspace', 'loan_number'), name='loans_pawn_workspace_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pawnloan',
            constraint=models.CheckConstraint(condition=models.Q(('principal_amount__gt', 0)), name='loans_pawn_principal_positive'),
        ),
        migrations.AddConstraint(
            model_name='pawnloan',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_interest_rate__gte', 0)), name='loans_pawn_rate_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='pawnloan',
            constraint=models.CheckConstraint(condition=models.Q(('tenure_months__gt', 0)), name='loans_pawn_tenure_positive'),
        ),
        migrations.AddIndex(
            model_name='pawncollateralitem',
            index=models.Index(fields=['loan', 'custody_state'], name='loans_item_custody_idx'),
        ),
        migrations.AddConstraint(
            model_name='pawncollateralitem',
            constraint=models.CheckConstraint(condition=models.Q(('gross_weight__gt', 0)), name='loans_item_gross_positive'),
        ),
        migrations.AddConstraint(
            model_name='pawncollateralitem',
            constraint=models.CheckConstraint(condition=models.Q(('net_weight__gt', 0)), name='loans_item_net_positive'),
        ),
        migrations.AddConstraint(
            model_name='pawncollateralitem',
            constraint=models.CheckConstraint(condition=models.Q(('gross_weight__gte', models.F('net_weight'))), name='loans_item_gross_gte_net'),
        ),
        migrations.AddConstraint(
            model_name='pawncollateralitem',
            constraint=models.CheckConstraint(condition=models.Q(('purity_percentage__gt', 0), ('purity_percentage__lte', 100)), name='loans_item_purity_range'),
        ),
        migrations.AddConstraint(
            model_name='pawncollateralitem',
            constraint=models.CheckConstraint(condition=models.Q(('latest_appraised_value__isnull', True), ('latest_appraised_value__gt', 0), _connector='OR'), name='loans_item_appraisal_positive'),
        ),
        migrations.AddConstraint(
            model_name='loanpolicysnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('policy_version__gt', 0)), name='loans_policy_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='loanpolicysnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('maximum_ltv_ratio__gt', 0), ('maximum_ltv_ratio__lte', 1)), name='loans_policy_ltv_range'),
        ),
        migrations.AddIndex(
            model_name='loanchangelog',
            index=models.Index(fields=['loan', 'event_kind', 'created_at'], name='loans_change_event_idx'),
        ),
    ]
