# Generated by Django 6.0.3 on 2026-09-09 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from apps.tenancy.rls import EnableWorkspaceRLS


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_database_guards'),
        ('orgs', '0009_workspace_role_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PawnReleaseBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_key', models.UUIDField()),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('effective_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('paid_by', models.CharField(max_length=255)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='PawnReleaseBatchLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_name', models.CharField(max_length=255)),
                ('collector_name', models.CharField(max_length=255)),
                ('collector_is_borrower', models.BooleanField()),
                ('relationship', models.CharField(blank=True, max_length=100)),
                ('authorization_note', models.CharField(blank=True, max_length=500)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='loans.pawnreleasebatch')),
                ('release', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='batch_line', to='loans.pawnloanrelease')),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddConstraint(
            model_name='pawnreleasebatch',
            constraint=models.UniqueConstraint(fields=('workspace', 'request_key'), name='loans_batch_workspace_request_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pawnreleasebatch',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='loans_batch_total_nonnegative'),
        ),
        EnableWorkspaceRLS("PawnReleaseBatch"),
        EnableWorkspaceRLS("PawnReleaseBatchLine"),
        migrations.RunSQL(
            sql="""
            CREATE FUNCTION loans_release_batch_guard() RETURNS trigger LANGUAGE plpgsql AS $$
            BEGIN
                IF TG_OP <> 'INSERT' THEN
                    RAISE EXCEPTION 'Release batch evidence is immutable';
                END IF;
                IF TG_TABLE_NAME = 'loans_pawnreleasebatchline' THEN
                    IF NOT EXISTS (
                        SELECT 1 FROM loans_pawnreleasebatch b, loans_pawnloanrelease r
                        WHERE b.id = NEW.batch_id AND r.id = NEW.release_id
                          AND b.workspace_id = NEW.workspace_id AND r.workspace_id = NEW.workspace_id
                          AND b.effective_date = r.effective_date
                    ) THEN RAISE EXCEPTION 'Batch release must share workspace and effective date'; END IF;
                    IF btrim(NEW.collector_name) = '' OR (NOT NEW.collector_is_borrower AND
                        (btrim(NEW.relationship) = '' OR btrim(NEW.authorization_note) = ''))
                    THEN RAISE EXCEPTION 'Collector confirmation is required'; END IF;
                END IF;
                RETURN NEW;
            END $$;
            CREATE TRIGGER loans_batch_immutable BEFORE UPDATE OR DELETE ON loans_pawnreleasebatch
                FOR EACH ROW EXECUTE FUNCTION loans_release_batch_guard();
            CREATE TRIGGER loans_batch_line_guard BEFORE INSERT OR UPDATE OR DELETE ON loans_pawnreleasebatchline
                FOR EACH ROW EXECUTE FUNCTION loans_release_batch_guard();
            CREATE FUNCTION loans_release_batch_total_guard() RETURNS trigger LANGUAGE plpgsql AS $$
            DECLARE batch_id_value bigint; item_count bigint; actual numeric; expected numeric;
            BEGIN
                IF TG_TABLE_NAME = 'loans_pawnreleasebatch' THEN batch_id_value := NEW.id;
                ELSE batch_id_value := NEW.batch_id; END IF;
                SELECT total_amount INTO expected FROM loans_pawnreleasebatch WHERE id = batch_id_value;
                SELECT count(*), COALESCE(sum(r.settlement_amount), 0) INTO item_count, actual
                    FROM loans_pawnreleasebatchline l JOIN loans_pawnloanrelease r ON r.id = l.release_id
                    WHERE l.batch_id = batch_id_value;
                IF item_count = 0 OR actual <> expected THEN RAISE EXCEPTION 'Batch total must match its releases'; END IF;
                RETURN NULL;
            END $$;
            CREATE CONSTRAINT TRIGGER loans_batch_total AFTER INSERT ON loans_pawnreleasebatch
                DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION loans_release_batch_total_guard();
            CREATE CONSTRAINT TRIGGER loans_batch_line_total AFTER INSERT ON loans_pawnreleasebatchline
                DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION loans_release_batch_total_guard();
            """,
            reverse_sql="""
            DROP TRIGGER loans_batch_line_total ON loans_pawnreleasebatchline;
            DROP TRIGGER loans_batch_total ON loans_pawnreleasebatch;
            DROP FUNCTION loans_release_batch_total_guard();
            DROP TRIGGER loans_batch_line_guard ON loans_pawnreleasebatchline;
            DROP TRIGGER loans_batch_immutable ON loans_pawnreleasebatch;
            DROP FUNCTION loans_release_batch_guard();
            """,
        ),
    ]
