# Generated by Django 6.0.3 on 2026-09-11 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


APPRAISAL_GUARD = """
CREATE FUNCTION loans_guard_appraisal_evidence() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE item_workspace bigint; previous loans_collateralappraisal%ROWTYPE;
BEGIN
    IF TG_OP <> 'INSERT' THEN
        RAISE EXCEPTION 'Appraisals are immutable; append a reviewed version';
    END IF;
    SELECT item.workspace_id INTO item_workspace FROM loans_pawncollateralitem item
    JOIN loans_pawnloan loan ON loan.id = item.loan_id AND loan.workspace_id = NEW.workspace_id
    WHERE item.id = NEW.collateral_item_id;
    IF NOT FOUND OR item_workspace <> NEW.workspace_id THEN
        RAISE EXCEPTION 'Appraisal collateral must belong to the same Workspace';
    END IF;
    IF NEW.supersedes_id IS NOT NULL THEN
        SELECT * INTO previous FROM loans_collateralappraisal WHERE id = NEW.supersedes_id;
        IF NOT FOUND OR previous.workspace_id <> NEW.workspace_id OR previous.collateral_item_id <> NEW.collateral_item_id THEN
            RAISE EXCEPTION 'Appraisal predecessor must belong to the same item and Workspace';
        END IF;
    END IF;
    IF NEW.appraised_value::text = 'NaN' THEN
        RAISE EXCEPTION 'Appraisal value must be finite';
    END IF;
    IF NEW.method IN ('PHYSICAL_INSPECTION', 'EXTERNAL_REPORT') AND
       (NEW.created_by_id IS NULL OR length(trim(NEW.review_notes)) = 0 OR length(trim(NEW.evidence_reference)) = 0) THEN
        RAISE EXCEPTION 'Reassessment requires actor, supporting reference and reason';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER loans_appraisal_evidence BEFORE INSERT OR UPDATE OR DELETE ON loans_collateralappraisal
FOR EACH ROW EXECUTE FUNCTION loans_guard_appraisal_evidence();
"""


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_pawnreleasebatch_pawnreleasebatchline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collateralappraisal',
            name='valuation_context',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='collateralappraisal',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collateral_appraisals_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunSQL(APPRAISAL_GUARD, "DROP TRIGGER loans_appraisal_evidence ON loans_collateralappraisal; DROP FUNCTION loans_guard_appraisal_evidence();"),
        migrations.RunSQL("UPDATE loans_loanrisksnapshot SET status = 'STALE', error_message = 'Valuation freshness rules changed; reassessment required.' WHERE status <> 'ERROR'", migrations.RunSQL.noop),
    ]
