# Generated by Django 6.0.3 on 2026-09-11 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


GUARD = """
CREATE FUNCTION loans_guard_monitoring_policy() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE prior loans_loanmonitoringpolicy%ROWTYPE;
BEGIN
  IF TG_OP <> 'INSERT' THEN
    RAISE EXCEPTION 'Monitoring policy evidence is immutable; append an amendment';
  END IF;
  PERFORM id FROM orgs_company WHERE id = NEW.workspace_id FOR UPDATE;
  IF NEW.license_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM loans_loanlicense WHERE id = NEW.license_id AND workspace_id = NEW.workspace_id
  ) THEN RAISE EXCEPTION 'Monitoring license must belong to its Workspace'; END IF;
  IF NEW.supersedes_id IS NOT NULL THEN
    SELECT * INTO prior FROM loans_loanmonitoringpolicy WHERE id = NEW.supersedes_id;
    IF NOT FOUND OR prior.workspace_id <> NEW.workspace_id
       OR prior.license_id IS DISTINCT FROM NEW.license_id
       OR prior.effective_until IS NOT NULL OR NEW.effective_until IS NOT NULL
       OR NEW.effective_from < prior.effective_from OR NEW.version <= prior.version
       OR NEW.created_by_id IS NULL OR btrim(NEW.amendment_reason) = '' THEN
      RAISE EXCEPTION 'Invalid monitoring policy amendment';
    END IF;
  END IF;
  IF EXISTS (
    WITH RECURSIVE ancestors AS (
      SELECT id, supersedes_id FROM loans_loanmonitoringpolicy WHERE id = NEW.supersedes_id
      UNION ALL
      SELECT p.id, p.supersedes_id FROM loans_loanmonitoringpolicy p JOIN ancestors a ON p.id = a.supersedes_id
    )
    SELECT 1 FROM loans_loanmonitoringpolicy p
    WHERE p.workspace_id = NEW.workspace_id AND p.license_id IS NOT DISTINCT FROM NEW.license_id
      AND (p.effective_until IS NULL OR p.effective_until >= NEW.effective_from)
      AND (NEW.effective_until IS NULL OR p.effective_from <= NEW.effective_until)
      AND p.id NOT IN (SELECT id FROM ancestors)
  ) THEN RAISE EXCEPTION 'Monitoring periods may overlap only through explicit supersession'; END IF;
  RETURN NEW;
END; $$;
CREATE TRIGGER loans_monitoring_policy_evidence_guard
BEFORE INSERT OR UPDATE OR DELETE ON loans_loanmonitoringpolicy
FOR EACH ROW EXECUTE FUNCTION loans_guard_monitoring_policy();
UPDATE loans_loanrisksnapshot SET status = 'STALE',
  error_message = 'Monitoring portfolio contract changed; reassessment required.' WHERE status <> 'ERROR';
"""


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_collateralappraisal_valuation_context_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loanmonitoringpolicy',
            name='amendment_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='loanmonitoringpolicy',
            name='supersedes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor', to='loans.loanmonitoringpolicy'),
        ),
        migrations.AlterField(
            model_name='loanmonitoringpolicy',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_monitoring_policies_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunSQL(GUARD, "DROP TRIGGER loans_monitoring_policy_evidence_guard ON loans_loanmonitoringpolicy; DROP FUNCTION loans_guard_monitoring_policy();"),
    ]
