# Generated by Django 6.0.3 on 2026-08-03 08:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_pawnloanaccountingevent_reversal_of'),
        ('orgs', '0024_alter_auditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PawnLoanRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_number', models.CharField(max_length=64)),
                ('request_key', models.CharField(max_length=120)),
                ('effective_date', models.DateField(db_index=True)),
                ('is_full_release', models.BooleanField(default=True)),
                ('settlement_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('principal_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('interest_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('fee_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('valuation_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accounting_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='release', to='loans.pawnloanaccountingevent')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pawn_loan_releases_created', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='releases', to='loans.pawnloan')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pawn_loan_releases', to='orgs.company')),
            ],
            options={
                'ordering': ('loan_id', 'effective_date', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PawnCollateralCustodyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.CharField(choices=[('IN_VAULT', 'In Vault'), ('WITH_CUSTOMER', 'With Customer'), ('WITH_FUNDING_LENDER', 'With Funding Lender')], max_length=32)),
                ('to_state', models.CharField(choices=[('IN_VAULT', 'In Vault'), ('WITH_CUSTOMER', 'With Customer'), ('WITH_FUNDING_LENDER', 'With Funding Lender')], max_length=32)),
                ('effective_date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pawn_collateral_custody_events', to=settings.AUTH_USER_MODEL)),
                ('collateral_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custody_history', to='loans.pawncollateralitem')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custody_events', to='loans.pawnloanrelease')),
            ],
            options={
                'ordering': ('collateral_item_id', 'created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PawnLoanReleaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuation_snapshot', models.JSONField(default=dict)),
                ('returned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('collateral_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='release_items', to='loans.pawncollateralitem')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='loans.pawnloanrelease')),
            ],
            options={
                'ordering': ('release_id', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='pawnloanrelease',
            constraint=models.UniqueConstraint(fields=('workspace', 'release_number'), name='loans_release_workspace_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pawnloanrelease',
            constraint=models.UniqueConstraint(fields=('loan', 'request_key'), name='loans_release_loan_request_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pawnloanrelease',
            constraint=models.CheckConstraint(condition=models.Q(('settlement_amount__gte', 0), ('principal_amount__gte', 0), ('interest_amount__gte', 0), ('fee_amount__gte', 0)), name='loans_release_amounts_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='pawncollateralcustodyevent',
            constraint=models.CheckConstraint(condition=models.Q(('from_state', models.F('to_state')), _negated=True), name='loans_custody_state_changes'),
        ),
        migrations.AddConstraint(
            model_name='pawnloanreleaseitem',
            constraint=models.UniqueConstraint(fields=('release', 'collateral_item'), name='loans_release_item_uniq'),
        ),
    ]
