# Generated by Django 6.0.3 on 2026-08-03 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_pawnloanrelease_pawncollateralcustodyevent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pawnloanrelease',
            name='catch_up_accrual',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='release_catch_up', to='loans.pawnloaninterestaccrual'),
        ),
        migrations.CreateModel(
            name='PawnLoanReleaseReversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accounting_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='release_reversal', to='loans.pawnloanaccountingevent')),
                ('catch_up_reversal_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='release_catch_up_reversal', to='loans.pawnloanaccountingevent')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pawn_loan_release_reversals_created', to=settings.AUTH_USER_MODEL)),
                ('release', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='loans.pawnloanrelease')),
            ],
        ),
        migrations.AddField(
            model_name='pawncollateralcustodyevent',
            name='release_reversal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custody_events', to='loans.pawnloanreleasereversal'),
        ),
    ]
