# Generated by Django 6.0.3 on 2026-08-04 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_pawnloanrelease_catch_up_accrual_and_more'),
        ('orgs', '0024_alter_auditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PawnLoanNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_kind', models.CharField(choices=[('REPAYMENT_REMINDER', 'Repayment Reminder'), ('INTEREST_DUE', 'Interest Due'), ('OVERDUE_NOTICE', 'Overdue Notice'), ('RELEASE_CONFIRMATION', 'Release Confirmation'), ('AUCTION_NOTICE', 'Auction Notice')], max_length=32)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'Sms'), ('WHATSAPP', 'Whatsapp')], max_length=16)),
                ('request_key', models.CharField(max_length=120)),
                ('scheduled_for', models.DateTimeField(db_index=True)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('recipient_phone', models.CharField(blank=True, max_length=32)),
                ('payload_snapshot', models.JSONField(default=dict)),
                ('notification_event_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('notification_job_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pawn_loan_notices_created', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notices', to='loans.pawnloan')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pawn_loan_notices', to='orgs.company')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['workspace', 'scheduled_for'], name='loans_notice_due_idx'), models.Index(fields=['loan', 'notice_kind', 'created_at'], name='loans_notice_kind_idx')],
                'constraints': [models.UniqueConstraint(fields=('loan', 'request_key'), name='loans_notice_loan_request_uniq')],
            },
        ),
    ]
