# Generated by Django 6.0.3 on 2026-09-12 06:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from apps.tenancy.rls import EnableWorkspaceRLS


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_immutable_history_evidence'),
        ('orgs', '0009_workspace_role_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLoanImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_namespace', models.UUIDField()),
                ('source_id', models.CharField(max_length=120)),
                ('source_sha256', models.CharField(max_length=64)),
                ('document', models.JSONField()),
                ('references', models.JSONField()),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='historical_import', to='loans.pawnloan')),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('workspace', 'source_namespace', 'source_id'), name='loans_history_source_unique')],
            },
        ),
        EnableWorkspaceRLS("HistoricalLoanImport"),
        migrations.RunSQL("""
CREATE FUNCTION loans_history_origin_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF TG_OP <> 'INSERT' THEN RAISE EXCEPTION 'Historical source evidence is immutable'; END IF;
 IF NOT EXISTS (SELECT 1 FROM loans_pawnloan WHERE id=NEW.loan_id AND workspace_id=NEW.workspace_id)
 OR NEW.source_sha256 !~ '^[0-9a-f]{64}$' THEN RAISE EXCEPTION 'Invalid historical loan source reference'; END IF;
 RETURN NEW;
END; $$;
CREATE TRIGGER loans_history_origin_guard BEFORE INSERT OR UPDATE OR DELETE ON loans_historicalloanimport
FOR EACH ROW EXECUTE FUNCTION loans_history_origin_guard();
""", "DROP TRIGGER loans_history_origin_guard ON loans_historicalloanimport; DROP FUNCTION loans_history_origin_guard();"),
    ]
