# Generated by Django 6.0.3 on 2026-09-12 10:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_historicalloanimport'),
        ('orgs', '0009_workspace_role_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pawnloanevent',
            name='event_kind',
            field=models.CharField(choices=[('MIGRATION_OPENING', 'Migration Opening'), ('DISBURSAL', 'Disbursal'), ('REPAYMENT', 'Repayment'), ('INTEREST_ACCRUAL', 'Interest Accrual'), ('INTEREST_CAPITALIZATION', 'Interest Capitalization'), ('RELEASE_RECEIPT', 'Release Receipt'), ('AUCTION_RECOVERY', 'Auction Recovery'), ('RENEWAL_SETTLEMENT', 'Renewal Settlement'), ('RENEWAL_OPENING', 'Renewal Opening'), ('REVERSAL', 'Reversal')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='pawnloanevent',
            constraint=models.UniqueConstraint(condition=models.Q(('event_kind', 'MIGRATION_OPENING')), fields=('loan',), name='loans_one_migration_opening'),
        ),
    ]
