# Generated by Django 6.0.3 on 2026-08-04 11:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_pawnloannotice'),
        ('orgs', '0024_alter_auditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanchangelog',
            name='event_kind',
            field=models.CharField(choices=[('DRAFT_CREATED', 'Draft Created'), ('DRAFT_UPDATED', 'Draft Updated'), ('LICENSE_TRANSFERRED', 'License Transferred'), ('APPROVED', 'Approved'), ('RETURNED_TO_DRAFT', 'Returned To Draft'), ('CANCELLED', 'Cancelled'), ('DISBURSED', 'Disbursed'), ('REPAYMENT_RECORDED', 'Repayment Recorded'), ('ACCRUAL_FINALIZED', 'Accrual Finalized'), ('INTEREST_CAPITALIZED', 'Interest Capitalized'), ('RELEASE_COMPLETED', 'Release Completed'), ('AUCTION_INITIATED', 'Auction Initiated'), ('AUCTION_STARTED', 'Auction Started'), ('AUCTION_CANCELLED', 'Auction Cancelled'), ('AUCTION_COMPLETED', 'Auction Completed'), ('AUCTION_REVERSED', 'Auction Reversed'), ('CLOSED', 'Closed'), ('REVERSAL_RECORDED', 'Reversal Recorded')], max_length=40),
        ),
        migrations.AlterField(
            model_name='pawncollateralcustodyevent',
            name='from_state',
            field=models.CharField(choices=[('IN_VAULT', 'In Vault'), ('WITH_CUSTOMER', 'With Customer'), ('WITH_FUNDING_LENDER', 'With Funding Lender'), ('AUCTION_DISPOSED', 'Auction Disposed')], max_length=32),
        ),
        migrations.AlterField(
            model_name='pawncollateralcustodyevent',
            name='release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custody_events', to='loans.pawnloanrelease'),
        ),
        migrations.AlterField(
            model_name='pawncollateralcustodyevent',
            name='to_state',
            field=models.CharField(choices=[('IN_VAULT', 'In Vault'), ('WITH_CUSTOMER', 'With Customer'), ('WITH_FUNDING_LENDER', 'With Funding Lender'), ('AUCTION_DISPOSED', 'Auction Disposed')], max_length=32),
        ),
        migrations.AlterField(
            model_name='pawncollateralitem',
            name='custody_state',
            field=models.CharField(choices=[('IN_VAULT', 'In Vault'), ('WITH_CUSTOMER', 'With Customer'), ('WITH_FUNDING_LENDER', 'With Funding Lender'), ('AUCTION_DISPOSED', 'Auction Disposed')], db_index=True, default='IN_VAULT', max_length=32),
        ),
        migrations.AlterField(
            model_name='pawnloanaccountingevent',
            name='event_kind',
            field=models.CharField(choices=[('DISBURSAL', 'Disbursal'), ('REPAYMENT', 'Repayment'), ('INTEREST_ACCRUAL', 'Interest Accrual'), ('INTEREST_CAPITALIZATION', 'Interest Capitalization'), ('RELEASE_RECEIPT', 'Release Receipt'), ('AUCTION_RECOVERY', 'Auction Recovery'), ('REVERSAL', 'Reversal')], max_length=32),
        ),
        migrations.CreateModel(
            name='PawnLoanAuction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_number', models.CharField(max_length=96)),
                ('attempt_number', models.PositiveIntegerField()),
                ('request_key', models.CharField(max_length=120)),
                ('state', models.CharField(choices=[('INITIATED', 'Initiated'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='INITIATED', max_length=20)),
                ('notice_date', models.DateField()),
                ('scheduled_date', models.DateField(db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('buyer_name', models.CharField(blank=True, max_length=255)),
                ('buyer_reference', models.CharField(blank=True, max_length=120)),
                ('recovery_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('principal_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('interest_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('fee_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accounting_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auction', to='loans.pawnloanaccountingevent')),
                ('catch_up_accrual', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auction_catch_up', to='loans.pawnloaninterestaccrual')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pawn_loan_auctions_created', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auctions', to='loans.pawnloan')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pawn_loan_auctions', to='orgs.company')),
            ],
            options={
                'ordering': ('loan_id', 'attempt_number'),
            },
        ),
        migrations.AddField(
            model_name='pawncollateralcustodyevent',
            name='auction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custody_events', to='loans.pawnloanauction'),
        ),
        migrations.AddField(
            model_name='pawnloannotice',
            name='source_auction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notice', to='loans.pawnloanauction'),
        ),
        migrations.CreateModel(
            name='PawnLoanAuctionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.JSONField(default=dict)),
                ('disposed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='loans.pawnloanauction')),
                ('collateral_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auction_items', to='loans.pawncollateralitem')),
            ],
            options={
                'ordering': ('auction_id', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PawnLoanAuctionReversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accounting_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='auction_reversal', to='loans.pawnloanaccountingevent')),
                ('auction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='loans.pawnloanauction')),
                ('catch_up_reversal_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auction_catch_up_reversal', to='loans.pawnloanaccountingevent')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pawn_loan_auction_reversals_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pawncollateralcustodyevent',
            name='auction_reversal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custody_events', to='loans.pawnloanauctionreversal'),
        ),
        migrations.AddConstraint(
            model_name='pawncollateralcustodyevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('release__isnull', False), ('auction__isnull', True)), models.Q(('release__isnull', True), ('auction__isnull', False)), _connector='OR'), name='loans_custody_one_source'),
        ),
        migrations.AddIndex(
            model_name='pawnloanauction',
            index=models.Index(fields=['workspace', 'state', 'scheduled_date'], name='loans_auction_state_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='pawnloanauction',
            constraint=models.UniqueConstraint(fields=('workspace', 'auction_number'), name='loans_auction_workspace_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pawnloanauction',
            constraint=models.UniqueConstraint(fields=('loan', 'attempt_number'), name='loans_auction_loan_attempt_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pawnloanauction',
            constraint=models.UniqueConstraint(fields=('loan', 'request_key'), name='loans_auction_loan_request_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pawnloanauctionitem',
            constraint=models.UniqueConstraint(fields=('auction', 'collateral_item'), name='loans_auction_item_uniq'),
        ),
    ]
