# Generated by Django 6.0.3 on 2026-08-04 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0010_alter_loanchangelog_event_kind_and_more'),
        ('orgs', '0024_alter_auditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PawnLoanRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewal_number', models.CharField(max_length=96)),
                ('request_key', models.CharField(max_length=120)),
                ('mode', models.CharField(choices=[('PAY_AND_RENEW', 'Pay And Renew'), ('TOP_UP_RENEW', 'Top Up Renew')], max_length=20)),
                ('renewal_date', models.DateField(db_index=True)),
                ('source_principal_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('source_capitalized_principal_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('interest_settled', models.DecimalField(decimal_places=4, max_digits=18)),
                ('fees_settled', models.DecimalField(decimal_places=4, max_digits=18)),
                ('principal_paid', models.DecimalField(decimal_places=4, max_digits=18)),
                ('top_up_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('successor_principal_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('successor_capitalized_principal_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('valuation_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-renewal_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PawnLoanRenewalReversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='pawncollateralcustodyevent',
            name='loans_custody_one_source',
        ),
        migrations.AddField(
            model_name='pawncollateralitem',
            name='renewed_from',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='renewed_as', to='loans.pawncollateralitem'),
        ),
        migrations.AlterField(
            model_name='loanchangelog',
            name='event_kind',
            field=models.CharField(choices=[('DRAFT_CREATED', 'Draft Created'), ('DRAFT_UPDATED', 'Draft Updated'), ('LICENSE_TRANSFERRED', 'License Transferred'), ('APPROVED', 'Approved'), ('RETURNED_TO_DRAFT', 'Returned To Draft'), ('CANCELLED', 'Cancelled'), ('DISBURSED', 'Disbursed'), ('REPAYMENT_RECORDED', 'Repayment Recorded'), ('ACCRUAL_FINALIZED', 'Accrual Finalized'), ('INTEREST_CAPITALIZED', 'Interest Capitalized'), ('RELEASE_COMPLETED', 'Release Completed'), ('AUCTION_INITIATED', 'Auction Initiated'), ('AUCTION_STARTED', 'Auction Started'), ('AUCTION_CANCELLED', 'Auction Cancelled'), ('AUCTION_COMPLETED', 'Auction Completed'), ('AUCTION_REVERSED', 'Auction Reversed'), ('RENEWAL_COMPLETED', 'Renewal Completed'), ('RENEWAL_SUCCESSOR_ACTIVATED', 'Renewal Successor Activated'), ('RENEWAL_REVERSED', 'Renewal Reversed'), ('CLOSED', 'Closed'), ('REVERSAL_RECORDED', 'Reversal Recorded')], max_length=40),
        ),
        migrations.AlterField(
            model_name='pawncollateralcustodyevent',
            name='from_state',
            field=models.CharField(choices=[('IN_VAULT', 'In Vault'), ('WITH_CUSTOMER', 'With Customer'), ('WITH_FUNDING_LENDER', 'With Funding Lender'), ('AUCTION_DISPOSED', 'Auction Disposed'), ('RENEWAL_TRANSFERRED', 'Renewal Transferred'), ('RENEWAL_REVERSED', 'Renewal Reversed')], max_length=32),
        ),
        migrations.AlterField(
            model_name='pawncollateralcustodyevent',
            name='to_state',
            field=models.CharField(choices=[('IN_VAULT', 'In Vault'), ('WITH_CUSTOMER', 'With Customer'), ('WITH_FUNDING_LENDER', 'With Funding Lender'), ('AUCTION_DISPOSED', 'Auction Disposed'), ('RENEWAL_TRANSFERRED', 'Renewal Transferred'), ('RENEWAL_REVERSED', 'Renewal Reversed')], max_length=32),
        ),
        migrations.AlterField(
            model_name='pawncollateralitem',
            name='custody_state',
            field=models.CharField(choices=[('IN_VAULT', 'In Vault'), ('WITH_CUSTOMER', 'With Customer'), ('WITH_FUNDING_LENDER', 'With Funding Lender'), ('AUCTION_DISPOSED', 'Auction Disposed'), ('RENEWAL_TRANSFERRED', 'Renewal Transferred'), ('RENEWAL_REVERSED', 'Renewal Reversed')], db_index=True, default='IN_VAULT', max_length=32),
        ),
        migrations.AlterField(
            model_name='pawnloanaccountingevent',
            name='event_kind',
            field=models.CharField(choices=[('DISBURSAL', 'Disbursal'), ('REPAYMENT', 'Repayment'), ('INTEREST_ACCRUAL', 'Interest Accrual'), ('INTEREST_CAPITALIZATION', 'Interest Capitalization'), ('RELEASE_RECEIPT', 'Release Receipt'), ('AUCTION_RECOVERY', 'Auction Recovery'), ('RENEWAL_SETTLEMENT', 'Renewal Settlement'), ('RENEWAL_OPENING', 'Renewal Opening'), ('REVERSAL', 'Reversal')], max_length=32),
        ),
        migrations.AddField(
            model_name='pawnloanrenewal',
            name='catch_up_accrual',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='renewal_catch_up', to='loans.pawnloaninterestaccrual'),
        ),
        migrations.AddField(
            model_name='pawnloanrenewal',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pawn_loan_renewals_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pawnloanrenewal',
            name='opening_event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='renewal_opening', to='loans.pawnloanaccountingevent'),
        ),
        migrations.AddField(
            model_name='pawnloanrenewal',
            name='settlement_event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='renewal_settlement', to='loans.pawnloanaccountingevent'),
        ),
        migrations.AddField(
            model_name='pawnloanrenewal',
            name='source_loan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='renewal_as_source', to='loans.pawnloan'),
        ),
        migrations.AddField(
            model_name='pawnloanrenewal',
            name='successor_loan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='origin_renewal', to='loans.pawnloan'),
        ),
        migrations.AddField(
            model_name='pawnloanrenewal',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pawn_loan_renewals', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='pawncollateralcustodyevent',
            name='renewal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custody_events', to='loans.pawnloanrenewal'),
        ),
        migrations.AddField(
            model_name='pawnloanrenewalreversal',
            name='catch_up_reversal_event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='renewal_catch_up_reversal', to='loans.pawnloanaccountingevent'),
        ),
        migrations.AddField(
            model_name='pawnloanrenewalreversal',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pawn_loan_renewal_reversals_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pawnloanrenewalreversal',
            name='opening_reversal_event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='renewal_opening_reversal', to='loans.pawnloanaccountingevent'),
        ),
        migrations.AddField(
            model_name='pawnloanrenewalreversal',
            name='renewal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='loans.pawnloanrenewal'),
        ),
        migrations.AddField(
            model_name='pawnloanrenewalreversal',
            name='settlement_reversal_event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='renewal_settlement_reversal', to='loans.pawnloanaccountingevent'),
        ),
        migrations.AddField(
            model_name='pawncollateralcustodyevent',
            name='renewal_reversal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custody_events', to='loans.pawnloanrenewalreversal'),
        ),
        migrations.AddConstraint(
            model_name='pawncollateralcustodyevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('release__isnull', False), ('auction__isnull', True), ('renewal__isnull', True)), models.Q(('release__isnull', True), ('auction__isnull', False), ('renewal__isnull', True)), models.Q(('release__isnull', True), ('auction__isnull', True), ('renewal__isnull', False)), _connector='OR'), name='loans_custody_one_source'),
        ),
        migrations.AddConstraint(
            model_name='pawnloanrenewal',
            constraint=models.UniqueConstraint(fields=('workspace', 'renewal_number'), name='loans_renewal_workspace_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pawnloanrenewal',
            constraint=models.UniqueConstraint(fields=('workspace', 'request_key'), name='loans_renewal_workspace_request_uniq'),
        ),
    ]
