# Generated by Django 6.0.3 on 2026-09-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0010_migration_opening_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pawncollateralitem',
            name='gross_weight',
            field=models.DecimalField(decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='pawncollateralitem',
            name='metal',
            field=models.CharField(choices=[('GOLD', 'Gold'), ('SILVER', 'Silver'), ('BRONZE', 'Bronze'), ('OTHER', 'Other')], max_length=16),
        ),
        migrations.AlterField(
            model_name='pawnmetalinterestratepolicy',
            name='metal',
            field=models.CharField(choices=[('GOLD', 'Gold'), ('SILVER', 'Silver'), ('BRONZE', 'Bronze'), ('OTHER', 'Other')], max_length=16),
        ),
    ]
