# Generated by Django 6.0.3 on 2026-08-05 09:24

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0011_pawnloanrenewal_pawnloanrenewalreversal_and_more'),
        ('orgs', '0024_alter_auditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pawncollateralitem',
            name='allocated_principal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='pawncollateralitem',
            name='monthly_interest_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.CreateModel(
            name='PawnLoanEconomicPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuation_method', models.CharField(choices=[('CALCULATED_METAL_VALUE', 'Calculated Metal Value'), ('LATEST_APPRAISAL', 'Latest Appraisal'), ('LOWER_OF_CALCULATED_AND_APPRAISAL', 'Lower Of Calculated And Appraisal')], default='LOWER_OF_CALCULATED_AND_APPRAISAL', max_length=40)),
                ('maximum_ltv_ratio', models.DecimalField(decimal_places=6, default=Decimal('0.800000'), max_digits=7)),
                ('advance_interest_periods', models.PositiveSmallIntegerField(default=1)),
                ('effective_from', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pawn_loan_economic_policies_created', to=settings.AUTH_USER_MODEL)),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='economic_policies', to='loans.loanlicense')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pawn_loan_economic_policies', to='orgs.company')),
            ],
            options={
                'ordering': ('workspace_id', 'license_id', '-effective_from', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PawnLoanFeePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=100)),
                ('calculation_type', models.CharField(choices=[('FIXED', 'Fixed'), ('PERCENTAGE', 'Percentage')], max_length=16)),
                ('value', models.DecimalField(decimal_places=6, max_digits=18)),
                ('deducted_at_disbursal', models.BooleanField(default=True)),
                ('effective_from', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pawn_loan_fee_policies_created', to=settings.AUTH_USER_MODEL)),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_policies', to='loans.loanlicense')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pawn_loan_fee_policies', to='orgs.company')),
            ],
            options={
                'ordering': ('workspace_id', 'license_id', 'code', '-effective_from', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PawnMetalInterestRatePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal', models.CharField(choices=[('GOLD', 'Gold'), ('SILVER', 'Silver'), ('OTHER', 'Other')], max_length=16)),
                ('monthly_interest_rate', models.DecimalField(decimal_places=6, max_digits=9)),
                ('effective_from', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pawn_metal_interest_rate_policies_created', to=settings.AUTH_USER_MODEL)),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metal_interest_rate_policies', to='loans.loanlicense')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pawn_metal_interest_rate_policies', to='orgs.company')),
            ],
            options={
                'ordering': ('workspace_id', 'license_id', 'metal', '-effective_from', '-id'),
            },
        ),
        migrations.AddField(
            model_name='pawncollateralitem',
            name='interest_rate_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collateral_items', to='loans.pawnmetalinterestratepolicy'),
        ),
        migrations.AddConstraint(
            model_name='pawncollateralitem',
            constraint=models.CheckConstraint(condition=models.Q(('allocated_principal__isnull', True), ('allocated_principal__gt', 0), _connector='OR'), name='loans_item_allocation_positive'),
        ),
        migrations.AddConstraint(
            model_name='pawncollateralitem',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_interest_rate__isnull', True), models.Q(('monthly_interest_rate__gte', 0), ('monthly_interest_rate__lte', 100)), _connector='OR'), name='loans_item_rate_range'),
        ),
        migrations.AddIndex(
            model_name='pawnloaneconomicpolicy',
            index=models.Index(fields=['workspace', 'license', 'is_active', 'effective_from'], name='loans_econ_resolve_idx'),
        ),
        migrations.AddConstraint(
            model_name='pawnloaneconomicpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('license__isnull', True)), fields=('workspace', 'effective_from'), name='loans_econ_ws_date_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pawnloaneconomicpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('license__isnull', False)), fields=('license', 'effective_from'), name='loans_econ_license_date_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pawnloaneconomicpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('maximum_ltv_ratio__gt', 0), ('maximum_ltv_ratio__lte', 1)), name='loans_econ_ltv_range'),
        ),
        migrations.AddConstraint(
            model_name='pawnloaneconomicpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('advance_interest_periods__lte', 12)), name='loans_econ_advance_range'),
        ),
        migrations.AddConstraint(
            model_name='pawnloaneconomicpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('effective_until__isnull', True), ('effective_until__gte', models.F('effective_from')), _connector='OR'), name='loans_econ_dates_valid'),
        ),
        migrations.AddIndex(
            model_name='pawnloanfeepolicy',
            index=models.Index(fields=['workspace', 'license', 'code', 'is_active', 'effective_from'], name='loans_fee_resolve_idx'),
        ),
        migrations.AddConstraint(
            model_name='pawnloanfeepolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('license__isnull', True)), fields=('workspace', 'code', 'effective_from'), name='loans_fee_ws_code_date_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pawnloanfeepolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('license__isnull', False)), fields=('license', 'code', 'effective_from'), name='loans_fee_license_date_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pawnloanfeepolicy',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', 0)), name='loans_fee_value_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='pawnloanfeepolicy',
            constraint=models.CheckConstraint(condition=models.Q(('effective_until__isnull', True), ('effective_until__gte', models.F('effective_from')), _connector='OR'), name='loans_fee_dates_valid'),
        ),
        migrations.AddIndex(
            model_name='pawnmetalinterestratepolicy',
            index=models.Index(fields=['workspace', 'license', 'metal', 'is_active', 'effective_from'], name='loans_rate_resolve_idx'),
        ),
        migrations.AddConstraint(
            model_name='pawnmetalinterestratepolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('license__isnull', True)), fields=('workspace', 'metal', 'effective_from'), name='loans_rate_ws_metal_date_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pawnmetalinterestratepolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('license__isnull', False)), fields=('license', 'metal', 'effective_from'), name='loans_rate_license_date_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pawnmetalinterestratepolicy',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_interest_rate__gte', 0), ('monthly_interest_rate__lte', 100)), name='loans_rate_percent_range'),
        ),
        migrations.AddConstraint(
            model_name='pawnmetalinterestratepolicy',
            constraint=models.CheckConstraint(condition=models.Q(('effective_until__isnull', True), ('effective_until__gte', models.F('effective_from')), _connector='OR'), name='loans_rate_dates_valid'),
        ),
    ]
