# Generated by Django 6.0.3 on 2026-09-12 13:29

from django.conf import settings
from django.db import migrations, models

GUARDS = r"""
CREATE FUNCTION loans_guard_legacy_license_identity() RETURNS trigger AS $$
BEGIN
    IF NEW.is_legacy_reference IS DISTINCT FROM OLD.is_legacy_reference THEN
        RAISE EXCEPTION 'Legacy reference identity cannot be converted to verified licence identity';
    END IF;
    RETURN NEW;
END; $$ LANGUAGE plpgsql;
CREATE TRIGGER loans_legacy_license_identity_guard BEFORE UPDATE ON loans_loanlicense
FOR EACH ROW EXECUTE FUNCTION loans_guard_legacy_license_identity();

CREATE FUNCTION loans_guard_legacy_revision_kind() RETURNS trigger AS $$
DECLARE legacy boolean;
BEGIN
    SELECT is_legacy_reference INTO legacy FROM loans_loanlicense WHERE id = NEW.license_id;
    IF legacy IS NULL OR legacy <> (NEW.kind = 'LEGACY_REFERENCE') THEN
        RAISE EXCEPTION 'Legacy reference and verified licence revisions must remain separate';
    END IF;
    RETURN NEW;
END; $$ LANGUAGE plpgsql;
CREATE TRIGGER loans_legacy_revision_kind_guard BEFORE INSERT ON loans_loanlicenserevision
FOR EACH ROW EXECUTE FUNCTION loans_guard_legacy_revision_kind();

CREATE FUNCTION loans_guard_legacy_origination() RETURNS trigger AS $$
BEGIN
    IF NEW.event_kind = 'DISBURSAL' AND EXISTS (
        SELECT 1 FROM loans_pawnloan l JOIN loans_loanlicense r ON r.id = l.license_id
        WHERE l.id = NEW.loan_id AND r.is_legacy_reference
    ) THEN
        RAISE EXCEPTION 'A legacy licence reference cannot authorize disbursal';
    END IF;
    RETURN NEW;
END; $$ LANGUAGE plpgsql;
CREATE TRIGGER loans_legacy_origination_guard BEFORE INSERT ON loans_pawnloanevent
FOR EACH ROW EXECUTE FUNCTION loans_guard_legacy_origination();
"""

REVERSE_GUARDS = r"""
DROP TRIGGER loans_legacy_origination_guard ON loans_pawnloanevent;
DROP FUNCTION loans_guard_legacy_origination();
DROP TRIGGER loans_legacy_revision_kind_guard ON loans_loanlicenserevision;
DROP FUNCTION loans_guard_legacy_revision_kind();
DROP TRIGGER loans_legacy_license_identity_guard ON loans_loanlicense;
DROP FUNCTION loans_guard_legacy_license_identity();
"""

class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0011_legacy_collateral_evidence'),
        ('orgs', '0009_workspace_role_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loanlicense',
            name='is_legacy_reference',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='loanlicense',
            name='expires_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanlicense',
            name='issued_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanlicenserevision',
            name='expires_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanlicenserevision',
            name='issued_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanlicenserevision',
            name='kind',
            field=models.CharField(choices=[('INITIAL', 'Initial issue'), ('AMENDMENT', 'Amendment'), ('RENEWAL', 'Renewal'), ('LEGACY_REFERENCE', 'Legacy reference (validity unknown)')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='loanlicense',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('expires_on__isnull', True), ('is_active', False), ('is_legacy_reference', True), ('issued_on__isnull', True)), models.Q(('expires_on__isnull', False), ('is_legacy_reference', False), ('issued_on__isnull', False)), _connector='OR'), name='loans_license_validity_evidence'),
        ),
        migrations.AddConstraint(
            model_name='loanlicenserevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('expires_on__isnull', True), ('issued_on__isnull', True), ('kind', 'LEGACY_REFERENCE')), models.Q(models.Q(('kind', 'LEGACY_REFERENCE'), _negated=True), ('expires_on__isnull', False), ('issued_on__isnull', False)), _connector='OR'), name='loans_licrev_validity_evidence'),
        ),
        migrations.RunSQL(GUARDS, REVERSE_GUARDS),
    ]
