# Generated by Django 6.0.3 on 2026-09-12 23:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from apps.tenancy.rls import EnableWorkspaceRLS


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0012_legacy_opening_evidence_gaps'),
        ('orgs', '0009_workspace_role_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLoanEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_namespace', models.UUIDField()),
                ('source_system', models.CharField(max_length=120)),
                ('source_id', models.CharField(max_length=255)),
                ('source_sha256', models.CharField(max_length=64)),
                ('document', models.JSONField()),
                ('review', models.JSONField()),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('workspace', 'source_namespace', 'source_system', 'source_id', 'source_sha256'), name='loans_archive_snapshot_unique')],
            },
        ),
        EnableWorkspaceRLS("HistoricalLoanEvidence"),
        migrations.RunSQL("""
CREATE FUNCTION loans_archive_evidence_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF TG_OP <> 'INSERT' THEN RAISE EXCEPTION 'Accepted historical evidence is immutable'; END IF;
 IF NEW.source_sha256 !~ '^[0-9a-f]{64}$'
 OR NEW.document->>'profile' IS DISTINCT FROM 'loan-closed-evidence/1'
 OR NEW.document#>>'{facts,status}' IS DISTINCT FROM 'CLOSED'
 OR NEW.document#>>'{source,namespace}' IS DISTINCT FROM NEW.source_namespace::text
 OR NEW.document#>>'{source,system}' IS DISTINCT FROM NEW.source_system
 OR NEW.document#>>'{source,loan_id}' IS DISTINCT FROM NEW.source_id
 OR NEW.review->>'source_sha256' IS DISTINCT FROM NEW.source_sha256
 OR NEW.review->'operational_admission' IS DISTINCT FROM 'false'::jsonb
 THEN RAISE EXCEPTION 'Invalid closed-loan evidence binding'; END IF;
 RETURN NEW;
END; $$;
CREATE TRIGGER loans_archive_evidence_guard BEFORE INSERT OR UPDATE OR DELETE ON loans_historicalloanevidence
FOR EACH ROW EXECUTE FUNCTION loans_archive_evidence_guard();
""", "DROP TRIGGER loans_archive_evidence_guard ON loans_historicalloanevidence; DROP FUNCTION loans_archive_evidence_guard();"),
    ]
