# Generated by Django 6.0.3 on 2026-08-05 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0012_pawncollateralitem_allocated_principal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PawnLoanDisbursalSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_principal', models.DecimalField(decimal_places=4, max_digits=18)),
                ('monthly_interest', models.DecimalField(decimal_places=4, max_digits=18)),
                ('advance_interest_periods', models.PositiveSmallIntegerField(default=0)),
                ('advance_interest', models.DecimalField(decimal_places=4, max_digits=18)),
                ('deducted_fees', models.DecimalField(decimal_places=4, max_digits=18)),
                ('net_disbursed', models.DecimalField(decimal_places=4, max_digits=18)),
                ('evidence', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accounting_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='disbursal_snapshot', to='loans.pawnloanaccountingevent')),
                ('approval_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursal_snapshots', to='loans.pawnloanapprovalsnapshot')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pawn_loan_disbursal_snapshots', to=settings.AUTH_USER_MODEL)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='disbursal_snapshot', to='loans.pawnloan')),
                ('policy_snapshot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='disbursal_snapshot', to='loans.loanpolicysnapshot')),
            ],
            options={
                'ordering': ('loan_id',),
                'constraints': [models.CheckConstraint(condition=models.Q(('gross_principal__gt', 0)), name='loans_disbursal_gross_positive'), models.CheckConstraint(condition=models.Q(('monthly_interest__gte', 0), ('advance_interest__gte', 0), ('deducted_fees__gte', 0), ('net_disbursed__gt', 0)), name='loans_disbursal_amounts_valid')],
            },
        ),
    ]
