# Generated by Django 6.0.3 on 2026-08-05 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0013_pawnloandisbursalsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='PawnLoanInterestAccrualLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_base', models.DecimalField(decimal_places=12, max_digits=30)),
                ('monthly_interest_rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('period_fraction', models.DecimalField(decimal_places=4, max_digits=8)),
                ('unrounded_interest', models.DecimalField(decimal_places=12, max_digits=30)),
                ('calculated_interest', models.DecimalField(decimal_places=4, max_digits=18)),
                ('advance_interest_applied', models.DecimalField(decimal_places=4, max_digits=18)),
                ('recognized_interest', models.DecimalField(decimal_places=4, max_digits=18)),
                ('accrual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='loans.pawnloaninterestaccrual')),
                ('collateral_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interest_accrual_lines', to='loans.pawncollateralitem')),
            ],
            options={
                'ordering': ('accrual_id', 'collateral_item_id'),
                'constraints': [models.UniqueConstraint(fields=('accrual', 'collateral_item'), name='loans_accrual_item_uniq'), models.CheckConstraint(condition=models.Q(('principal_base__gte', 0), ('monthly_interest_rate__gte', 0), ('unrounded_interest__gte', 0), ('calculated_interest__gte', 0), ('advance_interest_applied__gte', 0), ('recognized_interest__gte', 0)), name='loans_accrual_line_amounts_valid'), models.CheckConstraint(condition=models.Q(('period_fraction__gt', 0), ('period_fraction__lte', 1)), name='loans_accrual_line_fraction_valid')],
            },
        ),
    ]
