# Generated by Django 6.0.3 on 2026-09-21 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from apps.tenancy.rls import EnableWorkspaceRLS


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0013_historicalloanevidence'),
        ('orgs', '0009_workspace_role_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pawncollateralphoto',
            name='source_evidence',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='pawncollateralphoto',
            name='workflow_source',
            field=models.CharField(choices=[('DRAFT', 'Draft capture'), ('RENEWAL', 'Release and renew'), ('POST_APPROVAL', 'Post-approval evidence'), ('LEGACY_IMPORT', 'Legacy source image (capture date unknown)')], max_length=24),
        ),
        migrations.CreateModel(
            name='HistoricalLoanAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to='')),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('sha256', models.CharField(max_length=64)),
                ('byte_size', models.PositiveBigIntegerField()),
                ('source_evidence', models.JSONField()),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='loans.historicalloanevidence')),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        EnableWorkspaceRLS("HistoricalLoanAttachment"),
        migrations.RunSQL("""
CREATE FUNCTION loans_archive_media_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF TG_OP <> 'INSERT' THEN RAISE EXCEPTION 'Historical media is immutable'; END IF;
 IF NOT EXISTS (SELECT 1 FROM loans_historicalloanevidence e WHERE e.id=NEW.evidence_id AND e.workspace_id=NEW.workspace_id)
 OR NEW.sha256 !~ '^[0-9a-f]{64}$' OR NEW.byte_size <= 0
 OR NEW.source_evidence#>>'{verified_source_file,sha256}' IS DISTINCT FROM NEW.sha256
 THEN RAISE EXCEPTION 'Invalid historical media binding'; END IF;
 RETURN NEW;
END; $$;
CREATE TRIGGER loans_archive_media_guard BEFORE INSERT OR UPDATE OR DELETE ON loans_historicalloanattachment
FOR EACH ROW EXECUTE FUNCTION loans_archive_media_guard();
CREATE FUNCTION loans_legacy_photo_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF NEW.workflow_source = 'LEGACY_IMPORT' AND (
 NEW.source_evidence#>>'{verified_source_file,sha256}' IS DISTINCT FROM NEW.sha256
 OR NEW.source_evidence->>'status' IS DISTINCT FROM 'EXACT_SOURCE_FILE_PRESERVED')
 THEN RAISE EXCEPTION 'Legacy photos require preserved source evidence'; END IF;
 RETURN NEW;
END; $$;
CREATE TRIGGER loans_legacy_photo_guard BEFORE INSERT ON loans_pawncollateralphoto
FOR EACH ROW EXECUTE FUNCTION loans_legacy_photo_guard();
""", """
DROP TRIGGER loans_legacy_photo_guard ON loans_pawncollateralphoto; DROP FUNCTION loans_legacy_photo_guard();
DROP TRIGGER loans_archive_media_guard ON loans_historicalloanattachment; DROP FUNCTION loans_archive_media_guard();
"""),
    ]
