# Generated by Django 6.0.3 on 2026-08-05 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0014_pawnloaninterestaccrualline'),
    ]

    operations = [
        migrations.CreateModel(
            name='PawnLoanRepaymentAllocationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_order', models.PositiveSmallIntegerField()),
                ('monthly_interest_rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('balance_before', models.DecimalField(decimal_places=4, max_digits=18)),
                ('principal_applied', models.DecimalField(decimal_places=4, max_digits=18)),
                ('balance_after', models.DecimalField(decimal_places=4, max_digits=18)),
                ('accounting_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayment_allocation_lines', to='loans.pawnloanaccountingevent')),
                ('collateral_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayment_allocation_lines', to='loans.pawncollateralitem')),
            ],
            options={
                'ordering': ('accounting_event_id', 'allocation_order'),
                'constraints': [models.UniqueConstraint(fields=('accounting_event', 'collateral_item'), name='loans_repayment_event_item_uniq'), models.UniqueConstraint(fields=('accounting_event', 'allocation_order'), name='loans_repayment_event_order_uniq'), models.CheckConstraint(condition=models.Q(('allocation_order__gt', 0)), name='loans_repayment_order_positive'), models.CheckConstraint(condition=models.Q(('monthly_interest_rate__gte', 0), ('balance_before__gte', 0), ('principal_applied__gte', 0), ('balance_after__gte', 0)), name='loans_repayment_line_amounts_valid')],
            },
        ),
    ]
