# Generated by Django 6.0.3 on 2026-08-06 11:03

import apps.tenant_apps.loans.models.documents
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0016_pawnloanprincipalclosingline_and_more'),
        ('orgs', '0024_alter_auditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanDocumentLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('loan_ticket', 'Loan ticket'), ('repayment_receipt', 'Repayment receipt'), ('release_memo', 'Release memo'), ('auction_notice', 'Auction notice'), ('auction_recovery', 'Auction recovery memo'), ('renewal', 'Renewal memo')], max_length=32)),
                ('name', models.CharField(max_length=100)),
                ('is_retired', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_document_layouts_created', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_document_layouts', to='orgs.company')),
            ],
            options={
                'ordering': ('document_type', 'name', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='LoanDocumentLayoutRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('RETIRED', 'Retired')], db_index=True, default='DRAFT', max_length=12)),
                ('definition', models.JSONField(default=dict)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('validation_result', models.JSONField(blank=True, default=dict)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_document_revisions_created', to=settings.AUTH_USER_MODEL)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='loans.loandocumentlayout')),
            ],
            options={
                'ordering': ('layout_id', 'version'),
            },
        ),
        migrations.CreateModel(
            name='LoanDocumentLayoutAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('loan_ticket', 'Loan ticket'), ('repayment_receipt', 'Repayment receipt'), ('release_memo', 'Release memo'), ('auction_notice', 'Auction notice'), ('auction_recovery', 'Auction recovery memo'), ('renewal', 'Renewal memo')], max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_document_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_layout_assignments', to='loans.loanlicense')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_layout_assignments', to='loans.loanseries')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_document_assignments', to='orgs.company')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='loans.loandocumentlayoutrevision')),
            ],
        ),
        migrations.CreateModel(
            name='LoanDocumentIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('loan_ticket', 'Loan ticket'), ('repayment_receipt', 'Repayment receipt'), ('release_memo', 'Release memo'), ('auction_notice', 'Auction notice'), ('auction_recovery', 'Auction recovery memo'), ('renewal', 'Renewal memo')], max_length=32)),
                ('issue_kind', models.CharField(choices=[('OFFICIAL', 'Official'), ('REGENERATED', 'Regenerated')], default='OFFICIAL', max_length=12)),
                ('source_type', models.CharField(max_length=64)),
                ('source_id', models.CharField(max_length=64)),
                ('source_fingerprint', models.CharField(max_length=128)),
                ('fixed_renderer_version', models.CharField(blank=True, max_length=64)),
                ('payload_schema_version', models.PositiveIntegerField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('layout_hash', models.CharField(blank=True, max_length=64)),
                ('asset_hashes', models.JSONField(blank=True, default=dict)),
                ('pdf_hash', models.CharField(max_length=64)),
                ('artifact', models.FileField(upload_to=apps.tenant_apps.loans.models.documents.document_issue_upload)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_document_issues_created', to=settings.AUTH_USER_MODEL)),
                ('prior_issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regenerated_issues', to='loans.loandocumentissue')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_document_issues', to='orgs.company')),
                ('revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='loans.loandocumentlayoutrevision')),
            ],
            options={
                'ordering': ('-issued_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='LoanDocumentAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('kind', models.CharField(choices=[('IMAGE', 'Image'), ('BACKGROUND', 'Background')], max_length=16)),
                ('mime_type', models.CharField(max_length=64)),
                ('file', models.FileField(upload_to=apps.tenant_apps.loans.models.documents.document_asset_upload)),
                ('sha256', models.CharField(max_length=64)),
                ('byte_size', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('page_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_document_assets_created', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_document_assets', to='orgs.company')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='loans.loandocumentlayoutrevision')),
            ],
        ),
        migrations.AddConstraint(
            model_name='loandocumentlayout',
            constraint=models.UniqueConstraint(fields=('workspace', 'document_type', 'name'), name='loans_doc_layout_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='loandocumentlayoutrevision',
            constraint=models.UniqueConstraint(fields=('layout', 'version'), name='loans_doc_revision_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='loandocumentlayoutrevision',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='loans_doc_revision_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='loandocumentlayoutassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('license__isnull', True), ('series__isnull', True)), fields=('workspace', 'document_type'), name='loans_doc_assign_workspace_uniq'),
        ),
        migrations.AddConstraint(
            model_name='loandocumentlayoutassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('license__isnull', False), ('series__isnull', True)), fields=('workspace', 'document_type', 'license'), name='loans_doc_assign_license_uniq'),
        ),
        migrations.AddConstraint(
            model_name='loandocumentlayoutassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('series__isnull', False)), fields=('workspace', 'document_type', 'series'), name='loans_doc_assign_series_uniq'),
        ),
        migrations.AddIndex(
            model_name='loandocumentissue',
            index=models.Index(fields=['workspace', 'document_type', 'source_type', 'source_id'], name='loans_doc_issue_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='loandocumentasset',
            constraint=models.UniqueConstraint(fields=('revision', 'key'), name='loans_doc_asset_key_uniq'),
        ),
    ]
