# Generated by Django 6.0.3 on 2026-08-06 11:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0017_document_layouts'),
        ('orgs', '0024_alter_auditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='loandocumentissue',
            constraint=models.UniqueConstraint(condition=models.Q(('issue_kind', 'OFFICIAL')), fields=('workspace', 'document_type', 'source_type', 'source_id', 'source_fingerprint'), name='loans_doc_official_issue_uniq'),
        ),
    ]
