# Generated by Django 6.0.3 on 2026-08-08 09:46

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0018_official_issue_uniqueness'),
        ('orgs', '0024_alter_auditlog_action'),
        ('party', '0005_partyportalaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funding_number', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('SETTLEMENT_PENDING', 'Settlement Pending'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('created_at', 'funding_number'),
            },
        ),
        migrations.CreateModel(
            name='FundingLoanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('event_kind', models.CharField(choices=[('ACTIVATION', 'Activation'), ('INTEREST_ACCRUAL', 'Interest Accrual'), ('FEE_ASSESSMENT', 'Fee Assessment'), ('REPAYMENT', 'Repayment'), ('REVERSAL', 'Reversal')], max_length=24)),
                ('operation', models.CharField(max_length=40)),
                ('effective_date', models.DateField(db_index=True)),
                ('principal_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('interest_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('fee_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('request_key', models.CharField(max_length=120)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('funding_loan_id', 'sequence'),
            },
        ),
        migrations.CreateModel(
            name='FundingLoanSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='FL-', max_length=24)),
                ('width', models.PositiveSmallIntegerField(default=6)),
                ('next_value', models.PositiveBigIntegerField(default=1)),
                ('maximum_value', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FundingLoanTermsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('monthly_interest_rate', models.DecimalField(decimal_places=6, max_digits=9)),
                ('activated_on', models.DateField(db_index=True)),
                ('maturity_on', models.DateField(db_index=True)),
                ('maximum_funding_ltv_ratio', models.DecimalField(decimal_places=6, default=Decimal('0.800000'), max_digits=7)),
                ('currency_quantum', models.DecimalField(decimal_places=4, default=Decimal('0.0100'), max_digits=8)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FundingPledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(db_index=True)),
                ('request_key', models.CharField(max_length=120)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('total_collateral_value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('maximum_funded_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('valuation_method', models.CharField(max_length=48)),
                ('valuation_version', models.PositiveSmallIntegerField(default=1)),
                ('valuation_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FundingPledgeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_pawn_loan_id', models.PositiveBigIntegerField()),
                ('selected_collateral_value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('valuation_snapshot', models.JSONField(default=dict)),
                ('valuation_fingerprint', models.CharField(max_length=64)),
                ('released_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FundingReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(db_index=True)),
                ('operation', models.CharField(default='RETURN_COLLATERAL', max_length=40)),
                ('request_key', models.CharField(max_length=120)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('principal_outstanding', models.DecimalField(decimal_places=4, max_digits=18)),
                ('retained_collateral_value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('retained_ltv_ratio', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('evidence_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FundingReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('evidence_snapshot', models.JSONField(default=dict)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='pawncollateralcustodyevent',
            name='loans_custody_one_source',
        ),
        migrations.AddField(
            model_name='fundingloan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funding_loans_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fundingloan',
            name='lender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funding_loans', to='party.party'),
        ),
        migrations.AddField(
            model_name='fundingloan',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funding_loans_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fundingloan',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funding_loans', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='fundingloanevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funding_loan_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fundingloanevent',
            name='funding_loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='loans.fundingloan'),
        ),
        migrations.AddField(
            model_name='fundingloanevent',
            name='reversal_of',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='loans.fundingloanevent'),
        ),
        migrations.AddField(
            model_name='fundingloansequence',
            name='workspace',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='funding_loan_sequence', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='fundingloantermssnapshot',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funding_terms_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fundingloantermssnapshot',
            name='funding_loan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='terms_snapshot', to='loans.fundingloan'),
        ),
        migrations.AddField(
            model_name='fundingpledge',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funding_pledges_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fundingpledge',
            name='funding_loan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pledge', to='loans.fundingloan'),
        ),
        migrations.AddField(
            model_name='fundingpledge',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funding_pledges', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='pawncollateralcustodyevent',
            name='funding_pledge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custody_events', to='loans.fundingpledge'),
        ),
        migrations.AddField(
            model_name='fundingpledgeitem',
            name='collateral_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funding_pledge_items', to='loans.pawncollateralitem'),
        ),
        migrations.AddField(
            model_name='fundingpledgeitem',
            name='funding_pledge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='loans.fundingpledge'),
        ),
        migrations.AddField(
            model_name='fundingreturn',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funding_returns_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fundingreturn',
            name='funding_loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='loans.fundingloan'),
        ),
        migrations.AddField(
            model_name='fundingreturn',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funding_returns', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='pawncollateralcustodyevent',
            name='funding_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custody_events', to='loans.fundingreturn'),
        ),
        migrations.AddConstraint(
            model_name='pawncollateralcustodyevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('release__isnull', False), ('auction__isnull', True), ('renewal__isnull', True), ('funding_pledge__isnull', True), ('funding_return__isnull', True)), models.Q(('release__isnull', True), ('auction__isnull', False), ('renewal__isnull', True), ('funding_pledge__isnull', True), ('funding_return__isnull', True)), models.Q(('release__isnull', True), ('auction__isnull', True), ('renewal__isnull', False), ('funding_pledge__isnull', True), ('funding_return__isnull', True)), models.Q(('release__isnull', True), ('auction__isnull', True), ('renewal__isnull', True), ('funding_pledge__isnull', False), ('funding_return__isnull', True)), models.Q(('release__isnull', True), ('auction__isnull', True), ('renewal__isnull', True), ('funding_pledge__isnull', True), ('funding_return__isnull', False)), _connector='OR'), name='loans_custody_one_source'),
        ),
        migrations.AddField(
            model_name='fundingreturnitem',
            name='funding_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='loans.fundingreturn'),
        ),
        migrations.AddField(
            model_name='fundingreturnitem',
            name='pledge_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='loans.fundingpledgeitem'),
        ),
        migrations.AddIndex(
            model_name='fundingloan',
            index=models.Index(fields=['workspace', 'state', 'created_at'], name='loans_funding_state_created_idx'),
        ),
        migrations.AddIndex(
            model_name='fundingloan',
            index=models.Index(fields=['lender', 'state'], name='loans_funding_lender_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='fundingloan',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ('DRAFT', 'ACTIVE', 'SETTLEMENT_PENDING', 'CLOSED', 'CANCELLED'))), name='loans_funding_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='fundingloan',
            constraint=models.UniqueConstraint(fields=('workspace', 'funding_number'), name='loans_funding_workspace_number_uniq'),
        ),
        migrations.AddIndex(
            model_name='fundingloanevent',
            index=models.Index(fields=['funding_loan', 'effective_date', 'sequence'], name='loans_funding_event_date_idx'),
        ),
        migrations.AddIndex(
            model_name='fundingloanevent',
            index=models.Index(fields=['funding_loan', 'event_kind', 'sequence'], name='loans_funding_event_kind_idx'),
        ),
        migrations.AddConstraint(
            model_name='fundingloanevent',
            constraint=models.UniqueConstraint(fields=('funding_loan', 'sequence'), name='loans_funding_event_sequence_uniq'),
        ),
        migrations.AddConstraint(
            model_name='fundingloanevent',
            constraint=models.UniqueConstraint(fields=('funding_loan', 'operation', 'request_key'), name='loans_funding_event_request_uniq'),
        ),
        migrations.AddConstraint(
            model_name='fundingloanevent',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gt', 0)), name='loans_funding_event_sequence_positive'),
        ),
        migrations.AddConstraint(
            model_name='fundingloanevent',
            constraint=models.CheckConstraint(condition=models.Q(('principal_amount__gte', 0), ('interest_amount__gte', 0), ('fee_amount__gte', 0)), name='loans_funding_event_amounts_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='fundingloanevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event_kind', 'REVERSAL'), ('reversal_of__isnull', False)), models.Q(models.Q(('event_kind', 'REVERSAL'), _negated=True), ('reversal_of__isnull', True)), _connector='OR'), name='loans_funding_event_reversal_link'),
        ),
        migrations.AddConstraint(
            model_name='fundingloansequence',
            constraint=models.CheckConstraint(condition=models.Q(('width__gt', 0), ('width__lte', 18)), name='loans_funding_seq_width_valid'),
        ),
        migrations.AddConstraint(
            model_name='fundingloansequence',
            constraint=models.CheckConstraint(condition=models.Q(('next_value__gt', 0)), name='loans_funding_seq_next_positive'),
        ),
        migrations.AddConstraint(
            model_name='fundingloansequence',
            constraint=models.CheckConstraint(condition=models.Q(('maximum_value__isnull', True), ('maximum_value__gte', models.F('next_value')), _connector='OR'), name='loans_funding_seq_max_valid'),
        ),
        migrations.AddConstraint(
            model_name='fundingloantermssnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('principal_amount__gt', 0), ('monthly_interest_rate__gte', 0), ('maturity_on__gte', models.F('activated_on')), ('maximum_funding_ltv_ratio__gt', 0), ('maximum_funding_ltv_ratio__lte', 1), ('currency_quantum__gt', 0), ('schema_version__gt', 0)), name='loans_funding_terms_valid'),
        ),
        migrations.AddConstraint(
            model_name='fundingpledge',
            constraint=models.UniqueConstraint(fields=('funding_loan', 'request_key'), name='loans_funding_pledge_request_uniq'),
        ),
        migrations.AddConstraint(
            model_name='fundingpledge',
            constraint=models.CheckConstraint(condition=models.Q(('total_collateral_value__gt', 0), ('maximum_funded_amount__gt', 0), ('valuation_version__gt', 0)), name='loans_funding_pledge_values_valid'),
        ),
        migrations.AddConstraint(
            model_name='fundingpledgeitem',
            constraint=models.UniqueConstraint(fields=('funding_pledge', 'collateral_item'), name='loans_funding_pledge_item_uniq'),
        ),
        migrations.AddConstraint(
            model_name='fundingpledgeitem',
            constraint=models.UniqueConstraint(condition=models.Q(('released_at__isnull', True)), fields=('collateral_item',), name='loans_funding_active_item_uniq'),
        ),
        migrations.AddConstraint(
            model_name='fundingpledgeitem',
            constraint=models.CheckConstraint(condition=models.Q(('selected_collateral_value__gt', 0)), name='loans_funding_item_value_positive'),
        ),
        migrations.AddConstraint(
            model_name='fundingreturn',
            constraint=models.UniqueConstraint(fields=('funding_loan', 'operation', 'request_key'), name='loans_funding_return_request_uniq'),
        ),
        migrations.AddConstraint(
            model_name='fundingreturn',
            constraint=models.CheckConstraint(condition=models.Q(('principal_outstanding__gte', 0), ('retained_collateral_value__gte', 0), models.Q(('retained_ltv_ratio__isnull', True), models.Q(('retained_ltv_ratio__gte', 0), ('retained_ltv_ratio__lte', 1)), _connector='OR')), name='loans_funding_return_values_valid'),
        ),
        migrations.AddConstraint(
            model_name='fundingreturnitem',
            constraint=models.UniqueConstraint(fields=('funding_return', 'pledge_item'), name='loans_funding_return_item_uniq'),
        ),
        migrations.AddConstraint(
            model_name='fundingreturnitem',
            constraint=models.UniqueConstraint(fields=('pledge_item',), name='loans_funding_item_returned_once'),
        ),
    ]
