# Generated by Django 6.1.1 on 2026-09-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0019_optional_sequence_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanlicense',
            name='proprietor_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='loanlicenserevision',
            name='proprietor_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
