# Generated by Django 6.1.1 on 2026-09-25 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0020_license_proprietor'),
        ('orgs', '0009_workspace_role_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pawnmetalinterestratepolicy',
            name='loans_rate_ws_metal_date_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='pawnmetalinterestratepolicy',
            name='loans_rate_license_date_uniq',
        ),
        migrations.AddField(
            model_name='pawnmetalinterestratepolicy',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metal_interest_rate_policies', to='loans.loanseries'),
        ),
        migrations.AddConstraint(
            model_name='pawnmetalinterestratepolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('license__isnull', True), ('series__isnull', True)), fields=('workspace', 'metal', 'effective_from'), name='loans_rate_ws_metal_date_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pawnmetalinterestratepolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('license__isnull', False), ('series__isnull', True)), fields=('license', 'metal', 'effective_from'), name='loans_rate_license_date_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pawnmetalinterestratepolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('series__isnull', False)), fields=('series', 'metal', 'effective_from'), name='loans_rate_series_date_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pawnmetalinterestratepolicy',
            constraint=models.CheckConstraint(condition=models.Q(('series__isnull', True), ('license__isnull', False), _connector='OR'), name='loans_rate_series_license'),
        ),
        migrations.RunSQL("""
CREATE FUNCTION loans_rate_series_scope_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF NEW.series_id IS NOT NULL AND NOT EXISTS (
   SELECT 1 FROM loans_loanseries s WHERE s.id=NEW.series_id
   AND s.workspace_id=NEW.workspace_id AND s.license_id=NEW.license_id)
 THEN RAISE EXCEPTION 'Rate series must belong to the same workspace and license'; END IF;
 RETURN NEW;
END; $$;
CREATE TRIGGER loans_rate_series_scope_guard BEFORE INSERT OR UPDATE
ON loans_pawnmetalinterestratepolicy FOR EACH ROW EXECUTE FUNCTION loans_rate_series_scope_guard();
""", """
DROP TRIGGER loans_rate_series_scope_guard ON loans_pawnmetalinterestratepolicy;
DROP FUNCTION loans_rate_series_scope_guard();
"""),
    ]
