# Generated by Django 6.1.1 on 2026-09-25 07:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
from apps.tenancy.rls import EnableWorkspaceRLS


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0021_series_interest_rates'),
        ('orgs', '0009_workspace_role_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pawnreleasebatch',
            name='exception_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pawnreleasebatch',
            name='mode',
            field=models.CharField(choices=[('COUNTER', 'Counter collection'), ('PAPER', 'Paper closures')], default='COUNTER', max_length=12),
        ),
        migrations.AddField(
            model_name='pawnreleasebatch',
            name='paper_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pawnreleasebatchline',
            name='paid_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pawnreleasebatchline',
            name='paper_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pawnloanreleaseitem',
            name='returned_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.CreateModel(
            name='PaperClosureTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_first_date', models.DateField(blank=True, null=True)),
                ('retired', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('workspace',), name='loans_paper_transition_workspace_uniq')],
            },
        ),
        EnableWorkspaceRLS("PaperClosureTransition"),
        migrations.RunSQL(
            """
            CREATE FUNCTION loans_paper_release_guard() RETURNS trigger LANGUAGE plpgsql AS $$
            BEGIN
              IF TG_TABLE_NAME = 'loans_pawnreleasebatch' THEN
                IF NEW.mode NOT IN ('COUNTER', 'PAPER') THEN RAISE EXCEPTION 'Invalid batch mode'; END IF;
              ELSIF TG_TABLE_NAME = 'loans_pawnreleasebatchline' THEN
                IF EXISTS (SELECT 1 FROM loans_pawnreleasebatch WHERE id=NEW.batch_id AND mode='PAPER')
                   AND btrim(NEW.paid_by) = '' THEN RAISE EXCEPTION 'Paper closure payer required'; END IF;
              ELSIF NEW.returned_at IS NULL THEN
                IF NOT EXISTS (SELECT 1 FROM loans_pawnloanrelease r JOIN loans_pawnloanevent e ON e.id=r.loan_event_id
                    WHERE r.id=NEW.release_id AND e.payload->'release'->'paper_closure'->>'date_precision'='DAY')
                THEN RAISE EXCEPTION 'Date-only return requires paper closure evidence'; END IF;
              END IF;
              RETURN NEW;
            END $$;
            CREATE TRIGGER loans_paper_batch_guard BEFORE INSERT ON loans_pawnreleasebatch
              FOR EACH ROW EXECUTE FUNCTION loans_paper_release_guard();
            CREATE TRIGGER loans_paper_line_guard BEFORE INSERT ON loans_pawnreleasebatchline
              FOR EACH ROW EXECUTE FUNCTION loans_paper_release_guard();
            CREATE TRIGGER loans_paper_return_guard BEFORE INSERT ON loans_pawnloanreleaseitem
              FOR EACH ROW EXECUTE FUNCTION loans_paper_release_guard();
            """,
            """
            DROP TRIGGER loans_paper_return_guard ON loans_pawnloanreleaseitem;
            DROP TRIGGER loans_paper_line_guard ON loans_pawnreleasebatchline;
            DROP TRIGGER loans_paper_batch_guard ON loans_pawnreleasebatch;
            DROP FUNCTION loans_paper_release_guard();
            """,
        ),
    ]
