# Generated by Django 6.0.3 on 2026-08-08 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0021_funding_sequence_exhausted_sentinel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingPledgeReversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(db_index=True)),
                ('request_key', models.CharField(max_length=120)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funding_pledge_reversals_created', to=settings.AUTH_USER_MODEL)),
                ('funding_pledge', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='loans.fundingpledge')),
            ],
        ),
        migrations.AddField(
            model_name='pawncollateralcustodyevent',
            name='funding_pledge_reversal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custody_events', to='loans.fundingpledgereversal'),
        ),
        migrations.CreateModel(
            name='FundingReturnReversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(db_index=True)),
                ('request_key', models.CharField(max_length=120)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funding_return_reversals_created', to=settings.AUTH_USER_MODEL)),
                ('funding_return', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='loans.fundingreturn')),
            ],
        ),
        migrations.AddField(
            model_name='pawncollateralcustodyevent',
            name='funding_return_reversal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custody_events', to='loans.fundingreturnreversal'),
        ),
        migrations.AddConstraint(
            model_name='fundingpledgereversal',
            constraint=models.UniqueConstraint(fields=('funding_pledge', 'request_key'), name='loans_funding_pledge_reversal_request_uniq'),
        ),
        migrations.AddConstraint(
            model_name='fundingreturnreversal',
            constraint=models.UniqueConstraint(fields=('funding_return', 'request_key'), name='loans_funding_return_reversal_request_uniq'),
        ),
    ]
