# Generated by Django 6.1.1 on 2026-09-25 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0022_paper_closure_transition'),
    ]

    operations = [
        migrations.AddField(
            model_name='pawnloan',
            name='disbursal_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='loans.pawnloandisbursalsnapshot'),
        ),
        migrations.AddField(
            model_name='pawnloan',
            name='policy_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='loans.loanpolicysnapshot'),
        ),
        migrations.AlterField(
            model_name='loanpolicysnapshot',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policy_snapshots', to='loans.pawnloan'),
        ),
        migrations.AlterField(
            model_name='pawnloandisbursalsnapshot',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursal_snapshots', to='loans.pawnloan'),
        ),
        migrations.RunSQL(
            """
            UPDATE loans_pawnloan l SET policy_snapshot_id = s.id
              FROM loans_loanpolicysnapshot s WHERE s.loan_id = l.id;
            UPDATE loans_pawnloan l SET disbursal_snapshot_id = s.id
              FROM loans_pawnloandisbursalsnapshot s WHERE s.loan_id = l.id;
            """, reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            """
            CREATE FUNCTION loans_current_disbursal_guard() RETURNS trigger LANGUAGE plpgsql AS $$
            BEGIN
              IF NEW.policy_snapshot_id IS NOT NULL AND NOT EXISTS (
                SELECT 1 FROM loans_loanpolicysnapshot s
                WHERE s.id = NEW.policy_snapshot_id AND s.loan_id = NEW.id AND s.workspace_id = NEW.workspace_id
              ) THEN RAISE EXCEPTION 'Current policy snapshot must belong to this loan and workspace'; END IF;
              IF NEW.disbursal_snapshot_id IS NOT NULL AND NOT EXISTS (
                SELECT 1 FROM loans_pawnloandisbursalsnapshot s
                WHERE s.id = NEW.disbursal_snapshot_id AND s.loan_id = NEW.id AND s.workspace_id = NEW.workspace_id
              ) THEN RAISE EXCEPTION 'Current disbursal snapshot must belong to this loan and workspace'; END IF;
              RETURN NEW;
            END $$;
            CREATE TRIGGER loans_current_disbursal_guard BEFORE INSERT OR UPDATE ON loans_pawnloan
              FOR EACH ROW EXECUTE FUNCTION loans_current_disbursal_guard();
            """,
            reverse_sql="""
            DROP TRIGGER loans_current_disbursal_guard ON loans_pawnloan;
            DROP FUNCTION loans_current_disbursal_guard();
            """,
        ),
    ]
