# Generated by Django 6.0.3 on 2026-08-08 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0022_fundingpledgereversal_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fundingreturnitem',
            name='loans_funding_item_returned_once',
        ),
    ]
