# Generated by Django 6.0.3 on 2026-08-08 11:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0023_remove_fundingreturnitem_loans_funding_item_returned_once'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pawncollateralcustodyevent',
            constraint=models.UniqueConstraint(fields=('funding_pledge_reversal', 'collateral_item'), name='loans_funding_pledge_custody_reversal_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pawncollateralcustodyevent',
            constraint=models.UniqueConstraint(fields=('funding_return_reversal', 'collateral_item'), name='loans_funding_return_custody_reversal_uniq'),
        ),
    ]
