# Generated by Django 6.1.1 on 2026-09-25 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0023_disbursal_attempt_history'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='repaymentscheduleversion',
            name='loans_schedule_loan_fingerprint_uniq',
        ),
    ]
