# Generated by Django 6.1.1 on 2026-09-25 11:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0024_disbursal_schedule_identity'),
        ('orgs', '0009_workspace_role_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pawnloaneconomicpolicy',
            options={'ordering': ('workspace_id', 'license_id', '-effective_from', '-revision', '-id')},
        ),
        migrations.AlterModelOptions(
            name='pawnmetalinterestratepolicy',
            options={'ordering': ('workspace_id', 'license_id', 'metal', '-effective_from', '-revision', '-id')},
        ),
        migrations.RemoveConstraint(
            model_name='pawnloaneconomicpolicy',
            name='loans_econ_ws_date_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='pawnloaneconomicpolicy',
            name='loans_econ_license_date_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='pawnmetalinterestratepolicy',
            name='loans_rate_ws_metal_date_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='pawnmetalinterestratepolicy',
            name='loans_rate_license_date_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='pawnmetalinterestratepolicy',
            name='loans_rate_series_date_uniq',
        ),
        migrations.AddField(
            model_name='pawnloaneconomicpolicy',
            name='revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pawnmetalinterestratepolicy',
            name='revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='pawnloaneconomicpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('license__isnull', True)), fields=('workspace', 'effective_from', 'revision'), name='loans_econ_ws_date_rev_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pawnloaneconomicpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('license__isnull', False)), fields=('license', 'effective_from', 'revision'), name='loans_econ_lic_date_rev_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pawnmetalinterestratepolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('license__isnull', True), ('series__isnull', True)), fields=('workspace', 'metal', 'effective_from', 'revision'), name='loans_rate_ws_date_rev_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pawnmetalinterestratepolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('license__isnull', False), ('series__isnull', True)), fields=('license', 'metal', 'effective_from', 'revision'), name='loans_rate_lic_date_rev_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pawnmetalinterestratepolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('series__isnull', False)), fields=('series', 'metal', 'effective_from', 'revision'), name='loans_rate_ser_date_rev_uniq'),
        ),
    ]
