# Generated by Django 6.1.1 on 2026-09-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0025_same_day_economic_policy_revisions'),
        ('orgs', '0009_workspace_role_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='pawncollateralitem',
            name='interest_override_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pawncollateralitem',
            name='interest_rate_override',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='pawncollateralitem',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='pawncollateralitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__isnull', True), models.Q(('quantity__gte', 1), ('quantity__lte', 10000)), _connector='OR'), name='loans_item_quantity_range'),
        ),
        migrations.AddConstraint(
            model_name='pawncollateralitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('interest_override_reason', ''), ('interest_rate_override__isnull', True)), models.Q(('interest_rate_override__gte', 0), ('interest_rate_override__isnull', False), ('interest_rate_override__lte', 100), models.Q(('interest_override_reason', ''), _negated=True)), _connector='OR'), name='loans_item_override_reason'),
        ),
    ]
