# Generated by Django 6.0.3 on 2026-08-08 17:43

import apps.tenant_apps.loans.models.regulatory
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_initial_license_revisions(apps, schema_editor):
    LoanLicense = apps.get_model("loans", "LoanLicense")
    LoanLicenseRevision = apps.get_model("loans", "LoanLicenseRevision")
    revisions = []
    for license in LoanLicense.objects.all().iterator():
        revisions.append(
            LoanLicenseRevision(
                license_id=license.pk,
                revision_number=1,
                kind="INITIAL",
                name=license.name,
                license_number=license.license_number,
                issuing_authority=license.issuing_authority,
                issued_on=license.issued_on,
                expires_on=license.expires_on,
                notes=license.notes,
                created_by_id=license.created_by_id,
            )
        )
    LoanLicenseRevision.objects.bulk_create(revisions, batch_size=500)


LICENSE_REVISION_GUARD_SQL = r"""
CREATE OR REPLACE FUNCTION loans_guard_license_revision_immutable()
RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'Loan license revision evidence is immutable';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER loans_license_revision_update_guard
BEFORE UPDATE ON loans_loanlicenserevision
FOR EACH ROW EXECUTE FUNCTION loans_guard_license_revision_immutable();

CREATE TRIGGER loans_license_revision_delete_guard
BEFORE DELETE ON loans_loanlicenserevision
FOR EACH ROW EXECUTE FUNCTION loans_guard_license_revision_immutable();
"""


LICENSE_REVISION_GUARD_REVERSE_SQL = r"""
DROP TRIGGER IF EXISTS loans_license_revision_delete_guard ON loans_loanlicenserevision;
DROP TRIGGER IF EXISTS loans_license_revision_update_guard ON loans_loanlicenserevision;
DROP FUNCTION IF EXISTS loans_guard_license_revision_immutable();
"""


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0026_funding_draft_inputs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanLicenseRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('INITIAL', 'Initial issue'), ('AMENDMENT', 'Amendment'), ('RENEWAL', 'Renewal')], max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('license_number', models.CharField(max_length=100)),
                ('issuing_authority', models.CharField(blank=True, max_length=255)),
                ('issued_on', models.DateField()),
                ('expires_on', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('supporting_document', models.FileField(blank=True, upload_to=apps.tenant_apps.loans.models.regulatory.loan_license_document_upload)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('byte_size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_license_revisions_created', to=settings.AUTH_USER_MODEL)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='loans.loanlicense')),
            ],
            options={
                'ordering': ('license_id', 'revision_number'),
                'indexes': [models.Index(fields=['license', '-revision_number'], name='loans_licrev_latest_idx'), models.Index(fields=['expires_on', 'kind'], name='loans_licrev_expiry_idx')],
                'constraints': [models.UniqueConstraint(fields=('license', 'revision_number'), name='loans_license_revision_number_uniq'), models.CheckConstraint(condition=models.Q(('revision_number__gt', 0)), name='loans_license_revision_number_positive'), models.CheckConstraint(condition=models.Q(('expires_on__gte', models.F('issued_on'))), name='loans_license_revision_dates_valid'), models.CheckConstraint(condition=models.Q(models.Q(('byte_size', 0), ('sha256', ''), ('supporting_document', '')), models.Q(models.Q(('supporting_document', ''), _negated=True), models.Q(('sha256', ''), _negated=True), ('byte_size__gt', 0)), _connector='OR'), name='loans_license_revision_document_complete')],
            },
        ),
        migrations.RunPython(
            backfill_initial_license_revisions,
            migrations.RunPython.noop,
        ),
        migrations.RunSQL(
            LICENSE_REVISION_GUARD_SQL,
            reverse_sql=LICENSE_REVISION_GUARD_REVERSE_SQL,
        ),
    ]
