# Generated by Django 6.0.3 on 2026-08-08 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0027_license_regulatory_evidence'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fundingloan',
            new_name='loans_fund_state_created_idx',
            old_name='loans_funding_state_created_idx',
        ),
    ]
