# Generated by Django 6.1.1 on 2026-09-28 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from apps.tenancy.rls import EnableWorkspaceRLS


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0027_draft_submission_identity'),
        ('orgs', '0009_workspace_role_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanOriginationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_collateral_photos', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('workspace',), name='loans_origination_settings_ws_uniq')],
            },
        ),
        EnableWorkspaceRLS("LoanOriginationSettings"),
    ]
