# Generated by Django 6.0.3 on 2026-08-09 03:19

import django.db.models.deletion
from django.db import migrations, models


def backfill_pawn_loan_license_revisions(apps, schema_editor):
    PawnLoan = apps.get_model("loans", "PawnLoan")
    LoanLicenseRevision = apps.get_model("loans", "LoanLicenseRevision")
    first_by_license = {}
    for revision in LoanLicenseRevision.objects.order_by(
        "license_id", "revision_number"
    ).iterator():
        first_by_license.setdefault(revision.license_id, revision.pk)
    for license_id, revision_id in first_by_license.items():
        PawnLoan.objects.filter(
            license_id=license_id,
            license_revision_id__isnull=True,
        ).update(license_revision_id=revision_id)


LICENSE_LINK_GUARD_SQL = r"""
CREATE OR REPLACE FUNCTION loans_guard_pawn_license_revision()
RETURNS trigger AS $$
DECLARE
    revision_license_id bigint;
BEGIN
    IF NEW.license_revision_id IS NOT NULL THEN
        SELECT license_id INTO revision_license_id
          FROM loans_loanlicenserevision
         WHERE id = NEW.license_revision_id;
        IF revision_license_id IS NULL OR revision_license_id <> NEW.license_id THEN
            RAISE EXCEPTION 'PawnLoan license revision must belong to its license';
        END IF;
    END IF;
    IF TG_OP = 'UPDATE'
       AND OLD.state <> 'DRAFT'
       AND NEW.license_revision_id IS DISTINCT FROM OLD.license_revision_id THEN
        RAISE EXCEPTION 'PawnLoan license revision is immutable after draft';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER loans_pawn_license_revision_guard
BEFORE INSERT OR UPDATE OF license_id, license_revision_id
ON loans_pawnloan
FOR EACH ROW EXECUTE FUNCTION loans_guard_pawn_license_revision();
"""


LICENSE_LINK_GUARD_REVERSE_SQL = r"""
DROP TRIGGER IF EXISTS loans_pawn_license_revision_guard ON loans_pawnloan;
DROP FUNCTION IF EXISTS loans_guard_pawn_license_revision();
"""


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0028_shorten_portable_index_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='pawnloan',
            name='license_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pawn_loans', to='loans.loanlicenserevision'),
        ),
        migrations.RunPython(
            backfill_pawn_loan_license_revisions,
            migrations.RunPython.noop,
        ),
        migrations.RunSQL(
            LICENSE_LINK_GUARD_SQL,
            reverse_sql=LICENSE_LINK_GUARD_REVERSE_SQL,
        ),
    ]
