# Generated by Django 6.1.1 on 2026-09-30 05:16

import apps.tenant_apps.loans.models.statutory
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from apps.tenancy.rls import EnableWorkspaceRLS


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0028_origination_photo_settings'),
        ('orgs', '0010_storage_inventory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatutoryAuctionNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.JSONField()),
                ('snapshot_sha256', models.CharField(max_length=64)),
                ('artifact', models.FileField(upload_to=apps.tenant_apps.loans.models.statutory.statutory_upload)),
                ('artifact_sha256', models.CharField(max_length=64)),
                ('template_version', models.CharField(default='tn-rule12-catalogue-v1', max_length=60)),
                ('request_key', models.CharField(max_length=120)),
                ('auction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='statutory_notice', to='loans.pawnloanauction')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatutoryNoticeEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(choices=[('PRINTED', 'Printed and signed by the auctioneer'), ('POSTED', 'Posted with registration and acknowledgement/POD'), ('ACKNOWLEDGED', 'Acknowledgement / proof of delivery received'), ('RETURNED', 'Undelivered cover received back'), ('REFERRED', 'Referred to the Village Administrative Officer'), ('OFFICER_RECEIVED', 'Village Officer receipt confirmed'), ('CERTIFIED', 'Official affixture and proclamation certificate received'), ('REVIEWED', 'Readiness evidence reviewed'), ('WITHDRAWN', 'Notice withdrawn / correction required')], max_length=20)),
                ('occurred_on', models.DateField()),
                ('details', models.JSONField(default=dict)),
                ('attachment', models.FileField(blank=True, upload_to=apps.tenant_apps.loans.models.statutory.statutory_upload)),
                ('attachment_sha256', models.CharField(blank=True, max_length=64)),
                ('request_key', models.CharField(max_length=120)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='loans.statutoryauctionnotice')),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company')),
            ],
            options={
                'ordering': ('created_at', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('notice', 'request_key'), name='loans_stat_evidence_request_uniq')],
            },
        ),
        EnableWorkspaceRLS('StatutoryAuctionNotice'),
        EnableWorkspaceRLS('StatutoryNoticeEvidence'),
        migrations.RunSQL(
            """
            CREATE FUNCTION loans_statutory_evidence_guard() RETURNS trigger LANGUAGE plpgsql AS $$
            BEGIN
              IF TG_OP <> 'INSERT' THEN RAISE EXCEPTION 'Statutory evidence is immutable'; END IF;
              IF TG_TABLE_NAME = 'loans_statutoryauctionnotice' THEN
                IF NOT EXISTS (SELECT 1 FROM loans_pawnloanauction WHERE id=NEW.auction_id AND workspace_id=NEW.workspace_id)
                THEN RAISE EXCEPTION 'Statutory auction Workspace mismatch'; END IF;
              ELSE
                IF NOT EXISTS (SELECT 1 FROM loans_statutoryauctionnotice WHERE id=NEW.notice_id AND workspace_id=NEW.workspace_id)
                THEN RAISE EXCEPTION 'Statutory notice Workspace mismatch'; END IF;
              END IF;
              RETURN NEW;
            END $$;
            CREATE TRIGGER loans_stat_notice_immutable BEFORE INSERT OR UPDATE OR DELETE ON loans_statutoryauctionnotice
              FOR EACH ROW EXECUTE FUNCTION loans_statutory_evidence_guard();
            CREATE TRIGGER loans_stat_evidence_immutable BEFORE INSERT OR UPDATE OR DELETE ON loans_statutorynoticeevidence
              FOR EACH ROW EXECUTE FUNCTION loans_statutory_evidence_guard();
            """,
            """
            DROP TRIGGER loans_stat_evidence_immutable ON loans_statutorynoticeevidence;
            DROP TRIGGER loans_stat_notice_immutable ON loans_statutoryauctionnotice;
            DROP FUNCTION loans_statutory_evidence_guard();
            """,
        ),
    ]
