# Generated by Django 6.1.1 on 2026-09-30 06:36

import apps.tenant_apps.loans.models.statutory
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from apps.tenancy.rls import EnableWorkspaceRLS


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0029_statutory_notices'),
        ('orgs', '0010_storage_inventory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PledgeBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('layout', models.CharField(choices=[('facing_a4', 'Facing A4'), ('landscape_a4', 'Landscape A4')], max_length=20)),
                ('starts_on', models.DateField()),
                ('first_page', models.PositiveIntegerField(default=1)),
                ('opening_note', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('series', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pledge_book', to='loans.loanseries')),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PledgeBookBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_page', models.PositiveIntegerField()),
                ('last_page', models.PositiveIntegerField()),
                ('mode', models.CharField(choices=[('full', 'Full pages'), ('partial', 'Include partial page')], max_length=10)),
                ('cutoff', models.DateField()),
                ('snapshot', models.JSONField()),
                ('snapshot_sha256', models.CharField(max_length=64)),
                ('review_sha256', models.CharField(max_length=64)),
                ('artifact', models.FileField(upload_to=apps.tenant_apps.loans.models.statutory.statutory_upload)),
                ('artifact_sha256', models.CharField(max_length=64)),
                ('template_version', models.CharField(max_length=60)),
                ('request_key', models.CharField(max_length=64)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='loans.pledgebook')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company')),
            ],
            options={
                'ordering': ('first_page',),
            },
        ),
        migrations.CreateModel(
            name='PledgeBookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_page', models.PositiveIntegerField()),
                ('last_page', models.PositiveIntegerField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='loans.pledgebookbatch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pledge_book_entry', to='loans.pawnloan')),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PledgeBookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('basis_sha256', models.CharField(max_length=64)),
                ('supplements', models.JSONField(blank=True, default=dict)),
                ('source_reference', models.CharField(max_length=300)),
                ('notes', models.TextField()),
                ('request_key', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pledge_reviews', to='loans.pawnloan')),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company')),
            ],
        ),
        migrations.AddConstraint(
            model_name='pledgebookbatch',
            constraint=models.UniqueConstraint(fields=('book', 'request_key'), name='loans_pledge_batch_request_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pledgebookbatch',
            constraint=models.UniqueConstraint(fields=('book', 'first_page'), name='loans_pledge_batch_page_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pledgebookbatch',
            constraint=models.CheckConstraint(condition=models.Q(('last_page__gte', models.F('first_page'))), name='loans_pledge_batch_page_order'),
        ),
        migrations.AddConstraint(
            model_name='pledgebookreview',
            constraint=models.UniqueConstraint(fields=('loan', 'request_key'), name='loans_pledge_review_request_uniq'),
        ),
        *[EnableWorkspaceRLS(name) for name in ('PledgeBook', 'PledgeBookBatch', 'PledgeBookEntry', 'PledgeBookReview')],
        migrations.RunSQL(
            """
            CREATE FUNCTION loans_pledge_book_guard() RETURNS trigger LANGUAGE plpgsql AS $$
            DECLARE parent_workspace bigint; parent_series bigint; start_page integer; end_page integer;
            BEGIN
              IF TG_OP <> 'INSERT' THEN RAISE EXCEPTION 'Pledge book evidence is immutable'; END IF;
              IF TG_TABLE_NAME = 'loans_pledgebook' THEN
                SELECT workspace_id INTO parent_workspace FROM loans_loanseries WHERE id=NEW.series_id;
                IF NEW.first_page < 1 OR NEW.layout NOT IN ('facing_a4','landscape_a4')
                  THEN RAISE EXCEPTION 'Invalid pledge book layout or starting page'; END IF;
              ELSIF TG_TABLE_NAME = 'loans_pledgebookreview' THEN
                SELECT workspace_id INTO parent_workspace FROM loans_pawnloan WHERE id=NEW.loan_id;
              ELSIF TG_TABLE_NAME = 'loans_pledgebookbatch' THEN
                SELECT workspace_id, first_page INTO parent_workspace, start_page FROM loans_pledgebook WHERE id=NEW.book_id FOR UPDATE;
                SELECT COALESCE(MAX(last_page)+1,start_page) INTO start_page FROM loans_pledgebookbatch WHERE book_id=NEW.book_id;
                IF NEW.first_page <> start_page OR NEW.last_page < NEW.first_page
                  THEN RAISE EXCEPTION 'Pledge book pages must advance without overlap or gaps'; END IF;
              ELSE
                SELECT b.workspace_id, k.series_id, b.first_page, b.last_page INTO parent_workspace, parent_series, start_page, end_page
                  FROM loans_pledgebookbatch b JOIN loans_pledgebook k ON k.id=b.book_id WHERE b.id=NEW.batch_id;
                IF NOT EXISTS (SELECT 1 FROM loans_pawnloan WHERE id=NEW.loan_id AND workspace_id=NEW.workspace_id AND series_id=parent_series)
                  OR NEW.first_page < start_page OR NEW.last_page > end_page OR NEW.last_page < NEW.first_page
                  THEN RAISE EXCEPTION 'Pledge entry parent or page mismatch'; END IF;
              END IF;
              IF parent_workspace IS NULL OR parent_workspace <> NEW.workspace_id
                THEN RAISE EXCEPTION 'Pledge book Workspace mismatch'; END IF;
              RETURN NEW;
            END $$;
            CREATE TRIGGER loans_pledge_book_immutable BEFORE INSERT OR UPDATE OR DELETE ON loans_pledgebook
              FOR EACH ROW EXECUTE FUNCTION loans_pledge_book_guard();
            CREATE TRIGGER loans_pledge_review_immutable BEFORE INSERT OR UPDATE OR DELETE ON loans_pledgebookreview
              FOR EACH ROW EXECUTE FUNCTION loans_pledge_book_guard();
            CREATE TRIGGER loans_pledge_batch_immutable BEFORE INSERT OR UPDATE OR DELETE ON loans_pledgebookbatch
              FOR EACH ROW EXECUTE FUNCTION loans_pledge_book_guard();
            CREATE TRIGGER loans_pledge_entry_immutable BEFORE INSERT OR UPDATE OR DELETE ON loans_pledgebookentry
              FOR EACH ROW EXECUTE FUNCTION loans_pledge_book_guard();
            """,
            """
            DROP TRIGGER loans_pledge_entry_immutable ON loans_pledgebookentry;
            DROP TRIGGER loans_pledge_batch_immutable ON loans_pledgebookbatch;
            DROP TRIGGER loans_pledge_review_immutable ON loans_pledgebookreview;
            DROP TRIGGER loans_pledge_book_immutable ON loans_pledgebook;
            DROP FUNCTION loans_pledge_book_guard();
            """,
        ),
    ]
