# Generated by Django 6.0.3 on 2026-08-09 03:46

import apps.tenant_apps.loans.models.media
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_collateral_public_ids(apps, schema_editor):
    PawnCollateralItem = apps.get_model("loans", "PawnCollateralItem")
    for item in PawnCollateralItem.objects.filter(public_id__isnull=True).iterator():
        item.public_id = uuid.uuid4()
        item.save(update_fields=["public_id"])


def create_media_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        """
        CREATE OR REPLACE FUNCTION loans_reject_collateral_evidence_mutation()
        RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'collateral media and label evidence is immutable';
        END;
        $$ LANGUAGE plpgsql;
        CREATE TRIGGER loans_photo_immutable
        BEFORE UPDATE OR DELETE ON loans_pawncollateralphoto
        FOR EACH ROW EXECUTE FUNCTION loans_reject_collateral_evidence_mutation();
        CREATE TRIGGER loans_label_immutable
        BEFORE UPDATE OR DELETE ON loans_pawncollaterallabelissue
        FOR EACH ROW EXECUTE FUNCTION loans_reject_collateral_evidence_mutation();
        CREATE OR REPLACE FUNCTION loans_reject_collateral_public_id_change()
        RETURNS trigger AS $$
        BEGIN
            IF NEW.public_id IS DISTINCT FROM OLD.public_id THEN
                RAISE EXCEPTION 'collateral public identity is immutable';
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        CREATE TRIGGER loans_item_public_id_immutable
        BEFORE UPDATE ON loans_pawncollateralitem
        FOR EACH ROW EXECUTE FUNCTION loans_reject_collateral_public_id_change();
        """
    )


def drop_media_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        """
        DROP TRIGGER IF EXISTS loans_item_public_id_immutable ON loans_pawncollateralitem;
        DROP FUNCTION IF EXISTS loans_reject_collateral_public_id_change();
        DROP TRIGGER IF EXISTS loans_label_immutable ON loans_pawncollaterallabelissue;
        DROP TRIGGER IF EXISTS loans_photo_immutable ON loans_pawncollateralphoto;
        DROP FUNCTION IF EXISTS loans_reject_collateral_evidence_mutation();
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0029_pawn_loan_license_revision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pawncollateralitem',
            name='public_id',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(
            backfill_collateral_public_ids,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='pawncollateralitem',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='PawnCollateralLabelIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('PREVIEW', 'Preview'), ('PRINT', 'Print or reprint')], max_length=12)),
                ('qr_target', models.CharField(max_length=500)),
                ('payload_sha256', models.CharField(max_length=64)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('collateral_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='label_issues', to='loans.pawncollateralitem')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pawn_collateral_labels_issued', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('collateral_item_id', 'issued_at', 'id'),
                'indexes': [models.Index(fields=['collateral_item', 'issued_at'], name='loans_label_item_time_idx')],
            },
        ),
        migrations.CreateModel(
            name='PawnCollateralPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to=apps.tenant_apps.loans.models.media.collateral_photo_upload_to)),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('sha256', models.CharField(max_length=64)),
                ('byte_size', models.PositiveBigIntegerField()),
                ('workflow_source', models.CharField(choices=[('DRAFT', 'Draft capture'), ('RENEWAL', 'Release and renew'), ('POST_APPROVAL', 'Post-approval evidence')], max_length=24)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pawn_collateral_photos_captured', to=settings.AUTH_USER_MODEL)),
                ('collateral_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='loans.pawncollateralitem')),
                ('inherited_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='renewal_copies', to='loans.pawncollateralphoto')),
            ],
            options={
                'ordering': ('collateral_item_id', 'captured_at', 'id'),
                'indexes': [models.Index(fields=['collateral_item', 'captured_at'], name='loans_photo_item_time_idx')],
            },
        ),
        migrations.RunPython(create_media_guards, drop_media_guards),
    ]
