# Generated by Django 6.1.1 on 2026-09-30 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from apps.tenancy.rls import EnableWorkspaceRLS


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0030_pledge_book'),
        ('orgs', '0010_storage_inventory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctioneerHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=160)),
                ('auctioneer', models.CharField(max_length=200)),
                ('loan_ids', models.JSONField()),
                ('request_key', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='loans.loanlicense')),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company')),
            ],
        ),
        migrations.CreateModel(
            name='AuctioneerHandoverRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('number', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('snapshot_sha256', models.CharField(max_length=64)),
                ('request_key', models.CharField(max_length=64)),
                ('request_sha256', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('handover', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='loans.auctioneerhandover')),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company')),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.AddConstraint(
            model_name='auctioneerhandover',
            constraint=models.UniqueConstraint(fields=('workspace', 'request_key'), name='loans_handover_request_uniq'),
        ),
        migrations.AddConstraint(
            model_name='auctioneerhandoverrevision',
            constraint=models.UniqueConstraint(fields=('handover', 'number'), name='loans_handover_revision_uniq'),
        ),
        migrations.AddConstraint(
            model_name='auctioneerhandoverrevision',
            constraint=models.UniqueConstraint(fields=('workspace', 'request_key'), name='loans_handover_revision_req_uniq'),
        ),
        EnableWorkspaceRLS('AuctioneerHandover'),
        EnableWorkspaceRLS('AuctioneerHandoverRevision'),
        migrations.RunSQL(
            """
            CREATE FUNCTION loans_handover_guard() RETURNS trigger LANGUAGE plpgsql AS $$
            DECLARE ids jsonb; parent_ws bigint; last_number integer;
            BEGIN
              IF TG_OP <> 'INSERT' THEN RAISE EXCEPTION 'Auctioneer handover evidence is immutable'; END IF;
              IF TG_TABLE_NAME = 'loans_auctioneerhandover' THEN
                IF NOT EXISTS (SELECT 1 FROM loans_loanlicense WHERE id=NEW.license_id AND workspace_id=NEW.workspace_id)
                THEN RAISE EXCEPTION 'Handover licence Workspace mismatch'; END IF;
                IF jsonb_typeof(NEW.loan_ids) <> 'array' OR jsonb_array_length(NEW.loan_ids) NOT BETWEEN 1 AND 100
                THEN RAISE EXCEPTION 'Invalid handover cohort'; END IF;
                IF (SELECT count(DISTINCT value) FROM jsonb_array_elements(NEW.loan_ids)) <> jsonb_array_length(NEW.loan_ids)
                THEN RAISE EXCEPTION 'Duplicate handover loan'; END IF;
                IF EXISTS (SELECT 1 FROM jsonb_array_elements_text(NEW.loan_ids) v
                  WHERE NOT EXISTS (SELECT 1 FROM loans_pawnloan l WHERE l.id=v.value::bigint
                    AND l.workspace_id=NEW.workspace_id AND l.license_id=NEW.license_id))
                THEN RAISE EXCEPTION 'Handover loan scope mismatch'; END IF;
              ELSE
                SELECT loan_ids, workspace_id INTO ids, parent_ws FROM loans_auctioneerhandover WHERE id=NEW.handover_id FOR UPDATE;
                IF parent_ws IS NULL OR parent_ws <> NEW.workspace_id THEN RAISE EXCEPTION 'Handover Workspace mismatch'; END IF;
                SELECT COALESCE(MAX(number),0) INTO last_number FROM loans_auctioneerhandoverrevision WHERE handover_id=NEW.handover_id;
                IF NEW.number <> last_number+1 THEN RAISE EXCEPTION 'Handover revisions must be consecutive'; END IF;
                IF NEW.snapshot->'loan_ids' IS DISTINCT FROM ids
                  OR jsonb_typeof(NEW.snapshot->'rows') IS DISTINCT FROM 'array'
                THEN RAISE EXCEPTION 'Handover cohort cannot change'; END IF;
                IF (SELECT jsonb_agg((r->>'loan_id')::bigint ORDER BY (r->>'loan_id')::bigint) FROM jsonb_array_elements(NEW.snapshot->'rows') r)
                    IS DISTINCT FROM ids
                THEN RAISE EXCEPTION 'Revision must account for every original loan exactly once'; END IF;
              END IF;
              RETURN NEW;
            END $$;
            CREATE TRIGGER loans_handover_immutable BEFORE INSERT OR UPDATE OR DELETE ON loans_auctioneerhandover
              FOR EACH ROW EXECUTE FUNCTION loans_handover_guard();
            CREATE TRIGGER loans_handover_revision_immutable BEFORE INSERT OR UPDATE OR DELETE ON loans_auctioneerhandoverrevision
              FOR EACH ROW EXECUTE FUNCTION loans_handover_guard();
            """,
            """
            DROP TRIGGER loans_handover_revision_immutable ON loans_auctioneerhandoverrevision;
            DROP TRIGGER loans_handover_immutable ON loans_auctioneerhandover;
            DROP FUNCTION loans_handover_guard();
            """,
        ),
    ]
