# Generated by Django 6.0.3 on 2026-08-09 04:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def create_storage_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        """
        CREATE OR REPLACE FUNCTION loans_validate_storage_location()
        RETURNS trigger AS $$
        DECLARE parent_level text; parent_workspace bigint;
        BEGIN
            IF TG_OP = 'UPDATE' AND NEW.public_id IS DISTINCT FROM OLD.public_id THEN
                RAISE EXCEPTION 'storage public identity is immutable';
            END IF;
            IF NEW.level = 'BRANCH' THEN
                IF NEW.parent_id IS NOT NULL THEN RAISE EXCEPTION 'branch cannot have a parent'; END IF;
                RETURN NEW;
            END IF;
            IF NEW.parent_id IS NULL THEN RAISE EXCEPTION 'storage hierarchy cannot skip a parent'; END IF;
            SELECT level, workspace_id INTO parent_level, parent_workspace
              FROM loans_pawnstoragelocation WHERE id = NEW.parent_id;
            IF parent_workspace IS DISTINCT FROM NEW.workspace_id THEN
                RAISE EXCEPTION 'storage parent belongs to another workspace';
            END IF;
            IF (NEW.level = 'VAULT' AND parent_level <> 'BRANCH')
               OR (NEW.level = 'CABINET' AND parent_level <> 'VAULT')
               OR (NEW.level = 'BOX' AND parent_level <> 'CABINET')
               OR (NEW.level = 'SLOT' AND parent_level <> 'BOX') THEN
                RAISE EXCEPTION 'invalid storage hierarchy';
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        CREATE TRIGGER loans_storage_location_guard
        BEFORE INSERT OR UPDATE ON loans_pawnstoragelocation
        FOR EACH ROW EXECUTE FUNCTION loans_validate_storage_location();

        CREATE OR REPLACE FUNCTION loans_reject_storage_movement_mutation()
        RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'collateral storage movement is immutable';
        END;
        $$ LANGUAGE plpgsql;
        CREATE TRIGGER loans_storage_movement_immutable
        BEFORE UPDATE OR DELETE ON loans_pawncollateralstoragemovement
        FOR EACH ROW EXECUTE FUNCTION loans_reject_storage_movement_mutation();

        CREATE OR REPLACE FUNCTION loans_validate_storage_movement()
        RETURNS trigger AS $$
        DECLARE current_location bigint; item_workspace bigint; endpoint_workspace bigint;
        BEGIN
            SELECT i.current_storage_location_id, l.workspace_id
              INTO current_location, item_workspace
              FROM loans_pawncollateralitem i
              JOIN loans_pawnloan l ON l.id = i.loan_id
             WHERE i.id = NEW.collateral_item_id;
            IF NEW.from_location_id IS DISTINCT FROM current_location THEN
                RAISE EXCEPTION 'storage movement does not start at current projection';
            END IF;
            IF NEW.to_location_id IS NOT NULL THEN
                SELECT workspace_id INTO endpoint_workspace
                  FROM loans_pawnstoragelocation WHERE id = NEW.to_location_id;
                IF endpoint_workspace IS DISTINCT FROM item_workspace THEN
                    RAISE EXCEPTION 'storage destination belongs to another workspace';
                END IF;
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        CREATE TRIGGER loans_storage_movement_guard
        BEFORE INSERT ON loans_pawncollateralstoragemovement
        FOR EACH ROW EXECUTE FUNCTION loans_validate_storage_movement();

        CREATE OR REPLACE FUNCTION loans_validate_storage_projection()
        RETURNS trigger AS $$
        DECLARE latest_destination bigint; destination_workspace bigint; item_workspace bigint;
        BEGIN
            IF NEW.current_storage_location_id IS NOT DISTINCT FROM OLD.current_storage_location_id THEN RETURN NEW; END IF;
            SELECT to_location_id INTO latest_destination
              FROM loans_pawncollateralstoragemovement
             WHERE collateral_item_id = NEW.id ORDER BY id DESC LIMIT 1;
            IF latest_destination IS DISTINCT FROM NEW.current_storage_location_id THEN
                RAISE EXCEPTION 'storage projection must match latest movement';
            END IF;
            IF NEW.current_storage_location_id IS NOT NULL THEN
                SELECT workspace_id INTO destination_workspace FROM loans_pawnstoragelocation WHERE id = NEW.current_storage_location_id;
                SELECT workspace_id INTO item_workspace FROM loans_pawnloan WHERE id = NEW.loan_id;
                IF destination_workspace IS DISTINCT FROM item_workspace THEN RAISE EXCEPTION 'storage projection crosses workspace'; END IF;
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        CREATE TRIGGER loans_storage_projection_guard
        BEFORE UPDATE OF current_storage_location_id ON loans_pawncollateralitem
        FOR EACH ROW EXECUTE FUNCTION loans_validate_storage_projection();
        """
    )


def drop_storage_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        """
        DROP TRIGGER IF EXISTS loans_storage_projection_guard ON loans_pawncollateralitem;
        DROP FUNCTION IF EXISTS loans_validate_storage_projection();
        DROP TRIGGER IF EXISTS loans_storage_movement_guard ON loans_pawncollateralstoragemovement;
        DROP FUNCTION IF EXISTS loans_validate_storage_movement();
        DROP TRIGGER IF EXISTS loans_storage_movement_immutable ON loans_pawncollateralstoragemovement;
        DROP FUNCTION IF EXISTS loans_reject_storage_movement_mutation();
        DROP TRIGGER IF EXISTS loans_storage_location_guard ON loans_pawnstoragelocation;
        DROP FUNCTION IF EXISTS loans_validate_storage_location();
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0030_collateral_media_and_labels'),
        ('orgs', '0024_alter_auditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PawnStorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('level', models.CharField(choices=[('BRANCH', 'Branch'), ('VAULT', 'Vault'), ('CABINET', 'Cabinet'), ('BOX', 'Box'), ('SLOT', 'Slot')], max_length=12)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pawn_storage_locations_created', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='loans.pawnstoragelocation')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pawn_storage_locations', to='orgs.company')),
            ],
            options={
                'ordering': ('level', 'code', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PawnCollateralStorageMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PLACEMENT', 'Initial placement'), ('TRANSFER', 'Storage transfer'), ('REMOVAL', 'Workflow removal')], max_length=12)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('workflow_source', models.CharField(default='OPERATOR', max_length=64)),
                ('source_reference', models.CharField(blank=True, max_length=120)),
                ('moved_at', models.DateTimeField(auto_now_add=True)),
                ('collateral_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storage_movements', to='loans.pawncollateralitem')),
                ('moved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pawn_storage_movements_recorded', to=settings.AUTH_USER_MODEL)),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outbound_movements', to='loans.pawnstoragelocation')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inbound_movements', to='loans.pawnstoragelocation')),
            ],
            options={
                'ordering': ('collateral_item_id', 'moved_at', 'id'),
            },
        ),
        migrations.AddField(
            model_name='pawncollateralitem',
            name='current_storage_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_collateral_items', to='loans.pawnstoragelocation'),
        ),
        migrations.AddIndex(
            model_name='pawnstoragelocation',
            index=models.Index(fields=['workspace', 'level', 'is_active'], name='loans_storage_level_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='pawnstoragelocation',
            constraint=models.UniqueConstraint(fields=('workspace', 'code'), name='loans_storage_workspace_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pawnstoragelocation',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__isnull', True), ('capacity__gt', 0), _connector='OR'), name='loans_storage_capacity_positive'),
        ),
        migrations.AddIndex(
            model_name='pawncollateralstoragemovement',
            index=models.Index(fields=['collateral_item', 'moved_at'], name='loans_storage_item_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='pawncollateralstoragemovement',
            constraint=models.CheckConstraint(condition=models.Q(('from_location__isnull', True), ('to_location__isnull', True), _negated=True), name='loans_storage_movement_has_endpoint'),
        ),
        migrations.AddConstraint(
            model_name='pawncollateralstoragemovement',
            constraint=models.CheckConstraint(condition=models.Q(('from_location__isnull', True), ('to_location__isnull', True), models.Q(('from_location', models.F('to_location')), _negated=True), _connector='OR'), name='loans_storage_movement_changes'),
        ),
        migrations.RunPython(create_storage_guards, drop_storage_guards),
    ]
