# Generated by Django 6.1.1 on 2026-09-30 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0031_auctioneer_handovers'),
        ('orgs', '0010_storage_inventory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pawnloaneconomicpolicy',
            name='loans_econ_ws_date_rev_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='pawnloaneconomicpolicy',
            name='loans_econ_lic_date_rev_uniq',
        ),
        migrations.AddField(
            model_name='loanpolicysnapshot',
            name='minimum_first_month',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pawnloaneconomicpolicy',
            name='minimum_first_month',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pawnloaneconomicpolicy',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='economic_policies', to='loans.loanseries'),
        ),
        migrations.AlterField(
            model_name='loanpolicysnapshot',
            name='partial_month_method',
            field=models.CharField(choices=[('FULL_MONTH', 'Full Month'), ('SLAB', 'Slab'), ('STARTED_WEEKS', 'Started Weeks'), ('ACTUAL_DAYS', 'Actual Days')], max_length=16),
        ),
        migrations.AlterField(
            model_name='pawnloaneconomicpolicy',
            name='partial_month_method',
            field=models.CharField(choices=[('FULL_MONTH', 'Full Month'), ('SLAB', 'Slab'), ('STARTED_WEEKS', 'Started Weeks'), ('ACTUAL_DAYS', 'Actual Days')], default='FULL_MONTH', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='pawnloaneconomicpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('license__isnull', True), ('series__isnull', True)), fields=('workspace', 'effective_from', 'revision'), name='loans_econ_ws_date_rev_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pawnloaneconomicpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('license__isnull', False), ('series__isnull', True)), fields=('license', 'effective_from', 'revision'), name='loans_econ_lic_date_rev_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pawnloaneconomicpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('series__isnull', False)), fields=('series', 'effective_from', 'revision'), name='loans_econ_ser_date_rev_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pawnloaneconomicpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('series__isnull', True), ('license__isnull', False), _connector='OR'), name='loans_econ_series_license'),
        ),
    ]
