# Generated by Django 6.1.1 on 2026-10-01 12:31

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models
from apps.tenancy.rls import EnableWorkspaceRLS


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0032_series_partial_interest'),
        ('orgs', '0010_storage_inventory'),
        ('party', '0003_party_photo_gallery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),

    ]

    operations = [
        migrations.CreateModel(
            name='KhataSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=120)),
                ('prefix', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^[A-Z][A-Z-]{0,15}$')])),
                ('width', models.PositiveSmallIntegerField(default=5)),
                ('next_number', models.PositiveBigIntegerField(default=1, editable=False)),
                ('maximum_number', models.PositiveBigIntegerField(default=99999)),
                ('has_issued_number', models.BooleanField(default=False, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='khata_series', to='loans.loanlicense')),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company')),
            ],
        ),
        migrations.CreateModel(
            name='KhataAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('account_number', models.CharField(editable=False, max_length=28)),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=16)),
                ('request_key', models.UUIDField(editable=False)),
                ('request_sha256', models.CharField(editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='khata_accounts', to='party.party')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='loans.khataseries')),
            ],
        ),
        migrations.CreateModel(
            name='KhataAgreementRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('intended_on', models.DateField()),
                ('agreed_limit', models.DecimalField(decimal_places=2, max_digits=18)),
                ('monthly_rate', models.DecimalField(decimal_places=6, max_digits=10)),
                ('ltv', models.DecimalField(decimal_places=6, max_digits=7)),
                ('frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('ANNUAL', 'Annually')], max_length=7)),
                ('contract_version', models.CharField(default='KHATA-1', editable=False, max_length=16)),
                ('lender_name', models.CharField(max_length=255)),
                ('lender_address', models.TextField(max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('reason', models.TextField()),
                ('request_key', models.UUIDField(editable=False)),
                ('request_sha256', models.CharField(editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreement_revisions', to='loans.khataaccount')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company')),
            ],
            options={
                'ordering': ('number',),
                'constraints': [models.UniqueConstraint(fields=('account', 'number'), name='khata_revision_number_uniq'), models.UniqueConstraint(fields=('workspace', 'request_key'), name='khata_revision_request_uniq'), models.CheckConstraint(condition=models.Q(('agreed_limit__gt', 0), ('ltv__gt', 0), ('ltv__lte', 1), ('monthly_rate__gte', 0), ('number__gte', 1)), name='khata_revision_terms_valid'), models.CheckConstraint(condition=models.Q(('contract_version', 'KHATA-1'), ('frequency__in', ('MONTHLY', 'ANNUAL'))), name='khata_revision_contract_valid')],
            },
        ),
        migrations.AddConstraint(
            model_name='khataseries',
            constraint=models.UniqueConstraint(fields=('workspace', 'code'), name='khata_series_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='khataseries',
            constraint=models.UniqueConstraint(fields=('workspace', 'prefix'), name='khata_series_prefix_uniq'),
        ),
        migrations.AddConstraint(
            model_name='khataseries',
            constraint=models.CheckConstraint(condition=models.Q(('width__gte', 1), ('width__lte', 12)), name='khata_series_width_valid'),
        ),
        migrations.AddConstraint(
            model_name='khataseries',
            constraint=models.CheckConstraint(condition=models.Q(('maximum_number__gte', 1), ('maximum_number__lte', 999999999999), ('next_number__gte', 1), ('next_number__lte', django.db.models.expressions.CombinedExpression(models.F('maximum_number'), '+', models.Value(1)))), name='khata_series_counter_valid'),
        ),
        migrations.AddConstraint(
            model_name='khataseries',
            constraint=models.CheckConstraint(condition=models.Q(('prefix__regex', '^[A-Z][A-Z-]{0,15}$')), name='khata_series_prefix_valid'),
        ),
        migrations.AddConstraint(
            model_name='khataaccount',
            constraint=models.UniqueConstraint(fields=('workspace', 'account_number'), name='khata_account_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='khataaccount',
            constraint=models.UniqueConstraint(fields=('workspace', 'request_key'), name='khata_account_request_uniq'),
        ),
        migrations.AddConstraint(
            model_name='khataaccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancellation_reason', ''), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('state', 'DRAFT')), models.Q(('cancelled_at__isnull', False), ('cancelled_by__isnull', False), ('state', 'CANCELLED'), models.Q(('cancellation_reason', ''), _negated=True)), _connector='OR'), name='khata_account_draft_only'),
        ),
        EnableWorkspaceRLS('KhataSeries'),
        EnableWorkspaceRLS('KhataAccount'),
        EnableWorkspaceRLS('KhataAgreementRevision'),
        migrations.RunSQL(
            """
            CREATE FUNCTION loans_khata_foundation_guard() RETURNS trigger LANGUAGE plpgsql AS $$
            DECLARE series_row loans_khataseries%ROWTYPE; parent_row loans_khataaccount%ROWTYPE;
              expected text; last_revision integer;
            BEGIN
              IF TG_OP = 'DELETE' THEN RAISE EXCEPTION 'Khata evidence cannot be deleted'; END IF;
              IF TG_TABLE_NAME = 'loans_khataseries' THEN
                IF NEW.license_id IS NOT NULL AND NOT EXISTS (
                  SELECT 1 FROM loans_loanlicense WHERE id=NEW.license_id AND workspace_id=NEW.workspace_id)
                THEN RAISE EXCEPTION 'Khata licence Workspace mismatch'; END IF;
                IF NEW.maximum_number >= power(10::numeric, NEW.width)
                  OR btrim(NEW.code) = '' OR btrim(NEW.name) = ''
                THEN RAISE EXCEPTION 'Invalid khata series configuration'; END IF;
                IF TG_OP = 'INSERT' THEN
                  IF NEW.next_number <> 1 OR NEW.has_issued_number
                  THEN RAISE EXCEPTION 'Khata series must start unused at one'; END IF;
                ELSE
                  IF NEW.workspace_id <> OLD.workspace_id OR NEW.created_by_id <> OLD.created_by_id
                    OR NEW.created_at <> OLD.created_at OR NEW.next_number < OLD.next_number
                    OR (OLD.has_issued_number AND NOT NEW.has_issued_number)
                  THEN RAISE EXCEPTION 'Khata series identity/counter cannot be rewritten'; END IF;
                  IF OLD.has_issued_number AND (
                    NEW.license_id IS DISTINCT FROM OLD.license_id OR NEW.prefix <> OLD.prefix OR NEW.width <> OLD.width)
                  THEN RAISE EXCEPTION 'Issued khata series association and format are frozen'; END IF;
                END IF;
              ELSIF TG_TABLE_NAME = 'loans_khataaccount' THEN
                IF TG_OP = 'UPDATE' THEN
                  IF OLD.state <> 'DRAFT' OR NEW.state <> 'CANCELLED'
                    OR (to_jsonb(NEW) - ARRAY['state','cancelled_at','cancelled_by_id','cancellation_reason'])
                       IS DISTINCT FROM (to_jsonb(OLD) - ARRAY['state','cancelled_at','cancelled_by_id','cancellation_reason'])
                    OR btrim(NEW.cancellation_reason) = ''
                  THEN RAISE EXCEPTION 'Khata draft identity is immutable; only cancellation is supported'; END IF;
                ELSE
                  SELECT * INTO series_row FROM loans_khataseries WHERE id=NEW.series_id FOR UPDATE;
                  IF series_row.id IS NULL OR series_row.workspace_id <> NEW.workspace_id
                    OR NOT EXISTS (SELECT 1 FROM party_party WHERE id=NEW.borrower_id AND workspace_id=NEW.workspace_id)
                  THEN RAISE EXCEPTION 'Khata account parent Workspace mismatch'; END IF;
                  IF NEW.state <> 'DRAFT' OR NOT series_row.is_active OR series_row.next_number > series_row.maximum_number
                  THEN RAISE EXCEPTION 'Khata series unavailable or account is not a draft'; END IF;
                  expected := series_row.prefix || lpad(series_row.next_number::text, series_row.width, '0');
                  IF NEW.account_number <> expected THEN RAISE EXCEPTION 'Khata account number must be the next series number'; END IF;
                  IF EXISTS (SELECT 1 FROM loans_pawnloan WHERE workspace_id=NEW.workspace_id AND loan_number=expected)
                  THEN RAISE EXCEPTION 'Khata number conflicts with an ordinary loan'; END IF;
                  UPDATE loans_khataseries SET next_number=next_number+1, has_issued_number=true WHERE id=NEW.series_id;
                END IF;
              ELSE
                IF TG_OP <> 'INSERT' THEN RAISE EXCEPTION 'Khata agreement evidence is immutable'; END IF;
                SELECT * INTO parent_row FROM loans_khataaccount WHERE id=NEW.account_id FOR UPDATE;
                IF parent_row.id IS NULL OR parent_row.workspace_id <> NEW.workspace_id
                THEN RAISE EXCEPTION 'Khata agreement parent Workspace mismatch'; END IF;
                IF parent_row.state <> 'DRAFT' THEN RAISE EXCEPTION 'Agreement proposals require a draft'; END IF;
                SELECT COALESCE(MAX(number),0) INTO last_revision FROM loans_khataagreementrevision WHERE account_id=NEW.account_id;
                IF NEW.number <> last_revision+1 THEN RAISE EXCEPTION 'Khata agreement revisions must be consecutive'; END IF;
                IF btrim(NEW.lender_name) = '' OR btrim(NEW.lender_address) = '' OR btrim(NEW.reason) = ''
                  OR NEW.agreed_limit = 'NaN'::numeric OR NEW.monthly_rate = 'NaN'::numeric OR NEW.ltv = 'NaN'::numeric
                THEN RAISE EXCEPTION 'Khata terms require finite amounts and lender/reason evidence'; END IF;
              END IF;
              RETURN NEW;
            END $$;
            CREATE TRIGGER loans_khata_series_guard BEFORE INSERT OR UPDATE OR DELETE ON loans_khataseries
              FOR EACH ROW EXECUTE FUNCTION loans_khata_foundation_guard();
            CREATE TRIGGER loans_khata_account_guard BEFORE INSERT OR UPDATE OR DELETE ON loans_khataaccount
              FOR EACH ROW EXECUTE FUNCTION loans_khata_foundation_guard();
            CREATE TRIGGER loans_khata_revision_guard BEFORE INSERT OR UPDATE OR DELETE ON loans_khataagreementrevision
              FOR EACH ROW EXECUTE FUNCTION loans_khata_foundation_guard();
            """,
            """
            DROP TRIGGER loans_khata_revision_guard ON loans_khataagreementrevision;
            DROP TRIGGER loans_khata_account_guard ON loans_khataaccount;
            DROP TRIGGER loans_khata_series_guard ON loans_khataseries;
            DROP FUNCTION loans_khata_foundation_guard();
            """,
        ),
    ]
