# Generated by Django 6.0.3 on 2026-08-09 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0032_pawnphysicalverificationexpectation_and_more'),
        ('orgs', '0024_alter_auditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanOperationalNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_kind', models.CharField(choices=[('LICENSE_EXPIRY', 'Regulatory license expiry'), ('VERIFICATION_DISCREPANCY', 'Physical-verification discrepancy')], max_length=32)),
                ('request_key', models.CharField(max_length=120)),
                ('scheduled_for', models.DateTimeField(db_index=True)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('payload_snapshot', models.JSONField(default=dict)),
                ('notification_event_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('notification_job_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_operational_notices_created', to=settings.AUTH_USER_MODEL)),
                ('source_license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operational_notices', to='loans.loanlicense')),
                ('source_verification_observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operational_notices', to='loans.pawnphysicalverificationobservation')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_operational_notices', to='orgs.company')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['workspace', 'scheduled_for'], name='loans_oper_notice_due_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'request_key'), name='loans_operational_notice_request_uniq'), models.CheckConstraint(condition=models.Q(models.Q(('notice_kind', 'LICENSE_EXPIRY'), ('source_license__isnull', False), ('source_verification_observation__isnull', True)), models.Q(('notice_kind', 'VERIFICATION_DISCREPANCY'), ('source_license__isnull', True), ('source_verification_observation__isnull', False)), _connector='OR'), name='loans_operational_notice_source_shape')],
            },
        ),
        migrations.RunSQL(
            sql=r"""
CREATE OR REPLACE FUNCTION loans_operational_notice_guard() RETURNS trigger AS $$
DECLARE source_workspace bigint;
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'Loans operational notice intents cannot be deleted.';
    END IF;
    IF TG_OP = 'INSERT' THEN
        IF NEW.source_license_id IS NOT NULL THEN
            SELECT workspace_id INTO source_workspace FROM loans_loanlicense
             WHERE id = NEW.source_license_id;
        ELSE
            SELECT session.workspace_id INTO source_workspace
              FROM loans_pawnphysicalverificationobservation observation
              JOIN loans_pawnphysicalverificationsession session
                ON session.id = observation.session_id
             WHERE observation.id = NEW.source_verification_observation_id;
        END IF;
        IF source_workspace IS NULL OR source_workspace <> NEW.workspace_id THEN
            RAISE EXCEPTION 'Operational notice source must belong to its workspace.';
        END IF;
        RETURN NEW;
    END IF;
    IF OLD.notification_event_id IS NULL AND OLD.notification_job_id IS NULL
       AND NEW.notification_event_id IS NOT NULL AND NEW.notification_job_id IS NOT NULL
       AND OLD.workspace_id = NEW.workspace_id
       AND OLD.notice_kind = NEW.notice_kind
       AND OLD.request_key = NEW.request_key
       AND OLD.scheduled_for = NEW.scheduled_for
       AND OLD.recipient_name = NEW.recipient_name
       AND OLD.recipient_email = NEW.recipient_email
       AND OLD.payload_snapshot = NEW.payload_snapshot
       AND OLD.source_license_id IS NOT DISTINCT FROM NEW.source_license_id
       AND OLD.source_verification_observation_id IS NOT DISTINCT FROM NEW.source_verification_observation_id
       AND OLD.created_by_id IS NOT DISTINCT FROM NEW.created_by_id
       AND OLD.created_at = NEW.created_at THEN
        RETURN NEW;
    END IF;
    RAISE EXCEPTION 'Loans operational notice intents are immutable.';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER loans_operational_notice_guard_trigger
BEFORE INSERT OR UPDATE OR DELETE ON loans_loanoperationalnotice
FOR EACH ROW EXECUTE FUNCTION loans_operational_notice_guard();
""",
            reverse_sql=r"""
DROP TRIGGER IF EXISTS loans_operational_notice_guard_trigger ON loans_loanoperationalnotice;
DROP FUNCTION IF EXISTS loans_operational_notice_guard();
""",
        ),
    ]
