# Generated by Django 6.1.1 on 2026-10-01 12:47

import apps.tenant_apps.loans.models.khata
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from apps.tenancy.rls import EnableWorkspaceRLS
from importlib import import_module


# Reuse the frozen previous migration, never live application code.
PREVIOUS_GUARD = import_module("apps.tenant_apps.loans.migrations.0033_khata_foundation").Migration.operations[-1].sql.split(
    "CREATE TRIGGER loans_khata_series_guard")[0].replace("CREATE FUNCTION", "CREATE OR REPLACE FUNCTION", 1)
OLD_UPDATE = PREVIOUS_GUARD[PREVIOUS_GUARD.index("IF OLD.state <> 'DRAFT'"):PREVIOUS_GUARD.index("\n                ELSE\n                  SELECT * INTO series_row")]
NEW_UPDATE = """
                  IF NEW.state = 'CANCELLED' THEN
                    IF OLD.state NOT IN ('DRAFT','APPROVED') OR OLD.opened_on IS NOT NULL
                      OR (to_jsonb(NEW) - ARRAY['state','cancelled_at','cancelled_by_id','cancellation_reason'])
                         IS DISTINCT FROM (to_jsonb(OLD) - ARRAY['state','cancelled_at','cancelled_by_id','cancellation_reason'])
                      OR btrim(NEW.cancellation_reason) = ''
                      OR EXISTS (SELECT 1 FROM loans_khatacollateralitem i WHERE i.account_id=OLD.id
                        AND NOT EXISTS (SELECT 1 FROM loans_khataoperation o WHERE o.item_id=i.id AND o.kind='RETURN'))
                    THEN RAISE EXCEPTION 'Return unopened collateral before cancelling; active khatas cannot be cancelled'; END IF;
                  ELSE
                    IF OLD.state = 'CANCELLED'
                      OR (to_jsonb(NEW) - ARRAY['state','opened_on']) IS DISTINCT FROM (to_jsonb(OLD) - ARRAY['state','opened_on'])
                      OR NEW.state <> (CASE WHEN EXISTS (SELECT 1 FROM loans_khataoperation WHERE account_id=OLD.id AND kind='WITHDRAW')
                           THEN 'ACTIVE' ELSE 'APPROVED' END)
                      OR NEW.opened_on IS DISTINCT FROM (SELECT min(business_date) FROM loans_khataoperation WHERE account_id=OLD.id AND kind='WITHDRAW')
                      OR NOT EXISTS (SELECT 1 FROM loans_khataoperation WHERE account_id=OLD.id AND kind='APPROVE')
                    THEN RAISE EXCEPTION 'Khata lifecycle requires matching source operations'; END IF;
                  END IF;
"""
OPENING_GUARD = PREVIOUS_GUARD.replace(OLD_UPDATE, NEW_UPDATE).replace(
    "IF parent_row.state <> 'DRAFT' THEN", "IF parent_row.state NOT IN ('DRAFT','APPROVED') THEN")


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0033_khata_foundation'),
        ('orgs', '0010_storage_inventory'),
        ('party', '0003_party_photo_gallery'),
        ('rates', '0004_rate_daily_confirmation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KhataCollateralItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('metal', models.CharField(choices=[('GOLD', 'Gold'), ('SILVER', 'Silver')], max_length=6)),
                ('quantity', models.PositiveIntegerField()),
                ('gross_weight', models.DecimalField(decimal_places=3, max_digits=12)),
                ('net_weight', models.DecimalField(decimal_places=3, max_digits=12)),
                ('purity', models.DecimalField(decimal_places=4, max_digits=7)),
                ('storage_reference', models.CharField(max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='KhataCollateralPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to=apps.tenant_apps.loans.models.khata.khata_photo_upload_to)),
                ('sha256', models.CharField(max_length=64)),
                ('byte_size', models.PositiveIntegerField()),
                ('mime_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='KhataCollateralValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('rate_evidence', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='KhataOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('APPROVE', 'Approve opening'), ('WITHDRAW', 'Withdrawal'), ('DEPOSIT', 'Collateral received'), ('RETURN', 'Unopened collateral returned'), ('PHOTO', 'Collateral photograph')], max_length=8)),
                ('business_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('request_key', models.UUIDField()),
                ('request_sha256', models.CharField(max_length=64)),
                ('evidence', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('sequence',),
            },
        ),
        migrations.CreateModel(
            name='KhataPolicyRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('exchange', models.CharField(choices=[('WARN', 'Warn'), ('BLOCK', 'Block')], max_length=5)),
                ('overdue', models.CharField(choices=[('WARN', 'Warn'), ('BLOCK', 'Block')], max_length=5)),
                ('reason', models.TextField()),
                ('request_key', models.UUIDField()),
                ('request_sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='khataaccount',
            name='khata_account_draft_only',
        ),
        migrations.AddField(
            model_name='khataaccount',
            name='opened_on',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='khataaccount',
            name='state',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='khataaccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancellation_reason', ''), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('opened_on__isnull', True), ('state__in', ('DRAFT', 'APPROVED'))), models.Q(('cancellation_reason', ''), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('opened_on__isnull', False), ('state', 'ACTIVE')), models.Q(('cancelled_at__isnull', False), ('cancelled_by__isnull', False), ('opened_on__isnull', True), ('state', 'CANCELLED'), models.Q(('cancellation_reason', ''), _negated=True)), _connector='OR'), name='khata_account_state_valid'),
        ),
        migrations.AddField(
            model_name='khatacollateralitem',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collateral', to='loans.khataaccount'),
        ),
        migrations.AddField(
            model_name='khatacollateralitem',
            name='workspace',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='khatacollateralphoto',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='loans.khatacollateralitem'),
        ),
        migrations.AddField(
            model_name='khatacollateralphoto',
            name='workspace',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='khatacollateralvaluation',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valuations', to='loans.khatacollateralitem'),
        ),
        migrations.AddField(
            model_name='khatacollateralvaluation',
            name='rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rates.rate'),
        ),
        migrations.AddField(
            model_name='khatacollateralvaluation',
            name='workspace',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='khataoperation',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='loans.khataaccount'),
        ),
        migrations.AddField(
            model_name='khataoperation',
            name='agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='loans.khataagreementrevision'),
        ),
        migrations.AddField(
            model_name='khataoperation',
            name='approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='loans.khataoperation'),
        ),
        migrations.AddField(
            model_name='khataoperation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='khataoperation',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='loans.khatacollateralitem'),
        ),
        migrations.AddField(
            model_name='khataoperation',
            name='workspace',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='khatacollateralvaluation',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valuations', to='loans.khataoperation'),
        ),
        migrations.AddField(
            model_name='khatacollateralphoto',
            name='operation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='photo', to='loans.khataoperation'),
        ),
        migrations.AddField(
            model_name='khatacollateralitem',
            name='received_operation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='received_item', to='loans.khataoperation'),
        ),
        migrations.AddField(
            model_name='khatapolicyrevision',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='khatapolicyrevision',
            name='workspace',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='khataoperation',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='loans.khatapolicyrevision'),
        ),
        migrations.AddConstraint(
            model_name='khatacollateralvaluation',
            constraint=models.UniqueConstraint(fields=('operation', 'item'), name='khata_valuation_item_uniq'),
        ),
        migrations.AddConstraint(
            model_name='khatacollateralvaluation',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', 0)), name='khata_valuation_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='khatacollateralphoto',
            constraint=models.CheckConstraint(condition=models.Q(('byte_size__gte', 1), ('byte_size__lte', 10485760), ('mime_type__in', ('image/jpeg', 'image/png'))), name='khata_photo_values_valid'),
        ),
        migrations.AddConstraint(
            model_name='khatacollateralitem',
            constraint=models.CheckConstraint(condition=models.Q(('gross_weight__gte', models.F('net_weight')), ('metal__in', ('GOLD', 'SILVER')), ('net_weight__gt', 0), ('purity__gt', 0), ('purity__lte', 100), ('quantity__gte', 1)), name='khata_item_values_valid'),
        ),
        migrations.AddConstraint(
            model_name='khatapolicyrevision',
            constraint=models.UniqueConstraint(fields=('workspace', 'number'), name='khata_policy_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='khatapolicyrevision',
            constraint=models.UniqueConstraint(fields=('workspace', 'request_key'), name='khata_policy_request_uniq'),
        ),
        migrations.AddConstraint(
            model_name='khatapolicyrevision',
            constraint=models.CheckConstraint(condition=models.Q(('exchange__in', ('WARN', 'BLOCK')), ('number__gte', 1), ('overdue__in', ('WARN', 'BLOCK'))), name='khata_policy_values_valid'),
        ),
        migrations.AddConstraint(
            model_name='khataoperation',
            constraint=models.UniqueConstraint(fields=('account', 'sequence'), name='khata_op_sequence_uniq'),
        ),
        migrations.AddConstraint(
            model_name='khataoperation',
            constraint=models.UniqueConstraint(fields=('workspace', 'request_key'), name='khata_op_request_uniq'),
        ),
        migrations.AddConstraint(
            model_name='khataoperation',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'RETURN')), fields=('item',), name='khata_item_return_once'),
        ),
        migrations.AddConstraint(
            model_name='khataoperation',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gte', 1), models.Q(models.Q(('agreement__isnull', False), ('amount__gt', 0), ('approval__isnull', False), ('item__isnull', True), ('kind', 'WITHDRAW')), models.Q(('agreement__isnull', False), ('amount', 0), ('approval__isnull', True), ('item__isnull', True), ('kind', 'APPROVE')), models.Q(('agreement__isnull', True), ('amount', 0), ('approval__isnull', True), ('item__isnull', True), ('kind', 'DEPOSIT')), models.Q(('agreement__isnull', True), ('amount', 0), ('approval__isnull', True), ('item__isnull', False), ('kind__in', ('RETURN', 'PHOTO'))), _connector='OR')), name='khata_op_shape_valid'),
        ),
    ]

    operations += [
        EnableWorkspaceRLS('KhataPolicyRevision'),
        EnableWorkspaceRLS('KhataOperation'),
        EnableWorkspaceRLS('KhataCollateralItem'),
        EnableWorkspaceRLS('KhataCollateralValuation'),
        EnableWorkspaceRLS('KhataCollateralPhoto'),
        migrations.RunSQL(OPENING_GUARD, PREVIOUS_GUARD),
        migrations.RunSQL(
            r"""
            CREATE FUNCTION loans_khata_opening_guard() RETURNS trigger LANGUAGE plpgsql AS $$
            DECLARE a loans_khataaccount%ROWTYPE; op loans_khataoperation%ROWTYPE;
              item_row loans_khatacollateralitem%ROWTYPE; terms loans_khataagreementrevision%ROWTYPE;
              quote rates_rate%ROWTYPE; previous integer; principal numeric;
            BEGIN
              IF TG_OP <> 'INSERT' THEN RAISE EXCEPTION 'Khata operation/custody evidence is immutable'; END IF;
              IF TG_TABLE_NAME = 'loans_khatapolicyrevision' THEN
                PERFORM id FROM orgs_company WHERE id=NEW.workspace_id FOR UPDATE;
                SELECT COALESCE(max(number),0) INTO previous FROM loans_khatapolicyrevision WHERE workspace_id=NEW.workspace_id;
                IF NEW.number <> previous+1 OR btrim(NEW.reason) = '' THEN RAISE EXCEPTION 'Invalid policy revision'; END IF;
              ELSIF TG_TABLE_NAME = 'loans_khataoperation' THEN
                SELECT * INTO a FROM loans_khataaccount WHERE id=NEW.account_id FOR UPDATE;
                IF a.id IS NULL OR a.workspace_id <> NEW.workspace_id OR a.state='CANCELLED'
                THEN RAISE EXCEPTION 'Khata operation account scope/state mismatch'; END IF;
                SELECT COALESCE(max(sequence),0) INTO previous FROM loans_khataoperation WHERE account_id=a.id;
                IF NEW.sequence <> previous+1 OR jsonb_typeof(NEW.evidence) <> 'object' OR NEW.amount='NaN'::numeric
                THEN RAISE EXCEPTION 'Invalid khata operation sequence/evidence'; END IF;
                IF NEW.policy_id IS NOT NULL AND NOT EXISTS (
                  SELECT 1 FROM loans_khatapolicyrevision WHERE id=NEW.policy_id AND workspace_id=NEW.workspace_id)
                THEN RAISE EXCEPTION 'Khata policy Workspace mismatch'; END IF;
                IF NEW.agreement_id IS NOT NULL THEN
                  SELECT * INTO terms FROM loans_khataagreementrevision WHERE id=NEW.agreement_id;
                  IF terms.id IS NULL OR terms.account_id <> a.id OR terms.workspace_id <> NEW.workspace_id
                  THEN RAISE EXCEPTION 'Khata agreement scope mismatch'; END IF;
                END IF;
                IF NEW.item_id IS NOT NULL THEN
                  SELECT * INTO item_row FROM loans_khatacollateralitem WHERE id=NEW.item_id;
                  IF item_row.id IS NULL OR item_row.account_id <> a.id OR item_row.workspace_id <> NEW.workspace_id
                    OR EXISTS (SELECT 1 FROM loans_khataoperation WHERE item_id=NEW.item_id AND kind='RETURN')
                  THEN RAISE EXCEPTION 'Khata item scope/custody mismatch'; END IF;
                END IF;
                IF NEW.kind='APPROVE' THEN
                  IF a.state NOT IN ('DRAFT','APPROVED') OR terms.intended_on <> NEW.business_date
                    OR terms.number <> (SELECT max(number) FROM loans_khataagreementrevision WHERE account_id=a.id)
                  THEN RAISE EXCEPTION 'Opening approval requires current unopened terms'; END IF;
                ELSIF NEW.kind='WITHDRAW' THEN
                  SELECT * INTO op FROM loans_khataoperation WHERE id=NEW.approval_id;
                  IF a.state NOT IN ('APPROVED','ACTIVE') OR op.id IS NULL OR op.account_id <> a.id
                    OR op.workspace_id <> NEW.workspace_id OR op.kind <> 'APPROVE' OR op.agreement_id <> NEW.agreement_id
                    OR op.sequence <> (SELECT max(sequence) FROM loans_khataoperation WHERE account_id=a.id AND kind='APPROVE')
                    OR terms.number <> (SELECT max(number) FROM loans_khataagreementrevision WHERE account_id=a.id)
                    OR (a.opened_on IS NULL AND op.business_date <> NEW.business_date)
                    OR (a.opened_on IS NOT NULL AND NEW.business_date < a.opened_on)
                  THEN RAISE EXCEPTION 'Withdrawal requires current approval'; END IF;
                  SELECT COALESCE(sum(amount),0) INTO principal FROM loans_khataoperation WHERE account_id=a.id AND kind='WITHDRAW';
                  IF principal+NEW.amount > terms.agreed_limit THEN RAISE EXCEPTION 'Khata withdrawal exceeds limit'; END IF;
                ELSIF NEW.kind='RETURN' AND a.opened_on IS NOT NULL THEN
                  RAISE EXCEPTION 'Active collateral return requires reduction/exchange/settlement';
                END IF;
              ELSIF TG_TABLE_NAME = 'loans_khatacollateralitem' THEN
                SELECT * INTO op FROM loans_khataoperation WHERE id=NEW.received_operation_id;
                IF op.id IS NULL OR op.workspace_id <> NEW.workspace_id OR op.account_id <> NEW.account_id OR op.kind <> 'DEPOSIT'
                  OR btrim(NEW.description)='' OR btrim(NEW.storage_reference)=''
                  OR NEW.gross_weight='NaN'::numeric OR NEW.net_weight='NaN'::numeric OR NEW.purity='NaN'::numeric
                THEN RAISE EXCEPTION 'Invalid collateral receipt/source'; END IF;
              ELSE
                SELECT * INTO op FROM loans_khataoperation WHERE id=NEW.operation_id;
                SELECT * INTO item_row FROM loans_khatacollateralitem WHERE id=NEW.item_id;
                IF op.id IS NULL OR item_row.id IS NULL OR op.workspace_id <> NEW.workspace_id
                  OR item_row.workspace_id <> NEW.workspace_id OR op.account_id <> item_row.account_id
                  OR EXISTS (SELECT 1 FROM loans_khataoperation WHERE item_id=NEW.item_id AND kind='RETURN')
                THEN RAISE EXCEPTION 'Khata collateral evidence scope/custody mismatch'; END IF;
                IF TG_TABLE_NAME = 'loans_khatacollateralphoto' THEN
                  IF op.kind <> 'PHOTO' OR op.item_id <> NEW.item_id OR NEW.file NOT LIKE 'loans/khata/' || NEW.workspace_id || '/%'
                    OR NEW.sha256 !~ '^[a-f0-9]{64}$'
                  THEN RAISE EXCEPTION 'Invalid khata photo evidence'; END IF;
                ELSE
                  SELECT * INTO quote FROM rates_rate WHERE id=NEW.rate_id;
                  IF op.kind NOT IN ('APPROVE','WITHDRAW') OR quote.id IS NULL OR quote.workspace_id <> NEW.workspace_id
                    OR upper(quote.metal) <> item_row.metal OR quote.currency <> 'INR' OR quote.purity <> '24k'
                    OR quote.is_withdrawal OR quote.buying_rate <= 0 OR quote.buying_rate='NaN'::numeric
                    OR NEW.value <> floor(quote.buying_rate * item_row.net_weight * item_row.purity) / 100
                    OR NEW.value='NaN'::numeric
                  THEN RAISE EXCEPTION 'Invalid khata price valuation'; END IF;
                  IF jsonb_typeof(op.evidence->'valuations') IS DISTINCT FROM 'array' OR NOT EXISTS (
                    SELECT 1 FROM jsonb_array_elements(op.evidence->'valuations') e
                    WHERE (e->>'item_id')::bigint=NEW.item_id AND (e->>'rate_id')::bigint=NEW.rate_id
                      AND (e->>'value')::numeric=NEW.value AND e->'rate_evidence'=NEW.rate_evidence)
                  THEN RAISE EXCEPTION 'Valuation must match the frozen operation snapshot'; END IF;
                END IF;
              END IF;
              RETURN NEW;
            END $$;
            CREATE FUNCTION loans_khata_project_opening() RETURNS trigger LANGUAGE plpgsql AS $$
            BEGIN
              IF NEW.kind='APPROVE' THEN
                UPDATE loans_khataaccount SET state='APPROVED' WHERE id=NEW.account_id;
              ELSIF NEW.kind='WITHDRAW' THEN
                UPDATE loans_khataaccount SET state='ACTIVE', opened_on=COALESCE(opened_on,NEW.business_date) WHERE id=NEW.account_id;
              END IF;
              RETURN NEW;
            END $$;
            CREATE FUNCTION loans_khata_complete_opening() RETURNS trigger LANGUAGE plpgsql AS $$
            DECLARE total numeric; principal numeric; fraction numeric;
            BEGIN
              IF NEW.kind IN ('APPROVE','WITHDRAW') THEN
                IF jsonb_typeof(NEW.evidence->'valuations') IS DISTINCT FROM 'array'
                  OR jsonb_array_length(NEW.evidence->'valuations') <> (SELECT count(*) FROM loans_khatacollateralvaluation WHERE operation_id=NEW.id)
                  OR NOT EXISTS (SELECT 1 FROM loans_khatacollateralvaluation WHERE operation_id=NEW.id)
                  OR EXISTS (SELECT 1 FROM loans_khatacollateralitem i WHERE i.account_id=NEW.account_id
                    AND i.received_operation_id IN (SELECT id FROM loans_khataoperation WHERE account_id=NEW.account_id AND sequence<=NEW.sequence)
                    AND NOT EXISTS (SELECT 1 FROM loans_khataoperation o WHERE o.item_id=i.id AND o.kind='RETURN' AND o.sequence<=NEW.sequence)
                    AND NOT EXISTS (SELECT 1 FROM loans_khatacollateralvaluation v WHERE v.operation_id=NEW.id AND v.item_id=i.id))
                THEN RAISE EXCEPTION 'Khata valuation must cover every held item'; END IF;
                IF NEW.kind='WITHDRAW' THEN
                  SELECT sum(value) INTO total FROM loans_khatacollateralvaluation WHERE operation_id=NEW.id;
                  SELECT ltv INTO fraction FROM loans_khataagreementrevision WHERE id=NEW.agreement_id;
                  SELECT sum(amount) INTO principal FROM loans_khataoperation WHERE account_id=NEW.account_id AND kind='WITHDRAW' AND sequence<=NEW.sequence;
                  IF principal > floor(total*fraction*100)/100 THEN RAISE EXCEPTION 'Khata payout exceeds collateral LTV'; END IF;
                END IF;
              ELSIF NEW.kind='DEPOSIT' AND NOT EXISTS (SELECT 1 FROM loans_khatacollateralitem WHERE received_operation_id=NEW.id) THEN
                RAISE EXCEPTION 'Deposit requires actual item evidence';
              ELSIF NEW.kind='PHOTO' AND NOT EXISTS (SELECT 1 FROM loans_khatacollateralphoto WHERE operation_id=NEW.id) THEN
                RAISE EXCEPTION 'Photo action requires file evidence';
              END IF;
              RETURN NEW;
            END $$;
            CREATE TRIGGER khata_policy_guard BEFORE INSERT OR UPDATE OR DELETE ON loans_khatapolicyrevision FOR EACH ROW EXECUTE FUNCTION loans_khata_opening_guard();
            CREATE TRIGGER khata_operation_guard BEFORE INSERT OR UPDATE OR DELETE ON loans_khataoperation FOR EACH ROW EXECUTE FUNCTION loans_khata_opening_guard();
            CREATE TRIGGER khata_item_guard BEFORE INSERT OR UPDATE OR DELETE ON loans_khatacollateralitem FOR EACH ROW EXECUTE FUNCTION loans_khata_opening_guard();
            CREATE TRIGGER khata_valuation_guard BEFORE INSERT OR UPDATE OR DELETE ON loans_khatacollateralvaluation FOR EACH ROW EXECUTE FUNCTION loans_khata_opening_guard();
            CREATE TRIGGER khata_photo_guard BEFORE INSERT OR UPDATE OR DELETE ON loans_khatacollateralphoto FOR EACH ROW EXECUTE FUNCTION loans_khata_opening_guard();
            CREATE TRIGGER khata_opening_projection AFTER INSERT ON loans_khataoperation FOR EACH ROW EXECUTE FUNCTION loans_khata_project_opening();
            CREATE CONSTRAINT TRIGGER khata_opening_complete AFTER INSERT ON loans_khataoperation DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION loans_khata_complete_opening();
            """,
            """
            DROP TRIGGER khata_opening_complete ON loans_khataoperation;
            DROP TRIGGER khata_opening_projection ON loans_khataoperation;
            DROP TRIGGER khata_photo_guard ON loans_khatacollateralphoto;
            DROP TRIGGER khata_valuation_guard ON loans_khatacollateralvaluation;
            DROP TRIGGER khata_item_guard ON loans_khatacollateralitem;
            DROP TRIGGER khata_operation_guard ON loans_khataoperation;
            DROP TRIGGER khata_policy_guard ON loans_khatapolicyrevision;
            DROP FUNCTION loans_khata_complete_opening();
            DROP FUNCTION loans_khata_project_opening();
            DROP FUNCTION loans_khata_opening_guard();
            """,
        ),
    ]
