# Generated by Django 6.0.3 on 2026-08-09

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0033_loanoperationalnotice"),
    ]

    operations = [
        migrations.AddField(
            model_name="pawnloaneconomicpolicy",
            name="accounting_recognition",
            field=models.CharField(
                choices=[("CASH", "Cash"), ("ACCRUAL", "Accrual")],
                default="CASH",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="pawnloaneconomicpolicy",
            name="capitalization_interval_periods",
            field=models.PositiveSmallIntegerField(default=12),
        ),
        migrations.AddField(
            model_name="pawnloaneconomicpolicy",
            name="currency_quantum",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.01"),
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="pawnloaneconomicpolicy",
            name="interest_method",
            field=models.CharField(
                choices=[("SIMPLE", "Simple"), ("COMPOUND", "Compound")],
                default="SIMPLE",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="pawnloaneconomicpolicy",
            name="partial_month_cutoff_days",
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name="pawnloaneconomicpolicy",
            name="partial_month_lower_fraction",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.5"),
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="pawnloaneconomicpolicy",
            name="partial_month_method",
            field=models.CharField(
                choices=[("FULL_MONTH", "Full Month"), ("SLAB", "Slab")],
                default="FULL_MONTH",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="pawnloaneconomicpolicy",
            name="rounding_method",
            field=models.CharField(
                choices=[
                    ("PER_ACCRUAL_PERIOD", "Per Accrual Period"),
                ],
                default="PER_ACCRUAL_PERIOD",
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="pawnloaneconomicpolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("partial_month_cutoff_days__gte", 1),
                    ("partial_month_cutoff_days__lte", 30),
                ),
                name="loans_econ_partial_cutoff_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="pawnloaneconomicpolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("partial_month_lower_fraction__gt", 0),
                    ("partial_month_lower_fraction__lte", 1),
                ),
                name="loans_econ_partial_fraction_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="pawnloaneconomicpolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(("capitalization_interval_periods__gte", 1)),
                name="loans_econ_cap_interval_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="pawnloaneconomicpolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(("currency_quantum__gt", 0)),
                name="loans_econ_currency_quantum_positive",
            ),
        ),
    ]

