# Generated by Django 6.1.1 on 2026-10-01 13:19

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models
from apps.tenancy.rls import EnableWorkspaceRLS


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0034_khata_opening'),
        ('orgs', '0010_storage_inventory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KhataInterestAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='KhataInterestPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('start_on', models.DateField()),
                ('end_on', models.DateField()),
                ('due_on', models.DateField()),
                ('actual_charge', models.DecimalField(decimal_places=2, max_digits=18)),
                ('minimum_adjustment', models.DecimalField(decimal_places=2, max_digits=18)),
                ('charge', models.DecimalField(decimal_places=2, max_digits=18)),
                ('contract_version', models.CharField(default='KHATA-1', editable=False, max_length=16)),
            ],
            options={
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='KhataInterestSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('start_on', models.DateField()),
                ('end_on', models.DateField()),
                ('period_days', models.PositiveSmallIntegerField()),
                ('exact_numerator', models.DecimalField(decimal_places=0, max_digits=60)),
                ('exact_denominator', models.DecimalField(decimal_places=0, max_digits=60)),
            ],
            options={
                'ordering': ('sequence',),
            },
        ),
        migrations.RemoveConstraint(
            model_name='khataoperation',
            name='khata_op_shape_valid',
        ),
        migrations.AlterField(
            model_name='khataoperation',
            name='kind',
            field=models.CharField(choices=[('APPROVE', 'Approve opening'), ('WITHDRAW', 'Withdrawal'), ('DEPOSIT', 'Collateral received'), ('RETURN', 'Unopened collateral returned'), ('PHOTO', 'Collateral photograph'), ('ACCRUE', 'Finalize completed interest periods'), ('INTEREST', 'Interest received')], max_length=8),
        ),
        migrations.AddConstraint(
            model_name='khataoperation',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gte', 1), models.Q(models.Q(('agreement__isnull', False), ('amount__gt', 0), ('approval__isnull', False), ('item__isnull', True), ('kind', 'WITHDRAW')), models.Q(('agreement__isnull', False), ('amount', 0), ('approval__isnull', True), ('item__isnull', True), ('kind', 'APPROVE')), models.Q(('agreement__isnull', True), ('amount', 0), ('approval__isnull', True), ('item__isnull', True), ('kind', 'DEPOSIT')), models.Q(('agreement__isnull', True), ('amount', 0), ('approval__isnull', True), ('item__isnull', True), ('kind', 'ACCRUE'), ('policy__isnull', True)), models.Q(('agreement__isnull', True), ('amount__gt', 0), ('approval__isnull', True), ('item__isnull', True), ('kind', 'INTEREST'), ('policy__isnull', True)), models.Q(('agreement__isnull', True), ('amount', 0), ('approval__isnull', True), ('item__isnull', False), ('kind__in', ('RETURN', 'PHOTO'))), _connector='OR')), name='khata_op_shape_valid'),
        ),
        migrations.AddField(
            model_name='khatainterestallocation',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interest_allocations', to='loans.khataoperation'),
        ),
        migrations.AddField(
            model_name='khatainterestallocation',
            name='workspace',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='khatainterestperiod',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interest_periods', to='loans.khataaccount'),
        ),
        migrations.AddField(
            model_name='khatainterestperiod',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interest_periods', to='loans.khataoperation'),
        ),
        migrations.AddField(
            model_name='khatainterestperiod',
            name='workspace',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='khatainterestallocation',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='loans.khatainterestperiod'),
        ),
        migrations.AddField(
            model_name='khatainterestsegment',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interest_segments', to='loans.khataagreementrevision'),
        ),
        migrations.AddField(
            model_name='khatainterestsegment',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='segments', to='loans.khatainterestperiod'),
        ),
        migrations.AddField(
            model_name='khatainterestsegment',
            name='workspace',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddConstraint(
            model_name='khatainterestperiod',
            constraint=models.UniqueConstraint(fields=('account', 'index'), name='khata_interest_period_uniq'),
        ),
        migrations.AddConstraint(
            model_name='khatainterestperiod',
            constraint=models.CheckConstraint(condition=models.Q(('actual_charge__gte', 0), ('contract_version', 'KHATA-1'), ('due_on__gte', models.F('end_on')), ('end_on__gt', models.F('start_on')), ('minimum_adjustment__gte', 0), ('charge', django.db.models.expressions.CombinedExpression(models.F('actual_charge'), '+', models.F('minimum_adjustment')))), name='khata_interest_period_valid'),
        ),
        migrations.AddConstraint(
            model_name='khatainterestallocation',
            constraint=models.UniqueConstraint(fields=('operation', 'period'), name='khata_interest_allocation_uniq'),
        ),
        migrations.AddConstraint(
            model_name='khatainterestallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='khata_interest_allocation_positive'),
        ),
        migrations.AddConstraint(
            model_name='khatainterestsegment',
            constraint=models.UniqueConstraint(fields=('period', 'sequence'), name='khata_interest_segment_uniq'),
        ),
        migrations.AddConstraint(
            model_name='khatainterestsegment',
            constraint=models.CheckConstraint(condition=models.Q(('end_on__gt', models.F('start_on')), ('exact_denominator__gt', 0), ('exact_numerator__gte', 0), ('period_days__gte', 28), ('period_days__lte', 31), ('sequence__gte', 1)), name='khata_interest_segment_valid'),
        ),
        EnableWorkspaceRLS('KhataInterestPeriod'),
        EnableWorkspaceRLS('KhataInterestSegment'),
        EnableWorkspaceRLS('KhataInterestAllocation'),
        migrations.RunSQL(
            r"""
            CREATE FUNCTION loans_khata_interest_guard() RETURNS trigger LANGUAGE plpgsql AS $$
            DECLARE a loans_khataaccount%ROWTYPE; op loans_khataoperation%ROWTYPE;
              first_draw loans_khataoperation%ROWTYPE; terms loans_khataagreementrevision%ROWTYPE;
              period_row loans_khatainterestperiod%ROWTYPE; previous integer;
              paid numeric; received numeric;
            BEGIN
              IF TG_OP <> 'INSERT' THEN RAISE EXCEPTION 'Khata interest evidence is immutable'; END IF;
              IF TG_TABLE_NAME = 'loans_khataoperation' THEN
                IF NEW.kind NOT IN ('ACCRUE','INTEREST') THEN RETURN NEW; END IF;
                SELECT * INTO a FROM loans_khataaccount WHERE id=NEW.account_id FOR UPDATE;
                IF a.id IS NULL OR a.workspace_id <> NEW.workspace_id OR a.state <> 'ACTIVE'
                  OR NEW.business_date < a.opened_on
                  OR NEW.evidence->>'schema' IS DISTINCT FROM 'khata-interest/1'
                THEN RAISE EXCEPTION 'Interest servicing requires an active khata and valid evidence'; END IF;
                IF NEW.kind='ACCRUE' THEN
                  IF jsonb_typeof(NEW.evidence->'periods') IS DISTINCT FROM 'array'
                    OR jsonb_array_length(NEW.evidence->'periods')=0
                  THEN RAISE EXCEPTION 'Accrual requires completed periods'; END IF;
                ELSE
                  IF jsonb_typeof(NEW.evidence->'allocations') IS DISTINCT FROM 'array'
                    OR jsonb_array_length(NEW.evidence->'allocations')=0
                    OR COALESCE(btrim(NEW.evidence->>'payment_reference'),'')=''
                    OR (NEW.evidence->>'amount')::numeric IS DISTINCT FROM NEW.amount
                  THEN RAISE EXCEPTION 'Interest receipt requires allocation and payment evidence'; END IF;
                END IF;
                RETURN NEW;
              END IF;

              IF TG_TABLE_NAME = 'loans_khatainterestsegment' THEN
                SELECT * INTO period_row FROM loans_khatainterestperiod WHERE id=NEW.period_id;
                SELECT * INTO op FROM loans_khataoperation WHERE id=period_row.operation_id;
              ELSE
                SELECT * INTO op FROM loans_khataoperation WHERE id=NEW.operation_id;
              END IF;
              SELECT * INTO a FROM loans_khataaccount WHERE id=op.account_id FOR UPDATE;
              IF op.id IS NULL OR a.id IS NULL OR a.workspace_id <> NEW.workspace_id
                OR op.workspace_id <> NEW.workspace_id
              THEN RAISE EXCEPTION 'Khata interest source Workspace mismatch'; END IF;
              SELECT * INTO first_draw FROM loans_khataoperation
                WHERE account_id=a.id AND kind='WITHDRAW' ORDER BY sequence LIMIT 1;
              SELECT * INTO terms FROM loans_khataagreementrevision WHERE id=first_draw.agreement_id;
              IF first_draw.id IS NULL THEN RAISE EXCEPTION 'Interest requires a first withdrawal'; END IF;

              IF TG_TABLE_NAME = 'loans_khatainterestperiod' THEN
                SELECT COALESCE(max(index),-1) INTO previous FROM loans_khatainterestperiod WHERE account_id=a.id;
                IF op.kind <> 'ACCRUE' OR NEW.account_id <> a.id OR NEW.index <> previous+1
                  OR NEW.start_on <> (a.opened_on + make_interval(months=>NEW.index))::date
                  OR NEW.end_on <> (a.opened_on + make_interval(months=>NEW.index+1))::date
                  OR NEW.due_on <> (a.opened_on + make_interval(months=>CASE WHEN terms.frequency='MONTHLY'
                      THEN NEW.index+1 ELSE (NEW.index/12+1)*12 END))::date
                  OR NEW.end_on > op.business_date
                  OR NEW.actual_charge <> round(terms.agreed_limit * terms.monthly_rate / 100, 2)
                  OR NEW.actual_charge='NaN'::numeric OR NEW.minimum_adjustment <> 0
                  OR NEW.charge <> NEW.actual_charge
                THEN RAISE EXCEPTION 'Invalid completed khata interest period'; END IF;
                IF NOT EXISTS (SELECT 1 FROM jsonb_array_elements(op.evidence->'periods') e
                  WHERE (e->>'index')::integer=NEW.index AND (e->>'start_on')::date=NEW.start_on
                    AND (e->>'end_on')::date=NEW.end_on AND (e->>'due_on')::date=NEW.due_on
                    AND (e->>'actual_charge')::numeric=NEW.actual_charge
                    AND (e->>'minimum_adjustment')::numeric=NEW.minimum_adjustment
                    AND (e->>'charge')::numeric=NEW.charge AND e->>'contract_version'=NEW.contract_version)
                THEN RAISE EXCEPTION 'Period must match frozen accrual evidence'; END IF;
              ELSIF TG_TABLE_NAME = 'loans_khatainterestsegment' THEN
                -- This delivery permits unchanged opening terms only. A later
                -- revision migration must extend these rules before activating revisions.
                IF period_row.workspace_id <> NEW.workspace_id OR op.kind <> 'ACCRUE'
                  OR NEW.agreement_id <> terms.id OR NEW.sequence <> 1
                  OR NEW.start_on <> period_row.start_on OR NEW.end_on <> period_row.end_on
                  OR NEW.period_days <> period_row.end_on-period_row.start_on
                  OR NEW.exact_numerator='NaN'::numeric OR NEW.exact_denominator='NaN'::numeric
                  OR NEW.exact_numerator * 100 <> terms.agreed_limit * terms.monthly_rate * NEW.exact_denominator
                THEN RAISE EXCEPTION 'Invalid khata interest segment/source'; END IF;
                IF NOT EXISTS (SELECT 1 FROM jsonb_array_elements(op.evidence->'periods') e,
                    jsonb_array_elements(e->'segments') s
                  WHERE (e->>'index')::integer=period_row.index AND (s->>'sequence')::integer=NEW.sequence
                    AND (s->>'agreement_id')::bigint=NEW.agreement_id
                    AND (s->>'start_on')::date=NEW.start_on AND (s->>'end_on')::date=NEW.end_on
                    AND (s->>'period_days')::integer=NEW.period_days
                    AND (s->>'exact_numerator')::numeric=NEW.exact_numerator
                    AND (s->>'exact_denominator')::numeric=NEW.exact_denominator)
                THEN RAISE EXCEPTION 'Segment must match frozen accrual evidence'; END IF;
              ELSE
                SELECT * INTO period_row FROM loans_khatainterestperiod WHERE id=NEW.period_id;
                IF period_row.id IS NULL OR period_row.workspace_id <> NEW.workspace_id
                  OR period_row.account_id <> a.id OR op.kind <> 'INTEREST'
                  OR period_row.due_on > op.business_date OR NEW.amount='NaN'::numeric
                  OR (SELECT sequence FROM loans_khataoperation WHERE id=period_row.operation_id) >= op.sequence
                THEN RAISE EXCEPTION 'Interest allocation requires this account''s finalized due period'; END IF;
                SELECT COALESCE(sum(amount),0) INTO paid FROM loans_khatainterestallocation WHERE period_id=NEW.period_id;
                SELECT COALESCE(sum(amount),0) INTO received FROM loans_khatainterestallocation WHERE operation_id=op.id;
                IF NEW.amount+paid > period_row.charge OR NEW.amount+received > op.amount
                THEN RAISE EXCEPTION 'Interest allocation exceeds unpaid charge or receipt'; END IF;
                IF EXISTS (SELECT 1 FROM loans_khatainterestperiod p WHERE p.account_id=a.id
                  AND (p.due_on,p.index) < (period_row.due_on,period_row.index)
                  AND p.charge > COALESCE((SELECT sum(amount) FROM loans_khatainterestallocation WHERE period_id=p.id),0))
                THEN RAISE EXCEPTION 'Allocate interest to oldest unpaid dues first'; END IF;
                IF NOT EXISTS (SELECT 1 FROM jsonb_array_elements(op.evidence->'allocations') e
                  WHERE (e->>'period_id')::bigint=NEW.period_id AND (e->>'index')::integer=period_row.index
                    AND (e->>'amount')::numeric=NEW.amount)
                THEN RAISE EXCEPTION 'Allocation must match frozen receipt evidence'; END IF;
              END IF;
              RETURN NEW;
            END $$;

            CREATE FUNCTION loans_khata_interest_complete() RETURNS trigger LANGUAGE plpgsql AS $$
            DECLARE opening date;
            BEGIN
              IF NEW.kind='ACCRUE' THEN
                IF jsonb_array_length(NEW.evidence->'periods') <> (SELECT count(*) FROM loans_khatainterestperiod WHERE operation_id=NEW.id)
                  OR EXISTS (SELECT 1 FROM loans_khatainterestperiod p WHERE p.operation_id=NEW.id
                    AND (SELECT count(*) FROM loans_khatainterestsegment s WHERE s.period_id=p.id) <> 1)
                  OR EXISTS (SELECT 1 FROM jsonb_array_elements(NEW.evidence->'periods') e
                    WHERE jsonb_array_length(e->'segments') <> 1)
                THEN RAISE EXCEPTION 'Accrual must retain every period and exact segment'; END IF;
              ELSIF NEW.kind='INTEREST' THEN
                IF NEW.amount <> COALESCE((SELECT sum(amount) FROM loans_khatainterestallocation WHERE operation_id=NEW.id),0)
                  OR jsonb_array_length(NEW.evidence->'allocations') <> (SELECT count(*) FROM loans_khatainterestallocation WHERE operation_id=NEW.id)
                THEN RAISE EXCEPTION 'Receipt must be fully allocated'; END IF;
                SELECT opened_on INTO opening FROM loans_khataaccount WHERE id=NEW.account_id;
                IF EXISTS (SELECT 1 FROM generate_series(0,
                    (extract(year FROM NEW.business_date)::integer-extract(year FROM opening)::integer)*12
                    +extract(month FROM NEW.business_date)::integer-extract(month FROM opening)::integer) n
                  WHERE (opening+make_interval(months=>n+1))::date <= NEW.business_date
                    AND NOT EXISTS (SELECT 1 FROM loans_khatainterestperiod p
                      JOIN loans_khataoperation o ON o.id=p.operation_id
                      WHERE p.account_id=NEW.account_id AND p.index=n AND o.sequence<NEW.sequence))
                THEN RAISE EXCEPTION 'Finalize completed months before receiving interest'; END IF;
              END IF;
              RETURN NEW;
            END $$;
            CREATE TRIGGER khata_servicing_operation_guard BEFORE INSERT ON loans_khataoperation FOR EACH ROW EXECUTE FUNCTION loans_khata_interest_guard();
            CREATE TRIGGER khata_interest_period_guard BEFORE INSERT OR UPDATE OR DELETE ON loans_khatainterestperiod FOR EACH ROW EXECUTE FUNCTION loans_khata_interest_guard();
            CREATE TRIGGER khata_interest_segment_guard BEFORE INSERT OR UPDATE OR DELETE ON loans_khatainterestsegment FOR EACH ROW EXECUTE FUNCTION loans_khata_interest_guard();
            CREATE TRIGGER khata_interest_allocation_guard BEFORE INSERT OR UPDATE OR DELETE ON loans_khatainterestallocation FOR EACH ROW EXECUTE FUNCTION loans_khata_interest_guard();
            CREATE CONSTRAINT TRIGGER khata_interest_complete AFTER INSERT ON loans_khataoperation DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION loans_khata_interest_complete();
            """,
            """
            DROP TRIGGER khata_interest_complete ON loans_khataoperation;
            DROP TRIGGER khata_interest_allocation_guard ON loans_khatainterestallocation;
            DROP TRIGGER khata_interest_segment_guard ON loans_khatainterestsegment;
            DROP TRIGGER khata_interest_period_guard ON loans_khatainterestperiod;
            DROP TRIGGER khata_servicing_operation_guard ON loans_khataoperation;
            DROP FUNCTION loans_khata_interest_complete();
            DROP FUNCTION loans_khata_interest_guard();
            """,
        ),
    ]
