# Generated by Django 6.0.3 on 2026-08-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0034_pawn_economic_calculation_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandocumentissue',
            name='document_type',
            field=models.CharField(choices=[('loan_ticket', 'Loan ticket'), ('repayment_receipt', 'Repayment receipt'), ('release_memo', 'Release memo'), ('auction_notice', 'Auction notice'), ('auction_recovery', 'Auction recovery memo'), ('renewal', 'Renewal agreement')], max_length=32),
        ),
        migrations.AlterField(
            model_name='loandocumentlayout',
            name='document_type',
            field=models.CharField(choices=[('loan_ticket', 'Loan ticket'), ('repayment_receipt', 'Repayment receipt'), ('release_memo', 'Release memo'), ('auction_notice', 'Auction notice'), ('auction_recovery', 'Auction recovery memo'), ('renewal', 'Renewal agreement')], max_length=32),
        ),
        migrations.AlterField(
            model_name='loandocumentlayoutassignment',
            name='document_type',
            field=models.CharField(choices=[('loan_ticket', 'Loan ticket'), ('repayment_receipt', 'Repayment receipt'), ('release_memo', 'Release memo'), ('auction_notice', 'Auction notice'), ('auction_recovery', 'Auction recovery memo'), ('renewal', 'Renewal agreement')], max_length=32),
        ),
    ]
