# Generated by Django 6.0.3 on 2026-08-10 05:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0035_alter_loandocumentissue_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pawnloanrenewal',
            name='successor_advance_interest',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='pawnloanrenewal',
            name='successor_deducted_fees',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18),
        ),
    ]
