# Generated by Django 6.1.1 on 2026-10-01 13:47

from django.conf import settings
from django.db import migrations, models
from importlib import import_module
import re


# Extend frozen prior migration definitions, never live service/calculator code.
opening = import_module("apps.tenant_apps.loans.migrations.0034_khata_opening")
collection = import_module("apps.tenant_apps.loans.migrations.0035_khata_interest_collection")


def function(sql, name):
    return re.search(r"CREATE FUNCTION " + name + r"\(\) RETURNS trigger.*?END \$\$;", sql, re.S).group().replace(
        "CREATE FUNCTION", "CREATE OR REPLACE FUNCTION", 1)


OLD_FOUNDATION = opening.OPENING_GUARD
OLD_OPENING = function(opening.Migration.operations[-1].sql, "loans_khata_opening_guard")
OLD_COMPLETE = function(opening.Migration.operations[-1].sql, "loans_khata_complete_opening")
OLD_INTEREST = function(collection.Migration.operations[-1].sql, "loans_khata_interest_guard")
OLD_INTEREST_COMPLETE = function(collection.Migration.operations[-1].sql, "loans_khata_interest_complete")

FOUNDATION = OLD_FOUNDATION.replace("parent_row.state NOT IN ('DRAFT','APPROVED')", "parent_row.state NOT IN ('DRAFT','APPROVED','ACTIVE')")
FOUNDATION = FOUNDATION.replace("SELECT COALESCE(MAX(number),0) INTO last_revision", """
                IF parent_row.opened_on IS NOT NULL AND NOT EXISTS (
                  SELECT 1 FROM loans_khataoperation o JOIN loans_khataagreementrevision r ON r.id=o.agreement_id
                  WHERE o.id=(SELECT id FROM loans_khataoperation WHERE account_id=NEW.account_id AND kind='WITHDRAW' ORDER BY sequence LIMIT 1)
                    AND (NEW.ltv,NEW.frequency,NEW.lender_name,NEW.lender_address,NEW.contract_version)
                       =(r.ltv,r.frequency,r.lender_name,r.lender_address,r.contract_version)
                    AND NEW.intended_on>=parent_row.opened_on)
                THEN RAISE EXCEPTION 'Active khata proposals preserve payment frequency, LTV and lender identity'; END IF;
                SELECT COALESCE(MAX(number),0) INTO last_revision""")

withdrawal_start = OLD_OPENING.index("SELECT * INTO op FROM loans_khataoperation WHERE id=NEW.approval_id;")
withdrawal_end = OLD_OPENING.index("ELSIF NEW.kind='RETURN'", withdrawal_start)
old_withdrawal = OLD_OPENING[withdrawal_start:withdrawal_end]
OPENING = OLD_OPENING.replace("previous integer; principal numeric;", "previous integer; principal numeric; position_row record;")
OPENING = OPENING.replace(old_withdrawal, """
                  IF a.opened_on IS NULL THEN
                    """ + old_withdrawal + """
                  ELSE
                    SELECT * INTO position_row FROM loans_khata_position(a.id,NEW.sequence);
                    IF NEW.agreement_id IS DISTINCT FROM position_row.agreement_id
                      OR NEW.approval_id IS DISTINCT FROM position_row.authority_id
                      OR NEW.business_date < (SELECT max(business_date) FROM loans_khataoperation WHERE account_id=a.id AND kind IN ('WITHDRAW','REVISE'))
                    THEN RAISE EXCEPTION 'Withdrawal requires current activated agreement authority'; END IF;
                    IF NEW.amount>position_row.unused OR NEW.amount+position_row.principal>position_row.agreed_limit
                    THEN RAISE EXCEPTION 'Khata withdrawal exceeds unused entitlement or limit'; END IF;
                  END IF;
                """)
COMPLETE = OLD_COMPLETE.replace(
    "SELECT sum(amount) INTO principal FROM loans_khataoperation WHERE account_id=NEW.account_id AND kind='WITHDRAW' AND sequence<=NEW.sequence;",
    "SELECT p.principal INTO principal FROM loans_khata_position(NEW.account_id,NEW.sequence+1) p;")

INTEREST = OLD_INTEREST.replace("paid numeric; received numeric;", "paid numeric; received numeric; expected_row record; actual numeric; floor_charge numeric;")
INTEREST = INTEREST.replace("SELECT COALESCE(max(index),-1) INTO previous", """
                SELECT loans_khata_round_fraction(sum(s.exact_numerator),max(s.exact_denominator)) INTO actual
                  FROM loans_khata_segments(a.id,op.sequence,NEW.start_on,NEW.end_on) s;
                floor_charge := CASE WHEN NEW.index=0 THEN round(terms.agreed_limit*terms.monthly_rate/100,2) ELSE 0 END;
                SELECT COALESCE(max(index),-1) INTO previous""")
INTEREST = INTEREST.replace("NEW.actual_charge <> round(terms.agreed_limit * terms.monthly_rate / 100, 2)", "NEW.actual_charge IS DISTINCT FROM actual")
INTEREST = INTEREST.replace("NEW.minimum_adjustment <> 0", "NEW.minimum_adjustment IS DISTINCT FROM greatest(actual,floor_charge)-actual")
INTEREST = INTEREST.replace("NEW.charge <> NEW.actual_charge", "NEW.charge IS DISTINCT FROM greatest(actual,floor_charge)")
segment_start = INTEREST.index("-- This delivery permits unchanged opening terms only.")
segment_end = INTEREST.index("IF NOT EXISTS (SELECT 1 FROM jsonb_array_elements(op.evidence->'periods') e,", segment_start)
INTEREST = INTEREST[:segment_start] + """
                SELECT * INTO expected_row FROM loans_khata_segments(a.id,op.sequence,period_row.start_on,period_row.end_on)
                  WHERE segment_sequence=NEW.sequence;
                IF expected_row.agreement_id IS NULL OR period_row.workspace_id <> NEW.workspace_id OR op.kind <> 'ACCRUE'
                  OR NEW.agreement_id <> expected_row.agreement_id
                  OR NEW.start_on <> expected_row.start_on OR NEW.end_on <> expected_row.end_on
                  OR NEW.period_days <> period_row.end_on-period_row.start_on
                  OR NEW.exact_numerator='NaN'::numeric OR NEW.exact_denominator='NaN'::numeric
                  OR NEW.exact_numerator * expected_row.exact_denominator <> expected_row.exact_numerator * NEW.exact_denominator
                THEN RAISE EXCEPTION 'Invalid khata interest segment/source'; END IF;
                """ + INTEREST[segment_end:]
INTEREST_COMPLETE = OLD_INTEREST_COMPLETE.replace(
    "(SELECT count(*) FROM loans_khatainterestsegment s WHERE s.period_id=p.id) <> 1",
    "(SELECT count(*) FROM loans_khatainterestsegment s WHERE s.period_id=p.id) <> (SELECT count(*) FROM loans_khata_segments(p.account_id,NEW.sequence,p.start_on,p.end_on))")
INTEREST_COMPLETE = INTEREST_COMPLETE.replace("jsonb_array_length(e->'segments') <> 1", """
                    jsonb_array_length(e->'segments') IS DISTINCT FROM (SELECT count(*) FROM loans_khatainterestsegment s
                      JOIN loans_khatainterestperiod p ON p.id=s.period_id WHERE p.operation_id=NEW.id AND p.index=(e->>'index')::integer)""")

HELPERS = r"""
CREATE FUNCTION loans_khata_position(account_key bigint, before_sequence integer)
RETURNS TABLE (agreed_limit numeric, principal numeric, unused numeric, agreement_id bigint, authority_id bigint)
LANGUAGE plpgsql STABLE AS $$
DECLARE event record;
BEGIN
  principal := 0; unused := 0;
  FOR event IN SELECT o.*, r.agreed_limit AS new_limit FROM loans_khataoperation o
    JOIN loans_khataagreementrevision r ON r.id=o.agreement_id
    WHERE o.account_id=account_key AND o.sequence<before_sequence AND o.kind IN ('WITHDRAW','REVISE') ORDER BY o.sequence
  LOOP
    IF event.kind='WITHDRAW' THEN
      IF agreed_limit IS NULL THEN
        agreed_limit:=event.new_limit; unused:=agreed_limit; agreement_id:=event.agreement_id; authority_id:=event.approval_id;
      END IF;
      principal:=principal+event.amount; unused:=unused-event.amount;
    ELSE
      unused:=greatest(0,unused+event.new_limit-agreed_limit); principal:=principal-event.amount;
      agreed_limit:=event.new_limit; agreement_id:=event.agreement_id; authority_id:=event.approval_id;
    END IF;
  END LOOP;
  RETURN NEXT;
END $$;

CREATE FUNCTION loans_khata_round_fraction(n numeric,d numeric) RETURNS numeric
LANGUAGE sql IMMUTABLE STRICT AS $$
  SELECT (div(n*100,d)+CASE WHEN mod(n*100,d)*2>=d THEN 1 ELSE 0 END)/100;
$$;

CREATE FUNCTION loans_khata_segments(account_key bigint,before_sequence integer,period_start date,period_end date)
RETURNS TABLE (segment_sequence integer,agreement_id bigint,start_on date,end_on date,exact_numerator numeric,exact_denominator numeric)
LANGUAGE sql STABLE AS $$
  WITH first_draw AS (
    SELECT o.* FROM loans_khataoperation o WHERE o.account_id=account_key AND o.kind='WITHDRAW' AND o.sequence<before_sequence ORDER BY sequence LIMIT 1
  ), activations AS (
    SELECT business_date,sequence,agreement_id FROM first_draw
    UNION ALL SELECT o.business_date,o.sequence,o.agreement_id FROM loans_khataoperation o
      WHERE o.account_id=account_key AND o.kind='REVISE' AND o.sequence<before_sequence
  ), daily AS (
    SELECT DISTINCT ON (business_date) * FROM activations ORDER BY business_date,sequence DESC
  ), spans AS (
    SELECT agreement_id,greatest(business_date,period_start) AS start_on,
      least(COALESCE(lead(business_date) OVER (ORDER BY business_date),period_end),period_end) AS end_on FROM daily
  ) SELECT row_number() OVER (ORDER BY s.start_on)::integer,s.agreement_id,s.start_on,s.end_on,
      (r.agreed_limit*100)*(r.monthly_rate*1000000)*(s.end_on-s.start_on),
      10000000000::numeric*(period_end-period_start)
    FROM spans s JOIN loans_khataagreementrevision r ON r.id=s.agreement_id WHERE s.start_on<s.end_on;
$$;

CREATE FUNCTION loans_khata_revision_operation_guard() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE a loans_khataaccount%ROWTYPE; proposal loans_khataagreementrevision%ROWTYPE;
  prior loans_khataagreementrevision%ROWTYPE; approval_row loans_khataoperation%ROWTYPE;
  position_row record; snapshot jsonb; repayment numeric; next_unused numeric;
BEGIN
  IF NEW.kind NOT IN ('TERMS_OK','REVISE') THEN RETURN NEW; END IF;
  SELECT * INTO a FROM loans_khataaccount WHERE id=NEW.account_id FOR UPDATE;
  SELECT * INTO proposal FROM loans_khataagreementrevision WHERE id=NEW.agreement_id;
  SELECT * INTO position_row FROM loans_khata_position(a.id,NEW.sequence);
  SELECT * INTO prior FROM loans_khataagreementrevision WHERE id=position_row.agreement_id;
  IF a.state<>'ACTIVE' OR prior.id IS NULL OR proposal.id IS NULL OR proposal.account_id<>a.id
    OR proposal.workspace_id<>NEW.workspace_id OR a.workspace_id<>NEW.workspace_id
    OR proposal.number<>(SELECT max(number) FROM loans_khataagreementrevision WHERE account_id=a.id)
    OR proposal.number<=prior.number OR proposal.intended_on<>NEW.business_date
    OR (proposal.agreed_limit,proposal.monthly_rate)=(prior.agreed_limit,prior.monthly_rate)
    OR NEW.business_date<(SELECT max(business_date) FROM loans_khataoperation WHERE account_id=a.id)
    OR EXISTS (SELECT 1 FROM loans_khatainterestperiod WHERE account_id=a.id AND end_on>NEW.business_date)
    OR NEW.evidence->>'schema' IS DISTINCT FROM 'khata-revision/1'
  THEN RAISE EXCEPTION 'Agreement change requires current active terms and cannot rewrite finalized interest'; END IF;
  snapshot:=CASE WHEN NEW.kind='TERMS_OK' THEN NEW.evidence->'review' ELSE NEW.evidence END;
  repayment:=(snapshot->>'principal_repayment')::numeric;
  next_unused:=greatest(0,position_row.unused+proposal.agreed_limit-prior.agreed_limit);
  IF repayment IS NULL OR repayment='NaN'::numeric OR repayment<0 OR repayment>position_row.principal
    OR repayment<>round(repayment,2) OR (repayment>0 AND proposal.agreed_limit>=prior.agreed_limit)
    OR position_row.principal-repayment>proposal.agreed_limit
  THEN RAISE EXCEPTION 'Invalid principal repayment for formal limit reduction'; END IF;
  IF (snapshot->>'account_id')::bigint IS DISTINCT FROM a.id
    OR (snapshot->>'date')::date IS DISTINCT FROM NEW.business_date
    OR (snapshot->>'last_sequence')::integer IS DISTINCT FROM NEW.sequence-1
    OR (snapshot->>'current_agreement_id')::bigint IS DISTINCT FROM prior.id
    OR (snapshot->>'proposal_id')::bigint IS DISTINCT FROM proposal.id
    OR (snapshot->>'old_limit')::numeric IS DISTINCT FROM prior.agreed_limit
    OR (snapshot->>'new_limit')::numeric IS DISTINCT FROM proposal.agreed_limit
    OR (snapshot->>'old_monthly_rate')::numeric IS DISTINCT FROM prior.monthly_rate
    OR (snapshot->>'new_monthly_rate')::numeric IS DISTINCT FROM proposal.monthly_rate
    OR (snapshot->>'principal')::numeric IS DISTINCT FROM position_row.principal
    OR (snapshot->>'unused')::numeric IS DISTINCT FROM position_row.unused
    OR (snapshot->>'new_principal')::numeric IS DISTINCT FROM position_row.principal-repayment
    OR (snapshot->>'new_unused')::numeric IS DISTINCT FROM next_unused
  THEN RAISE EXCEPTION 'Agreement change snapshot must match canonical balances and terms'; END IF;
  IF NEW.kind='TERMS_OK' THEN
    IF COALESCE(btrim(NEW.evidence->>'agreement_reference'),'')=''
    THEN RAISE EXCEPTION 'Agreement approval needs borrower consent evidence'; END IF;
  ELSE
    SELECT * INTO approval_row FROM loans_khataoperation WHERE id=NEW.approval_id;
    IF approval_row.id IS NULL OR approval_row.kind<>'TERMS_OK' OR approval_row.workspace_id<>NEW.workspace_id
      OR approval_row.account_id<>a.id OR approval_row.agreement_id<>proposal.id
      OR approval_row.business_date<>NEW.business_date OR approval_row.sequence<>NEW.sequence-1
      OR NEW.amount<>repayment OR (snapshot->>'approval_id')::bigint IS DISTINCT FROM approval_row.id
      OR (snapshot-ARRAY['last_sequence','approval_id','payment_reference']) IS DISTINCT FROM ((approval_row.evidence->'review')-'last_sequence')
      OR (repayment>0 AND COALESCE(btrim(snapshot->>'payment_reference'),'')='')
    THEN RAISE EXCEPTION 'Activation requires unchanged approval and actual repayment evidence'; END IF;
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER khata_revision_operation_guard BEFORE INSERT ON loans_khataoperation FOR EACH ROW EXECUTE FUNCTION loans_khata_revision_operation_guard();
"""


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0035_khata_interest_collection'),
        ('orgs', '0010_storage_inventory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='khataoperation',
            name='khata_op_shape_valid',
        ),
        migrations.AlterField(
            model_name='khataoperation',
            name='kind',
            field=models.CharField(choices=[('APPROVE', 'Approve opening'), ('WITHDRAW', 'Withdrawal'), ('DEPOSIT', 'Collateral received'), ('RETURN', 'Unopened collateral returned'), ('PHOTO', 'Collateral photograph'), ('ACCRUE', 'Finalize completed interest periods'), ('INTEREST', 'Interest received'), ('TERMS_OK', 'Approve agreement change'), ('REVISE', 'Activate agreement change')], max_length=8),
        ),
        migrations.AddConstraint(
            model_name='khataoperation',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'REVISE')), fields=('agreement',), name='khata_revision_activate_once'),
        ),
        migrations.AddConstraint(
            model_name='khataoperation',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gte', 1), models.Q(models.Q(('agreement__isnull', False), ('amount__gt', 0), ('approval__isnull', False), ('item__isnull', True), ('kind', 'WITHDRAW')), models.Q(('agreement__isnull', False), ('amount', 0), ('approval__isnull', True), ('item__isnull', True), ('kind', 'APPROVE')), models.Q(('agreement__isnull', True), ('amount', 0), ('approval__isnull', True), ('item__isnull', True), ('kind', 'DEPOSIT')), models.Q(('agreement__isnull', True), ('amount', 0), ('approval__isnull', True), ('item__isnull', True), ('kind', 'ACCRUE'), ('policy__isnull', True)), models.Q(('agreement__isnull', True), ('amount__gt', 0), ('approval__isnull', True), ('item__isnull', True), ('kind', 'INTEREST'), ('policy__isnull', True)), models.Q(('agreement__isnull', False), ('amount', 0), ('approval__isnull', True), ('item__isnull', True), ('kind', 'TERMS_OK'), ('policy__isnull', True)), models.Q(('agreement__isnull', False), ('amount__gte', 0), ('approval__isnull', False), ('item__isnull', True), ('kind', 'REVISE'), ('policy__isnull', True)), models.Q(('agreement__isnull', True), ('amount', 0), ('approval__isnull', True), ('item__isnull', False), ('kind__in', ('RETURN', 'PHOTO'))), _connector='OR')), name='khata_op_shape_valid'),
        ),
    ]

    operations += [migrations.RunSQL(
        HELPERS + FOUNDATION + OPENING + COMPLETE + INTEREST + INTEREST_COMPLETE,
        OLD_FOUNDATION + OLD_OPENING + OLD_COMPLETE + OLD_INTEREST + OLD_INTEREST_COMPLETE + """
        DROP TRIGGER khata_revision_operation_guard ON loans_khataoperation;
        DROP FUNCTION loans_khata_revision_operation_guard();
        DROP FUNCTION loans_khata_segments(bigint,integer,date,date);
        DROP FUNCTION loans_khata_round_fraction(numeric,numeric);
        DROP FUNCTION loans_khata_position(bigint,integer);
        """,
    )]
