# Generated by Django 6.1.1 on 2026-10-01 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from apps.tenancy.rls import EnableWorkspaceRLS
from importlib import import_module

previous = import_module("apps.tenant_apps.loans.migrations.0036_khata_agreement_changes")
OLD_POSITION = previous.HELPERS[:previous.HELPERS.index("CREATE FUNCTION loans_khata_round_fraction")].replace("CREATE FUNCTION", "CREATE OR REPLACE FUNCTION", 1)
POSITION = OLD_POSITION.replace("('WITHDRAW','REVISE')", "('WITHDRAW','REVISE','SETTLE')").replace(
    "ELSE\n      unused:=", "ELSIF event.kind='SETTLE' THEN\n      principal:=0; unused:=0;\n    ELSE\n      unused:=")
FOUNDATION = previous.FOUNDATION.replace("ARRAY['state','opened_on']", "ARRAY['state','opened_on','settled_on']")
state_start = FOUNDATION.index("OR NEW.state <> (CASE WHEN EXISTS")
state_end = FOUNDATION.index("OR NEW.opened_on IS DISTINCT", state_start)
FOUNDATION = FOUNDATION[:state_start] + """
                      OR NEW.state <> loans_khata_state(OLD.id)
                      OR NEW.settled_on IS DISTINCT FROM (SELECT business_date FROM loans_khataoperation WHERE account_id=OLD.id AND kind='SETTLE' ORDER BY sequence LIMIT 1)
                      """ + FOUNDATION[state_end:]
OPENING = previous.OPENING.replace("OR a.state='CANCELLED'", "OR a.state='CANCELLED' OR (a.state IN ('SETTLED_RETURN_PENDING','CLOSED') AND NEW.kind<>'HANDOVER')")
OPENING = OPENING.replace("kind='RETURN'", "kind IN ('RETURN','HANDOVER')")
OPENING = OPENING.replace("NEW.kind IN ('RETURN','HANDOVER') AND a.opened_on IS NOT NULL", "NEW.kind='RETURN' AND a.opened_on IS NOT NULL")
OPENING = OPENING.replace("op.kind NOT IN ('APPROVE','WITHDRAW')", "op.kind NOT IN ('APPROVE','WITHDRAW','EXCHANGE','REVISE','HANDOVER')")
OPENING = OPENING.replace("SELECT * INTO quote FROM rates_rate WHERE id=NEW.rate_id;", """
                  IF EXISTS (SELECT 1 FROM loans_khatacollateralselection s JOIN loans_khataoperation o ON o.id=s.operation_id
                    WHERE s.item_id=NEW.item_id AND s.role='OUT' AND o.sequence<op.sequence)
                  THEN RAISE EXCEPTION 'Reserved outgoing collateral cannot back another operation'; END IF;
                  SELECT * INTO quote FROM rates_rate WHERE id=NEW.rate_id;""")
COMPLETE = previous.COMPLETE.replace("o.kind='RETURN'", "o.kind IN ('RETURN','HANDOVER')")
COMPLETE = COMPLETE.replace("AND NOT EXISTS (SELECT 1 FROM loans_khatacollateralvaluation v", """
                    AND NOT EXISTS (SELECT 1 FROM loans_khatacollateralselection s JOIN loans_khataoperation o ON o.id=s.operation_id
                      WHERE s.item_id=i.id AND s.role='OUT' AND o.sequence<=NEW.sequence)
                    AND NOT EXISTS (SELECT 1 FROM loans_khatacollateralvaluation v""")

INTEREST = previous.INTEREST.replace("op.kind <> 'ACCRUE'", "op.kind NOT IN ('ACCRUE','SETTLE')")
INTEREST = INTEREST.replace("NEW.start_on,NEW.end_on) s", "NEW.start_on,NEW.end_on,COALESCE(NEW.charged_through,NEW.end_on)) s")
INTEREST = INTEREST.replace("loans_khata_segments(a.id,op.sequence,NEW.start_on", "loans_khata_closing_segments(a.id,op.sequence,NEW.start_on")
INTEREST = INTEREST.replace("loans_khata_segments(a.id,op.sequence,period_row.start_on,period_row.end_on)",
    "loans_khata_closing_segments(a.id,op.sequence,period_row.start_on,period_row.end_on,COALESCE(period_row.charged_through,period_row.end_on))")
INTEREST = INTEREST.replace("INTO actual\n", "INTO actual\n")
INTEREST = INTEREST.replace("floor_charge := CASE", "actual := COALESCE(actual,0);\n                floor_charge := CASE")
INTEREST = INTEREST.replace("OR NEW.end_on > op.business_date", """
                  OR (op.kind='ACCRUE' AND (NEW.charged_through IS NOT NULL OR NEW.end_on>op.business_date))
                  OR (op.kind='SETTLE' AND COALESCE(NEW.charged_through,NEW.end_on)<>least(NEW.end_on,op.business_date))""")
INTEREST = INTEREST.replace("op.kind <> 'INTEREST'", "op.kind NOT IN ('INTEREST','SETTLE')")
INTEREST = INTEREST.replace("OR period_row.due_on > op.business_date", "OR (op.kind='INTEREST' AND period_row.due_on > op.business_date)")
INTEREST = INTEREST.replace(">= op.sequence", "> (CASE WHEN op.kind='SETTLE' THEN op.sequence ELSE op.sequence-1 END)")
INTEREST = INTEREST.replace("NEW.amount+received > op.amount", "NEW.amount+received > (CASE WHEN op.kind='SETTLE' THEN op.interest_amount ELSE op.amount END)")
INTEREST = INTEREST.replace("(e->>'period_id')::bigint=NEW.period_id", "(op.kind='SETTLE' OR (e->>'period_id')::bigint=NEW.period_id)")
INTEREST_COMPLETE = previous.INTEREST_COMPLETE.replace("NEW.kind='ACCRUE'", "NEW.kind IN ('ACCRUE','SETTLE')")
INTEREST_COMPLETE = INTEREST_COMPLETE.replace("loans_khata_segments(p.account_id,NEW.sequence,p.start_on,p.end_on)",
    "loans_khata_closing_segments(p.account_id,NEW.sequence,p.start_on,p.end_on,COALESCE(p.charged_through,p.end_on))")

HELPERS = r"""
CREATE FUNCTION loans_khata_state(account_key bigint) RETURNS text LANGUAGE sql STABLE AS $$
  SELECT CASE WHEN EXISTS(SELECT 1 FROM loans_khataoperation WHERE account_id=account_key AND kind='SETTLE')
    THEN CASE WHEN EXISTS(SELECT 1 FROM loans_khatacollateralitem i WHERE i.account_id=account_key
      AND NOT EXISTS(SELECT 1 FROM loans_khataoperation o WHERE o.item_id=i.id AND o.kind IN ('RETURN','HANDOVER')))
      THEN 'SETTLED_RETURN_PENDING' ELSE 'CLOSED' END
    WHEN EXISTS(SELECT 1 FROM loans_khataoperation WHERE account_id=account_key AND kind='WITHDRAW') THEN 'ACTIVE' ELSE 'APPROVED' END;
$$;
CREATE FUNCTION loans_khata_eligible(account_key bigint,before_sequence integer) RETURNS SETOF bigint LANGUAGE sql STABLE AS $$
  SELECT i.id FROM loans_khatacollateralitem i JOIN loans_khataoperation receipt ON receipt.id=i.received_operation_id
    WHERE i.account_id=account_key AND receipt.sequence<before_sequence
      AND NOT EXISTS(SELECT 1 FROM loans_khataoperation o WHERE o.item_id=i.id AND o.kind IN ('RETURN','HANDOVER') AND o.sequence<before_sequence)
      AND NOT EXISTS(SELECT 1 FROM loans_khatacollateralselection s JOIN loans_khataoperation o ON o.id=s.operation_id
        WHERE s.item_id=i.id AND s.role='OUT' AND o.sequence<before_sequence);
$$;
CREATE FUNCTION loans_khata_closing_segments(account_key bigint,before_sequence integer,period_start date,period_end date,through_date date)
RETURNS TABLE(segment_sequence integer,agreement_id bigint,start_on date,end_on date,exact_numerator numeric,exact_denominator numeric)
LANGUAGE sql STABLE AS $$
  SELECT s.segment_sequence,s.agreement_id,s.start_on,least(s.end_on,through_date),
    div(s.exact_numerator,s.end_on-s.start_on)*(least(s.end_on,through_date)-s.start_on),s.exact_denominator
    FROM loans_khata_segments(account_key,before_sequence,period_start,period_end) s WHERE s.start_on<through_date;
$$;
CREATE FUNCTION loans_khata_due(account_key bigint,before_sequence integer,day date,overdue boolean) RETURNS numeric LANGUAGE plpgsql STABLE AS $$
DECLARE first_draw record; idx integer:=0; finish date; due_date date; charge numeric; paid numeric; total numeric:=0;
BEGIN
  IF EXISTS(SELECT 1 FROM loans_khataoperation WHERE account_id=account_key AND kind='SETTLE' AND sequence<before_sequence) THEN RETURN 0; END IF;
  SELECT o.business_date,r.* INTO first_draw FROM loans_khataoperation o JOIN loans_khataagreementrevision r ON r.id=o.agreement_id
    WHERE o.account_id=account_key AND o.kind='WITHDRAW' AND o.sequence<before_sequence ORDER BY o.sequence LIMIT 1;
  IF first_draw.id IS NULL THEN RETURN 0; END IF;
  LOOP
    finish:=(first_draw.business_date+make_interval(months=>idx+1))::date;
    EXIT WHEN finish>day;
    due_date:=(first_draw.business_date+make_interval(months=>CASE WHEN first_draw.frequency='MONTHLY' THEN idx+1 ELSE (idx/12+1)*12 END))::date;
    IF due_date<=day AND (NOT overdue OR due_date<day) THEN
      SELECT p.charge INTO charge FROM loans_khatainterestperiod p JOIN loans_khataoperation o ON o.id=p.operation_id
        WHERE p.account_id=account_key AND p.index=idx AND o.sequence<before_sequence;
      IF charge IS NULL THEN
        SELECT loans_khata_round_fraction(sum(s.exact_numerator),max(s.exact_denominator)) INTO charge
          FROM loans_khata_segments(account_key,before_sequence,(first_draw.business_date+make_interval(months=>idx))::date,finish) s;
        IF idx=0 THEN charge:=greatest(charge,round(first_draw.agreed_limit*first_draw.monthly_rate/100,2)); END IF;
      END IF;
      SELECT COALESCE(sum(a.amount),0) INTO paid FROM loans_khatainterestallocation a
        JOIN loans_khatainterestperiod p ON p.id=a.period_id JOIN loans_khataoperation o ON o.id=a.operation_id
        WHERE p.account_id=account_key AND p.index=idx AND o.sequence<before_sequence;
      total:=total+charge-paid;
    END IF;
    idx:=idx+1;
  END LOOP;
  RETURN total;
END $$;
"""

GUARDS = r"""
CREATE FUNCTION loans_khata_custody_guard() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE a loans_khataaccount%ROWTYPE; op loans_khataoperation%ROWTYPE; source loans_khataoperation%ROWTYPE;
  item_row loans_khatacollateralitem%ROWTYPE; position_row record; terms loans_khataagreementrevision%ROWTYPE;
  prior loans_khataagreementrevision%ROWTYPE; policy_row loans_khatapolicyrevision%ROWTYPE;
BEGIN
  IF TG_TABLE_NAME='loans_khatacollateralselection' THEN
    IF TG_OP<>'INSERT' THEN RAISE EXCEPTION 'Khata custody membership is immutable'; END IF;
    SELECT * INTO op FROM loans_khataoperation WHERE id=NEW.operation_id;
    SELECT * INTO a FROM loans_khataaccount WHERE id=op.account_id FOR UPDATE;
    SELECT * INTO item_row FROM loans_khatacollateralitem WHERE id=NEW.item_id;
    IF op.id IS NULL OR a.id IS NULL OR item_row.id IS NULL OR op.workspace_id<>NEW.workspace_id OR a.workspace_id<>NEW.workspace_id
      OR item_row.workspace_id<>NEW.workspace_id OR item_row.account_id<>a.id
      OR op.kind NOT IN ('EXCHANGE','REVISE','SETTLE') OR (NEW.role='IN' AND op.kind<>'EXCHANGE')
      OR NOT EXISTS(SELECT 1 FROM loans_khata_eligible(a.id,op.sequence) k WHERE k=NEW.item_id)
      OR NOT EXISTS(SELECT 1 FROM jsonb_array_elements_text(op.evidence->CASE WHEN NEW.role='OUT' THEN 'outgoing_ids' ELSE 'incoming_ids' END) k WHERE k::bigint=NEW.item_id)
    THEN RAISE EXCEPTION 'Invalid khata custody membership/scope/source'; END IF;
    RETURN NEW;
  END IF;
  IF NEW.kind NOT IN ('EXCHANGE','SETTLE','HANDOVER','REVISE') THEN RETURN NEW; END IF;
  SELECT * INTO a FROM loans_khataaccount WHERE id=NEW.account_id FOR UPDATE;
  IF a.id IS NULL OR a.workspace_id<>NEW.workspace_id THEN RAISE EXCEPTION 'Khata custody Workspace mismatch'; END IF;
  IF NEW.kind='HANDOVER' THEN
    SELECT * INTO source FROM loans_khataoperation WHERE id=NEW.parent_id;
    IF source.id IS NULL OR source.account_id<>a.id OR source.workspace_id<>NEW.workspace_id
      OR NOT EXISTS(SELECT 1 FROM loans_khatacollateralselection WHERE item_id=NEW.item_id AND operation_id=source.id AND role='OUT')
      OR COALESCE(btrim(NEW.evidence->>'recipient'),'')='' OR COALESCE(btrim(NEW.evidence->>'reference'),'')=''
      OR NEW.business_date<source.business_date
    THEN RAISE EXCEPTION 'Handover requires actual recipient/reference and this item reservation'; END IF;
    IF source.kind='REVISE' AND a.state='ACTIVE' AND loans_khata_due(a.id,NEW.sequence,NEW.business_date,false)>0
    THEN RAISE EXCEPTION 'Clear due interest before reduction handover'; END IF;
    RETURN NEW;
  END IF;
  IF a.state<>'ACTIVE' THEN RAISE EXCEPTION 'Custody/settlement requires active khata'; END IF;
  SELECT * INTO position_row FROM loans_khata_position(a.id,NEW.sequence);
  SELECT * INTO terms FROM loans_khataagreementrevision WHERE id=NEW.agreement_id;
  IF NEW.kind='SETTLE' THEN
    IF NEW.agreement_id IS DISTINCT FROM position_row.agreement_id OR NEW.amount IS DISTINCT FROM position_row.principal
      OR NEW.interest_amount='NaN'::numeric OR COALESCE(btrim(NEW.evidence->>'payment_reference'),'')=''
      OR NEW.evidence->>'schema' IS DISTINCT FROM 'khata-settlement/1'
      OR jsonb_typeof(NEW.evidence->'periods') IS DISTINCT FROM 'array'
      OR jsonb_typeof(NEW.evidence->'allocations') IS DISTINCT FROM 'array'
      OR jsonb_typeof(NEW.evidence->'outgoing_ids') IS DISTINCT FROM 'array'
      OR NEW.business_date<(SELECT max(business_date) FROM loans_khataoperation WHERE account_id=a.id)
    THEN RAISE EXCEPTION 'Settlement requires actual canonical principal and complete evidence'; END IF;
  ELSIF NEW.kind='EXCHANGE' THEN
    SELECT * INTO policy_row FROM loans_khatapolicyrevision WHERE workspace_id=a.workspace_id ORDER BY number DESC LIMIT 1;
    IF NEW.agreement_id IS DISTINCT FROM position_row.agreement_id OR NEW.policy_id IS DISTINCT FROM policy_row.id
      OR NEW.evidence->>'schema' IS DISTINCT FROM 'khata-custody/1'
      OR jsonb_typeof(NEW.evidence->'outgoing_ids') IS DISTINCT FROM 'array'
      OR jsonb_typeof(NEW.evidence->'incoming_ids') IS DISTINCT FROM 'array'
      OR jsonb_array_length(NEW.evidence->'outgoing_ids')=0 OR jsonb_array_length(NEW.evidence->'incoming_ids')=0
      OR EXISTS(SELECT 1 FROM jsonb_array_elements_text(NEW.evidence->'outgoing_ids') o,
        jsonb_array_elements_text(NEW.evidence->'incoming_ids') i WHERE o=i)
      OR (policy_row.overdue='BLOCK' AND loans_khata_due(a.id,NEW.sequence,NEW.business_date,true)>0)
    THEN RAISE EXCEPTION 'Invalid exchange evidence or overdue policy'; END IF;
  ELSIF NEW.evidence ? 'outgoing_ids' THEN
    SELECT * INTO prior FROM loans_khataagreementrevision WHERE id=position_row.agreement_id;
    IF terms.agreed_limit>=prior.agreed_limit OR loans_khata_due(a.id,NEW.sequence,NEW.business_date,false)>0
    THEN RAISE EXCEPTION 'Reduction returns require reduced terms and cleared due interest'; END IF;
  END IF;
  RETURN NEW;
END $$;

CREATE FUNCTION loans_khata_custody_complete() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE position_row record; fraction numeric; retained numeric; opening_date date; expected_interest numeric;
  policy_row loans_khatapolicyrevision%ROWTYPE; parent_kind text;
BEGIN
  IF NEW.kind IN ('EXCHANGE','SETTLE') OR (NEW.kind='REVISE' AND NEW.evidence ? 'outgoing_ids') THEN
    IF jsonb_array_length(NEW.evidence->'outgoing_ids') IS DISTINCT FROM
        (SELECT count(*) FROM loans_khatacollateralselection WHERE operation_id=NEW.id AND role='OUT')
      OR (NEW.kind='EXCHANGE' AND jsonb_array_length(NEW.evidence->'incoming_ids') IS DISTINCT FROM
        (SELECT count(*) FROM loans_khatacollateralselection WHERE operation_id=NEW.id AND role='IN'))
    THEN RAISE EXCEPTION 'Custody operation must preserve all selection children'; END IF;
    IF NEW.kind='SETTLE' AND EXISTS(SELECT 1 FROM loans_khata_eligible(NEW.account_id,NEW.sequence) k
      WHERE NOT EXISTS(SELECT 1 FROM loans_khatacollateralselection s WHERE s.operation_id=NEW.id AND s.role='OUT' AND s.item_id=k))
    THEN RAISE EXCEPTION 'Settlement must reserve all remaining collateral'; END IF;
  END IF;
  SELECT kind INTO parent_kind FROM loans_khataoperation WHERE id=NEW.parent_id;
  IF NEW.kind='EXCHANGE' OR (NEW.kind='REVISE' AND NEW.evidence ? 'outgoing_ids')
    OR (NEW.kind='HANDOVER' AND parent_kind='REVISE' AND NOT EXISTS(SELECT 1 FROM loans_khataoperation WHERE account_id=NEW.account_id AND kind='SETTLE' AND sequence<NEW.sequence)) THEN
    IF jsonb_array_length(NEW.evidence->'valuations') IS DISTINCT FROM (SELECT count(*) FROM loans_khatacollateralvaluation WHERE operation_id=NEW.id)
      OR EXISTS(SELECT 1 FROM loans_khata_eligible(NEW.account_id,NEW.sequence) k
        WHERE NOT EXISTS(SELECT 1 FROM loans_khatacollateralvaluation v WHERE v.operation_id=NEW.id AND v.item_id=k))
      OR (SELECT count(*) FROM loans_khata_eligible(NEW.account_id,NEW.sequence))<>(SELECT count(*) FROM loans_khatacollateralvaluation WHERE operation_id=NEW.id)
      OR EXISTS(SELECT 1 FROM loans_khatacollateralvaluation v JOIN loans_khatacollateralitem i ON i.id=v.item_id
        WHERE v.operation_id=NEW.id GROUP BY i.metal HAVING count(DISTINCT v.rate_id)>1)
    THEN RAISE EXCEPTION 'Custody valuation must cover all eligible items at one price per metal'; END IF;
    SELECT ltv INTO fraction FROM loans_khataagreementrevision WHERE id=COALESCE(NEW.agreement_id,
      (SELECT agreement_id FROM loans_khata_position(NEW.account_id,NEW.sequence)));
    SELECT COALESCE(sum(v.value),0) INTO retained FROM loans_khatacollateralvaluation v WHERE v.operation_id=NEW.id
      AND NOT EXISTS(SELECT 1 FROM loans_khatacollateralselection s WHERE s.operation_id=NEW.id AND s.item_id=v.item_id AND s.role='OUT');
    SELECT * INTO position_row FROM loans_khata_position(NEW.account_id,NEW.sequence+CASE WHEN NEW.kind='REVISE' THEN 1 ELSE 0 END);
    IF NEW.kind='EXCHANGE' THEN
      IF EXISTS(SELECT i.metal FROM loans_khatacollateralselection s JOIN loans_khatacollateralitem i ON i.id=s.item_id
        WHERE s.operation_id=NEW.id GROUP BY i.metal HAVING count(*) FILTER(WHERE s.role='OUT')=0 OR count(*) FILTER(WHERE s.role='IN')=0)
      THEN RAISE EXCEPTION 'Exchange replacement must use the same metals'; END IF;
      SELECT * INTO policy_row FROM loans_khatapolicyrevision WHERE id=NEW.policy_id;
      IF policy_row.exchange='BLOCK' AND (position_row.principal>floor(retained*fraction*100)/100 OR EXISTS(
        SELECT i.metal FROM loans_khatacollateralselection s JOIN loans_khatacollateralitem i ON i.id=s.item_id
          JOIN loans_khatacollateralvaluation v ON v.item_id=i.id AND v.operation_id=NEW.id
        WHERE s.operation_id=NEW.id GROUP BY i.metal HAVING sum(CASE WHEN s.role='OUT' THEN v.value ELSE -v.value END)>0))
      THEN RAISE EXCEPTION 'Strict exchange policy rejects value or LTV shortfalls'; END IF;
    ELSIF position_row.principal>floor(retained*fraction*100)/100 THEN
      RAISE EXCEPTION 'Reduction retained collateral LTV failed';
    END IF;
  END IF;
  IF NEW.kind='SETTLE' THEN
    SELECT opened_on INTO opening_date FROM loans_khataaccount WHERE id=NEW.account_id;
    IF EXISTS(SELECT 1 FROM generate_series(0,
      (extract(year FROM NEW.business_date)::integer-extract(year FROM opening_date)::integer)*12
       +extract(month FROM NEW.business_date)::integer-extract(month FROM opening_date)::integer) n
      WHERE (n=0 OR (opening_date+make_interval(months=>n))::date<NEW.business_date)
        AND NOT EXISTS(SELECT 1 FROM loans_khatainterestperiod p JOIN loans_khataoperation o ON o.id=p.operation_id
          WHERE p.account_id=NEW.account_id AND p.index=n AND o.sequence<=NEW.sequence))
      OR EXISTS(SELECT 1 FROM loans_khatainterestperiod p JOIN loans_khataoperation o ON o.id=p.operation_id
        WHERE p.account_id=NEW.account_id AND o.sequence<=NEW.sequence AND COALESCE(p.charged_through,p.end_on)>NEW.business_date)
    THEN RAISE EXCEPTION 'Settlement must finalize interest exactly through closure'; END IF;
    SELECT COALESCE(sum(p.charge-COALESCE((SELECT sum(a.amount) FROM loans_khatainterestallocation a JOIN loans_khataoperation o ON o.id=a.operation_id
      WHERE a.period_id=p.id AND o.sequence<NEW.sequence),0)),0) INTO expected_interest FROM loans_khatainterestperiod p
      JOIN loans_khataoperation o ON o.id=p.operation_id WHERE p.account_id=NEW.account_id AND o.sequence<=NEW.sequence;
    IF expected_interest<>NEW.interest_amount OR NEW.interest_amount<>COALESCE((SELECT sum(amount) FROM loans_khatainterestallocation WHERE operation_id=NEW.id),0)
      OR jsonb_array_length(NEW.evidence->'allocations')<>(SELECT count(*) FROM loans_khatainterestallocation WHERE operation_id=NEW.id)
    THEN RAISE EXCEPTION 'Settlement must collect and allocate all unpaid interest'; END IF;
  END IF;
  RETURN NEW;
END $$;
CREATE FUNCTION loans_khata_project_custody() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.kind='SETTLE' OR (NEW.kind='HANDOVER' AND EXISTS(SELECT 1 FROM loans_khataoperation WHERE account_id=NEW.account_id AND kind='SETTLE')) THEN
    UPDATE loans_khataaccount SET state=loans_khata_state(NEW.account_id),
      settled_on=(SELECT business_date FROM loans_khataoperation WHERE account_id=NEW.account_id AND kind='SETTLE' ORDER BY sequence LIMIT 1)
      WHERE id=NEW.account_id;
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER khata_selection_guard BEFORE INSERT OR UPDATE OR DELETE ON loans_khatacollateralselection FOR EACH ROW EXECUTE FUNCTION loans_khata_custody_guard();
CREATE TRIGGER khata_custody_operation_guard BEFORE INSERT ON loans_khataoperation FOR EACH ROW EXECUTE FUNCTION loans_khata_custody_guard();
CREATE TRIGGER khata_custody_projection AFTER INSERT ON loans_khataoperation FOR EACH ROW EXECUTE FUNCTION loans_khata_project_custody();
CREATE CONSTRAINT TRIGGER khata_custody_complete AFTER INSERT ON loans_khataoperation DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION loans_khata_custody_complete();
"""


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0036_khata_agreement_changes'),
        ('orgs', '0010_storage_inventory'),
        ('party', '0003_party_photo_gallery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KhataCollateralSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('IN', 'Replacement'), ('OUT', 'Reserved for return')], max_length=3)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='khataaccount',
            name='khata_account_state_valid',
        ),
        migrations.RemoveConstraint(
            model_name='khataoperation',
            name='khata_item_return_once',
        ),
        migrations.RemoveConstraint(
            model_name='khataoperation',
            name='khata_op_shape_valid',
        ),
        migrations.AddField(
            model_name='khataaccount',
            name='settled_on',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='khatainterestperiod',
            name='charged_through',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='khataoperation',
            name='interest_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='khataoperation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handovers', to='loans.khataoperation'),
        ),
        migrations.AlterField(
            model_name='khataaccount',
            name='state',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('SETTLED_RETURN_PENDING', 'Settled, return pending'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=24),
        ),
        migrations.AlterField(
            model_name='khataoperation',
            name='kind',
            field=models.CharField(choices=[('APPROVE', 'Approve opening'), ('WITHDRAW', 'Withdrawal'), ('DEPOSIT', 'Collateral received'), ('RETURN', 'Unopened collateral returned'), ('PHOTO', 'Collateral photograph'), ('ACCRUE', 'Finalize completed interest periods'), ('INTEREST', 'Interest received'), ('TERMS_OK', 'Approve agreement change'), ('REVISE', 'Activate agreement change'), ('EXCHANGE', 'Collateral exchange'), ('HANDOVER', 'Reserved collateral handed over'), ('SETTLE', 'Financial settlement')], max_length=8),
        ),
        migrations.AddConstraint(
            model_name='khataaccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancellation_reason', ''), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('opened_on__isnull', True), ('settled_on__isnull', True), ('state__in', ('DRAFT', 'APPROVED'))), models.Q(('cancellation_reason', ''), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('opened_on__isnull', False), ('settled_on__isnull', True), ('state', 'ACTIVE')), models.Q(('cancellation_reason', ''), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('opened_on__isnull', False), ('settled_on__gte', models.F('opened_on')), ('state__in', ('SETTLED_RETURN_PENDING', 'CLOSED')), ('settled_on__isnull', False)), models.Q(('cancelled_at__isnull', False), ('cancelled_by__isnull', False), ('opened_on__isnull', True), ('settled_on__isnull', True), ('state', 'CANCELLED'), models.Q(('cancellation_reason', ''), _negated=True)), _connector='OR'), name='khata_account_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='khatainterestperiod',
            constraint=models.CheckConstraint(condition=models.Q(('charged_through__isnull', True), models.Q(('charged_through__gte', models.F('start_on')), ('charged_through__lte', models.F('end_on'))), _connector='OR'), name='khata_interest_through_valid'),
        ),
        migrations.AddConstraint(
            model_name='khataoperation',
            constraint=models.UniqueConstraint(condition=models.Q(('kind__in', ('RETURN', 'HANDOVER'))), fields=('item',), name='khata_item_return_once'),
        ),
        migrations.AddConstraint(
            model_name='khataoperation',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gte', 1), models.Q(models.Q(('agreement__isnull', False), ('amount__gt', 0), ('approval__isnull', False), ('item__isnull', True), ('kind', 'WITHDRAW')), models.Q(('agreement__isnull', False), ('amount', 0), ('approval__isnull', True), ('item__isnull', True), ('kind', 'APPROVE')), models.Q(('agreement__isnull', True), ('amount', 0), ('approval__isnull', True), ('item__isnull', True), ('kind', 'DEPOSIT')), models.Q(('agreement__isnull', True), ('amount', 0), ('approval__isnull', True), ('item__isnull', True), ('kind', 'ACCRUE'), ('policy__isnull', True)), models.Q(('agreement__isnull', True), ('amount__gt', 0), ('approval__isnull', True), ('item__isnull', True), ('kind', 'INTEREST'), ('policy__isnull', True)), models.Q(('agreement__isnull', False), ('amount', 0), ('approval__isnull', True), ('item__isnull', True), ('kind', 'TERMS_OK'), ('policy__isnull', True)), models.Q(('agreement__isnull', False), ('amount__gte', 0), ('approval__isnull', False), ('item__isnull', True), ('kind', 'REVISE'), ('policy__isnull', True)), models.Q(('agreement__isnull', False), ('amount', 0), ('approval__isnull', True), ('item__isnull', True), ('kind', 'EXCHANGE')), models.Q(('agreement__isnull', True), ('amount', 0), ('approval__isnull', True), ('item__isnull', False), ('kind', 'HANDOVER'), ('policy__isnull', True)), models.Q(('agreement__isnull', False), ('amount__gte', 0), ('approval__isnull', True), ('item__isnull', True), ('kind', 'SETTLE'), ('policy__isnull', True)), models.Q(('agreement__isnull', True), ('amount', 0), ('approval__isnull', True), ('item__isnull', False), ('kind__in', ('RETURN', 'PHOTO'))), _connector='OR')), name='khata_op_shape_valid'),
        ),
        migrations.AddConstraint(
            model_name='khataoperation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('interest_amount__gte', 0), ('kind', 'SETTLE')), models.Q(models.Q(('kind', 'SETTLE'), _negated=True), ('interest_amount', 0)), _connector='OR'), models.Q(models.Q(('kind', 'HANDOVER'), ('parent__isnull', False)), models.Q(models.Q(('kind', 'HANDOVER'), _negated=True), ('parent__isnull', True)), _connector='OR')), name='khata_op_money_parent_valid'),
        ),
        migrations.AddField(
            model_name='khatacollateralselection',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selections', to='loans.khatacollateralitem'),
        ),
        migrations.AddField(
            model_name='khatacollateralselection',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collateral_selections', to='loans.khataoperation'),
        ),
        migrations.AddField(
            model_name='khatacollateralselection',
            name='workspace',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddConstraint(
            model_name='khatacollateralselection',
            constraint=models.UniqueConstraint(fields=('operation', 'item'), name='khata_selection_item_uniq'),
        ),
        migrations.AddConstraint(
            model_name='khatacollateralselection',
            constraint=models.UniqueConstraint(fields=('item', 'role'), name='khata_selection_role_once'),
        ),
        migrations.AddConstraint(
            model_name='khatacollateralselection',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ('IN', 'OUT'))), name='khata_selection_role_valid'),
        ),
    ]

    operations += [
        EnableWorkspaceRLS('KhataCollateralSelection'),
        migrations.RunSQL(
            HELPERS + POSITION + FOUNDATION + OPENING + COMPLETE + INTEREST + INTEREST_COMPLETE + GUARDS,
            """
            DROP TRIGGER khata_custody_complete ON loans_khataoperation;
            DROP TRIGGER khata_custody_projection ON loans_khataoperation;
            DROP TRIGGER khata_custody_operation_guard ON loans_khataoperation;
            DROP TRIGGER khata_selection_guard ON loans_khatacollateralselection;
            DROP FUNCTION loans_khata_project_custody();
            DROP FUNCTION loans_khata_custody_complete();
            DROP FUNCTION loans_khata_custody_guard();
            """ + OLD_POSITION + previous.FOUNDATION + previous.OPENING + previous.COMPLETE + previous.INTEREST + previous.INTEREST_COMPLETE + """
            DROP FUNCTION loans_khata_due(bigint,integer,date,boolean);
            DROP FUNCTION loans_khata_closing_segments(bigint,integer,date,date,date);
            DROP FUNCTION loans_khata_eligible(bigint,integer);
            DROP FUNCTION loans_khata_state(bigint);
            """,
        ),
    ]
