# Generated by Django 6.0.3 on 2026-08-10 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0036_pawnloanrenewal_successor_advance_interest_and_more'),
        ('orgs', '0024_alter_auditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanDocumentPrintProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('loan_ticket', 'Loan ticket'), ('repayment_receipt', 'Repayment receipt'), ('release_memo', 'Release memo'), ('auction_notice', 'Auction notice'), ('auction_recovery', 'Auction recovery memo'), ('renewal', 'Renewal agreement')], max_length=32)),
                ('name', models.CharField(max_length=100)),
                ('is_retired', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_document_print_profiles_created', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_document_print_profiles', to='orgs.company')),
            ],
            options={
                'ordering': ('document_type', 'name', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='LoanDocumentPrintProfileRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('RETIRED', 'Retired')], db_index=True, default='DRAFT', max_length=12)),
                ('definition', models.JSONField(default=dict)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('validation_result', models.JSONField(blank=True, default=dict)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_document_print_profile_revisions_created', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='loans.loandocumentprintprofile')),
            ],
            options={
                'ordering': ('profile_id', 'version'),
            },
        ),
        migrations.CreateModel(
            name='LoanDocumentPrintProfileAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('loan_ticket', 'Loan ticket'), ('repayment_receipt', 'Repayment receipt'), ('release_memo', 'Release memo'), ('auction_notice', 'Auction notice'), ('auction_recovery', 'Auction recovery memo'), ('renewal', 'Renewal agreement')], max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_document_print_profile_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_print_profile_assignments', to='loans.loanseries')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_document_print_profile_assignments', to='orgs.company')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='loans.loandocumentprintprofilerevision')),
            ],
        ),
        migrations.AddConstraint(
            model_name='loandocumentprintprofile',
            constraint=models.UniqueConstraint(fields=('workspace', 'document_type', 'name'), name='loans_print_profile_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='loandocumentprintprofilerevision',
            constraint=models.UniqueConstraint(fields=('profile', 'version'), name='loans_print_rev_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='loandocumentprintprofilerevision',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='loans_print_rev_version_pos'),
        ),
        migrations.AddConstraint(
            model_name='loandocumentprintprofileassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('series__isnull', True)), fields=('workspace', 'document_type'), name='loans_print_assign_ws_uniq'),
        ),
        migrations.AddConstraint(
            model_name='loandocumentprintprofileassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('series__isnull', False)), fields=('workspace', 'document_type', 'series'), name='loans_print_assign_series_uniq'),
        ),
    ]
