# Generated by Django 6.1.1 on 2026-10-01 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from importlib import import_module


# Extend frozen prior definitions, never live service code. Prefix-bounded
# correction lookup preserves validation of already committed original evidence.
previous = import_module("apps.tenant_apps.loans.migrations.0037_khata_custody_settlement")
function = previous.previous.function

HELPERS = r"""
CREATE FUNCTION loans_khata_effective_operation(source_key bigint,before_sequence integer) RETURNS boolean LANGUAGE sql STABLE AS $$
  SELECT NOT EXISTS(SELECT 1 FROM loans_khataoperation WHERE correction_of_id=source_key AND sequence<before_sequence);
$$;
CREATE FUNCTION loans_khata_correction_dependencies(source_key bigint,before_sequence integer) RETURNS SETOF bigint LANGUAGE sql STABLE AS $$
  SELECT o.id FROM loans_khataoperation o JOIN loans_khataoperation s ON s.id=source_key
    WHERE o.account_id=s.account_id AND o.sequence>s.sequence AND o.sequence<before_sequence
      AND o.kind<>'CORRECT' AND loans_khata_effective_operation(o.id,before_sequence)
  UNION
  SELECT o.id FROM loans_khataoperation o JOIN loans_khataoperation s ON s.id=source_key
    WHERE o.account_id=s.account_id AND o.sequence>s.sequence AND o.sequence<before_sequence AND o.kind='CORRECT'
      AND EXISTS(SELECT 1 FROM loans_khatacollateralselection m WHERE m.operation_id=o.id AND m.role='OUT'
        AND NOT EXISTS(SELECT 1 FROM loans_khataoperation r WHERE r.item_id=m.item_id AND r.kind IN ('RETURN','HANDOVER') AND r.sequence<before_sequence));
$$;
CREATE FUNCTION loans_khata_correction_items(source_key bigint,before_sequence integer) RETURNS SETOF bigint LANGUAGE sql STABLE AS $$
  SELECT k FROM loans_khataoperation o,loans_khata_eligible(o.account_id,before_sequence) k WHERE o.id=source_key
  UNION
  SELECT item_id FROM loans_khatacollateralselection WHERE operation_id=source_key AND role='OUT';
$$;
"""

ELIGIBLE = previous.HELPERS[previous.HELPERS.index("CREATE FUNCTION loans_khata_eligible"):previous.HELPERS.index("CREATE FUNCTION loans_khata_closing_segments")]
ELIGIBLE = ELIGIBLE.replace("CREATE FUNCTION", "CREATE OR REPLACE FUNCTION", 1).replace(
    "AND o.sequence<before_sequence)", "AND o.sequence<before_sequence AND loans_khata_effective_operation(o.id,before_sequence))")
DUE = previous.HELPERS[previous.HELPERS.index("CREATE FUNCTION loans_khata_due"):].replace("CREATE FUNCTION", "CREATE OR REPLACE FUNCTION", 1)
DUE = DUE.replace("AND o.sequence<before_sequence;", "AND o.sequence<before_sequence AND loans_khata_effective_operation(o.id,before_sequence);")
OPENING = previous.OPENING.replace("'EXCHANGE','REVISE','HANDOVER')", "'EXCHANGE','REVISE','HANDOVER','CORRECT')")
OPENING = OPENING.replace("s.role='OUT' AND o.sequence<op.sequence)",
    "s.role='OUT' AND o.sequence<op.sequence AND loans_khata_effective_operation(o.id,op.sequence) AND o.id IS DISTINCT FROM op.correction_of_id)")
COMPLETE = previous.COMPLETE.replace("s.role='OUT' AND o.sequence<=NEW.sequence)",
    "s.role='OUT' AND o.sequence<=NEW.sequence AND loans_khata_effective_operation(o.id,NEW.sequence+1))")
INTEREST = previous.INTEREST.replace("WHERE period_id=NEW.period_id;",
    "WHERE period_id=NEW.period_id AND loans_khata_effective_operation(operation_id,op.sequence+1);")
INTEREST = INTEREST.replace("WHERE period_id=p.id),0)",
    "WHERE period_id=p.id AND loans_khata_effective_operation(operation_id,op.sequence+1)),0)")
CUSTODY = function(previous.GUARDS, "loans_khata_custody_guard")
CUSTODY = CUSTODY.replace("op.kind NOT IN ('EXCHANGE','REVISE','SETTLE')", "op.kind NOT IN ('EXCHANGE','REVISE','SETTLE','CORRECT')")
CUSTODY = CUSTODY.replace("IF source.id IS NULL OR source.account_id<>a.id", "IF source.id IS NULL OR NOT loans_khata_effective_operation(source.id,NEW.sequence) OR source.account_id<>a.id")
CUSTODY = CUSTODY.replace("source.kind='REVISE'", "source.kind IN ('REVISE','CORRECT')")
CUSTODY = CUSTODY.replace("RETURN NEW;\n  END IF;\n  IF NEW.kind", """
    IF EXISTS(SELECT 1 FROM loans_khatacollateralselection s WHERE s.item_id=NEW.item_id AND s.role=NEW.role
      AND loans_khata_effective_operation(s.operation_id,op.sequence+1))
    THEN RAISE EXCEPTION 'Khata item already has active custody membership for this role'; END IF;
    RETURN NEW;
  END IF;
  IF NEW.kind""")
CUSTODY_COMPLETE = function(previous.GUARDS, "loans_khata_custody_complete")
CUSTODY_COMPLETE = CUSTODY_COMPLETE.replace("parent_kind='REVISE'", "parent_kind IN ('REVISE','CORRECT')")
CUSTODY_COMPLETE = CUSTODY_COMPLETE.replace("a.period_id=p.id AND o.sequence<NEW.sequence)",
    "a.period_id=p.id AND o.sequence<NEW.sequence AND loans_khata_effective_operation(o.id,NEW.sequence))")

GUARDS = r"""
CREATE FUNCTION loans_khata_correction_guard() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE a loans_khataaccount%ROWTYPE; source loans_khataoperation%ROWTYPE;
BEGIN
  IF NEW.kind<>'CORRECT' THEN RETURN NEW; END IF;
  SELECT * INTO a FROM loans_khataaccount WHERE id=NEW.account_id FOR UPDATE;
  SELECT * INTO source FROM loans_khataoperation WHERE id=NEW.correction_of_id;
  IF a.id IS NULL OR a.state<>'ACTIVE' OR source.id IS NULL OR source.account_id<>a.id
    OR source.workspace_id<>NEW.workspace_id OR a.workspace_id<>NEW.workspace_id
    OR source.kind NOT IN ('INTEREST','EXCHANGE') OR source.sequence>=NEW.sequence
    OR NOT loans_khata_effective_operation(source.id,NEW.sequence)
    OR NEW.business_date<(SELECT max(business_date) FROM loans_khataoperation WHERE account_id=a.id)
    OR EXISTS(SELECT 1 FROM loans_khata_correction_dependencies(source.id,NEW.sequence))
    OR NEW.amount IS DISTINCT FROM source.amount OR NEW.agreement_id IS DISTINCT FROM source.agreement_id
    OR NEW.evidence->>'schema' IS DISTINCT FROM 'khata-correction/1'
    OR (NEW.evidence->>'source_id')::bigint IS DISTINCT FROM source.id
    OR (NEW.evidence->>'account_id')::bigint IS DISTINCT FROM a.id
    OR (NEW.evidence->>'date')::date IS DISTINCT FROM NEW.business_date
    OR (NEW.evidence->>'last_sequence')::integer IS DISTINCT FROM NEW.sequence-1
    OR (NEW.evidence->>'source_sequence')::integer IS DISTINCT FROM source.sequence
    OR (NEW.evidence->>'amount')::numeric IS DISTINCT FROM source.amount
    OR (NEW.evidence->>'principal')::numeric IS DISTINCT FROM (SELECT principal FROM loans_khata_position(a.id,NEW.sequence))
    OR NEW.evidence->>'source_kind' IS DISTINCT FROM source.kind
    OR NEW.evidence->>'source_request_sha256' IS DISTINCT FROM source.request_sha256
    OR COALESCE(btrim(NEW.evidence->>'reason'),'')='' OR COALESCE(btrim(NEW.evidence->>'resolution_reference'),'')=''
  THEN RAISE EXCEPTION 'Correction requires supported same-account source, reason and no later dependencies'; END IF;
  IF source.kind='INTEREST' THEN
    IF NEW.evidence->>'cash_resolution' IS NULL OR NEW.evidence->>'cash_resolution' NOT IN ('NOT_RECEIVED','REFUNDED')
      OR NEW.evidence ? 'outgoing_ids' OR NEW.evidence ? 'valuations'
      OR jsonb_typeof(NEW.evidence->'allocations') IS DISTINCT FROM 'array'
      OR jsonb_array_length(NEW.evidence->'allocations')<>(SELECT count(*) FROM loans_khatainterestallocation WHERE operation_id=source.id)
      OR EXISTS(SELECT 1 FROM loans_khatainterestallocation v JOIN loans_khatainterestperiod p ON p.id=v.period_id
        WHERE v.operation_id=source.id AND NOT EXISTS(SELECT 1 FROM jsonb_array_elements(NEW.evidence->'allocations') e
          WHERE (e->>'period_id')::bigint=v.period_id AND (e->>'index')::integer=p.index AND (e->>'amount')::numeric=v.amount))
    THEN RAISE EXCEPTION 'Receipt correction needs entire original allocations and actual cash resolution'; END IF;
  ELSE
    IF NEW.evidence->>'cash_resolution' IS DISTINCT FROM ''
      OR NEW.evidence->'released_ids' IS DISTINCT FROM (SELECT jsonb_agg(item_id ORDER BY item_id) FROM loans_khatacollateralselection WHERE operation_id=source.id AND role='OUT')
      OR NEW.evidence->'outgoing_ids' IS DISTINCT FROM (SELECT jsonb_agg(item_id ORDER BY item_id) FROM loans_khatacollateralselection WHERE operation_id=source.id AND role='IN')
      OR jsonb_typeof(NEW.evidence->'valuations') IS DISTINCT FROM 'array'
    THEN RAISE EXCEPTION 'Exchange correction must release original outgoing and reserve all replacements'; END IF;
  END IF;
  RETURN NEW;
END $$;
CREATE FUNCTION loans_khata_correction_complete() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE source_kind text; retained numeric; fraction numeric; principal numeric;
BEGIN
  IF NEW.kind<>'CORRECT' THEN RETURN NEW; END IF;
  SELECT kind INTO source_kind FROM loans_khataoperation WHERE id=NEW.correction_of_id;
  IF source_kind='INTEREST' THEN
    IF EXISTS(SELECT 1 FROM loans_khatacollateralselection WHERE operation_id=NEW.id)
      OR EXISTS(SELECT 1 FROM loans_khatacollateralvaluation WHERE operation_id=NEW.id)
      OR EXISTS(SELECT 1 FROM loans_khatainterestallocation WHERE operation_id=NEW.id)
      OR EXISTS(SELECT 1 FROM loans_khatainterestperiod WHERE operation_id=NEW.id)
    THEN RAISE EXCEPTION 'Receipt correction cannot add money or custody children'; END IF;
    RETURN NEW;
  END IF;
  IF jsonb_array_length(NEW.evidence->'outgoing_ids')<>(SELECT count(*) FROM loans_khatacollateralselection WHERE operation_id=NEW.id AND role='OUT')
    OR EXISTS(SELECT 1 FROM loans_khatacollateralselection WHERE operation_id=NEW.id AND role<>'OUT')
    OR jsonb_array_length(NEW.evidence->'valuations')<>(SELECT count(*) FROM loans_khatacollateralvaluation WHERE operation_id=NEW.id)
    OR (SELECT count(*) FROM loans_khata_correction_items(NEW.correction_of_id,NEW.sequence))<>(SELECT count(*) FROM loans_khatacollateralvaluation WHERE operation_id=NEW.id)
    OR EXISTS(SELECT 1 FROM loans_khata_correction_items(NEW.correction_of_id,NEW.sequence) k
      WHERE NOT EXISTS(SELECT 1 FROM loans_khatacollateralvaluation WHERE operation_id=NEW.id AND item_id=k))
    OR EXISTS(SELECT 1 FROM loans_khatacollateralvaluation v JOIN loans_khatacollateralitem i ON i.id=v.item_id
      WHERE v.operation_id=NEW.id GROUP BY i.metal HAVING count(DISTINCT v.rate_id)>1)
  THEN RAISE EXCEPTION 'Exchange correction must preserve complete valuations and replacement reservations'; END IF;
  SELECT ltv INTO fraction FROM loans_khataagreementrevision WHERE id=NEW.agreement_id;
  SELECT p.principal INTO principal FROM loans_khata_position(NEW.account_id,NEW.sequence) p;
  SELECT COALESCE(sum(v.value),0) INTO retained FROM loans_khatacollateralvaluation v WHERE v.operation_id=NEW.id
    AND NOT EXISTS(SELECT 1 FROM loans_khatacollateralselection m WHERE m.operation_id=NEW.id AND m.item_id=v.item_id AND m.role='OUT');
  IF principal>floor(retained*fraction*100)/100 THEN RAISE EXCEPTION 'Exchange correction retained collateral LTV failed'; END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER khata_correction_guard BEFORE INSERT ON loans_khataoperation FOR EACH ROW EXECUTE FUNCTION loans_khata_correction_guard();
CREATE CONSTRAINT TRIGGER khata_correction_complete AFTER INSERT ON loans_khataoperation DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION loans_khata_correction_complete();
"""


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0037_khata_custody_settlement'),
        ('orgs', '0010_storage_inventory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='khatacollateralselection',
            name='khata_selection_role_once',
        ),
        migrations.RemoveConstraint(
            model_name='khataoperation',
            name='khata_op_shape_valid',
        ),
        migrations.AddField(
            model_name='khataoperation',
            name='correction_of',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrected_by', to='loans.khataoperation'),
        ),
        migrations.AlterField(
            model_name='khataoperation',
            name='kind',
            field=models.CharField(choices=[('APPROVE', 'Approve opening'), ('WITHDRAW', 'Withdrawal'), ('DEPOSIT', 'Collateral received'), ('RETURN', 'Unopened collateral returned'), ('PHOTO', 'Collateral photograph'), ('ACCRUE', 'Finalize completed interest periods'), ('INTEREST', 'Interest received'), ('TERMS_OK', 'Approve agreement change'), ('REVISE', 'Activate agreement change'), ('EXCHANGE', 'Collateral exchange'), ('HANDOVER', 'Reserved collateral handed over'), ('SETTLE', 'Financial settlement'), ('CORRECT', 'Compensating correction')], max_length=8),
        ),
        migrations.AddConstraint(
            model_name='khataoperation',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gte', 1), models.Q(models.Q(('agreement__isnull', False), ('amount__gt', 0), ('approval__isnull', False), ('item__isnull', True), ('kind', 'WITHDRAW')), models.Q(('agreement__isnull', False), ('amount', 0), ('approval__isnull', True), ('item__isnull', True), ('kind', 'APPROVE')), models.Q(('agreement__isnull', True), ('amount', 0), ('approval__isnull', True), ('item__isnull', True), ('kind', 'DEPOSIT')), models.Q(('agreement__isnull', True), ('amount', 0), ('approval__isnull', True), ('item__isnull', True), ('kind', 'ACCRUE'), ('policy__isnull', True)), models.Q(('agreement__isnull', True), ('amount__gt', 0), ('approval__isnull', True), ('item__isnull', True), ('kind', 'INTEREST'), ('policy__isnull', True)), models.Q(('agreement__isnull', False), ('amount', 0), ('approval__isnull', True), ('item__isnull', True), ('kind', 'TERMS_OK'), ('policy__isnull', True)), models.Q(('agreement__isnull', False), ('amount__gte', 0), ('approval__isnull', False), ('item__isnull', True), ('kind', 'REVISE'), ('policy__isnull', True)), models.Q(('agreement__isnull', False), ('amount', 0), ('approval__isnull', True), ('item__isnull', True), ('kind', 'EXCHANGE')), models.Q(('agreement__isnull', True), ('amount', 0), ('approval__isnull', True), ('item__isnull', False), ('kind', 'HANDOVER'), ('policy__isnull', True)), models.Q(('agreement__isnull', False), ('amount__gte', 0), ('approval__isnull', True), ('item__isnull', True), ('kind', 'SETTLE'), ('policy__isnull', True)), models.Q(('amount__gte', 0), ('approval__isnull', True), ('item__isnull', True), ('kind', 'CORRECT'), ('policy__isnull', True)), models.Q(('agreement__isnull', True), ('amount', 0), ('approval__isnull', True), ('item__isnull', False), ('kind__in', ('RETURN', 'PHOTO'))), _connector='OR')), name='khata_op_shape_valid'),
        ),
        migrations.AddConstraint(
            model_name='khataoperation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('correction_of__isnull', False), ('kind', 'CORRECT')), models.Q(models.Q(('kind', 'CORRECT'), _negated=True), ('correction_of__isnull', True)), _connector='OR'), name='khata_correction_source_valid'),
        ),
    ]

    operations += [migrations.RunSQL(
        HELPERS + ELIGIBLE + DUE + OPENING + COMPLETE + INTEREST + CUSTODY + CUSTODY_COMPLETE + GUARDS,
        """
        DROP TRIGGER khata_correction_complete ON loans_khataoperation;
        DROP TRIGGER khata_correction_guard ON loans_khataoperation;
        DROP FUNCTION loans_khata_correction_complete();
        DROP FUNCTION loans_khata_correction_guard();
        """ + previous.OPENING + previous.COMPLETE + previous.INTEREST
        + function(previous.GUARDS, "loans_khata_custody_guard") + function(previous.GUARDS, "loans_khata_custody_complete")
        + previous.HELPERS[previous.HELPERS.index("CREATE FUNCTION loans_khata_eligible"):previous.HELPERS.index("CREATE FUNCTION loans_khata_closing_segments")].replace("CREATE FUNCTION", "CREATE OR REPLACE FUNCTION", 1)
        + previous.HELPERS[previous.HELPERS.index("CREATE FUNCTION loans_khata_due"):].replace("CREATE FUNCTION", "CREATE OR REPLACE FUNCTION", 1) + """
        DROP FUNCTION loans_khata_correction_items(bigint,integer);
        DROP FUNCTION loans_khata_correction_dependencies(bigint,integer);
        DROP FUNCTION loans_khata_effective_operation(bigint,integer);
        """,
    )]
