# Generated by Django 6.0.3 on 2026-08-10 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0037_loandocumentprintprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandocumentissue',
            name='print_profile_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='loandocumentissue',
            name='print_profile_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='loandocumentissue',
            name='print_profile_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='loans.loandocumentprintprofilerevision'),
        ),
        migrations.AddField(
            model_name='loandocumentissue',
            name='print_profile_source_scope',
            field=models.CharField(blank=True, choices=[('LEGACY_LAYOUT', 'Legacy embedded layout'), ('SERIES', 'Series assignment'), ('WORKSPACE', 'Workspace assignment'), ('BUILT_IN', 'Built-in fallback')], max_length=16),
        ),
        migrations.AddField(
            model_name='loandocumentissue',
            name='print_profile_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
