# Generated by Django 6.0.3 on 2026-08-11 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_legacy_product_versions(apps, schema_editor):
    PawnLoan = apps.get_model("loans", "PawnLoan")
    LoanProduct = apps.get_model("loans", "LoanProduct")
    LoanProductVersion = apps.get_model("loans", "LoanProductVersion")
    for workspace_id in PawnLoan.objects.filter(product_version__isnull=True).values_list(
        "workspace_id", flat=True
    ).distinct():
        product, _ = LoanProduct.objects.get_or_create(
            workspace_id=workspace_id,
            code="LEGACY-UNSPECIFIED",
            defaults={"name": "Legacy loan contract (unspecified)", "is_active": False},
        )
        version, _ = LoanProductVersion.objects.get_or_create(
            product_id=product.pk,
            version=1,
            defaults={
                "status": "RETIRED",
                "repayment_structure": "LEGACY_UNSPECIFIED",
                "amortisation_method": "NONE",
                "payment_frequency": "AT_MATURITY",
                "minimum_tenor_months": 1,
                "maximum_tenor_months": 600,
                "operational_grace_days": 0,
                "extra_payment_rule": "NOT_APPLICABLE",
                "calculation_contract_version": "LEGACY-PERIOD-OPENING-V1",
            },
        )
        PawnLoan.objects.filter(
            workspace_id=workspace_id, product_version__isnull=True
        ).update(product_version_id=version.pk)


def reject_reverse_with_product_references(apps, schema_editor):
    PawnLoan = apps.get_model("loans", "PawnLoan")
    if PawnLoan.objects.exists():
        raise RuntimeError(
            "Cannot reverse loan-product backfill while PawnLoan contracts reference it."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0038_add_issue_print_profile_provenance'),
        ('orgs', '0024_alter_auditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_products_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_products_updated', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_products', to='orgs.company')),
            ],
            options={
                'ordering': ('workspace_id', 'code'),
            },
        ),
        migrations.CreateModel(
            name='LoanProductVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('RETIRED', 'Retired')], db_index=True, default='DRAFT', max_length=12)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('available_until', models.DateField(blank=True, null=True)),
                ('repayment_structure', models.CharField(choices=[('SINGLE_PAYMENT_BULLET', 'Single Payment Bullet'), ('PERIODIC_INTEREST_BULLET', 'Periodic Interest Bullet'), ('FLEXIBLE_PARTIAL_PAYMENT', 'Flexible Partial Payment'), ('INSTALLMENT', 'Installment'), ('LEGACY_UNSPECIFIED', 'Legacy Unspecified')], max_length=32)),
                ('amortisation_method', models.CharField(choices=[('NONE', 'None'), ('EMI', 'Emi'), ('EQUAL_PRINCIPAL', 'Equal Principal')], default='NONE', max_length=24)),
                ('payment_frequency', models.CharField(choices=[('AT_MATURITY', 'At Maturity'), ('MONTHLY', 'Monthly'), ('FLEXIBLE', 'Flexible')], max_length=16)),
                ('minimum_tenor_months', models.PositiveIntegerField(default=1)),
                ('maximum_tenor_months', models.PositiveIntegerField()),
                ('operational_grace_days', models.PositiveSmallIntegerField(default=3)),
                ('extra_payment_rule', models.CharField(choices=[('NOT_APPLICABLE', 'Not Applicable'), ('REDUCE_PRINCIPAL', 'Reduce Principal'), ('KEEP_PAYMENT_SHORTEN_TENURE', 'Keep Payment Shorten Tenure')], max_length=32)),
                ('calculation_contract_version', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_product_versions_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='loans.loanproduct')),
            ],
            options={
                'ordering': ('product_id', 'version'),
            },
        ),
        migrations.AddField(
            model_name='pawnloan',
            name='product_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pawn_loans', to='loans.loanproductversion'),
        ),
        migrations.AddIndex(
            model_name='loanproduct',
            index=models.Index(fields=['workspace', 'is_active'], name='loans_product_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='loanproduct',
            constraint=models.UniqueConstraint(fields=('workspace', 'code'), name='loans_product_workspace_code_uniq'),
        ),
        migrations.AddIndex(
            model_name='loanproductversion',
            index=models.Index(fields=['product', 'status', 'available_from'], name='loans_product_version_ready_idx'),
        ),
        migrations.AddConstraint(
            model_name='loanproductversion',
            constraint=models.UniqueConstraint(fields=('product', 'version'), name='loans_product_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='loanproductversion',
            constraint=models.CheckConstraint(condition=models.Q(('maximum_tenor_months__gte', models.F('minimum_tenor_months'))), name='loans_product_tenor_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='loanproductversion',
            constraint=models.CheckConstraint(condition=models.Q(('operational_grace_days__lte', 30)), name='loans_product_grace_reasonable'),
        ),
        migrations.RunPython(
            backfill_legacy_product_versions,
            reject_reverse_with_product_references,
        ),
        migrations.AlterField(
            model_name='pawnloan',
            name='product_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pawn_loans', to='loans.loanproductversion'),
        ),
    ]
