# Generated by Django 6.1.1 on 2026-10-01 15:09

import apps.tenant_apps.loans.models.khata
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from apps.tenancy.rls import EnableWorkspaceRLS


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0038_khata_corrections'),
        ('orgs', '0010_storage_inventory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KhataDocumentIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('OPERATION', 'Source document'), ('STATEMENT', 'Dated statement')], max_length=9)),
                ('as_of', models.DateField()),
                ('source_sequence', models.PositiveIntegerField()),
                ('request_key', models.UUIDField()),
                ('request_sha256', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('payload_sha256', models.CharField(max_length=64)),
                ('renderer_version', models.CharField(max_length=24)),
                ('artifact', models.FileField(max_length=255, upload_to=apps.tenant_apps.loans.models.khata.khata_document_path)),
                ('artifact_sha256', models.CharField(max_length=64)),
                ('byte_size', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_issues', to='loans.khataaccount')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_issues', to='loans.khataoperation')),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
                'constraints': [models.UniqueConstraint(fields=('workspace', 'request_key'), name='khata_document_request_uniq'), models.CheckConstraint(condition=models.Q(('byte_size__gt', 0)), name='khata_document_bytes_positive'), models.CheckConstraint(condition=models.Q(models.Q(('kind', 'OPERATION'), ('source_operation__isnull', False)), models.Q(('kind', 'STATEMENT'), ('source_operation__isnull', True)), _connector='OR'), name='khata_document_source_valid')],
            },
        ),
        EnableWorkspaceRLS("KhataDocumentIssue"),
        migrations.RunSQL(
            """
            CREATE FUNCTION loans_khata_document_guard() RETURNS trigger LANGUAGE plpgsql AS $$
            DECLARE a loans_khataaccount%ROWTYPE; o loans_khataoperation%ROWTYPE; expected_revision bigint; position_row record; series_license bigint;
            BEGIN
              IF TG_OP <> 'INSERT' THEN
                RAISE EXCEPTION 'Issued khata documents are immutable';
              END IF;
              SELECT * INTO a FROM loans_khataaccount WHERE id=NEW.account_id AND workspace_id=NEW.workspace_id;
              IF NOT FOUND THEN RAISE EXCEPTION 'Khata document account must match its workspace'; END IF;
              PERFORM 1 FROM loans_khataaccount WHERE id=a.id FOR UPDATE;
              IF NEW.request_sha256 !~ '^[a-f0-9]{64}$' OR NEW.payload_sha256 !~ '^[a-f0-9]{64}$'
                OR NEW.artifact_sha256 !~ '^[a-f0-9]{64}$' OR NEW.renderer_version <> 'khata-a4-v1'
                OR NEW.artifact <> 'loans/khata/'||NEW.workspace_id||'/documents/'||NEW.account_id||'/'||NEW.request_key||'.pdf'
                OR (NEW.payload->>'schema') IS DISTINCT FROM 'khata-document/1'
                OR (NEW.payload->>'workspace_id') IS DISTINCT FROM NEW.workspace_id::text
                OR (NEW.payload->>'account_id') IS DISTINCT FROM NEW.account_id::text
                OR (NEW.payload->>'account_number') IS DISTINCT FROM a.account_number
                OR (NEW.payload->'borrower'->>'id') IS DISTINCT FROM a.borrower_id::text
                OR (NEW.payload->>'kind') IS DISTINCT FROM NEW.kind
                OR (NEW.payload->>'as_of') IS DISTINCT FROM NEW.as_of::text
                OR (NEW.payload->>'source_sequence') IS DISTINCT FROM NEW.source_sequence::text
              THEN RAISE EXCEPTION 'Khata document metadata or identity is invalid'; END IF;
              IF NEW.kind='OPERATION' THEN
                SELECT * INTO o FROM loans_khataoperation WHERE id=NEW.source_operation_id
                  AND account_id=NEW.account_id AND workspace_id=NEW.workspace_id;
                IF NOT FOUND OR o.sequence <> NEW.source_sequence OR o.business_date <> NEW.as_of
                  OR o.kind NOT IN ('APPROVE','WITHDRAW','INTEREST','TERMS_OK','REVISE','EXCHANGE','HANDOVER','RETURN','SETTLE','CORRECT','DEPOSIT')
                  OR (NEW.payload->'source'->>'id') IS DISTINCT FROM o.id::text
                  OR (NEW.payload->'source'->>'kind') IS DISTINCT FROM o.kind
                  OR (NEW.payload->'source'->>'sequence') IS DISTINCT FROM o.sequence::text
                  OR (NEW.payload->'source'->>'date') IS DISTINCT FROM o.business_date::text
                  OR (NEW.payload->'source'->>'amount') IS DISTINCT FROM o.amount::text
                  OR (NEW.payload->'source'->>'interest_amount') IS DISTINCT FROM o.interest_amount::text
                  OR (NEW.payload->'source'->'evidence') IS DISTINCT FROM o.evidence
                THEN RAISE EXCEPTION 'Khata document must preserve its own typed source'; END IF;
              ELSE
                IF NEW.source_sequence <> COALESCE((SELECT max(sequence) FROM loans_khataoperation WHERE account_id=a.id),0)
                  OR NEW.payload->'source' IS DISTINCT FROM 'null'::jsonb
                THEN RAISE EXCEPTION 'Khata statement must snapshot the current source sequence'; END IF;
              END IF;
              SELECT * INTO position_row FROM loans_khata_position(a.id, NEW.source_sequence+1);
              IF (NEW.payload->>'principal')::numeric IS DISTINCT FROM position_row.principal
                OR (NEW.payload->>'unused')::numeric IS DISTINCT FROM position_row.unused
              THEN RAISE EXCEPTION 'Khata document position must match its source prefix'; END IF;
              SELECT license_id INTO series_license FROM loans_khataseries WHERE id=a.series_id;
              IF series_license IS NULL THEN
                IF NEW.payload->'license' IS DISTINCT FROM 'null'::jsonb
                THEN RAISE EXCEPTION 'Independent khata documents cannot claim a licence'; END IF;
              ELSE
                IF (NEW.payload->'license'->>'id') IS DISTINCT FROM series_license::text
                  OR (NEW.payload->'license'->>'revision_id' IS NOT NULL AND NOT EXISTS
                    (SELECT 1 FROM loans_loanlicenserevision r WHERE r.id=(NEW.payload->'license'->>'revision_id')::bigint
                      AND r.license_id=series_license AND r.workspace_id=NEW.workspace_id))
                THEN RAISE EXCEPTION 'Khata document licence evidence must match its series'; END IF;
              END IF;
              IF NEW.kind='OPERATION' AND o.agreement_id IS NOT NULL THEN
                expected_revision := o.agreement_id;
              ELSE
                SELECT agreement_id INTO expected_revision FROM loans_khataoperation
                  WHERE account_id=a.id AND sequence<=NEW.source_sequence
                    AND kind IN ('WITHDRAW','REVISE') ORDER BY sequence DESC LIMIT 1;
                IF expected_revision IS NULL THEN
                  IF NEW.kind='STATEMENT' THEN
                    SELECT id INTO expected_revision FROM loans_khataagreementrevision
                      WHERE account_id=a.id ORDER BY number DESC LIMIT 1;
                  ELSE
                    SELECT agreement_id INTO expected_revision FROM loans_khataoperation
                      WHERE account_id=a.id AND sequence<=NEW.source_sequence
                        AND kind='APPROVE' ORDER BY sequence DESC LIMIT 1;
                  END IF;
                END IF;
              END IF;
              IF (NEW.payload->'agreement'->>'id') IS DISTINCT FROM expected_revision::text
              THEN RAISE EXCEPTION 'Khata document must retain the effective source agreement'; END IF;
              IF NOT EXISTS (SELECT 1 FROM loans_khataagreementrevision r
                WHERE r.id=(NEW.payload->'agreement'->>'id')::bigint AND r.account_id=a.id AND r.workspace_id=NEW.workspace_id
                  AND r.lender_name=NEW.payload->'agreement'->>'lender_name'
                  AND r.lender_address=NEW.payload->'agreement'->>'lender_address'
                  AND r.number::text=NEW.payload->'agreement'->>'number'
                  AND r.agreed_limit::text=NEW.payload->'agreement'->>'agreed_limit'
                  AND r.monthly_rate::text=NEW.payload->'agreement'->>'monthly_rate'
                  AND r.ltv::text=NEW.payload->'agreement'->>'ltv'
                  AND r.frequency=NEW.payload->'agreement'->>'frequency'
                  AND r.contract_version=NEW.payload->'agreement'->>'contract_version')
              THEN RAISE EXCEPTION 'Khata document lender must come from its own agreement'; END IF;
              RETURN NEW;
            END $$;
            CREATE TRIGGER khata_document_guard BEFORE INSERT OR UPDATE OR DELETE ON loans_khatadocumentissue
              FOR EACH ROW EXECUTE FUNCTION loans_khata_document_guard();
            """,
            """
            DROP TRIGGER khata_document_guard ON loans_khatadocumentissue;
            DROP FUNCTION loans_khata_document_guard();
            """,
        ),
    ]
