# Generated by Django 6.0.3 on 2026-08-11 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0039_loan_products_and_versions'),
        ('orgs', '0024_alter_auditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RepaymentScheduleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('contract_version', models.CharField(max_length=40)),
                ('fingerprint', models.CharField(max_length=64)),
                ('disbursed_on', models.DateField()),
                ('maturity_date', models.DateField()),
                ('principal', models.DecimalField(decimal_places=4, max_digits=18)),
                ('contractual_interest', models.DecimalField(decimal_places=4, max_digits=18)),
                ('rounding_adjustment', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repayment_schedule_versions_created', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayment_schedules', to='loans.pawnloan')),
                ('source_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='repayment_schedule', to='loans.pawnloanaccountingevent')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='loans.repaymentscheduleversion')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayment_schedule_versions', to='orgs.company')),
            ],
            options={
                'ordering': ('loan_id', 'version'),
            },
        ),
        migrations.CreateModel(
            name='RepaymentObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('due_date', models.DateField(db_index=True)),
                ('principal_due', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('interest_due', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('opening_principal', models.DecimalField(decimal_places=4, max_digits=18)),
                ('closing_principal', models.DecimalField(decimal_places=4, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayment_obligations', to='loans.pawnloan')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayment_obligations', to='orgs.company')),
                ('schedule_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligations', to='loans.repaymentscheduleversion')),
            ],
            options={
                'ordering': ('due_date', 'sequence'),
            },
        ),
        migrations.CreateModel(
            name='ObligationAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(choices=[('PRINCIPAL', 'Principal'), ('INTEREST', 'Interest')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('allocation_order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obligation_allocations_created', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligation_allocations', to='loans.pawnloan')),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='loans.obligationallocation')),
                ('source_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligation_allocations', to='loans.pawnloanaccountingevent')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligation_allocations', to='orgs.company')),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='loans.repaymentobligation')),
            ],
            options={
                'ordering': ('source_event_id', 'allocation_order'),
                'indexes': [models.Index(fields=['workspace', 'loan', 'component'], name='loans_allocation_component_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_event', 'allocation_order'), name='loans_allocation_event_order_uniq'), models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='loans_allocation_amount_nonzero')],
            },
        ),
        migrations.AddIndex(
            model_name='repaymentscheduleversion',
            index=models.Index(fields=['workspace', 'loan', 'version'], name='loans_schedule_workspace_idx'),
        ),
        migrations.AddConstraint(
            model_name='repaymentscheduleversion',
            constraint=models.UniqueConstraint(fields=('loan', 'version'), name='loans_schedule_loan_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='repaymentscheduleversion',
            constraint=models.UniqueConstraint(fields=('loan', 'fingerprint'), name='loans_schedule_loan_fingerprint_uniq'),
        ),
        migrations.AddConstraint(
            model_name='repaymentscheduleversion',
            constraint=models.CheckConstraint(condition=models.Q(('principal__gt', 0)), name='loans_schedule_principal_positive'),
        ),
        migrations.AddConstraint(
            model_name='repaymentscheduleversion',
            constraint=models.CheckConstraint(condition=models.Q(('contractual_interest__gte', 0)), name='loans_schedule_interest_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='repaymentscheduleversion',
            constraint=models.CheckConstraint(condition=models.Q(('maturity_date__gte', models.F('disbursed_on'))), name='loans_schedule_dates_valid'),
        ),
        migrations.AddIndex(
            model_name='repaymentobligation',
            index=models.Index(fields=['workspace', 'loan', 'due_date'], name='loans_obligation_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='repaymentobligation',
            constraint=models.UniqueConstraint(fields=('schedule_version', 'sequence'), name='loans_obligation_schedule_sequence_uniq'),
        ),
        migrations.AddConstraint(
            model_name='repaymentobligation',
            constraint=models.CheckConstraint(condition=models.Q(('principal_due__gte', 0)), name='loans_obligation_principal_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='repaymentobligation',
            constraint=models.CheckConstraint(condition=models.Q(('interest_due__gte', 0)), name='loans_obligation_interest_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='repaymentobligation',
            constraint=models.CheckConstraint(condition=models.Q(('opening_principal__gte', 0)), name='loans_obligation_opening_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='repaymentobligation',
            constraint=models.CheckConstraint(condition=models.Q(('closing_principal__gte', 0)), name='loans_obligation_closing_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='repaymentobligation',
            constraint=models.CheckConstraint(condition=models.Q(('principal_due__gt', 0), ('interest_due__gt', 0), _connector='OR'), name='loans_obligation_amount_positive'),
        ),
    ]
