# Generated by Django 6.0.3 on 2026-08-11 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0040_repayment_obligations'),
        ('orgs', '0024_alter_auditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RepaymentScheduleChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('TERMINATE', 'Terminate'), ('REACTIVATE', 'Reactivate')], max_length=12)),
                ('effective_date', models.DateField()),
                ('reason', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repayment_schedule_changes_created', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayment_schedule_changes', to='loans.pawnloan')),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='loans.repaymentschedulechange')),
                ('schedule_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='loans.repaymentscheduleversion')),
                ('source_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='repayment_schedule_change', to='loans.pawnloanaccountingevent')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayment_schedule_changes', to='orgs.company')),
            ],
            options={
                'ordering': ('effective_date', 'pk'),
                'indexes': [models.Index(fields=['workspace', 'loan', 'effective_date'], name='loans_schedule_change_idx')],
            },
        ),
    ]
