# Generated by Django 6.0.3 on 2026-08-11 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_legacy_appraisals(apps, schema_editor):
    Item = apps.get_model('loans', 'PawnCollateralItem')
    Appraisal = apps.get_model('loans', 'CollateralAppraisal')
    for item in Item.objects.filter(latest_appraised_value__isnull=False).select_related('loan').iterator():
        Appraisal.objects.create(
            workspace_id=item.loan.workspace_id,
            collateral_item_id=item.pk,
            version=1,
            effective_at=item.updated_at,
            appraised_value=item.latest_appraised_value,
            status='APPROVED',
            method='LEGACY_LATEST_APPRAISED_VALUE',
            evidence_reference=f'PawnCollateralItem:{item.pk}',
            review_notes='Backfilled from the pre-history latest_appraised_value field.',
        )


def remove_legacy_appraisals(apps, schema_editor):
    Appraisal = apps.get_model('loans', 'CollateralAppraisal')
    Appraisal.objects.filter(method='LEGACY_LATEST_APPRAISED_VALUE').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0041_schedule_termination_evidence'),
        ('orgs', '0024_alter_auditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollateralAppraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('effective_at', models.DateTimeField(db_index=True)),
                ('appraised_value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISPUTED', 'Disputed')], default='APPROVED', max_length=12)),
                ('method', models.CharField(max_length=80)),
                ('evidence_reference', models.CharField(blank=True, max_length=255)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collateral_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appraisals', to='loans.pawncollateralitem')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collateral_appraisals_created', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='loans.collateralappraisal')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collateral_appraisals', to='orgs.company')),
            ],
            options={
                'ordering': ('collateral_item_id', 'version'),
                'indexes': [models.Index(fields=['workspace', 'collateral_item', 'effective_at', 'status'], name='loans_appraisal_asof_idx')],
                'constraints': [models.UniqueConstraint(fields=('collateral_item', 'version'), name='loans_appraisal_item_version_uniq'), models.CheckConstraint(condition=models.Q(('appraised_value__gt', 0)), name='loans_appraisal_value_positive')],
            },
        ),
        migrations.RunPython(backfill_legacy_appraisals, remove_legacy_appraisals),
    ]
