# Generated by Django 6.0.3 on 2026-08-11 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0042_collateralappraisal'),
        ('orgs', '0024_alter_auditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanMonitoringPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('effective_from', models.DateField()),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('compliance_profile', models.CharField(max_length=120)),
                ('maturity_warning_days', models.PositiveSmallIntegerField(default=30)),
                ('operational_grace_days', models.PositiveSmallIntegerField(default=3)),
                ('dpd_watch_threshold', models.PositiveSmallIntegerField(default=1)),
                ('dpd_substandard_threshold', models.PositiveSmallIntegerField(default=90)),
                ('ltv_warning_ratio', models.DecimalField(decimal_places=6, max_digits=7)),
                ('ltv_breach_ratio', models.DecimalField(decimal_places=6, max_digits=7)),
                ('ltv_critical_ratio', models.DecimalField(decimal_places=6, max_digits=7)),
                ('rate_freshness_days', models.PositiveSmallIntegerField(default=7)),
                ('appraisal_freshness_days', models.PositiveSmallIntegerField(default=90)),
                ('eligible_custody_states', models.JSONField(default=list)),
                ('severity_mapping', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_monitoring_policies_created', to=settings.AUTH_USER_MODEL)),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_policies', to='loans.loanlicense')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_monitoring_policies', to='orgs.company')),
            ],
            options={
                'ordering': ('workspace_id', 'license_id', 'effective_from', 'version'),
                'indexes': [models.Index(fields=['workspace', 'license', 'effective_from', 'effective_until'], name='loans_monitor_policy_asof_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'license', 'version'), name='loans_monitor_policy_scope_version_uniq', nulls_distinct=False), models.CheckConstraint(condition=models.Q(('effective_until__isnull', True), ('effective_until__gte', models.F('effective_from')), _connector='OR'), name='loans_monitor_policy_dates_valid'), models.CheckConstraint(condition=models.Q(('ltv_warning_ratio__gt', 0), ('ltv_warning_ratio__lte', 1)), name='loans_monitor_ltv_warning_range'), models.CheckConstraint(condition=models.Q(('ltv_breach_ratio__gt', 0), ('ltv_breach_ratio__lte', 1)), name='loans_monitor_ltv_breach_range'), models.CheckConstraint(condition=models.Q(('ltv_critical_ratio__gt', 0)), name='loans_monitor_ltv_critical_positive')],
            },
        ),
    ]
