# Generated by Django 6.0.3 on 2026-08-11 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0043_loanmonitoringpolicy'),
        ('orgs', '0024_alter_auditlog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRiskSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of_date', models.DateField()),
                ('exposure', models.DecimalField(decimal_places=4, max_digits=18, null=True)),
                ('due', models.DecimalField(decimal_places=4, max_digits=18, null=True)),
                ('overdue', models.DecimalField(decimal_places=4, max_digits=18, null=True)),
                ('days_past_due', models.PositiveIntegerField(null=True)),
                ('days_to_maturity', models.IntegerField(null=True)),
                ('collateral_value', models.DecimalField(decimal_places=4, max_digits=18, null=True)),
                ('ltv_ratio', models.DecimalField(decimal_places=8, max_digits=12, null=True)),
                ('performance_class', models.CharField(blank=True, max_length=24)),
                ('severity', models.CharField(blank=True, max_length=16)),
                ('action_hint', models.CharField(blank=True, max_length=32)),
                ('flags', models.JSONField(default=list)),
                ('explanations', models.JSONField(default=list)),
                ('policy_identity', models.CharField(blank=True, max_length=255)),
                ('assessment_fingerprint', models.CharField(blank=True, max_length=64)),
                ('input_fingerprint', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('CURRENT', 'Current'), ('STALE', 'Stale'), ('ERROR', 'Error')], db_index=True, default='STALE', max_length=12)),
                ('error_message', models.TextField(blank=True)),
                ('assessed_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_snapshot', to='loans.pawnloan')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_risk_snapshots', to='orgs.company')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'status', 'severity'], name='loans_risk_portfolio_idx'), models.Index(fields=['workspace', 'days_past_due', 'ltv_ratio'], name='loans_risk_metrics_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'loan'), name='loans_risk_snapshot_workspace_loan_uniq'), models.CheckConstraint(condition=models.Q(('status', 'ERROR'), models.Q(('assessment_fingerprint', ''), _negated=True), _connector='OR'), name='loans_risk_current_has_assessment')],
            },
        ),
    ]
