# Generated by Django 6.0.3 on 2026-08-11 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0044_loanrisksnapshot'),
        ('orgs', '0024_alter_auditlog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRiskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=40)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('as_of_date', models.DateField()),
                ('old_value', models.JSONField(default=dict)),
                ('new_value', models.JSONField(default=dict)),
                ('old_fingerprint', models.CharField(blank=True, max_length=64)),
                ('new_fingerprint', models.CharField(blank=True, max_length=64)),
                ('policy_identity', models.CharField(blank=True, max_length=255)),
                ('trigger_key', models.CharField(max_length=64)),
                ('metadata', models.JSONField(default=dict)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_events', to='loans.pawnloan')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transition_events', to='loans.loanrisksnapshot')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_risk_events', to='orgs.company')),
            ],
            options={
                'ordering': ('occurred_at', 'pk'),
                'indexes': [models.Index(fields=['workspace', 'as_of_date', 'event_type'], name='loans_risk_event_portfolio_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'loan', 'trigger_key'), name='loans_risk_event_trigger_uniq')],
            },
        ),
    ]
