# Generated by Django 6.0.3 on 2026-08-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0045_loanriskevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandocumentissue',
            name='document_type',
            field=models.CharField(choices=[('loan_ticket', 'Loan ticket'), ('repayment_receipt', 'Repayment receipt'), ('release_memo', 'Release memo'), ('auction_notice', 'Auction notice'), ('auction_recovery', 'Auction recovery memo'), ('renewal', 'Renewal agreement'), ('loan_kfs_schedule', 'Key facts and repayment schedule')], max_length=32),
        ),
        migrations.AlterField(
            model_name='loandocumentlayout',
            name='document_type',
            field=models.CharField(choices=[('loan_ticket', 'Loan ticket'), ('repayment_receipt', 'Repayment receipt'), ('release_memo', 'Release memo'), ('auction_notice', 'Auction notice'), ('auction_recovery', 'Auction recovery memo'), ('renewal', 'Renewal agreement'), ('loan_kfs_schedule', 'Key facts and repayment schedule')], max_length=32),
        ),
        migrations.AlterField(
            model_name='loandocumentlayoutassignment',
            name='document_type',
            field=models.CharField(choices=[('loan_ticket', 'Loan ticket'), ('repayment_receipt', 'Repayment receipt'), ('release_memo', 'Release memo'), ('auction_notice', 'Auction notice'), ('auction_recovery', 'Auction recovery memo'), ('renewal', 'Renewal agreement'), ('loan_kfs_schedule', 'Key facts and repayment schedule')], max_length=32),
        ),
        migrations.AlterField(
            model_name='loandocumentprintprofile',
            name='document_type',
            field=models.CharField(choices=[('loan_ticket', 'Loan ticket'), ('repayment_receipt', 'Repayment receipt'), ('release_memo', 'Release memo'), ('auction_notice', 'Auction notice'), ('auction_recovery', 'Auction recovery memo'), ('renewal', 'Renewal agreement'), ('loan_kfs_schedule', 'Key facts and repayment schedule')], max_length=32),
        ),
        migrations.AlterField(
            model_name='loandocumentprintprofileassignment',
            name='document_type',
            field=models.CharField(choices=[('loan_ticket', 'Loan ticket'), ('repayment_receipt', 'Repayment receipt'), ('release_memo', 'Release memo'), ('auction_notice', 'Auction notice'), ('auction_recovery', 'Auction recovery memo'), ('renewal', 'Renewal agreement'), ('loan_kfs_schedule', 'Key facts and repayment schedule')], max_length=32),
        ),
    ]
