# Generated by Django 6.0.3 on 2026-08-12 04:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0046_alter_loandocumentissue_document_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='loanproductversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('product',), name='loans_product_one_active_uniq'),
        ),
    ]
