# Generated by Django 6.0.3 on 2026-08-12 06:17

from django.db import migrations


OLD_NAME = 'loans_product_version_ready_idx'
NEW_NAME = 'loans_product_ready_idx'


def _rename_if_needed(apps, schema_editor, source=OLD_NAME, target=NEW_NAME):
    model = apps.get_model('loans', 'LoanProductVersion')
    with schema_editor.connection.cursor() as cursor:
        constraints = schema_editor.connection.introspection.get_constraints(
            cursor, model._meta.db_table
        )
    if target in constraints:
        return
    if source not in constraints:
        raise RuntimeError(
            f'Cannot normalize product readiness index: neither {source} nor {target} exists.'
        )
    quote = schema_editor.quote_name
    schema_editor.execute(
        f'ALTER INDEX {quote(source)} RENAME TO {quote(target)}'
    )


def rename_forward(apps, schema_editor):
    _rename_if_needed(apps, schema_editor)


def rename_backward(apps, schema_editor):
    _rename_if_needed(apps, schema_editor, NEW_NAME, OLD_NAME)


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0047_loanproductversion_loans_product_one_active_uniq'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(rename_forward, rename_backward),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='loanproductversion',
                    new_name=NEW_NAME,
                    old_name=OLD_NAME,
                ),
            ],
        ),
    ]
