# Generated by Django 6.0.3 on 2026-08-12 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0051_collateral_intake_guards'),
    ]

    # Remove the retired feature from Django's model state without destroying
    # any intake rows already captured in deployed tenant schemas.
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.RemoveConstraint(
            model_name='collateralintakebatch',
            name='loans_intake_workspace_ref_uniq',
        ),
        migrations.RemoveField(
            model_name='collateralintakeitem',
            name='batch',
        ),
        migrations.RemoveConstraint(
            model_name='collateralintakegroup',
            name='loans_intake_group_name_uniq',
        ),
        migrations.RemoveField(
            model_name='collateralintakephoto',
            name='item',
        ),
        migrations.RemoveField(
            model_name='collateralintakephoto',
            name='captured_by',
        ),
        migrations.RemoveField(
            model_name='collateralintakebatch',
            name='abandoned_by',
        ),
        migrations.RemoveField(
            model_name='collateralintakebatch',
            name='converted_by',
        ),
        migrations.RemoveField(
            model_name='collateralintakebatch',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='collateralintakebatch',
            name='party',
        ),
        migrations.RemoveField(
            model_name='collateralintakebatch',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='collateralintakebatch',
            name='workspace',
        ),
        migrations.RemoveField(
            model_name='collateralintakegroup',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='collateralintakegroup',
            name='product_version',
        ),
        migrations.RemoveField(
            model_name='collateralintakegroup',
            name='resulting_loan',
        ),
        migrations.RemoveField(
            model_name='collateralintakegroup',
            name='series',
        ),
        migrations.DeleteModel(
            name='CollateralIntakeItem',
        ),
        migrations.DeleteModel(
            name='CollateralIntakePhoto',
        ),
        migrations.DeleteModel(
            name='CollateralIntakeBatch',
        ),
        migrations.DeleteModel(
            name='CollateralIntakeGroup',
        ),
            ],
        ),
    ]
