# Generated by Django 6.0.3 on 2026-08-13 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0054_loanriskalert'),
        ('orgs', '0024_alter_auditlog_action'),
        ('party', '0005_partyportalaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PawnLoanCommunicationConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'Sms'), ('WHATSAPP', 'Whatsapp')], max_length=16)),
                ('service_notices_allowed', models.BooleanField(default=False)),
                ('opted_out_at', models.DateTimeField(blank=True, null=True)),
                ('evidence', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='pawnloannotice',
            name='notification_template_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pawnloannotice',
            name='notification_template_locale',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='pawnloannotice',
            name='notification_template_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pawnloannotice',
            name='source_risk_alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='borrower_notices', to='loans.loanriskalert'),
        ),
        migrations.AddField(
            model_name='pawnloannotice',
            name='source_risk_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='borrower_notices', to='loans.loanriskevent'),
        ),
        migrations.AddConstraint(
            model_name='pawnloannotice',
            constraint=models.UniqueConstraint(condition=models.Q(('source_risk_event__isnull', False)), fields=('source_risk_event', 'notice_kind', 'channel', 'notification_template_version'), name='loans_risk_notice_intent_uniq'),
        ),
        migrations.AddField(
            model_name='pawnloancommunicationconsent',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pawn_loan_communication_consents', to='party.party'),
        ),
        migrations.AddField(
            model_name='pawnloancommunicationconsent',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pawn_loan_communication_consents_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pawnloancommunicationconsent',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pawn_loan_communication_consents', to='orgs.company'),
        ),
        migrations.AddConstraint(
            model_name='pawnloancommunicationconsent',
            constraint=models.UniqueConstraint(fields=('workspace', 'party', 'channel'), name='loans_pawn_notice_consent_uniq'),
        ),
    ]
