# Generated by Django 6.0.3 on 2026-08-13 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0055_pawnloancommunicationconsent_and_more'),
        ('orgs', '0024_alter_auditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PawnLoanCommunicationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_channel', models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp')], default='EMAIL', max_length=16)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('cooldown_days', models.PositiveSmallIntegerField(default=0)),
                ('escalation_dpd', models.PositiveSmallIntegerField(default=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pawn_loan_communication_policies_updated', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pawn_loan_communication_policy', to='orgs.company')),
            ],
        ),
    ]
