# Generated by Django 6.0.3 on 2026-08-16 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0056_pawnloancommunicationpolicy'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pawnloanaccountingoutbox',
            name='loans_outbox_due_idx',
        ),
        migrations.DeleteModel(
            name='PawnLoanAccountingOutbox',
        ),
    ]
