# Generated by Django 6.0.3 on 2026-08-16 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0058_rename_pawnloanaccountingevent_pawnloanevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pawnloanevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pawn_loan_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pawnloanevent',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_events', to='loans.pawnloan'),
        ),
    ]
