# Generated by Django 6.0.3 on 2026-08-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0060_rename_accounting_event_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pawnloanprincipalclosingline',
            options={'ordering': ('loan_event_id', 'allocation_order')},
        ),
        migrations.AlterModelOptions(
            name='pawnloanprincipalopeningline',
            options={'ordering': ('loan_event_id', 'allocation_order')},
        ),
        migrations.AlterModelOptions(
            name='pawnloanrepaymentallocationline',
            options={'ordering': ('loan_event_id', 'allocation_order')},
        ),
        migrations.RemoveConstraint(
            model_name='pawnloanprincipalclosingline',
            name='loans_close_event_item_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='pawnloanprincipalclosingline',
            name='loans_close_event_order_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='pawnloanprincipalopeningline',
            name='loans_open_event_order_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='pawnloanrepaymentallocationline',
            name='loans_repayment_event_item_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='pawnloanrepaymentallocationline',
            name='loans_repayment_event_order_uniq',
        ),
        migrations.AddConstraint(
            model_name='pawnloanprincipalclosingline',
            constraint=models.UniqueConstraint(fields=('loan_event', 'collateral_item'), name='loans_close_event_item_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pawnloanprincipalclosingline',
            constraint=models.UniqueConstraint(fields=('loan_event', 'allocation_order'), name='loans_close_event_order_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pawnloanprincipalopeningline',
            constraint=models.UniqueConstraint(fields=('loan_event', 'allocation_order'), name='loans_open_event_order_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pawnloanrepaymentallocationline',
            constraint=models.UniqueConstraint(fields=('loan_event', 'collateral_item'), name='loans_repayment_event_item_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pawnloanrepaymentallocationline',
            constraint=models.UniqueConstraint(fields=('loan_event', 'allocation_order'), name='loans_repayment_event_order_uniq'),
        ),
    ]
