# Generated by Django 6.0.3 on 2026-08-16 18:28

from django.db import migrations, models


def normalize_cash_recognition(apps, schema_editor):
    LoanPolicySnapshot = apps.get_model("loans", "LoanPolicySnapshot")
    PawnLoanEconomicPolicy = apps.get_model("loans", "PawnLoanEconomicPolicy")
    LoanPolicySnapshot.objects.exclude(accounting_recognition="CASH").update(
        accounting_recognition="CASH"
    )
    PawnLoanEconomicPolicy.objects.exclude(accounting_recognition="CASH").update(
        accounting_recognition="CASH"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0061_alter_pawnloanprincipalclosingline_options_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_cash_recognition, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='loanpolicysnapshot',
            name='accounting_recognition',
            field=models.CharField(choices=[('CASH', 'Cash')], max_length=16),
        ),
        migrations.AlterField(
            model_name='pawnloaneconomicpolicy',
            name='accounting_recognition',
            field=models.CharField(choices=[('CASH', 'Cash')], default='CASH', max_length=16),
        ),
    ]
