# Generated by Django 6.0.3 on 2026-08-16 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0062_alter_loanpolicysnapshot_accounting_recognition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanpolicysnapshot',
            name='accounting_recognition',
        ),
        migrations.RemoveField(
            model_name='pawnloaneconomicpolicy',
            name='accounting_recognition',
        ),
    ]
