# Generated by Django 6.1.1 on 2026-10-06 10:16

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0062_terminal_position_evidence'),
        ('orgs', '0010_storage_inventory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loanoriginationsettings',
            name='maximum_quote_age_days',
            field=models.PositiveSmallIntegerField(default=7, validators=[django.core.validators.MaxValueValidator(32767)]),
        ),
        migrations.AddConstraint(
            model_name='loanoriginationsettings',
            constraint=models.CheckConstraint(condition=models.Q(('maximum_quote_age_days__lte', 32767)), name='loans_origination_quote_age_range'),
        ),
    ]
