# Generated by Django 6.0.3 on 2026-08-16 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0063_remove_loanpolicysnapshot_accounting_recognition_and_more'),
        ('orgs', '0025_alter_company_schema_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingloancancellation',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='fundingloandraftcollateral',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='fundingloandraftterms',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='fundingloanevent',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='fundingloantermssnapshot',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='fundingpledgeitem',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='fundingpledgereversal',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='fundingreturnitem',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='fundingreturnreversal',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='loanchangelog',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='loandocumentlayoutrevision',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='loandocumentprintprofilerevision',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='loanlicenserevision',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='loannumbersequence',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='loanpolicysnapshot',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='loanproductversion',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='loanseries',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='pawncollateralcustodyevent',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='pawncollateralitem',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='pawncollaterallabelissue',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='pawncollateralphoto',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='pawncollateralstoragemovement',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='pawnloanapprovalsnapshot',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='pawnloanauctionitem',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='pawnloanauctionreversal',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='pawnloandisbursalsnapshot',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='pawnloanevent',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='pawnloaninterestaccrual',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='pawnloaninterestaccrualline',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='pawnloanprincipalclosingline',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='pawnloanprincipalopeningline',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='pawnloanreleaseitem',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='pawnloanreleasereversal',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='pawnloanrenewalreversal',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='pawnloanrepaymentallocationline',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='pawnphysicalverificationexpectation',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='pawnphysicalverificationobservation',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='pawnphysicalverificationresolution',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
    ]
