# Generated by Django 5.2.6 on 2026-02-24 12:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0003_alter_customer_options_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("girvi", "add_custody_tracking"),
        ("notify", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        help_text="The ID of the referenced object"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount related to this item (loan amount, invoice total, etc.)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True,
                        help_text="Due date for this item (loan maturity, invoice due date, etc.)",
                        null=True,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="Reference number from the related object (loan_id, invoice_number, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes specific to this item"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Notification Item",
                "verbose_name_plural": "Notification Items",
            },
        ),
        migrations.AlterModelOptions(
            name="noticegroup",
            options={
                "ordering": ["-created"],
                "verbose_name": "Notice Group",
                "verbose_name_plural": "Notice Groups",
            },
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ["-created"],
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
            },
        ),
        migrations.AddField(
            model_name="noticegroup",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="notification",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="contact.customer",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_printed",
            field=models.BooleanField(
                default=False, help_text="Set to True when notification is printed"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="loans",
            field=models.ManyToManyField(
                blank=True,
                help_text="DEPRECATED: Use NotificationItem model instead for generic relationships",
                related_name="notifications",
                to="girvi.givenloan",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="medium_type",
            field=models.CharField(
                choices=[
                    ("E", "Email"),
                    ("P", "Post"),
                    ("W", "Whatsapp"),
                    ("S", "SMS"),
                    ("L", "Letter"),
                ],
                default="E",
                help_text="Channel to use for sending this notification",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.TextField(
                blank=True,
                help_text="Notification message. Auto-generated from template if empty.",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notice_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FR", "First Reminder"),
                    ("SR", "Second Reminder"),
                    ("FN", "Final Notice"),
                    ("LN", "Loan Created"),
                ],
                help_text="DEPRECATED: Use notice_type_config instead for flexible notice types",
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="status",
            field=models.CharField(
                choices=[
                    ("D", "Draft"),
                    ("S", "Sent"),
                    ("Z", "Delivered"),
                    ("A", "Acknowledged"),
                    ("R", "Responded"),
                ],
                default="D",
                help_text="Current status in the notification lifecycle",
                max_length=1,
            ),
        ),
        migrations.CreateModel(
            name="NoticeTypeConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique identifier for this notice type (e.g., LOAN_FIRST_REMINDER, INVOICE_REMINDER)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this notice type", max_length=100
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("LOAN", "Loan/Girvi"),
                            ("SALES", "Sales"),
                            ("PURCHASE", "Purchase"),
                            ("INVENTORY", "Inventory"),
                            ("ACCOUNTING", "Accounting"),
                            ("HR", "Human Resources"),
                            ("GENERAL", "General"),
                        ],
                        help_text="Business module category for grouping notice types",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of when and how this notice type should be used",
                    ),
                ),
                (
                    "sms_template",
                    models.TextField(
                        blank=True,
                        help_text="Default SMS template with {{variable}} placeholders",
                    ),
                ),
                (
                    "whatsapp_template",
                    models.TextField(
                        blank=True,
                        help_text="Default WhatsApp template with {{variable}} placeholders",
                    ),
                ),
                (
                    "email_subject_template",
                    models.CharField(
                        blank=True,
                        help_text="Email subject line template",
                        max_length=200,
                    ),
                ),
                (
                    "email_template",
                    models.TextField(
                        blank=True,
                        help_text="Default email body template with {{variable}} placeholders",
                    ),
                ),
                (
                    "postal_template",
                    models.TextField(
                        blank=True,
                        help_text="Default postal letter template with {{variable}} placeholders",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive notice types won't appear in selection dropdowns",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order in dropdowns (lower numbers first)",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Notice Type Configuration",
                "verbose_name_plural": "Notice Type Configurations",
                "ordering": ["category", "sort_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["category", "is_active"],
                        name="notify_noti_categor_afd71b_idx",
                    ),
                    models.Index(fields=["code"], name="notify_noti_code_aa781e_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="notice_type_config",
            field=models.ForeignKey(
                blank=True,
                help_text="Configurable notice type that supports all business modules",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notifications",
                to="notify.noticetypeconfig",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["status", "created"], name="notify_noti_status_0f2d84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["customer", "notice_type"],
                name="notify_noti_custome_c8ff02_idx",
            ),
        ),
        migrations.AddField(
            model_name="notificationitem",
            name="content_type",
            field=models.ForeignKey(
                help_text="The type of object this item references (e.g., GivenLoan, Invoice, PurchaseOrder)",
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="notificationitem",
            name="notification",
            field=models.ForeignKey(
                help_text="The notification this item belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="notify.notification",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationitem",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="notify_noti_content_d4dd79_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationitem",
            index=models.Index(
                fields=["notification"], name="notify_noti_notific_b87aa7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="notificationitem",
            unique_together={("notification", "content_type", "object_id")},
        ),
    ]
