# Generated by Django 5.2.6 on 2026-02-24 12:44

from django.db import migrations


def noop_forward(apps, schema_editor):
    # Seed moved to apps.orgs.management.commands.seed_tenant_defaults.
    pass


def seed_default_notice_types(apps, schema_editor):
    """
    Seed default notice type configurations for all modules.
    These can be customized by each tenant later.
    """
    NoticeTypeConfig = apps.get_model("notify", "NoticeTypeConfig")

    default_types = [
        # ========== LOAN/GIRVI NOTICE TYPES ==========
        {
            "code": "LOAN_FIRST_REMINDER",
            "name": "First Reminder",
            "category": "LOAN",
            "description": "First reminder for loan payment or renewal",
            "sort_order": 1,
            "sms_template": "Dear {{customer.name}}, this is a first reminder for your loan {{items.0.reference}}. Amount: {{items.0.amount}}. Please contact us.",
            "email_subject_template": "First Reminder - Loan {{items.0.reference}}",
            "email_template": "Dear {{customer.name}},\n\nThis is a first reminder regarding your loan:\n{% for item in items %}\n- Loan ID: {{item.reference}}, Amount: ₹{{item.amount}}, Due: {{item.due_date}}\n{% endfor %}\n\nPlease contact us for repayment or renewal.",
            "postal_template": "Dear {{customer.name}},\n\nThis is a first reminder regarding your loan(s):\n{% for item in items %}\nLoan ID: {{item.reference}}\nAmount: ₹{{item.amount}}\nDue Date: {{item.due_date}}\n{% endfor %}\n\nPlease visit our office or contact us for repayment.",
        },
        {
            "code": "LOAN_SECOND_REMINDER",
            "name": "Second Reminder",
            "category": "LOAN",
            "description": "Second reminder for overdue loan with urgency",
            "sort_order": 2,
            "sms_template": "URGENT: Second reminder for loan {{items.0.reference}}. Amount: ₹{{items.0.amount}}. Please visit immediately.",
            "email_subject_template": "URGENT: Second Reminder - Loan {{items.0.reference}}",
            "email_template": "Dear {{customer.name}},\n\nThis is your SECOND reminder. Your loan(s) are overdue:\n{% for item in items %}\n- Loan ID: {{item.reference}}, Amount: ₹{{item.amount}}, Overdue Since: {{item.due_date}}\n{% endfor %}\n\nImmediate action required. Please contact us.",
            "postal_template": "Dear {{customer.name}},\n\nSECOND REMINDER - URGENT\n\nYour loan(s) are now overdue:\n{% for item in items %}\nLoan ID: {{item.reference}}\nAmount: ₹{{item.amount}}\nOverdue Since: {{item.due_date}}\n{% endfor %}\n\nPlease visit immediately.",
        },
        {
            "code": "LOAN_FINAL_NOTICE",
            "name": "Final Notice",
            "category": "LOAN",
            "description": "Final notice before legal action or auction",
            "sort_order": 3,
            "sms_template": "FINAL NOTICE: Loan {{items.0.reference}} overdue. Legal action pending. Visit immediately.",
            "email_subject_template": "FINAL NOTICE - Loan {{items.0.reference}}",
            "email_template": "Dear {{customer.name}},\n\nFINAL NOTICE\n\nYour loan(s) are severely overdue:\n{% for item in items %}\n- Loan ID: {{item.reference}}, Amount: ₹{{item.amount}}, Overdue Since: {{item.due_date}}\n{% endfor %}\n\nFinal opportunity to clear dues before legal proceedings.",
            "postal_template": "Dear {{customer.name}},\n\nFINAL NOTICE\n\nThis is your final notice before legal action.\n\nOverdue Loans:\n{% for item in items %}\nLoan ID: {{item.reference}}\nAmount: ₹{{item.amount}}\nOverdue Since: {{item.due_date}}\n{% endfor %}\n\nPlease settle immediately.",
        },
        {
            "code": "LOAN_CREATED",
            "name": "Loan Created/Disbursed",
            "category": "LOAN",
            "description": "Welcome notification when new loan is created",
            "sort_order": 4,
            "sms_template": "Your loan {{items.0.reference}} of ₹{{items.0.amount}} has been approved. Thank you!",
            "email_subject_template": "Loan Approved - {{items.0.reference}}",
            "email_template": "Dear {{customer.name}},\n\nYour loan has been successfully approved:\n{% for item in items %}\n- Loan ID: {{item.reference}}\n- Amount: ₹{{item.amount}}\n- Due Date: {{item.due_date}}\n{% endfor %}\n\nThank you for choosing our services.",
            "postal_template": "Dear {{customer.name}},\n\nLoan Approval Confirmation\n\n{% for item in items %}\nLoan ID: {{item.reference}}\nAmount: ₹{{item.amount}}\nDue Date: {{item.due_date}}\n{% endfor %}\n\nThank you!",
        },
        {
            "code": "LOAN_MATURITY_ALERT",
            "name": "Loan Maturity Alert",
            "category": "LOAN",
            "description": "Proactive alert before loan matures",
            "sort_order": 5,
            "sms_template": "Your loan {{items.0.reference}} matures on {{items.0.due_date}}. Please plan repayment.",
            "email_subject_template": "Loan Maturity Alert - {{items.0.reference}}",
            "email_template": "Dear {{customer.name}},\n\nYour loan will mature soon:\n{% for item in items %}\n- Loan ID: {{item.reference}}\n- Amount: ₹{{item.amount}}\n- Maturity Date: {{item.due_date}}\n{% endfor %}\n\nPlease plan for repayment or renewal.",
        },
        # ========== SALES NOTICE TYPES ==========
        {
            "code": "INVOICE_REMINDER",
            "name": "Invoice Payment Reminder",
            "category": "SALES",
            "description": "Reminder for unpaid invoices",
            "sort_order": 10,
            "sms_template": "Invoice {{items.0.reference}} of ₹{{items.0.amount}} is pending. Due: {{items.0.due_date}}",
            "email_subject_template": "Payment Reminder - Invoice {{items.0.reference}}",
            "email_template": "Dear {{customer.name}},\n\nYour invoice(s) are pending payment:\n{% for item in items %}\n- Invoice #: {{item.reference}}\n- Amount: ₹{{item.amount}}\n- Due Date: {{item.due_date}}\n{% endfor %}\n\nPlease pay at your earliest convenience.",
        },
        {
            "code": "SALES_CONFIRMATION",
            "name": "Sale/Order Confirmation",
            "category": "SALES",
            "description": "Confirmation after successful sale",
            "sort_order": 11,
            "sms_template": "Order confirmed! Order #{{items.0.reference}} for ₹{{items.0.amount}}. Thank you!",
            "email_subject_template": "Order Confirmation - {{items.0.reference}}",
            "email_template": "Dear {{customer.name}},\n\nThank you for your order!\n\nOrder Details:\n{% for item in items %}\n- Order #: {{item.reference}}\n- Amount: ₹{{item.amount}}\n{% endfor %}\n\nWe will process your order shortly.",
        },
        {
            "code": "DELIVERY_UPDATE",
            "name": "Delivery Status Update",
            "category": "SALES",
            "description": "Notification about delivery or shipment",
            "sort_order": 12,
            "sms_template": "Your order {{items.0.reference}} is out for delivery. Track your shipment.",
            "email_subject_template": "Delivery Update - Order {{items.0.reference}}",
            "email_template": "Dear {{customer.name}},\n\nYour order is on its way:\n{% for item in items %}\n- Order #: {{item.reference}}\n{% endfor %}\n\nExpected delivery soon.",
        },
        # ========== PURCHASE NOTICE TYPES ==========
        {
            "code": "PO_CREATED",
            "name": "Purchase Order Created",
            "category": "PURCHASE",
            "description": "Notification to vendor when PO is created",
            "sort_order": 20,
            "sms_template": "PO {{items.0.reference}} created for ₹{{items.0.amount}}. Please confirm.",
            "email_subject_template": "Purchase Order - {{items.0.reference}}",
            "email_template": "Dear Vendor,\n\nWe have created a purchase order:\n{% for item in items %}\n- PO #: {{item.reference}}\n- Amount: ₹{{item.amount}}\n{% endfor %}\n\nPlease confirm receipt and delivery schedule.",
        },
        {
            "code": "PO_DELIVERY_REMINDER",
            "name": "PO Delivery Reminder",
            "category": "PURCHASE",
            "description": "Reminder to vendor about pending delivery",
            "sort_order": 21,
            "sms_template": "Reminder: PO {{items.0.reference}} delivery pending. Expected: {{items.0.due_date}}",
            "email_subject_template": "Delivery Reminder - PO {{items.0.reference}}",
            "email_template": "Dear Vendor,\n\nThis is a reminder for pending delivery:\n{% for item in items %}\n- PO #: {{item.reference}}\n- Expected Date: {{item.due_date}}\n{% endfor %}\n\nPlease update us on the status.",
        },
        # ========== INVENTORY NOTICE TYPES ==========
        {
            "code": "STOCK_LOW_ALERT",
            "name": "Low Stock Alert",
            "category": "INVENTORY",
            "description": "Alert when stock falls below threshold",
            "sort_order": 30,
            "sms_template": "Low stock alert for {{items.0.reference}}. Current: {{items.0.amount}} units.",
            "email_subject_template": "Low Stock Alert - {{items.0.reference}}",
            "email_template": "Dear Team,\n\nThe following items are running low:\n{% for item in items %}\n- Item: {{item.reference}}\n- Current Stock: {{item.amount}} units\n{% endfor %}\n\nPlease reorder.",
        },
        {
            "code": "STOCK_REORDER",
            "name": "Stock Reorder Notification",
            "category": "INVENTORY",
            "description": "Notification to supplier for reordering",
            "sort_order": 31,
            "sms_template": "Reorder request for {{items.0.reference}}. Quantity: {{items.0.amount}}",
            "email_subject_template": "Reorder Request - {{items.0.reference}}",
            "email_template": "Dear Supplier,\n\nWe need to reorder:\n{% for item in items %}\n- Item: {{item.reference}}\n- Quantity: {{item.amount}}\n{% endfor %}\n\nPlease confirm delivery schedule.",
        },
        # ========== ACCOUNTING NOTICE TYPES ==========
        {
            "code": "GST_FILING_REMINDER",
            "name": "GST Filing Reminder",
            "category": "ACCOUNTING",
            "description": "Reminder for upcoming GST filing deadline",
            "sort_order": 40,
            "sms_template": "GST filing due on {{items.0.due_date}}. Please prepare documents.",
            "email_subject_template": "GST Filing Reminder - Due {{items.0.due_date}}",
            "email_template": "Dear Customer,\n\nYour GST filing is due on {{items.0.due_date}}.\n\nPlease ensure all documents are ready.\n\nContact us if you need assistance.",
        },
        {
            "code": "STATEMENT_DELIVERY",
            "name": "Account Statement",
            "category": "ACCOUNTING",
            "description": "Monthly or periodic account statement",
            "sort_order": 41,
            "sms_template": "Your account statement for {{items.0.reference}} is ready.",
            "email_subject_template": "Account Statement - {{items.0.reference}}",
            "email_template": "Dear {{customer.name}},\n\nYour account statement is attached.\n\nPeriod: {{items.0.reference}}\n\nPlease review and contact us for any queries.",
        },
        # ========== HR NOTICE TYPES ==========
        {
            "code": "PAYSLIP_DELIVERY",
            "name": "Salary Slip Delivery",
            "category": "HR",
            "description": "Monthly salary slip delivery to employees",
            "sort_order": 50,
            "sms_template": "Your salary for {{items.0.reference}} has been credited. Amount: ₹{{items.0.amount}}",
            "email_subject_template": "Salary Slip - {{items.0.reference}}",
            "email_template": "Dear Employee,\n\nYour salary slip for {{items.0.reference}} is attached.\n\nNet Pay: ₹{{items.0.amount}}\n\nPlease check and confirm receipt.",
        },
        {
            "code": "LEAVE_APPROVED",
            "name": "Leave Approval Notification",
            "category": "HR",
            "description": "Notification when leave is approved",
            "sort_order": 51,
            "sms_template": "Your leave request for {{items.0.reference}} has been approved.",
            "email_subject_template": "Leave Approved - {{items.0.reference}}",
            "email_template": "Dear Employee,\n\nYour leave request has been approved:\n- Dates: {{items.0.reference}}\n- Duration: {{items.0.amount}} days\n\nEnjoy your time off!",
        },
        # ========== GENERAL NOTICE TYPES ==========
        {
            "code": "BIRTHDAY_WISH",
            "name": "Birthday Greeting",
            "category": "GENERAL",
            "description": "Automated birthday wishes to customers",
            "sort_order": 60,
            "sms_template": "Happy Birthday {{customer.name}}! Wishing you a wonderful year ahead!",
            "email_subject_template": "Happy Birthday {{customer.name}}!",
            "email_template": "Dear {{customer.name}},\n\nWishing you a very Happy Birthday!\n\nMay this year bring you joy, success, and prosperity.\n\nWith best wishes,\nYour Team",
        },
        {
            "code": "PROMOTIONAL_CAMPAIGN",
            "name": "Promotional Campaign",
            "category": "GENERAL",
            "description": "Marketing and promotional messages",
            "sort_order": 61,
            "sms_template": "Special offer! {{items.0.reference}}. Visit us today!",
            "email_subject_template": "Special Offer - {{items.0.reference}}",
            "email_template": "Dear {{customer.name}},\n\nWe have an exciting offer for you!\n\n{{items.0.reference}}\n\nVisit us to avail this limited-time offer.",
        },
        {
            "code": "ANNOUNCEMENT",
            "name": "General Announcement",
            "category": "GENERAL",
            "description": "Company announcements and updates",
            "sort_order": 62,
            "sms_template": "Announcement: {{items.0.reference}}",
            "email_subject_template": "Important Announcement - {{items.0.reference}}",
            "email_template": "Dear {{customer.name}},\n\nWe have an important announcement:\n\n{{items.0.reference}}\n\nThank you for your attention.",
        },
    ]

    # Create all notice types
    for notice_data in default_types:
        NoticeTypeConfig.objects.get_or_create(
            code=notice_data["code"], defaults=notice_data
        )


def reverse_seed(apps, schema_editor):
    """Remove all seeded notice types"""
    NoticeTypeConfig = apps.get_model("notify", "NoticeTypeConfig")

    codes = [
        "LOAN_FIRST_REMINDER",
        "LOAN_SECOND_REMINDER",
        "LOAN_FINAL_NOTICE",
        "LOAN_CREATED",
        "LOAN_MATURITY_ALERT",
        "INVOICE_REMINDER",
        "SALES_CONFIRMATION",
        "DELIVERY_UPDATE",
        "PO_CREATED",
        "PO_DELIVERY_REMINDER",
        "STOCK_LOW_ALERT",
        "STOCK_REORDER",
        "GST_FILING_REMINDER",
        "STATEMENT_DELIVERY",
        "PAYSLIP_DELIVERY",
        "LEAVE_APPROVED",
        "BIRTHDAY_WISH",
        "PROMOTIONAL_CAMPAIGN",
        "ANNOUNCEMENT",
    ]

    NoticeTypeConfig.objects.filter(code__in=codes).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("notify", "0002_notificationitem_alter_noticegroup_options_and_more"),
    ]

    operations = [
        migrations.RunPython(noop_forward, reverse_code=migrations.RunPython.noop),
    ]
