# Generated by Django 6.0.3 on 2026-04-07 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0003_seed_default_notice_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal label for this template entry.', max_length=100)),
                ('medium_type', models.CharField(choices=[('E', 'Email'), ('P', 'Post'), ('W', 'Whatsapp'), ('S', 'SMS'), ('L', 'Letter')], help_text='Channel this template should be used for.', max_length=1)),
                ('renderer', models.CharField(choices=[('DJANGO', 'Django/Jinja Template'), ('PDF', 'PDF / Predefined Print Format')], default='DJANGO', help_text='Use PDF for fixed printable formats and Django/Jinja for flexible digital messages.', max_length=10)),
                ('subject_template', models.CharField(blank=True, help_text='Optional subject override for media such as email.', max_length=200)),
                ('body_template', models.TextField(blank=True, help_text='Use Django template syntax such as {{ customer.name }} and {% for item in items %}.')),
                ('pdf_template_key', models.CharField(blank=True, help_text='Optional key for selecting the printable PDF layout implementation.', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Only active templates are considered during renderer selection.')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower values are preferred first when multiple templates exist.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('notice_type_config', models.ForeignKey(help_text='Notice type this template belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to='notify.noticetypeconfig')),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'ordering': ['notice_type_config__category', 'sort_order', 'name'],
                'indexes': [models.Index(fields=['notice_type_config', 'medium_type', 'is_active'], name='notify_noti_notice__aa9f5e_idx')],
                'constraints': [models.UniqueConstraint(fields=('notice_type_config', 'medium_type', 'name'), name='notify_unique_template_name_per_notice_medium')],
            },
        ),
    ]
