# Generated by Django 5.2.6 on 2026-02-27 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_step",
                    models.IntegerField(
                        choices=[
                            (1, "Profile Setup"),
                            (2, "Company Setup"),
                            (3, "Team Setup"),
                            (4, "Feature Tour"),
                            (5, "Complete"),
                        ],
                        default=1,
                        verbose_name="Current Step",
                    ),
                ),
                (
                    "profile_completed",
                    models.BooleanField(
                        default=False, verbose_name="Profile Completed"
                    ),
                ),
                (
                    "company_created",
                    models.BooleanField(default=False, verbose_name="Company Created"),
                ),
                (
                    "team_setup_completed",
                    models.BooleanField(default=False, verbose_name="Team Setup"),
                ),
                (
                    "tour_completed",
                    models.BooleanField(default=False, verbose_name="Tour Completed"),
                ),
                (
                    "is_complete",
                    models.BooleanField(
                        default=False, verbose_name="Onboarding Complete"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed At"
                    ),
                ),
                (
                    "skipped_tour",
                    models.BooleanField(default=False, verbose_name="Skipped Tour"),
                ),
                (
                    "skipped_team",
                    models.BooleanField(default=False, verbose_name="Skipped Team"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_progress",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Onboarding Progress",
                "verbose_name_plural": "Onboarding Progress",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OnboardingChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step", models.IntegerField(verbose_name="Step")),
                (
                    "choice_key",
                    models.CharField(max_length=100, verbose_name="Choice Key"),
                ),
                ("choice_value", models.TextField(verbose_name="Choice Value")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "progress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="onboarding.onboardingprogress",
                        verbose_name="Progress",
                    ),
                ),
            ],
            options={
                "verbose_name": "Onboarding Choice",
                "verbose_name_plural": "Onboarding Choices",
                "ordering": ["step", "created_at"],
            },
        ),
    ]
