# Generated by Django 6.0.3 on 2026-08-16 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('onboarding', '0001_initial'),
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacesetupstate',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setup_states', to='orgs.company', verbose_name='Workspace'),
        ),
        migrations.AddConstraint(
            model_name='workspacesetupstate',
            constraint=models.UniqueConstraint(fields=('user', 'workspace'), name='onboarding_workspace_setup_state_unique_user_workspace'),
        ),
    ]
