# Generated by Django 6.0.3 on 2026-08-16 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('tax_included', models.BooleanField(default=False)),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal', models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze')], default='Gold', max_length=6)),
                ('currency', models.CharField(choices=[('INR', 'INR'), ('USD', 'USD')], default='INR', max_length=3)),
                ('purity', models.CharField(choices=[('24k', '24K'), ('22k', '22K'), ('18k', '18K'), ('14k', '14K'), ('10k', '10K')], default='24k', max_length=3)),
                ('buying_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company')),
                ('rate_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rates.ratesource')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('workspace', 'metal', 'currency', 'timestamp', 'purity'), name='rates_rate_workspace_quote_uniq')],
            },
        ),
    ]
