# Generated by Django 5.1.2 on 2024-12-04 11:24

import django.db.models.deletion
from django.core.management import call_command
from django.db import migrations, models

# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# apps.tenant_apps.rates.migrations.0002_load_metal_rates


def load_fixture(apps, schema_editor):
    call_command("loaddata", "metal_rates.json")


class Migration(migrations.Migration):
    replaces = [
        ("rates", "0001_initial"),
        ("rates", "0002_load_metal_rates"),
        ("rates", "0003_alter_rate_metal"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RateSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("location", models.CharField(max_length=30)),
                ("tax_included", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Rate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metal",
                    models.CharField(
                        choices=[("Gold", "Gold"), ("Silver", "Silver")],
                        default="Gold",
                        max_length=6,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("INR", "INR"), ("USD", "USD")],
                        default="INR",
                        max_length=3,
                    ),
                ),
                (
                    "purity",
                    models.CharField(
                        choices=[
                            ("24k", "24K"),
                            ("22k", "22K"),
                            ("18k", "18K"),
                            ("14k", "14K"),
                            ("10k", "10K"),
                        ],
                        default="24k",
                        max_length=3,
                    ),
                ),
                ("buying_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("selling_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "rate_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rates.ratesource",
                    ),
                ),
            ],
            options={
                "unique_together": {("metal", "currency", "timestamp", "purity")},
            },
        ),
        migrations.AlterField(
            model_name="rate",
            name="metal",
            field=models.CharField(
                choices=[("Gold", "Gold"), ("Silver", "Silver"), ("Bronze", "Bronze")],
                default="Gold",
                max_length=6,
            ),
        ),
        migrations.RunPython(load_fixture),
    ]
