# Generated by Django 5.2.6 on 2025-11-15 10:03

from django.core.management import call_command
from django.db import migrations


def load_fixture(apps, schema_editor):
    call_command("loaddata", "metal_rates.json")


class Migration(migrations.Migration):
    dependencies = [
        ("rates", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
