# Generated by Django 5.2.6 on 2025-11-15 10:03

from django.core.management import call_command
from django.db import migrations


def noop_forward(apps, schema_editor):
    # Seed moved to apps.orgs.management.commands.seed_tenant_defaults.
    pass


def load_fixture(apps, schema_editor):
    call_command("loaddata", "metal_rates.json")


class Migration(migrations.Migration):
    dependencies = [
        ("rates", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(noop_forward, reverse_code=migrations.RunPython.noop),
    ]
