# Generated by Django 6.0.3 on 2026-09-11 12:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


BACKFILL = """
UPDATE rates_rate AS quote SET effective_at = quote.timestamp,
    source_snapshot = jsonb_build_object('name', source.name, 'location', source.location,
                                         'tax_included', source.tax_included, 'legacy', true)
FROM rates_ratesource AS source WHERE source.id = quote.rate_source_id;
"""

GUARD = """
CREATE FUNCTION rates_guard_quote_evidence() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE previous rates_rate%ROWTYPE; source rates_ratesource%ROWTYPE;
BEGIN
    IF TG_OP <> 'INSERT' THEN
        RAISE EXCEPTION 'Quotes are immutable; append a correction or withdrawal';
    END IF;
    SELECT * INTO source FROM rates_ratesource WHERE id = NEW.rate_source_id;
    IF NOT FOUND OR source.workspace_id <> NEW.workspace_id THEN
        RAISE EXCEPTION 'Quote source must belong to the same Workspace';
    END IF;
    IF NEW.supersedes_id IS NOT NULL THEN
        SELECT * INTO previous FROM rates_rate WHERE id = NEW.supersedes_id FOR UPDATE;
        IF NOT FOUND OR previous.workspace_id <> NEW.workspace_id OR previous.is_withdrawal THEN
            RAISE EXCEPTION 'Invalid original quote for correction or withdrawal';
        END IF;
        IF NEW.recorded_by_id IS NULL OR length(trim(NEW.reason)) = 0 THEN
            RAISE EXCEPTION 'Quote revision requires actor and reason';
        END IF;
    ELSIF NEW.is_withdrawal THEN
        RAISE EXCEPTION 'Withdrawal requires an original quote';
    END IF;
    IF NEW.is_withdrawal THEN
        IF ROW(NEW.metal, NEW.currency, NEW.purity, NEW.effective_at, NEW.rate_source_id,
               NEW.buying_rate, NEW.selling_rate) IS DISTINCT FROM
           ROW(previous.metal, previous.currency, previous.purity, previous.effective_at,
               previous.rate_source_id, previous.buying_rate, previous.selling_rate) THEN
            RAISE EXCEPTION 'Withdrawal must preserve original quote values';
        END IF;
    ELSE
        IF NEW.buying_rate <= 0 OR NEW.selling_rate <= 0 OR
           NEW.buying_rate::text = 'NaN' OR NEW.selling_rate::text = 'NaN' THEN
            RAISE EXCEPTION 'Quote prices must be positive';
        END IF;
        IF NEW.metal <> 'Gold' AND NEW.purity <> '24k' THEN
            RAISE EXCEPTION 'Non-gold quotes require pure-metal basis';
        END IF;
    END IF;
    NEW.source_snapshot = jsonb_build_object('name', source.name, 'location', source.location,
                                            'tax_included', source.tax_included);
    RETURN NEW;
END;
$$;
CREATE TRIGGER rates_quote_evidence BEFORE INSERT OR UPDATE OR DELETE ON rates_rate
FOR EACH ROW EXECUTE FUNCTION rates_guard_quote_evidence();
"""


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0002_enable_workspace_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='effective_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rate',
            name='is_withdrawal',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='rate',
            name='reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='rate',
            name='recorded_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rate',
            name='source_snapshot',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='rate',
            name='supersedes',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor', to='rates.rate'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='buying_rate',
            field=models.DecimalField(decimal_places=2, help_text='Currency per gram of the selected purity.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='rate',
            name='purity',
            field=models.CharField(choices=[('24k', 'Pure metal (100%)'), ('22k', '22K'), ('18k', '18K'), ('14k', '14K'), ('10k', '10K')], default='24k', max_length=3),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rates.ratesource'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='selling_rate',
            field=models.DecimalField(decimal_places=2, help_text='Currency per gram of the selected purity.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.RunSQL(BACKFILL, migrations.RunSQL.noop),
        migrations.RunSQL(GUARD, "DROP TRIGGER rates_quote_evidence ON rates_rate; DROP FUNCTION rates_guard_quote_evidence();"),
    ]
