# Generated by Django 5.0.8 on 2024-10-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rates", "0002_load_metal_rates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rate",
            name="metal",
            field=models.CharField(
                choices=[("Gold", "Gold"), ("Silver", "Silver"), ("Bronze", "Bronze")],
                default="Gold",
                max_length=6,
            ),
        ),
    ]
