# Generated by Django 5.2.6 on 2025-11-15 09:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contact", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PBL", "Pawn Brokers License"),
                            ("GST", "Goods & Service Tax"),
                        ],
                        default="PBL",
                        max_length=30,
                        verbose_name="Type",
                    ),
                ),
                ("shopname", models.CharField(max_length=30, verbose_name="Shop Name")),
                ("address", models.TextField(max_length=100, verbose_name="Address")),
                ("phonenumber", models.CharField(max_length=30)),
                (
                    "propreitor",
                    models.CharField(max_length=30, verbose_name="Propreitor"),
                ),
                ("renewal_date", models.DateField()),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="LoanItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pic",
                    models.ImageField(blank=True, null=True, upload_to="loan_pics/"),
                ),
                (
                    "itemtype",
                    models.CharField(
                        choices=[
                            ("Gold", "Gold"),
                            ("Silver", "Silver"),
                            ("Bronze", "Bronze"),
                        ],
                        default="Gold",
                        max_length=30,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("weight", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "purity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=75,
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("loanamount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("interestrate", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "interest",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "itemdesc",
                    models.TextField(
                        blank=True, max_length=100, null=True, verbose_name="Item"
                    ),
                ),
                ("is_repledged", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("id", "loan"),
                "get_latest_by": "id",
            },
        ),
        migrations.CreateModel(
            name="LoanItemPic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pic",
                    models.ImageField(
                        blank=True, null=True, upload_to="loan_item_pics/"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoanItemStorageBox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=50)),
                ("start_item_id", models.CharField(max_length=50)),
                ("end_item_id", models.CharField(max_length=50)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("Gold", "Gold"),
                            ("Silver", "Silver"),
                            ("Bronze", "Bronze"),
                        ],
                        default="Gold",
                        max_length=6,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoanPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("payment_date", models.DateTimeField()),
                (
                    "payment_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Payment"
                    ),
                ),
                (
                    "principal_payment",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "interest_payment",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("with_release", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="LoanTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "base_template",
                    models.FileField(blank=True, null=True, upload_to="pdf_templates/"),
                ),
                (
                    "dup_template",
                    models.FileField(blank=True, null=True, upload_to="pdf_templates/"),
                ),
                (
                    "terms_template",
                    models.FileField(blank=True, null=True, upload_to="pdf_templates/"),
                ),
                (
                    "form_d3_template",
                    models.FileField(blank=True, null=True, upload_to="pdf_templates/"),
                ),
                (
                    "print_option",
                    models.CharField(
                        choices=[
                            ("O", "Original Copy Only"),
                            ("OT", "Original with Terms on Back"),
                            ("D", "Duplicate Copy Only"),
                            ("DF", "Duplicate with Form D3 on Back"),
                            ("BS", "Both Copies Single Sided"),
                            ("BD", "Both Copies Double Sided"),
                            ("BA", "Both on Single A4 Landscape"),
                            ("BDA", "Both Double Sided on A4 Landscape (2 pages)"),
                        ],
                        default="BS",
                        max_length=3,
                    ),
                ),
                (
                    "page_width",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Width in centimeters",
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "page_height",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Height in centimeters",
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Release",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "release_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "release_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Release ID",
                    ),
                ),
            ],
            options={
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="RepledgedLoanItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "repledged_loanamount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "interest_rate",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                (
                    "interest",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "repledged_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=30,
                        verbose_name="Series Name/prefix",
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        default="Z",
                        help_text="Prefix for loan IDs in this series",
                        max_length=3,
                    ),
                ),
                (
                    "max_limit",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Number of digits in loan ID sequence",
                        verbose_name="Max Limit",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "loan_type",
                    models.CharField(
                        blank=True,
                        choices=[("Taken", "Taken"), ("Given", "Given")],
                        default="Given",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "ordering": ("created",),
            },
        ),
        migrations.CreateModel(
            name="Statement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("completed", models.DateTimeField(blank=True, null=True)),
                ("reopened_at", models.DateTimeField(null=True)),
                (
                    "statement_type",
                    models.CharField(
                        choices=[
                            ("REGULAR", "Regular Verification"),
                            ("SPOT", "Spot Check"),
                            ("ANNUAL", "Annual Audit"),
                        ],
                        default="REGULAR",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("REOPENED", "Reopened"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="StatementItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("descrepancy_found", models.BooleanField(default=False)),
                (
                    "descrepancy_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MISSING", "Item Missing"),
                            ("WEIGHT", "Weight Mismatch"),
                            ("CONDITION", "Condition Changed"),
                            ("RELEASED", "Released but Present"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("descrepancy_note", models.TextField(blank=True, null=True)),
                ("auto_generated", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="TemplateFrame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frame_name",
                    models.CharField(
                        choices=[
                            ("license_no", "License Number"),
                            ("license_name", "License Name"),
                            ("license_address", "License Address"),
                            ("license_phone", "License Phone"),
                            ("license_propreitor", "License Propreitor"),
                            ("logo", "Logo"),
                            ("loan_id", "Loan ID"),
                            ("loan_qr", "Loan QR Code"),
                            ("loan_date", "Date"),
                            ("customer_info", "Customer Info"),
                            ("customer_name", "Customer Name"),
                            ("customer_pic", "Customer Photo"),
                            ("loanitem_pic", "Loan Item Photo"),
                            ("loan_desc", "Loan Description"),
                            ("weight", "Weight"),
                            ("value", "Value"),
                            ("address", "Address"),
                            ("phone", "Phone Number"),
                            ("items_table", "Items Table"),
                            ("amount", "Amount"),
                            ("amount_words", "Amount in Words"),
                            ("label", "Label"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("O", "Original Copy"),
                            ("D", "Duplicate Copy"),
                            ("B", "Both Copies"),
                        ],
                        default="B",
                        help_text="Specify if frame appears on original, duplicate or both copies",
                        max_length=1,
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("image", "Image"),
                            ("table", "Table"),
                            ("qr", "QR Code"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "x_pos",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="X position in centimeters",
                        max_digits=6,
                    ),
                ),
                (
                    "y_pos",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Y position in centimeters",
                        max_digits=6,
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        decimal_places=2, help_text="Width in centimeters", max_digits=6
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Height in centimeters",
                        max_digits=6,
                    ),
                ),
                ("font_size", models.PositiveIntegerField(default=12)),
                ("font_name", models.CharField(default="Helvetica", max_length=50)),
                ("show_boundary", models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "loan_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Loan Date"
                    ),
                ),
                (
                    "loan_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "loan_type",
                    models.CharField(
                        blank=True,
                        choices=[("Taken", "Taken"), ("Given", "Given")],
                        default="Given",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("weight", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "item_desc",
                    models.TextField(
                        blank=True, max_length=100, null=True, verbose_name="Item"
                    ),
                ),
                (
                    "loan_amount",
                    models.PositiveIntegerField(
                        blank=True, default=0, null=True, verbose_name="Amount"
                    ),
                ),
                (
                    "interest",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Created", "Created"),
                            ("Cancelled", "Cancelled"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Disbursed", "Disbursed"),
                            ("Closed", "Closed"),
                            ("Released", "Released"),
                            ("Repledged", "Repledged"),
                            ("Sold", "Sold"),
                            ("Defaulted", "Defaulted"),
                            ("Auctioned", "Auctioned"),
                        ],
                        default="Created",
                        max_length=20,
                    ),
                ),
                (
                    "interest_type",
                    models.CharField(
                        choices=[("Simple", "Simple"), ("Compound", "Compound")],
                        default="Simple",
                        max_length=10,
                    ),
                ),
                ("tenure", models.PositiveIntegerField(default=3)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="loans_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contact.customer",
                    ),
                ),
            ],
            options={
                "ordering": ("series", "loan_id"),
                "permissions": [
                    ("can_approve_loan", "Can approve loan"),
                    ("can_disburse_loan", "Can disburse loan"),
                    ("can_release_loan", "Can release loan"),
                    ("can_cancel_loan", "Can cancel loan"),
                    ("can_mark_defaulted", "Can mark loan as defaulted"),
                    ("can_mark_auctioned", "Can mark loan as auctioned"),
                    ("can_mark_sold", "Can mark loan as sold"),
                ],
                "get_latest_by": "id",
            },
        ),
        migrations.CreateModel(
            name="LoanChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("changed", models.DateTimeField(default=django.utils.timezone.now)),
                ("source", models.CharField(max_length=255)),
                ("target", models.CharField(max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("diff", models.TextField()),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="girvi.loan"
                    ),
                ),
            ],
            options={
                "ordering": ["-changed"],
            },
        ),
    ]
