# Generated by Django 5.2.6 on 2025-11-15 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contact", "0001_initial"),
        ("girvi", "0001_initial"),
        ("product", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="loanitem",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="product.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="loanitem",
            name="loan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loanitems",
                to="girvi.loan",
            ),
        ),
        migrations.AddField(
            model_name="loanitempic",
            name="loan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loanitem_pics",
                to="girvi.loan",
            ),
        ),
        migrations.AddField(
            model_name="loanpayment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="loan_payments_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loanpayment",
            name="loan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loan_payments",
                to="girvi.loan",
            ),
        ),
        migrations.AddField(
            model_name="release",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="releases_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="release",
            name="loan",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="release",
                to="girvi.loan",
            ),
        ),
        migrations.AddField(
            model_name="release",
            name="released_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="released_by",
                to="contact.customer",
                verbose_name="Released By",
            ),
        ),
        migrations.AddField(
            model_name="repledgedloanitem",
            name="loan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repledgedloanitems",
                to="girvi.loan",
            ),
        ),
        migrations.AddField(
            model_name="repledgedloanitem",
            name="original_loanitem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repledged_items",
                to="girvi.loanitem",
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="license",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="girvi.license",
                verbose_name="License",
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="series",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="girvi.series",
                verbose_name="Series",
            ),
        ),
        migrations.AddField(
            model_name="statement",
            name="completed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="statements_completed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="statement",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="loan_statements_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="statement",
            name="reopened_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="statements_reopened",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="statementitem",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="statement_items_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="statementitem",
            name="loan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="girvi.loan"
            ),
        ),
        migrations.AddField(
            model_name="statementitem",
            name="statement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="girvi.statement"
            ),
        ),
        migrations.AddField(
            model_name="templateframe",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="girvi.loantemplate"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="series",
            unique_together={("license", "name")},
        ),
        migrations.AddConstraint(
            model_name="loan",
            constraint=models.UniqueConstraint(
                fields=("series", "loan_id"), name="unique_loan_id_per_series"
            ),
        ),
        migrations.AddConstraint(
            model_name="statementitem",
            constraint=models.UniqueConstraint(
                fields=("statement", "loan"), name="unique_loan_per_statement"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="templateframe",
            unique_together={("template", "frame_name", "template_type")},
        ),
    ]
