# Generated by Django 5.0.1 on 2024-02-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0002_alter_license_address_alter_license_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="pic",
            field=models.ImageField(
                blank=True, null=True, upload_to="loan_pics/", verbose_name="Image"
            ),
        ),
    ]
