# Generated by Django 5.2.6 on 2026-02-24 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0005_migrate_loan_data_to_givenloan_takenloan"),
        ("product", "0004_auto_views"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="repledgehistory",
            new_name="girvi_reple_loan_it_08f1e3_idx",
            old_name="girvi_repl_loan_it_idx",
        ),
        migrations.RenameIndex(
            model_name="repledgehistory",
            new_name="girvi_reple_taken_l_301f8d_idx",
            old_name="girvi_repl_taken_l_idx",
        ),
        migrations.RenameIndex(
            model_name="repledgehistory",
            new_name="girvi_reple_returne_7a4c6e_idx",
            old_name="girvi_repl_returne_idx",
        ),
        migrations.RemoveField(
            model_name="loanitem",
            name="is_repledged",
        ),
        migrations.RemoveField(
            model_name="loanitemstoragebox",
            name="end_item_id",
        ),
        migrations.RemoveField(
            model_name="loanitemstoragebox",
            name="start_item_id",
        ),
        migrations.AddField(
            model_name="loanitemstoragebox",
            name="end_item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="as_box_end",
                to="girvi.loanitem",
            ),
        ),
        migrations.AddField(
            model_name="loanitemstoragebox",
            name="start_item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="as_box_start",
                to="girvi.loanitem",
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="status",
            field=models.CharField(
                choices=[
                    ("Created", "Created"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Disbursed", "Disbursed"),
                    ("Closed", "Closed"),
                    ("Released", "Released"),
                    ("Repledged", "Repledged"),
                    ("Sold", "Sold"),
                    ("Defaulted", "Defaulted"),
                    ("Auctioned", "Auctioned"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Created",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="loanitem",
            name="loan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loanitems",
                to="girvi.givenloan",
            ),
        ),
        migrations.AlterField(
            model_name="loanitempic",
            name="loan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loanitem_pics",
                to="girvi.givenloan",
            ),
        ),
        migrations.AlterField(
            model_name="release",
            name="loan",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="release",
                to="girvi.givenloan",
            ),
        ),
        migrations.AlterField(
            model_name="repledgedloanitem",
            name="loan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repledgedloanitems",
                to="girvi.takenloan",
            ),
        ),
        migrations.AlterField(
            model_name="statementitem",
            name="loan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="girvi.givenloan"
            ),
        ),
        migrations.AddIndex(
            model_name="loanitem",
            index=models.Index(
                fields=["loan", "itemtype"], name="loanitem_loan_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loanitem",
            index=models.Index(fields=["itemtype"], name="loanitem_type_idx"),
        ),
        migrations.AddIndex(
            model_name="loanitem",
            index=models.Index(fields=["custody_status"], name="loanitem_custody_idx"),
        ),
        migrations.AddIndex(
            model_name="loanitem",
            index=models.Index(
                fields=["custody_status", "itemtype"], name="loanitem_custody_type_idx"
            ),
        ),
    ]
