# Generated by Django 5.2.6 on 2026-02-24 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0006_update_foreign_keys_to_new_loan_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LicenseDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("CERTIFICATE", "License Certificate"),
                            ("APPROVAL_LETTER", "Approval Letter"),
                            ("RENEWAL_NOTICE", "Renewal Notice"),
                            ("INSPECTION_REPORT", "Inspection Report"),
                            ("COMPLIANCE_DOC", "Compliance Document"),
                            ("OTHER", "Other Document"),
                        ],
                        default="CERTIFICATE",
                        max_length=20,
                        verbose_name="Document Type",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Document Title"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "document_file",
                    models.FileField(
                        upload_to="license_documents/%Y/%m/",
                        verbose_name="Document File",
                    ),
                ),
                (
                    "file_size",
                    models.IntegerField(
                        blank=True,
                        editable=False,
                        help_text="File size in bytes",
                        null=True,
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True, editable=False, max_length=50, null=True
                    ),
                ),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Document Expiry Date"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Verified?"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "License Document",
                "verbose_name_plural": "License Documents",
                "ordering": ["-upload_date"],
            },
        ),
        migrations.AlterModelOptions(
            name="license",
            options={
                "ordering": ("-created",),
                "verbose_name": "License",
                "verbose_name_plural": "Licenses",
            },
        ),
        migrations.AddField(
            model_name="license",
            name="business_type",
            field=models.CharField(
                choices=[
                    ("PAWNBROKER", "Pawnbroker Only"),
                    ("JEWELLER", "Jeweller Only"),
                    ("COMBINED", "Pawnbroker & Jeweller"),
                    ("OTHER", "Other"),
                ],
                default="COMBINED",
                max_length=20,
                verbose_name="Business Type",
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="City"),
        ),
        migrations.AddField(
            model_name="license",
            name="date_expires",
            field=models.DateField(blank=True, null=True, verbose_name="Expiry Date"),
        ),
        migrations.AddField(
            model_name="license",
            name="date_issued",
            field=models.DateField(blank=True, null=True, verbose_name="Date Issued"),
        ),
        migrations.AddField(
            model_name="license",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Business email",
                max_length=254,
                verbose_name="Email",
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
        migrations.AddField(
            model_name="license",
            name="is_renewable",
            field=models.BooleanField(default=True, verbose_name="Auto-renewable?"),
        ),
        migrations.AddField(
            model_name="license",
            name="issuing_authority",
            field=models.CharField(
                blank=True,
                help_text="Authority that issued this license",
                max_length=200,
                verbose_name="Issuing Authority",
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="license_number",
            field=models.CharField(
                blank=True,
                help_text="Unique license identifier from authority",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="License Number",
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Additional Notes"),
        ),
        migrations.AddField(
            model_name="license",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Postal Code"
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="state",
            field=models.CharField(blank=True, max_length=100, verbose_name="State"),
        ),
        migrations.AddField(
            model_name="license",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                    ("EXPIRED", "Expired"),
                    ("SUSPENDED", "Suspended"),
                    ("PENDING", "Pending Approval"),
                    ("RENEWED", "Renewed"),
                ],
                default="ACTIVE",
                max_length=20,
                verbose_name="License Status",
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="address",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="Business Address"
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="License Name"
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="phonenumber",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Phone Number"
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="propreitor",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Proprietor/Owner Name",
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="renewal_date",
            field=models.DateField(blank=True, null=True, verbose_name="Renewal Date"),
        ),
        migrations.AlterField(
            model_name="license",
            name="shopname",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Shop/Business Name"
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="type",
            field=models.CharField(
                choices=[
                    ("PBL", "Pawn Brokers License"),
                    ("GST", "Goods & Service Tax Registration"),
                    ("IMPORT_EXPORT", "Import/Export License"),
                    ("HALLMARK", "Hallmark Certificate"),
                    ("FSSAI", "FSSAI Registration (Food)"),
                    ("OTHER", "Other"),
                ],
                default="PBL",
                max_length=30,
                verbose_name="License Type",
            ),
        ),
        migrations.AddIndex(
            model_name="license",
            index=models.Index(fields=["status"], name="girvi_licen_status_9bb4a2_idx"),
        ),
        migrations.AddIndex(
            model_name="license",
            index=models.Index(fields=["type"], name="girvi_licen_type_cec49c_idx"),
        ),
        migrations.AddIndex(
            model_name="license",
            index=models.Index(
                fields=["date_expires"], name="girvi_licen_date_ex_bc2e25_idx"
            ),
        ),
        migrations.AddField(
            model_name="licensedocument",
            name="license",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="girvi.license",
                verbose_name="License",
            ),
        ),
        migrations.AddField(
            model_name="licensedocument",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Uploaded By",
            ),
        ),
        migrations.AddIndex(
            model_name="licensedocument",
            index=models.Index(
                fields=["license", "is_active"], name="girvi_licen_license_53bafb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="licensedocument",
            index=models.Index(
                fields=["document_type"], name="girvi_licen_documen_d475ad_idx"
            ),
        ),
    ]
