# Generated by Django 5.2.6 on 2026-02-26 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("girvi", "0007_licensedocument_alter_license_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loanchangelog",
            name="loan",
        ),
        migrations.AddField(
            model_name="loanchangelog",
            name="content_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="loanchangelog",
            name="object_id",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="givenloan",
            name="series",
            field=models.ForeignKey(
                help_text="Series - determines loan ID prefix and sequence (required)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="given_loans",
                to="girvi.series",
                verbose_name="Series",
            ),
        ),
        migrations.AlterField(
            model_name="loanpayment",
            name="loan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loan_payments",
                to="girvi.givenloan",
            ),
        ),
        migrations.AlterField(
            model_name="takenloan",
            name="series",
            field=models.ForeignKey(
                help_text="Series - determines loan ID prefix and sequence (required)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="taken_loans",
                to="girvi.series",
                verbose_name="Series",
            ),
        ),
        migrations.AddIndex(
            model_name="loanchangelog",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="girvi_loanc_content_b6e936_idx",
            ),
        ),
    ]
