# Generated by Django 5.0.1 on 2024-06-06 07:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0007_alter_loan_created_by_alter_loanpayment_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="interest_type",
            field=models.CharField(
                choices=[("Simple", "Simple"), ("Compound", "Compound")],
                default="Simple",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="tenure",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="loan",
            name="voucher_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="loan",
            name="voucher_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
