# Generated by Django 5.0.1 on 2024-06-10 09:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0008_loan_interest_type_loan_tenure_loan_voucher_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loan",
            name="has_collateral",
        ),
    ]
