# Generated by Django 5.2.6 on 2026-03-16 13:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0009_series_guardrails"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="series",
            new_name="girvi_serie_is_acti_e2e482_idx",
            old_name="girvi_series_active_loans_idx",
        ),
        migrations.RenameIndex(
            model_name="series",
            new_name="girvi_serie_is_acti_fbc2e1_idx",
            old_name="girvi_series_active_releases_idx",
        ),
    ]
