# Generated by Django 5.0.1 on 2024-07-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0009_remove_loan_has_collateral"),
    ]

    operations = [
        migrations.AlterField(
            model_name="series",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=30, verbose_name="Series Name"
            ),
        ),
    ]
