# Generated by Django 5.0.1 on 2024-08-07 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0012_address_is_default_contact_is_default"),
        ("girvi", "0010_alter_series_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loan",
                to="contact.customer",
            ),
        ),
    ]
