# Generated by Django 6.0.3 on 2026-03-19 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girvi', '0010_rename_girvi_series_active_loans_idx_girvi_serie_is_acti_e2e482_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanitempic',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Only one picture per loan item should be marked as default.'),
        ),
        migrations.AddField(
            model_name='loanitempic',
            name='loan_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='girvi.loanitem'),
        ),
        migrations.AlterField(
            model_name='templateframe',
            name='frame_name',
            field=models.CharField(choices=[('license_no', 'License Number'), ('license_name', 'License Name'), ('license_address', 'License Address'), ('license_phone', 'License Phone'), ('license_propreitor', 'License Propreitor'), ('logo', 'Logo'), ('loan_id', 'Loan ID'), ('loan_qr', 'Loan QR Code'), ('loan_date', 'Date'), ('customer_info', 'Customer Info'), ('customer_name', 'Customer Name'), ('customer_pic', 'Customer Photo'), ('loanitem_pic', 'Loan Item Photo'), ('loan_desc', 'Loan Description'), ('weight', 'Weight'), ('pure', 'Pure Weight'), ('value', 'Value'), ('address', 'Address'), ('phone', 'Phone Number'), ('items_table', 'Items Table'), ('amount', 'Amount'), ('amount_words', 'Amount in Words'), ('label', 'Label')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='loanitempic',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('loan_item',), name='only_one_default_pic_per_item'),
        ),
    ]
