# Generated by Django 5.0.1 on 2024-08-07 13:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0011_alter_loan_customer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loan",
            name="pic",
        ),
    ]
