# Generated by Django 5.0.1 on 2024-08-07 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0013_remove_customer_address_remove_customer_area_and_more"),
        ("girvi", "0012_remove_loan_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="contact.customer"
            ),
        ),
    ]
