# Generated by Django 5.1.2 on 2024-11-17 05:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    # replaces = [
    #     ("girvi", "0014_loanitempic"),
    #     ("girvi", "0015_statement_completed_statementitem_descrepancy_found_and_more"),
    #     ("girvi", "0016_statementitem_unique_loan_per_statement"),
    #     ("girvi", "0017_loan_value_loan_weight_alter_loan_tenure"),
    #     ("girvi", "0018_remove_loan_voucher_date_remove_loan_voucher_no"),
    #     ("girvi", "0019_loanitemstoragebox"),
    #     ("girvi", "0020_loan_loan_id_copy_alter_loanitemstoragebox_item_type"),
    #     ("girvi", "0021_series_max_limit"),
    #     ("girvi", "0022_alter_series_name"),
    #     ("girvi", "0023_alter_loan_options"),
    #     ("girvi", "0024_alter_loanitemstoragebox_end_item_id_and_more"),
    #     ("girvi", "0025_alter_loanitemstoragebox_item_type"),
    #     (
    #         "girvi",
    #         "0026_loantemplate_templateframe_squashed_0040_templateframe_show_boundary",
    #     ),
    #     ("girvi", "0041_alter_loantemplate_page_height_and_more"),
    # ]

    dependencies = [
        ("girvi", "0013_alter_loan_customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanItemPic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pic",
                    models.ImageField(
                        blank=True, null=True, upload_to="loan_item_pics/"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=255, null=True),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loanitem_pics",
                        to="girvi.loan",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="statement",
            name="completed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="statementitem",
            name="descrepancy_found",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="statementitem",
            name="descrepancy_note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="statementitem",
            name="verified_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name="statementitem",
            constraint=models.UniqueConstraint(
                fields=("statement", "loan"), name="unique_loan_per_statement"
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="loan",
            name="weight",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="loan",
            name="tenure",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.RemoveField(
            model_name="loan",
            name="voucher_date",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="voucher_no",
        ),
        migrations.AddField(
            model_name="series",
            name="max_limit",
            field=models.PositiveIntegerField(default=5, verbose_name="Max Limit"),
        ),
        migrations.AlterField(
            model_name="series",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=30, verbose_name="Series Name/prefix"
            ),
        ),
        migrations.AlterModelOptions(
            name="loan",
            options={"get_latest_by": "id", "ordering": ("series", "loan_id")},
        ),
        migrations.CreateModel(
            name="LoanItemStorageBox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=50)),
                ("start_item_id", models.CharField(max_length=50)),
                ("end_item_id", models.CharField(max_length=50)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("Gold", "Gold"),
                            ("Silver", "Silver"),
                            ("Bronze", "Bronze"),
                        ],
                        default="Gold",
                        max_length=6,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoanTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "base_template",
                    models.FileField(blank=True, null=True, upload_to="pdf_templates/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "dup_template",
                    models.FileField(blank=True, null=True, upload_to="pdf_templates/"),
                ),
                (
                    "form_d3_template",
                    models.FileField(blank=True, null=True, upload_to="pdf_templates/"),
                ),
                (
                    "print_option",
                    models.CharField(
                        choices=[
                            ("O", "Original Copy Only"),
                            ("OT", "Original with Terms on Back"),
                            ("D", "Duplicate Copy Only"),
                            ("DF", "Duplicate with Form D3 on Back"),
                            ("BS", "Both Copies Single Sided"),
                            ("BD", "Both Copies Double Sided"),
                            ("BA", "Both on Single A4 Landscape"),
                            ("BDA", "Both Double Sided on A4 Landscape (2 pages)"),
                        ],
                        default="BS",
                        max_length=3,
                    ),
                ),
                (
                    "terms_template",
                    models.FileField(blank=True, null=True, upload_to="pdf_templates/"),
                ),
                (
                    "page_height",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Height in centimeters",
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "page_width",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Width in centimeters",
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="TemplateFrame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frame_name",
                    models.CharField(
                        choices=[
                            ("license_no", "License Number"),
                            ("license_name", "License Name"),
                            ("license_address", "License Address"),
                            ("license_phone", "License Phone"),
                            ("license_propreitor", "License Propreitor"),
                            ("logo", "Logo"),
                            ("loan_id", "Loan ID"),
                            ("loan_qr", "Loan QR Code"),
                            ("loan_date", "Date"),
                            ("customer_info", "Customer Info"),
                            ("customer_name", "Customer Name"),
                            ("customer_pic", "Customer Photo"),
                            ("loanitem_pic", "Loan Item Photo"),
                            ("loan_desc", "Loan Description"),
                            ("weight", "Weight"),
                            ("value", "Value"),
                            ("address", "Address"),
                            ("phone", "Phone Number"),
                            ("items_table", "Items Table"),
                            ("amount", "Amount"),
                            ("amount_words", "Amount in Words"),
                            ("label", "Label"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("image", "Image"),
                            ("table", "Table"),
                            ("qr", "QR Code"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "x_pos",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="X position in centimeters",
                        max_digits=6,
                    ),
                ),
                (
                    "y_pos",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Y position in centimeters",
                        max_digits=6,
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        decimal_places=2, help_text="Width in centimeters", max_digits=6
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Height in centimeters",
                        max_digits=6,
                    ),
                ),
                ("font_size", models.PositiveIntegerField(default=12)),
                ("font_name", models.CharField(default="Helvetica", max_length=50)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="girvi.loantemplate",
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("O", "Original Copy"),
                            ("D", "Duplicate Copy"),
                            ("B", "Both Copies"),
                        ],
                        default="B",
                        help_text="Specify if frame appears on original, duplicate or both copies",
                        max_length=1,
                    ),
                ),
                ("show_boundary", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "unique_together": {("template", "frame_name", "template_type")},
            },
        ),
    ]
