# Generated by Django 6.0.3 on 2026-03-23 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('girvi', '0013_archive_loanpayments_to_paymentvoucher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanpayment',
            options={'managed': False, 'ordering': ('-id',)},
        ),
    ]
