# Generated by Django 5.0.8 on 2024-08-22 04:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0014_loanitempic"),
    ]

    operations = [
        migrations.AddField(
            model_name="statement",
            name="completed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="statementitem",
            name="descrepancy_found",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="statementitem",
            name="descrepancy_note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="statementitem",
            name="verified_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
