# Generated by Django 6.0.3 on 2026-03-31 12:16

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girvi', '0014_alter_loanpayment_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('PAY_AND_RENEW', 'Pay & Renew'), ('TOPUP_RENEW', 'Top-Up Renew')], max_length=20, verbose_name='Renewal Mode')),
                ('renewal_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Renewal Date')),
                ('interest_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Interest Paid')),
                ('principal_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Principal Paid')),
                ('requested_extra_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Additional amount borrowed (Top-Up mode only)', max_digits=10, verbose_name='Requested Extra Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('renewed_loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='renewal_record', to='girvi.givenloan', verbose_name='Renewed Loan')),
                ('source_loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renewals_as_source', to='girvi.givenloan', verbose_name='Source Loan')),
            ],
            options={
                'verbose_name': 'Loan Renewal',
                'verbose_name_plural': 'Loan Renewals',
                'ordering': ('-created_at',),
            },
        ),
    ]
