# Generated by Django 5.0.8 on 2024-08-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0015_statement_completed_statementitem_descrepancy_found_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="statementitem",
            constraint=models.UniqueConstraint(
                fields=("statement", "loan"), name="unique_loan_per_statement"
            ),
        ),
    ]
