# Generated by Django 6.0.3 on 2026-04-04 13:55

from django.db import migrations, models


LEGACY_TO_V2_GIVENLOAN_STATUS = {
    "Created": "Draft",
    "Approved": "Approved",
    "Disbursed": "ActiveCurrent",
    "Defaulted": "ActiveNPA",
    "Auctioned": "AuctionComplete",
    "Sold": "AuctionComplete",
    "Released": "Closed",
    "Closed": "Closed",
    "Repledged": "Renewed",
    "Rejected": "Rejected",
    "Cancelled": "Cancelled",
}


V2_TO_LEGACY_GIVENLOAN_STATUS = {
    "Draft": "Created",
    "PendingApproval": "Created",
    "Approved": "Approved",
    "ActiveCurrent": "Disbursed",
    "ActiveOverdue": "Disbursed",
    "ActiveNPA": "Defaulted",
    "ClosurePending": "Disbursed",
    "RenewalPending": "Disbursed",
    "AuctionInitiated": "Auctioned",
    "AuctionInProgress": "Auctioned",
    "AuctionComplete": "Auctioned",
    "Renewed": "Repledged",
    "WrittenOff": "Auctioned",
    "Closed": "Closed",
    "Rejected": "Rejected",
    "Cancelled": "Cancelled",
}


def migrate_givenloan_statuses_forward(apps, schema_editor):
    GivenLoan = apps.get_model("girvi", "GivenLoan")
    for old_status, new_status in LEGACY_TO_V2_GIVENLOAN_STATUS.items():
        GivenLoan.objects.filter(status=old_status).update(status=new_status)


def migrate_givenloan_statuses_backward(apps, schema_editor):
    GivenLoan = apps.get_model("girvi", "GivenLoan")
    for new_status, old_status in V2_TO_LEGACY_GIVENLOAN_STATUS.items():
        GivenLoan.objects.filter(status=new_status).update(status=old_status)


class Migration(migrations.Migration):

    dependencies = [
        ('girvi', '0015_loan_renewal_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='givenloan',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Disbursed', 'Disbursed'), ('Closed', 'Closed'), ('Released', 'Released'), ('Repledged', 'Repledged'), ('Sold', 'Sold'), ('Defaulted', 'Defaulted'), ('Auctioned', 'Auctioned'), ('Cancelled', 'Cancelled'), ('Draft', 'Draft'), ('PendingApproval', 'Pending Approval'), ('ActiveCurrent', 'Active Current'), ('ActiveOverdue', 'Active Overdue'), ('ActiveNPA', 'Active NPA'), ('ClosurePending', 'Closure Pending'), ('RenewalPending', 'Renewal Pending'), ('AuctionInitiated', 'Auction Initiated'), ('AuctionInProgress', 'Auction In Progress'), ('AuctionComplete', 'Auction Complete'), ('Renewed', 'Renewed'), ('WrittenOff', 'Written Off')], db_index=True, default='Created', max_length=20),
        ),
        migrations.AlterField(
            model_name='takenloan',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Disbursed', 'Disbursed'), ('Closed', 'Closed'), ('Released', 'Released'), ('Repledged', 'Repledged'), ('Sold', 'Sold'), ('Defaulted', 'Defaulted'), ('Auctioned', 'Auctioned'), ('Cancelled', 'Cancelled'), ('Draft', 'Draft'), ('PendingApproval', 'Pending Approval'), ('ActiveCurrent', 'Active Current'), ('ActiveOverdue', 'Active Overdue'), ('ActiveNPA', 'Active NPA'), ('ClosurePending', 'Closure Pending'), ('RenewalPending', 'Renewal Pending'), ('AuctionInitiated', 'Auction Initiated'), ('AuctionInProgress', 'Auction In Progress'), ('AuctionComplete', 'Auction Complete'), ('Renewed', 'Renewed'), ('WrittenOff', 'Written Off')], db_index=True, default='Created', max_length=20),
        ),
        migrations.RunPython(
            migrate_givenloan_statuses_forward,
            migrate_givenloan_statuses_backward,
        ),
    ]
