# Generated by Django 5.0.8 on 2024-08-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0016_statementitem_unique_loan_per_statement"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="loan",
            name="weight",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="loan",
            name="tenure",
            field=models.PositiveIntegerField(default=3),
        ),
    ]
