# Generated by Django 6.0.3 on 2026-04-06

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dea", "0016_remove_currencyconfiguration_workspace"),
        ("girvi", "0016_alter_givenloan_status_alter_takenloan_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanInterestAccrual",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("period_start", models.DateField(verbose_name="Period Start")),
                ("period_end", models.DateField(verbose_name="Period End")),
                ("accrued_amount", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12, verbose_name="Accrued Amount")),
                ("base_interest_snapshot", models.DecimalField(decimal_places=2, default=Decimal("0"), help_text="Per-period interest amount used when this accrual row was generated.", max_digits=12, verbose_name="Base Interest Snapshot")),
                ("months_covered", models.PositiveIntegerField(default=1, verbose_name="Months Covered")),
                ("trigger_source", models.CharField(choices=[("MANUAL", "Manual"), ("SCHEDULED", "Scheduled Batch"), ("PERIOD_CLOSE", "Period Close"), ("RELEASE", "Release Catch-up"), ("RENEWAL", "Renewal Catch-up"), ("RECEIPT", "Receipt Catch-up"), ("BACKFILL", "Backfill")], default="MANUAL", max_length=20, verbose_name="Trigger Source")),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("POSTED", "Posted"), ("SKIPPED", "Skipped"), ("REVERSED", "Reversed")], db_index=True, default="DRAFT", max_length=10, verbose_name="Status")),
                ("recognized_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name="Recognized At")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="loan_interest_accruals_created", to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("journal_entry_voucher", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="loan_interest_accruals", to="dea.journalentryvoucher", verbose_name="Journal Entry Voucher")),
                ("loan", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="interest_accruals", to="girvi.givenloan", verbose_name="Loan")),
            ],
            options={
                "verbose_name": "Loan Interest Accrual",
                "verbose_name_plural": "Loan Interest Accruals",
                "ordering": ("-period_end", "-created_at"),
            },
        ),
        migrations.AddConstraint(
            model_name="loaninterestaccrual",
            constraint=models.CheckConstraint(condition=models.Q(("period_end__gt", models.F("period_start"))), name="loan_interest_accrual_period_end_after_start"),
        ),
        migrations.AddConstraint(
            model_name="loaninterestaccrual",
            constraint=models.UniqueConstraint(fields=("loan", "period_start", "period_end"), name="unique_loan_interest_accrual_period"),
        ),
        migrations.AddIndex(
            model_name="loaninterestaccrual",
            index=models.Index(fields=["loan", "period_end"], name="girvi_loani_loan_id_89530e_idx"),
        ),
        migrations.AddIndex(
            model_name="loaninterestaccrual",
            index=models.Index(fields=["status", "recognized_at"], name="girvi_loani_status_f940d8_idx"),
        ),
    ]
