# Generated by Django 5.0.8 on 2024-09-06 12:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0017_loan_value_loan_weight_alter_loan_tenure"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loan",
            name="voucher_date",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="voucher_no",
        ),
    ]
