# Generated by Django 5.0.8 on 2024-09-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0018_remove_loan_voucher_date_remove_loan_voucher_no"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanItemStorageBox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=50)),
                ("start_item_id", models.PositiveIntegerField()),
                ("end_item_id", models.PositiveIntegerField()),
                (
                    "item_type",
                    models.CharField(
                        choices=[("gold", "Gold"), ("silver", "Silver")],
                        default="gold",
                        max_length=6,
                    ),
                ),
            ],
        ),
    ]
