# Generated by Django 5.0.8 on 2024-09-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0020_loan_loan_id_copy_alter_loanitemstoragebox_item_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="series",
            name="max_limit",
            field=models.PositiveIntegerField(default=5, verbose_name="Max Limit"),
        ),
    ]
