# Generated by Django 5.0.8 on 2024-09-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0021_series_max_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="series",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=30, verbose_name="Series Name/prefix"
            ),
        ),
    ]
