# Generated by Django 6.0.3 on 2026-06-19 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_loan_parties(apps, schema_editor):
    GivenLoan = apps.get_model('girvi', 'GivenLoan')
    TakenLoan = apps.get_model('girvi', 'TakenLoan')

    for loan in GivenLoan.objects.filter(
        borrower_party__isnull=True,
        borrower__party__isnull=False,
    ).select_related('borrower'):
        loan.borrower_party_id = loan.borrower.party_id
        loan.save(update_fields=['borrower_party'])

    for loan in TakenLoan.objects.filter(
        lender_party__isnull=True,
        lender__party__isnull=False,
    ).select_related('lender'):
        loan.lender_party_id = loan.lender.party_id
        loan.save(update_fields=['lender_party'])


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_customer_party'),
        ('girvi', '0021_canonical_loan_lifecycles'),
        ('party', '0003_party_relation_label_party_relation_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='givenloan',
            name='borrower_party',
            field=models.ForeignKey(blank=True, help_text='Shadow Party link for the borrower during Customer migration.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='given_loans', to='party.party', verbose_name='Borrower Party'),
        ),
        migrations.AddField(
            model_name='takenloan',
            name='lender_party',
            field=models.ForeignKey(blank=True, help_text='Shadow Party link for the lender during Customer migration.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='taken_loans', to='party.party', verbose_name='Lender Party'),
        ),
        migrations.RunPython(backfill_loan_parties, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='givenloan',
            index=models.Index(fields=['borrower_party', 'status'], name='girvi_given_borrowe_8e8f6f_idx'),
        ),
        migrations.AddIndex(
            model_name='takenloan',
            index=models.Index(fields=['lender_party', 'status'], name='girvi_taken_lender__7f27c8_idx'),
        ),
    ]
