# Generated by Django 5.0.8 on 2024-10-04 12:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0022_alter_series_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loan",
            options={"get_latest_by": "id", "ordering": ("series", "loan_id")},
        ),
    ]
