# Generated by Django 5.0.8 on 2024-10-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0023_alter_loan_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanitemstoragebox",
            name="end_item_id",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="loanitemstoragebox",
            name="item_type",
            field=models.CharField(
                choices=[("Gold", "Gold"), ("silver", "Silver"), ("bronze", "Bronze")],
                default="Gold",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="loanitemstoragebox",
            name="start_item_id",
            field=models.CharField(max_length=50),
        ),
    ]
