# Generated by Django 6.0.3 on 2026-06-22 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('girvi', '0024_girvi_posting_outbox_event'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='girvipostingoutboxevent',
            new_name='girvi_girvi_status_08ea95_idx',
            old_name='girvi_girvi_status_8c2f89_idx',
        ),
        migrations.RenameIndex(
            model_name='girvipostingoutboxevent',
            new_name='girvi_girvi_event_t_6664f1_idx',
            old_name='girvi_girvi_event_t_113738_idx',
        ),
        migrations.RenameIndex(
            model_name='girvipostingoutboxevent',
            new_name='girvi_girvi_source__c02712_idx',
            old_name='girvi_girvi_source__ca5934_idx',
        ),
    ]
