# Generated by Django 5.1.2 on 2024-10-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0024_alter_loanitemstoragebox_end_item_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanitemstoragebox",
            name="item_type",
            field=models.CharField(
                choices=[("Gold", "Gold"), ("Silver", "Silver"), ("Bronze", "Bronze")],
                default="Gold",
                max_length=6,
            ),
        ),
    ]
