# Generated by Django 5.1.2 on 2024-11-12 15:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("girvi", "0026_loantemplate_templateframe"),
        ("girvi", "0027_alter_templateframe_unique_together"),
        ("girvi", "0028_alter_templateframe_frame_name"),
        ("girvi", "0029_alter_templateframe_field_type"),
        ("girvi", "0030_alter_templateframe_frame_name"),
        ("girvi", "0031_alter_templateframe_frame_name"),
        ("girvi", "0032_alter_templateframe_unique_together_and_more"),
        ("girvi", "0033_loantemplate_page_height_loantemplate_page_width"),
        ("girvi", "0034_alter_loantemplate_print_option"),
        ("girvi", "0035_alter_loantemplate_base_template"),
        ("girvi", "0036_remove_loantemplate_print_layout_and_more"),
        ("girvi", "0037_alter_templateframe_frame_name"),
        ("girvi", "0038_alter_templateframe_frame_name"),
        ("girvi", "0039_alter_templateframe_frame_name"),
        ("girvi", "0040_templateframe_show_boundary"),
    ]

    dependencies = [
        ("girvi", "0025_alter_loanitemstoragebox_item_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "base_template",
                    models.FileField(blank=True, null=True, upload_to="pdf_templates/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "dup_template",
                    models.FileField(blank=True, null=True, upload_to="pdf_templates/"),
                ),
                (
                    "form_d3_template",
                    models.FileField(blank=True, null=True, upload_to="pdf_templates/"),
                ),
                (
                    "print_option",
                    models.CharField(
                        choices=[
                            ("O", "Original Copy Only"),
                            ("OT", "Original with Terms on Back"),
                            ("D", "Duplicate Copy Only"),
                            ("DF", "Duplicate with Form D3 on Back"),
                            ("BS", "Both Copies Single Sided"),
                            ("BD", "Both Copies Double Sided"),
                            ("BA", "Both on Single A4 Landscape"),
                            ("BDA", "Both Double Sided on A4 Landscape (2 pages)"),
                        ],
                        default="BS",
                        max_length=3,
                    ),
                ),
                (
                    "terms_template",
                    models.FileField(blank=True, null=True, upload_to="pdf_templates/"),
                ),
                (
                    "page_height",
                    models.DecimalField(
                        decimal_places=2,
                        default=29.7,
                        help_text="Height in centimeters",
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "page_width",
                    models.DecimalField(
                        decimal_places=2,
                        default=21,
                        help_text="Width in centimeters",
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="TemplateFrame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frame_name",
                    models.CharField(
                        choices=[
                            ("license_no", "License Number"),
                            ("license_name", "License Name"),
                            ("license_address", "License Address"),
                            ("license_phone", "License Phone"),
                            ("license_propreitor", "License Propreitor"),
                            ("logo", "Logo"),
                            ("loan_id", "Loan ID"),
                            ("loan_qr", "Loan QR Code"),
                            ("loan_date", "Date"),
                            ("customer_info", "Customer Info"),
                            ("customer_name", "Customer Name"),
                            ("customer_pic", "Customer Photo"),
                            ("loanitem_pic", "Loan Item Photo"),
                            ("loan_desc", "Loan Description"),
                            ("weight", "Weight"),
                            ("value", "Value"),
                            ("address", "Address"),
                            ("phone", "Phone Number"),
                            ("items_table", "Items Table"),
                            ("amount", "Amount"),
                            ("amount_words", "Amount in Words"),
                            ("label", "Label"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("image", "Image"),
                            ("table", "Table"),
                            ("qr", "QR Code"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "x_pos",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="X position in centimeters",
                        max_digits=6,
                    ),
                ),
                (
                    "y_pos",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Y position in centimeters",
                        max_digits=6,
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        decimal_places=2, help_text="Width in centimeters", max_digits=6
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Height in centimeters",
                        max_digits=6,
                    ),
                ),
                ("font_size", models.PositiveIntegerField(default=12)),
                ("font_name", models.CharField(default="Helvetica", max_length=50)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="girvi.loantemplate",
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("O", "Original Copy"),
                            ("D", "Duplicate Copy"),
                            ("B", "Both Copies"),
                        ],
                        default="B",
                        help_text="Specify if frame appears on original, duplicate or both copies",
                        max_length=1,
                    ),
                ),
                ("show_boundary", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "unique_together": {("template", "frame_name", "template_type")},
            },
        ),
    ]
