# Generated by Django 6.0.3 on 2026-08-08 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('girvi', '0028_girvi_number_sequence'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='loan',
            name='unique_loan_id_per_series',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='series',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='LoanPayment',
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
