# Generated by Django 6.0.3 on 2026-08-08 07:37

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girvi', '0030_alter_girvipostingoutboxevent_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('RECEIPT', 'Receipt'), ('PAYMENT', 'Payment')], max_length=8)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('payment_date', models.DateTimeField(db_index=True)),
                ('payment_method', models.CharField(max_length=32)),
                ('reference_number', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('is_final_payment', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accounting_voucher_pk', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='girvi_loan_repayments_created', to=settings.AUTH_USER_MODEL)),
                ('given_loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='repayment_evidence', to='girvi.givenloan')),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='girvi.loanrepayment')),
                ('taken_loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='repayment_evidence', to='girvi.takenloan')),
            ],
            options={
                'ordering': ('payment_date', 'pk'),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('given_loan__isnull', False), ('taken_loan__isnull', True)), models.Q(('given_loan__isnull', True), ('taken_loan__isnull', False)), _connector='OR'), name='girvi_repayment_exactly_one_loan'), models.CheckConstraint(condition=models.Q(('total_amount__gt', 0)), name='girvi_repayment_positive_total'), models.CheckConstraint(condition=models.Q(('principal_amount__gte', 0), ('interest_amount__gte', 0)), name='girvi_repayment_nonnegative_split'), models.CheckConstraint(condition=models.Q(('total_amount', django.db.models.expressions.CombinedExpression(models.F('principal_amount'), '+', models.F('interest_amount')))), name='girvi_repayment_split_matches_total'), models.CheckConstraint(condition=models.Q(models.Q(('given_loan__isnull', False), ('direction', 'RECEIPT')), models.Q(('taken_loan__isnull', False), ('direction', 'PAYMENT')), _connector='OR'), name='girvi_repayment_direction_matches_loan'), models.UniqueConstraint(condition=models.Q(('given_loan__isnull', False)), fields=('given_loan', 'reference_number'), name='girvi_repayment_given_reference_uniq'), models.UniqueConstraint(condition=models.Q(('taken_loan__isnull', False)), fields=('taken_loan', 'reference_number'), name='girvi_repayment_taken_reference_uniq')],
            },
        ),
    ]
