# Generated by Django 6.0.3 on 2026-08-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girvi', '0031_loanrepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='girvipostingoutboxevent',
            name='event_type',
            field=models.CharField(choices=[('DISBURSAL', 'Disbursal'), ('TAKEN_LOAN_ACTIVATION', 'Taken Loan Activation'), ('REPAYMENT', 'Repayment'), ('TAKEN_LOAN_REPAYMENT', 'Taken Loan Repayment'), ('RELEASE', 'Release'), ('ACCRUAL', 'Accrual'), ('AUCTION_RECOVERY', 'Auction Recovery'), ('SALE_RECOVERY', 'Sale Recovery')], db_index=True, max_length=32),
        ),
    ]
