# Generated by Django 5.1.2 on 2024-11-12 17:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "girvi",
            "0026_loantemplate_templateframe_squashed_0040_templateframe_show_boundary",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="loantemplate",
            name="page_height",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Height in centimeters",
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="loantemplate",
            name="page_width",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Width in centimeters",
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
