# Generated by Django 5.1.2 on 2024-11-19 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "girvi",
            "0014_loanitempic_squashed_0041_alter_loantemplate_page_height_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="loanitem",
            name="is_repledged",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="loanitem",
            name="repledged_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="repledged_items",
                to="girvi.loan",
            ),
        ),
    ]
