# Generated by Django 5.1.2 on 2024-12-01 19:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0042_loanitem_is_repledged_loanitem_repledged_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loanitem",
            name="repledged_to",
        ),
        migrations.AlterModelOptions(
            name="loanitem",
            options={"get_latest_by": "id", "ordering": ("id", "loan")},
        ),
        migrations.AddField(
            model_name="series",
            name="loan_type",
            field=models.CharField(
                blank=True,
                choices=[("Taken", "Taken"), ("Given", "Given")],
                default="Given",
                max_length=10,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="RepledgedLoanItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "repledged_loanamount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "repledged_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repledgedloanitems",
                        to="girvi.loan",
                    ),
                ),
                (
                    "original_loanitem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repledged_items",
                        to="girvi.loanitem",
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                (
                    "interest",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
        ),
    ]
