# Generated by Django 5.1.2 on 2024-12-11 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "girvi",
            "0043_remove_loanitem_repledged_to_repledgedloanitem_squashed_0049_repledgedloanitem_interest",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="status",
            field=models.CharField(
                choices=[
                    ("Created", "Created"),
                    ("Cancelled", "Cancelled"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Disbursed", "Disbursed"),
                    ("Closed", "Closed"),
                    ("Released", "Released"),
                    ("Repledged", "Repledged"),
                    ("Sold", "Sold"),
                    ("Defaulted", "Defaulted"),
                    ("Auctioned", "Auctioned"),
                ],
                default="Created",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="statement",
            name="completed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="statements_completed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="statement",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="statement",
            name="reopened_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="statement",
            name="reopened_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="statements_reopened",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="statement",
            name="statement_type",
            field=models.CharField(
                choices=[
                    ("REGULAR", "Regular Verification"),
                    ("SPOT", "Spot Check"),
                    ("ANNUAL", "Annual Audit"),
                ],
                default="REGULAR",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="statement",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("REOPENED", "Reopened"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="statementitem",
            name="auto_generated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="statementitem",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="statement_items_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="statementitem",
            name="descrepancy_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MISSING", "Item Missing"),
                    ("WEIGHT", "Weight Mismatch"),
                    ("CONDITION", "Condition Changed"),
                    ("RELEASED", "Released but Present"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
