# Generated by Django 5.1.2 on 2024-12-14 12:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0050_loan_status_statement_completed_by_statement_notes_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loan",
            options={
                "get_latest_by": "id",
                "ordering": ("series", "loan_id"),
                "permissions": [
                    ("can_approve_loan", "Can approve loan"),
                    ("can_disburse_loan", "Can disburse loan"),
                    ("can_release_loan", "Can release loan"),
                    ("can_cancel_loan", "Can cancel loan"),
                    ("can_mark_defaulted", "Can mark loan as defaulted"),
                    ("can_mark_auctioned", "Can mark loan as auctioned"),
                    ("can_mark_sold", "Can mark loan as sold"),
                ],
            },
        ),
        migrations.RemoveField(
            model_name="loan",
            name="lid",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="status",
        ),
    ]
