# Generated by Django 5.1.2 on 2024-12-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0052_loanchangelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="status",
            field=models.CharField(
                choices=[
                    ("Created", "Created"),
                    ("Cancelled", "Cancelled"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Disbursed", "Disbursed"),
                    ("Closed", "Closed"),
                    ("Released", "Released"),
                    ("Repledged", "Repledged"),
                    ("Sold", "Sold"),
                    ("Defaulted", "Defaulted"),
                    ("Auctioned", "Auctioned"),
                ],
                default="Created",
                max_length=20,
            ),
        ),
    ]
