# Generated by Django 5.1.2 on 2024-12-15 14:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0054_loan_approved_at_loan_approved_by_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loanchangelog",
            old_name="review",
            new_name="loan",
        ),
    ]
