# Generated by Django 5.1.2 on 2024-12-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0055_rename_review_loanchangelog_loan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanchangelog",
            name="source",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="loanchangelog",
            name="target",
            field=models.CharField(max_length=255),
        ),
    ]
