# Generated by Django 5.0.8 on 2025-03-24 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0017_alter_contact_is_default"),
        ("girvi", "0056_alter_loanchangelog_source_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="series",
            name="prefix",
            field=models.CharField(
                default="Z",
                help_text="Prefix for loan IDs in this series",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="series",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loans",
                to="girvi.series",
                verbose_name="Series",
            ),
        ),
        migrations.AlterField(
            model_name="series",
            name="max_limit",
            field=models.PositiveIntegerField(
                default=5,
                help_text="Number of digits in loan ID sequence",
                verbose_name="Max Limit",
            ),
        ),
        migrations.AddConstraint(
            model_name="loan",
            constraint=models.UniqueConstraint(
                fields=("series", "loan_id"), name="unique_loan_id_per_series"
            ),
        ),
    ]
