# Generated by Django 5.0.8 on 2025-03-25 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0057_series_prefix_alter_loan_series_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loanchangelog",
            options={"ordering": ["-changed"]},
        ),
        migrations.RemoveField(
            model_name="loan",
            name="approved_at",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="auction_amount",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="auctioned_at",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="auctioned_by",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="cancellation_reason",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="cancelled_at",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="cancelled_by",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="default_reason",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="defaulted_at",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="defaulted_by",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="disbursed_at",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="disbursed_by",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="sold_amount",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="sold_at",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="sold_by",
        ),
        migrations.AddField(
            model_name="loanchangelog",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="loanchangelog",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="loan",
            name="series",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="girvi.series",
                verbose_name="Series",
            ),
        ),
    ]
