# Generated by Django 6.0.3 on 2026-08-16 21:47

import apps.tenant_apps.party.models.document
import apps.tenant_apps.party.models.party
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_code', models.CharField(blank=True, db_index=True, help_text='Workspace-scoped party code.', max_length=32)),
                ('party_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('ORGANIZATION', 'Organization'), ('BANK', 'Bank'), ('GOVERNMENT', 'Government Body'), ('INTERNAL_WORKSPACE', 'Internal Workspace Entity'), ('OTHER', 'Other')], db_index=True, default='INDIVIDUAL', max_length=32)),
                ('display_name', models.CharField(db_index=True, max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('normalized_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('relation_label', models.CharField(blank=True, choices=[('SON_OF', 'S/o'), ('DAUGHTER_OF', 'D/o'), ('CARE_OF', 'C/o'), ('PARENT_OF', 'P/o'), ('FATHER_OF', 'F/o'), ('WIFE_OF', 'W/o'), ('HUSBAND_OF', 'H/o'), ('OTHER', 'O/o')], max_length=16)),
                ('relation_name', models.CharField(blank=True, max_length=255)),
                ('primary_phone', models.CharField(blank=True, max_length=32)),
                ('primary_email', models.EmailField(blank=True, max_length=254)),
                ('profile_photo', models.ImageField(blank=True, upload_to=apps.tenant_apps.party.models.party.party_profile_photo_upload_to)),
                ('tax_pan', models.CharField(blank=True, db_index=True, max_length=16)),
                ('gstin', models.CharField(blank=True, db_index=True, max_length=24)),
                ('risk_level', models.CharField(blank=True, max_length=32)),
                ('credit_hold', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BLOCKED', 'Blocked'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parties_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parties_updated', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company')),
            ],
            options={
                'verbose_name': 'Party',
                'verbose_name_plural': 'Parties',
                'ordering': ('display_name', 'party_code'),
            },
        ),
        migrations.CreateModel(
            name='PartyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('REGISTERED', 'Registered'), ('BILLING', 'Billing'), ('SHIPPING', 'Shipping'), ('HOME', 'Home'), ('WORK', 'Work'), ('KYC', 'KYC'), ('OTHER', 'Other')], default='BILLING', max_length=16)),
                ('line1', models.CharField(max_length=255)),
                ('line2', models.CharField(blank=True, max_length=255)),
                ('area', models.CharField(blank=True, max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(blank=True, max_length=128)),
                ('postal_code', models.CharField(blank=True, max_length=24)),
                ('country', models.CharField(default='IN', max_length=2)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='party.party')),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company')),
            ],
            options={
                'verbose_name': 'Party Address',
                'verbose_name_plural': 'Party Addresses',
                'ordering': ('party', '-is_default', 'address_type'),
            },
        ),
        migrations.CreateModel(
            name='PartyCodeSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company')),
            ],
            options={
                'verbose_name': 'Party Code Sequence',
                'verbose_name_plural': 'Party Code Sequences',
            },
        ),
        migrations.CreateModel(
            name='PartyContactMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('PHONE', 'Phone'), ('MOBILE', 'Mobile'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('WEBSITE', 'Website'), ('OTHER', 'Other')], max_length=16)),
                ('label', models.CharField(blank=True, max_length=64)),
                ('value', models.CharField(max_length=255)),
                ('normalized_value', models.CharField(blank=True, db_index=True, max_length=255)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_methods', to='party.party')),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company')),
            ],
            options={
                'verbose_name': 'Party Contact Method',
                'verbose_name_plural': 'Party Contact Methods',
                'ordering': ('party', '-is_primary', 'contact_type'),
            },
        ),
        migrations.CreateModel(
            name='PartyIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier_type', models.CharField(choices=[('PAN', 'PAN'), ('AADHAAR', 'Aadhaar'), ('GSTIN', 'GSTIN'), ('CIN', 'CIN'), ('UDYAM', 'Udyam'), ('PASSPORT', 'Passport'), ('DRIVING_LICENSE', 'Driving License'), ('OTHER', 'Other')], max_length=32)),
                ('value', models.CharField(max_length=128)),
                ('masked_value', models.CharField(blank=True, max_length=128)),
                ('value_hash', models.CharField(blank=True, db_index=True, max_length=128)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='party.party')),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company')),
            ],
            options={
                'verbose_name': 'Party Identifier',
                'verbose_name_plural': 'Party Identifiers',
                'ordering': ('party', 'identifier_type'),
            },
        ),
        migrations.CreateModel(
            name='PartyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('KYC', 'KYC'), ('TAX', 'Tax'), ('CONTRACT', 'Contract'), ('LICENSE', 'License'), ('OTHER', 'Other')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, upload_to=apps.tenant_apps.party.models.document.party_document_upload_to)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='party.party')),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company')),
                ('identifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='party.partyidentifier')),
            ],
            options={
                'verbose_name': 'Party Document',
                'verbose_name_plural': 'Party Documents',
                'ordering': ('party', 'document_type', 'title'),
            },
        ),
        migrations.CreateModel(
            name='PartyPortalAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('INVITED', 'Invited'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('REVOKED', 'Revoked')], db_index=True, default='INVITED', max_length=16)),
                ('invited_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portal_access_grants', to='party.party')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_portal_access_grants', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company')),
            ],
            options={
                'verbose_name': 'Party Portal Access',
                'verbose_name_plural': 'Party Portal Access Grants',
                'ordering': ('party', 'user', 'status'),
            },
        ),
        migrations.CreateModel(
            name='PartyRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('CONTACT_PERSON', 'Contact Person'), ('EMPLOYER', 'Employer'), ('EMPLOYEE', 'Employee'), ('BROKER', 'Broker'), ('AGENT', 'Agent'), ('RELATED_BUSINESS', 'Related Business'), ('FAMILY', 'Family'), ('OTHER', 'Other')], max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='party.party')),
                ('to_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='party.party')),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company')),
            ],
            options={
                'verbose_name': 'Party Relationship',
                'verbose_name_plural': 'Party Relationships',
                'ordering': ('from_party', 'to_party', 'relationship_type'),
            },
        ),
        migrations.CreateModel(
            name='PartyRoleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64)),
                ('label', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company')),
            ],
            options={
                'verbose_name': 'Party Role Type',
                'verbose_name_plural': 'Party Role Types',
                'ordering': ('sort_order', 'label'),
            },
        ),
        migrations.CreateModel(
            name='PartyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ENDED', 'Ended')], db_index=True, default='ACTIVE', max_length=16)),
                ('segment', models.CharField(blank=True, help_text='Optional role-specific segment such as RETAIL or WHOLESALE.', max_length=64)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='party.party')),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company')),
                ('role_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='party_roles', to='party.partyroletype')),
            ],
            options={
                'verbose_name': 'Party Role',
                'verbose_name_plural': 'Party Roles',
                'ordering': ('party', 'role_type'),
            },
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['workspace', 'party_code'], name='party_party_workspa_145b27_idx'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['status', 'party_type'], name='party_party_status_388b24_idx'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['normalized_name'], name='party_party_normali_9e387b_idx'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['tax_pan'], name='party_party_tax_pan_670826_idx'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['gstin'], name='party_party_gstin_404645_idx'),
        ),
        migrations.AddConstraint(
            model_name='party',
            constraint=models.UniqueConstraint(fields=('workspace', 'party_code'), name='party_workspace_code_uniq'),
        ),
        migrations.AddIndex(
            model_name='partyaddress',
            index=models.Index(fields=['party', 'address_type'], name='party_party_party_i_22e4f2_idx'),
        ),
        migrations.AddIndex(
            model_name='partyaddress',
            index=models.Index(fields=['city', 'state'], name='party_party_city_9a4c5b_idx'),
        ),
        migrations.AddConstraint(
            model_name='partyaddress',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('party', 'address_type'), name='party_one_default_address_per_type'),
        ),
        migrations.AddConstraint(
            model_name='partycodesequence',
            constraint=models.UniqueConstraint(fields=('workspace', 'key'), name='party_sequence_workspace_key_uniq'),
        ),
        migrations.AddIndex(
            model_name='partycontactmethod',
            index=models.Index(fields=['party', 'contact_type'], name='party_party_party_i_4d7ac4_idx'),
        ),
        migrations.AddIndex(
            model_name='partycontactmethod',
            index=models.Index(fields=['normalized_value'], name='party_party_normali_472d11_idx'),
        ),
        migrations.AddConstraint(
            model_name='partycontactmethod',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('party', 'contact_type'), name='party_one_primary_contact_per_type'),
        ),
        migrations.AddIndex(
            model_name='partyidentifier',
            index=models.Index(fields=['identifier_type', 'value_hash'], name='party_party_identif_2634c8_idx'),
        ),
        migrations.AddIndex(
            model_name='partyidentifier',
            index=models.Index(fields=['party', 'identifier_type'], name='party_party_party_i_1aac7b_idx'),
        ),
        migrations.AddConstraint(
            model_name='partyidentifier',
            constraint=models.UniqueConstraint(fields=('party', 'identifier_type'), name='party_one_identifier_per_type'),
        ),
        migrations.AddIndex(
            model_name='partydocument',
            index=models.Index(fields=['party', 'document_type'], name='party_party_party_i_00fc82_idx'),
        ),
        migrations.AddIndex(
            model_name='partydocument',
            index=models.Index(fields=['expires_on'], name='party_party_expires_9cf5c7_idx'),
        ),
        migrations.AddIndex(
            model_name='partyportalaccess',
            index=models.Index(fields=['user', 'status'], name='party_party_user_id_627e4a_idx'),
        ),
        migrations.AddIndex(
            model_name='partyportalaccess',
            index=models.Index(fields=['party', 'status'], name='party_party_party_i_b1c4aa_idx'),
        ),
        migrations.AddConstraint(
            model_name='partyportalaccess',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['INVITED', 'ACTIVE', 'SUSPENDED'])), fields=('party', 'user'), name='party_one_live_portal_access_per_user_party'),
        ),
        migrations.AddIndex(
            model_name='partyrelationship',
            index=models.Index(fields=['from_party', 'relationship_type'], name='party_party_from_pa_02dd6d_idx'),
        ),
        migrations.AddIndex(
            model_name='partyrelationship',
            index=models.Index(fields=['to_party', 'relationship_type'], name='party_party_to_part_2bf884_idx'),
        ),
        migrations.AddConstraint(
            model_name='partyrelationship',
            constraint=models.UniqueConstraint(fields=('from_party', 'to_party', 'relationship_type'), name='party_relationship_uniq'),
        ),
        migrations.AddConstraint(
            model_name='partyrelationship',
            constraint=models.CheckConstraint(condition=models.Q(('from_party', models.F('to_party')), _negated=True), name='party_relationship_not_self'),
        ),
        migrations.AddConstraint(
            model_name='partyroletype',
            constraint=models.UniqueConstraint(fields=('workspace', 'key'), name='party_role_type_workspace_key_uniq'),
        ),
        migrations.AddIndex(
            model_name='partyrole',
            index=models.Index(fields=['party', 'status'], name='party_party_party_i_1d2f83_idx'),
        ),
        migrations.AddIndex(
            model_name='partyrole',
            index=models.Index(fields=['role_type', 'status'], name='party_party_role_ty_b3fa40_idx'),
        ),
        migrations.AddConstraint(
            model_name='partyrole',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('party', 'role_type'), name='party_one_active_role_per_type'),
        ),
    ]
