# Generated by Django 6.0.3 on 2026-06-19 07:47

import apps.tenant_apps.party.models.party
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to=apps.tenant_apps.party.models.party.party_profile_photo_upload_to),
        ),
    ]
