# Generated by Django 6.1.1 on 2026-09-25 05:41

import apps.tenant_apps.party.models.party
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from apps.tenancy.rls import EnableWorkspaceRLS


def preserve_current_photos(apps, schema_editor):
    Party = apps.get_model("party", "Party")
    Photo = apps.get_model("party", "PartyPhoto")
    alias = schema_editor.connection.alias
    for party in Party.objects.using(alias).exclude(profile_photo="").iterator():
        Photo.objects.using(alias).get_or_create(workspace_id=party.workspace_id,
            party_id=party.pk, file=party.profile_photo.name)


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0009_workspace_role_identity'),
        ('party', '0002_enable_workspace_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=apps.tenant_apps.party.models.party.party_profile_photo_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='party.party')),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company')),
            ],
            options={
                'ordering': ('pk',),
                'constraints': [models.UniqueConstraint(fields=('party', 'file'), name='party_photo_file_uniq')],
            },
        ),
        migrations.RunPython(preserve_current_photos, migrations.RunPython.noop),
        EnableWorkspaceRLS("PartyPhoto"),
        migrations.RunSQL("""
CREATE FUNCTION party_photo_parent_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF NOT EXISTS (SELECT 1 FROM party_party p WHERE p.id=NEW.party_id AND p.workspace_id=NEW.workspace_id)
 THEN RAISE EXCEPTION 'Photo parent must belong to the same workspace'; END IF;
 RETURN NEW;
END; $$;
CREATE TRIGGER party_photo_parent_guard BEFORE INSERT OR UPDATE ON party_partyphoto
FOR EACH ROW EXECUTE FUNCTION party_photo_parent_guard();
""", """
DROP TRIGGER party_photo_parent_guard ON party_partyphoto;
DROP FUNCTION party_photo_parent_guard();
"""),
    ]
