# Generated by Django 6.0.3 on 2026-06-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_party_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='relation_label',
            field=models.CharField(blank=True, choices=[('SON_OF', 'S/o'), ('DAUGHTER_OF', 'D/o'), ('CARE_OF', 'C/o'), ('PARENT_OF', 'P/o'), ('FATHER_OF', 'F/o'), ('WIFE_OF', 'W/o'), ('HUSBAND_OF', 'H/o'), ('OTHER', 'O/o')], max_length=16),
        ),
        migrations.AddField(
            model_name='party',
            name='relation_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
