# Generated by Django 6.0.3 on 2026-08-16 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0025_alter_company_schema_name'),
        ('party', '0005_partyportalaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='partyaddress',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='partycodesequence',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='partycontactmethod',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='partydocument',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='partyidentifier',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='partyportalaccess',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='partyrelationship',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='partyrole',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AddField(
            model_name='partyroletype',
            name='workspace',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AlterField(
            model_name='party',
            name='party_code',
            field=models.CharField(blank=True, db_index=True, help_text='Workspace-scoped party code.', max_length=32),
        ),
        migrations.AlterField(
            model_name='partycodesequence',
            name='key',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='partyroletype',
            name='key',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['workspace', 'party_code'], name='party_party_workspa_145b27_idx'),
        ),
        migrations.AddConstraint(
            model_name='party',
            constraint=models.UniqueConstraint(fields=('workspace', 'party_code'), name='party_workspace_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='partycodesequence',
            constraint=models.UniqueConstraint(fields=('workspace', 'key'), name='party_sequence_workspace_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='partyroletype',
            constraint=models.UniqueConstraint(fields=('workspace', 'key'), name='party_role_type_workspace_key_uniq'),
        ),
    ]
