# Generated by Django 6.0.3 on 2026-08-16 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0025_alter_company_schema_name'),
        ('party', '0007_backfill_party_workspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='workspace',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AlterField(
            model_name='partyaddress',
            name='workspace',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AlterField(
            model_name='partycodesequence',
            name='workspace',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AlterField(
            model_name='partycontactmethod',
            name='workspace',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AlterField(
            model_name='partydocument',
            name='workspace',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AlterField(
            model_name='partyidentifier',
            name='workspace',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AlterField(
            model_name='partyportalaccess',
            name='workspace',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AlterField(
            model_name='partyrelationship',
            name='workspace',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AlterField(
            model_name='partyrole',
            name='workspace',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
        migrations.AlterField(
            model_name='partyroletype',
            name='workspace',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company'),
        ),
    ]
