# Generated by Django 4.2.3 on 2023-07-23 11:17


from django.core.management import call_command
from django.db import migrations


def noop_forward(apps, schema_editor):
    # Seed moved to apps.orgs.management.commands.seed_tenant_defaults.
    pass


def load_fixture(apps, schema_editor):
    call_command("loaddata", "apps/tenant_apps/terms/fixtures/data.json")


class Migration(migrations.Migration):
    dependencies = [
        ("terms", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(noop_forward, reverse_code=migrations.RunPython.noop),
    ]
