# Generated by Django 4.2.3 on 2023-07-23 11:17

from django.db import migrations
from django.db.migrations.operations.base import Operation


class CreateView(Operation):
    reversible = True

    def __init__(self, name, sql):
        self.name = name
        self.sql = sql

    def state_forwards(self, app_label, state):
        pass

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        schema_editor.execute(f"CREATE VIEW {self.name} AS {self.sql}")

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        schema_editor.execute(f"DROP VIEW IF EXISTS {self.name};")

    def describe(self):
        return "Creates VIEW %s" % self.name

    @property
    def migration_name_fragment(self):
        return "create_view_%s" % self.name


class Migration(migrations.Migration):
    dependencies = [
        ("dea", "0002_initial_fixture"),
    ]
    lb_yay1 = """
    -- CREATE OR REPLACE VIEW ledger_balances AS
     WITH all_ledgers AS (
         SELECT dea_ledger.id
           FROM jcl.dea_ledger
        ), latest_ls AS (
         SELECT l.id AS ledgerno_id,
            ls.created,
            ls."ClosingBalance" AS open_balance
           FROM jcl.dea_ledger l
             LEFT JOIN ( SELECT DISTINCT ON (ls_1.ledgerno_id) ls_1.ledgerno_id,
                    ls_1.created,
                    ls_1."ClosingBalance"
                   FROM jcl.dea_ledgerstatement ls_1
                  ORDER BY ls_1.ledgerno_id, ls_1.created DESC) ls ON l.id = ls.ledgerno_id
        ), ls_open AS (
         SELECT l.ledgerno_id,
            cb_elem.currency,
            cb_elem.amount AS opening_balance,
            l.created
           FROM latest_ls l,
            LATERAL unnest(l.open_balance) cb_elem(amount, currency)
        ), txn_debit AS (
         SELECT combined.ledgerno,
            combined.amount_currency,
            sum(combined.amount) AS total_debit
           FROM ( SELECT lt.ledgerno_dr_id AS ledgerno,
                    lt.amount_currency,
                    lt.amount
                   FROM jcl.dea_ledgertransaction lt
                     JOIN latest_ls l ON lt.ledgerno_dr_id = l.ledgerno_id
                  WHERE lt.created > l.created
                UNION ALL
                 SELECT at.ledgerno_id AS ledgerno,
                    at.amount_currency,
                    at.amount
                   FROM jcl.dea_accounttransaction at
                     JOIN latest_ls l ON at.ledgerno_id = l.ledgerno_id
                  WHERE at.created > l.created AND at."XactTypeCode_id"::text = 'Dr'::text) combined
          GROUP BY combined.ledgerno, combined.amount_currency
        ), txn_credit AS (
         SELECT combined.ledgerno,
            combined.amount_currency,
            sum(combined.amount) AS total_credit
           FROM ( SELECT lt.ledgerno_id AS ledgerno,
                    lt.amount_currency,
                    lt.amount
                   FROM jcl.dea_ledgertransaction lt
                     JOIN latest_ls l ON lt.ledgerno_id = l.ledgerno_id
                  WHERE lt.created > l.created
                UNION ALL
                 SELECT at.ledgerno_id AS ledgerno,
                    at.amount_currency,
                    at.amount
                   FROM jcl.dea_accounttransaction at
                     JOIN latest_ls l ON at.ledgerno_id = l.ledgerno_id
                  WHERE at.created > l.created AND at."XactTypeCode_id"::text = 'Cr'::text) combined
          GROUP BY combined.ledgerno, combined.amount_currency
        ), all_keys AS (
         SELECT ls_open.ledgerno_id,
            ls_open.currency,
            ls_open.created
           FROM ls_open
        UNION
         SELECT txn_debit.ledgerno,
            txn_debit.amount_currency,
            l.created
           FROM txn_debit
             JOIN latest_ls l ON txn_debit.ledgerno = l.ledgerno_id
        UNION
         SELECT txn_credit.ledgerno,
            txn_credit.amount_currency,
            l.created
           FROM txn_credit
             JOIN latest_ls l ON txn_credit.ledgerno = l.ledgerno_id
        ), ddata AS (
         SELECT ak.ledgerno_id,
            ak.currency,
            ak.created,
            o.opening_balance,
            COALESCE(d.total_debit, 0::numeric) AS total_debit,
            COALESCE(c.total_credit, 0::numeric) AS total_credit
           FROM all_keys ak
             LEFT JOIN ls_open o ON ak.ledgerno_id = o.ledgerno_id AND ak.currency::text = o.currency::text
             LEFT JOIN txn_debit d ON ak.ledgerno_id = d.ledgerno AND ak.currency::text = o.currency::text
             LEFT JOIN txn_credit c ON ak.ledgerno_id = c.ledgerno AND ak.currency::text = o.currency::text
        )
 SELECT al.id AS ledgerno_id,
    max(ddata.created) AS statement_created,
        CASE
            WHEN count(ddata.opening_balance) = 0 THEN NULL::money_value[]
            ELSE array_agg(ROW(COALESCE(ddata.opening_balance, 0::numeric)::numeric(14,3), ddata.currency)::money_value ORDER BY ddata.currency)
        END AS opening_balance,
        CASE
            WHEN count(ddata.total_debit) = 0 THEN ARRAY[ROW(0::numeric::numeric(14,3), 'INR'::character varying(3))::money_value]
            ELSE array_agg(ROW(ddata.total_debit::numeric(14,3), ddata.currency)::money_value ORDER BY ddata.currency)
        END AS debit,
        CASE
            WHEN count(ddata.total_credit) = 0 THEN ARRAY[ROW(0::numeric::numeric(14,3), 'INR'::character varying(3))::money_value]
            ELSE array_agg(ROW(ddata.total_credit::numeric(14,3), ddata.currency)::money_value ORDER BY ddata.currency)
        END AS credit,
        CASE
            WHEN count(ddata.opening_balance) = 0 THEN ARRAY[ROW(0::numeric::numeric(14,3), 'INR'::character varying(3))::money_value]
            ELSE array_agg(ROW((COALESCE(ddata.opening_balance, 0::numeric) + ddata.total_debit - ddata.total_credit)::numeric(14,3), ddata.currency)::money_value ORDER BY ddata.currency)
        END AS closing_balance
   FROM all_ledgers al
     LEFT JOIN ddata ON al.id = ddata.ledgerno_id
  GROUP BY al.id;
"""
    lb_yay = """
    -- CREATE OR REPLACE VIEW ledger_balances AS
WITH latest_ls AS (
  -- For each ledger, fetch its latest ledger statement.
  SELECT DISTINCT ON (ls.ledgerno_id)
         ls.ledgerno_id,
         ls.created,
         ls."ClosingBalance" AS open_balance
  FROM jcl.dea_ledgerstatement ls
  ORDER BY ls.ledgerno_id, ls.created DESC
),
ls_open AS (
  -- Unnest the closing_balance array from the latest statement.
  -- Each row now represents one (currency, opening_balance) pair.
  SELECT l.ledgerno_id,
         (cb_elem).currency AS currency,
         (cb_elem).amount AS opening_balance,
         l.created
  FROM latest_ls l,
       LATERAL unnest(l.open_balance) AS cb_elem
),
txn_debit AS (
  -- Sum debit transactions (where ledger appears as ledgerno_dr)
  -- that occurred after the latest statement.
  SELECT lt.ledgerno_dr_id AS ledgerno,
         lt.amount_currency AS currency,
         SUM(lt.amount) AS total_debit
  FROM jcl.dea_ledgertransaction lt
  JOIN latest_ls l ON lt.ledgerno_dr_id = l.ledgerno_id
  WHERE lt.created > l.created
  GROUP BY lt.ledgerno_dr_id, lt.amount_currency
),
txn_credit AS (
  -- Sum credit transactions (where ledger appears as ledgerno)
  -- that occurred after the latest statement.
  SELECT lt.ledgerno_id AS ledgerno,
         lt.amount_currency AS currency,
         SUM(lt.amount) AS total_credit
  FROM jcl.dea_ledgertransaction lt
  JOIN latest_ls l ON lt.ledgerno_id = l.ledgerno_id
  WHERE lt.created > l.created
  GROUP BY lt.ledgerno_id, lt.amount_currency
),
all_keys AS (
  -- Build a complete list of (ledger, currency) pairs from all sources.
  SELECT ledgerno_id, currency FROM ls_open
  UNION
  SELECT ledgerno, currency FROM txn_debit
  UNION
  SELECT ledgerno, currency FROM txn_credit
)
SELECT 
  ak.ledgerno_id,
  -- Aggregate opening balances into a money_value array.
  array_agg(ROW(COALESCE(o.opening_balance, 0), ak.currency)::money_value ORDER BY ak.currency) AS opening_balance,
  -- Aggregate debit totals into a money_value array.
  array_agg(ROW(COALESCE(d.total_debit, 0), ak.currency)::money_value ORDER BY ak.currency) AS debit,
  -- Aggregate credit totals into a money_value array.
  array_agg(ROW(COALESCE(c.total_credit, 0), ak.currency)::money_value ORDER BY ak.currency) AS credit,
  -- Compute and aggregate the closing balance per currency.
  array_agg(
    ROW(
      COALESCE(o.opening_balance, 0) 
      + COALESCE(d.total_debit, 0)
      - COALESCE(c.total_credit, 0),
      ak.currency
    )::money_value ORDER BY ak.currency
  ) AS closing_balance
FROM all_keys ak
LEFT JOIN ls_open o ON ak.ledgerno_id = o.ledgerno_id AND ak.currency = o.currency
LEFT JOIN txn_debit d ON ak.ledgerno_id = d.ledgerno AND ak.currency = d.currency
LEFT JOIN txn_credit c ON ak.ledgerno_id = c.ledgerno AND ak.currency = c.currency
GROUP BY ak.ledgerno_id;
    
"""
    ledger_balance_fucking_v1 = """
    WITH ls AS (
    SELECT DISTINCT ON (dea_ledgerstatement.ledgerno_id) 
        dea_ledgerstatement.id,
        dea_ledgerstatement.created,
        dea_ledgerstatement."ClosingBalance",
        dea_ledgerstatement.ledgerno_id
    FROM dea_ledgerstatement
    ORDER BY dea_ledgerstatement.ledgerno_id, dea_ledgerstatement.created DESC
), unnested_closing_balance AS (
    SELECT s.ledgerno_id,
        (unnest(s."ClosingBalance")).amount AS amount,
        (unnest(s."ClosingBalance")).currency AS currency
    FROM ls s
), transactions_since_latest AS (
    SELECT t.ledgerno_id,
        t.amount_currency,
        sum(
            CASE
                WHEN t.ledgerno_id = t.ledgerno_dr_id THEN t.amount
                ELSE 0::numeric
            END) AS total_debit,
        sum(
            CASE
                WHEN t.ledgerno_id <> t.ledgerno_dr_id THEN t.amount
                ELSE 0::numeric
            END) AS total_credit
    FROM dea_ledgertransaction t
    LEFT JOIN ls s ON t.ledgerno_id = s.ledgerno_id
    WHERE t.created > COALESCE(s.created, '1970-01-01 00:00:00+05:30'::timestamp with time zone)
    GROUP BY t.ledgerno_id, t.amount_currency
)
SELECT l.id AS ledgerno_id,
    l.name,
    at."AccountType",
    ls.created AS ls_created,
    COALESCE(ls."ClosingBalance", ARRAY[ROW(0::numeric, 'USD')::money_value]) AS opening_balance,
    array_agg(ROW(COALESCE(tsl.total_credit, 0::numeric)::numeric(14,3), COALESCE(tsl.amount_currency, 'USD'))::money_value) AS cr,
    array_agg(ROW(COALESCE(tsl.total_debit, 0::numeric)::numeric(14,3), COALESCE(tsl.amount_currency, 'USD'))::money_value) AS dr,
    array_agg(ROW(
        CASE
            WHEN at."AccountType"::text = ANY (ARRAY['Asset'::character varying, 'Expense'::character varying]::text[]) THEN COALESCE(ucb.amount, 0::numeric) + COALESCE(tsl.total_debit - tsl.total_credit, 0::numeric)::numeric(14,3)
            ELSE COALESCE(ucb.amount, 0::numeric) + COALESCE(tsl.total_credit - tsl.total_debit, 0::numeric)::numeric(14,3)
        END::numeric(14,3), COALESCE(ucb.currency, 'USD'))::money_value) AS closing_balance
FROM dea_ledger l
LEFT JOIN ls ON l.id = ls.ledgerno_id
LEFT JOIN unnested_closing_balance ucb ON l.id = ucb.ledgerno_id
LEFT JOIN transactions_since_latest tsl ON ucb.ledgerno_id = tsl.ledgerno_id AND ucb.currency::text = tsl.amount_currency::text
LEFT JOIN dea_accounttype at ON l."AccountType_id" = at.id
GROUP BY l.id, l.name, at."AccountType", ls.created, ls."ClosingBalance";
    """
    ledger_balance_fucking = """
         WITH ls AS (
         SELECT DISTINCT ON (dea_ledgerstatement.ledgerno_id) dea_ledgerstatement.id,
            dea_ledgerstatement.created,
            dea_ledgerstatement."ClosingBalance",
            dea_ledgerstatement.ledgerno_id
           FROM dea_ledgerstatement
          ORDER BY dea_ledgerstatement.ledgerno_id, dea_ledgerstatement.created DESC
        ), unnested_closing_balance AS (
         SELECT s.ledgerno_id,
            (unnest(s."ClosingBalance")).amount AS amount,
            (unnest(s."ClosingBalance")).currency AS currency
           FROM ls s
        ), transactions_since_latest AS (
         SELECT t.ledgerno_id,
            t.amount_currency,
            sum(
                CASE
                    WHEN t.ledgerno_id = t.ledgerno_dr_id THEN t.amount
                    ELSE 0::numeric
                END) AS total_debit,
            sum(
                CASE
                    WHEN t.ledgerno_id <> t.ledgerno_dr_id THEN t.amount
                    ELSE 0::numeric
                END) AS total_credit
           FROM dea_ledgertransaction t
             LEFT JOIN ls s ON t.ledgerno_id = s.ledgerno_id
          WHERE t.created > COALESCE(s.created, '1970-01-01 00:00:00+05:30'::timestamp with time zone)
          GROUP BY t.ledgerno_id, t.amount_currency
        )
 SELECT l.id AS ledgerno_id,
    l.name,
    at."AccountType",
    ls.created AS ls_created,
    ls."ClosingBalance" AS opening_balance,
    array_agg(ROW(COALESCE(tsl.total_credit, 0::numeric)::numeric(14,3), tsl.amount_currency)::money_value) AS cr,
    array_agg(ROW(COALESCE(tsl.total_debit, 0::numeric)::numeric(14,3), tsl.amount_currency)::money_value) AS dr,
    array_agg(ROW(
        CASE
            WHEN at."AccountType"::text = ANY (ARRAY['Asset'::character varying, 'Expense'::character varying]::text[]) THEN COALESCE(ucb.amount, 0::numeric) + COALESCE(tsl.total_debit - tsl.total_credit, 0::numeric)::numeric(14,3)
            ELSE COALESCE(ucb.amount, 0::numeric) + COALESCE(tsl.total_credit - tsl.total_debit, 0::numeric)::numeric(14,3)
        END::numeric(14,3), ucb.currency)::money_value) AS closing_balance
   FROM dea_ledger l
     LEFT JOIN ls ON l.id = ls.ledgerno_id
     LEFT JOIN unnested_closing_balance ucb ON l.id = ucb.ledgerno_id
     LEFT JOIN transactions_since_latest tsl ON ucb.ledgerno_id = tsl.ledgerno_id AND ucb.currency::text = tsl.amount_currency::text
     LEFT JOIN dea_accounttype at ON l."AccountType_id" = at.id
  GROUP BY l.id, l.name, at."AccountType", ls.created, ls."ClosingBalance";
    """
    ledger_balance_sql_final = """
       
    WITH ls AS (
        SELECT DISTINCT ON (dea_ledgerstatement.ledgerno_id)
            dea_ledgerstatement.id,
            dea_ledgerstatement.created,
            dea_ledgerstatement."ClosingBalance",
            dea_ledgerstatement.ledgerno_id
        FROM dea_ledgerstatement
        ORDER BY dea_ledgerstatement.ledgerno_id, dea_ledgerstatement.created DESC
    ), unnested_closing_balance AS (
        SELECT s.ledgerno_id,
            (unnest(s."ClosingBalance")).amount AS amount,
            (unnest(s."ClosingBalance")).currency AS currency
        FROM ls s
    ), transactions_since_latest AS (
        SELECT t.ledgerno_id,
            t.amount_currency,
            SUM(CASE WHEN t."XactTypeCode" = 'Dr' THEN t.amount ELSE 0 END) AS total_debit,
            SUM(CASE WHEN t."XactTypeCode" = 'Cr' THEN t.amount ELSE 0 END) AS total_credit
        FROM dea_ledgertransaction t
        LEFT JOIN ls s ON t.ledgerno_id = s.ledgerno_id
        WHERE t.created > COALESCE(s.created, '1970-01-01'::timestamp with time zone)
        GROUP BY t.ledgerno_id, t.amount_currency
    )
    SELECT l.id AS ledgerno_id,
        l.name,
        at."AccountType",
        ls.created AS ls_created,
        ls."ClosingBalance" AS opening_balance,
    
        -- Credit (Cr) Calculation: Sum of credits since last statement
        ARRAY_AGG(ROW(
            COALESCE(tsl.total_credit, 0::numeric)::numeric(14,3),
            tsl.amount_currency
        )::money_value) AS cr,
    
        -- Debit (Dr) Calculation: Sum of debits since last statement
        ARRAY_AGG(ROW(
            COALESCE(tsl.total_debit, 0::numeric)::numeric(14,3),
            tsl.amount_currency
        )::money_value) AS dr,
    
        -- Closing Balance Calculation: Adjust based on ledger type
        ARRAY_AGG(ROW(
            CASE
                WHEN at."AccountType" IN ('Asset', 'Expense') THEN
                    COALESCE(ucb.amount, 0::numeric) + COALESCE(tsl.total_debit - tsl.total_credit, 0::numeric)::numeric(14,3)
                ELSE
                    COALESCE(ucb.amount, 0::numeric) + COALESCE(tsl.total_credit - tsl.total_debit, 0::numeric)::numeric(14,3)
            END,
            ucb.currency
        )::money_value) AS closing_balance
    
    FROM dea_ledger l
    LEFT JOIN ls ON l.id = ls.ledgerno_id
    LEFT JOIN unnested_closing_balance ucb ON l.id = ucb.ledgerno_id
    LEFT JOIN transactions_since_latest tsl ON ucb.ledgerno_id = tsl.ledgerno_id AND ucb.currency = tsl.amount_currency
    LEFT JOIN dea_accounttype at ON l."AccountType_id" = at.id
    GROUP BY l.id, l.name, at."AccountType", ls.created, ls."ClosingBalance";
    """
    ledger_balance_sql_v7 = """
        CREATE VIEW current_ledger_balance AS
        WITH acc_st AS (
            SELECT DISTINCT ON (dea_accountstatement."AccountNo_id")
                dea_accountstatement.id,
                dea_accountstatement.created,
                dea_accountstatement."ClosingBalance",
                dea_accountstatement."AccountNo_id"
            FROM dea_accountstatement
            ORDER BY dea_accountstatement."AccountNo_id", dea_accountstatement.created DESC
        ),
        unnested_closing_balance AS (
            SELECT s."AccountNo_id",
                (unnest(s."ClosingBalance")).amount AS amount,
                (unnest(s."ClosingBalance")).currency AS currency
            FROM acc_st s
        ),
        ledger_transactions AS (
            SELECT
                t."ledgerno_id" AS ledger_id,
                t.amount_currency,
                SUM(CASE WHEN t."ledgerno_dr_id" IS NOT NULL THEN t.amount ELSE 0 END) AS total_debit,
                SUM(CASE WHEN t."ledgerno_id" IS NOT NULL THEN t.amount ELSE 0 END) AS total_credit
            FROM ledgertransaction t
            LEFT JOIN acc_st s ON t."ledgerno_id" = s."AccountNo_id"
            WHERE t.created > COALESCE(s.created, '1970-01-01 00:00:00+05:30'::timestamp with time zone)
            GROUP BY t."ledgerno_id", t.amount_currency
        ),
        account_transactions AS (
            SELECT
                t."Account_id" AS ledger_id,
                t.amount_currency,
                SUM(CASE WHEN t."XactTypeCode_id" = 'Dr' THEN t.amount ELSE 0 END) AS total_debit,
                SUM(CASE WHEN t."XactTypeCode_id" = 'Cr' THEN t.amount ELSE 0 END) AS total_credit
            FROM dea_accounttransaction t
            LEFT JOIN acc_st s ON t."Account_id" = s."AccountNo_id"
            WHERE t.created > COALESCE(s.created, '1970-01-01 00:00:00+05:30'::timestamp with time zone)
            GROUP BY t."Account_id", t.amount_currency
        ),
        combined_transactions AS (
            SELECT
                ledger_id,
                amount_currency,
                SUM(total_debit) AS total_debit,
                SUM(total_credit) AS total_credit
            FROM (
                SELECT * FROM ledger_transactions
                UNION ALL
                SELECT * FROM account_transactions
            ) combined
            GROUP BY ledger_id, amount_currency
        )
        SELECT
            a.id AS "AccountNo_id",
            a.contact_id,
            acc_st.created AS ls_created,
            acc_st."ClosingBalance" AS opening_balance,
            ARRAY_AGG(ROW(
                COALESCE(ct.total_credit, 0::numeric)::numeric(14,3),
                ct.amount_currency
            )::money_value) AS cr,
            ARRAY_AGG(ROW(
                COALESCE(ct.total_debit, 0::numeric)::numeric(14,3),
                ct.amount_currency
            )::money_value) AS dr,
            ARRAY_AGG(ROW(
                COALESCE(ucb.amount, 0::numeric) +
                    COALESCE(ct.total_credit, 0::numeric) -
                    COALESCE(ct.total_debit, 0::numeric)::numeric(14,3),
                ucb.currency
            )::money_value) AS closing_balance
        FROM dea_account a
        LEFT JOIN acc_st ON a.id = acc_st."AccountNo_id"
        LEFT JOIN unnested_closing_balance ucb ON a.id = ucb."AccountNo_id"
        LEFT JOIN combined_transactions ct ON ucb."AccountNo_id" = ct.ledger_id AND ucb.currency::text = ct.amount_currency::text
        GROUP BY a.id, a.contact_id, acc_st.created, acc_st."ClosingBalance";
        """
    ledger_balance_sql_v6_array_agg = """
        CREATE VIEW current_ledger_balance AS
        WITH latest_statements AS (
            SELECT DISTINCT ON (ledger_id)
                id,
                created,
                closing_balance,
                ledger_id
            FROM ledgerstatement
            ORDER BY ledger_id, created DESC
        ),
        unnested_closing_balance AS (
            SELECT
                s.ledger_id,
                (unnest(s.closing_balance)).*
            FROM
                latest_statements s
        ),
        transactions_since_latest AS (
            SELECT
                t.ledger_id,
                t.amount_currency,
                SUM(CASE WHEN t.xact_type = 'Dr' THEN t.amount ELSE 0 END) AS total_debit,
                SUM(CASE WHEN t.xact_type = 'Cr' THEN t.amount ELSE 0 END) AS total_credit
            FROM
                ledgertransaction t
            LEFT JOIN
                latest_statements s ON t.ledger_id = s.ledger_id
            WHERE
                t.created > COALESCE(s.created, '1970-01-01')
            GROUP BY
                t.ledger_id, t.amount_currency
        )
        SELECT
            l.id AS ledger_id,
            ARRAY_AGG(ROW(
                COALESCE(ucb.amount, 0) + 
                (COALESCE(tsl.total_debit, 0) - COALESCE(tsl.total_credit, 0)),
                ucb.currency
            )::money_value) AS current_balance
        FROM
            ledger l
        LEFT JOIN
            unnested_closing_balance ucb ON l.id = ucb.ledger_id
        LEFT JOIN
            transactions_since_latest tsl ON ucb.ledger_id = tsl.ledger_id AND ucb.currency = tsl.amount_currency
        GROUP BY l.id;
    """
    ledger_balance_sql_v5 = """
        CREATE VIEW ledger_balance AS
        WITH ls AS (
            SELECT DISTINCT ON (dea_ledgerstatement.ledgerno_id) 
                dea_ledgerstatement.id,
                dea_ledgerstatement.created,
                dea_ledgerstatement."ClosingBalance",
                dea_ledgerstatement.ledgerno_id
            FROM dea_ledgerstatement
            ORDER BY dea_ledgerstatement.ledgerno_id, dea_ledgerstatement.created DESC
        ),unnested_closing_balance AS (
         SELECT s."AccountNo_id",
            (unnest(s."ClosingBalance")).amount AS amount,
            (unnest(s."ClosingBalance")).currency AS currency
           FROM ls s
        )
        SELECT dea_ledger.id AS ledgerno_id,
            ls.created AS ls_created,
            ls."ClosingBalance" AS opening_balance,
            SUM(dea_ledgertransaction.amount) FILTER (WHERE dea_ledgertransaction.ledgerno_id = dea_ledger.id)::numeric(14,0) AS cr,
            SUM(dea_ledgertransaction.amount) FILTER (WHERE dea_ledgertransaction.ledgerno_dr_id = dea_ledger.id)::numeric(14,0) AS dr,
            (ls."ClosingBalance" + SUM(dea_ledgertransaction.amount) FILTER (WHERE dea_ledgertransaction.ledgerno_id = dea_ledger.id) - SUM(dea_ledgertransaction.amount) FILTER (WHERE dea_ledgertransaction.ledgerno_dr_id = dea_ledger.id))::numeric(14,0) AS closing_balance
        FROM dea_ledger
        LEFT JOIN ls ON dea_ledger.id = ls.ledgerno_id
        LEFT JOIN dea_ledgertransaction ON dea_ledger.id = dea_ledgertransaction.ledgerno_id OR dea_ledger.id = dea_ledgertransaction.ledgerno_dr_id
        WHERE (ls.created IS NULL OR dea_ledgertransaction.created >= ls.created)
        GROUP BY dea_ledger.id, ls.created, ls."ClosingBalance";
        """
    ledger_balance_sql_v4_ob_cb = """
        need to unnest arrays then perform + - operations
        CREATE VIEW ledger_balance AS
        WITH ls AS (
            SELECT DISTINCT ON (dea_ledgerstatement.ledgerno_id) 
                dea_ledgerstatement.id,
                dea_ledgerstatement.created,
                dea_ledgerstatement."ClosingBalance",
                dea_ledgerstatement.ledgerno_id
            FROM dea_ledgerstatement
            ORDER BY dea_ledgerstatement.ledgerno_id, dea_ledgerstatement.created DESC
        )
        SELECT dea_ledger.id AS ledgerno_id,
            ls.created AS ls_created,
            ls."ClosingBalance" AS opening_balance,
            SUM(dea_ledgertransaction.amount) FILTER (WHERE dea_ledgertransaction.ledgerno_id = dea_ledger.id)::numeric(14,0) AS cr,
            SUM(dea_ledgertransaction.amount) FILTER (WHERE dea_ledgertransaction.ledgerno_dr_id = dea_ledger.id)::numeric(14,0) AS dr,
            (ls."ClosingBalance" + SUM(dea_ledgertransaction.amount) FILTER (WHERE dea_ledgertransaction.ledgerno_id = dea_ledger.id) - SUM(dea_ledgertransaction.amount) FILTER (WHERE dea_ledgertransaction.ledgerno_dr_id = dea_ledger.id))::numeric(14,0) AS closing_balance
        FROM dea_ledger
        LEFT JOIN ls ON dea_ledger.id = ls.ledgerno_id
        LEFT JOIN dea_ledgertransaction ON dea_ledger.id = dea_ledgertransaction.ledgerno_id OR dea_ledger.id = dea_ledgertransaction.ledgerno_dr_id
        WHERE (ls.created IS NULL OR dea_ledgertransaction.created >= ls.created)
        GROUP BY dea_ledger.id, ls.created, ls."ClosingBalance";
    """
    ledger_balance_sql_v3_with_filter = """
        CREATE VIEW ledger_balance AS
        WITH ls AS (
            SELECT DISTINCT ON (dea_ledgerstatement.ledgerno_id) 
                dea_ledgerstatement.id,
                dea_ledgerstatement.created,
                dea_ledgerstatement."ClosingBalance",
                dea_ledgerstatement.ledgerno_id
            FROM dea_ledgerstatement
            ORDER BY dea_ledgerstatement.ledgerno_id, dea_ledgerstatement.created DESC
        )
        SELECT dea_ledger.id AS ledgerno_id,
            ls.created AS ls_created,
            ls."ClosingBalance" AS opening_balance,
            ARRAY(
                SELECT ROW(
                    SUM(dea_ledgertransaction.amount) FILTER (WHERE dea_ledgertransaction.ledgerno_id = dea_ledger.id)::numeric(14,0),
                    dea_ledgertransaction.amount_currency
                )::money_value AS "row"
                FROM dea_ledgertransaction
                WHERE (ls.created IS NULL OR dea_ledgertransaction.created >= ls.created)
                GROUP BY dea_ledgertransaction.amount_currency
            ) AS cr,
            ARRAY(
                SELECT ROW(
                    SUM(dea_ledgertransaction.amount) FILTER (WHERE dea_ledgertransaction.ledgerno_dr_id = dea_ledger.id)::numeric(14,0),
                    dea_ledgertransaction.amount_currency
                )::money_value AS "row"
                FROM dea_ledgertransaction
                WHERE (ls.created IS NULL OR dea_ledgertransaction.created >= ls.created)
                GROUP BY dea_ledgertransaction.amount_currency
            ) AS dr,
            ARRAY(
                SELECT ROW(
                    (SUM(dea_ledgertransaction.amount) FILTER (WHERE dea_ledgertransaction.ledgerno_id = dea_ledger.id) - SUM(dea_ledgertransaction.amount) FILTER (WHERE dea_ledgertransaction.ledgerno_dr_id = dea_ledger.id))::numeric(14,0),
                    dea_ledgertransaction.amount_currency
                )::money_value AS "row"
                FROM dea_ledgertransaction
                WHERE (ls.created IS NULL OR dea_ledgertransaction.created >= ls.created)
                GROUP BY dea_ledgertransaction.amount_currency
            ) AS closing_balance
        FROM dea_ledger
        LEFT JOIN ls ON dea_ledger.id = ls.ledgerno_id
        JOIN dea_accounttype at ON at.id = dea_ledger."AccountType_id";
    """
    ledger_balance_sql_v2 = """
        CREATE VIEW ledger_balance AS
        WITH ls AS (
        SELECT DISTINCT ON (dea_ledgerstatement.ledgerno_id) 
            dea_ledgerstatement.id,
            dea_ledgerstatement.created,
            dea_ledgerstatement."ClosingBalance",
            dea_ledgerstatement.ledgerno_id
           FROM dea_ledgerstatement
          ORDER BY dea_ledgerstatement.ledgerno_id, dea_ledgerstatement.created DESC
        )
        SELECT dea_ledger.id AS ledgerno_id,
            ls.created AS ls_created,
            ls."ClosingBalance" AS opening_balance,
            ARRAY( SELECT ROW(sum(dea_ledgertransaction.amount)::numeric(14,0), dea_ledgertransaction.amount_currency)::money_value AS "row"
                FROM dea_ledgertransaction
                WHERE dea_ledgertransaction.ledgerno_id = dea_ledger.id 
                AND (ls.created IS NULL OR dea_ledgertransaction.created >= ls.created)
                GROUP BY dea_ledgertransaction.amount_currency) AS cr,
            ARRAY( SELECT ROW(sum(dea_ledgertransaction.amount)::numeric(14,0), dea_ledgertransaction.amount_currency)::money_value AS "row"
                FROM dea_ledgertransaction
                WHERE dea_ledgertransaction.ledgerno_dr_id = dea_ledger.id AND (ls.created IS NULL OR dea_ledgertransaction.created >= ls.created)
                GROUP BY dea_ledgertransaction.amount_currency) AS dr
            ARRAY(SELECT ROW((sum(dea_ledgertransaction.amount) FILTER (WHERE dea_ledgertransaction.ledgerno_id = dea_ledger.id) - sum(dea_ledgertransaction.amount) FILTER (WHERE dea_ledgertransaction.ledgerno_dr_id = dea_ledger.id))::numeric(14,0), dea_ledgertransaction.amount_currency)::money_value AS "row"
                FROM dea_ledgertransaction
                WHERE (dea_ledgertransaction.ledgerno_id = dea_ledger.id OR dea_ledgertransaction.ledgerno_dr_id = dea_ledger.id) AND (ls.created IS NULL OR dea_ledgertransaction.created >= ls.created)
                GROUP BY dea_ledgertransaction.amount_currency) AS closing_balance 

        FROM dea_ledger
        LEFT JOIN ls ON dea_ledger.id = ls.ledgerno_id
        JOIN dea_accounttype at ON at.id = dea_ledger."AccountType_id";        
            """
    ledger_balance_sql_v1 = """
        CREATE VIEW ledger_balance AS
        WITH ls AS (
        SELECT DISTINCT ON (dea_ledgerstatement.ledgerno_id) 
            dea_ledgerstatement.id,
            dea_ledgerstatement.created,
            dea_ledgerstatement."ClosingBalance",
            dea_ledgerstatement.ledgerno_id
           FROM dea_ledgerstatement
          ORDER BY dea_ledgerstatement.ledgerno_id, dea_ledgerstatement.created DESC
        )
        SELECT dea_ledger.id AS ledgerno_id,
            dea_ledger.name,
            at."AccountType",
            ls.created,
            ls."ClosingBalance",
            ARRAY( SELECT ROW(sum(dea_ledgertransaction.amount)::numeric(14,0), dea_ledgertransaction.amount_currency)::money_value AS "row"
                FROM dea_ledgertransaction
                WHERE dea_ledgertransaction.ledgerno_id = dea_ledger.id 
                AND (ls.created IS NULL OR dea_ledgertransaction.created >= ls.created)
                GROUP BY dea_ledgertransaction.amount_currency) AS cr,
            ARRAY( SELECT ROW(sum(dea_ledgertransaction.amount)::numeric(14,0), 
            dea_ledgertransaction.amount_currency)::money_value AS "row"
                FROM dea_ledgertransaction
                WHERE dea_ledgertransaction.ledgerno_dr_id = dea_ledger.id AND (ls.created IS NULL OR dea_ledgertransaction.created >= ls.created)
                GROUP BY dea_ledgertransaction.amount_currency) AS dr
        FROM dea_ledger
        LEFT JOIN ls ON dea_ledger.id = ls.ledgerno_id
        JOIN dea_accounttype at ON at.id = dea_ledger."AccountType_id";        
            """
    ledger_balance_sql = """
         WITH ls AS (
         SELECT DISTINCT ON (dea_ledgerstatement.ledgerno_id) 
            dea_ledgerstatement.id,
            dea_ledgerstatement.created,
            dea_ledgerstatement."ClosingBalance",
            dea_ledgerstatement.ledgerno_id,
            dl.id,
            dl.name,
            dl.lft,
            dl.rght,
            dl.tree_id,
            dl.level,
            dl."AccountType_id",
            dl.parent_id
           FROM dea_ledgerstatement
             JOIN dea_ledger dl ON dl.id = dea_ledgerstatement.ledgerno_id
          ORDER BY dea_ledgerstatement.ledgerno_id, dea_ledgerstatement.created DESC
        )
        SELECT ls.ledgerno_id,
            ls.created,
            ls.name,
            at."AccountType",
            ls."ClosingBalance",
            ARRAY( SELECT ROW(sum(dea_ledgertransaction.amount)::numeric(14,0), dea_ledgertransaction.amount_currency)::money_value AS "row"
                FROM dea_ledgertransaction
                WHERE dea_ledgertransaction.ledgerno_id = ls.ledgerno_id AND dea_ledgertransaction.created >= ls.created
                GROUP BY dea_ledgertransaction.amount_currency) AS cr,
            ARRAY( SELECT ROW(sum(dea_ledgertransaction.amount)::numeric(14,0), dea_ledgertransaction.amount_currency)::money_value AS "row"
                FROM dea_ledgertransaction
                WHERE dea_ledgertransaction.ledgerno_dr_id = ls.ledgerno_id AND dea_ledgertransaction.created >= ls.created
                GROUP BY dea_ledgertransaction.amount_currency) AS dr
        FROM ls ls(id, created, "ClosingBalance", ledgerno_id, id_1, name, lft, rght, tree_id, level, "AccountType_id", parent_id)
            JOIN dea_accounttype at ON at.id = ls."AccountType_id";
    """
    ledger_balance_with_lt_and_at_sql = """
        WITH ls AS (
            SELECT DISTINCT ON (dea_ledgerstatement.ledgerno_id) dea_ledgerstatement.id,
                dea_ledgerstatement.created,
                dea_ledgerstatement."ClosingBalance",
                dea_ledgerstatement.ledgerno_id,
                dl.id,
                dl.name,
                dl.lft,
                dl.rght,
                dl.tree_id,
                dl.level,
                dl."AccountType_id",
                dl.parent_id
            FROM dea_ledgerstatement
                JOIN dea_ledger dl ON dl.id = dea_ledgerstatement.ledgerno_id
            ORDER BY dea_ledgerstatement.ledgerno_id, dea_ledgerstatement.created DESC
            )
        SELECT ls.ledgerno_id,
            ls.created,
            ls.name,
            at."AccountType",
            ls."ClosingBalance",
            ARRAY( SELECT ROW(sum(dea_ledgertransaction.amount)::numeric(14,0), dea_ledgertransaction.amount_currency)::money_value AS "row"
                FROM dea_ledgertransaction
                WHERE dea_ledgertransaction.ledgerno_id = ls.ledgerno_id AND dea_ledgertransaction.created >= ls.created
                GROUP BY dea_ledgertransaction.amount_currency) AS ll_cr,
            ARRAY( SELECT ROW(sum(dea_ledgertransaction.amount)::numeric(14,0), dea_ledgertransaction.amount_currency)::money_value AS "row"
                FROM dea_ledgertransaction
                WHERE dea_ledgertransaction.ledgerno_dr_id = ls.ledgerno_id AND dea_ledgertransaction.created >= ls.created
                GROUP BY dea_ledgertransaction.amount_currency) AS ll_dr,
            ARRAY( SELECT ROW(sum(dea_accounttransaction.amount)::numeric(14,0), dea_accounttransaction.amount_currency)::money_value AS "row"
                FROM dea_accounttransaction
                WHERE dea_accounttransaction.ledgerno_id = ls.ledgerno_id AND dea_accounttransaction."XactTypeCode_id"::text = 'Dr'::text 
                GROUP BY dea_accounttransaction.amount_currency) AS la_cr,
            ARRAY( SELECT ROW(sum(dea_accounttransaction.amount)::numeric(14,0), dea_accounttransaction.amount_currency)::money_value AS "row"
                FROM dea_accounttransaction
                WHERE dea_accounttransaction.ledgerno_id = ls.ledgerno_id AND dea_accounttransaction."XactTypeCode_id"::text = 'Cr'::text 
                GROUP BY dea_accounttransaction.amount_currency) AS la_dr
        FROM ls ls(id, created, "ClosingBalance", ledgerno_id, id_1, name, lft, rght, tree_id, level, "AccountType_id", parent_id)
            JOIN dea_accounttype at ON at.id = ls."AccountType_id";
    """
    account_balance_proper = """
        set search_path to 'testsplit','public';
WITH acc_st AS (
    SELECT DISTINCT ON (dea_accountstatement."AccountNo_id")
        dea_accountstatement.id,
        dea_accountstatement.created,
        dea_accountstatement."ClosingBalance",
        dea_accountstatement."AccountNo_id"
    FROM dea_accountstatement
    ORDER BY dea_accountstatement."AccountNo_id", dea_accountstatement.created DESC
), unnested_closing_balance AS (
    SELECT s."AccountNo_id",
        (unnest(s."ClosingBalance")).amount AS amount,
        (unnest(s."ClosingBalance")).currency AS currency
    FROM acc_st s
), transactions_since_latest AS (
    SELECT t."Account_id",
        t.amount_currency,
        SUM(CASE WHEN t."XactTypeCode_id" = 'Dr' THEN t.amount ELSE 0 END) AS total_debit,
        SUM(CASE WHEN t."XactTypeCode_id" = 'Cr' THEN t.amount ELSE 0 END) AS total_credit
    FROM dea_accounttransaction t
    LEFT JOIN acc_st s ON t."Account_id" = s."AccountNo_id"
    WHERE s."AccountNo_id" IS NULL OR t.created > COALESCE(s.created, '1970-01-01'::timestamp with time zone)
    GROUP BY t."Account_id", t.amount_currency
)

SELECT 
    a.id AS "AccountNo_id",
    a.contact_id,
    acc_st.created AS ls_created,
    acc_st."ClosingBalance" AS opening_balance,

    -- Credit (Cr) Calculation - No changes needed here
    ARRAY_AGG(DISTINCT ROW(
        COALESCE(tsl.total_credit, 0::numeric)::numeric(14,3),
        COALESCE(tsl.amount_currency, ucb.currency)
    )::money_value) FILTER (WHERE tsl.amount_currency IS NOT NULL) AS cr,

    -- Debit (Dr) Calculation - No changes needed here
    ARRAY_AGG(DISTINCT ROW(
        COALESCE(tsl.total_debit, 0::numeric)::numeric(14,3),
        COALESCE(tsl.amount_currency, ucb.currency)
    )::money_value) FILTER (WHERE tsl.amount_currency IS NOT NULL) AS dr,

    -- Closing Balance Calculation - Fixed currency handling
    ARRAY_AGG(DISTINCT ROW(
        CASE
            WHEN at."XactTypeCode_id" = 'Dr' THEN
                COALESCE(ucb.amount, 0::numeric) + 
                COALESCE(tsl.total_debit - tsl.total_credit, 0::numeric)::numeric(14,3)
            ELSE
                COALESCE(ucb.amount, 0::numeric) + 
                COALESCE(tsl.total_credit - tsl.total_debit, 0::numeric)::numeric(14,3)
        END,
        COALESCE(tsl.amount_currency, ucb.currency)
    )::money_value) FILTER (WHERE ucb.currency IS NOT NULL 
                           OR tsl.amount_currency IS NOT NULL) AS closing_balance

FROM dea_account a
LEFT JOIN acc_st ON a.id = acc_st."AccountNo_id"
LEFT JOIN unnested_closing_balance ucb ON a.id = ucb."AccountNo_id"
LEFT JOIN dea_accounttype_ext at ON a."AccountType_Ext_id" = at.id
LEFT JOIN transactions_since_latest tsl ON a.id = tsl."Account_id" 
    AND COALESCE(ucb.currency, tsl.amount_currency) = tsl.amount_currency

GROUP BY 
    a.id, 
    a.contact_id, 
    acc_st.created, 
    acc_st."ClosingBalance",
    at."XactTypeCode_id";
"""

    account_balance_fucking = """

WITH acc_st AS (
    SELECT DISTINCT ON (dea_accountstatement."AccountNo_id")
        dea_accountstatement.id,
        dea_accountstatement.created,
        dea_accountstatement."ClosingBalance",
        dea_accountstatement."AccountNo_id"
    FROM dea_accountstatement
    ORDER BY dea_accountstatement."AccountNo_id", dea_accountstatement.created DESC
), unnested_closing_balance AS (
    SELECT s."AccountNo_id",
        (unnest(s."ClosingBalance")).amount AS amount,
        (unnest(s."ClosingBalance")).currency AS currency
    FROM acc_st s
), transactions_since_latest AS (
    SELECT t."Account_id",
        t.amount_currency,
        SUM(CASE WHEN t."XactTypeCode_id" = 'Dr' THEN t.amount ELSE 0 END) AS total_debit,
        SUM(CASE WHEN t."XactTypeCode_id" = 'Cr' THEN t.amount ELSE 0 END) AS total_credit
    FROM dea_accounttransaction t
    LEFT JOIN acc_st s ON t."Account_id" = s."AccountNo_id"
    WHERE s."AccountNo_id" IS NULL OR t.created > COALESCE(s.created, '1970-01-01'::timestamp with time zone)
    GROUP BY t."Account_id", t.amount_currency
)
SELECT a.id AS "AccountNo_id",
    a.contact_id,
    acc_st.created AS ls_created,
    acc_st."ClosingBalance" AS opening_balance,

    -- Credit (Cr) Calculation: Sum of credits since last statement
    ARRAY_AGG(ROW(
        COALESCE(tsl.total_credit, 0::numeric)::numeric(14,3),
        tsl.amount_currency
    )::public.money_value) AS cr,

	-- debit (dr) Calculation: Sum of credits since last statement
    ARRAY_AGG(ROW(
        COALESCE(tsl.total_debit, 0::numeric)::numeric(14,3),
        tsl.amount_currency
    )::public.money_value) AS dr,

	-- Closing Balance Calculation: Add previous closing balance and net transactions (debit - credit)
	ARRAY_AGG(ROW(
		CASE
			WHEN at."XactTypeCode_id" = 'Dr' THEN
				COALESCE(ucb.amount, 0::numeric) + COALESCE(tsl.total_debit - tsl.total_credit, 0::numeric)::numeric(14,3)
			ELSE
				COALESCE(ucb.amount, 0::numeric) + COALESCE(tsl.total_credit - tsl.total_debit, 0::numeric)::numeric(14,3)
		END,
		ucb.currency
	)::money_value) AS closing_balance


FROM dea_account a
LEFT JOIN acc_st ON a.id = acc_st."AccountNo_id"
LEFT JOIN unnested_closing_balance ucb ON ucb."AccountNo_id" = a.id
LEFT JOIN dea_accounttype_ext at ON a."AccountType_Ext_id" = at.id
LEFT JOIN transactions_since_latest tsl ON a.id = tsl."Account_id"
GROUP BY a.id, a.contact_id, acc_st.created, acc_st."ClosingBalance";
    """
    account_balance_final_sql = """
    CREATE VIEW account_balance AS
    WITH acc_st AS (
        SELECT DISTINCT ON (dea_accountstatement."AccountNo_id")
            dea_accountstatement.id,
            dea_accountstatement.created,
            dea_accountstatement."ClosingBalance",
            dea_accountstatement."AccountNo_id"
        FROM dea_accountstatement
        ORDER BY dea_accountstatement."AccountNo_id", dea_accountstatement.created DESC
    ), unnested_closing_balance AS (
        SELECT s."AccountNo_id",
            (unnest(s."ClosingBalance")).amount AS amount,
            (unnest(s."ClosingBalance")).currency AS currency
        FROM acc_st s
    ), transactions_since_latest AS (
        SELECT t."Account_id",
            t.amount_currency,
            SUM(CASE WHEN t."XactTypeCode" = 'Dr' THEN t.amount ELSE 0 END) AS total_debit,
            SUM(CASE WHEN t."XactTypeCode" = 'Cr' THEN t.amount ELSE 0 END) AS total_credit
        FROM dea_accounttransaction t
        LEFT JOIN acc_st s ON t."Account_id" = s."AccountNo_id"
        WHERE t.created is null or t.created > COALESCE(s.created, '1970-01-01'::timestamp with time zone)
        GROUP BY t."Account_id", t.amount_currency
    )
    SELECT a.id AS "AccountNo_id",
        a.contact_id,
        acc_st.created AS ls_created,
        acc_st."ClosingBalance" AS opening_balance,

        -- Credit (Cr) Calculation: Sum of credits since last statement
        ARRAY_AGG(ROW(
            COALESCE(tsl.total_credit, 0::numeric)::numeric(14,3),
            tsl.amount_currency
        )::money_value) AS cr,

        -- Debit (Dr) Calculation: Sum of debits since last statement
        ARRAY_AGG(ROW(
            COALESCE(tsl.total_debit, 0::numeric)::numeric(14,3),
            tsl.amount_currency
        )::money_value) AS dr,

        -- Closing Balance Calculation: Add previous closing balance and net transactions (debit - credit)
        ARRAY_AGG(ROW(
            CASE
                WHEN at."XactTypeCode" = 'Dr' THEN
                    COALESCE(ucb.amount, 0::numeric) + COALESCE(tsl.total_debit - tsl.total_credit, 0::numeric)::numeric(14,3)
                ELSE
                    COALESCE(ucb.amount, 0::numeric) + COALESCE(tsl.total_credit - tsl.total_debit, 0::numeric)::numeric(14,3)
            END,
            ucb.currency
        )::money_value) AS closing_balance

    FROM dea_account a
    LEFT JOIN acc_st ON a.id = acc_st."AccountNo_id"
    LEFT JOIN unnested_closing_balance ucb ON ucb."AccountNo_id" = a.id
    LEFT JOIN transactions_since_latest tsl ON ucb."AccountNo_id" = tsl."Account_id" AND ucb.currency = tsl.amount_currency
    LEFT JOIN dea_accounttype_ext at ON a."AccountType_Ext_id" = at.id
    GROUP BY a.id, a.contact_id, acc_st.created, acc_st."ClosingBalance", at."XactTypeCode";
    """
    account_balance_sql_v7 = """
        WITH acc_st AS (
            SELECT DISTINCT ON (dea_accountstatement."AccountNo_id")
                dea_accountstatement.id,
                dea_accountstatement.created,
                dea_accountstatement."ClosingBalance",
                dea_accountstatement."AccountNo_id"
            FROM dea_accountstatement
            ORDER BY dea_accountstatement."AccountNo_id", dea_accountstatement.created DESC
        ), unnested_closing_balance AS (
            SELECT s."AccountNo_id",
                (unnest(s."ClosingBalance")).amount AS amount,
                (unnest(s."ClosingBalance")).currency AS currency
            FROM acc_st s
        ), transactions_since_latest AS (
            SELECT t."Account_id",
                t.amount_currency,
                SUM(CASE WHEN t."XactTypeCode_id" = 'Dr' THEN t.amount ELSE 0 END) AS total_debit,
                SUM(CASE WHEN t."XactTypeCode_id" = 'Cr' THEN t.amount ELSE 0 END) AS total_credit
            FROM dea_accounttransaction t
            LEFT JOIN acc_st s ON t."Account_id" = s."AccountNo_id"
            WHERE t.created > COALESCE(s.created, '1970-01-01'::timestamp with time zone)
            GROUP BY t."Account_id", t.amount_currency
        )
        SELECT a.id AS "AccountNo_id",
            a.contact_id,
            acc_st.created AS ls_created,
            acc_st."ClosingBalance" AS opening_balance,

            -- Credit (Cr) Calculation: Sum of credits since last statement
            ARRAY_AGG(ROW(
                COALESCE(tsl.total_credit, 0::numeric)::numeric(14,3),
                tsl.amount_currency
            )::money_value) AS cr,

            -- Debit (Dr) Calculation: Sum of debits since last statement
            ARRAY_AGG(ROW(
                COALESCE(tsl.total_debit, 0::numeric)::numeric(14,3),
                tsl.amount_currency
            )::money_value) AS dr,

            -- Closing Balance Calculation: Add previous closing balance and net transactions (debit - credit)
            ARRAY_AGG(ROW(
                COALESCE(ucb.amount, 0::numeric) + 
                COALESCE(tsl.total_debit - tsl.total_credit, 0::numeric)::numeric(14,3),
                ucb.currency
            )::money_value) AS closing_balance

        FROM dea_account a
        LEFT JOIN acc_st ON a.id = acc_st."AccountNo_id"
        LEFT JOIN unnested_closing_balance ucb ON ucb."AccountNo_id" = a.id
        LEFT JOIN transactions_since_latest tsl ON ucb."AccountNo_id" = tsl."Account_id" AND ucb.currency = tsl.amount_currency
        GROUP BY a.id, a.contact_id, acc_st.created, acc_st."ClosingBalance";
    """
    account_balance_sql_v6_arrayagg = """
        WITH acc_st AS (
        SELECT DISTINCT ON (dea_accountstatement."AccountNo_id")
            dea_accountstatement.id,
            dea_accountstatement.created,
            dea_accountstatement."ClosingBalance",
            dea_accountstatement."AccountNo_id"
        FROM dea_accountstatement
        ORDER BY dea_accountstatement."AccountNo_id", dea_accountstatement.created DESC
        ), unnested_closing_balance AS (
            SELECT s."AccountNo_id",
                (unnest(s."ClosingBalance")).amount AS amount,
                (unnest(s."ClosingBalance")).currency AS currency
            FROM acc_st s
        ), transactions_since_latest AS (
            SELECT t."Account_id",
                t.amount_currency,
                SUM(t.amount) FILTER (WHERE t."XactTypeCode_id" = 'Dr') AS total_debit,
                SUM(t.amount) FILTER (WHERE t."XactTypeCode_id" = 'Cr') AS total_credit
            FROM dea_accounttransaction t
            LEFT JOIN acc_st s ON t."Account_id" = s."AccountNo_id"
            WHERE t.created > COALESCE(s.created, '1970-01-01 00:00:00+05:30'::timestamp with time zone)
            GROUP BY t."Account_id", t.amount_currency
        )
        SELECT a.id AS "AccountNo_id",
            a.contact_id,
            acc_st.created AS ls_created,
            acc_st."ClosingBalance" AS opening_balance,
            ARRAY_AGG(ROW(COALESCE(SUM(t.amount), 0::numeric)::numeric(14,3), t.amount_currency)::money_value) 
                FILTER (WHERE t."XactTypeCode_id" = 'Dr' AND (acc_st.created IS NULL OR t.created >= acc_st.created)) AS cr,
            ARRAY_AGG(ROW(COALESCE(SUM(t.amount), 0::numeric)::numeric(14,3), t.amount_currency)::money_value) 
                FILTER (WHERE t."XactTypeCode_id" = 'Cr' AND (acc_st.created IS NULL OR t.created >= acc_st.created)) AS dr,
            ARRAY_AGG(ROW(
                COALESCE(ucb.amount, 0::numeric) + COALESCE(tsl.total_debit - tsl.total_credit, 0::numeric)::numeric(14,3),
                ucb.currency
            )::money_value) AS closing_balance
        FROM dea_account a
        LEFT JOIN acc_st ON a.id = acc_st."AccountNo_id"
        LEFT JOIN dea_accounttransaction t ON a.id = t."Account_id"  -- Include dea_accounttransaction for cr and dr calculations
        LEFT JOIN unnested_closing_balance ucb ON a.id = ucb."AccountNo_id"
        LEFT JOIN transactions_since_latest tsl ON a.id = tsl."Account_id" AND ucb.currency = tsl.amount_currency  -- Join with transactions_since_latest (tsl)
        GROUP BY a.id, a.contact_id, acc_st.created, acc_st."ClosingBalance";
    """
    account_balance_final_filter = """
        WITH acc_st AS (
        SELECT DISTINCT ON (dea_accountstatement."AccountNo_id")
            dea_accountstatement.id,
            dea_accountstatement.created,
            dea_accountstatement."ClosingBalance",
            dea_accountstatement."AccountNo_id"
        FROM dea_accountstatement
        ORDER BY dea_accountstatement."AccountNo_id", dea_accountstatement.created DESC
        ), unnested_closing_balance AS (
            SELECT s."AccountNo_id",
                (unnest(s."ClosingBalance")).amount AS amount,
                (unnest(s."ClosingBalance")).currency AS currency
            FROM acc_st s
        ), transactions_since_latest AS (
            SELECT t."Account_id",
                t.amount_currency,
                SUM(t.amount) FILTER (WHERE t."XactTypeCode_id"::text = 'Dr') AS total_debit,
                SUM(t.amount) FILTER (WHERE t."XactTypeCode_id"::text = 'Cr') AS total_credit
            FROM dea_accounttransaction t
            LEFT JOIN acc_st s ON t."Account_id" = s."AccountNo_id"
            WHERE t.created > COALESCE(s.created, '1970-01-01 00:00:00+05:30'::timestamp with time zone)
            GROUP BY t."Account_id", t.amount_currency
        )
        SELECT a.id AS "AccountNo_id",
            a.contact_id,
            acc_st.created AS ls_created,
            acc_st."ClosingBalance" AS opening_balance,
            ARRAY(
                SELECT ROW(COALESCE(SUM(t.amount), 0::numeric)::numeric(14,3), t.amount_currency)::money_value AS "row"
                FROM dea_accounttransaction t
                WHERE t."Account_id" = a.id AND t."XactTypeCode_id"::text = 'Dr' AND (acc_st.created IS NULL OR t.created >= acc_st.created)
                GROUP BY t.amount_currency
            ) AS cr,
            ARRAY(
                SELECT ROW(COALESCE(SUM(t.amount), 0::numeric)::numeric(14,3), t.amount_currency)::money_value AS "row"
                FROM dea_accounttransaction t
                WHERE t."Account_id" = a.id AND t."XactTypeCode_id"::text = 'Cr' AND (acc_st.created IS NULL OR t.created >= acc_st.created)
                GROUP BY t.amount_currency
            ) AS dr,
            ARRAY(
                SELECT ROW(
                    COALESCE(ucb.amount, 0::numeric) +
                        COALESCE(SUM(tsl.total_debit - tsl.total_credit) FILTER (WHERE at."XactTypeCode_id"::text = 'Dr'), 0::numeric) +
                        COALESCE(SUM(tsl.total_credit - tsl.total_debit) FILTER (WHERE at."XactTypeCode_id"::text = 'Cr'), 0::numeric)::numeric(14,3),
                    ucb.currency
                )::money_value AS "row"
                FROM unnested_closing_balance ucb
                LEFT JOIN transactions_since_latest tsl ON ucb."AccountNo_id" = tsl."Account_id" AND ucb.currency::text = tsl.amount_currency::text
                WHERE ucb."AccountNo_id" = a.id
                GROUP BY ucb.currency, at."XactTypeCode_id", ucb.amount, tsl.total_debit, tsl.total_credit
            ) AS closing_balance
        FROM dea_account a
        LEFT JOIN acc_st ON a.id = acc_st."AccountNo_id"
        LEFT JOIN dea_accounttype_ext at ON a."AccountType_Ext_id" = at.id;
    """
    account_balance_final_WHEN_CASE = """
     WITH acc_st AS (
         SELECT DISTINCT ON (dea_accountstatement."AccountNo_id") dea_accountstatement.id,
            dea_accountstatement.created,
            dea_accountstatement."ClosingBalance",
            dea_accountstatement."AccountNo_id"
           FROM dea_accountstatement
          ORDER BY dea_accountstatement."AccountNo_id", dea_accountstatement.created DESC
        ), unnested_closing_balance AS (
         SELECT s."AccountNo_id",
            (unnest(s."ClosingBalance")).amount AS amount,
            (unnest(s."ClosingBalance")).currency AS currency
           FROM acc_st s
        ), transactions_since_latest AS (
         SELECT t."Account_id",
            t.amount_currency,
            sum(
                CASE
                    WHEN t."XactTypeCode_id"::text = 'Dr'::text THEN t.amount
                    ELSE 0::numeric
                END) AS total_debit,
            sum(
                CASE
                    WHEN t."XactTypeCode_id"::text = 'Cr'::text THEN t.amount
                    ELSE 0::numeric
                END) AS total_credit
           FROM dea_accounttransaction t
             LEFT JOIN acc_st s ON t."Account_id" = s."AccountNo_id"
          WHERE t.created > COALESCE(s.created, '1970-01-01 00:00:00+05:30'::timestamp with time zone)
          GROUP BY t."Account_id", t.amount_currency
        )
        SELECT a.id AS "AccountNo_id",
            a.contact_id,
            acc_st.created AS ls_created,
            acc_st."ClosingBalance" AS opening_balance,
            ARRAY( SELECT ROW(COALESCE(sum(t.amount), 0::numeric)::numeric(14,3), t.amount_currency)::money_value AS "row"
                FROM dea_accounttransaction t
                WHERE t."Account_id" = a.id AND t."XactTypeCode_id"::text = 'Dr'::text AND (acc_st.created IS NULL OR t.created >= acc_st.created)
                GROUP BY t.amount_currency) AS cr,
            ARRAY( SELECT ROW(COALESCE(sum(t.amount), 0::numeric)::numeric(14,3), t.amount_currency)::money_value AS "row"
                FROM dea_accounttransaction t
                WHERE t."Account_id" = a.id AND t."XactTypeCode_id"::text = 'Cr'::text AND (acc_st.created IS NULL OR t.created >= acc_st.created)
                GROUP BY t.amount_currency) AS dr,
            ARRAY( SELECT ROW(
                        CASE
                            WHEN at."XactTypeCode_id"::text = 'Dr'::text THEN COALESCE(ucb.amount, 0::numeric) + (COALESCE(tsl.total_debit, 0::numeric) - COALESCE(tsl.total_credit, 0::numeric))
                            ELSE COALESCE(ucb.amount, 0::numeric) + (COALESCE(tsl.total_credit, 0::numeric) - COALESCE(tsl.total_debit, 0::numeric))
                        END::numeric(14,3), ucb.currency)::money_value AS "row"
                FROM unnested_closing_balance ucb
                    LEFT JOIN transactions_since_latest tsl ON ucb."AccountNo_id" = tsl."Account_id" AND ucb.currency::text = tsl.amount_currency::text
                WHERE ucb."AccountNo_id" = a.id
                GROUP BY ucb.currency, at."XactTypeCode_id", ucb.amount, tsl.total_debit, tsl.total_credit) AS closing_balance
        FROM dea_account a
            LEFT JOIN acc_st ON a.id = acc_st."AccountNo_id"
            LEFT JOIN dea_accounttype_ext at ON a."AccountType_Ext_id" = at.id;
     """
    account_balance_sql_v5 = """
     WITH acc_st AS (
         SELECT DISTINCT ON (dea_accountstatement."AccountNo_id") dea_accountstatement.id,
            dea_accountstatement.created,
            dea_accountstatement."ClosingBalance",
            dea_accountstatement."AccountNo_id"
           FROM dea_accountstatement
          ORDER BY dea_accountstatement."AccountNo_id", dea_accountstatement.created DESC
        ), unnested_closing_balance AS (
         SELECT s."AccountNo_id",
            (unnest(s."ClosingBalance")).amount AS amount,
            (unnest(s."ClosingBalance")).currency AS currency
           FROM acc_st s
        ), transactions_since_latest AS (
         SELECT t."Account_id",
            t.amount_currency,
            sum(
                CASE
                    WHEN t."XactTypeCode_id"::text = 'Dr'::text THEN t.amount
                    ELSE 0::numeric
                END) AS total_debit,
            sum(
                CASE
                    WHEN t."XactTypeCode_id"::text = 'Cr'::text THEN t.amount
                    ELSE 0::numeric
                END) AS total_credit
           FROM dea_accounttransaction t
             LEFT JOIN acc_st s ON t."Account_id" = s."AccountNo_id"
          WHERE t.created > COALESCE(s.created, '1970-01-01 00:00:00+05:30'::timestamp with time zone)
          GROUP BY t."Account_id", t.amount_currency
        )
        SELECT a.id AS "AccountNo_id",
            a.contact_id,
            acc_st.created AS ls_created,
            acc_st."ClosingBalance" AS opening_balance,
            ARRAY( SELECT ROW(COALESCE(sum(t.amount), 0::numeric)::numeric(14,3), t.amount_currency)::money_value AS "row"
                FROM dea_accounttransaction t
                WHERE t."Account_id" = a.id AND t."XactTypeCode_id"::text = 'Dr'::text AND (acc_st.created IS NULL OR t.created >= acc_st.created)
                GROUP BY t.amount_currency) AS cr,
            ARRAY( SELECT ROW(COALESCE(sum(t.amount), 0::numeric)::numeric(14,3), t.amount_currency)::money_value AS "row"
                FROM dea_accounttransaction t
                WHERE t."Account_id" = a.id AND t."XactTypeCode_id"::text = 'Cr'::text AND (acc_st.created IS NULL OR t.created >= acc_st.created)
                GROUP BY t.amount_currency) AS dr,
            ARRAY( SELECT ROW(
                        CASE
                            WHEN at."XactTypeCode_id"::text = 'Dr'::text THEN COALESCE(ucb.amount, 0::numeric) + (COALESCE(tsl.total_debit, 0::numeric) - COALESCE(tsl.total_credit, 0::numeric))
                            ELSE COALESCE(ucb.amount, 0::numeric) + (COALESCE(tsl.total_credit, 0::numeric) - COALESCE(tsl.total_debit, 0::numeric))
                        END::numeric(14,3), ucb.currency)::money_value AS "row"
                FROM unnested_closing_balance ucb
                    LEFT JOIN transactions_since_latest tsl ON ucb."AccountNo_id" = tsl."Account_id" AND ucb.currency::text = tsl.amount_currency::text
                WHERE ucb."AccountNo_id" = a.id
                GROUP BY ucb.currency, at."XactTypeCode_id", ucb.amount, tsl.total_debit, tsl.total_credit) AS closing_balance
                FROM dea_account a
            LEFT JOIN acc_st ON a.id = acc_st."AccountNo_id"
            LEFT JOIN dea_accounttype_ext at ON a."AccountType_Ext_id" = at.id;
     """
    account_balance_sql_v4 = """
        WITH acc_st AS (
        SELECT DISTINCT ON (dea_accountstatement."AccountNo_id") dea_accountstatement.id,
            dea_accountstatement.created,
            dea_accountstatement."ClosingBalance",
            dea_accountstatement."AccountNo_id"
        FROM dea_accountstatement
        ORDER BY dea_accountstatement."AccountNo_id", dea_accountstatement.created DESC
        )
        SELECT dea_account.id AS "AccountNo_id",
            dea_account.contact_id,
            acc_st.created AS ls_created,
            acc_st."ClosingBalance" AS opening_balance,
            ARRAY(SELECT ROW(COALESCE(SUM(dea_accounttransaction.amount), 0::numeric)::numeric(14,3), dea_accounttransaction.amount_currency)::money_value AS "row"
                FROM dea_accounttransaction
                WHERE dea_accounttransaction."Account_id" = dea_account.id AND dea_accounttransaction."XactTypeCode_id"::text = 'Dr'::text AND (acc_st.created IS NULL OR dea_accounttransaction.created >= acc_st.created)
                GROUP BY dea_accounttransaction.amount_currency) AS cr,
            ARRAY(SELECT ROW(COALESCE(SUM(dea_accounttransaction.amount), 0::numeric)::numeric(14,3), dea_accounttransaction.amount_currency)::money_value AS "row"
                FROM dea_accounttransaction
                WHERE dea_accounttransaction."Account_id" = dea_account.id AND dea_accounttransaction."XactTypeCode_id"::text = 'Cr'::text AND (acc_st.created IS NULL OR dea_accounttransaction.created >= acc_st.created)
                GROUP BY dea_accounttransaction.amount_currency) AS dr,
            ARRAY(SELECT ROW(
                    CASE
                        WHEN at."XactTypeCode" = 'Dr' THEN
                            COALESCE(acc_st."ClosingBalance"->>'amount'::numeric, 0) + (COALESCE(SUM(dea_accounttransaction.amount) FILTER (WHERE dea_accounttransaction."XactTypeCode_id"::text = 'Dr'::text), 0::numeric) - COALESCE(SUM(dea_accounttransaction.amount) FILTER (WHERE dea_accounttransaction."XactTypeCode_id"::text = 'Cr'::text), 0::numeric))
                        ELSE
                            COALESCE(acc_st."ClosingBalance"->>'amount'::numeric, 0) + (COALESCE(SUM(dea_accounttransaction.amount) FILTER (WHERE dea_accounttransaction."XactTypeCode_id"::text = 'Cr'::text), 0::numeric) - COALESCE(SUM(dea_accounttransaction.amount) FILTER (WHERE dea_accounttransaction."XactTypeCode_id"::text = 'Dr'::text), 0::numeric))
                    END::numeric(14,3),
                    dea_accounttransaction.amount_currency)::money_value AS "row"
                FROM dea_accounttransaction
                WHERE dea_accounttransaction."Account_id" = dea_account.id AND (acc_st.created IS NULL OR dea_accounttransaction.created >= acc_st.created)
                GROUP BY dea_accounttransaction.amount_currency) AS closing_balance
        FROM dea_account
        LEFT JOIN acc_st ON dea_account.id = acc_st."AccountNo_id"
        LEFT JOIN "AccountType_Ext" at ON dea_account."AccountType_Ext_id" = at.id;
    """
    account_balance_sql_v3 = """
        doesnt work dont bother.need to unnest arrays and perform + - operations
        CREATE VIEW account_balance AS
        WITH acc_st AS (
            SELECT DISTINCT ON (dea_accountstatement."AccountNo_id") 
                dea_accountstatement.id,
                dea_accountstatement.created,
                dea_accountstatement."ClosingBalance",
                dea_accountstatement."AccountNo_id"
            FROM dea_accountstatement
            ORDER BY dea_accountstatement."AccountNo_id", dea_accountstatement.created DESC
        )
        SELECT dea_account.id AS "AccountNo_id",
            dea_account.contact_id AS contact_id,
            acc_st.created AS ls_created,
            acc_st."ClosingBalance" AS opening_balance,
            SUM(dea_accounttransaction.amount) FILTER (WHERE dea_accounttransaction."XactTypeCode_id"::text = 'Dr'::text)::numeric(14,0) AS cr,
            SUM(dea_accounttransaction.amount) FILTER (WHERE dea_accounttransaction."XactTypeCode_id"::text = 'Cr'::text)::numeric(14,0) AS dr,
            (acc_st."ClosingBalance" + SUM(dea_accounttransaction.amount) FILTER (WHERE dea_accounttransaction."XactTypeCode_id"::text = 'Dr'::text) - SUM(dea_accounttransaction.amount) FILTER (WHERE dea_accounttransaction."XactTypeCode_id"::text = 'Cr'::text))::numeric(14,0) AS closing_balance
        FROM dea_account
        LEFT JOIN acc_st ON dea_account.id = acc_st."AccountNo_id"
        LEFT JOIN dea_accounttransaction ON dea_account.id = dea_accounttransaction."Account_id"
        WHERE (acc_st.created IS NULL OR dea_accounttransaction.created >= acc_st.created)
        GROUP BY dea_account.id, dea_account.contact_id, acc_st.created, acc_st."ClosingBalance";
    """
    account_balance_sql_v2 = """
        CREATE VIEW account_balance AS
        WITH acc_st AS (
            SELECT DISTINCT ON (dea_accountstatement."AccountNo_id") 
                dea_accountstatement.id,
                dea_accountstatement.created,
                dea_accountstatement."ClosingBalance",
                dea_accountstatement."AccountNo_id"
            FROM dea_accountstatement
            ORDER BY dea_accountstatement."AccountNo_id", dea_accountstatement.created DESC
            )
        SELECT dea_account.id AS "AccountNo_id",
            dea_account.contact_id AS contact_id,
            acc_st.created AS ls_created,
            acc_st."ClosingBalance" AS opening_balance,
            ARRAY( SELECT ROW(sum(dea_accounttransaction.amount)::numeric(14,0), dea_accounttransaction.amount_currency)::money_value AS "row"
                FROM dea_accounttransaction
                WHERE dea_accounttransaction."Account_id" = dea_account.id 
                AND dea_accounttransaction."XactTypeCode_id"::text = 'Dr'::text 
                AND ((acc_st.created isnull) or dea_accounttransaction.created >= acc_st.created)
                GROUP BY dea_accounttransaction.amount_currency) AS cr,
            ARRAY( SELECT ROW(sum(dea_accounttransaction.amount)::numeric(14,0), dea_accounttransaction.amount_currency)::money_value AS "row"
                FROM dea_accounttransaction
                WHERE dea_accounttransaction."Account_id" = dea_account.id 
                AND dea_accounttransaction."XactTypeCode_id"::text = 'Cr'::text 
                AND ((acc_st.created isnull) or dea_accounttransaction.created >= acc_st.created)
                GROUP BY dea_accounttransaction.amount_currency) AS dr
            ARRAY( SELECT ROW(sum(dea_accounttransaction.amount) FILTER (WHERE dea_accounttransaction."XactTypeCode_id"::text = 'Dr'::text) - sum(dea_accounttransaction.amount) FILTER (WHERE dea_accounttransaction."XactTypeCode_id"::text = 'Cr'::text))::numeric(14,0), dea_accounttransaction.amount_currency)::money_value AS "row"
                FROM dea_accounttransaction
                WHERE dea_accounttransaction."Account_id" = dea_account.id
                AND ((acc_st.created IS NULL) or dea_accounttransaction.created >= acc_st.created)
                GROUP BY dea_accounttransaction.amount_currency) AS closing_balance
        FROM dea_account
            LEFT JOIN acc_st ON dea_account.id = acc_st."AccountNo_id"            
    """
    account_balance_sql_v1 = """
    CREATE VIEW account_balance AS
        WITH acc_st AS (
            SELECT DISTINCT ON (dea_accountstatement."AccountNo_id") 
                dea_accountstatement.id,
                dea_accountstatement.created,
                dea_accountstatement."ClosingBalance",
                dea_accountstatement."TotalCredit",
                dea_accountstatement."TotalDebit",
                dea_accountstatement."AccountNo_id"
            FROM dea_accountstatement
            ORDER BY dea_accountstatement."AccountNo_id", dea_accountstatement.created DESC
            )
        SELECT dea_account.id AS "AccountNo_id",
            ate.description,
            et.name AS entity,
            ct.name AS contact,
            acc_st.created,
            acc_st."ClosingBalance",
            acc_st."TotalCredit",
            acc_st."TotalDebit",
            ARRAY( SELECT ROW(sum(dea_accounttransaction.amount)::numeric(14,0), dea_accounttransaction.amount_currency)::money_value AS "row"
                FROM dea_accounttransaction
                WHERE dea_accounttransaction."Account_id" = dea_account.id 
                AND dea_accounttransaction."XactTypeCode_id"::text = 'Dr'::text 
                AND ((acc_st.created isnull) or dea_accounttransaction.created >= acc_st.created)
                GROUP BY dea_accounttransaction.amount_currency) AS cr,
            ARRAY( SELECT ROW(sum(dea_accounttransaction.amount)::numeric(14,0), dea_accounttransaction.amount_currency)::money_value AS "row"
                FROM dea_accounttransaction
                WHERE dea_accounttransaction."Account_id" = dea_account.id 
                AND dea_accounttransaction."XactTypeCode_id"::text = 'Cr'::text 
                AND ((acc_st.created isnull) or dea_accounttransaction.created >= acc_st.created)
                GROUP BY dea_accounttransaction.amount_currency) AS dr
        FROM dea_account
            LEFT JOIN acc_st ON dea_account.id = acc_st."AccountNo_id"
            JOIN dea_accounttype_ext ate ON ate.id = dea_account."AccountType_Ext_id"
            JOIN contact_customer ct ON ct.id = dea_account.contact_id
            JOIN dea_entitytype et ON et.id = dea_account.entity_id;
    """
    account_balance_sql = """
    
        WITH astmt AS
        (
         SELECT DISTINCT ON (dea_accountstatement."AccountNo_id") 
            et.name AS entity,
            acte.description AS acc_type,
            cu.name AS acc_name,
            dea_accountstatement.id,
            dea_accountstatement.created,
            dea_accountstatement."ClosingBalance",
            dea_accountstatement."TotalCredit",
            dea_accountstatement."TotalDebit",
            dea_accountstatement."AccountNo_id"
           FROM dea_accountstatement
             JOIN dea_account acc ON acc.id = dea_accountstatement."AccountNo_id"
             JOIN dea_accounttype_ext acte ON acte.id = acc."AccountType_Ext_id"
             JOIN dea_entitytype et ON et.id = acc.entity_id
             JOIN contact_customer cu ON cu.id = acc.contact_id
          ORDER BY dea_accountstatement."AccountNo_id", dea_accountstatement.created DESC
        )
        SELECT astmt.acc_name,
            astmt.entity,
            astmt.acc_type,
            astmt.id,
            astmt.created,
            astmt."ClosingBalance",
            astmt."TotalCredit",
            astmt."TotalDebit",
            astmt."AccountNo_id",
            ARRAY( SELECT ROW(sum(dea_accounttransaction.amount)::numeric(14,0), dea_accounttransaction.amount_currency)::money_value AS "row"
                FROM dea_accounttransaction
                WHERE dea_accounttransaction."Account_id" = astmt."AccountNo_id" 
                AND dea_accounttransaction."XactTypeCode_id"::text = 'Dr'::text 
                AND dea_accounttransaction.created >= astmt.created
                GROUP BY dea_accounttransaction.amount_currency) AS cr,
            ARRAY( SELECT ROW(sum(dea_accounttransaction.amount)::numeric(14,0), dea_accounttransaction.amount_currency)::money_value AS "row"
                FROM dea_accounttransaction
                WHERE dea_accounttransaction."Account_id" = astmt."AccountNo_id" 
                AND dea_accounttransaction."XactTypeCode_id"::text = 'Cr'::text 
                AND dea_accounttransaction.created >= astmt.created
                GROUP BY dea_accounttransaction.amount_currency) AS dr
        FROM astmt;
    """
    operations = [
        CreateView("ledger_balance", ledger_balance_fucking_v1),
        CreateView("account_balance", account_balance_fucking),
        # migrations.RunSQL(ledger_balance_sql_v1, reverse_sql=migrations.RunSQL.noop),
        # migrations.RunSQL(account_balance_sql_v1, reverse_sql=migrations.RunSQL.noop),
    ]
