# Generated by Django 6.0.3 on 2026-08-07 10:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingOrganization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_key', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('external_tenant_key', models.CharField(blank=True, max_length=128, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('organization_key',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_tenant_key__isnull', False)), fields=('external_tenant_key',), name='acct_org_external_tenant_uniq')],
            },
        ),
        migrations.CreateModel(
            name='AccountingBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('book_key', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('base_currency', models.CharField(max_length=3)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounting_books', to='standalone_accounting.accountingorganization')),
            ],
            options={
                'ordering': ('organization_id', 'book_key'),
            },
        ),
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_key', models.CharField(max_length=64)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ADJUSTMENT_ONLY', 'Adjustment Only'), ('CLOSED', 'Closed'), ('LOCKED', 'Locked')], db_index=True, default='OPEN', max_length=24)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='standalone_accounting.accountingbook')),
            ],
            options={
                'ordering': ('book_id', 'start_date', 'period_key'),
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ledger_key', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('reporting_class', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('REVENUE', 'Revenue'), ('EXPENSE', 'Expense'), ('GAIN', 'Gain'), ('LOSS', 'Loss')], max_length=16)),
                ('normal_side', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=8)),
                ('node_kind', models.CharField(choices=[('INTERMEDIATE', 'Intermediate'), ('POSTING', 'Posting')], max_length=16)),
                ('can_debit', models.BooleanField(default=True)),
                ('can_credit', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledgers', to='standalone_accounting.accountingbook')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='standalone_accounting.ledger')),
            ],
            options={
                'ordering': ('book_id', 'code', 'ledger_key'),
            },
        ),
        migrations.AddConstraint(
            model_name='accountingbook',
            constraint=models.UniqueConstraint(fields=('organization', 'book_key'), name='acct_book_org_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='accountingbook',
            constraint=models.CheckConstraint(condition=models.Q(('decimal_places__gte', 0), ('decimal_places__lte', 8)), name='acct_book_decimal_places_range'),
        ),
        migrations.AddConstraint(
            model_name='accountingperiod',
            constraint=models.UniqueConstraint(fields=('book', 'period_key'), name='acct_period_book_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='accountingperiod',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='acct_period_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='accountingperiod',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('closed_at__isnull', False), ('status', 'CLOSED')), models.Q(('status', 'CLOSED'), _negated=True), _connector='OR'), name='acct_period_closed_evidence'),
        ),
        migrations.AddConstraint(
            model_name='accountingperiod',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('locked_at__isnull', False), ('status', 'LOCKED')), models.Q(('status', 'LOCKED'), _negated=True), _connector='OR'), name='acct_period_locked_evidence'),
        ),
        migrations.AddConstraint(
            model_name='ledger',
            constraint=models.UniqueConstraint(fields=('book', 'ledger_key'), name='acct_ledger_book_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='ledger',
            constraint=models.UniqueConstraint(fields=('book', 'code'), name='acct_ledger_book_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='ledger',
            constraint=models.CheckConstraint(condition=models.Q(('id', models.F('parent_id')), _negated=True), name='acct_ledger_not_own_parent'),
        ),
        migrations.AddConstraint(
            model_name='ledger',
            constraint=models.CheckConstraint(condition=models.Q(('can_debit', True), ('can_credit', True), _connector='OR'), name='acct_ledger_has_allowed_side'),
        ),
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS btree_gist;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE standalone_accounting_accountingperiod
                ADD CONSTRAINT acct_period_no_overlap
                EXCLUDE USING GIST (
                    book_id WITH =,
                    daterange(start_date, end_date, '[]') WITH &&
                );
            """,
            reverse_sql="""
                ALTER TABLE standalone_accounting_accountingperiod
                DROP CONSTRAINT IF EXISTS acct_period_no_overlap;
            """,
        ),
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION standalone_accounting_validate_ledger_hierarchy()
                RETURNS trigger
                LANGUAGE plpgsql
                AS $$
                DECLARE
                    parent_book uuid;
                    parent_kind varchar(16);
                    cycle_exists boolean;
                BEGIN
                    IF NEW.parent_id IS NOT NULL THEN
                        IF NEW.parent_id = NEW.id THEN
                            RAISE EXCEPTION 'A ledger cannot be its own parent.';
                        END IF;

                        SELECT book_id, node_kind
                        INTO parent_book, parent_kind
                        FROM standalone_accounting_ledger
                        WHERE id = NEW.parent_id;

                        IF NOT FOUND THEN
                            RAISE EXCEPTION 'Parent ledger does not exist.';
                        END IF;
                        IF parent_book <> NEW.book_id THEN
                            RAISE EXCEPTION 'Parent ledger must belong to the same book.';
                        END IF;
                        IF parent_kind <> 'INTERMEDIATE' THEN
                            RAISE EXCEPTION 'Only an intermediate ledger may have children.';
                        END IF;

                        WITH RECURSIVE ancestors(id, parent_id) AS (
                            SELECT id, parent_id
                            FROM standalone_accounting_ledger
                            WHERE id = NEW.parent_id
                            UNION ALL
                            SELECT ledger.id, ledger.parent_id
                            FROM standalone_accounting_ledger ledger
                            JOIN ancestors ON ledger.id = ancestors.parent_id
                        )
                        SELECT EXISTS(
                            SELECT 1 FROM ancestors WHERE id = NEW.id
                        ) INTO cycle_exists;

                        IF cycle_exists THEN
                            RAISE EXCEPTION 'Ledger hierarchy must not contain a cycle.';
                        END IF;
                    END IF;

                    IF NEW.node_kind = 'POSTING' AND EXISTS(
                        SELECT 1
                        FROM standalone_accounting_ledger
                        WHERE parent_id = NEW.id AND id <> NEW.id
                    ) THEN
                        RAISE EXCEPTION 'A posting ledger cannot have children.';
                    END IF;

                    RETURN NEW;
                END;
                $$;

                CREATE TRIGGER standalone_accounting_ledger_hierarchy_guard
                BEFORE INSERT OR UPDATE OF parent_id, book_id, node_kind
                ON standalone_accounting_ledger
                FOR EACH ROW
                EXECUTE FUNCTION standalone_accounting_validate_ledger_hierarchy();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS standalone_accounting_ledger_hierarchy_guard
                ON standalone_accounting_ledger;
                DROP FUNCTION IF EXISTS standalone_accounting_validate_ledger_hierarchy();
            """,
        ),
    ]
