# Generated by Django 6.0.3 on 2026-08-07 10:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standalone_accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_key', models.CharField(max_length=128)),
                ('party_key', models.CharField(max_length=128)),
                ('purpose', models.CharField(choices=[('CUSTOMER_RECEIVABLE', 'Customer Receivable'), ('SUPPLIER_PAYABLE', 'Supplier Payable'), ('BORROWER_LOAN_RECEIVABLE', 'Borrower Loan Receivable'), ('LENDER_LOAN_PAYABLE', 'Lender Loan Payable'), ('CUSTOMER_ADVANCE', 'Customer Advance'), ('SUPPLIER_ADVANCE', 'Supplier Advance')], max_length=40)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_accounts', to='standalone_accounting.accountingbook')),
            ],
            options={
                'ordering': ('book_id', 'account_key'),
            },
        ),
        migrations.CreateModel(
            name='ExternalAccountClassification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_key', models.CharField(max_length=64)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('reporting_class', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('REVENUE', 'Revenue'), ('EXPENSE', 'Expense'), ('GAIN', 'Gain'), ('LOSS', 'Loss')], max_length=16)),
                ('normal_side', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('external_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classification_versions', to='standalone_accounting.externalaccount')),
                ('reporting_ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_account_classifications', to='standalone_accounting.ledger')),
            ],
            options={
                'ordering': ('external_account_id', 'effective_from', 'version_key'),
            },
        ),
        migrations.AddIndex(
            model_name='externalaccount',
            index=models.Index(fields=['book', 'party_key', 'purpose', 'is_active'], name='acct_ext_party_purpose_idx'),
        ),
        migrations.AddConstraint(
            model_name='externalaccount',
            constraint=models.UniqueConstraint(fields=('book', 'account_key'), name='acct_ext_account_book_key_uniq'),
        ),
        migrations.AddIndex(
            model_name='externalaccountclassification',
            index=models.Index(fields=['external_account', 'effective_from', 'effective_to'], name='acct_ext_class_dates_idx'),
        ),
        migrations.AddConstraint(
            model_name='externalaccountclassification',
            constraint=models.UniqueConstraint(fields=('external_account', 'version_key'), name='acct_ext_class_account_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='externalaccountclassification',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='acct_ext_class_dates_valid'),
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE standalone_accounting_externalaccountclassification
                ADD CONSTRAINT acct_ext_class_no_overlap
                EXCLUDE USING GIST (
                    external_account_id WITH =,
                    daterange(effective_from, effective_to, '[]') WITH &&
                );
            """,
            reverse_sql="""
                ALTER TABLE standalone_accounting_externalaccountclassification
                DROP CONSTRAINT IF EXISTS acct_ext_class_no_overlap;
            """,
        ),
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION standalone_accounting_validate_external_classification()
                RETURNS trigger
                LANGUAGE plpgsql
                AS $$
                DECLARE
                    account_book uuid;
                    ledger_book uuid;
                    ledger_class varchar(16);
                    ledger_side varchar(8);
                    ledger_kind varchar(16);
                BEGIN
                    SELECT book_id
                    INTO account_book
                    FROM standalone_accounting_externalaccount
                    WHERE id = NEW.external_account_id;

                    SELECT book_id, reporting_class, normal_side, node_kind
                    INTO ledger_book, ledger_class, ledger_side, ledger_kind
                    FROM standalone_accounting_ledger
                    WHERE id = NEW.reporting_ledger_id;

                    IF account_book <> ledger_book THEN
                        RAISE EXCEPTION 'Reporting ledger must belong to the external account book.';
                    END IF;
                    IF ledger_kind <> 'POSTING' THEN
                        RAISE EXCEPTION 'Reporting ledger must be a posting ledger.';
                    END IF;
                    IF NEW.reporting_class <> ledger_class THEN
                        RAISE EXCEPTION 'Reporting class must match the reporting ledger.';
                    END IF;
                    IF NEW.normal_side <> ledger_side THEN
                        RAISE EXCEPTION 'Normal side must match the reporting ledger.';
                    END IF;
                    RETURN NEW;
                END;
                $$;

                CREATE TRIGGER standalone_accounting_external_classification_guard
                BEFORE INSERT OR UPDATE
                ON standalone_accounting_externalaccountclassification
                FOR EACH ROW
                EXECUTE FUNCTION standalone_accounting_validate_external_classification();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS standalone_accounting_external_classification_guard
                ON standalone_accounting_externalaccountclassification;
                DROP FUNCTION IF EXISTS standalone_accounting_validate_external_classification();
            """,
        ),
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION standalone_accounting_protect_external_classification()
                RETURNS trigger
                LANGUAGE plpgsql
                AS $$
                BEGIN
                    IF TG_OP = 'DELETE' THEN
                        RAISE EXCEPTION 'External account classifications cannot be deleted.';
                    END IF;

                    IF NEW.external_account_id <> OLD.external_account_id
                       OR NEW.version_key <> OLD.version_key
                       OR NEW.effective_from <> OLD.effective_from
                       OR NEW.reporting_ledger_id <> OLD.reporting_ledger_id
                       OR NEW.reporting_class <> OLD.reporting_class
                       OR NEW.normal_side <> OLD.normal_side
                       OR NEW.created_at <> OLD.created_at
                       OR OLD.effective_to IS NOT NULL
                       OR NEW.effective_to IS NULL
                       OR NEW.effective_to < OLD.effective_from THEN
                        RAISE EXCEPTION 'External account classification is immutable except for one-time closure.';
                    END IF;
                    RETURN NEW;
                END;
                $$;

                CREATE TRIGGER standalone_accounting_external_classification_immutable
                BEFORE UPDATE OR DELETE
                ON standalone_accounting_externalaccountclassification
                FOR EACH ROW
                EXECUTE FUNCTION standalone_accounting_protect_external_classification();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS standalone_accounting_external_classification_immutable
                ON standalone_accounting_externalaccountclassification;
                DROP FUNCTION IF EXISTS standalone_accounting_protect_external_classification();
            """,
        ),
    ]
