# Generated by Django 6.0.3 on 2026-08-07 10:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standalone_accounting', '0002_externalaccount_externalaccountclassification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voucher_key', models.CharField(max_length=128)),
                ('voucher_number', models.CharField(blank=True, max_length=128)),
                ('effective_date', models.DateField(db_index=True)),
                ('purpose', models.CharField(choices=[('ORDINARY', 'Ordinary'), ('ADJUSTMENT', 'Adjustment')], default='ORDINARY', max_length=16)),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('AUTHORIZED', 'Authorized'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=16)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('source_system', models.CharField(max_length=64)),
                ('source_type', models.CharField(max_length=64)),
                ('source_id', models.CharField(max_length=128)),
                ('source_version', models.CharField(max_length=64)),
                ('rule_key', models.CharField(max_length=128)),
                ('rule_version', models.CharField(max_length=64)),
                ('fingerprint', models.CharField(blank=True, max_length=64, null=True)),
                ('authorized_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('narration', models.TextField(blank=True)),
                ('correction_group_key', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='standalone_accounting.accountingbook')),
            ],
            options={
                'ordering': ('book_id', 'effective_date', 'voucher_key'),
            },
        ),
        migrations.CreateModel(
            name='AccountingTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('discriminator', models.CharField(choices=[('LEDGER', 'Ledger To Ledger'), ('ACCOUNT', 'Ledger To External Account')], max_length=8)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=24)),
                ('currency', models.CharField(max_length=3)),
                ('base_amount', models.DecimalField(decimal_places=8, max_digits=24)),
                ('base_currency', models.CharField(max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=12, max_digits=24)),
                ('rate_source', models.CharField(max_length=128)),
                ('narration', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='standalone_accounting.voucher')),
            ],
            options={
                'ordering': ('voucher_id', 'sequence'),
            },
        ),
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='account_detail', serialize=False, to='standalone_accounting.accountingtransaction')),
                ('ledger_side', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=8)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draft_transactions', to='standalone_accounting.externalaccountclassification')),
                ('external_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draft_transactions', to='standalone_accounting.externalaccount')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draft_external_transactions', to='standalone_accounting.ledger')),
            ],
        ),
        migrations.CreateModel(
            name='LedgerTransaction',
            fields=[
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ledger_detail', serialize=False, to='standalone_accounting.accountingtransaction')),
                ('credit_ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draft_credit_transactions', to='standalone_accounting.ledger')),
                ('debit_ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draft_debit_transactions', to='standalone_accounting.ledger')),
            ],
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['book', 'source_system', 'source_type', 'source_id'], name='acct_voucher_source_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['book', 'state', 'effective_date'], name='acct_voucher_state_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.UniqueConstraint(fields=('book', 'voucher_key'), name='acct_voucher_book_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.UniqueConstraint(fields=('book', 'idempotency_key'), name='acct_voucher_book_idempotency_uniq'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('authorized_at__isnull', False), ('authorized_by_id__isnull', False), ('state', 'AUTHORIZED')), models.Q(('state', 'AUTHORIZED'), _negated=True), _connector='OR'), name='acct_voucher_authorized_evidence'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(('fingerprint__isnull', True)), name='acct_voucher_preposting_no_fingerprint'),
        ),
        migrations.AddConstraint(
            model_name='accountingtransaction',
            constraint=models.UniqueConstraint(fields=('voucher', 'sequence'), name='acct_tx_voucher_sequence_uniq'),
        ),
        migrations.AddConstraint(
            model_name='accountingtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gt', 0)), name='acct_tx_sequence_positive'),
        ),
        migrations.AddConstraint(
            model_name='accountingtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='acct_tx_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='accountingtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('base_amount__gt', 0)), name='acct_tx_base_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='accountingtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('exchange_rate__gt', 0)), name='acct_tx_exchange_rate_positive'),
        ),
        migrations.AddConstraint(
            model_name='ledgertransaction',
            constraint=models.CheckConstraint(condition=models.Q(('debit_ledger', models.F('credit_ledger')), _negated=True), name='acct_ledger_tx_distinct_ledgers'),
        ),
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION standalone_accounting_guard_voucher_draft()
                RETURNS trigger
                LANGUAGE plpgsql
                AS $$
                BEGIN
                    IF OLD.state <> 'DRAFT' THEN
                        RAISE EXCEPTION 'Authorized or cancelled vouchers are immutable.';
                    END IF;
                    IF TG_OP = 'DELETE' THEN
                        RETURN OLD;
                    END IF;
                    IF NEW.state NOT IN ('DRAFT', 'AUTHORIZED', 'CANCELLED') THEN
                        RAISE EXCEPTION 'Invalid pre-posting voucher transition.';
                    END IF;
                    RETURN NEW;
                END;
                $$;

                CREATE TRIGGER standalone_accounting_voucher_draft_guard
                BEFORE UPDATE OR DELETE
                ON standalone_accounting_voucher
                FOR EACH ROW
                EXECUTE FUNCTION standalone_accounting_guard_voucher_draft();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS standalone_accounting_voucher_draft_guard
                ON standalone_accounting_voucher;
                DROP FUNCTION IF EXISTS standalone_accounting_guard_voucher_draft();
            """,
        ),
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION standalone_accounting_validate_transaction_base()
                RETURNS trigger
                LANGUAGE plpgsql
                AS $$
                DECLARE
                    voucher_state varchar(16);
                    book_currency varchar(3);
                    book_places smallint;
                    target_voucher_id uuid;
                BEGIN
                    IF TG_OP = 'DELETE' THEN
                        target_voucher_id := OLD.voucher_id;
                    ELSE
                        target_voucher_id := NEW.voucher_id;
                    END IF;
                    SELECT voucher.state, book.base_currency, book.decimal_places
                    INTO voucher_state, book_currency, book_places
                    FROM standalone_accounting_voucher voucher
                    JOIN standalone_accounting_accountingbook book ON book.id = voucher.book_id
                    WHERE voucher.id = target_voucher_id;

                    IF voucher_state <> 'DRAFT' THEN
                        RAISE EXCEPTION 'Transactions may change only on a draft voucher.';
                    END IF;
                    IF TG_OP = 'DELETE' THEN
                        RETURN OLD;
                    END IF;
                    IF NEW.currency !~ '^[A-Z]{3}$' OR NEW.base_currency !~ '^[A-Z]{3}$' THEN
                        RAISE EXCEPTION 'Transaction currencies must be three uppercase letters.';
                    END IF;
                    IF NEW.base_currency <> book_currency THEN
                        RAISE EXCEPTION 'Transaction base currency must match the accounting book.';
                    END IF;
                    IF btrim(NEW.rate_source) = '' THEN
                        RAISE EXCEPTION 'Transaction rate source is required.';
                    END IF;
                    IF NEW.currency = NEW.base_currency
                       AND (NEW.exchange_rate <> 1 OR NEW.amount <> NEW.base_amount) THEN
                        RAISE EXCEPTION 'Same-currency transactions require rate 1 and equal amounts.';
                    END IF;
                    IF round(NEW.amount * NEW.exchange_rate, book_places) <> NEW.base_amount THEN
                        RAISE EXCEPTION 'Transaction base amount does not match its exchange rate.';
                    END IF;
                    RETURN NEW;
                END;
                $$;

                CREATE TRIGGER standalone_accounting_transaction_base_guard
                BEFORE INSERT OR UPDATE OR DELETE
                ON standalone_accounting_accountingtransaction
                FOR EACH ROW
                EXECUTE FUNCTION standalone_accounting_validate_transaction_base();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS standalone_accounting_transaction_base_guard
                ON standalone_accounting_accountingtransaction;
                DROP FUNCTION IF EXISTS standalone_accounting_validate_transaction_base();
            """,
        ),
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION standalone_accounting_validate_transaction_subtype()
                RETURNS trigger
                LANGUAGE plpgsql
                AS $$
                DECLARE
                    base_kind varchar(8);
                    voucher_book uuid;
                    voucher_date date;
                    voucher_state varchar(16);
                    debit_book uuid;
                    debit_kind varchar(16);
                    debit_allowed boolean;
                    credit_book uuid;
                    credit_kind varchar(16);
                    credit_allowed boolean;
                    internal_book uuid;
                    internal_kind varchar(16);
                    internal_debit boolean;
                    internal_credit boolean;
                    account_book uuid;
                    class_account uuid;
                    class_from date;
                    class_to date;
                    target_transaction_id uuid;
                BEGIN
                    IF TG_OP = 'DELETE' THEN
                        target_transaction_id := OLD.transaction_id;
                    ELSE
                        target_transaction_id := NEW.transaction_id;
                    END IF;
                    SELECT tx.discriminator, voucher.book_id, voucher.effective_date, voucher.state
                    INTO base_kind, voucher_book, voucher_date, voucher_state
                    FROM standalone_accounting_accountingtransaction tx
                    JOIN standalone_accounting_voucher voucher ON voucher.id = tx.voucher_id
                    WHERE tx.id = target_transaction_id;

                    IF voucher_state <> 'DRAFT' THEN
                        RAISE EXCEPTION 'Transaction subtypes may change only on a draft voucher.';
                    END IF;
                    IF TG_OP = 'DELETE' THEN
                        RETURN OLD;
                    END IF;

                    IF TG_TABLE_NAME = 'standalone_accounting_ledgertransaction' THEN
                        IF base_kind <> 'LEDGER' THEN
                            RAISE EXCEPTION 'Ledger subtype requires LEDGER discriminator.';
                        END IF;
                        SELECT book_id, node_kind, can_debit
                        INTO debit_book, debit_kind, debit_allowed
                        FROM standalone_accounting_ledger WHERE id = NEW.debit_ledger_id;
                        SELECT book_id, node_kind, can_credit
                        INTO credit_book, credit_kind, credit_allowed
                        FROM standalone_accounting_ledger WHERE id = NEW.credit_ledger_id;
                        IF debit_book <> voucher_book OR credit_book <> voucher_book THEN
                            RAISE EXCEPTION 'Transaction ledgers must belong to the voucher book.';
                        END IF;
                        IF debit_kind <> 'POSTING' OR credit_kind <> 'POSTING' THEN
                            RAISE EXCEPTION 'Transactions require posting ledgers.';
                        END IF;
                        IF NOT debit_allowed OR NOT credit_allowed THEN
                            RAISE EXCEPTION 'Ledger does not permit the requested transaction side.';
                        END IF;
                    ELSE
                        IF base_kind <> 'ACCOUNT' THEN
                            RAISE EXCEPTION 'Account subtype requires ACCOUNT discriminator.';
                        END IF;
                        SELECT book_id, node_kind, can_debit, can_credit
                        INTO internal_book, internal_kind, internal_debit, internal_credit
                        FROM standalone_accounting_ledger WHERE id = NEW.ledger_id;
                        SELECT book_id INTO account_book
                        FROM standalone_accounting_externalaccount WHERE id = NEW.external_account_id;
                        SELECT external_account_id, effective_from, effective_to
                        INTO class_account, class_from, class_to
                        FROM standalone_accounting_externalaccountclassification
                        WHERE id = NEW.classification_id;
                        IF internal_book <> voucher_book OR account_book <> voucher_book THEN
                            RAISE EXCEPTION 'Account transaction sides must belong to the voucher book.';
                        END IF;
                        IF internal_kind <> 'POSTING' THEN
                            RAISE EXCEPTION 'Account transaction requires a posting ledger.';
                        END IF;
                        IF (NEW.ledger_side = 'DEBIT' AND NOT internal_debit)
                           OR (NEW.ledger_side = 'CREDIT' AND NOT internal_credit) THEN
                            RAISE EXCEPTION 'Ledger does not permit the requested account transaction side.';
                        END IF;
                        IF class_account <> NEW.external_account_id THEN
                            RAISE EXCEPTION 'Classification must belong to the external account.';
                        END IF;
                        IF class_from > voucher_date OR (class_to IS NOT NULL AND class_to < voucher_date) THEN
                            RAISE EXCEPTION 'Classification must be effective on the voucher date.';
                        END IF;
                    END IF;
                    RETURN NEW;
                END;
                $$;

                CREATE TRIGGER standalone_accounting_ledger_transaction_guard
                BEFORE INSERT OR UPDATE OR DELETE
                ON standalone_accounting_ledgertransaction
                FOR EACH ROW
                EXECUTE FUNCTION standalone_accounting_validate_transaction_subtype();

                CREATE TRIGGER standalone_accounting_account_transaction_guard
                BEFORE INSERT OR UPDATE OR DELETE
                ON standalone_accounting_accounttransaction
                FOR EACH ROW
                EXECUTE FUNCTION standalone_accounting_validate_transaction_subtype();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS standalone_accounting_account_transaction_guard
                ON standalone_accounting_accounttransaction;
                DROP TRIGGER IF EXISTS standalone_accounting_ledger_transaction_guard
                ON standalone_accounting_ledgertransaction;
                DROP FUNCTION IF EXISTS standalone_accounting_validate_transaction_subtype();
            """,
        ),
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION standalone_accounting_validate_subtype_cardinality()
                RETURNS trigger
                LANGUAGE plpgsql
                AS $$
                DECLARE
                    tx_id uuid;
                    base_kind varchar(8);
                    ledger_count integer;
                    account_count integer;
                BEGIN
                    IF TG_TABLE_NAME = 'standalone_accounting_accountingtransaction' THEN
                        IF TG_OP = 'DELETE' THEN
                            tx_id := OLD.id;
                        ELSE
                            tx_id := NEW.id;
                        END IF;
                    ELSE
                        IF TG_OP = 'DELETE' THEN
                            tx_id := OLD.transaction_id;
                        ELSE
                            tx_id := NEW.transaction_id;
                        END IF;
                    END IF;
                    SELECT discriminator INTO base_kind
                    FROM standalone_accounting_accountingtransaction
                    WHERE id = tx_id;
                    IF NOT FOUND THEN
                        RETURN NULL;
                    END IF;
                    SELECT count(*) INTO ledger_count
                    FROM standalone_accounting_ledgertransaction WHERE transaction_id = tx_id;
                    SELECT count(*) INTO account_count
                    FROM standalone_accounting_accounttransaction WHERE transaction_id = tx_id;
                    IF (base_kind = 'LEDGER' AND (ledger_count <> 1 OR account_count <> 0))
                       OR (base_kind = 'ACCOUNT' AND (account_count <> 1 OR ledger_count <> 0)) THEN
                        RAISE EXCEPTION 'Accounting transaction must have exactly one matching subtype.';
                    END IF;
                    RETURN NULL;
                END;
                $$;

                CREATE CONSTRAINT TRIGGER acct_tx_subtype_base_guard
                AFTER INSERT OR UPDATE OR DELETE
                ON standalone_accounting_accountingtransaction
                DEFERRABLE INITIALLY DEFERRED
                FOR EACH ROW
                EXECUTE FUNCTION standalone_accounting_validate_subtype_cardinality();

                CREATE CONSTRAINT TRIGGER acct_tx_subtype_ledger_guard
                AFTER INSERT OR UPDATE OR DELETE
                ON standalone_accounting_ledgertransaction
                DEFERRABLE INITIALLY DEFERRED
                FOR EACH ROW
                EXECUTE FUNCTION standalone_accounting_validate_subtype_cardinality();

                CREATE CONSTRAINT TRIGGER acct_tx_subtype_account_guard
                AFTER INSERT OR UPDATE OR DELETE
                ON standalone_accounting_accounttransaction
                DEFERRABLE INITIALLY DEFERRED
                FOR EACH ROW
                EXECUTE FUNCTION standalone_accounting_validate_subtype_cardinality();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS acct_tx_subtype_account_guard
                ON standalone_accounting_accounttransaction;
                DROP TRIGGER IF EXISTS acct_tx_subtype_ledger_guard
                ON standalone_accounting_ledgertransaction;
                DROP TRIGGER IF EXISTS acct_tx_subtype_base_guard
                ON standalone_accounting_accountingtransaction;
                DROP FUNCTION IF EXISTS standalone_accounting_validate_subtype_cardinality();
            """,
        ),
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION standalone_accounting_protect_external_classification()
                RETURNS trigger
                LANGUAGE plpgsql
                AS $$
                BEGIN
                    IF TG_OP = 'DELETE' THEN
                        RAISE EXCEPTION 'External account classifications cannot be deleted.';
                    END IF;
                    IF NEW.external_account_id <> OLD.external_account_id
                       OR NEW.version_key <> OLD.version_key
                       OR NEW.effective_from <> OLD.effective_from
                       OR NEW.reporting_ledger_id <> OLD.reporting_ledger_id
                       OR NEW.reporting_class <> OLD.reporting_class
                       OR NEW.normal_side <> OLD.normal_side
                       OR NEW.created_at <> OLD.created_at
                       OR OLD.effective_to IS NOT NULL
                       OR NEW.effective_to IS NULL
                       OR NEW.effective_to < OLD.effective_from THEN
                        RAISE EXCEPTION 'External account classification is immutable except for one-time closure.';
                    END IF;
                    IF EXISTS(
                        SELECT 1
                        FROM standalone_accounting_accounttransaction account_tx
                        JOIN standalone_accounting_accountingtransaction tx
                          ON tx.id = account_tx.transaction_id
                        JOIN standalone_accounting_voucher voucher
                          ON voucher.id = tx.voucher_id
                        WHERE account_tx.classification_id = OLD.id
                          AND voucher.effective_date > NEW.effective_to
                    ) THEN
                        RAISE EXCEPTION 'Classification cannot close before an existing voucher that uses it.';
                    END IF;
                    RETURN NEW;
                END;
                $$;
            """,
            reverse_sql="""
                CREATE OR REPLACE FUNCTION standalone_accounting_protect_external_classification()
                RETURNS trigger
                LANGUAGE plpgsql
                AS $$
                BEGIN
                    IF TG_OP = 'DELETE' THEN
                        RAISE EXCEPTION 'External account classifications cannot be deleted.';
                    END IF;
                    IF NEW.external_account_id <> OLD.external_account_id
                       OR NEW.version_key <> OLD.version_key
                       OR NEW.effective_from <> OLD.effective_from
                       OR NEW.reporting_ledger_id <> OLD.reporting_ledger_id
                       OR NEW.reporting_class <> OLD.reporting_class
                       OR NEW.normal_side <> OLD.normal_side
                       OR NEW.created_at <> OLD.created_at
                       OR OLD.effective_to IS NOT NULL
                       OR NEW.effective_to IS NULL
                       OR NEW.effective_to < OLD.effective_from THEN
                        RAISE EXCEPTION 'External account classification is immutable except for one-time closure.';
                    END IF;
                    RETURN NEW;
                END;
                $$;
            """,
        ),
    ]
