# Generated by Django 6.0.3 on 2026-08-07 11:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standalone_accounting', '0003_voucher_accountingtransaction_accounttransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('posted_at', models.DateTimeField()),
                ('posted_by_id', models.PositiveBigIntegerField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('verification_digest', models.CharField(max_length=64)),
                ('correction_group_key', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('book_id', 'posted_at', 'id'),
            },
        ),
        migrations.RemoveConstraint(
            model_name='voucher',
            name='acct_voucher_authorized_evidence',
        ),
        migrations.RemoveConstraint(
            model_name='voucher',
            name='acct_voucher_preposting_no_fingerprint',
        ),
        migrations.AlterField(
            model_name='voucher',
            name='state',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('AUTHORIZED', 'Authorized'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('authorized_at__isnull', False), ('authorized_by_id__isnull', False), ('state__in', ('AUTHORIZED', 'POSTED'))), models.Q(('state__in', ('AUTHORIZED', 'POSTED')), _negated=True), _connector='OR'), name='acct_voucher_authorized_evidence'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('fingerprint__isnull', False), ('state', 'POSTED')), models.Q(('fingerprint__isnull', True), models.Q(('state', 'POSTED'), _negated=True)), _connector='OR'), name='acct_voucher_fingerprint_by_state'),
        ),
        migrations.AddField(
            model_name='transactionbatch',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_batches', to='standalone_accounting.accountingbook'),
        ),
        migrations.AddField(
            model_name='transactionbatch',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_batches', to='standalone_accounting.accountingperiod'),
        ),
        migrations.AddField(
            model_name='transactionbatch',
            name='reversal_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_batches', to='standalone_accounting.transactionbatch'),
        ),
        migrations.AddField(
            model_name='transactionbatch',
            name='voucher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='posting_batch', to='standalone_accounting.voucher'),
        ),
        migrations.AddConstraint(
            model_name='transactionbatch',
            constraint=models.UniqueConstraint(fields=('book', 'fingerprint'), name='acct_batch_book_fingerprint_uniq'),
        ),
        migrations.AddConstraint(
            model_name='transactionbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('reversal_of__isnull', False)), fields=('reversal_of',), name='acct_batch_one_reversal_per_original'),
        ),
        migrations.AddConstraint(
            model_name='transactionbatch',
            constraint=models.CheckConstraint(condition=models.Q(('id', models.F('reversal_of_id')), _negated=True), name='acct_batch_not_own_reversal'),
        ),
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION standalone_accounting_guard_voucher_draft()
                RETURNS trigger
                LANGUAGE plpgsql
                AS $$
                BEGIN
                    IF OLD.state = 'DRAFT' THEN
                        IF TG_OP = 'DELETE' THEN
                            RETURN OLD;
                        END IF;
                        IF NEW.state NOT IN ('DRAFT', 'AUTHORIZED', 'CANCELLED') THEN
                            RAISE EXCEPTION 'Invalid draft voucher transition.';
                        END IF;
                        RETURN NEW;
                    END IF;
                    IF OLD.state = 'AUTHORIZED' AND TG_OP = 'UPDATE'
                       AND NEW.state = 'POSTED'
                       AND NEW.book_id = OLD.book_id
                       AND NEW.voucher_key = OLD.voucher_key
                       AND NEW.voucher_number = OLD.voucher_number
                       AND NEW.effective_date = OLD.effective_date
                       AND NEW.purpose = OLD.purpose
                       AND NEW.idempotency_key = OLD.idempotency_key
                       AND NEW.source_system = OLD.source_system
                       AND NEW.source_type = OLD.source_type
                       AND NEW.source_id = OLD.source_id
                       AND NEW.source_version = OLD.source_version
                       AND NEW.rule_key = OLD.rule_key
                       AND NEW.rule_version = OLD.rule_version
                       AND NEW.authorized_by_id = OLD.authorized_by_id
                       AND NEW.authorized_at = OLD.authorized_at
                       AND NEW.narration = OLD.narration
                       AND NEW.correction_group_key = OLD.correction_group_key
                       AND NEW.created_at = OLD.created_at
                       AND NEW.fingerprint IS NOT NULL THEN
                        RETURN NEW;
                    END IF;
                    RAISE EXCEPTION 'Authorized, posted, or cancelled voucher intent is immutable.';
                END;
                $$;
            """,
            reverse_sql="""
                CREATE OR REPLACE FUNCTION standalone_accounting_guard_voucher_draft()
                RETURNS trigger
                LANGUAGE plpgsql
                AS $$
                BEGIN
                    IF OLD.state <> 'DRAFT' THEN
                        RAISE EXCEPTION 'Authorized or cancelled vouchers are immutable.';
                    END IF;
                    IF TG_OP = 'DELETE' THEN
                        RETURN OLD;
                    END IF;
                    IF NEW.state NOT IN ('DRAFT', 'AUTHORIZED', 'CANCELLED') THEN
                        RAISE EXCEPTION 'Invalid pre-posting voucher transition.';
                    END IF;
                    RETURN NEW;
                END;
                $$;
            """,
        ),
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION standalone_accounting_guard_posting_batch()
                RETURNS trigger
                LANGUAGE plpgsql
                AS $$
                DECLARE
                    voucher_book uuid;
                    voucher_date date;
                    voucher_state varchar(16);
                    voucher_purpose varchar(16);
                    voucher_fingerprint varchar(64);
                    period_book uuid;
                    period_start date;
                    period_end date;
                    period_status varchar(24);
                    original_book uuid;
                    original_reversal uuid;
                BEGIN
                    IF TG_OP IN ('UPDATE', 'DELETE') THEN
                        RAISE EXCEPTION 'Posting batches are immutable.';
                    END IF;
                    SELECT book_id, effective_date, state, purpose, fingerprint
                    INTO voucher_book, voucher_date, voucher_state, voucher_purpose,
                         voucher_fingerprint
                    FROM standalone_accounting_voucher WHERE id = NEW.voucher_id;
                    SELECT book_id, start_date, end_date, status
                    INTO period_book, period_start, period_end, period_status
                    FROM standalone_accounting_accountingperiod WHERE id = NEW.period_id;
                    IF voucher_state <> 'POSTED' THEN
                        RAISE EXCEPTION 'Posting batch requires a posted voucher.';
                    END IF;
                    IF voucher_book <> NEW.book_id OR period_book <> NEW.book_id THEN
                        RAISE EXCEPTION 'Posting batch, voucher, and period books must match.';
                    END IF;
                    IF voucher_date < period_start OR voucher_date > period_end THEN
                        RAISE EXCEPTION 'Voucher date must fall inside the posting period.';
                    END IF;
                    IF period_status <> 'OPEN'
                       AND NOT (period_status = 'ADJUSTMENT_ONLY' AND voucher_purpose = 'ADJUSTMENT') THEN
                        RAISE EXCEPTION 'Posting period does not permit this voucher purpose.';
                    END IF;
                    IF NEW.fingerprint <> voucher_fingerprint
                       OR NEW.fingerprint !~ '^[0-9a-f]{64}$'
                       OR NEW.verification_digest !~ '^[0-9a-f]{64}$' THEN
                        RAISE EXCEPTION 'Posting batch digests are invalid.';
                    END IF;
                    IF NEW.reversal_of_id IS NOT NULL THEN
                        SELECT book_id, reversal_of_id INTO original_book, original_reversal
                        FROM standalone_accounting_transactionbatch
                        WHERE id = NEW.reversal_of_id;
                        IF original_book <> NEW.book_id OR original_reversal IS NOT NULL THEN
                            RAISE EXCEPTION 'Invalid reversal batch relationship.';
                        END IF;
                    END IF;
                    RETURN NEW;
                END;
                $$;

                CREATE TRIGGER standalone_accounting_posting_batch_guard
                BEFORE INSERT OR UPDATE OR DELETE
                ON standalone_accounting_transactionbatch
                FOR EACH ROW
                EXECUTE FUNCTION standalone_accounting_guard_posting_batch();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS standalone_accounting_posting_batch_guard
                ON standalone_accounting_transactionbatch;
                DROP FUNCTION IF EXISTS standalone_accounting_guard_posting_batch();
            """,
        ),
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION standalone_accounting_validate_voucher_batch()
                RETURNS trigger
                LANGUAGE plpgsql
                AS $$
                DECLARE
                    target_voucher uuid;
                    voucher_state varchar(16);
                    batch_count integer;
                BEGIN
                    IF TG_TABLE_NAME = 'standalone_accounting_voucher' THEN
                        target_voucher := CASE WHEN TG_OP = 'DELETE' THEN OLD.id ELSE NEW.id END;
                    ELSE
                        target_voucher := CASE WHEN TG_OP = 'DELETE' THEN OLD.voucher_id ELSE NEW.voucher_id END;
                    END IF;
                    SELECT state INTO voucher_state
                    FROM standalone_accounting_voucher WHERE id = target_voucher;
                    IF NOT FOUND THEN
                        RETURN NULL;
                    END IF;
                    SELECT count(*) INTO batch_count
                    FROM standalone_accounting_transactionbatch
                    WHERE voucher_id = target_voucher;
                    IF (voucher_state = 'POSTED' AND batch_count <> 1)
                       OR (voucher_state <> 'POSTED' AND batch_count <> 0) THEN
                        RAISE EXCEPTION 'Voucher posted state must correspond to exactly one posting batch.';
                    END IF;
                    RETURN NULL;
                END;
                $$;

                CREATE CONSTRAINT TRIGGER acct_voucher_batch_voucher_guard
                AFTER INSERT OR UPDATE OR DELETE
                ON standalone_accounting_voucher
                DEFERRABLE INITIALLY DEFERRED
                FOR EACH ROW
                EXECUTE FUNCTION standalone_accounting_validate_voucher_batch();

                CREATE CONSTRAINT TRIGGER acct_voucher_batch_batch_guard
                AFTER INSERT OR UPDATE OR DELETE
                ON standalone_accounting_transactionbatch
                DEFERRABLE INITIALLY DEFERRED
                FOR EACH ROW
                EXECUTE FUNCTION standalone_accounting_validate_voucher_batch();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS acct_voucher_batch_batch_guard
                ON standalone_accounting_transactionbatch;
                DROP TRIGGER IF EXISTS acct_voucher_batch_voucher_guard
                ON standalone_accounting_voucher;
                DROP FUNCTION IF EXISTS standalone_accounting_validate_voucher_batch();
            """,
        ),
    ]
