# Generated by Django 6.0.3 on 2026-08-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standalone_accounting', '0004_transactionbatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionbatch',
            name='reversal_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='transactionbatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reversal_of__isnull', True), ('reversal_reason', '')), models.Q(('reversal_of__isnull', False), models.Q(('reversal_reason', ''), _negated=True)), _connector='OR'), name='acct_batch_reversal_reason_evidence'),
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE standalone_accounting_accounttransaction
                DISABLE TRIGGER standalone_accounting_account_transaction_guard;
            """,
            reverse_sql="""
                ALTER TABLE standalone_accounting_accounttransaction
                ENABLE TRIGGER standalone_accounting_account_transaction_guard;
            """,
        ),
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION standalone_accounting_validate_account_tx_k5_5()
                RETURNS trigger
                LANGUAGE plpgsql
                AS $$
                DECLARE
                    base_kind varchar(8);
                    voucher_book uuid;
                    voucher_date date;
                    voucher_state varchar(16);
                    voucher_source_type varchar(64);
                    internal_book uuid;
                    internal_kind varchar(16);
                    internal_debit boolean;
                    internal_credit boolean;
                    account_book uuid;
                    class_account uuid;
                    class_from date;
                    class_to date;
                BEGIN
                    SELECT tx.discriminator, voucher.book_id, voucher.effective_date,
                           voucher.state, voucher.source_type
                    INTO base_kind, voucher_book, voucher_date, voucher_state,
                         voucher_source_type
                    FROM standalone_accounting_accountingtransaction tx
                    JOIN standalone_accounting_voucher voucher ON voucher.id = tx.voucher_id
                    WHERE tx.id = CASE WHEN TG_OP = 'DELETE' THEN OLD.transaction_id ELSE NEW.transaction_id END;
                    IF voucher_state <> 'DRAFT' THEN
                        RAISE EXCEPTION 'Transaction subtypes may change only on a draft voucher.';
                    END IF;
                    IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
                    IF base_kind <> 'ACCOUNT' THEN
                        RAISE EXCEPTION 'Account subtype requires ACCOUNT discriminator.';
                    END IF;
                    SELECT book_id, node_kind, can_debit, can_credit
                    INTO internal_book, internal_kind, internal_debit, internal_credit
                    FROM standalone_accounting_ledger WHERE id = NEW.ledger_id;
                    SELECT book_id INTO account_book
                    FROM standalone_accounting_externalaccount WHERE id = NEW.external_account_id;
                    SELECT external_account_id, effective_from, effective_to
                    INTO class_account, class_from, class_to
                    FROM standalone_accounting_externalaccountclassification
                    WHERE id = NEW.classification_id;
                    IF internal_book <> voucher_book OR account_book <> voucher_book THEN
                        RAISE EXCEPTION 'Account transaction sides must belong to the voucher book.';
                    END IF;
                    IF internal_kind <> 'POSTING' THEN
                        RAISE EXCEPTION 'Account transaction requires a posting ledger.';
                    END IF;
                    IF (NEW.ledger_side = 'DEBIT' AND NOT internal_debit)
                       OR (NEW.ledger_side = 'CREDIT' AND NOT internal_credit) THEN
                        RAISE EXCEPTION 'Ledger does not permit the requested account transaction side.';
                    END IF;
                    IF class_account <> NEW.external_account_id THEN
                        RAISE EXCEPTION 'Classification must belong to the external account.';
                    END IF;
                    IF voucher_source_type <> 'REVERSAL'
                       AND (class_from > voucher_date OR (class_to IS NOT NULL AND class_to < voucher_date)) THEN
                        RAISE EXCEPTION 'Classification must be effective on the voucher date.';
                    END IF;
                    RETURN NEW;
                END;
                $$;

                CREATE TRIGGER standalone_accounting_account_transaction_guard_k5_5
                BEFORE INSERT OR UPDATE OR DELETE
                ON standalone_accounting_accounttransaction
                FOR EACH ROW
                EXECUTE FUNCTION standalone_accounting_validate_account_tx_k5_5();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS standalone_accounting_account_transaction_guard_k5_5
                ON standalone_accounting_accounttransaction;
                DROP FUNCTION IF EXISTS standalone_accounting_validate_account_tx_k5_5();
            """,
        ),
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION standalone_accounting_verify_exact_reversal()
                RETURNS trigger
                LANGUAGE plpgsql
                AS $$
                DECLARE
                    original_voucher uuid;
                    original_count integer;
                    reversal_count integer;
                    reversal_source_type varchar(64);
                    voucher_group varchar(128);
                BEGIN
                    IF NEW.reversal_of_id IS NULL THEN RETURN NEW; END IF;
                    SELECT voucher_id INTO original_voucher
                    FROM standalone_accounting_transactionbatch WHERE id = NEW.reversal_of_id;
                    SELECT source_type, correction_group_key
                    INTO reversal_source_type, voucher_group
                    FROM standalone_accounting_voucher WHERE id = NEW.voucher_id;
                    IF reversal_source_type <> 'REVERSAL'
                       OR NEW.correction_group_key IS DISTINCT FROM voucher_group THEN
                        RAISE EXCEPTION 'Reversal batch identity is invalid.';
                    END IF;
                    SELECT count(*) INTO original_count
                    FROM standalone_accounting_accountingtransaction WHERE voucher_id = original_voucher;
                    SELECT count(*) INTO reversal_count
                    FROM standalone_accounting_accountingtransaction WHERE voucher_id = NEW.voucher_id;
                    IF original_count <> reversal_count OR original_count = 0 THEN
                        RAISE EXCEPTION 'Reversal must contain every original transaction exactly once.';
                    END IF;
                    IF EXISTS (
                        SELECT 1
                        FROM standalone_accounting_accountingtransaction original
                        LEFT JOIN standalone_accounting_accountingtransaction reversal
                          ON reversal.voucher_id = NEW.voucher_id
                         AND reversal.sequence = original_count + 1 - original.sequence
                        LEFT JOIN standalone_accounting_ledgertransaction ol ON ol.transaction_id = original.id
                        LEFT JOIN standalone_accounting_ledgertransaction rl ON rl.transaction_id = reversal.id
                        LEFT JOIN standalone_accounting_accounttransaction oa ON oa.transaction_id = original.id
                        LEFT JOIN standalone_accounting_accounttransaction ra ON ra.transaction_id = reversal.id
                        WHERE original.voucher_id = original_voucher
                          AND (
                            reversal.id IS NULL
                            OR reversal.discriminator IS DISTINCT FROM original.discriminator
                            OR reversal.amount IS DISTINCT FROM original.amount
                            OR reversal.currency IS DISTINCT FROM original.currency
                            OR reversal.base_amount IS DISTINCT FROM original.base_amount
                            OR reversal.base_currency IS DISTINCT FROM original.base_currency
                            OR reversal.exchange_rate IS DISTINCT FROM original.exchange_rate
                            OR reversal.rate_source IS DISTINCT FROM original.rate_source
                            OR (original.discriminator = 'LEDGER' AND (
                                rl.debit_ledger_id IS DISTINCT FROM ol.credit_ledger_id
                                OR rl.credit_ledger_id IS DISTINCT FROM ol.debit_ledger_id
                            ))
                            OR (original.discriminator = 'ACCOUNT' AND (
                                ra.ledger_id IS DISTINCT FROM oa.ledger_id
                                OR ra.external_account_id IS DISTINCT FROM oa.external_account_id
                                OR ra.classification_id IS DISTINCT FROM oa.classification_id
                                OR ra.ledger_side IS DISTINCT FROM CASE oa.ledger_side
                                    WHEN 'DEBIT' THEN 'CREDIT' ELSE 'DEBIT' END
                            ))
                          )
                    ) THEN
                        RAISE EXCEPTION 'Reversal transactions must be the exact reverse-order opposite.';
                    END IF;
                    RETURN NEW;
                END;
                $$;

                CREATE TRIGGER standalone_accounting_exact_reversal_guard
                BEFORE INSERT
                ON standalone_accounting_transactionbatch
                FOR EACH ROW
                EXECUTE FUNCTION standalone_accounting_verify_exact_reversal();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS standalone_accounting_exact_reversal_guard
                ON standalone_accounting_transactionbatch;
                DROP FUNCTION IF EXISTS standalone_accounting_verify_exact_reversal();
            """,
        ),
    ]
