# Generated by Django 6.0.3 on 2026-08-07 11:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standalone_accounting', '0005_transactionbatch_reversal_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('open_item_key', models.CharField(max_length=128)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('original_amount', models.DecimalField(decimal_places=8, max_digits=24)),
                ('currency', models.CharField(max_length=3)),
                ('original_base_amount', models.DecimalField(decimal_places=8, max_digits=24)),
                ('base_currency', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_id', models.PositiveBigIntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='open_items', to='standalone_accounting.accountingbook')),
                ('external_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='open_items', to='standalone_accounting.externalaccount')),
                ('origin_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='open_item', to='standalone_accounting.accounttransaction')),
            ],
            options={
                'ordering': ('book_id', 'open_item_key'),
            },
        ),
        migrations.CreateModel(
            name='OpenItemAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=8, max_digits=24)),
                ('currency', models.CharField(max_length=3)),
                ('base_amount', models.DecimalField(decimal_places=8, max_digits=24)),
                ('base_currency', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_id', models.PositiveBigIntegerField()),
                ('open_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='standalone_accounting.openitem')),
                ('settlement_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='open_item_allocations', to='standalone_accounting.accounttransaction')),
            ],
            options={
                'ordering': ('settlement_transaction_id', 'sequence'),
            },
        ),
        migrations.AddConstraint(
            model_name='openitem',
            constraint=models.UniqueConstraint(fields=('book', 'open_item_key'), name='acct_open_item_book_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='openitem',
            constraint=models.CheckConstraint(condition=models.Q(('original_amount__gt', 0)), name='acct_open_item_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='openitem',
            constraint=models.CheckConstraint(condition=models.Q(('original_base_amount__gt', 0)), name='acct_open_item_base_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='openitemallocation',
            constraint=models.UniqueConstraint(fields=('settlement_transaction', 'sequence'), name='acct_allocation_settlement_sequence_uniq'),
        ),
        migrations.AddConstraint(
            model_name='openitemallocation',
            constraint=models.UniqueConstraint(fields=('settlement_transaction', 'open_item'), name='acct_allocation_settlement_item_uniq'),
        ),
        migrations.AddConstraint(
            model_name='openitemallocation',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gt', 0)), name='acct_allocation_sequence_positive'),
        ),
        migrations.AddConstraint(
            model_name='openitemallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='acct_allocation_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='openitemallocation',
            constraint=models.CheckConstraint(condition=models.Q(('base_amount__gt', 0)), name='acct_allocation_base_amount_positive'),
        ),
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION standalone_accounting_guard_open_item()
                RETURNS trigger
                LANGUAGE plpgsql
                AS $$
                DECLARE
                    origin_book uuid;
                    origin_account uuid;
                    origin_state varchar(16);
                    origin_amount numeric;
                    origin_currency varchar(3);
                    origin_base_amount numeric;
                    origin_base_currency varchar(3);
                BEGIN
                    IF TG_OP IN ('UPDATE', 'DELETE') THEN
                        RAISE EXCEPTION 'Open items are immutable.';
                    END IF;
                    SELECT voucher.book_id, detail.external_account_id, voucher.state,
                           tx.amount, tx.currency, tx.base_amount, tx.base_currency
                    INTO origin_book, origin_account, origin_state, origin_amount,
                         origin_currency, origin_base_amount, origin_base_currency
                    FROM standalone_accounting_accounttransaction detail
                    JOIN standalone_accounting_accountingtransaction tx
                      ON tx.id = detail.transaction_id
                    JOIN standalone_accounting_voucher voucher ON voucher.id = tx.voucher_id
                    WHERE detail.transaction_id = NEW.origin_transaction_id;
                    IF origin_state <> 'POSTED' THEN
                        RAISE EXCEPTION 'Open item origin must be posted.';
                    END IF;
                    IF NEW.book_id <> origin_book OR NEW.external_account_id <> origin_account THEN
                        RAISE EXCEPTION 'Open item ownership must match its origin transaction.';
                    END IF;
                    IF NEW.original_amount <> origin_amount
                       OR NEW.currency <> origin_currency
                       OR NEW.original_base_amount <> origin_base_amount
                       OR NEW.base_currency <> origin_base_currency THEN
                        RAISE EXCEPTION 'Open item must freeze the exact origin money.';
                    END IF;
                    RETURN NEW;
                END;
                $$;

                CREATE TRIGGER standalone_accounting_open_item_guard
                BEFORE INSERT OR UPDATE OR DELETE
                ON standalone_accounting_openitem
                FOR EACH ROW
                EXECUTE FUNCTION standalone_accounting_guard_open_item();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS standalone_accounting_open_item_guard
                ON standalone_accounting_openitem;
                DROP FUNCTION IF EXISTS standalone_accounting_guard_open_item();
            """,
        ),
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION standalone_accounting_guard_open_item_allocation()
                RETURNS trigger
                LANGUAGE plpgsql
                AS $$
                DECLARE
                    settlement_book uuid;
                    settlement_account uuid;
                    settlement_state varchar(16);
                    settlement_side varchar(8);
                    settlement_amount numeric;
                    settlement_base_amount numeric;
                    item_book uuid;
                    item_account uuid;
                    item_side varchar(8);
                    item_amount numeric;
                    item_base_amount numeric;
                    item_currency varchar(3);
                    item_base_currency varchar(3);
                    used_settlement numeric;
                    used_settlement_base numeric;
                    used_item numeric;
                    used_item_base numeric;
                BEGIN
                    IF TG_OP IN ('UPDATE', 'DELETE') THEN
                        RAISE EXCEPTION 'Open-item allocations are immutable.';
                    END IF;
                    PERFORM 1 FROM standalone_accounting_accounttransaction
                    WHERE transaction_id = NEW.settlement_transaction_id FOR UPDATE;
                    PERFORM 1 FROM standalone_accounting_openitem
                    WHERE id = NEW.open_item_id FOR UPDATE;
                    SELECT voucher.book_id, detail.external_account_id, voucher.state,
                           detail.ledger_side, tx.amount, tx.base_amount
                    INTO settlement_book, settlement_account, settlement_state,
                         settlement_side, settlement_amount, settlement_base_amount
                    FROM standalone_accounting_accounttransaction detail
                    JOIN standalone_accounting_accountingtransaction tx
                      ON tx.id = detail.transaction_id
                    JOIN standalone_accounting_voucher voucher ON voucher.id = tx.voucher_id
                    WHERE detail.transaction_id = NEW.settlement_transaction_id;
                    SELECT item.book_id, item.external_account_id, origin.ledger_side,
                           item.original_amount, item.original_base_amount,
                           item.currency, item.base_currency
                    INTO item_book, item_account, item_side, item_amount,
                         item_base_amount, item_currency, item_base_currency
                    FROM standalone_accounting_openitem item
                    JOIN standalone_accounting_accounttransaction origin
                      ON origin.transaction_id = item.origin_transaction_id
                    WHERE item.id = NEW.open_item_id;
                    IF settlement_state <> 'POSTED' THEN
                        RAISE EXCEPTION 'Settlement transaction must be posted.';
                    END IF;
                    IF settlement_book <> item_book OR settlement_account <> item_account THEN
                        RAISE EXCEPTION 'Allocation cannot cross books or external accounts.';
                    END IF;
                    IF settlement_side = item_side THEN
                        RAISE EXCEPTION 'Settlement must oppose the open-item transaction side.';
                    END IF;
                    IF NEW.currency <> item_currency OR NEW.base_currency <> item_base_currency THEN
                        RAISE EXCEPTION 'Allocation currencies must match the open item.';
                    END IF;
                    SELECT COALESCE(sum(amount), 0), COALESCE(sum(base_amount), 0)
                    INTO used_settlement, used_settlement_base
                    FROM standalone_accounting_openitemallocation
                    WHERE settlement_transaction_id = NEW.settlement_transaction_id;
                    SELECT COALESCE(sum(amount), 0), COALESCE(sum(base_amount), 0)
                    INTO used_item, used_item_base
                    FROM standalone_accounting_openitemallocation
                    WHERE open_item_id = NEW.open_item_id;
                    IF used_settlement + NEW.amount > settlement_amount
                       OR used_settlement_base + NEW.base_amount > settlement_base_amount THEN
                        RAISE EXCEPTION 'Allocation exceeds settlement capacity.';
                    END IF;
                    IF used_item + NEW.amount > item_amount
                       OR used_item_base + NEW.base_amount > item_base_amount THEN
                        RAISE EXCEPTION 'Allocation exceeds open-item outstanding capacity.';
                    END IF;
                    RETURN NEW;
                END;
                $$;

                CREATE TRIGGER standalone_accounting_open_item_allocation_guard
                BEFORE INSERT OR UPDATE OR DELETE
                ON standalone_accounting_openitemallocation
                FOR EACH ROW
                EXECUTE FUNCTION standalone_accounting_guard_open_item_allocation();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS standalone_accounting_open_item_allocation_guard
                ON standalone_accounting_openitemallocation;
                DROP FUNCTION IF EXISTS standalone_accounting_guard_open_item_allocation();
            """,
        ),
    ]
