# Generated by Django 6.0.3 on 2026-08-07 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standalone_accounting', '0006_openitem_openitemallocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openitemallocation',
            name='reversal_of',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compensating_allocation', to='standalone_accounting.openitemallocation'),
        ),
        migrations.AddConstraint(
            model_name='openitemallocation',
            constraint=models.CheckConstraint(condition=models.Q(('id', models.F('reversal_of_id')), _negated=True), name='acct_allocation_not_own_reversal'),
        ),
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION standalone_accounting_guard_open_item_allocation()
                RETURNS trigger
                LANGUAGE plpgsql
                AS $$
                DECLARE
                    settlement_book uuid; settlement_account uuid;
                    settlement_state varchar(16); settlement_side varchar(8);
                    settlement_amount numeric; settlement_base_amount numeric;
                    settlement_batch uuid; settlement_reversal_of uuid;
                    item_book uuid; item_account uuid; item_side varchar(8);
                    item_amount numeric; item_base_amount numeric;
                    item_currency varchar(3); item_base_currency varchar(3);
                    original_item uuid; original_amount numeric;
                    original_currency varchar(3); original_base_amount numeric;
                    original_base_currency varchar(3); original_batch uuid;
                    used_settlement numeric; used_settlement_base numeric;
                    used_item numeric; used_item_base numeric;
                BEGIN
                    IF TG_OP IN ('UPDATE', 'DELETE') THEN
                        RAISE EXCEPTION 'Open-item allocations are immutable.';
                    END IF;
                    PERFORM 1 FROM standalone_accounting_accounttransaction
                    WHERE transaction_id = NEW.settlement_transaction_id FOR UPDATE;
                    PERFORM 1 FROM standalone_accounting_openitem
                    WHERE id = NEW.open_item_id FOR UPDATE;
                    SELECT voucher.book_id, detail.external_account_id, voucher.state,
                           detail.ledger_side, tx.amount, tx.base_amount,
                           batch.id, batch.reversal_of_id
                    INTO settlement_book, settlement_account, settlement_state,
                         settlement_side, settlement_amount, settlement_base_amount,
                         settlement_batch, settlement_reversal_of
                    FROM standalone_accounting_accounttransaction detail
                    JOIN standalone_accounting_accountingtransaction tx ON tx.id = detail.transaction_id
                    JOIN standalone_accounting_voucher voucher ON voucher.id = tx.voucher_id
                    JOIN standalone_accounting_transactionbatch batch ON batch.voucher_id = voucher.id
                    WHERE detail.transaction_id = NEW.settlement_transaction_id;
                    SELECT item.book_id, item.external_account_id, origin.ledger_side,
                           item.original_amount, item.original_base_amount,
                           item.currency, item.base_currency
                    INTO item_book, item_account, item_side, item_amount,
                         item_base_amount, item_currency, item_base_currency
                    FROM standalone_accounting_openitem item
                    JOIN standalone_accounting_accounttransaction origin
                      ON origin.transaction_id = item.origin_transaction_id
                    WHERE item.id = NEW.open_item_id;
                    IF settlement_state <> 'POSTED'
                       OR settlement_book <> item_book OR settlement_account <> item_account THEN
                        RAISE EXCEPTION 'Allocation requires a posted settlement on the same book and account.';
                    END IF;
                    IF NEW.currency <> item_currency OR NEW.base_currency <> item_base_currency THEN
                        RAISE EXCEPTION 'Allocation currencies must match the open item.';
                    END IF;
                    IF NEW.reversal_of_id IS NOT NULL THEN
                        SELECT original.open_item_id, original.amount, original.currency,
                               original.base_amount, original.base_currency, batch.id
                        INTO original_item, original_amount, original_currency,
                             original_base_amount, original_base_currency, original_batch
                        FROM standalone_accounting_openitemallocation original
                        JOIN standalone_accounting_accounttransaction detail
                          ON detail.transaction_id = original.settlement_transaction_id
                        JOIN standalone_accounting_accountingtransaction tx ON tx.id = detail.transaction_id
                        JOIN standalone_accounting_transactionbatch batch ON batch.voucher_id = tx.voucher_id
                        WHERE original.id = NEW.reversal_of_id
                          AND original.reversal_of_id IS NULL;
                        IF original_item IS NULL
                           OR original_item <> NEW.open_item_id
                           OR original_amount <> NEW.amount
                           OR original_currency <> NEW.currency
                           OR original_base_amount <> NEW.base_amount
                           OR original_base_currency <> NEW.base_currency
                           OR settlement_reversal_of <> original_batch
                           OR settlement_side <> item_side THEN
                            RAISE EXCEPTION 'Allocation compensation must exactly follow the financial reversal.';
                        END IF;
                        RETURN NEW;
                    END IF;
                    IF settlement_side = item_side THEN
                        RAISE EXCEPTION 'Settlement must oppose the open-item transaction side.';
                    END IF;
                    SELECT COALESCE(sum(amount) FILTER (WHERE reversal_of_id IS NULL), 0)
                             - COALESCE(sum(amount) FILTER (WHERE reversal_of_id IS NOT NULL), 0),
                           COALESCE(sum(base_amount) FILTER (WHERE reversal_of_id IS NULL), 0)
                             - COALESCE(sum(base_amount) FILTER (WHERE reversal_of_id IS NOT NULL), 0)
                    INTO used_settlement, used_settlement_base
                    FROM standalone_accounting_openitemallocation
                    WHERE settlement_transaction_id = NEW.settlement_transaction_id;
                    SELECT COALESCE(sum(amount) FILTER (WHERE reversal_of_id IS NULL), 0)
                             - COALESCE(sum(amount) FILTER (WHERE reversal_of_id IS NOT NULL), 0),
                           COALESCE(sum(base_amount) FILTER (WHERE reversal_of_id IS NULL), 0)
                             - COALESCE(sum(base_amount) FILTER (WHERE reversal_of_id IS NOT NULL), 0)
                    INTO used_item, used_item_base
                    FROM standalone_accounting_openitemallocation
                    WHERE open_item_id = NEW.open_item_id;
                    IF used_settlement + NEW.amount > settlement_amount
                       OR used_settlement_base + NEW.base_amount > settlement_base_amount THEN
                        RAISE EXCEPTION 'Allocation exceeds settlement capacity.';
                    END IF;
                    IF used_item + NEW.amount > item_amount
                       OR used_item_base + NEW.base_amount > item_base_amount THEN
                        RAISE EXCEPTION 'Allocation exceeds open-item outstanding capacity.';
                    END IF;
                    RETURN NEW;
                END;
                $$;
            """,
            reverse_sql="""
                CREATE OR REPLACE FUNCTION standalone_accounting_guard_open_item_allocation()
                RETURNS trigger
                LANGUAGE plpgsql
                AS $$
                DECLARE
                    settlement_book uuid; settlement_account uuid;
                    settlement_state varchar(16); settlement_side varchar(8);
                    settlement_amount numeric; settlement_base_amount numeric;
                    item_book uuid; item_account uuid; item_side varchar(8);
                    item_amount numeric; item_base_amount numeric;
                    item_currency varchar(3); item_base_currency varchar(3);
                    used_settlement numeric; used_settlement_base numeric;
                    used_item numeric; used_item_base numeric;
                BEGIN
                    IF TG_OP IN ('UPDATE', 'DELETE') THEN
                        RAISE EXCEPTION 'Open-item allocations are immutable.';
                    END IF;
                    PERFORM 1 FROM standalone_accounting_accounttransaction
                    WHERE transaction_id = NEW.settlement_transaction_id FOR UPDATE;
                    PERFORM 1 FROM standalone_accounting_openitem
                    WHERE id = NEW.open_item_id FOR UPDATE;
                    SELECT voucher.book_id, detail.external_account_id, voucher.state,
                           detail.ledger_side, tx.amount, tx.base_amount
                    INTO settlement_book, settlement_account, settlement_state,
                         settlement_side, settlement_amount, settlement_base_amount
                    FROM standalone_accounting_accounttransaction detail
                    JOIN standalone_accounting_accountingtransaction tx ON tx.id = detail.transaction_id
                    JOIN standalone_accounting_voucher voucher ON voucher.id = tx.voucher_id
                    WHERE detail.transaction_id = NEW.settlement_transaction_id;
                    SELECT item.book_id, item.external_account_id, origin.ledger_side,
                           item.original_amount, item.original_base_amount,
                           item.currency, item.base_currency
                    INTO item_book, item_account, item_side, item_amount,
                         item_base_amount, item_currency, item_base_currency
                    FROM standalone_accounting_openitem item
                    JOIN standalone_accounting_accounttransaction origin ON origin.transaction_id = item.origin_transaction_id
                    WHERE item.id = NEW.open_item_id;
                    IF settlement_state <> 'POSTED' OR settlement_book <> item_book
                       OR settlement_account <> item_account OR settlement_side = item_side
                       OR NEW.currency <> item_currency OR NEW.base_currency <> item_base_currency THEN
                        RAISE EXCEPTION 'Invalid open-item allocation boundary.';
                    END IF;
                    SELECT COALESCE(sum(amount), 0), COALESCE(sum(base_amount), 0)
                    INTO used_settlement, used_settlement_base
                    FROM standalone_accounting_openitemallocation
                    WHERE settlement_transaction_id = NEW.settlement_transaction_id;
                    SELECT COALESCE(sum(amount), 0), COALESCE(sum(base_amount), 0)
                    INTO used_item, used_item_base
                    FROM standalone_accounting_openitemallocation WHERE open_item_id = NEW.open_item_id;
                    IF used_settlement + NEW.amount > settlement_amount
                       OR used_settlement_base + NEW.base_amount > settlement_base_amount
                       OR used_item + NEW.amount > item_amount
                       OR used_item_base + NEW.base_amount > item_base_amount THEN
                        RAISE EXCEPTION 'Allocation exceeds capacity.';
                    END IF;
                    RETURN NEW;
                END;
                $$;
            """,
        ),
    ]
