# Generated by Django 6.0.3 on 2026-08-07 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standalone_accounting', '0007_openitemallocation_reversal_of_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionbatch',
            name='posted_by_identity',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='voucher',
            name='authorized_by_identity',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='voucher',
            name='created_by_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='created_by_identity',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.CreateModel(
            name='VoucherNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_year', models.PositiveSmallIntegerField()),
                ('next_number', models.PositiveBigIntegerField(default=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_number_sequences', to='standalone_accounting.accountingbook')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('book', 'sequence_year'), name='acct_voucher_seq_book_year_uniq'), models.CheckConstraint(condition=models.Q(('next_number__gt', 0)), name='acct_voucher_seq_next_positive')],
            },
        ),
    ]
