# Generated by Django 6.0.3 on 2026-08-07 12:35

from django.db import migrations, models


def backfill_actor_evidence(apps, schema_editor):
    Voucher = apps.get_model("standalone_accounting", "Voucher")
    Batch = apps.get_model("standalone_accounting", "TransactionBatch")
    for voucher in Voucher.objects.all().iterator():
        voucher.created_by_identity = "legacy:unattributed"
        if voucher.authorized_by_id:
            voucher.authorized_by_identity = f"user:{voucher.authorized_by_id}"
        voucher.save(update_fields=("created_by_identity", "authorized_by_identity"))
    for batch in Batch.objects.all().iterator():
        batch.posted_by_identity = f"user:{batch.posted_by_id}"
        batch.save(update_fields=("posted_by_identity",))


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('standalone_accounting', '0008_durable_actor_evidence_and_voucher_numbering'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE standalone_accounting_voucher
                DISABLE TRIGGER standalone_accounting_voucher_draft_guard;
                ALTER TABLE standalone_accounting_transactionbatch
                DISABLE TRIGGER standalone_accounting_posting_batch_guard;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunPython(backfill_actor_evidence, migrations.RunPython.noop),
        migrations.RunSQL(
            sql="""
                ALTER TABLE standalone_accounting_voucher
                ENABLE TRIGGER standalone_accounting_voucher_draft_guard;
                ALTER TABLE standalone_accounting_transactionbatch
                ENABLE TRIGGER standalone_accounting_posting_batch_guard;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddConstraint(
            model_name='transactionbatch',
            constraint=models.CheckConstraint(condition=models.Q(('posted_by_identity', ''), _negated=True), name='acct_batch_poster_identity_required'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(('created_by_identity', ''), _negated=True), name='acct_voucher_creator_identity_required'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('state__in', ('AUTHORIZED', 'POSTED')), models.Q(('authorized_by_identity', ''), _negated=True)), models.Q(('state__in', ('AUTHORIZED', 'POSTED')), _negated=True), _connector='OR'), name='acct_voucher_authorizer_identity_required'),
        ),
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION standalone_accounting_protect_actor_evidence()
                RETURNS trigger LANGUAGE plpgsql AS $$
                BEGIN
                    IF NEW.created_by_id IS DISTINCT FROM OLD.created_by_id
                       OR NEW.created_by_identity IS DISTINCT FROM OLD.created_by_identity THEN
                        RAISE EXCEPTION 'Voucher creator evidence is immutable.';
                    END IF;
                    IF OLD.state IN ('AUTHORIZED', 'POSTED') AND (
                        NEW.authorized_by_id IS DISTINCT FROM OLD.authorized_by_id
                        OR NEW.authorized_by_identity IS DISTINCT FROM OLD.authorized_by_identity
                        OR NEW.authorized_at IS DISTINCT FROM OLD.authorized_at
                    ) THEN
                        RAISE EXCEPTION 'Voucher authorization evidence is immutable.';
                    END IF;
                    RETURN NEW;
                END;
                $$;
                CREATE TRIGGER standalone_accounting_actor_evidence_guard
                BEFORE UPDATE ON standalone_accounting_voucher
                FOR EACH ROW EXECUTE FUNCTION standalone_accounting_protect_actor_evidence();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS standalone_accounting_actor_evidence_guard
                ON standalone_accounting_voucher;
                DROP FUNCTION IF EXISTS standalone_accounting_protect_actor_evidence();
            """,
        ),
    ]
