# Generated by Django 6.0.3 on 2026-08-07 12:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standalone_accounting', '0009_actor_evidence_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingPeriodTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(choices=[('OPEN', 'Open'), ('ADJUSTMENT_ONLY', 'Adjustment Only'), ('CLOSED', 'Closed'), ('LOCKED', 'Locked')], max_length=24)),
                ('to_status', models.CharField(choices=[('OPEN', 'Open'), ('ADJUSTMENT_ONLY', 'Adjustment Only'), ('CLOSED', 'Closed'), ('LOCKED', 'Locked')], max_length=24)),
                ('actor_id', models.PositiveBigIntegerField()),
                ('actor_identity', models.CharField(max_length=512)),
                ('occurred_at', models.DateTimeField()),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to='standalone_accounting.accountingperiod')),
            ],
            options={
                'ordering': ('period_id', 'occurred_at', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('from_status', models.F('to_status')), _negated=True), name='acct_period_transition_changes_status'), models.UniqueConstraint(fields=('period', 'occurred_at'), name='acct_period_transition_time_uniq')],
            },
        ),
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION standalone_accounting_guard_period_transition()
                RETURNS trigger LANGUAGE plpgsql AS $$
                BEGIN
                    IF TG_TABLE_NAME = 'standalone_accounting_accountingperiodtransition' THEN
                        IF TG_OP IN ('UPDATE', 'DELETE') THEN
                            RAISE EXCEPTION 'Accounting period transition evidence is immutable.';
                        END IF;
                        RETURN NEW;
                    END IF;
                    IF NEW.status = OLD.status THEN RETURN NEW; END IF;
                    IF NOT ((OLD.status = 'OPEN' AND NEW.status IN ('ADJUSTMENT_ONLY','CLOSED'))
                       OR (OLD.status = 'ADJUSTMENT_ONLY' AND NEW.status = 'CLOSED')
                       OR (OLD.status = 'CLOSED' AND NEW.status IN ('ADJUSTMENT_ONLY','LOCKED'))) THEN
                        RAISE EXCEPTION 'Invalid accounting period transition.';
                    END IF;
                    IF NOT EXISTS (
                        SELECT 1 FROM standalone_accounting_accountingperiodtransition e
                        WHERE e.period_id = OLD.id AND e.from_status = OLD.status
                          AND e.to_status = NEW.status
                    ) THEN
                        RAISE EXCEPTION 'Accounting period transition requires audit evidence.';
                    END IF;
                    RETURN NEW;
                END; $$;
                CREATE TRIGGER standalone_accounting_period_guard
                BEFORE UPDATE ON standalone_accounting_accountingperiod
                FOR EACH ROW EXECUTE FUNCTION standalone_accounting_guard_period_transition();
                CREATE TRIGGER standalone_accounting_period_evidence_guard
                BEFORE UPDATE OR DELETE ON standalone_accounting_accountingperiodtransition
                FOR EACH ROW EXECUTE FUNCTION standalone_accounting_guard_period_transition();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS standalone_accounting_period_evidence_guard ON standalone_accounting_accountingperiodtransition;
                DROP TRIGGER IF EXISTS standalone_accounting_period_guard ON standalone_accounting_accountingperiod;
                DROP FUNCTION IF EXISTS standalone_accounting_guard_period_transition();
            """,
        ),
    ]
