# Generated by Django 6.0.3 on 2026-08-07 12:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standalone_accounting', '0011_period_transition_latest_evidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingSourceDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_system', models.CharField(max_length=64)),
                ('source_type', models.CharField(max_length=64)),
                ('source_id', models.CharField(max_length=128)),
                ('source_version', models.CharField(max_length=64)),
                ('schema_version', models.CharField(max_length=16)),
                ('payload_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('POSTED', 'Posted'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_deliveries', to='standalone_accounting.accountingbook')),
                ('voucher', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_delivery', to='standalone_accounting.voucher')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('book', 'source_system', 'source_type', 'source_id', 'source_version'), name='acct_delivery_source_version_uniq'), models.CheckConstraint(condition=models.Q(('payload_hash__regex', '^[0-9a-f]{64}$')), name='acct_delivery_payload_hash_valid')],
            },
        ),
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION standalone_accounting_guard_source_delivery()
                RETURNS trigger LANGUAGE plpgsql AS $$
                BEGIN
                    IF TG_OP = 'DELETE' THEN
                        RAISE EXCEPTION 'Accounting source delivery evidence cannot be deleted.';
                    END IF;
                    IF NEW.book_id <> OLD.book_id
                       OR NEW.source_system <> OLD.source_system
                       OR NEW.source_type <> OLD.source_type
                       OR NEW.source_id <> OLD.source_id
                       OR NEW.source_version <> OLD.source_version
                       OR NEW.schema_version <> OLD.schema_version
                       OR NEW.payload_hash <> OLD.payload_hash
                       OR NEW.created_at <> OLD.created_at THEN
                        RAISE EXCEPTION 'Accounting source delivery identity is immutable.';
                    END IF;
                    IF OLD.status = 'POSTED' AND ROW(NEW.*) IS DISTINCT FROM ROW(OLD.*) THEN
                        RAISE EXCEPTION 'Posted accounting source delivery is immutable.';
                    END IF;
                    RETURN NEW;
                END; $$;
                CREATE TRIGGER standalone_accounting_source_delivery_guard
                BEFORE UPDATE OR DELETE ON standalone_accounting_accountingsourcedelivery
                FOR EACH ROW EXECUTE FUNCTION standalone_accounting_guard_source_delivery();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS standalone_accounting_source_delivery_guard ON standalone_accounting_accountingsourcedelivery;
                DROP FUNCTION IF EXISTS standalone_accounting_guard_source_delivery();
            """,
        ),
    ]
