# Generated by Django 6.0.3 on 2026-08-07 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0005_partyportalaccess'),
        ('standalone_accounting', '0012_sales_receipt_source_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalaccount',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounting_external_accounts', to='party.party'),
        ),
        migrations.AddConstraint(
            model_name='externalaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('party__isnull', False)), fields=('book', 'party', 'purpose'), name='acct_ext_book_party_purpose_uniq'),
        ),
    ]
