"""Canonical Girvi lifecycle vocabulary and compatibility helpers.

The canonical business language is the next-generation lifecycle state set
(`Draft`, `PendingApproval`, `ActiveCurrent`, ...). Some production rows and
legacy flows still persist older status values (`Created`, `Disbursed`, ...).
New query/service code should import this module instead of comparing raw
status strings inline.
"""

LEGACY_DRAFT = "Created"
LEGACY_APPROVED = "Approved"
LEGACY_ACTIVE = "Disbursed"
LEGACY_RELEASED = "Released"
LEGACY_CLOSED = "Closed"
LEGACY_REJECTED = "Rejected"
LEGACY_CANCELLED = "Cancelled"
LEGACY_DEFAULTED = "Defaulted"
LEGACY_AUCTIONED = "Auctioned"
LEGACY_SOLD = "Sold"
LEGACY_REPLEDGED = "Repledged"

CANONICAL_DRAFT = "Draft"
CANONICAL_PENDING_APPROVAL = "PendingApproval"
CANONICAL_APPROVED = "Approved"
CANONICAL_ACTIVE_CURRENT = "ActiveCurrent"
CANONICAL_ACTIVE_OVERDUE = "ActiveOverdue"
CANONICAL_ACTIVE_NPA = "ActiveNPA"
CANONICAL_CLOSURE_PENDING = "ClosurePending"
CANONICAL_RENEWAL_PENDING = "RenewalPending"
CANONICAL_AUCTION_INITIATED = "AuctionInitiated"
CANONICAL_AUCTION_IN_PROGRESS = "AuctionInProgress"
CANONICAL_AUCTION_COMPLETE = "AuctionComplete"
CANONICAL_CLOSED = "Closed"
CANONICAL_RENEWED = "Renewed"
CANONICAL_WRITTEN_OFF = "WrittenOff"
CANONICAL_REJECTED = "Rejected"
CANONICAL_CANCELLED = "Cancelled"

LEGACY_TO_CANONICAL_STATUS = {
    LEGACY_DRAFT: CANONICAL_DRAFT,
    LEGACY_APPROVED: CANONICAL_APPROVED,
    LEGACY_ACTIVE: CANONICAL_ACTIVE_CURRENT,
    LEGACY_RELEASED: CANONICAL_CLOSED,
    LEGACY_CLOSED: CANONICAL_CLOSED,
    LEGACY_REJECTED: CANONICAL_REJECTED,
    LEGACY_CANCELLED: CANONICAL_CANCELLED,
    LEGACY_DEFAULTED: CANONICAL_ACTIVE_NPA,
    LEGACY_AUCTIONED: CANONICAL_AUCTION_COMPLETE,
    LEGACY_SOLD: CANONICAL_AUCTION_COMPLETE,
    LEGACY_REPLEDGED: CANONICAL_RENEWED,
}

CANONICAL_STATUS_VALUES = (
    CANONICAL_DRAFT,
    CANONICAL_PENDING_APPROVAL,
    CANONICAL_APPROVED,
    CANONICAL_ACTIVE_CURRENT,
    CANONICAL_ACTIVE_OVERDUE,
    CANONICAL_ACTIVE_NPA,
    CANONICAL_CLOSURE_PENDING,
    CANONICAL_RENEWAL_PENDING,
    CANONICAL_AUCTION_INITIATED,
    CANONICAL_AUCTION_IN_PROGRESS,
    CANONICAL_AUCTION_COMPLETE,
    CANONICAL_CLOSED,
    CANONICAL_RENEWED,
    CANONICAL_WRITTEN_OFF,
    CANONICAL_REJECTED,
    CANONICAL_CANCELLED,
)

NEXT_GEN_ACTIVE_COMPAT_STATUSES = (
    CANONICAL_DRAFT,
    CANONICAL_PENDING_APPROVAL,
    CANONICAL_ACTIVE_CURRENT,
    CANONICAL_ACTIVE_OVERDUE,
    CANONICAL_ACTIVE_NPA,
    CANONICAL_CLOSURE_PENDING,
    CANONICAL_RENEWAL_PENDING,
)

ACTIVE_LOAN_STATUSES = (
    LEGACY_DRAFT,
    LEGACY_APPROVED,
    LEGACY_ACTIVE,
    *NEXT_GEN_ACTIVE_COMPAT_STATUSES,
)

OVERDUE_LOAN_STATUSES = (
    LEGACY_DEFAULTED,
    LEGACY_AUCTIONED,
    CANONICAL_ACTIVE_OVERDUE,
    CANONICAL_ACTIVE_NPA,
)

V2_CLOSURE_STATUSES = (
    CANONICAL_ACTIVE_CURRENT,
    CANONICAL_ACTIVE_OVERDUE,
    CANONICAL_ACTIVE_NPA,
    CANONICAL_CLOSURE_PENDING,
)

RELEASED_COMPAT_STATUSES = (
    LEGACY_RELEASED,
    LEGACY_CLOSED,
    CANONICAL_CLOSED,
)

UNRELEASED_EXCLUDED_STATUSES = RELEASED_COMPAT_STATUSES

EDITABLE_ITEM_STATUSES = (
    LEGACY_DRAFT,
    CANONICAL_DRAFT,
    CANONICAL_PENDING_APPROVAL,
    LEGACY_APPROVED,
    CANONICAL_APPROVED,
)


def canonical_status(status: str | None) -> str | None:
    """Return the canonical lifecycle value for a legacy or canonical status."""
    if status is None:
        return None
    return LEGACY_TO_CANONICAL_STATUS.get(str(status), str(status))


def is_released_status(status: str | None) -> bool:
    return canonical_status(status) == CANONICAL_CLOSED


def is_active_status(status: str | None) -> bool:
    return canonical_status(status) in {
        CANONICAL_ACTIVE_CURRENT,
        CANONICAL_ACTIVE_OVERDUE,
        CANONICAL_ACTIVE_NPA,
        CANONICAL_CLOSURE_PENDING,
        CANONICAL_RENEWAL_PENDING,
    }
