# Generated by Django 6.0.3 on 2026-08-16 21:47

import colorfield.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('theme', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_companies', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_companies', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='CompanyPreferenceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, db_index=True, default=None, max_length=150, null=True, verbose_name='Section Name')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Name')),
                ('raw_value', models.TextField(blank=True, null=True, verbose_name='Raw Value')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.company')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='orgs.company')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date joined')),
                ('invite_reason', models.CharField(blank=True, max_length=64, verbose_name='Invite reason')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='orgs.company', verbose_name='Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='members',
            field=models.ManyToManyField(through='orgs.Membership', through_fields=('company', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('permissions', models.ManyToManyField(blank=True, to='auth.permission', verbose_name='permissions')),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='orgs.role', verbose_name='Role'),
        ),
        migrations.CreateModel(
            name='CompanyInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False, verbose_name='accepted')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='key')),
                ('sent', models.DateTimeField(null=True, verbose_name='sent')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail address')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('revoked', 'Revoked')], db_index=True, default='pending', max_length=16)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='orgs.company', verbose_name='company')),
                ('inviter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='inviter')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='orgs.role', verbose_name='role')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('LOGIN_FAILED', 'Login Failed'), ('PASSWORD_CHANGE', 'Password Changed'), ('PASSWORD_RESET', 'Password Reset'), ('COMPANY_CREATE', 'Company Created'), ('COMPANY_UPDATE', 'Company Updated'), ('COMPANY_DELETE', 'Company Deleted'), ('COMPANY_RESTORE', 'Company Restored'), ('WORKSPACE_ACCESS', 'Workspace Accessed'), ('TEAM_INVITE', 'Member Invited'), ('TEAM_MEMBER_ADD', 'Member Added'), ('TEAM_MEMBER_REMOVE', 'Member Removed'), ('TEAM_ROLE_CHANGE', 'Member Role Changed'), ('TEAM_INVITE_ACCEPT', 'Invitation Accepted'), ('TEAM_INVITE_DECLINE', 'Invitation Declined'), ('TEAM_INVITE_REVOKE', 'Invitation Revoked'), ('PERMISSION_GRANT', 'Permission Granted'), ('PERMISSION_REVOKE', 'Permission Revoked'), ('PERMISSION_DENIED', 'Permission Denied'), ('UNAUTHORIZED_ACCESS', 'Unauthorized Access Attempt'), ('DATA_CREATE', 'Data Created'), ('DATA_UPDATE', 'Data Updated'), ('DATA_DELETE', 'Data Deleted'), ('DATA_EXPORT', 'Data Exported'), ('DATA_IMPORT', 'Data Imported'), ('BILLING_UPDATE', 'Billing Updated'), ('SUBSCRIPTION_CHANGE', 'Subscription Changed'), ('SUBSCRIPTION_CANCEL', 'Subscription Cancelled'), ('PAYMENT_SUCCESS', 'Payment Successful'), ('PAYMENT_FAILED', 'Payment Failed'), ('SETTINGS_UPDATE', 'Settings Updated'), ('PREFERENCES_UPDATE', 'Preferences Updated'), ('PARTY_PORTAL_ACCESS_ACTIVATE', 'Party Portal Access Activated'), ('PARTY_PORTAL_ACCESS_SUSPEND', 'Party Portal Access Suspended'), ('PARTY_PORTAL_ACCESS_REVOKE', 'Party Portal Access Revoked'), ('OWNERSHIP_TRANSFER', 'Ownership Transferred')], db_index=True, max_length=50, verbose_name='Action')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Timestamp')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Object ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True, verbose_name='User Agent')),
                ('description', models.TextField(blank=True, help_text='Human-readable description of the action', verbose_name='Description')),
                ('data', models.JSONField(blank=True, default=dict, help_text='JSON data with additional context', verbose_name='Additional Data')),
                ('success', models.BooleanField(default=True, help_text='Whether the action was successful', verbose_name='Success')),
                ('error_message', models.TextField(blank=True, help_text='Error message if action failed', verbose_name='Error Message')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('company', models.ForeignKey(blank=True, help_text='Company context for the action', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='orgs.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='orgs_auditl_user_id_c0d068_idx'), models.Index(fields=['company', '-timestamp'], name='orgs_auditl_company_ba4ab8_idx'), models.Index(fields=['action', '-timestamp'], name='orgs_auditl_action_f84764_idx'), models.Index(fields=['-timestamp'], name='orgs_auditl_timesta_647b3b_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompanyOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.company', verbose_name='Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'company'), name='orgs_companyownership_unique_user_company')],
            },
        ),
        migrations.CreateModel(
            name='PendingInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail address')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_invitations', to='orgs.company', verbose_name='company')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_invitations', to='orgs.role', verbose_name='role')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('email', 'company'), name='orgs_pendinginvitation_unique_email_company')],
            },
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'company'), name='orgs_membership_unique_user_company'),
        ),
        migrations.AddConstraint(
            model_name='companyinvitation',
            constraint=models.UniqueConstraint(fields=('email', 'company'), name='orgs_companyinvitation_unique_email_company'),
        ),
    ]
