# Generated by Django 5.0.1 on 2024-02-17 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0004_companyinvitation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="orgs.role",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="company",
            unique_together={("name", "owner")},
        ),
    ]
