# Generated by Django 6.0.3 on 2026-09-09 08:51

import django.db.models.deletion
from django.db import migrations, models


from apps.tenancy.rls import EnableWorkspaceRLS

DEFAULTS = {'Owner': ['loan_approve', 'loan_disburse', 'loan_repay', 'loan_release', 'loan_accrue', 'loan_capitalize', 'workspace_view', 'workspace_list', 'workspace_edit', 'workspace_settings', 'workspace_delete', 'workspace_archive', 'workspace_transfer', 'team_view', 'team_list', 'team_invite', 'team_invite_admin', 'team_edit', 'team_remove', 'team_change_role', 'team_view_activity', 'data_view', 'data_view_own', 'data_create', 'data_edit', 'data_edit_own', 'data_delete', 'data_delete_own', 'data_export', 'data_export_bulk', 'data_import', 'billing_view', 'billing_history', 'billing_edit', 'billing_manage', 'billing_cancel', 'report_view', 'report_view_basic', 'report_create', 'report_export', 'report_schedule', 'contact_view', 'contact_create', 'contact_edit', 'contact_delete', 'contact_import', 'contact_export'], 'Admin': ['loan_approve', 'loan_disburse', 'loan_repay', 'loan_release', 'loan_accrue', 'loan_capitalize', 'workspace_view', 'workspace_list', 'workspace_edit', 'workspace_settings', 'team_view', 'team_list', 'team_invite', 'team_edit', 'team_remove', 'team_change_role', 'data_view', 'data_view_own', 'data_create', 'data_edit', 'data_edit_own', 'data_delete', 'data_delete_own', 'data_export', 'data_export_bulk', 'data_import', 'billing_view', 'billing_history', 'report_view', 'report_view_basic', 'report_create', 'report_export', 'report_schedule', 'contact_view', 'contact_create', 'contact_edit', 'contact_delete', 'contact_import', 'contact_export'], 'Member': ['workspace_view', 'workspace_list', 'team_view', 'team_list', 'data_view', 'data_view_own', 'data_create', 'data_edit', 'data_edit_own', 'data_delete_own', 'report_view', 'report_view_basic', 'report_export', 'contact_view', 'contact_create', 'contact_edit'], 'Viewer': ['workspace_view', 'workspace_list', 'team_view', 'team_list', 'data_view', 'data_view_own', 'report_view', 'report_view_basic', 'contact_view']}
CATALOG = ['workspace_view', 'workspace_list', 'workspace_edit', 'workspace_settings', 'workspace_delete', 'workspace_archive', 'workspace_transfer', 'team_view', 'team_list', 'team_invite', 'team_invite_admin', 'team_edit', 'team_remove', 'team_change_role', 'team_view_activity', 'data_view', 'data_view_own', 'data_create', 'data_edit', 'data_edit_own', 'data_delete', 'data_delete_own', 'data_export', 'data_export_bulk', 'data_import', 'billing_view', 'billing_history', 'billing_edit', 'billing_manage', 'billing_cancel', 'report_view', 'report_view_basic', 'report_create', 'report_export', 'report_schedule', 'contact_view', 'contact_create', 'contact_edit', 'contact_delete', 'contact_import', 'contact_export', 'loan_repay', 'loan_release', 'loan_accrue', 'loan_capitalize', 'loan_approve', 'loan_disburse']


def copy_workspace_grants(apps, schema_editor):
    Company = apps.get_model("orgs", "Company")
    Role = apps.get_model("orgs", "Role")
    Local = apps.get_model("orgs", "WorkspaceRole")
    Grant = apps.get_model("orgs", "WorkspaceRoleGrant")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")
    Membership = apps.get_model("orgs", "Membership")
    Invitation = apps.get_model("orgs", "CompanyInvitation")
    ct, _ = ContentType.objects.get_or_create(app_label="orgs", model="company")
    permissions = {code: Permission.objects.get_or_create(content_type=ct, codename=code,
                    defaults={"name": code})[0] for code in CATALOG}
    # Development seed scripts may have inserted explicit role IDs.
    schema_editor.execute("SELECT setval(pg_get_serial_sequence('orgs_role', 'id'), COALESCE((SELECT MAX(id) FROM orgs_role), 1), EXISTS(SELECT 1 FROM orgs_role))")
    for name in DEFAULTS:
        Role.objects.get_or_create(name=name)
    for workspace in Company._base_manager.all().iterator():
        referenced = set(Membership.objects.filter(company_id=workspace.pk).values_list("role_id", flat=True))
        referenced.update(Invitation.objects.filter(company_id=workspace.pk).values_list("role_id", flat=True))
        for role in Role.objects.all():
            if role.name not in DEFAULTS and role.pk not in referenced:
                continue
            local = Local.objects.create(workspace_id=workspace.pk, role_id=role.pk)
            codes = (set(DEFAULTS.get(role.name, [])) |
                     set(role.permissions.values_list("codename", flat=True))) & set(CATALOG)
            Grant.objects.bulk_create([Grant(workspace_id=workspace.pk, workspace_role_id=local.pk,
                permission_id=permissions[c].pk) for c in sorted(codes)])
    # Experimental-development cleanup: retired app codes are not live grants.
    for prefix in ("girvi_", "dea_", "accounting_"):
        Permission.objects.filter(codename__startswith=prefix).delete()
    # Existing invitations have no verified grant snapshot. Reissue pending ones.
    Invitation.objects.filter(status="pending", accepted=False).update(status="revoked")


GRANT_SCOPE_SQL = """
CREATE FUNCTION orgs_role_grant_scope_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM orgs_workspacerole
                 WHERE id = NEW.workspace_role_id AND workspace_id = NEW.workspace_id) THEN
    RAISE EXCEPTION 'Role grant workspace mismatch' USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END; $$;
CREATE TRIGGER orgs_role_grant_scope BEFORE INSERT OR UPDATE ON orgs_workspacerolegrant
FOR EACH ROW EXECUTE FUNCTION orgs_role_grant_scope_guard();
"""


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('orgs', '0007_loan_operational_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinvitation',
            name='role_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='WorkspaceRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField(default=1)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workspace_roles', to='orgs.role')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local_roles', to='orgs.company')),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceRoleGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.permission')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company')),
                ('workspace_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='orgs.workspacerole')),
            ],
        ),
        migrations.AddConstraint(
            model_name='workspacerole',
            constraint=models.UniqueConstraint(fields=('workspace', 'role'), name='orgs_workspace_role_unique'),
        ),
        migrations.AddConstraint(
            model_name='workspacerolegrant',
            constraint=models.UniqueConstraint(fields=('workspace_role', 'permission'), name='orgs_workspace_role_grant_unique'),
        ),
        migrations.RunPython(copy_workspace_grants, migrations.RunPython.noop),
        EnableWorkspaceRLS("WorkspaceRole"),
        EnableWorkspaceRLS("WorkspaceRoleGrant"),
        migrations.RunSQL(GRANT_SCOPE_SQL, "DROP TRIGGER orgs_role_grant_scope ON orgs_workspacerolegrant; DROP FUNCTION orgs_role_grant_scope_guard();"),
    ]
