# Generated by Django 5.0.1 on 2024-02-25 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0009_alter_company_options_alter_role_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyPreferenceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        max_length=150,
                        null=True,
                        verbose_name="Section Name",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=150, verbose_name="Name"
                    ),
                ),
                (
                    "raw_value",
                    models.TextField(blank=True, null=True, verbose_name="Raw Value"),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orgs.company"
                    ),
                ),
            ],
        ),
    ]
