# Generated by Django 6.1.1 on 2026-09-29 18:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
from apps.tenancy.rls import EnableWorkspaceRLS


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0009_workspace_role_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageInventoryRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(null=True)),
                ('state', models.CharField(choices=[('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='running', max_length=12)),
                ('scope', models.CharField(max_length=500)),
                ('totals', models.JSONField(default=dict)),
                ('coverage', models.JSONField(default=dict)),
                ('failure_code', models.CharField(blank=True, max_length=80)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-started_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='StorageInventoryObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=1024)),
                ('key_digest', models.CharField(max_length=64)),
                ('byte_size', models.PositiveBigIntegerField(default=0)),
                ('modified_at', models.DateTimeField(null=True)),
                ('state', models.CharField(max_length=24)),
                ('category', models.CharField(max_length=40)),
                ('workspace_count', models.PositiveIntegerField(default=0)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_objects', to='orgs.storageinventoryrun')),
            ],
            options={
                'indexes': [models.Index(fields=['run', 'state', 'id'], name='storage_review_page_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'key_digest'), name='storage_run_object_unique')],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceStorageUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totals', models.JSONField(default=dict)),
                ('categories', models.JSONField(default=list)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orgs.storageinventoryrun')),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.company')),
            ],
            options={
                'ordering': ('-run_id',),
                'constraints': [models.UniqueConstraint(fields=('workspace', 'run'), name='storage_workspace_run_unique')],
            },
        ),
        EnableWorkspaceRLS("WorkspaceStorageUsage"),
    ]
