# Generated by Django 5.0.1 on 2024-03-03 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0010_companypreferencemodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyinvitation",
            name="role",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="orgs.role",
                verbose_name="role",
            ),
            preserve_default=False,
        ),
    ]
