# Generated by Django 5.0.1 on 2024-03-09 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("orgs", "0011_companyinvitation_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyinvitation",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="orgs.company",
                verbose_name="company",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="orgs.company",
                verbose_name="Company",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="date_joined",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date joined"),
        ),
        migrations.AlterField(
            model_name="membership",
            name="invite_reason",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="Invite reason"
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="orgs.role",
                verbose_name="Role",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(
                blank=True, to="auth.permission", verbose_name="permissions"
            ),
        ),
    ]
