# Generated by Django 5.0.1 on 2024-08-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0012_alter_companyinvitation_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyinvitation",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="e-mail address"),
        ),
        migrations.AlterUniqueTogether(
            name="companyinvitation",
            unique_together={("email", "company")},
        ),
    ]
