# Generated by Django 5.0.8 on 2024-10-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0014_company_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="company_logos/"),
        ),
    ]
