# Generated by Django 5.1.2 on 2024-12-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0016_pendinginvitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
