# Generated by Django 5.1.7 on 2025-03-29 04:29

from django.db import migrations


def create_default_roles(apps, schema_editor):
    Role = apps.get_model("orgs", "Role")
    default_roles = [
        {"id": 1, "name": "Owner"},
        {"id": 2, "name": "Admin"},
        {"id": 3, "name": "Member"},
        {"id": 4, "name": "Customer"},
    ]

    for role_data in default_roles:
        Role.objects.create(**role_data)


def remove_default_roles(apps, schema_editor):
    Role = apps.get_model("orgs", "Role")
    Role.objects.filter(id__in=[1, 2, 3, 4]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0017_company_is_deleted"),
    ]

    operations = [
        migrations.RunPython(create_default_roles, reverse_code=remove_default_roles),
    ]
