# Generated by Django 5.2.6 on 2025-09-26 12:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0018_create_default_roles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="members",
            field=models.ManyToManyField(
                through="orgs.Membership",
                through_fields=("company", "user"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
