# Generated by Django 5.2.6 on 2026-02-27 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("orgs", "0019_alter_company_members"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN", "User Login"),
                            ("LOGOUT", "User Logout"),
                            ("LOGIN_FAILED", "Login Failed"),
                            ("PASSWORD_CHANGE", "Password Changed"),
                            ("PASSWORD_RESET", "Password Reset"),
                            ("COMPANY_CREATE", "Company Created"),
                            ("COMPANY_UPDATE", "Company Updated"),
                            ("COMPANY_DELETE", "Company Deleted"),
                            ("COMPANY_RESTORE", "Company Restored"),
                            ("WORKSPACE_ACCESS", "Workspace Accessed"),
                            ("MEMBER_INVITE", "Member Invited"),
                            ("MEMBER_JOIN", "Member Joined"),
                            ("MEMBER_REMOVE", "Member Removed"),
                            ("MEMBER_ROLE_CHANGE", "Member Role Changed"),
                            ("PERMISSION_GRANT", "Permission Granted"),
                            ("PERMISSION_REVOKE", "Permission Revoked"),
                            ("PERMISSION_DENIED", "Permission Denied"),
                            ("UNAUTHORIZED_ACCESS", "Unauthorized Access Attempt"),
                            ("DATA_CREATE", "Data Created"),
                            ("DATA_UPDATE", "Data Updated"),
                            ("DATA_DELETE", "Data Deleted"),
                            ("DATA_EXPORT", "Data Exported"),
                            ("DATA_IMPORT", "Data Imported"),
                            ("BILLING_UPDATE", "Billing Updated"),
                            ("SUBSCRIPTION_CHANGE", "Subscription Changed"),
                            ("SUBSCRIPTION_CANCEL", "Subscription Cancelled"),
                            ("PAYMENT_SUCCESS", "Payment Successful"),
                            ("PAYMENT_FAILED", "Payment Failed"),
                            ("SETTINGS_UPDATE", "Settings Updated"),
                            ("PREFERENCES_UPDATE", "Preferences Updated"),
                            ("OWNERSHIP_TRANSFER", "Ownership Transferred"),
                        ],
                        db_index=True,
                        max_length=50,
                        verbose_name="Action",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Timestamp"
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Object ID"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="User Agent"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable description of the action",
                        verbose_name="Description",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON data with additional context",
                        verbose_name="Additional Data",
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the action was successful",
                        verbose_name="Success",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if action failed",
                        verbose_name="Error Message",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Company context for the action",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="orgs.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Content Type",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="orgs_auditl_user_id_c0d068_idx",
                    ),
                    models.Index(
                        fields=["company", "-timestamp"],
                        name="orgs_auditl_company_ba4ab8_idx",
                    ),
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="orgs_auditl_action_f84764_idx",
                    ),
                    models.Index(
                        fields=["-timestamp"], name="orgs_auditl_timesta_647b3b_idx"
                    ),
                ],
            },
        ),
    ]
