# Generated by Django 5.0.14 on 2026-03-28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0020_auditlog"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pendinginvitation",
            unique_together={("email", "company")},
        ),
    ]
