# Generated by Django 6.0.3 on 2026-05-01 18:06

from django.db import migrations, models


def backfill_invitation_status(apps, schema_editor):
    CompanyInvitation = apps.get_model("orgs", "CompanyInvitation")

    CompanyInvitation.objects.filter(accepted=True).update(
        status="accepted",
        responded_at=models.F("sent"),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0021_pendinginvitation_unique_email_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinvitation',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyinvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('revoked', 'Revoked')], db_index=True, default='pending', max_length=16),
        ),
        migrations.RunPython(backfill_invitation_status, migrations.RunPython.noop),
    ]
