# Generated by Django 6.0.3 on 2026-08-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0024_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='schema_name',
            field=models.CharField(db_index=True, max_length=63, unique=True),
        ),
    ]
